### ISSUE TITLE
Changing property type

### ISSUE THREAD

**Issue by theunforgiven89** [SemanticMediaWiki/SemanticMediaWiki#1008]
Hi all.

I've been having this major issue for quite some time now.

Ever since I updated my MediaWiki and Semantic MediaWiki to versions 1.24.1 and 2.1.1 respectively, I haven't been able to change the type of any of my properties (e.g. Property:Website...[[Has type::URL]]). When I try to do that, my page goes blank. When I refresh, it shows the change has been made, but it doesn't seem to take effect at all.

I must've tried every possible solution and run every possible maintenance script, but nothing seems to work.

Any idea on how to get this problem fixed?

Thanks in advance!

**Comment by mwjames** [comment]
>  When I try to do that, my page goes blank

This sounds odd, you might want to add this to your `LocalSettings.php` and try change a type again and see if instead of a blank screen you receive a failure or exception output.

```php
error_reporting(E_STRICT|E_ALL);
ini_set("display_errors", 1);
$wgShowExceptionDetails = true;
$wgDevelopmentWarnings = false;
$wgShowSQLErrors = true;
$wgDebugDumpSql  = false;
$wgShowDBErrorBacktrace = true;
```

**Comment by theunforgiven89** [comment]
Hi mwjames,

Thank you for your help. I managed to get this problem fix by running "Data repair and upgrade" in the "Admin functions for Semantic MediaWiki".
