### ISSUE TITLE
Improve wiki documentation of the API

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1015]
The [respective wiki page](https://semantic-mediawiki.org/wiki/Ask_API) started out small with just two modules. Over the time more coolness was added which increased the uncoolness of the documentation I was doing. This should help remind me of unmessing this mess I created.

**Comment by JeroenDeDauw** [comment]
It's hardly you that created the mess ;)

**Comment by kghbln** [comment]
Not sure. I guess I am the usual suspect here. Was a bit grumpy when I wrote this. :|

**Comment by JeroenDeDauw** [comment]
![grumpy](https://cloud.githubusercontent.com/assets/146040/7657491/83cc95c4-fb32-11e4-83a3-fa3a5581da08.png)

**Comment by kghbln** [comment]
Grumpybunny! :)

**Comment by kghbln** [comment]
It was a little tour de force with some tweaks to come tomorrow but basically this is [done now](https://www.semantic-mediawiki.org/wiki/Help:API). Took too long.
