### ISSUE TITLE
Add "improper value for" statistics to "Special:SemanticStatistics"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1016]
This is basically a follow-up to pull request https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/893 I think these statistics should also go on this special page.

**Comment by mwjames** [comment]
I'd expect `Special:SemanticStatistics` to be removed with 3.0 / #1014

**Comment by kghbln** [comment]
Fair enough. :)
