### ISSUE TITLE
Move includes/parserhooks to src/

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1020]
`src/ParserHooks` or `src/MediaWiki/ParserHooks`?

Ping @mwjames

**Comment by mwjames** [comment]
Well, I thought about this but I'm not sure because `ParserHooks` is MediaWiki (with the `{{#...}}` syntax) but what does fit better for SMW in this regards?
-  `SMW\MediaWiki\ParserHooks\AskParserFunction` or
- `SMW\ParserHooks\AskParserFunction`

**Comment by JeroenDeDauw** [comment]
Parser hooks are a MediaWiki specific thing. Perhaps more importantly, they are a presentation specific thing, which naturally ends up being MediaWiki in our case.

**Comment by mwjames** [comment]
Done with #2136.
