### ISSUE TITLE
option to switch off internationalization in #ask

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1032]
for import/export and other features it would be useful to make sure that the results of ask are given in a generic/international format.

Currently the results are converted e.g. boolean true/false values are reported as wahr/falsch - Namespaces are translated e.g. Concept:x is translated to Konzept:y  - dates are shown in the current locale. 

While this is all useful for the User Interface it is quite annoying for writing scripts and automating things. It would be great to have an option for ask which gives generic results e.g. 
boolean as true/false
namespaces in english
dates in ISO format

and so on...

http://semantic-mediawiki.org/wiki/Help:List_of_datatypes#Example_Values_and_Formatting
shows that #- does not consistently work at this time e.g.
for Records, URLs there is still links active. And for telephone something strange happens (which might be a bug in itself)

I'd suggest to add a new #raw option to get the result of a true generic non formatted output.

**Comment by Hans-Oleander** [comment]
dates in ISO format should already work by now, this way:
https://semantic-mediawiki.org/wiki/Help:Displaying_information#Date

**Comment by WolfgangFahl** [comment]
A related issues is that the namespace canonical value is not canonical see: 
http://www.grazwiki.at/api.php?action=query&meta=siteinfo&siprop=|namespaces
- the canonical value for the Concept namespace should be "Concept" not "Konzept"

**Comment by mwjames** [comment]
When citing sources as above `http://www.grazwiki.at`, please be sure it corresponds to a current release and not to a no longer maintained Semantic MediaWiki (Version 1.8.0.5) as in case of [0] .

[0] http://www.grazwiki.at/Spezial:Version

**Comment by mwjames** [comment]
@kghbln Any idea whether the mixed language/canonical form is still an issue or not?

**Comment by mwjames** [comment]
Canonical namespace related  classes/functions  are:
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/HookRegistry.php#L356
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/NamespaceManager.php

**Comment by WolfgangFahl** [comment]
My own wiki is 2.1 and has the issue. Since it's on an intranet I could not use the link above. But here is the api call result for it:
<?xml version="1.0"?>
<api>
  <warnings>
    <siteinfo xml:space="preserve">Unrecognized value for parameter 'siprop': </siteinfo>
  </warnings>
  <query>
    <namespaces>
      <ns id="-2" case="first-letter" canonical="Media" xml:space="preserve">Medium</ns>
      <ns id="-1" case="first-letter" canonical="Special" xml:space="preserve">Spezial</ns>
      <ns id="0" case="first-letter" content="" xml:space="preserve" />
      <ns id="1" case="first-letter" subpages="" canonical="Talk" xml:space="preserve">Diskussion</ns>
      <ns id="2" case="first-letter" subpages="" canonical="User" xml:space="preserve">Benutzer</ns>
      <ns id="3" case="first-letter" subpages="" canonical="User talk" xml:space="preserve">Benutzer Diskussion</ns>
      <ns id="4" case="first-letter" subpages="" canonical="Project" xml:space="preserve">BITPlanWiki</ns>
      <ns id="5" case="first-letter" subpages="" canonical="Project talk" xml:space="preserve">BITPlanWiki Diskussion</ns>
      <ns id="6" case="first-letter" canonical="File" xml:space="preserve">Datei</ns>
      <ns id="7" case="first-letter" subpages="" canonical="File talk" xml:space="preserve">Datei Diskussion</ns>
      <ns id="8" case="first-letter" subpages="" canonical="MediaWiki" xml:space="preserve">MediaWiki</ns>
      <ns id="9" case="first-letter" subpages="" canonical="MediaWiki talk" xml:space="preserve">MediaWiki Diskussion</ns>
      <ns id="10" case="first-letter" canonical="Template" xml:space="preserve">Vorlage</ns>
      <ns id="11" case="first-letter" subpages="" canonical="Template talk" xml:space="preserve">Vorlage Diskussion</ns>
      <ns id="12" case="first-letter" subpages="" canonical="Help" xml:space="preserve">Hilfe</ns>
      <ns id="13" case="first-letter" subpages="" canonical="Help talk" xml:space="preserve">Hilfe Diskussion</ns>
      <ns id="14" case="first-letter" canonical="Category" xml:space="preserve">Kategorie</ns>
      <ns id="15" case="first-letter" subpages="" canonical="Category talk" xml:space="preserve">Kategorie Diskussion</ns>
      <ns id="102" case="first-letter" canonical="Attribut" xml:space="preserve">Attribut</ns>
      <ns id="103" case="first-letter" subpages="" canonical="Attribut Diskussion" xml:space="preserve">Attribut Diskussion</ns>
      <ns id="104" case="first-letter" canonical="Type" xml:space="preserve">Type</ns>
      <ns id="105" case="first-letter" subpages="" canonical="Type talk" xml:space="preserve">Type talk</ns>
      <ns id="106" case="first-letter" canonical="Form" xml:space="preserve">Formular</ns>
      <ns id="107" case="first-letter" subpages="" canonical="Form talk" xml:space="preserve">Formular Diskussion</ns>
      <ns id="108" case="first-letter" canonical="Konzept" xml:space="preserve">Konzept</ns>
      <ns id="109" case="first-letter" subpages="" canonical="Konzept Diskussion" xml:space="preserve">Konzept Diskussion</ns>
      <ns id="170" case="first-letter" canonical="Filter" xml:space="preserve">Filter</ns>
      <ns id="171" case="first-letter" subpages="" canonical="Filter Diskussion" xml:space="preserve">Filter Diskussion</ns>
    </namespaces>
  </query>
</api>

**Comment by mwjames** [comment]
> My own wiki is 2.1 and has the issue.

Fair enough but since it has a low priority on my list, maybe @kghbln can help with this issue to find out the cause.

PS: It works for me

![image](https://cloud.githubusercontent.com/assets/1245473/7800213/617a63ba-0312-11e5-8b1f-0c1104a9c581.png)

**Comment by WolfgangFahl** [comment]
@mwjames: In any case the specially handled namespaces, property, type and concept are the culprit. In your chinese example these are in english instead of i18n. So the issue here is the other way round but otherwise also not what one would expect. The expected result IMHO should be canonical=english and node value= translated localized namespace description.

**Comment by kghbln** [comment]
With custom namespaces even [MediaWiki core fails:](https://de.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=|namespaces) 

```text
            "101": {
                "id": 101,
                "case": "first-letter",
                "subpages": "",
                "canonical": "Portal Diskussion",
                "*": "Portal Diskussion"
```
However there seems to be a way for extensions to define English as canonical and at the same time provide I18n as the example shows:

```text
            "828": {
                "id": 828,
                "case": "first-letter",
                "subpages": "",
                "canonical": "Module",
                "*": "Modul"
            },
```

**Comment by mwjames** [comment]
> handled namespaces, property, type and concept are the culprit. In your chinese example these are in english instead of i18n.

Namespaces require a special content language translation and are displayed in the selected content language.

[0] https://www.semantic-mediawiki.org/wiki/Content,_page_and_user_language
