### ISSUE TITLE
uploadable Namespace handling

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1036]
This issue is also posted as a question at
http://stackoverflow.com/questions/30374660/uploadable-namespace-handling

The following links and text snippets describe and reference the "uploadable" parameter for field in SMW Forms (hope this is the right issue tracker for this)

Specifies that a link should be placed next to this field, that opens a popup window to let the user upload a file; see "Uploading files", below. See

https://www.mediawiki.org/wiki/Extension:Semantic_Forms/Defining_forms#.27field.27_tag
https://www.mediawiki.org/wiki/Extension:Semantic_Forms/Defining_forms#Uploading_files

The type of the target property seems  to have to be Page for this to work, there is no special standard datatype for images in:

https://semantic-mediawiki.org/wiki/Help:List_of_datatypes

There are explanations in how this works at:

http://smw.referata.com/wiki/Using_Semantic_Forms_for_file_pages_and_uploads
http://discoursedb.org/wiki/Form:Images_test
http://discoursedb.org/wiki/Special:FormEdit/Images_test/ImageTest

and there has been a discussion how to handle the "File:" namespace prefix:
http://semediawiki-devel.narkive.com/gm7hJMBE/smw-devel-sf-turning-uploadable-into-input-type-upload

Now I assume that at this point the "File:" part is not handled by the uploadable flag (at least not by default). 

It would be great to have solution (or if one exists a proper documentation pointer to it) that allows the File: prefix to be added automatically so that the full page description File:someImage is available as the result of "uploadable".

**Comment by mwjames** [comment]
> The following links and text snippets describe and reference the "uploadable" parameter for field in SMW Forms (hope this is the right issue tracker for this)

This is the wrong forum for questions relating to SF. Please have  look at the extension's homepage for further assistance.
