### ISSUE TITLE
type telephone number / querying for plain output from within a table

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1037]
Setup: MW 1.23.9, SMW 2.3 alpha, PHP 5.4.39, MySQL 5.5.43

When querying for a plain output of a property of type telephone number from within a table cell like

```text
{| class='wikitable'
! Example value
! Query display using #- (plain)
|-
| [[Telephone number::+1-800-225-5288]]
| {{#show: {{FULLPAGENAME}} | ?Telephone number#- }}
|}
```
the result gets added within `<caption>` tags to the top of the table rather than within the table cell containing the query. Doing `{{#ask: [[{{FULLPAGENAME}}]] |?Telephone number#- |mainlabel=- |headers=hide }}` causes the same behaviour.

See also a live example on a [different wiki](https://semantic-mediawiki.org/wiki/Help:List_of_datatypes).

**Comment by mwjames** [comment]
I just tried/copied the example from above but I cannot replicate the issue (SMW 2.3 / MW 1.24.2 / PHP 5.6.8).I have no idea where "result gets added within` <caption>` tags" is coming from.

![image](https://cloud.githubusercontent.com/assets/1245473/7783788/eb47b680-014e-11e5-897f-d44e2546e2ed.png)

**Comment by kghbln** [comment]
Addmittedly I formatted the query a bit here at GitHub to make in not appear as lazy as on wiki and did not test the result. However this uncovered the reason for the issue. Notice the difference in the cell containing the query:

```text
{| class='wikitable'
! Example value
! Query display using #- (plain)
|-
| [[Telephone number::+1-800-225-5288]]
|{{#show: {{FULLPAGENAME}} | ?Telephone number#- }}
|}
```
It is the space I [inserted](https://semantic-mediawiki.org/w/index.php?title=Help%3AList_of_datatypes&action=historysubmit&diff=39424&oldid=39423) which solved the issue.

**Comment by mwjames** [comment]
`|{{#show: {{FULLPAGENAME}} | ?Telephone number#- }}` vs `| {{#show: {{FULLPAGENAME}} | ?Telephone number#- }}`

Parsing of `|{{` is handled by MW and not by SMW whether this occurs in other occasions needs to be checked.

**Comment by kghbln** [comment]
I just wonder why this apparently only happens for type "telephone number". However this is an invalid one here.
