### ISSUE TITLE
Comparators and multi-valued properties

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1043]
Re: 

> If a datatype has no natural linear ordering, Semantic MediaWiki will just apply the alphabetical order to the normalised datavalues as they are used in the RDF export. You can thus use greater than and less than to select alphabetic ranges of a string property. For example, you could ask [[surname::>Do]] [[surname::<G]] to select surnames between «Do» and up to «G». For wiki pages, the comparator refers to the name of the given page (without the namespace prefix). 

(from the docs)

I've found that queries of the type "[[surname::>Do]] [[surname::<G]]" don't always produce the results you would expect as they can also include results that fall outside this range. 

It's a stab in the dark, but perhaps one reason for this anomaly is that queries using these comparators might not cater for multi-valued properties. So if a given page contains more than one value for "Property:surname" above, say «Carr» and «Herbert», the query for the range Do-G takes an average of those surnames and includes the page all the same.

**Comment by JeroenDeDauw** [comment]
If your query is `[[surname::>Do]] [[surname::<G]]`, then keep in mind that you'll get all pages with at least one surname `>Do` and all those with with at least one surname `<G`. These conditions are not about the same surname. I'm not sure if you can express a conjunction for a single value with this wikitext syntaxt.

**Comment by JeroenDeDauw** [comment]
Something in this direction probably:

`[[surname::<q>[[nyan::>Do]] [[nyan::<G]]</q>]]`

Where `nyan` should be replaced by the thing selecting the value itself.

**Comment by Contrafibularity** [comment]
Thanks for the explanation! I would have expected that at least one of the surnames should fall within the Do-G range, but I wasn't aware that the two constraints ">Do" and "<G" do not necessarily apply to the same surname - at least not when there's multiple values for a single property. 

That syntax didn't work for me (four error messages: no subqueries allowed; some parts [nowiki tags] of the query was not understood; etc.).

**Comment by JeroenDeDauw** [comment]
@mkroetzsch are conjunctions for a single value possible?

**Comment by mkroetzsch** [comment]
@JeroenDeDauw The object model for queries supports conjunctions of conditions for a single value, and it is possible that the SQL implementation also treats these correctly, but I don't recall any syntax for getting this. Your idea about the single values would be sensible but I don't think this was ever implemented. In particular, there are no queries that return values that are not pages (which would be possible if the subquery you gave would be a legal query).

A related syntax that does work is the use of "||" in values to express "OR". This can also be combined with comparators. For example, you can do ```[[Date::>2009||<2015]]```. Of course, this is not addressing your problem, but it might show how to extend the query syntax without too much effort: one could just support "&&" in addition to "||" in such expressions.

**Comment by JeroenDeDauw** [comment]
@mkroetzsch thanks for explaining!

@Contrafibularity perhaps create a feature request for having this supported? `[[surname::>Do&&<G]]`

@kghbln perhaps we can improve the docs to clarify that conjunctions do not act on a single value when there are multiple ones

**Comment by kghbln** [comment]
Ok I was up here and did not notice before. Now [added](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASearch_operators&type=revision&diff=64558&oldid=64026) to the wiki. Everything else from this was done, thus closing.
