### ISSUE TITLE
Feature request: Allow inverse properties of type "Text".

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1044]
The subject title says it all, but the need for this feature may also be explained using a simple example. Say you have many pages that use multiple properties of type "Text". Now you want users to be able to crawl through an alphabetically arranged list of unique property values and use it to get results for tagged pages. The biggest obstacle standing in the way of this is that we can't have inverse referencing for properties other than those of type "Page". 

Cf. http://wikimedia.7.x6.nabble.com/Status-of-retrieving-unique-values-from-a-property-td5030153.html

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
