### ISSUE TITLE
Feature request: parameter for custom collation algorithm in query

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1045]
I'm not sure if this is even possible (although the Collation::factory hook allows for extra collations to be added by extensions). But surely it would be great if sorting in queries could be further customised using a parameter that allows editors to change the default algorithm for categories. 

This could be an important thing to have, in part also because the use of multiple languages on a single website is being taken more seriously these days.

**Comment by mwjames** [comment]
I expect this to be addressed with #2429 (3.0.x)
