### ISSUE TITLE
Clean up issue tracking

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#105]
We have not been doing that well of a job of keeping on top of all the reported SMW issues on bugzilla. There are many issues there that are not prioritized in a meaningful way and are not categorized in any way. Furthermore a good chunk are very old issues that no one has looked at for a long time, and are perhaps no longer relevant.

We have now been trying our the issue tracking here on GitHub, which is working well, and seems to have many advantages over bugzilla. I suggest we stick with it, and drop our support for bugzilla. Meaning that we point people here rather than to bugzilla, and move over old bugs of interest on an as-needed basis.

This means we need to update the documentation explaining where and how to report bugs.

**Comment by JeroenDeDauw** [comment]
Open tasks on Phabricator: https://phabricator.wikimedia.org/maniphest/?statuses=open%2Cstalled&allProjects=PHID-PROJ-45zxvka3on5j63qsxuaa#R

@kghbln @mwjames any idea of what the state of this issue is?

**Comment by kghbln** [comment]
In the meantime we have had two or three clean up efforts. In case an old issue from Bugzilla, Phabricator is dealt with we cross-referenced them for better follow up. Some issues were even transferred to here at one point. Also the issue tracking here has not stabilized. So ...
