### ISSUE TITLE
Concepts / ConceptDescriptionInterpreter fails with undefined method SMW\DIWikiPage::getText

### ISSUE THREAD

**Issue by chironimow** [SemanticMediaWiki/SemanticMediaWiki#1050]
I have upgraded my system from MW1.16 SMW 1.6.2 to MW1.25 and SMW2.2

Since then pages including concepts are failing directly:

( ! ) Fatal error: Call to undefined method SMW\DIWikiPage::getText() in /home/innowiki/wikifarm/latest/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Interpreter/ConceptDescriptionInterpreter.php on line 112
Call Stack
#	Time	Memory	Function	Location
1	0.0000	234160	{main}( )	../index.php:0
2	0.0282	4760520	MediaWiki->run( )	../index.php:41
3	0.0282	4762088	MediaWiki->main( )	../MediaWiki.php:414
4	0.0355	5114136	MediaWiki->performRequest( )	../MediaWiki.php:566
5	0.0371	5234672	MediaWiki->performAction( )	../MediaWiki.php:273
6	0.0372	5234904	ViewAction->show( )	../MediaWiki.php:395
7	0.0372	5237264	Article->view( )	../ViewAction.php:44
8	0.0577	6691872	PoolCounterWork->execute( )	../Article.php:674
9	0.0578	6717216	PoolWorkArticleView->doWork( )	../PoolCounterWork.php:123
10	0.0578	6717624	AbstractContent->getParserOutput( )	../PoolWorkArticleView.php:140
11	0.0579	6719136	WikitextContent->fillParserOutput( )	../AbstractContent.php:497
12	0.0579	6721336	Parser->parse( )	../WikitextContent.php:333
13	0.0582	6734656	Parser->internalParse( )	../Parser.php:434
14	0.0583	6738208	Parser->replaceVariables( )	../Parser.php:1231
15	0.0639	6742376	PPFrame_DOM->expand( )	../Parser.php:3322
16	1.5873	9930384	Parser->braceSubstitution( )	../Preprocessor_DOM.php:1169
17	1.5926	9944048	PPFrame_DOM->expand( )	../Parser.php:3647
18	1.5963	9961168	Parser->braceSubstitution( )	../Preprocessor_DOM.php:1169
19	1.5979	9965712	Parser->callParserFunction( )	../Parser.php:3505
20	1.5987	9967888	call_user_func_array ( )	../Parser.php:3771
21	1.5987	9969192	SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}( )	../Parser.php:3771
22	1.5988	9972776	SMW\AskParserFunction->parse( )	../HookRegistry.php:103
23	1.5988	9973848	SMW\AskParserFunction->doFetchResultsForRawParameters( )	../AskParserFunction.php:115
24	1.6081	10027984	SMWQueryProcessor::getResultFromQuery( )	../AskParserFunction.php:154
25	1.6081	10027984	SMWSQLStore3->getQueryResult( )	../SMW_QueryProcessor.php:508
26	1.6081	10028032	SMWSQLStore3->fetchQueryResult( )	../SMW_SQLStore3.php:294
27	1.6082	10033640	SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult( )	../SMW_SQLStore3.php:303
28	1.6082	10033912	SMW\SQLStore\QueryEngine\QueryBuilder->buildQuerySegmentFor( )	../QueryEngine.php:170
29	1.6082	10033912	SMW\SQLStore\QueryEngine\Interpreter\DispatchingInterpreter->interpretDescription( )	../QueryBuilder.php:211
30	1.6082	10033912	SMW\SQLStore\QueryEngine\Interpreter\DisjunctionConjunctionInterpreter->interpretDescription( )	../DispatchingInterpreter.php:54
31	1.6083	10034272	SMW\SQLStore\QueryEngine\QueryBuilder->buildQuerySegmentFor( )	../DisjunctionConjunctionInterpreter.php:59
32	1.6083	10034272	SMW\SQLStore\QueryEngine\Interpreter\DispatchingInterpreter->interpretDescription( )	../QueryBuilder.php:211
33	1.6083	10035016	SMW\SQLStore\QueryEngine\Interpreter\DisjunctionConjunctionInterpreter->interpretDescription( )	../DispatchingInterpreter.php:54
34	1.6083	10035376	SMW\SQLStore\QueryEngine\QueryBuilder->buildQuerySegmentFor( )	../DisjunctionConjunctionInterpreter.php:59
35	1.6083	10035376	SMW\SQLStore\QueryEngine\Interpreter\DispatchingInterpreter->interpretDescription( )	../QueryBuilder.php:211
36	1.6083	10037120	SMW\SQLStore\QueryEngine\Interpreter\ConceptDescriptionInterpreter->interpretDescription( )	../DispatchingInterpreter.php:54

**Comment by mwjames** [comment]
It would be great to have some examples for Concepts to fail. This is so we are able to replicate the issue as we currently don't have any test that fails for  Concept/`SMW\DIWikiPage::getText()`

**Comment by mwjames** [comment]
The line that causes the issue `wfMessage( 'smw_concept_cache_miss', $description->getConcept()->getText() )->text()` is not a regression because it has been there at least 1.8* [0], which means that it was never tested.

A __quick fix__ is to use `getConcept()->getHash()` or `getConcept()->getTitle()->getText()` as replacement for `getText()`in [1].

`$description->getConcept()` always returns a `DIWikiPage`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8.0.5/includes/storage/SQLStore/SMW_SQLStore3_Queries.php#L602

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/Interpreter/ConceptDescriptionInterpreter.php#L112

**Comment by chironimow** [comment]
Hi mwjames
I added the get_Title and it works! Thank you very much. Hope this will be changed for the future, as I am not a contributor right now, just a user...

chironimow

**Comment by mwjames** [comment]
> Hope this will be changed for the future, as I am not a contributor right now, just a user

Fix has been released with [2.2.1](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/2.2.1).
