### ISSUE TITLE
Disjunction Constraints Ignored in Ask Queries

### ISSUE THREAD

**Issue by lbillett** [SemanticMediaWiki/SemanticMediaWiki#1056]
Ask query as  [[Prop1::Value1]] [[Prop2::Value1]]  returns results exactly as expected. However introducing disjunctions sees constraints on Prop2 ignored.

ie.  [[Prop1::Value1]] [[Prop2::Value1||Value2]] returns same results as
[[Prop1:Value1]].

SMW 2.1 on MW 1.23.2

**Comment by mwjames** [comment]
By using the following example with query returns an expected list of subjects hence I'm not able to verify the issue as described unless a more sufficient example is given. 

* page `Issue1056/1` with [[Prop1::Value1]] [[Prop2::Value1]]
* page `Issue1056/2` with [[Prop1::Value1]] [[Prop2::Value2]]
* page `Issue1056/3` with [[Prop1::Value1]]

```
{{#ask: [[Prop1::Value1]] [[Prop2::Value1||Value2]]
 |format=table
}}
```

### SQLStore
```
SELECT DISTINCT t9.smw_title AS t,t9.smw_namespace AS ns FROM `smw_object_ids` AS t9 INNER JOIN `smw_di_wikipage` AS t1 ON t9.smw_id=t1.s_id INNER JOIN `smw_di_wikipage` AS t4 ON t1.s_id=t4.s_id INNER JOIN `t6` AS t6 ON t4.o_id=t6.id WHERE (t1.p_id='1955' AND t1.o_id='1956' AND (t4.p_id='1957')) ORDER BY t9.smw_sortkey ASC LIMIT 55 OFFSET 0;
Auxilliary Tables Used
Temporary table t6
  INSERT IGNORE INTO `t6` (id) VALUES ('1956')
  INSERT IGNORE INTO `t6` (id) VALUES ('1959')
```
will return `Issue1056/1` and `Issue1056/2`

### SPARQLStore

```
PREFIX wiki: <http://example.org/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <http://example.org/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?result WHERE {
?result swivt:wikiPageSortKey ?resultsk .
?result property:Prop1 wiki:Value1 .
?result property:Prop2 ?v2 .
FILTER( ?v2 = wiki:Value1 || ?v2 = wiki:Value2 )

}
ORDER BY ASC(?resultsk) 
OFFSET 0


LIMIT 51
```
will return `Issue1056/1` and `Issue1056/2`

**Comment by lbillett** [comment]
On more exploring, my statement isn't quite correct. The disjunction portion isn't ignored entirely, but the result set is not correct. In the below preview screen shot/example, only querying for [[Action Item Status::Open]] would give hundreds of results. Adding the Property:Owner constraint works fine for specifying a single value, but adding the disjunction sees the result set include some additional items that are don't fit.

![image](https://cloud.githubusercontent.com/assets/12837660/8108663/d24eab0e-101f-11e5-895b-438330220811.png)

Could out-of-sync smw tables cause something like this? I can run a full property rebuild tonight if it'd help (we're way overdue anyway).

**Comment by mwjames** [comment]
> Could out-of-sync smw tables cause something like this? I can run a full property rebuild tonight if it'd help (we're way overdue anyway).

I couldn't say, I'm unable to reproduce the issue. Even if I add a `Issue1056/4` page with Value3 being unrelated as of [[Prop1::Value1]] [[Prop2::Value3]] to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1056#issuecomment-111074017, the result list will __not__ list  `Issue1056/4` as result subject.

It would help if you try the example given and report your results. Also try using `format=debug` to see the actual `SQL` execution.

```
{{#ask: [[Prop1::Value1]] [[Prop2::Value1||Value2]]
 |format=debug
}}
```

**Comment by mwjames** [comment]
Similar query `[[Category:Animal]][[Has trait::Herding||Hunting]]` is tested with https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/Fixtures/query-08-03-category-nested-hierarchy-en.json#L97

**Comment by lbillett** [comment]
Ah, neato. Here is the debug output I get with the disjunction. Structure looks almost identical? Though some different table names.
````
Debug Output by SMWSQLStore3
Generated Wiki-Query
[[Action Item Status::Open]] [[Owner::Nlewis||Swilson]]
Query Metrics
Query-Size:5
Query-Depth:1
SQL Query
SELECT DISTINCT t5.smw_title AS t,t5.smw_namespace AS ns FROM `smw_object_ids` AS t5 INNER JOIN `smw_di_blob` AS t1 ON t5.smw_id=t1.s_id INNER JOIN `smw_di_blob` AS t3 ON t1.s_id=t3.s_id WHERE ((t1.o_hash='Open') AND t1.p_id='577' AND ((t3.o_hash='Nlewis') OR (t3.o_hash='Swilson') AND t3.p_id='343')) ORDER BY t5.smw_sortkey ASC LIMIT 55 OFFSET 0;
Auxilliary Tables Used
No auxilliary tables used.
Errors and Warnings
None
````

**Comment by mwjames** [comment]
According to `((t1.o_hash='Open') AND t1.p_id='577' AND ((t3.o_hash='Nlewis') OR (t3.o_hash='Swilson')`, `t3.o_hash='Nlewis'` are declared as text value types.

Changing Prop1 and Prop2 to `Has type::Text` will result in 
```
Debug Output by SQLStore
Generated Wiki-Query
[[Prop1::Value1]] [[Prop2::Value1||Value2]]
Query Metrics
Query-Size:5
Query-Depth:1
SQL Query
SELECT DISTINCT t5.smw_title AS t,t5.smw_namespace AS ns FROM `smw_object_ids` AS t5 INNER JOIN `smw_di_blob` AS t1 ON t5.smw_id=t1.s_id INNER JOIN `smw_di_blob` AS t3 ON t1.s_id=t3.s_id WHERE ((t1.o_hash='Value1') AND t1.p_id='1955' AND (((t3.o_hash='Value1') OR (t3.o_hash='Value2')) AND t3.p_id='1957')) ORDER BY t5.smw_sortkey ASC LIMIT 55 OFFSET 0;
Auxilliary Tables Used
No auxilliary tables used.
Errors and Warnings
None
```
and returns `Issue1056/1` and `Issue1056/2`.

There is a difference in statement encapsulation (parentheses used):

```
WHERE ((t1.o_hash='Value1') AND t1.p_id='1955' AND (((t3.o_hash='Value1') OR (t3.o_hash='Value2')) AND t3.p_id='1957'))
```

```
WHERE ((t1.o_hash='Open') AND t1.p_id='577' AND ((t3.o_hash='Nlewis') OR (t3.o_hash='Swilson') AND t3.p_id='343'))
```

I'd suggest you update to 2.2* due to #556 / parentheses issue.

**Comment by mwjames** [comment]
Additional test for the cited example can now be found in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/Fixtures/query-09-01-disjunction-conjunction-19-1056.json#L99-L129

**Comment by kghbln** [comment]
[Task T31866](https://phabricator.wikimedia.org/T31866) may be related. Have not checked if this is already tested with pull request https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1057

@cicalese FYI

**Comment by mwjames** [comment]
> Task T31866 may be related. Have not checked if this is already tested with pull request #1057

Use cases from T31866 are now covered by #1059.

**Comment by mwjames** [comment]
It is actually no longer a bug because #556 has long solved the issue.

**Comment by JeroenDeDauw** [comment]
Seems like I use the labels differently than you. To me the label "bug" indicates that the post is about a perceived bug. That does not change based on there being an actual bug or not, or it being fixed or not.

**Comment by mwjames** [comment]
> Seems like I use the labels differently than you.

I only add the bug tag when it is clear that it is a bug from the given evidence and not the mere notion of a likelihood.

**Comment by mwjames** [comment]
@lbillett Any update on the issue?

**Comment by lbillett** [comment]
Bah. Not yet, I haven't gotten a chance to update our production
installation where I'm seeing the behavior (day job has been keeping me
busy). I'm not entirely convinced it's not something else on my side. I
have other disjunctions that work as expected. Though if the brackets bug
can introduce results that would be considered unexpected, it very well may
be it. I'll do the upgrade soon.

**Comment by mwjames** [comment]
As per https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1056#issuecomment-111571331.
