### ISSUE TITLE
data repair / actualisation progress bar

### ISSUE THREAD

**Issue by DW-rocks** [SemanticMediaWiki/SemanticMediaWiki#1064]
When installing SMW and selecting: Repair / Actualize Data the progress bar goes beyond 100 percent.
![bildschirmfoto 2015-06-14 um 17 07 39](https://cloud.githubusercontent.com/assets/4059641/8149100/054ab21e-12b9-11e5-8d66-32a390eeb0ae.png)

**SMW Version:** 2.2.1
**MediaWiki Version:** 1.24.1
**PHP:** 5.6.8 (cgi-fcgi)
**MariaDB:** 5.5.43-MariaDB-1~wheezy

**Comment by mwjames** [comment]
Expected to be fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1041 in 2.3

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by JeroenDeDauw** [comment]
@DW-rocks Thanks for reporting the issue. Clearly SMW should go way beyond 103%, it's that awesome!

**Comment by DW-rocks** [comment]
@JeroenDeDauw You're welcome :-) I think exactly the same and I really appreciate this awesome work! I wish I had some more time to understand it sooner - it's rather complex to implement all the features that makes MW usable to non-IT people.

**Comment by kghbln** [comment]
This is actually a very old bug from SMW 1.5 finally fixed.  Great and thanks!

**Comment by mwjames** [comment]
@kghbln Feel free to re-open the issue if it isn't solved with #1041 as it was just a by-product of the re-factoring.
