### ISSUE TITLE
Code coverage and project risks

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#107]
With 1.9.0.2 we cover a total of 41.12% lines but some domains still suck big times:
- articlepages 0.00%
- dataitems 54.26%
- datavalues     10.07%
-  export 1.63%
- query 56.05%
-  queryprinters 33.11%
- sparql 0.00%
- specials 31.40%
- storage 34.57% (coverage is only achieved because of the integration tests otherwise the Store fails completely on the notion of unit testing)
-  parserhooks 60.38% (mostly because of legacy code in DeclareParserFunction, DocumentationParserFunction, InfoParserFunction)
## Top Project Risks
- SMWTimeValue (23655)
- SMWSparqlStoreQueryEngine (17030)
- SMWExporter (15464)
- SMWSQLStore3QueryEngine (13304)
- SMWExportController (7482)
- SMWSQLHelpers (7140)
- SMWURIValue (5700)
- SMWSQLStore3 (4755)
- SMWPageSchemas (4290)
- SMWSQLStore3SetupHandlers (4160)

Analysis is based on PHP_CodeCoverage 1.2.7 using PHP 5.4.7 and PHPUnit 3.7.13 at Fri Jan 17 6:36:41 UTC 2014.

**Comment by mwjames** [comment]
As of 2.2 ~74% coverage (Tests: 3014, Assertions: 8721)

**Comment by kghbln** [comment]
- as of 2.0 ~??% coverage [(Tests: 2316, Assertions: 7181)](https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/31618041)
- as of 2.1 ~??% coverage [(Tests: 2966, Assertions: 8950)](https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/47559265)

@mwjames Have not checked the consecutive releases but there is a difference for 2.1?!

**Comment by JeroenDeDauw** [comment]
Note that the slides from last year include a bunch of stuff you can copy or at least steal the data from https://jeroendedauw.github.io/slides/smwcon/2015fall/yearly/#/5/1

**Comment by mwjames** [comment]
Tracked in https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/1.
