### ISSUE TITLE
Invalid marker error on form edit

### ISSUE THREAD

**Issue by Betacommand** [SemanticMediaWiki/SemanticMediaWiki#1072]
I have a fairly basic setup and am getting error messages like
 Invalid marker: UNIQf85c1265251db270-item-0--QINU

When trying to use forms to edit a page.

Will provide any additional information that is needed just ask.

**Comment by mwjames** [comment]
Please be so kind and post this on the [SF](https://www.mediawiki.org/wiki/Extension_talk:Semantic_Forms) page directly as it doesn't relate to SMW-core.

See also https://github.com/WikiApiary/WikiApiary/issues/210
