### ISSUE TITLE
"Embedded" format also transcludes properties and subobjects

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#1076]
http://www.semantic-mediawiki.org/wiki/Help:Embedded_format claims that "SMW will take care that embedded articles do not import their semantic annotations, so these need not be treated specifically"

Yet this is precisely what's happening on http://www.vanhamel.nl/codecs/Rennes,_Biblioth%C3%A8que_de_Rennes_M%C3%A9tropole,_MS_598/ff._90-125
The "Embedded" format is used here to embed three tables of contents, whose properties (e.g. Semantic Form's "Has default form") and subobjects are inherited by the page. 

For the factbox, see http://www.vanhamel.nl/codecs/Special:Browse/Rennes,_Biblioth%C3%A8que_de_Rennes_M%C3%A9tropole,_MS_598-2Fff._90-2D125

**Comment by mwjames** [comment]
#1068 solves the issue by excluding "embedded" from the recursive annotation support. `parser-08-01-embedded-ask.json` tests that no annotations are imported for the default setting.

**Comment by D-Groenewegen** [comment]
Thanks for this as well as for that issue with the Pagewidget format.

**Comment by D-Groenewegen** [comment]
Just a question. I'd like to test
$smwgEnabledResultFormatsWithRecursiveAnnotationSupport but I'm not sure
how to use it in order for the "embedded" or the "pagewidget" result format
to exclude any semantic annotations from the source page? In SMW 2.4alpha,
import of annotations seems to be true by default (at least that's what
still happens on my installation), so how does the 'switch' work?

Best,
Dennis




2015-07-07 8:42 GMT+02:00 mwjames <notifications@github.com>:

**Comment by mwjames** [comment]
> n SMW 2.4alpha, import of annotations seems to be true by default

No, it should not (I think we have some tests that explicit test this).

`smwgEnabledResultFormatsWithRecursiveAnnotationSupport` was actually removed with 2.3.1 as it was creating more trouble (#1255) then anticipated and instead of a global setting, importing has being made available only on a per query basis when the `import-annotation` parameter is set `true` (which by default is set false).

#1257 restored the previous behaviour.

**Comment by mwjames** [comment]
Feel free to create an example at [0] (which hosts the most recent development incl. SMW) to demonstrate your observation.

[0] http://sandbox.semantic-mediawiki.org

**Comment by D-Groenewegen** [comment]
Curiously, the problem is still happening on my fresh SMW 2.4alpha build,
which is why I asked. I just digged into this and discovered that it is
happening in a specific but not unusual context:

* If there is no other query on the same page, annotations are not imported
* If there is another query on the same page occurring after the embedded
page(s), annotations are not imported either (all good so far)

Now here comes trouble:

* annotations are imported if there is another query on the same page
occurring before the embedded page.

For some reason, the preceding query breaks behaviour expected of the
second query.






2016-03-12 12:54 GMT+01:00 mwjames <notifications@github.com>:

**Comment by mwjames** [comment]
> * annotations are imported if there is another query on the same page
occurring before the embedded page.
> For some reason, the preceding query breaks behaviour expected of the
second query.

In don't understand the issue hence me reiterating on the suggestion made in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1076#issuecomment-195726105.

**Comment by D-Groenewegen** [comment]
Demonstrated here:

http://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum_3






2016-03-12 22:48 GMT+01:00 mwjames <notifications@github.com>:

**Comment by mwjames** [comment]
> Demonstrated here:
> http://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum_3

This helps to not second guess the issue, so :+1:  but I imported the example into an old 1.9.2 system and it shows the same behaviour as the one linked above, so the behaviour between 1.9.2 and 2.4 has not changed in regards of how content such as  `{{:Lorem ipsum 2}}` is imported (this what the embedded format actually does).

**Comment by mwjames** [comment]
As for

```
[[SMW::off]]Lorem ipsum dolor sit amet consectetuer justo Nam quis lobortis vel. Sapien nulla enim Lorem enim pede lorem nulla justo diam wisi. [[Libero Nam turpis]] neque leo scelerisque nec habitasse a lacus mattis. Accumsan tincidunt Sed adipiscing nec facilisis tortor Nunc Sed ipsum tellus. [[Has page::Turpis pellentesque]] id sociis pede ipsum Quisque. Eu sed sed porta Integer pulvinar accumsan leo in semper lobortis. Urna vel mattis [[Has page::Pellentesque ante]] iaculis tincidunt et consequat Aliquam dictum.

__SHOWFACTBOX__[[SMW::on]]
```

[[SMW::off]] / [[SMW::on]] is only applied to "real" text but things that are wrapped in a parser function such as `#set`/`#subobject` are not influenced by this. Parser functions are separate and do not run through the `InTextAnnotationParser` which we can see by the time of the output "Lorem ipsum dolor sit amet consectetuer justo ..." which is the result of pre-processed #set call before `{{:Lorem ipsum 2}}` is invoked.

**Comment by mwjames** [comment]
To solve the issue with #set / #subobject one would have to use a brute force method of something like:

In `ResultPrinter` add:

```
@@ -297,10 +297,12 @@ abstract class ResultPrinter extends \ContextSource implements QueryResultPrinte
 		// Preprocess embedded templates if needed
 		if ( ( !$this->isHTML ) && ( $this->hasTemplates ) ) {
 			if ( ( $wgParser->getTitle() instanceof Title ) && ( $wgParser->getOptions() instanceof ParserOptions ) ) {
 				self::$mRecursionDepth++;
 
+				$wgParser->getOutput()->smwQueryResultFormat = $this->params['format'];
+
```

and amend the `SetParserFunction ` and `SubobjectParserFunction` with:


```
@@ -80,13 +80,15 @@ class SetParserFunction {
 						$value,
 						false,
 						$subject
 					);
 
-				$this->parserData->addDataValue(
-					$dataValue
-				);
+				if ( !isset( $this->parserData->getOutput()->smwQueryResultFormat ) || $this->parserData->getOutput()->smwQueryResultFormat !== 'embedded' ) {
+					$this->parserData->addDataValue(
+						$dataValue
+					);
+				}
``` 

```
@@ -139,11 +139,13 @@ class SubobjectParserFunction {
 						$value,
 						false,
 						$subject
 					);
 
-				$this->subobject->addDataValue( $dataValue );
+				if ( !isset( $this->parserData->getOutput()->smwQueryResultFormat ) || $this->parserData->getOutput()->smwQueryResultFormat !== 'embedded' ) {
+					$this->subobject->addDataValue( $dataValue );
+				}
 			}
```

__This isn't really tested nor have I made a full evaluation__ whether this is the correct approach or not but something along that line to indicate to those parser functions that they have been invoked during a `embedded` format call.

But above would be a new behaviour.

**Comment by D-Groenewegen** [comment]
Oh dear, that's really unfortunate! I hope it'll work out.

A temporary if perhaps expensive solution may be offered by the Variables
extension. It can be used to make parsing of #set or #subobject notations
conditional on a variable. For instance, a template for a subobject on the
source page could have

{{
   #if:{{#var:nosubobject}}||{{#subobject:...}}
}}

or shorter,

{{#var:nosubobject | {{#subobject:...}} }}

so that calls to {{#subobject:...}} are always made unless a variable
'nosubobject' has been defined to annul such calls. The page containing a
query with the embedded format should then also contain

{{#vardefine:nosubobject|}}

It's the best remedy I can think of at the moment.

2016-03-13 0:43 GMT+01:00 mwjames <notifications@github.com>:
