### ISSUE TITLE
Stop relying on deprecated $wgSpecialPageGroups

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1080]
As per https://gerrit.wikimedia.org/r/#/c/220804/, which was reverted by https://gerrit.wikimedia.org/r/#/c/221644/

**Comment by jongfeli** [comment]
@JeroenDeDauw, the changes committed in gerrit ([220804](https://gerrit.wikimedia.org/r/#/c/220804/)) where correct but should be replicated and committed via Github? This means **Umherirrender** never committed them via Github to get them in SMW?

**Comment by JeroenDeDauw** [comment]
The part that could be applied (compat with MW 1.26) has been merged, the part that could not (removal of compat with older MW versions), should be removed in SMW 3.x. (Not yet at present)

**Comment by mwjames** [comment]
@kghbln Not sure what to do with this? Any resolution would be appreciated.

**Comment by kghbln** [comment]
Well I could try to imitate Umherirrender's pull but probably @JeroenDeDauw could do this on the fly?

**Comment by kghbln** [comment]
Most of this was already done with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/09ac11f0d1f5b2b0fae241d67a7aee0c8f0750c0#diff-d465c67e3b2d34bdbd22caf7eae1f098
