### ISSUE TITLE
Query for Pages Not in Categories

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticMediaWiki#1084]
I would love to have the ability to query for pages and omit those in a particular category from the results.

``` text
{{#ask: [[Category:!Application]] [[Category:Software]] }} 
```

Similar to [selecting pages with comparators](http://semantic-mediawiki.org/wiki/Help:Selecting_pages#Comparators), but for categories. 

See also:
- https://semantic-mediawiki.org/wiki/Help:Selecting_pages#Things_that_are_not_possible
- https://semantic-mediawiki.org/wiki/Help_talk:Selecting_pages/Archive#Searching_for_pages_NOT_in_Categories

**Comment by joelkp** [comment]
Perhaps the best way to support this would be the more general negation feature found in an old pull request by vitalif: #20 - "Support subquery negation operator in SemanticMediaWiki queries."

It seems half-done: in order for it to be added, further work to modularize the code and make tests for it was needed. Time has passed, so no doubt a bit of updating would also be needed.

**Comment by JeroenDeDauw** [comment]
Yeah, I think it makes more sense to add general negation support than something specific to category selection.

**Comment by mwjames** [comment]
There will be an experimental support in the ES store for this but not for the `SQLStore` (and it is very unlikely that I will add this to the `SQLStore`).

https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=YzpVjcEKgzAQRL8muSmpVmgPe7AW_2PVTRNMGtiN2M9vWumhMIcH85h5QdXdSgbMamhVf30k9qTa_mQu56q7l6hmrNrxX9A2ccQMEydcMk6BdPDRZ2iMKfRcAUPQjnAhFhCXdi2EPLuAEwWo61o1xm6cHXEhJtlCFj0HlKIn_k6WYver_7HE_Xj69KATl21AmXWyViiD0RH98zh4Aw

https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=Yzp1jcEKgzAQRL8muSkxttAe9mCV_seqmxqMBnYj9vObVnrooTCHB_OYeUJxvuW0mFRbq-b6iOxJ1U1lLqfi3L1jzR9H2eqj2a46VGXvRX3_9bSLvGCCniOOCftAOvjFJ7DGZFpnwBD0RDgSC8gUdy2EPEwBewpQlqWyxm2cJuJMTLKFJHoIKFmP_JnMxe5n_2VZ9uPp3YOOnLcBZdDROaEERi_o1-PgBQ

> I think it makes more sense to add general negation support than something specific to category selection.

Feel free!

**Comment by ankostis** [comment]
So there is plan NOT make it possible to search NOT in categories?

**Comment by ankostis** [comment]
In any case this issue should also be linked from the documentation page: https://www.semantic-mediawiki.org/wiki/Help:Selecting_pages

**Comment by Larivact** [comment]
I think this issue should be reopened because it is still unresolved, #20 came to nothing.

**Comment by s7eph4n** [comment]
It is listed in the [Enhancements and features](https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4#card-9351531) project, so it is not forgotten. If you want to work on it, just assign it to yourself and re-open it.

**Comment by mwjames** [comment]
> I think this issue should be reopened because it is still unresolved, #20 came to nothing.

I already gave a statement about the state of this request (see above).

> If you want to work on it, just assign it to yourself and re-open it.

Yes, re-opening a feature request is possible but should only happen when there is a "... clear sign of sponsorship ...".

Of course, other developers are free to pick this task but as long as there is no sponsor [0] it doesn't make sense to occupy the issue list with feature requests that are not going to be implemented in near future or without a clear developer commitment.

[0] see 3629

**Comment by ankostis** [comment]
What makes it to hard to implement in SQL engines, or in general?
Is it the cache-invalidation logic (wild guess)?

**Comment by mwjames** [comment]
> Is it the cache-invalidation logic (wild guess)?

No.

> What makes it to hard to implement in SQL engines, or in general?

First of all you have to investigate the technical architecture which requires effort and diligence (and goes beyond my personal commitment).

You would probably end up with `LEFT JOIN` or `LEFT OUTER` constructs but would require to make sure that those take into account hierarchy segments (subcategories, meaning you need to traverse the leafs of those elements in order to meet the condition).

This is not your trivial `SELECT ... FROM ... WHERE ... LIMIT ...` SQL, it has to work with conjuntions and disjunctions equally otherwise you end-up with a special case that only works for a specific pattern.
