### ISSUE TITLE
Add support for MW 1.26+

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1092]
## composer require is broken

- Install MW.1 26/master
- Add `composer require mediawiki/semantic-media-wiki:@dev` results in no files being loaded and instead returns with a fatal.

```
Fatal error: Uncaught exception 'Exception' with message 'Validator
depends on the ParamProcessor library.' in
...\mw-core\extensions\Validator\Validator.php:31 Stack trace:
#0 ...\mw-core\vendor\composer\autoload_real.php(59): require()
#1 ...\mw-core\vendor\composer\autoload_real.php(50):
composerRequire4e18cf470417eba470c21612c0f81530('D:\\xampp\\htdocs...')
#2 ...\mw-core\vendor\autoload.php(7):
ComposerAutoloaderInit4e18cf470417eba470c21612c0f81530::getLoader()
#3 ...\mw-core\includes\WebStart.php(103): require_once('D:\\xampp\\htdocs...')
#4 ...\mw-core\index.php(38): require('D:\\xampp\\htdocs...')
#5 {main} thrown in ...\mw-core\extensions\Validator\Validator.php on line 31
```

Trying to run `composer update` again will some how correct this and
allows the files to be loaded correctly.

## Travis install is broken
https://phabricator.wikimedia.org/T106148

```
echo 'putenv( '\''MW_INSTALL_PATH=/home/travis/build/SemanticMediaWiki/mw'\'' );'
+php maintenance/update.php --quick
PHP Fatal error:  Call to undefined function MediaWiki\suppressWarnings() in /home/travis/build/SemanticMediaWiki/mw/maintenance/Maintenance.php on line 960
PHP Stack trace:
PHP   1. {main}() /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php:0
PHP   2. require_once() /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php:214
PHP   3. Maintenance->finalSetup() /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:95
Fatal error: Call to undefined function MediaWiki\suppressWarnings() in /home/travis/build/SemanticMediaWiki/mw/maintenance/Maintenance.php on line 960
Call Stack:
    0.0006     291112   1. {main}() /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php:0
    0.0029     680256   2. require_once('/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php') /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php:214
    0.0430    6136928   3. Maintenance->finalSetup() /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:95
```

## Test environment is broken 

Running `composer phpunit` no longer works on 1.26 / 1.26alpha (dfb9d81) (it does work on all previous releases).

```
$ composer phpunit
> php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist
PHPUnit already present

MediaWiki: 1.26alpha (MediaWiki vendor autoloader)
Semantic MediaWiki: 2.3 alpha (SMWSQLStore3, mysql)


Fatal error: Class 'SMW\Tests\Utils\Mock\MockTitle' not found in ...\extensions\SemanticMediaWiki\tests\phpunit\includes\Annotator\CategoryPropertyAnnotatorTest.php on line 226
Script php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist handling the phpunit event returned with an err
or



  [RuntimeException]
  Error Output:



phpunit [--dev] [--no-dev] [args1] ... [argsN]
```

@JeroenDeDauw @kghbln Do what you want but I'm not going to spend any time to make it work on 1.26.

**Comment by kghbln** [comment]
Phew! I can just roll my eyes about this. @JeroenDeDauw I believe we need your experience and effort here.

**Comment by JeroenDeDauw** [comment]
This is obviously not good, though as MW  has not been released yet, not the end of the world either. I'll try to put some time into this soon.

**Comment by JeroenDeDauw** [comment]
On composer require not working, @DanweDE actually mailed me the same error a few days back, but then for the SubPageList extension. I'm guessing this is caused by the [composer merge plug-in](https://github.com/wikimedia/composer-merge-plugin) somehow. @bd808 thoughts?

**Comment by mwjames** [comment]
As for "Test environment is broken" after using https://github.com/wikimedia/mediawiki/commit/db0d6164c2f4641d1684d4941e05cb37f7f71aa0 running `composer phpunit` works again:

```
$ composer phpunit
> php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist
PHPUnit already present

MediaWiki: 1.26alpha (MediaWiki vendor autoloader)
Semantic MediaWiki: 2.3 alpha (mysql) test autoloader

PHPUnit 3.7.37 by Sebastian Bergmann.

Configuration read from ...\mw-core\extensions\SemanticCite\phpunit.xml.dist

...............................................................  63 / 225 ( 28%)
............................................................... 126 / 225 ( 56%)
............................................←[31;1mE←[0m...←[31;1mE←[0m←[31;1mE←[0m............. 189 / 225 ( 8
4%)
......................
Fatal error: Call to protected method DatabaseBase::ignoreErrors() from context 'SMW\Tests\Utils\MwDatabaseTab
leBuilder' in ...\SemanticMediaWiki\tests\phpunit\Utils\MwDatabaseTableBuilder.
php on line 265
Script php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist handling the phpunit event returned with an err
or


```

**Comment by mwjames** [comment]
DatabaseBase interface change breaks tests on 1.26

```
MediaWiki: 1.26alpha (Extension vendor autoloader)
Semantic MediaWiki: 2.3 alpha (SMWSQLStore3, sqlite)
PHPUnit 4.6.10 by Sebastian Bergmann and contributors.
Configuration read from /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/phpunit.xml.dist
.............................................................   61 / 3080 (  1%)
.............................................................  122 / 3080 (  3%)
.............................................................  183 / 3080 (  5%)
.............................................................  244 / 3080 (  7%)
.............................................................  305 / 3080 (  9%)
.............................................................  366 / 3080 ( 11%)
.............................................................  427 / 3080 ( 13%)
.............................................................  488 / 3080 ( 15%)
.............................................................  549 / 3080 ( 17%)
.............................................................  610 / 3080 ( 19%)
..........EE.FFFE.F.............................E............  671 / 3080 ( 21%)
....
Fatal error: Class Mock_DatabaseBase_d7e8ce0b contains abstract method (getType) and must therefore be declared abstract or implement the remaining methods in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(290) : eval()'d code on line 1
```

https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/74120648

**Comment by JeroenDeDauw** [comment]
Do you know which test is failing, and why? This class was abstract before, and the `getType` method was also abstract. Why does it matter that this method is now defined in an implemented interface?

**Comment by bd808** [comment]
> DatabaseBase interface change breaks tests on 1.26

That looks to me to be a known HHVM bug with reflection and abstract methods:
* https://phabricator.wikimedia.org/T95864
* https://github.com/sebastianbergmann/phpunit-mock-objects/issues/223
* https://github.com/facebook/hhvm/issues/5170

**Comment by mwjames** [comment]
> hat looks to me to be a known HHVM bug with reflection and abstract methods:

I have to wonder about this because the same tests did pass on MW 1.25 / HHVM / PHP 5.6. (and I know I haven't touched those tests in a while).

This [0] is an early 1.26 run (HHVM 3.5.0 (rel)) which did not break on `Mock_DatabaseBase_d7e8ce0b` (has some other issue but that's API related) so clearly something has changed.


[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/67585424

**Comment by JeroenDeDauw** [comment]
The issue is that HHVM cannot mock abstract classes which don't fully implement an interface, such as DatabaseBase in MediaWiki 1.26. So yeah, we now have this failure due to a change in MediaWiki, nevertheless, it is not a MediaWiki issue.

**Comment by mwjames** [comment]
After reading [0] and looking at [1], I had a bad feeling about this so I made a fresh core fetch (a7d08ff).

The display starts to clutter with styles being loaded after a short delay making the screen look like a flip-flop game and to avoid any misunderstanding about the issue, video [2] highlights the problem.

PS: SMW is loading the styles at the top. [2] is using the Vector skin with a purged browser cache. The issue was no present when core was tested with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1092#issuecomment-127062180.

[0] https://lists.wikimedia.org/pipermail/wikitech-l/2015-August/082625.html
[1] https://phabricator.wikimedia.org/T107399
[2] https://youtu.be/_-DDLVnwR1Q

**Comment by JeroenDeDauw** [comment]
Is that something that affects SMW in particular or does this happen for the MW UI in general?

**Comment by addshore** [comment]
setIsRawMode will be removed from the api modules base class soon (just a heads up)
It looks like this is used twice in ApiQueryResultFormatterTest
Needs to be removed ;)
