### ISSUE TITLE
canonical getValue() in SMWDataItem

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1094]
SMW has evolved over the years to handle subject/predicate/object triples in many specific ways.
There is namespace support, sorting support, special handling for different types, special handling for different locales. All this adds a lot of complexity when handling Data Items and trying to import/export or format or whatever do with triples.

To get back to a more simplified, canonical view I propose to add a getValue() abstract function in:
http://semantic-mediawiki.org/doc/classSMWDataItem.html

to make sure a canonical representation is returned. This means e.g. a boolean would
return "true" or "false" as a value and not "falsch" or "wahr". This means a date is returned in ISO format
as yyyy-MM-dd HH:mm:ss (with zulu time zone if this is what we really call canonical). Pagetitle references are returned with canonical normalized namespaces e.g. like "Property:has population" and not "Attribut:has population" 

and so on. 
This would make life much easier when e.g. writing Semantic Result Format printers, importers, exporters or even just when debugging things.

**Comment by JeroenDeDauw** [comment]
Is that not what `getSerialization` already does?

**Comment by mwjames** [comment]
You can use either `getSerialization` or `getWikiValue`.
