### ISSUE TITLE
Backslash (%5C) causing trouble for the tooltip / info parser

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1098]
Using Composer I just upgraded to SMW 2.2.2 from another quite recent version of SMW. It struck me as odd that the tooltip functionality of the info parser had stopped working after this. When I checked the error console, it showed me messages like the following:

GET 
.../mw/extensions/SemanticMediaWiki%5Cresources/jquery/jquery.qtip.js [HTTP/1.1 404 Not Found 1ms]
GET 
.../mw/extensions/SemanticMediaWiki%5Cresources/smw/ext.smw.js [HTTP/1.1 404 Not Found 1ms]

Etc. As you can see there is an html backslash (%5C) rather than, as I would expect at least, a normal forward slash. What's the deal here?

**Comment by mwjames** [comment]
>  I just upgraded to SMW 2.2.2 from another quite recent version of SMW. 

What is the other recent version?

> When I checked the error console, it showed me messages like the following:

Nothing has changed  to the resource definition or the info parser in any of the 2.1/2.2* release therefore I can't see how SMW is the cause. The other thing is that the request for something like `...query/jquery.qtip.js` is done by MW's ResourceLoader and not SMW itself.

I have not seen an issue with something like `SemanticMediaWiki%5Cresources` on a local `1.25.1` instance.

**Comment by mwjames** [comment]
The resource path is specified in [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.2.x/resources/Resources.php#L17-L21

**Comment by Contrafibularity** [comment]
Interesting - I see that "onoi / cache" has been updated along with the rest. I'll try another update

**Comment by mwjames** [comment]
> Interesting - I see that "onoi / cache" has been updated along 

But those have **no dependency** on SMW or MW at all so I can not see how it comes into play with a MW/SMW issue.

**Comment by Contrafibularity** [comment]
Mmm, that didn't help. 

I actually ran "composer update" so that all extensions and their dependencies (which is probably where that "onoi / cache" comes from) are updated at one fell swoop. I'll remove some of the others to see what's causing this..

**Comment by Contrafibularity** [comment]
OK, this is apparently caused by a (recent) incompatibility between SMW and XMLContentExtension (https://www.mediawiki.org/wiki/Extension:XMLContentExtension).
