### ISSUE TITLE
Suggestion: Subobjects with named properties

### ISSUE THREAD

**Issue by Fannon** [SemanticMediaWiki/SemanticMediaWiki#1104]
Hello there!

I've thought about this a bit and like to throw it into discussion:

The gist of the idea is the following: SMW could (?) support a convenient document oriented (JSON) data structure in addition to its graph oriented structure, by the introduction of a simple new feature: The ability to give subobjects a custom property name in addition to the default internal property "Has subobject". 

As I understand it, the properties on a page can always be represented as a document structure. A graph only forms when the semantic properties of multiple pages are merged. Documents are much easier to understand and work with than graphs and since they are sufficient to describe a single page, why not make use of this?

Here's a simplified JSON representation of the current datastructure. Basically, each subobject is a "document" on its own.

```json
{
    "$ID": "PAGE_URL",

    "Prop1": ["single value"],
    "Prop2": ["multipleVal1", "multipleVal2"],

    "Has subobject": [
        "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82e0",
        "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82c3",
    ],
}
```
```json
{
    "$ID": "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82e0",
    "Prop1": ["something"],
}
```
```json
{
    "$ID": "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82c3",
    "Prop1": ["something else"],
}
```

If a custom property name can be set, it can contain the subobject directly:

```json
{
    "$ID": "PAGE_URL",

    "Prop1": ["single value"],
    "Prop2": ["multipleVal1", "multipleVal2"],

    "Has subobject": [
        "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82e0",
        "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82c3",
    ],

    "subobjectWithCustomPropertyName1": [{
        "$ID": "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82e0",
        "Prop1": ["something"],
    }],
    "subobjectWithCustomPropertyName2" :  [{
        "$ID": "PAGE_URL-23_548f35c5b6cc14c4fd963f9a9c4d82c3",
        "Prop1": ["something else"],
    }]
}
```

This way, it is easy to access it e.g. in JavaScript: `obj.subobjectWithCustomPropertyName2[0].Prop1`

This is currently not possible with subobject with anonymous identifieres (which I happen to use most). Since the name of the subobject is a hash that will change over time, it is not possible to use another semantic property to link to the subobject. The only way to reach it from its parent object (the page it is embedded in) is through the rather generic "Has subobject" property, which is a collection of all subobjects.  

The #subobject function to make this happen could look like this:
```
{{#subobject:|
 |@propertyName=subobjectWithCustomPropertyName
 |Prop1=something
}}
```

It would only add an additional semantic property with the given property name and the target of the (autogenerated or given) ID of the subobject.

This would also make sense from a graph structure perspective (imho), as it introduces more a more specific way to access all subobjects of a given kind.

What would be the benefit of having a convenient document structure? First, it would be a nice output for APIs. Second, it would allow to use document-oriented databases as stores, like Elasticsearch, MongoDB, RethinkDB, etc. Those databases are usually easy to scale horizontally - something relational and graph databases have their problems with.

I hope I could make my idea clear.

Best,
Simon

**Comment by mwjames** [comment]
> I've thought about this a bit and like to throw it into discussion:

:+1: 

> Since the name of the subobject is a hash that will change over time, it is not possible to use another semantic property to link to the subobject.

It will not change overtime but it will change over a content alteration. If a subobject and its property value annotations are not changed then the md5 (for the auto-generated ID) remains stable [0].

> Basically, each subobject is a "document" on its own.

Each subobject (in terms of its wiki representation) is connected to its embedding subject, so a subobject is not a loose graph element.

> It would only add an additional semantic property with the given property name and the target of the (autogenerated or given) ID of the subobject.
> `@propertyName=subobjectWithCustomPropertyName`

Not sure I completely understand the proposal but is `@propertyName` expected to contain a custom property name that if present will be set to the ID value of an individual subobject? If so then `@propertyName` is seems a bit too arbitrary as parameter identifier maybe something like `@idToPropertyName`.

By interpreting above comments, I'm guessing you are looking for an easy way to access a JSON object to get the ID. Access in the wiki to the ID is of lesser importance since a subobject is always connected to a subject representation (and you normally do not query for something like `[[Has subobject::MyID]] [[Another property::SomeValue]]`).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/includes/parserhooks/SubobjectParserFunctionTest.php#L147-L163

**Comment by mwjames** [comment]
> First, it would be a nice output for APIs. Second, it would allow to use document-oriented databases as stores, like Elasticsearch, MongoDB, RethinkDB, etc. Those databases are usually easy to scale horizontally

If you look for "NoSQL" support then you need a Store that actual writes `SemanticData` as document structure, the current SQLStore uses a row/column approach to fit the DB environment. I'm not sure how the `subobject` as a specific data representation fits in here.

PS: If you are looking for a semi-representation in a document style, please have a look at `api.php?action=browsebysubject&subject=MySubject&format=jsonfm` or `api.php?action=browsebysubject&subject=MySubject&subobject=SubobjectID&format=jsonfm` of the  `SemanticData` object.

**Comment by Fannon** [comment]
Hello mwjames,

thanks for your answer!

> Each subobject (in terms of its wiki representation) is connected to its embedding subject, so a subobject is not a loose graph element.

Yes, that's true. They are connected through "Has subobject" or through "sobj" in the API result you pointed out. But as I understand, it is not possible to further define/customize this relationship to the parent object. So yes, the document representation includes the subobjects, but in order to access specific types of subobjects I have to iterate all of them and look if it fits.

So yes, subobjects are connected, but you can't control how.

> Not sure I completely understand the proposal but is @propertyName expected to contain a custom property name that if present will be set to the ID value of an individual subobject? 

No, it would add an additional semantic property with the @propertyName name and link it to the subobject. like: [[customPropertyName::generatedSubobjectID]]

**Comment by mwjames** [comment]
> No, it would add an additional semantic property with the @propertyName name and link it to the subobject. like: [[customPropertyName::generatedSubobjectID]]

To where? To the subobject or to the subject `SemanticData` container?

You can create a list of IDs using `$store->getSemanticData( MYSUBJECT )->getPropertyValues( new DIProperty( '_SOBJ' )` which could be added to an API or serializer.

**Comment by Fannon** [comment]
Sorry, I don't know the internals of SMW good enough to understand this distinction ;)

**Comment by Fannon** [comment]
Is there a way to explain this better?

The basic idea is very simple: Just add the capability to define an additional and optional custom name for the "Has subobject" property that links to the subobject.

**Comment by mwjames** [comment]
> Sorry, I don't know the internals of SMW good enough to understand this distinction ;)

That's fine (don't worry).

> Just add the capability to define an additional and optional custom name for the "Has subobject" property that links to the subobject.

"Has subobject" is a fixed label (as for a predefined property) being described internally by DIProperty( '_SOBJ' ). "optional custom name" as in alias?

Maybe I'm a bit dense but what is expected from a declaration (storage and relational wise) like:

```
{{#subobject:|
 |@propertyName=subobjectWithCustomPropertyName
 |Prop1=something
}}
```

To filter `@propertyName` is not a problem, to set `subobjectWithCustomPropertyName` as a custom property label is not problem but what value is expected is not clear and how would that help if you look at it as an simplified array:

```
	array(
		"generatedSubobjectMd5Key" => array(
			'Prop1' => array(
				'something'
			)
			'subobjectWithCustomPropertyName' => ??
		)
	)

```

**Comment by Fannon** [comment]
Ah, I see. The value is the ID / URL of the subobject. Basically its the same linking/referencing a wiki page and to a subobject, right?

**Comment by mwjames** [comment]
The description misses the opportunity to identify actionable task in order to drive this issue forward. Feel free to re-open it with a more exhaustive use case that would clarify the necessary actions or tasks.

**Comment by Fannon** [comment]
Yes, you can close it. If there's some time, I might play around with this idea again.

Let me summarize some ideas again:

I guess my main problem is that "Has subobject" / "-Has subobject" is kind of a semantically weak annotation. If you want to select specific Subobjects you'd always have to give them an additional unique category (thanks for introducing @category btw, it solves a part of this problem already!) or an property which is only used for this kind of subobject.

Having the ability to use an additional, specific property to link from the main object to the subobject would make some queries nicer, but also allow you to serialize / export the data in JSON in a way that's much nicer than you can currently do.

**Comment by mwjames** [comment]
> I guess my main problem is that "Has subobject" / "-Has subobject" is kind of a semantically weak annotation.

Well, the "Has subobject" entity descriptor is suppose to be only used in connection with a "real" property/values assignment. In itself the property  "Has subobject" is being a place-holder to collect entity related assignments and make them distinct from the rest of the subject it is embedded.
