### ISSUE TITLE
Windows, MW ResourceLoader debug mode: Backslash (%5C) causing trouble in loading SMW resources

### ISSUE THREAD

**Issue by bogota** [SemanticMediaWiki/SemanticMediaWiki#1120]
MW1.25.2/SMW2.2.2 installation on Windows fails to let clients load CSS and JS files under SMW resource directory when $wgResourceLoaderDebug=true. Firebug spews the errors like "NetworkError: 404 Not Found - http://localhost/wiki/extensions/SemanticMediaWiki%5Cresources/jquery/jquery.qtip.css" for each of those files failed. The symptom is exactly the same as #1098 but I'm not using XMLContentExtension.

The backslash char comes from https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.2.x/resources/Resources.php#L19 where `__DIR__` returns a resource path name in the manner of Windows (e.g. "C:\xampp\htdocs\wiki\extensions\SemanticMediaWiki\resources").

The 404 errors fade out after modifying Resources.php to replace backslashes with slashes like that.
```php
$moduleTemplate = array(
	'localBasePath' => __DIR__,
	'remoteExtPath' => str_replace( '\\', '/', end( ( explode( DIRECTORY_SEPARATOR . 'extensions' . DIRECTORY_SEPARATOR, __DIR__, 2 ) ) ) ),
	'group' => 'ext.smw'
);
```

**Comment by mwjames** [comment]
#1098

**Comment by mwjames** [comment]
If this a WIN related problem then potential issues exists in:

- https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/Resources.php#L13-L21
- https://github.com/SemanticMediaWiki/SemanticCite/blob/master/SemanticCite.php#L56
- https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/blob/master/SemanticBreadcrumbLinks.php#L47
- https://github.com/SemanticMediaWiki/SemanticMaps/blob/master/SemanticMaps.php#L53-L54

**Comment by mwjames** [comment]
@bogota SMW 2.3 draws near and if this is an important issue then maybe having a PR to resolve this issue would be neat.

**Comment by mwjames** [comment]
I made the amendments as suggested, @bogota please test against dev-master.
