### ISSUE TITLE
Precision of Type:Number cannot be specified on output

### ISSUE THREAD

**Issue by dbolser** [SemanticMediaWiki/SemanticMediaWiki#1125]
Following up from https://phabricator.wikimedia.org/T22217, which I couldn't find here...

I'd suggest that the properties default output format could be specified on the property page, i.e. [[Has output format::.2f]],  etc. This way format would work like units, and could be overridden for 'raw' output in the usual way.

kthxbi.

**Comment by mwjames** [comment]
Merged with 7cfa279 and expected to be deployed with 2.4. For examples, please have a look at [0].

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/1335_%28Display_precision%29
