### ISSUE TITLE
The value of latitude and longitude on OpenLayer is opposite of the value of script.

### ISSUE THREAD

**Issue by JeongJun-Lee** [SemanticMediaWiki/SemanticMediaWiki#1128]
The order of value of latitude and longitude in the syntax of the display_map tag to show a map with specific position is latitude and longitude.
But when I lays a cursor on the OpenLayer Map like the attached, the order of value of latitude and longitude which is showed in OpenLayer Map is opposite to it of the value of script.
How can I make the order which is showed in the OpenLayer Map to latitude and longitude?

![issue](https://cloud.githubusercontent.com/assets/11474775/9567788/aa0c9b68-4f50-11e5-87a6-be1c848f8578.png)

**Comment by JeroenDeDauw** [comment]
Thanks for filing this question/feature request. Can you put it here? https://github.com/SemanticMediaWiki/SemanticMaps/issues

**Comment by JeongJun-Lee** [comment]
OK. I'll close here and move to the place.
