### ISSUE TITLE
Architecture notes / DataModel description

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1138]
I don't know where to put these (created as part of an issue investigation) but to avoid having them lost in the realm of the issues, I'll use this as place holder so interested parties can have a read.

## MediaWiki dependencies

![smw-mw-interface](https://cloud.githubusercontent.com/assets/1245473/10092160/d282671a-6343-11e5-84ef-683adc531000.png)

## Store

![image](https://cloud.githubusercontent.com/assets/1245473/10092183/10ea3500-6344-11e5-98c5-0f8c4b088599.png)

![image](https://cloud.githubusercontent.com/assets/1245473/10092243/7ef5ff66-6344-11e5-8555-ef8708f08c6a.png)

## UpdateJob

![image](https://cloud.githubusercontent.com/assets/1245473/9682986/f185d874-530b-11e5-94d3-cb6066749822.png)

## ParserData

![image](https://cloud.githubusercontent.com/assets/1245473/9608489/e38026ec-50ce-11e5-9239-46fa42a8b413.png)

## EmbeddedQueryDependencyLinksStore
![image](https://cloud.githubusercontent.com/assets/1245473/9419992/27bcb6d4-4861-11e5-8835-47fd0bd747af.png)

![image](https://cloud.githubusercontent.com/assets/1245473/10060472/672810f2-6251-11e5-97b1-ea0ed45ea548.png)

## DeferredRequestDispatchManager

![image](https://cloud.githubusercontent.com/assets/1245473/11161201/abe63820-8a76-11e5-9652-03b97667790d.png)

**Comment by JeroenDeDauw** [comment]
See also: https://semantic-mediawiki.org/wiki/Architecture_guide

**Comment by WolfgangFahl** [comment]
The images are all uploaded and embedded in the Architecture guide now.

**Comment by mwjames** [comment]
Most pictures where copied from here to the wiki and I may post an update on this in future but for now this is completed from where I'm standing.

**Comment by mwjames** [comment]
## InMemoryPoolCache 

Just to give some idea about our `InMemoryPoolCache` (which uses the `FixedInMemoryLruCache` to ensure an array stays fixed and doesn't inflate during run time with a Lru [0] algo to only keep the most used members in the cache space) to help us process things a bit quicker.

Running `rebuildData.php` on a 100 ID sample (which before would have accounted for a direct Store requests) with 2.4.

```
Processing all IDs from 1 to 100 ...

............................................................ 61%
........................................

100 IDs refreshed.

property.spec.lookup.cache 			inserts : 195 	deletes : 0 max : 500 count : 195 hits : 41775 	misses : 0
exporter.dataitem.resource.encoder	inserts : 1425 	deletes : 0 max : 500 count : 500 hits : 19938 	misses : 0
sql.store.dataitem.finder 			inserts : 1298 	deletes : 0 max : 500 count : 500 hits : 141 	misses : 0
sql.store.redirect.infostore 		inserts : 132 	deletes : 0 max : 500 count : 132 hits : 5176 	misses : 0
sparql.store.redirectlookup 		inserts : 166 	deletes : 0 max : 500 count : 166 hits : 11324 	misses : 0
store.redirectTarget.lookup 		inserts : 1 	deletes : 1 max : 500 count : 0	  hits : 1 		misses : 0
```

[0] http://mcicpc.cs.atu.edu/archives/2012/mcpc2012/lru/lru.html
