### ISSUE TITLE
Argument 1 passed to SMW\\ApplicationFactory::newParserData() must be an instance of Title

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/SemanticMediaWiki#1143]
We are intermittently getting the following PHP error:

PHP Catchable fatal error: Argument 1 passed to SMW\\ApplicationFactory::newParserData() must be an instance of Title, null given, called in .../extensions/SemanticMediaWiki/src/ParserFunctionFactory.php on line 71 and defined in .../extensions/SemanticMediaWiki/src/ApplicationFactory.php on line 233

It has happened while trying to save pages. If you save the page again, sometimes it will happen again, but usually you are then able to save the page. It has also happened sometimes while trying to access the Special:UserLogin page.

•MediaWiki 1.25.1
•PHP 5.5.28
•MySQL 5.5.45
•Semantic MediaWiki 2.3 alpha (54225eb)

**Comment by mwjames** [comment]
> It has happened while trying to save pages. If you save the page again, sometimes it will happen again, but usually you are then able to save the page. It has also happened sometimes while trying to access the Special:UserLogin page.

Unfortunately, this doesn't help much. Please provide a full stack trace [0] it may be that the some extension sent a null (via the Parser) where a Title is expected.

[0] https://semantic-mediawiki.org/wiki/Help:Identifying_bugs

**Comment by mwjames** [comment]
Maybe I know where this is coming from, anyhow a full stack trace would be good nevertheless.

**Comment by mwjames** [comment]
Expected to be fixed with dcdf0e2.

**Comment by mwjames** [comment]
Well, despite our efforts to test part of the code nothing beats the human in a real environment.

There are some other changes coming before the 2.3 release, please stay sharp and test as much as you can.

Thanks.

**Comment by cicalese** [comment]
Thank you!
