### ISSUE TITLE
Error when importing RDF

### ISSUE THREAD

**Issue by eyvzovaraz** [SemanticMediaWiki/SemanticMediaWiki#1156]
Hello,

I wanted to install RDFIO that could import RDF, but when I import RDF gives an error message: 

"Fatal error: Call to undefined method SMWExporter::decodeURI() inZ:\home\mw123.org\www\extensions\RDFIO\classes\RDFIO_ARC2StoreWrapper.php on line 88"

Please, HELP!
Thanks!

**Comment by mwjames** [comment]
The developer has been ask (as informed about the changes) to adjust the program in [0] which was closed because of inactivity, for more details see [0].

[0] https://github.com/samuell/RDFIO/issues/11
