### ISSUE TITLE
Properties disappear when using SRF tree together with TreeAndMenu

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#1166]
THIS ISSUE HAS ALREADY BEEN DISCUSSED ON MAILINGLIST

I see a strange behavior on one of our wikis where all semantic 
annotations for a page disappear when I use SRF tree inside a 
TreeAndMenu tree.

MW 1.25.2
SMW 2.2.2
SRF 2.2

$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

== Example ==

Materials that could be part of another Material like <Material A> <Is 
Part Of> <Material B>.

A page about "Concrete" shall show a tree with Materials. The 
Template:Material has

{{#tree:{{#ask: [[Category:Material]] | parent = Is Part Of | format = 
tree | limit=1000}}}}

This creates the correct tree. If you have a look at "Browse 
properties", all properties are there.

Now, if you refresh the page (&action=purge) all custom properties 
disappear from "Browse properties". Special properties like "Creation 
date" are still there. After a null edit, all properties are back. 
Strange...

== Test 1 ==

{{#ask: [[Category:Material]] | parent = Is Part Of | format = tree | 
limit=1000}}

-> No issues

== Test 2 ==

{{#tree:
* Test 1
** a
** b
}}
{{#ask: [[Category:Material]] | parent = Is Part Of | format = tree | 
limit=1000}}

-> No issues

Has anyone seen such a behavior?

I found a discussion on Github that might be related but has been marked 
as fixed:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/206

/Alexander

**Comment by gesinn-it** [comment]
Has been fixed by @mwjames

@@ -124,10 +124,14 @@ class ParserAfterTidy {
 	 * a static variable or any other messaging that is not persistent will not
 	 * work hence the reliance on the cache as temporary persistence marker
 	 */
 	private function checkForRequestedUpdateByPagePurge( $parserData ) {

+		if ( $parserData->getSemanticData()->getSubject()->getContextReference()
=== null ) {
+			return true;
+		}

**Comment by gesinn-it** [comment]
The patch works for me. Needs to be integrated.

**Comment by mwjames** [comment]
Fixed with  61d357d

**Comment by JeroenDeDauw** [comment]
`$parserData->getSemanticData()->getSubject()->getContextReference()` Demeter is going to jail someone:)

**Comment by mwjames** [comment]
>  Demeter is going to jail someone:)

Even though Demeter is my friend I thought I tease him a bit but of course we could go with `$parserData->getSubject()->getContextReference()`.
