### ISSUE TITLE
Test case query-02-01-concept.json

### ISSUE THREAD

**Issue by yoonghm** [SemanticMediaWiki/SemanticMediaWiki#1177]
My post was lost, here is the new one.

Except MySQL, PostgreSQL, MsSQL (at least) do not allow user to **ORDER BY** field(s) which is(are) not in the **SELECT** column(s) [0] . It is a good read and must read.

For the test case ```query-02-01-concept.json```, the query is something like that
```
SELECT DISTINCT t2.smw_title     AS t,
                t2.smw_namespace AS ns
  FROM          "smw_object_ids" AS t2 
 INNER JOIN     "smw_fpt_inst"   AS t0 
    ON          t2.smw_id = t0.s_id 
 WHERE          (t0.o_id = '53') 
 ORDER BY       t2.smw_sortkey 
   ASC 
 LIMIT 55 
OFFSET 0;
```

Alternatives
------------------
* Not sort by ```smw_object_ids.smw_softkey```
```
SELECT DISTINCT t2.smw_title     AS t,
                t2.smw_namespace AS ns
  FROM          "smw_object_ids" AS t2 
 INNER JOIN     "smw_fpt_inst"   AS t0 
    ON          t2.smw_id = t0.s_id 
 WHERE          (t0.o_id = '53') 
 ORDER BY       t, ns 
   ASC 
 LIMIT 55 
OFFSET 0;
```
* Do not support sort on non-select column as it does really make sense. From the records in my current database, I could not understand the reason to sort based on ```smw_object_ids.smw_sortkey```.

[0] http://www.programmerinterview.com/index.php/database-sql/sql-select-distinct-and-order-by/

**Comment by yoonghm** [comment]
Any one can advise?

**Comment by mwjames** [comment]
I do think we always select with a `sortkey` on instant queries [0], where is your cited example come from?

If you use the `debug` output from 2.2.2 then this hides some information, #1171 fixes this for 2.3.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/QueryEngine.php#L415-L416

**Comment by JeroenDeDauw** [comment]
Am I understanding correctly that this is currently not working properly on SQLite?

**Comment by mwjames** [comment]
> Am I understanding correctly that this is currently not working properly on SQLite?

? Why, this issue relates to postgres #781

**Comment by JeroenDeDauw** [comment]
> ? Why, this issue relates to postgres #781

Because...

> Except MySQL, PostgreSQL, MsSQL

Thanks for clarifying
