### ISSUE TITLE
Feature request: syntax for hierarchical inheritance

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1179]
This request stems from a recent thread on the mailinglist (Nabble: http://wikimedia.7.x6.nabble.com/inheritance-in-hierarchies-again-td5052571.html)

I will just cite the suggestions made by John McClure (aka Hypergrove), which overall seem quite reasonable to me:

> I think it'd help us all to modify SMW #ask syntax to handle
> these chains? It's easy to believe many need to select pages based on a
> transitive property predicate and second, to print all values of a
> transitive property for each 'root' page in a query result.
> 
> _Transitive predicates. *Tests for whether a page
>   [[pn::+]]  = has 1+ 'pn' relations
> [[pn_::+]] = has 1+ 'pn' relations (implicit wildcard)
> [[pn?::+]] = has 1+ 'pn' relations AND that no 'pn' relation has any
> 'pn' relation
> [[pn+::+]] = has 1+ 'pn' relations AND that some 'pn' relation has 1+
> 'pn' relations
> 
> _Transitive property values. *For each page in a result set_,
> _|?pn   = prints all 'pn' relations (no transitives)
> |?pn_ = prints all 'pn' relations (implicit wildcard, no transitives)
> |?pn? = prints all 'pn' transitive relations - once-removed (parent)
> transitives
> |?pn+ = prints all 'pn' transitive relations  - maximum transitivity

P.S. John takes into account a multilingual scenario as follows:

> This syntax works with multilingual syntax options I have sketched.
> Following, a query yields all pages that have a French-qualified value
> for property "Located in". It then lists the object's French and English
> values, with maximum transitivity for each, for the property.
> 
> {{#ask: [[Located in @fr *:: +]]
> |?Located in @fr += @en=Located in<br/>(French) @fr=Situe
> dans<br/>(Francais)
> |?Located in @en += @en=Located in<br/>(English) @fr=Situe
> dans<br/>(Anglais)
> }}

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
