### ISSUE TITLE
Error: Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance of Language, instance of StubUserLang given

### ISSUE THREAD

**Issue by Alexia** [SemanticMediaWiki/SemanticMediaWiki#1181]
Mediawiki 1.23.10
PHP 5.4.39
SemanticMediaWiki 2.2.2
http://hearthstone.gamepedia.com/Special:Version

This occurs when calling the MediaWiki API to parse wikitext.

Example URL: http://hearthstone.gamepedia.com/api.php?action=tooltip&format=json&options=text|title|image&contentmodel=wikitext&target=Goldshire Footman

The APIQueryTooltip class is part of the TippingOver extension.  https://github.com/oOeyes/TippingOver/

Catchable fatal error: Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance of Language, instance of StubUserLang given, called in extensions/SemanticMediaWiki/includes/parserhooks/ParserFunctionFactory.php on line 99 and defined in extensions/SemanticMediaWiki/includes/formatters/MessageFormatter.php on line 47

```
Call Stack
#   Time    Memory  Function    Location
1   0.0017  261080  {main}( )   ../api.php:0
2   0.3072  19677112    ApiMain->execute( ) ../api.php:86
3   0.3072  19677400    ApiMain->executeActionWithErrorHandling( )  ../ApiMain.php:334
4   0.3124  20143720    ApiMain->executeAction( )   ../ApiMain.php:363
5   0.3182  20685624    APIQueryTooltip->execute( ) ../ApiMain.php:913
6   0.3183  20688752    APIQueryTooltip->addResults( )  ../ApiQueryTooltip.php:149
7   0.3183  20689288    APIQueryTooltip->getTooltipTitleText( ) ../ApiQueryTooltip.php:116
8   0.3250  21242968    Message->parse( )   ../ApiQueryTooltip.php:57
9   0.3250  21243064    Message->toString( )    ../Message.php:720
10  0.3901  22607064    Message->parseText( )   ../Message.php:661
11  0.3902  22607232    MessageCache->parse( )  ../Message.php:963
12  0.4468  27181112    Parser->parse( )    ../MessageCache.php:1070
13  0.4516  27566808    Parser->internalParse( )    ../Parser.php:395
14  0.4516  27567744    Parser->replaceVariables( ) ../Parser.php:1216
15  0.4562  27991976    PPFrame_DOM->expand( )  ../Parser.php:3153
16  0.4564  27999232    Parser->braceSubstitution( )    ../Preprocessor_DOM.php:1113
17  0.4750  29405128    PPFrame_DOM->expand( )  ../Parser.php:3492
18  0.4751  29412368    Parser->braceSubstitution( )    ../Preprocessor_DOM.php:1113
19  0.4751  29412704    PPFrame_DOM->expand( )  ../Parser.php:3250
20  0.4752  29417368    Parser->argSubstitution( )  ../Preprocessor_DOM.php:1132
21  0.4752  29417864    PPTemplateFrame_DOM->getArgument( ) ../Parser.php:3946
22  0.4752  29417912    PPTemplateFrame_DOM->getNumberedArgument( ) ../Preprocessor_DOM.php:1536
23  0.4753  29418104    PPFrame_DOM->expand( )  ../Preprocessor_DOM.php:1518
24  0.4753  29423640    Parser->braceSubstitution( )    ../Preprocessor_DOM.php:1113
25  0.4755  29426224    Parser->callParserFunction( )   ../Parser.php:3336
26  0.4761  29427544    call_user_func_array ( )    ../Parser.php:3620
27  0.4761  29428400    SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}( )  ../Parser.php:3620
28  0.4767  29471920    SMW\ParserFunctionFactory->newShowParserFunction( ) ../HookRegistry.php:117
29  0.4788  29577144    SMW\MessageFormatter->__construct( )    ../ParserFunctionFactory.php:99
```

**Comment by mwjames** [comment]
> 9   0.3250  21243064    Message->toString( )    ../Message.php:720
10  0.3901  22607064    Message->parseText( )   ../Message.php:661
11  0.3902  22607232    MessageCache->parse( )  ../Message.php:963

Enforcing correct tying is __not the issue__ here but its seems  `MessageCache->parse( )` sends a `StubUserLang` instead of an expected `Language` object. We should probably disallow show/ask to be executed in a `Message::parse` context as done in [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/ParserAfterTidy.php#L58-L62

**Comment by mwjames** [comment]
Maybe you can try the fowling for your 2.2* [0] as it only appears in your environment with `APIQueryTooltip`.

```
		$parserFunctionDefinition['show'] = function( $parser ) {

			if ( $parser->getOptions()->getInterfaceMessage() ) {
				return '';
			}
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.2.x/src/MediaWiki/Hooks/HookRegistry.php#L114-L116

**Comment by Alexia** [comment]
That does fix the issue and allows API calls to go through.

The code in TippingOver that causes this issue:

$tooltipTitle - new Title object from the raw page title.
WikiTooltips::getTooltipWikiText( $tooltipTitle  ) returns "{{".$title->getPrefixedText()."}}" to be parsed.

```php
  private function getParsedText( $tooltipTitle ) {
    global $wgParser;
    
    $parserOptions = new ParserOptions();
    $parserOptions->setEditSection( false );
    $output = $wgParser->parse( WikiTooltips::getTooltipWikiText( $tooltipTitle  ), $tooltipTitle, $parserOptions );
    return $output->getText();
  }
```

The parse call seems fairly standard so I am not sure if this is a result of an error in TippingOver setting up the parse call or ultimately an issue in SMW.(Even though it seems that way.)

**Comment by mwjames** [comment]
> up the parse call or ultimately an issue in SMW.(Even though it seems that way.)

It isn't really an issue in SMW as a proper object invocation is expected (enforced by the type hinting).

> WikiTooltips::getTooltipWikiText( $tooltipTitle ) returns "{{".$title->getPrefixedText()."}}" to be parsed.

I'm feeling the pain ...

```
    if ( $this->mParser === null && isset( $wgParser ) ) {
      $wgParser->firstCallInit();
      $class = $wgParserConf['class'];
      if ( $class == 'ParserDiffTest' ) {
        $this->mParser = new $class( $wgParserConf );
      } else {
        $this->mParser = clone $wgParser;
      }
    }
```
https://github.com/oOeyes/TippingOver/blob/fec56ac4ec42105724efebaf327864499c4e1e11/includes/WikiTooltips.php#L338-L361

**Comment by oOeyes** [comment]
No, I'm sure the error is happening at line 56, when MediaWiki:To-tooltip-page-name is processed through the internal message API. That's where #show is being called to find the correct page title. There shouldn't be any titles being returned that refer to pages that contain a #show or #ask. It should all be image links by that point.

I intend to refactor this tonight to use a similar parsing approach as getParsedText. I'll replace the message parameter manually. The #ask and #show should no longer be parsed through MessageCache that way.

**Comment by Alexia** [comment]
@mwjames Thank you for your help on this.

**Comment by oOeyes** [comment]
Just adding a note that I've edited MediaWiki:To-tooltip-page-name to comment out the #shows for the time being, so the example URL will no longer generate the error.

Thanks for your help.

**Comment by mwjames** [comment]
There is no further actionable task for the project to handle hence closing this. As for the use of `StubUserLang` in MW core, see [0].

[0] https://gerrit.wikimedia.org/r/#/c/382067/
