### ISSUE TITLE
Increase ID signature length from INT(8) to INT(14)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1184]
ID's (those that identify a property, value, or subject) are currently specified as INT(8) and since those numbers are auto incremented they will grow (which is different from MW's page ID as subobjects or queries will also be identified by an ID found in the `smw_object_ids` table).

@kghbln @thingles What is the max ID you can currently find in your `smw_object_ids` table (just to see what wiggle room we have)?

refs #1183

**Comment by JeroenDeDauw** [comment]
2**(8*8) = 18446744073709551616
2**(8*14) = 5192296858534827628530496329220096

**Comment by mwjames** [comment]
> 2(8*8) = 18446744073709551616
2(8*14) = 5192296858534827628530496329220096

I'm aware of that but starting with 2.3 we will drop id's that are deleted from the table (before they remained and could have been reused but that just causes unexpected behaviour) which means we will see a slight increase in ID turn over depending on the usage pattern. 

SQLIte and Postgres have naturally no limit but MySQL SQLStore has while this doesn't warrant any  issue but to be on the safe side.

**Comment by mwjames** [comment]
> Where is this 14 coming from?

I don't know, just pulled that from the top of my head (this how we do things around SMW like a magician __numbers by intuition__ )

**Comment by mwjames** [comment]
MW's page ID is defined as INT(10)

**Comment by JeroenDeDauw** [comment]
Is this supported by all MySQL versions we care about? Also, will this have any real performance impact? And what about migration cost - will this be significant for people that have a wiki with lots of data in it?

**Comment by mwjames** [comment]
> Is this supported by all MySQL versions we care about? Also, will this have any real performance impact? And what about migration cost - will this be significant for people that have a wiki with lots of data in it?

One reason for this issue is the evaluate the proposal whether it makes sense or not.

 > will this be significant for people that have a wiki with lots of data in it?

Conversion takes times (but it would be a on-time conversion) and therefore should be (if it is done) targeted for 3.0.

**Comment by kghbln** [comment]
About 6,500,000 for the biggest one so this looks like plenty of room.

**Comment by JeroenDeDauw** [comment]
The current space is more than 6,500,000 times 6,500,000 times 6,500,000 :)

**Comment by mwjames** [comment]
> @thingles will have more :)

and Wikiocity shows 342,740,196 PV which is tenfold of that what WikiApiary displays as PV (29,906,412) and this doesn't say anything about the internal ID counter state.

**Comment by thingles** [comment]
WikiApiary isn't much higher, 8,442,042.

```
mysql> select max(smw_id) from smw_object_ids;
+-------------+
| max(smw_id) |
+-------------+
| 8442042     |
+-------------+
1 rows in set (0.09 sec)
```

**Comment by kghbln** [comment]
> About 6,500,000 for the biggest one so this looks like plenty of room.

I am at about 11,500,000 for this wiki now.
