### ISSUE TITLE
Issues with "sandbox.semantic-mediawiki.org"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1186]
This tracking issue is intended for reporting issues with the above mentioned wiki, e.g. it is down etc.

**Comment by kghbln** [comment]
I am closing this for now. If there is an issue this one should be reopened.

**Comment by kghbln** [comment]
Scheduled downtime tomorrow 2015-10-21 for about 10 minutes between 10 and 11 pm CET

**Comment by kghbln** [comment]
There is currently 2015-12-07 an issue with the server hosting sandbox which started at 15:15 UTC. This is being worked on and hopefully the machine is back up running soon.

**Comment by kghbln** [comment]
@mwjames Please ping me here as soon as [this](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1335#issuecomment-169837796) was merged for me to do the "update.php" run.

**Comment by kghbln** [comment]
Semantic Form is currently broken, thus the site is down: [T123308](https://phabricator.wikimedia.org/T123308)

**Comment by mwjames** [comment]
@kghbln As for the Chameleon-skin, maybe copy `/skins/chameleon/layouts/fixedhead.xml` to a local folder so that:

```
$egChameleonLayoutFile = __DIR__ . `myLocation/sandbox-fixedhead.xml';
```

and after [0] modify the content of `sandbox-fixedhead.xml` so that the language bar turns up in the NavMenu.

```
@@ -24,11 +24,11 @@ with this program. If not, see <http://www.gnu.org/licenses/>.
 -->
 <structure>
 
 	<component type="NavbarHorizontal" fixed="1">
 		<component type="Logo" position="head"></component>
-		<component type="NavMenu" flatten="navigation" showTools="no" showLanguages="no"></component>
+		<component type="NavMenu" flatten="navigation" showTools="yes" showLanguages="yes"></component>
 		<component type="PageTools" position="right" hideSelectedNameSpace="yes"></component>
 		<component type="SearchBar" position="right"></component>
 		<component type="PersonalTools" position="right"></component>
 	</component>
 
@@ -45,11 +45,11 @@ with this program. If not, see <http://www.gnu.org/licenses/>.
 			</cell>
 		</row>
 
 		<row>
 			<cell span="12">
-				<component type="ToolbarHorizontal" hideTools="no" hideLanguages="no"></component>
+				<component type="ToolbarHorizontal" hideTools="yes" hideLanguages="yes"></component>
 			</cell>
 		</row>
 
 		<row>
 			<cell span="12">
```

[0] https://gerrit.wikimedia.org/r/#/c/273982/2

**Comment by kghbln** [comment]
Hmm, the second stampede on the wiki this week. One core and 2 GB RAM apparently are not enough to cope with this. Thinking of moving the wiki to the OSDA server which provides much more power. On the other hand. If this one is down, everything is down.

**Comment by mwjames** [comment]
> Thinking of moving the wiki to the OSDA server which provides much more power. On the other hand. If this one is down, everything is down.

What about https://www.cloudflare.com/ free plan with basic DDoS protection?

**Comment by kghbln** [comment]
> What about https://www.cloudflare.com/ free plan with basic DDoS protection?

Thanks for the tip. Indeed something to consider. I will try it with another wiki which DNS I control and do sandbox in a next step.

**Comment by kghbln** [comment]
Re: https://github.com/SemanticMediaWiki/SemanticMaps/pull/52#issuecomment-204372088
> However, the sandbox Maps is still on 3.4.1

Dunno why: [that's the "composer.local.json"](http://sandbox.semantic-mediawiki.org/wiki/SMW_Sandbox:Setup_information) I am using. Should all be in there.

**Comment by mwjames** [comment]
> Dunno why: that's the "composer.local.json" I am using. Should all be in there.

@JeroenDeDauw @kghbln  I could be wrong but I think the issue is that Maps is not directly installed via Composer and only added as a dependency of SM which uses the stable 3.4.1 and not the `@dev` version.

https://igor.io/2013/02/07/composer-stability-flags.html

**Comment by kghbln** [comment]
>  I could be wrong but I think the issue is that Maps is not directly installed via Composer and only added as a dependency of SM which uses the stable 3.4.1 and not the @dev version.

You are right. Have not thought about this. We are now on master. In a production environment I'd leave it to composer to do the dependencies. In our case we should do it directly.

**Comment by JeroenDeDauw** [comment]
I'd always include Maps in composer.json, even for production, as this is something your wiki comes to rely on (Maps stuff is exposed to the user). That is quite different than libraries and whatnot

**Comment by kghbln** [comment]
> I'd always include Maps in composer.json, even for production, as this is something your wiki comes to rely on

Thanks for the advice. Will do! :)

**Comment by kghbln** [comment]
I am planning on upgrading the server this afternoon to Debian 8. I expect a downtime of about two hours. Never done this before so touching wood. If nothing fails we will be getting MariaDB 10.0.23, PHP 5.6.19 and Apache 2.4.10. If something fails it will probably take about a week to be online again.

**Comment by kghbln** [comment]
So I upgraded to Debian 8. Just guess which part of the upgrade caused trouble? Yeah, Apache. This software seems to be more ridiculous that I thought. It took me 25 of the 70 minutes downtime just to get it running again and I am just avoiding the issue. Another thing. MariaDB did not upgrade. So this is the next thing on my list. I feel fatigued and I am apparently pretty grumpy. Meh, old and grump. Not a combination one likes.

**Comment by JeroenDeDauw** [comment]
Apache...

![cant-deal-with-it](https://cloud.githubusercontent.com/assets/146040/14407575/ee81a68e-fece-11e5-910b-a222d45270e3.gif)

**Comment by kghbln** [comment]
Sandbox needs to go MW 1.26.x - eta Mid May 16

**Comment by kghbln** [comment]
> Sandbox needs to go MW 1.26.x - eta Mid May 16

Now planning to go MW 1.27.0-rc0 this weekend. I think we should permanently stay with "fr" as the wiki instances language. This adds enough language complication while is is still a language.

**Comment by mwjames** [comment]
> I think we should permanently stay with "fr" as the wiki instances language.

Yes, since we are getting closer on providing support for [0]. Having FR helped to uncover some unexpected behaviour while merging on the "tour de ...".

[0] https://www.semantic-mediawiki.org/wiki/Localization_and_multilingual_content

**Comment by kghbln** [comment]
> Now planning to go MW 1.27.0-rc0 this weekend.

I really need to do this now since Sematic Scribunto @dev requres Scribunto @dev which requires MW 1.27.0-wmf.23

**Comment by kghbln** [comment]
I just upated sandbox to 1.27.0-rc0 however it is still not possible to install SemanticScribunto

```
Problem 1
    - mediawiki/semantic-scribunto 1.x-dev requires mediawiki/scribunto dev-wmf/1.27.0-wmf.23 -> satisfiable by mediawiki/scribunto[dev-wmf/1.27.0-wmf.23] but these conflict with your requirements or minimum-stability.
    - mediawiki/semantic-scribunto dev-master requires mediawiki/scribunto dev-wmf/1.27.0-wmf.23 -> satisfiable by mediawiki/scribunto[dev-wmf/1.27.0-wmf.23] but these conflict with your requirements or minimum-stability.
    - Installation request for mediawiki/semantic-scribunto @dev -> satisfiable by mediawiki/semantic-scribunto[dev-master, 1.x-dev].
```
We lost the SemanticFormsSelect and Syntaxhighlight on the way. This is painful and I am fed up for today. The future will show.

**Comment by kghbln** [comment]
> As for the Chameleon-skin

@mwjames Done! Syntaxhighlight is back up too.

**Comment by mwjames** [comment]
> @mwjames Done! Syntaxhighlight is back up too.

Nice.

It seems that the AuthManager changes are responsible for:

![image](https://cloud.githubusercontent.com/assets/1245473/15993440/9604787a-30e6-11e6-92c1-cb157b1d5712.png)

**Comment by mwjames** [comment]
>  however it is still not possible to install SemanticScribunto

`mediawiki/semantic-scribunto @dev` cannot be used because the git ref is from `2014-12-17 01:34 UTC` [0] maybe using `dev-REL1_27` [1] would be a better match.

Unfortunately, WMF does not use proper release tags, so this a bit of a gamble. 

[0] https://packagist.org/packages/mediawiki/scribunto
[1] https://packagist.org/packages/mediawiki/scribunto#dev-REL1_27

**Comment by kghbln** [comment]
> It seems that the AuthManager changes are responsible for:

Indeed I saw this too today. Will report this.

> Unfortunately, WMF does not use proper release tags, so this a bit of a gamble. 

Indeed. I guess it will be best to use `dev-REL1_27` and switch to `dev-REL1_28` as soon as a `1.28.0-alpha` is tagged which will probably happen in September. I will upgrade to 1.28 at that time.

**Comment by mwjames** [comment]
> It seems that the AuthManager changes are responsible for:

@tgr The AuthManager has been merged to 1.27 and our sandbox got updated to 1.27 but now encounters several issues [0, 1] with the ConfirmAccount extension. It would be marvellous if those issues could be resolved quickly to ensure we don't have to write excuses [2] to users due to [1]. The ConfirmAccount extension provides measures to avoid spammers from creating unsolicited accounts but no being able to create standard accounts seems rather counter-productive.

[0] https://phabricator.wikimedia.org/T137723
[1] https://phabricator.wikimedia.org/T137843
[2] http://sandbox.semantic-mediawiki.org/wiki/Discussion_utilisateur:Jhamell_sandbox

**Comment by kghbln** [comment]
@JeroenDeDauw @mwjames What about creating a "meta repo" called "infrastructure" which helps us divide everything in this issue and what we labelled with infrastructure in a more orderly manner? This also will help others report issues, requests or ideas more easily I believe.

**Comment by kghbln** [comment]
Ping @JeroenDeDauw @mwjames https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1186#issuecomment-226007856 :)

**Comment by mwjames** [comment]
I'd say create a `semantic-mediawiki.org` repo then each single issue can be tracked and is not bound to the `SemanticMediaWiki` repo.

**Comment by mwjames** [comment]
... as in "Organizational meta-repository surrounding the semantic-mediawiki.org domain (including the sandbox) "

**Comment by JeroenDeDauw** [comment]
Both are fine with me

**Comment by kghbln** [comment]
Thanks @JeroenDeDauw and @mwjames Today I created the [semantic-mediawiki.org "repo"](https://github.com/SemanticMediaWiki/semantic-mediawiki.org) for [tracking such issues](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues) in the future.
