### ISSUE TITLE
Provide tarball building service

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1187]
**Problem**

Since we started using Composer, it has become more challenging for users that cannot run Composer on their server to install and upgrade SMW. While we have continued providing release tarballs, these users have still been forced to run Composer somewhere and upload the result to their server if they also wanted to use certain popular SMW extensions such as Semantic Result Formats.

**Solution**

We could try to provide tarballs with combinations of extensions, though this is very cumbersome. Having a service where users can download SMW, combined with the extensions of their choice, that then builds the tarball on demand would help these users and not be a pain to maintain.

**Work done so far**

I have created an experimental tool to provide such a service. The [code is on GitHub](https://github.com/JeroenDeDauw/TarballDownloader) and a [live version can be found on labs](https://tools.wmflabs.org/nyandata/). (Note that the tarballs you get there presently contain the requested extensions, though not yet in a format easily consumable by the target user group.)

**Remaining task** (help wanted)

While the tool provides minimal functionality, it misses a real user interface and a way for users to specify which extensions they want. I'd like some help with this. To be more precise, I'd like someone to create the layout part of the user interface. So the HTML, CCS and JS, but without doing the part of hooking this up to the application itself, which I'm happy to do. Suggestion of features to have in the UI:
- List of extensions and a way to select those the user wants to install
- When the user clicks the download thing, something to indicate that they should wait for the build to complete (including the disabling of starting a new download)
- Whatever else you think makes sense, though double check with me if you want to be sure it can actually be made to work

Have a look at the `templates` directory of [TarballDownloader](https://github.com/JeroenDeDauw/TarballDownloader) and see the README there for instructions on how to run the service yourself. It uses [Silex](http://silex.sensiolabs.org/), which includes the [Twig templating engine](http://twig.sensiolabs.org/).

A service like this is also be useful for other extensions, so not making it too SMW specific would be nice.

**Another way to help**

Labs is not terribly fast. If you can host this service on a reliable machine that is not so slow, that'd be great. As this service pulls in code based on user actions, I strongly advice against putting it on a server you do not want to have compromised. While I do not see any way to use the service to compromise the server it runs on, it seems prudent to isolate it due to the nature of what it does.

**Comment by JeroenDeDauw** [comment]
Ping @SemanticMediaWiki/testers - while not a testing task, this is something you might be interested in helping with.

**Comment by kghbln** [comment]
@JeroenDeDauw This one should go to the front burner. I think it is essential to have such a service. There are just too many people stuck with the latest release of Semantic Bundle without any chance to upgrade to a decent version of SMW and related extensions.

As for my personal testing in the past (some while now). After about five minutes without response I always gave up.

**Comment by JeroenDeDauw** [comment]
Yeah... it's no longer loading for some reason. Getting the latest stable version used to take maybe a minute when not run before and maybe 10 secs afterwards...

**Comment by kghbln** [comment]
I guess that's something for the new server to host. Alternatively we just create different  packs of popular semantic mediawiki software ("individual file releases"), tar them and add them to a folder to which we provide public access for download in case this does not work out.

**Comment by kghbln** [comment]
What about tackling this somehow? Since the Semantic Bundle is rapidly deteriorating ...

**Comment by JeroenDeDauw** [comment]
You could send another mail to the list and see if someone wants to pick this up.

**Comment by kghbln** [comment]
I actually was hoping for a code sprint by you since the ground work is already done. ;) I doubt that someone will pick this up. Doing translations is to much of a pain for most users.

**Comment by mwjames** [comment]
I do not think something will happen here in a foreseeable future hence moving this to [0] in case someone wants to pick the tab.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/2
