### ISSUE TITLE
Fix fixmes in SMWRDFXMLSerializer::serializeExpCollection

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1196]
![that-fixme](https://cloud.githubusercontent.com/assets/146040/10336495/7656e7a8-6cf9-11e5-997b-df7d0fbcf9c8.jpg)

**Comment by mwjames** [comment]
The code isn't currently tested (or used) but before trying to unchain the FIXME, I'd rather have the exporter-concept PR merged (is in my queue list and will hit the collection serialization code path) before a change is done here.

![image](https://cloud.githubusercontent.com/assets/1245473/10336785/99889f58-6cfb-11e5-80d5-9e404e8cf3f3.png)

**Comment by JeroenDeDauw** [comment]
It is not used? Then lets remove it?

**Comment by mwjames** [comment]
> It is not used? Then lets remove it?

No, it will be by the time my exporter-concept PR has been merged (that's why I'd like to wait before anything is done to this class so tests are run against the code path before a change is applied).

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
