### ISSUE TITLE
SemanticData access from an extension (or how to add property values)?

### ISSUE THREAD

**Issue by nilsdornblut** [SemanticMediaWiki/SemanticMediaWiki#1202]
About 5 years before we have developed a custom MW tag extension to create flowcharts. For this purpose we use a self-defined domain specific language to create process diagrams with links to other articles. As the result, we get an image-map consisting of image and HTML code generated. This will displayed on the wiki page. In addition, certain semantic properties deposited on the side that can’t appear directly in the source code of the page. We have had no problem with reload or refreshing the page. The properties were always there and were always stored correctly.

We use the following code:

```php
SMWParseData::addProperty("Has product",
	$value,
	false, 				// No caption
	self::$wikiParser, 		// Mediawiki parser
	true );				// Store data in the database
```
Problem: http://semantic-mediawiki.org/doc/classSMWParseData.html

THIS CLASS IS OBSOLETE AND SHOULD NOT BE USED BEYOND SMW 1.8. THIS CLASS WILL BE REMOVED IN SMW 1.10.

Therefore, we need an alternative. Do you know an code-example for that case? Or do we have to use SMW code and parse via the MW-parser?

Thanks!

**Comment by mwjames** [comment]
[0, 1] shows some example on how extensions can add semantic data without violating "chain of custody" but for a quick review you can (or better need):

```php
	// You should have access to a Parser ($parser) object when creating
	// a custom parser function or tag hook

	// Create in-memory ParserOutput transfer object
	$parserData = ApplicationFactory::getInstance()->newParserData(
		$parser->getTitle(),
		$parser->getOutput()
	);

	$subject = $this->parserData->getSubject();

	// Add individual instances
	foreach ( $values as $value ) {
		$dataValue = DataValueFactory::getInstance()->newPropertyValue(
			$property, // Text value
			trim( $value ), // Text value
			false,
			$subject
		);

		// Adds the object to the SemanticData container you could also use
		// $parserData->getSemanticData()->addPropertyObjectValue( ...)
		$parserData->addDataValue( $dataValue );
	}

	// Ensures that objects are pushed to the ParserOutput
	$parserData->pushSemanticDataToParserOutput();
``` 

See also the [#set](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/parserhooks/SetParserFunction.php#L76-L102) parser function code.

While this seems is bit more work as `SMWParseData::addProperty` we no longer support arbitrary injection of data hence the stress on separate interfaces (as we rely on SRP to distinguish application logic and making testing much easier when [IoC](https://en.wikipedia.org/wiki/Inversion_of_control) is executed). 

[0] https://github.com/SemanticMediaWiki/SemanticCite/blob/master/src/ParserFunctionFactory.php#L32-L65

[1] https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/blob/master/src/LanguageLinkAnnotator.php#L58-L77

![image](https://cloud.githubusercontent.com/assets/1245473/9608489/e38026ec-50ce-11e5-9239-46fa42a8b413.png)

**Comment by mwjames** [comment]
Issue linked in https://semantic-mediawiki.org/wiki/Help:Data_access

**Comment by nilsdornblut** [comment]
It works great! Thanks for your quick response and help.

Two little things:

```php
$subject = $this->parserData->getSubject(); 
```
should be:

```php
$subject = $parserData->getSubject();
```

insert on top for used classes:
```php
use SMW\ApplicationFactory;
use SMW\DataValueFactory;
```

**Comment by mwjames** [comment]
> It works great! Thanks for your quick response and help.

Closing this issue in anticipation that the question has been answered and is linked on-wiki.
