### ISSUE TITLE
Import vocabulary documentation

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1203]
I went through some trouble to update the https://semantic-mediawiki.org/wiki/Help:Import_vocabulary documentation.

@kghbln @jaideraf I would be nice if you could give this a review and a nudge of improvement .

User https://semantic-mediawiki.org/wiki/Special:Contributions/Alantygel added https://semantic-mediawiki.org/wiki/Help:Import_vocabulary/Step-by-step_on_how_to_import_a_vocabulary (I moved it to this place) might need a re-read.

refs #464, #891

**Comment by jaideraf** [comment]
Hi, I will see what I can do about it.
There is so much bullshit in this page[1] that I will have to, practically, delete it.

[1] https://semantic-mediawiki.org/wiki/Help:Import_vocabulary/Step-by-step_on_how_to_import_a_vocabulary

**Comment by jaideraf** [comment]
@mwjames, done!
@kghbln, could you please have a look at [1]? My English is not very good... 

[1] https://semantic-mediawiki.org/w/index.php?title=Help:Import_vocabulary/Step-by-step_on_how_to_import_a_vocabulary&oldid=41156

**Comment by mwjames** [comment]
Nicely done.

![image](https://cloud.githubusercontent.com/assets/1245473/10411509/edd0b0e0-6f68-11e5-9604-fef63b8ff62c.png)

I also pushed a design tweak for the infobox to be less distracting (I hope) when reading some of the texts.

![image](https://cloud.githubusercontent.com/assets/1245473/10411522/452f2164-6f69-11e5-97b6-2db74170d631.png)

**Comment by jaideraf** [comment]
@mwjames, beautiful :+1: 
In MediaWiki:Common.css:
```css
#smworgtable-toc #toc {
	border: 0px solid #AAA;
	background-color: #ffffff;
	font-size: 100%;
	width: 260px;
} 
```
please, change (I cannot edit the MW namespace)
```css
	width: 260px;
```
to
```
	width: 220px;
```
to correct the border of the infobox. :sunglasses:

**Comment by mwjames** [comment]
> please, change (I cannot edit the MW namespace)

Done.

Thanks for the re-write and I hope with the step-by-step + diagram the import content becomes it bit more self-explanatory.

**Comment by kghbln** [comment]
:+1:
