### ISSUE TITLE
canonical boolean values

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1204]
There seems to be no common internationalization ground for boolean values.
According to https://semantic-mediawiki.org/wiki/Help:Type_Boolean#Booleans_in_other_languages
The settings are localized via the Smw_true_words and Swm_false_words pages.

So if content is transferred from one wiki (even if it is a specifically designed internationalized master wiki) to a standard SMW wiki the booleans will not make it correctly to the target wiki if that wiki is not prepared for it. 

Yaron had told me that 0 and 1 would be standard true and false values internationally but on a wiki today I had the experience that this did not seem to be the case.

Look e.g. for 
https://semantic-mediawiki.org/wiki/MediaWiki:Smw_true_words
which has german wahr in it and 
https://semantic-mediawiki.org/wiki/MediaWiki:Smw_false_words
which has german falsch in it

which only seems to be a workaround. I think there should be a canonical version of pages and a way to make sure that also in semantic forms and such the canonical storage can be choosen. 

I think x,- might be a good international canonical choice with x=true and -=false

**Comment by mwjames** [comment]
> The settings are localized via the Smw_true_words and Swm_false_words pages.

It uses the content language as codified in [0] and which of course can be different on different wikis while the storage is being carried out as nominal representation of 0 or 1.

>  I think there should be a canonical version of pages and a way to make sure that also in semantic forms and such the canonical storage can be choosen.

If SF needs special treatment then this has to be done on the SF side. After reading above comments, I'm still unclear about the real issue and what is expected.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/datavalues/SMW_DV_Bool.php#L125-L129

**Comment by mwjames** [comment]
> which has german wahr in it and / which has german falsch in it

@kghbln To avoid any misunderstanding (and as the German language got mentioned above) maybe you can help clarify the issue.

**Comment by kghbln** [comment]
As I understand it, what is requested here is a commonly understood boolean value for true or false independent from the wiki's install lanuage and independent from what was added to the two system messages mentioned. So every value added to one of the system messages is also understood as 0 or 1 as stored in the database, no matter which value it is in particular.

**Comment by mwjames** [comment]
So every value added to one of the system messages is also understood as 0 or 1 as stored in the database, no matter which value it is in particular.

```
		$boolvalue = false;
		if ( $lcv === '1' ) {
			$boolvalue = true;
		} elseif ( $lcv === '0' ) {
			$boolvalue = false;
		} elseif ( in_array( $lcv, explode( ',', wfMessage( 'smw_true_words' )->inContentLanguage()->text() ), true ) ) {
			$boolvalue = true;
		} elseif ( in_array( $lcv, explode( ',', wfMessage( 'smw_false_words' )->inContentLanguage()->text() ), true ) ) {
			$boolvalue = false;
		} else {
			$this->addError( wfMessage( 'smw_noboolean', $value )->inContentLanguage()->text() );
		}
```

It is commonly understood as either `true` or `false` otherwise an error message is generate if it doesn't match the condition above.

I still don't understand the issue, if `smw_false_words` or `smw_true_words` are not maintained for the content language selected then of course it violates above precondition and will not be recognized as a valid value.

**Comment by mwjames** [comment]
if you need a programmatic way to access the canonical (0, 1) value representation then you have to use `DIBoolean::getWikiValue`.

**Comment by WolfgangFahl** [comment]
the smw_false_words and smw_true_words issue was part of what was hitting me. I still have to test if the 0/1 issue persists on the Wiki that initially brought up the issue. When entering value=1 the value was shown as not set in Semantic Forms - I'll have to check if it's a forms issue then ..

**Comment by jongfeli** [comment]
When you maintain a page, that contains Boolean values, with SF it will store them on your page as **Yes** or **No**. Only when they are assigned to a property will SMW "translate" this to **true** or **false** and makes them Boolean. The parameter that transfers the value to your template is not Boolean but text. This means that if you have any logic done in your template that uses this parameter you will need to do this on the text **Yes** or **No**.

You could also check your default Boolean values in your forms, when you have them. If they are not on ```MediaWiki:Smw_true_words``` or ```MediaWiki:Smw_false_words``` SF will not compute and show you an empty check box when, for example, the parameter value is set to 1.

As far as I know you can not tell SF which Boolean "style" you want to use in your forms but it could very well be that I missed something :)

**Comment by mwjames** [comment]
As per discussion above.

**Comment by WolfgangFahl** [comment]
This is not solved. There is no canoncial boolean value defined to solve the issue of a transferring content from one wiki to another.

**Comment by mwjames** [comment]
>  There is no canoncial boolean value defined to solve the issue of a transferring content from one wiki to another.

It is solved in a way that methods are provided as described above and unless there is a compelling use case (which I haven't seen) this is solved from dev perspective.
