### ISSUE TITLE
Release 2.2.3 contains 2.2.2 version info

### ISSUE THREAD

**Issue by formwandler** [SemanticMediaWiki/SemanticMediaWiki#1206]
The file *SemanticMediaWiki.php* does contain

```define( 'SMW_VERSION', '2.2.2' );```

even though it is tagged with 2.2.3.

That means: The* Spezial:Version* page still shows release 2.2.2.

**Comment by mwjames** [comment]
> even though it is tagged with 2.2.3.
> That means: The* Spezial:Version* page still shows release 2.2.2.

Thanks, yes that's right and unfortunate but I think we will let this issue slide otherwise you need a new tag just to correct the number. 2.2.3 was only tagged after two wiki reported issue on 1.25 that was already fixed with 2.3.

**Comment by JeroenDeDauw** [comment]
@mwjames a second pair of eyes looking at this before the release is not a bad idea

**Comment by mwjames** [comment]
>  a second pair of eyes looking at this before the release is not a bad idea

I ask you guys 3 days before making a move and then I just made the tag (my time is also precious and I already spent 3 h on analysing #1201).

**Comment by formwandler** [comment]
Don't worry. It's in deed minor ;-)

**Comment by JeroenDeDauw** [comment]
@mwjames I'm not always able to read all comments. Making a dedicated issue for the release or a PR that goes through code review makes it a lot clearer there will be a new tag. In this particular case the first I saw of it was its creation. I much appreciate the work you are doing. This is just a suggestion of how this type of annoying mistake can be avoided in the future.
