### ISSUE TITLE
NotLike (!~) comparator in combination with allowed values is not recognized

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1207]
[0] shows the issue in combination with `!~*en*` usage.

The issue is in [`SomeValueDescriptionDeserializer`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Deserializers/DVDescriptionDeserializer/SomeValueDescriptionDeserializer.php#L44-L47)

```php
		if( $comparator == SMW_CMP_LIKE ) {
			// ignore allowed values when the LIKE comparator is used (BUG 21893)
			$this->dataValue->setUserValue( $value, false, true );
		} else {
```

and should be changed to

```php
		if( $comparator == SMW_CMP_LIKE || $comparator == SMW_CMP_NLKE ) {
			// ignore allowed values when the LIKE comparator is used (BUG 21893)
			$this->dataValue->setUserValue( $value, false, true );
		} else {
```

[0] http://sandbox.semantic-mediawiki.org/wiki/NotLikeComparatorWithAllowedProperties

## See also 

https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/3507f84

**Comment by mwjames** [comment]
Also add test cases for (~) as seen in http://sandbox.semantic-mediawiki.org/wiki/LikeComparatorWithAllowedProperties

**Comment by JeroenDeDauw** [comment]
hah, funny bug. Nice catch!
