### ISSUE TITLE
ASK query API output broken with 1.26/1.27

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1208]
I first thought when our API tests failed with 1.26/1.27 that is was just another glitch but after encountering an issue with 1.27, I realized they really broke it this time.

## 1.25.2

![image](https://cloud.githubusercontent.com/assets/1245473/10480632/8f273b30-726b-11e5-97d8-501ee3dd3800.png)

## 1.27alpha (f6c605e)

Changed output as indicated (it is not a map anymore)

![image](https://cloud.githubusercontent.com/assets/1245473/10480696/ea4c2638-726b-11e5-91b6-259d4d04bf4f.png)

This means that for anyone that relies on the API output (as in case of Semantic Cite, SRF) fails by just changing from 1.25 to 1.26/1.27.

Our serializer hasn't changed in years and worked on 1.19 - 1.23, 1.24 and 1.25 with a guaranteed output format structure.

@kghbln @JeroenDeDauw So much for the semver compliance of the 2.x release.

**Comment by JeroenDeDauw** [comment]
That looks like the raw mode changes, see http://addshore.com/2015/08/removing-use-of-mediawikis-api-rawmode-in-wikibase/

> So much about semver compliance for the 2.x release.

If we do not officially support these MW versions, we won't have broken semver.

**Comment by kghbln** [comment]
For better or for worse, this is one of the reasons to have tests and I think it is good that this does indeed get detected prior to field testing. No commenting on other implications though.

**Comment by mwjames** [comment]
I fixed this now and I hope it remains this way.
