### ISSUE TITLE
Special:SpecialPages "Semantic" section is gone 1.26/1.27

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1209]
1.27alpha (f6c605e) no longer displays "Semantic" special page section.

![image](https://cloud.githubusercontent.com/assets/1245473/10481135/0aec8d4e-726f-11e5-9800-73d5a745d21f.png)

For comparison on 1.25.2

![image](https://cloud.githubusercontent.com/assets/1245473/10481146/1fa621be-726f-11e5-94ef-bbe7335b2dbc.png)

Maybe not the only thing that is gone or has been broken by WMF.

**Comment by kghbln** [comment]
I think https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/2c7a269a21562f5469574a2214e73be4b73f9956 is the reason for this. @JeroenDeDauw reverted the change to retain compat with MW 1.19. Obviously MW 1.27 dropped support for this method.

**Comment by JeroenDeDauw** [comment]
@kghbln thanks for the pointer, that is quite helpful. I'll have a go at applying this change in such a way it does not break b/c

**Comment by kghbln** [comment]
@JeroenDeDauw  There is little I can do here in terms of coding but if there is something that I can point to I will happily do so. This should go to the follow-up with SMW 3 task: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1014

**Comment by JeroenDeDauw** [comment]
Should be fixed by #1214. Not tested at all though, don't even have a working MW on this laptop...
