### ISSUE TITLE
Templates used only in format=template don't appear in Special:WantedTemplates

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticMediaWiki#1211]
I was migrating some existing pages that have an inline query to a brand new, empty wiki. As I went along I was checking the Special:Wanted* pages to make sure my page, properties, templates, etc. were migrating over appropriately. 

A section of my pages utilize a template to keep them all consistent in appearance. In that template is an inline query that uses the template format for results.

|format=template
|template=Dashboard Measures Result Format
|introtemplate=Dashboard Measures Result Format Header
|outrotemplate=Dashboard Measures Results Format Footer

The pages with this template (and query) weren't working for me and I went to looking as to why. It took me a few minutes to figure our why I had red links instead of query results!

The three above templates are only used in this particular query and do not appear in the Special:WantedTemplates - even though they don't exist, but are called in an inline query.

I suppose this is a feature request, but I though it was worth mentioning.

**Comment by mwjames** [comment]
> The three above templates are only used in this particular query and do not appear in the Special:WantedTemplates - even though they don't exist, but are called in an inline query.

Unless I'm missing something, [0] displays the expected templates for a query like:

```
{{#ask: [[Modification date::+]]
 |format=template
 |template=Dashboard Measures Result Format
 |introtemplate=Dashboard Measures Result Format Header
 |outrotemplate=Dashboard Measures Results Format Footer
 |limit=3
}}
```

The visibility depends on the execution of `refreshLinksJobs` and `updateSpecialPages.php`.

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/1211

**Comment by mwjames** [comment]
https://semantic-mediawiki.org/wiki/Help:Maintenance#MediaWiki_settings
