### ISSUE TITLE
Maintenance documentation

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1215]
@kghbln @jaideraf @jongfeli Would be great if you could review [0] and add tasks that normally carried out when running a Semantic MediaWiki instance. I couldn't really find something on smw.org that could be used as a run-down list, so I just added things off the top of my head.

[0] https://semantic-mediawiki.org/wiki/Help:Maintenance

**Comment by jongfeli** [comment]
@mwjames is your goal for this page to document how people could "automate" wiki maintenance? This means combining maintenance scripts from [0] and [1] with real world use cases (examples)?    

[0] https://semantic-mediawiki.org/wiki/Help:Maintenance_scripts
[1] https://www.mediawiki.org/wiki/Manual:Maintenance_scripts

**Comment by mwjames** [comment]
> @mwjames is your goal for this page to document how people could "automate" wiki maintenance? This means combining maintenance scripts from [0] and [1] with real world use cases (examples)?

The objective is that for someone who runs an instance it lists the common maintenance tasks required to be carried out. Based on experience and size of the instance some scripts should be run more frequent than others (and the page makes some suggestions about how frequent whether this is correct or not I can't say).

So, if you install SMW and you look at the page it should become obvious was needs to be done besides having the extension installed.

Questions that should be answered:
- Which scripts  should I run, when, and how often
- Which cache (for SMW) and cache type (additional coming with 2.3) should be set
- Reminder about checking property annotation health
- JobQueue settings
- MW settings (as a short list) that influence SMW tasks (#1211 comes to mind)
- Any other regular tasks to be carried out?

**Comment by mwjames** [comment]
If someone wants to work in this, feel free to re-open it but its been 6+ month of inactivity so we no longer pretend that someone is going to work on this.
