### ISSUE TITLE
Catchable fatal error: Argument 1 passed to EmbeddedQueryDependencyLinksStore::getIdForSubject()

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#1219]
@mwjames I have an error here by just visualizing the page:
http://wikincat.org/wiki/Obra:T%C3%ADtulo_da_obra_de_teste:_subt%C3%ADtulo_da_obra_de_teste

Catchable fatal error: Argument 1 passed to SMW\SQLStore\EmbeddedQueryDependencyLinksStore::getIdForSubject() must be an instance of SMW\DIWikiPage, null given, called in /w/extensions/SemanticMediaWiki/src/SQLStore/EmbeddedQueryDependencyLinksStore.php on line 297 and defined in /w/extensions/SemanticMediaWiki/src/SQLStore/EmbeddedQueryDependencyLinksStore.php on line 328

**Comment by mwjames** [comment]
I explicitly did not check for `$dependency` being instanceof DIWikiPage as I thought that this could not happen but apparently it does.

```php
		foreach ( $dependencyList as $dependency ) {
			$oid = $this->getIdForSubject( $dependency );
```

need to change to something like

```php
		foreach ( $dependencyList as $dependency ) {

			if ( !$dependency instanceof DIWikiPage ) {
				continue;
			}

			$oid = $this->getIdForSubject( $dependency );
```

I wonder where `null` is coming from as `$dependencyList` is either an empty array or an array with `DIWikiPage`.

**Comment by mwjames** [comment]
> I wonder where null is coming from as $dependencyList is either an empty array or an array with DIWikiPage.

Looking at [0, 1], I can see something like `{{#show:{{FULLPAGENAME}}|?-Has work manifested}}`which causes `Catchable fatal error: Argument 1 passed to ...` (tested it on a blank page).

[0] http://wikincat.org/wiki/Obra:T%C3%ADtulo_da_obra_de_teste:_subt%C3%ADtulo_da_obra_de_teste
[1] http://wikincat.org/w/index.php?title=M%C3%B3dulo:Work&action=edit

**Comment by mwjames** [comment]
> I wonder where null is coming from

So, why wasn't the issue fetched by any test?

Fairly easy, I was too lazy to test printrequests which results in a `null` for an inverse PR (as in above case of `-Has work manifested`) .

**Comment by mwjames** [comment]
Fixed with 2df3930.

**Comment by jaideraf** [comment]
Thanks @mwjames!

**Comment by mwjames** [comment]
@jaideraf Thanks to the exception and your `|?-Has work manifested` use case I was able to detect a deficiency in #1223.
