### ISSUE TITLE
Can't inherit abstract function Deserializers\\DispatchableDeserializer::isDeserializerFor

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/SemanticMediaWiki#1228]
When I attempt to use commit 15568e1 (September 30) or later, including 2.3.0-RC1, I get the following error:

PHP Fatal error:  Can't inherit abstract function Deserializers\\DispatchableDeserializer::isDeserializerFor() (previously declared abstract in SMW\\Deserializers\\DVDescriptionDeserializer\\DescriptionDeserializer) in .../extensions/SemanticMediaWiki/src/Deserializers/DVDescriptionDeserializer/DescriptionDeserializer.php on line 17

**Comment by mwjames** [comment]
Our tests work jst fine as well as [0] so I can't the see the issue. Where does this issue appear (the stack trace doesn't allow for any conclusion).

[0] http://sandbox.semantic-mediawiki.org

**Comment by cicalese** [comment]
We see the error in our apache error log. We get an HTTP 500 internal server error when we try to display any page in the wiki. We are running (sorry, should have included this before):

MediaWiki 1.25.2 (3afb7b8)
11:45, 8 October 2015 
PHP 5.3.3 (apache2handler) 
MySQL 5.1.73 

The only change I make on my end to switch between broken behavior and working behavior is a git checkout using commits before and after the one I listed above. I also tried doing a commit update to 2.3.0-RC1 with the same behavior.

**Comment by cicalese** [comment]
that should be "composer update" not "commit update"

**Comment by mwjames** [comment]
I'm guessing https://bugs.php.net/bug.php?id=66818 is the cause since you use PHP 5.3.3.

**Comment by mwjames** [comment]
We test on PHP 5.3.29.

**Comment by mwjames** [comment]
I'm somewhat reluctant to make a signature change (in order to accommodate a PHP bug) but maybe you can try the following changes (- means removed, + means added) on your PHP 5.3.3 and see whether it gets resolved or not.

```php
-abstract class DescriptionDeserializer implements DispatchableDeserializer {
+abstract class DescriptionDeserializer {
```

```php
+use Deserializers\DispatchableDeserializer;
 
 /**
  * @private
  *
  * @license GNU GPL v2+
  * @since 2.3
  *
  * @author mwjames
  */
-class RecordValueDescriptionDeserializer extends DescriptionDeserializer {
+class RecordValueDescriptionDeserializer extends DescriptionDeserializer implements DispatchableDeserializer {
```
```php
+use Deserializers\DispatchableDeserializer;
 
 /**
  * @private
  *
  * @license GNU GPL v2+
  * @since 2.3
  *
  * @author mwjames
  */
-class SomeValueDescriptionDeserializer extends DescriptionDeserializer {
+class SomeValueDescriptionDeserializer extends DescriptionDeserializer implements DispatchableDeserializer {
```
```php
+use Deserializers\DispatchableDeserializer;
 
 /**
  * @private
  *
  * @license GNU GPL v2+
  * @since 2.3
  *
  * @author mwjames
  */
-class TimeValueDescriptionDeserializer extends DescriptionDeserializer {
+class TimeValueDescriptionDeserializer extends DescriptionDeserializer implements DispatchableDeserializer {
```

**Comment by cicalese** [comment]
I just tested SMW 2.3.0-RC1 on another server running PHP 5.5.30, and it works, so I agree with you that it is probably that PHP bug. I'm going to see if there is a newer version of PHP available for the server running the older PHP. I will also try the patch above and let you know. Thanks.

**Comment by cicalese** [comment]
The patch did not fix the problem, but upgrading to PHP 5.4.45 did the trick. Thanks!

**Comment by JeroenDeDauw** [comment]
I think the issue was that the methods where defined twice, once in the interfaces and once in the abstract base class. Removed the later in #1231

**Comment by kghbln** [comment]
Should this or 1231 go into the release notes?

**Comment by mwjames** [comment]
> Should this or 1231 go into the release notes?

`DVDescriptionDeserializer` was only added with 2.3 in which case it doesn't have to but it would be nice to have a confirmation that #1231 solved the issue on PHP 5.3.3.

**Comment by kghbln** [comment]
Ah, true, now I get it. Well, smw.o will tell.

**Comment by cicalese** [comment]
I have confirmed that 1231 does fix the problem on PHP 5.3.3. Thank you!

**Comment by kghbln** [comment]
Heiya Cindy, thanks for confirming!

**Comment by JeroenDeDauw** [comment]
I'm not sure - was this issue present in 2.2? James said SMW wiki would fail if we upgrade, which suggests it was not in there. And if not, then this change undoes an earlier one, and should not be mentioned.
