### ISSUE TITLE
Thanks to MWJames

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticMediaWiki#1238]
@JeroenDeDauw is doing a great job updating everyone at SMWCon on what's new in SMW. He's mentioned @mwjames multiple times during his presentation. I don't think @mwjames can hear his kudos, so I want to take a moment to appreciate his work here with this 'issue'. I don't think we do it enough.

:+1: 

(@kghbln  We can close this issue at the end of SMWCon)

**Comment by toniher** [comment]
Thanks a lot, @mwjames !

**Comment by Fannon** [comment]
Yes, thanks @mwjames!

**Comment by WolfgangFahl** [comment]
There was just a big round applause for James at SMWCon Fall Barcelona at the 10 year celebration. James - you deserve this.

**Comment by mkroetzsch** [comment]
Thanks for all the work! We would not be here in Barcelona without you being somewhere fixing our code :-)

**Comment by vrandezo** [comment]
Thanks @mwjames ! We tried to send you a lot of applause from here, but I am afraid you are too far away to hear it.

**Comment by dbolser** [comment]
++

**Comment by LloydRutledge** [comment]
Thanks!

**Comment by gesinn-it** [comment]
@mwjames many thanks for all of your contributions!

**Comment by Contrafibularity** [comment]
Absolutely, same here!

**Comment by jongfeli** [comment]
Thanks for your time and effort @mwjames.

**Comment by Zabien** [comment]
Thank you, @mwjames!

**Comment by hexmode** [comment]
Hope my gratitude doesn't come too late!  Thank you, @mwjames !!

**Comment by lexsulzer** [comment]
This issue reminds me of Churchill's "Never was so much owed by so many to so few"—or in this case to the one @mwjames. Sincere thanks!

**Comment by kghbln** [comment]
Well, there is not much for me to add, I suppose. Thanks a ton!

Though closing for now, this "issue" one may very well continues to use it.
