### ISSUE TITLE
Triage issues to find easy tasks

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1245]
We have a list of "easy" tasks by using the easy label: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy

This label identifies tasks that are relatively small and simple, and thus suitable for people outside of the project to start with. This task is about doing triage of our issues to add the label where applicable, and in addition, to file new tasks for small enhancements that we do not explicitly track yet.

**Comment by JeroenDeDauw** [comment]
It is Google Code In time, so having such a list that we can link from https://www.mediawiki.org/wiki/Annoying_little_bugs would be great.

**Comment by mwjames** [comment]
> It is Google Code In time

Has been longer over and with no updates in 5 month, so this issue is dead.
