### ISSUE TITLE
Query Subobject Id

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1247]
I don't really know wether this is a ChangeRequest or just not documented in a way that I could find it.
How can the identifier of a Subobject be queried for?

See http://semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2015-11-02_WF for an example.
I'd like to query the id of the subobject and get
eg. _b414c851a6ae6d5715c01af3d9ea3bf6

**Comment by mwjames** [comment]
> How can the identifier of a Subobject be queried for?

No.

Why would you need to do that. The hash is computed from the content and is an internal identifier that shouldn't be used or relied upon outside of SMW. 

Something like "http://example.org/id/Foo-23_QUERY84a1584555f8e65c0c3e1596b4f12918" or "http://example.org/id/Bar-23_07ddeb1226b9d2bd8d1bcb4a2ea00619" represents an addressable URI resource in its entirety  (not part if it).

**Comment by WolfgangFahl** [comment]
In the example two of the object are displayed with the same label. It would be sufficient to know how to display the URL instead.
