### ISSUE TITLE
issue with "named args" and further results link

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1258]
The other day I noticed something odd about the "named args" parameter for the template format. When more than 6 properties are listed as printout parameters, the 'further results' link will not send you to the correct query: it omits "named args=yes" and basically makes a mess of things. It does not seem to matter which properties are used, as long as there are 6 or fewer of them. . 

This issue is distinct from #481

Specs: MW 1.24 / SMW 2.1.3

**Comment by mwjames** [comment]
Maybe having an example created on [0] would help to understand the issue.

[0] http://sandbox.semantic-mediawiki.org

**Comment by Contrafibularity** [comment]
Hope to get back to this shortly. It's been a while since I discovered this and have some trouble retrieving the original issue.

**Comment by Contrafibularity** [comment]
Some bad timing on my behalf. The sandbox site is unavailable.

**Comment by Contrafibularity** [comment]
OK, I've tested this on the main SMW site instead. See https://www.semantic-mediawiki.org/wiki/User:Cavila/namedargs_test

**Comment by kghbln** [comment]
@Contrafibularity Indeed bad timing. There was a probably bot generated stampede crossing the server. :( Just post to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1186 if this happens again and I will try to get it up again.

**Comment by mwjames** [comment]
> OK, I've tested this on the main SMW site instead. See https://www.semantic-mediawiki.org/wiki/User:Cavila/namedargs_test

I really suggest you try the sandbox because "www.semantic-mediawiki.org" is running an outdated release.

**Comment by Contrafibularity** [comment]
Alright, I recreated the demo here

http://sandbox.semantic-mediawiki.org/wiki/Videos

(Just ignore the widget errors)

**Comment by mwjames** [comment]
[0] will work because it uses a different encoding. Basically the issue for the above example is that "named%20args" becomes "named_args" which the query processor cannot match because it only knows "named args" as key.

The following change should mitigate the encoding/decoding issue:

```
@@ -84,10 +84,11 @@ class SMWAskPage extends SMWQuerySpecialPage {
 		// First make all inputs into a simple parameter list that can again be parsed into components later.
 		if ( $wgRequest->getCheck( 'q' ) ) { // called by own Special, ignore full param string in that case
 			$query_val = $wgRequest->getVal( 'p' );
 
 			if ( !empty( $query_val ) ) {
+				$query_val = str_replace("_", '-20', $query_val );
```

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/1258

**Comment by mwjames** [comment]
If someone could test the fix extensively (different generate links w/o template, different formats etc.) and send a PR then we could close this issue with 2.4.

**Comment by Contrafibularity** [comment]
Adding that extra line does not appear to solve the problem. Here's what happens instead:

(1) Hitting 'further results' gives the same issue: no <tt>named args=yes</tt> as is confirmed by "show embed code"
(2) 'Edit query' -> <tt>named args</tt> is back and the query looks fine again.

Personally, I'd be equally happy if this was resolved by changing "named args" to "namedargs", although I realise that this would be a breaking change.

**Comment by mwjames** [comment]
> Adding that extra line does not appear to solve the problem. Here's what happens instead:

You need 2.4 for this work because of changes that appeared in #1407.

**Comment by Contrafibularity** [comment]
Yes, this is a private wiki running SMW 2.4 (developer).

**Comment by mwjames** [comment]
> Personally, I'd be equally happy if this was resolved by changing "named args" to "namedargs", although I realise that this would be a breaking change.

The same thing would happen with other arguments that contain a space therefore this is not really a viable solution.

> Yes, this is a private wiki running SMW 2.4 (developer).

Well, it worked for me (for the given sandbox example) but then again I didn't really test this for all possible combinations.

**Comment by Contrafibularity** [comment]
As I conjectured in my original post, the number of properties used appears to be an important factor

It's not working in the first example here: http://sandbox.semantic-mediawiki.org/wiki/Videos

But you can see on the same page that it works after removing two random properties

**Comment by mwjames** [comment]
> As I conjectured in my original post, the number of properties used appears to be an important factor

It has something to do in how the linker tries to generate the URL. It first tries to create a title object from a text string [0] and when the text line is to long, a null is returned and it uses a different method to create the URL which is where the difference in encoding originates.

But all that doesn't really matter because `Special:Ask` just has find the correct decoding strategy so that a string with "_" is represented by its natural representation of " ".

You could also change `SMWQueryProcessor` in a way so that it would always match the natural representation of a space (for the argument key).

```
@@ -300,11 +300,11 @@ class SMWQueryProcessor {
 				$rawParam
 			);
 
 			// accept 'name' => 'value' just as '' => 'name=value':
 			if ( is_string( $name ) && ( $name !== '' ) ) {
-				$rawParam = $name . '=' . $rawParam;
+				$rawParam = str_replace( "_", " ", $name ) . '=' . $rawParam;
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/SMW_Infolink.php#L221-L237

**Comment by mwjames** [comment]
> It's not working in the first example here: http://sandbox.semantic-mediawiki.org/wiki/Videos

I used this example with the mentioned fix.

**Comment by Contrafibularity** [comment]
The suggested change to SMWQueryProcessor didn't fix this, unfortunately. What a head-scratcher.
