### ISSUE TITLE
Make use of DataValues library

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#126]
SMW is dependent on the [DataValues library](https://github.com/DataValues/) as of version 1.9 since this version is dependent on Validator 1.0 which uses DataValues. DataValues is a fresh implementation of the DataItems in SMW and contains ValueParsers and ValueFormatters that can replace the SMWDataValue code. Switching out the old SMW implementation for the new one in the DataValues library will be some work though brings important advantages:
- Fresh implementation taking care of design issues with current code
- Full test coverage of the new code
- The new code is SMW independent so can be shared with other projects (ie Wikidata)

Depends on #125

**Comment by mwjames** [comment]
Nothing has been done to resolve this task within the last 2 years, moving this two [0] where interested parties can still pick this up.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4
