### ISSUE TITLE
PostgreSQL documentation

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1265]
@hangya @yoonghm Would you mind having a look at [0] because this page seems outdated (or outright false for SMW 2+) and remove or update the text so it reflects a more recent state in connection with PostgreSQL. [1] seems not longer necessary or?

Thanks

[0] https://semantic-mediawiki.org/wiki/PostgreSQL

[1] https://semantic-mediawiki.org/wiki/Help:Patching_MediaWiki_for_PostgreSQL_UTF-8_access

**Comment by yoonghm** [comment]
"Your connection is not private".  My browsers do not allow me to access. what is wrong with the web site?

**Comment by mwjames** [comment]
> My browsers do not allow me to access. what is wrong with the web site?

My guess is #1263.

**Comment by JeroenDeDauw** [comment]
Yeah, just use the http:// version of those links ...

**Comment by yoonghm** [comment]
Too busy with my paid job. Will update it next week.

**Comment by yoonghm** [comment]
Hi @mwjames, I managed to write something in [https://www.mediawiki.org/wiki/Manual:PostgreSQL](https://www.mediawiki.org/wiki/Manual:PostgreSQL)

It seems that I no longer be able to login to [https://www.semantic-mediawiki.org](https://www.semantic-mediawiki.org)

**Comment by mwjames** [comment]
>  It seems that I no longer be able to login to https://www.semantic-mediawiki.org

Nothing has changed as far as I known and should work as before @kghbln.

**Comment by kghbln** [comment]
> Nothing has changed as far as I known and should work as before

Affirmative, probably you should just request an new password.
