### ISSUE TITLE
MediaWiki debug toolbar: UTF-8 encoding issues

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticMediaWiki#1269]
MediaWiki 1.23.11 (LTS)
Database: MariaDB / MySQL; Binary encoding
Semantic MediaWiki: 2.3

Since new Version of SMW my MediaWiki debug toolbar ($wgDebugToolbar) stopped working. The cause seems to be that `<mediawiki>/includes/debug/Debug.php:405` can not JSON encode the `$debugInfo`. PHP tells me it is a invalid UTF-8 sequence that can not be encoded.

I was able to track it down to this entry in `$debugInfo['queries']`:

    array (
      'sql' => 'REPLACE INTO `mw_objectcache` (keyname,value,exptime) VALUES (\'mywiki:smw:fc:a1d0c6e83f027327d8461063f4ac58a6\',\'KԲҪ.ֲҒ*ʌMUҮֲ4ђ2411710152ɘ[)%觕ŦՀxƖVJɐ]ǖJEʥީJ֙Vֆ懖Ē+\\n��ͫ\',\'20380119031407\')',
      'function' => 'SqlBagOStuff::set',
      'master' => false,
      'time' => 0.0094828605651855469,
    )

It seems to come from "CachedFactbox":

    Onoi\Cache\MediaWikiCache::save
    Onoi\Cache\CompositeCache::save
    SMW\Factbox\CachedFactbox::saveToCache
    SMW\Factbox\CachedFactbox::addContentToCache
    SMW\Factbox\CachedFactbox::prepareFactboxContent
    SMW\MediaWiki\Hooks\OutputPageParserOutput::performUpdate
    SMW\MediaWiki\Hooks\OutputPageParserOutput::process
    SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}
    call_user_func_array
    Hooks::run
    wfRunHooks
    OutputPage::addParserOutputNoText
    OutputPage::addParserOutput
    Article::view
    ViewAction::show
    MediaWiki::performAction
    MediaWiki::performRequest
    MediaWiki::main
    MediaWiki::run

I'm not entirely sure if this is a Semantic MediaWiki issue ore more of a MediaWiki thing.
What do you think?

--
Robert

**Comment by mwjames** [comment]
>   'sql' => 'REPLACE INTO `mw_objectcache` (keyname,value,exptime) VALUES (\'mywiki:smw:fc:a1d0c6e83f027327d8461063f4ac58a6\',\'KԲҪ.ֲҒ*ʌMUҮֲ4ђ2411710152�ɘ[)%觕ŦՀxƖVJɐ]ǖJEʥީJ֙Vֆ懖�Ē+\\n��ͫ�\',\'20380119031407\')'

ObjectCache entries are always serialized (have a look at the normal cli debug output), nothing has changed here.

**Comment by mwjames** [comment]
> cause seems to be that <mediawiki>/includes/debug/Debug.php:405 can not JSON encode the $debugInfo.

SMW itself doesn't generate any debug output for the `Debug.php`, if the output isn't handled correctly then the `DebugFormatter` (the one that generates the output content) needs investigation.

**Comment by kghbln** [comment]
I have just successfully activated the debug toolbar at the smw sandbox instance and it works without problems. This one is running master of SMW and as the main difference to your setup MW 1.25.3.

**Comment by kghbln** [comment]
Also on an second instance running 2.3 I cannot observe this behaviour. Still need to test on MW 1.23 though I do not think that the result should be different. There must be something else in the water.

**Comment by mwjames** [comment]
Given the observation from @kghbln, I'm inclined to close this issue as invalid.
