### ISSUE TITLE
Make use of Ask library

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#127]
Replace the implementation of the Ask language in SMW with the new one found in the [Ask library](https://github.com/wmde/Ask).

Usage of this library brings us the following advantages:
- Fresh implementation taking care of design issues with current code
- Full test coverage of the new code
- Technical documentation
- Object [serialization and deserialization support](https://github.com/wmde/AskSerialization) that can be used in web APIs
- The new code is SMW independent so can be shared with other projects (ie Wikidata)

Depends on #126

**Comment by mwjames** [comment]
Nothing has been done to resolve this task within the last 2 years, moving this two [0] where interested parties can still pick this up.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4
