### ISSUE TITLE
Embedding remote query results via #ask into a page (from a registered source)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1271]
Embedding query results from a "foreign" wiki into a local wiki page is planned to be achieved using a separate `SemanticRemoteRepositoryConnector` extension ( == `SMW\RemoteRepository`as NS) that will make it possible to combine local as well as non-local `#ask` queries within the same page using interwiki prefix declarations and the SMW API interface.

The `source` parameter (til now fairly unused) is used to specify a foreign repository key that corresponds to an interwiki prefix from where query results are expected to be retrieved.

How? The following [video](https://youtu.be/sOCh9M2sSvU) should be pretty much self-explanatory. Technically, we send an API request to a registered source, parse the response, and build a `CannedQueryResult` (canned == because we generate the result from the API response without using an active `Store` connection to re-fetch any rows).

```
{{#ask: [[Modification date::+]] [[Has page::+]]
 |?Has page
 |source=mw-2501 // From source mw-2501
 |limit=5
}}

{{#ask: [[Modification date::+]] [[Has page::+]]
 |?Has page
 |source=mw-core // From source mw-core
 |limit=5
}}
``` 
### Register sources
```
$GLOBALS['smwgQuerySources'] = array(
	'mw-2501' => 'SMW\RemoteRepository\RepositoryHttpEndpointConnector',
	'mw-core' => 'SMW\RemoteRepository\RepositoryHttpEndpointConnector',
);
```

### Register interwiki details

MediaWiki's [interwiki table](https://www.mediawiki.org/wiki/Manual:Interwiki_table) can be extended or `$GLOBALS['smwgRemoteRepositoryEndpoints']` is provided to inject relevant assignments dynamically `( iw_url, iw_api, iw_local )`.

```
$GLOBALS['smwgRemoteRepositoryEndpoints'] = array(
	'mw-2501' => array(
		'http://localhost:8080/mw-2501/index.php/$1', // iw_url
		'http://localhost:8080/mw-2501/api.php', // iw_api
		true  // iw_local 
	),
	'mw-core' => array(
		'http://localhost:8080/mw-core/index.php/$1',
		'http://localhost:8080/mw-core/api.php',
		true
	)
);
```

## Features and limitations 

- Images (`File:`) are only displayed as normal wiki links since file source information are not available outside of the original wiki

**Comment by mwjames** [comment]
@JeroenDeDauw @kghbln ... and again suggestions for a better naming are welcome before creating the git repo. Currently available are:

- `SemanticRemoteRepositoryConnector` extension with `SMW\RemoteRepository` as NS
- `SemanticForeignRepositoryConnector` extension with `SMW\ForeignRepository` as NS

The new extension will only have three or four new classes.

**Comment by kghbln** [comment]
Wow! My talk next year is already taking shape. :) What about "SemanticWikiConnector"?

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticExternalQueryLookup
