### ISSUE TITLE
Querying special properties with show and ask setup/documentation

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1279]
see http://semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2015-11-18b_WF
at least I was a bit surprised about the behavior and the behavior on my wiki is different. 

The modification date property is set only for a few pages in my wiki and I can't see the reason how the pages for which the property value is available are selected. creation date, last_editor is are not set for any page.

I'd expected that the properties are available or a documentation is (readily/findably) available how to switch them on.

**Comment by kghbln** [comment]
Yeah, the link to the configuration parameter was missing. Added with [this edit](https://semantic-mediawiki.org/w/index.php?title=Help%3ASpecial_properties&diff=42406&oldid=35929). Thanks for reporting.
