### ISSUE TITLE
Migrate roadmap items onto this issue tracker

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#128]
Migrate the items listed on [our old roadmap](https://semantic-mediawiki.org/wiki/Roadmap) onto this issue tracker. This results in a more holistic experience, allows people to filter based on tags (ie just show the easy items) and assign items to specific milestones.

**Comment by JeroenDeDauw** [comment]
I've send a mail to the user list asking for help with this task

**Comment by kghbln** [comment]
This was done thanks to @davidforgianni on Febrauary 21, 2015. Cool work!
