### ISSUE TITLE
Properties not saving when expected

### ISSUE THREAD

**Issue by rglasnap** [SemanticMediaWiki/SemanticMediaWiki#1304]
Hey, I've run across two different issues, which seem to be somewhat related (via action=purge)

MW: 1.25.2
SMW: 2.2.2

1) I'm saving a URL as part of an infobox template, and have a button at the bottom of the page that goes to the URL. When I initially save the page, the button doesn't work. However, after refreshing via "action=purge" it clears up.

2) I've got a template that saves a property based on the initial publish date. It used to work in older versions, but no longer works. Right now it will only save the new value after a purge. If I edit the page, it's still fine, but a purge will delete it. An additional purge will "re-save" the property, which makes it completely useless.

Relevant template code (with some debugging statements so I could figure out what was happening).

Full Page Name: {{FULLPAGENAME}}
{{#if: {{#show:{{FULLPAGENAME}}| ?Initial publish date}}
   | Publish date set: "{{#show:{{FULLPAGENAME}} | ?Initial publish date}}" {{#set:Initial publish date={{#show:{{FULLPAGENAME}} | ?Initial publish date}} }} 
   | Publish date not set: "{{#show:{{FULLPAGENAME}} | ?Initial publish date}}" {{#ifeq: {{{Status|}}} | Published 
      | Status is: "{{{Status|}}}" {{#set:Initial publish date={{CURRENTTIMESTAMP}} }} 
      | Status is: "{{{Status|}}}" which is not Published
      }}
}}

Is this fixed in a newer version? I looked through some of the fixes in 2.2.3 and 2.3 but didn't see anything that looked like it.

**Comment by mwjames** [comment]
> MW: 1.25.2
SMW: 2.2.2

Possibly related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1201

> Relevant template code (with some debugging statements so I could figure out what was happening).

Could you try replicating your issue on [0] to see whether this is solved or not.

[0] http://sandbox.semantic-mediawiki.org/

**Comment by rglasnap** [comment]
I was unable to replicate it, so it looks like it's better now. So looks like the fix is upgrading to 2.2.3 or 2.3?

**Comment by mwjames** [comment]
> So looks like the fix is upgrading to 2.2.3 or 2.3?

I hope you did upgrade to the later.
