### ISSUE TITLE
Template Result format is blocking parser functions HTML output 

### ISSUE THREAD

**Issue by toniher** [SemanticMediaWiki/SemanticMediaWiki#1305]
Hello,

one change I noticed in 2.3 version is that parser function extensions that returned HTML output are prevented to do so within a template SMW result format. Instead, plain wikitext is returned.

An example extension I was using: https://github.com/SimilisTools/mediawiki-aform

Any idea?

**Comment by mwjames** [comment]
> Any idea?

I believe it is the same as https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1255

**Comment by toniher** [comment]
You're right!
