### ISSUE TITLE
Cannot view travis ci builds

### ISSUE THREAD

**Issue by paladox** [SemanticMediaWiki/SemanticMediaWiki#1309]
When I go to for example https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/94908345 this it comes up with this error There was an error while loading data, please try again

and also same for going to There was an error while loading data, please try again

Please fix this.

**Comment by mwjames** [comment]
Works as expected.

![image](https://cloud.githubusercontent.com/assets/1245473/11768257/770176ca-a1c7-11e5-8bcd-3ecf65ae8f69.png)

**Comment by paladox** [comment]
Oh. I carn't view it.

**Comment by JeroenDeDauw** [comment]
Works fine for me as well
