### ISSUE TITLE
semantic-mediawiki.com HTTPS certificate has expired

### ISSUE THREAD

**Issue by PJosepherum** [SemanticMediaWiki/SemanticMediaWiki#1312]
You must have realised that the HTTPS certificate for semantic-mediawiki.com has expired as of 8th December.

FYI, Let's Encrypt is released and widely supported now, and although their domain validation certificates only last 90 days it is super simple to set up using their automated service.

https://letsencrypt.org/

**Comment by kghbln** [comment]
We are working on it https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1263 Should not take to long now. Thanks for noting.
