### ISSUE TITLE
Add property count to property pages

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1313]
So far one has to add `{{#ask: [[{{PAGENAME}}::+]] |format= count }}` to property pages to see how many pages store values that are set for a specific property. If one wants to know how many values are stored for the property one has to proceed to "Special:Properties". I will perhaps be nice to have a system message not only showing the number of pages but also extending this to display the number of values set: Something like "A total of x values are set on a total of x pages for this property. This information was last recalculated on x at y.". Admittedly this is kinda gimmick.

**Comment by mwjames** [comment]
> I will perhaps be nice to have a system message not only showing the number of pages but also extending this to display the number of 


```php
@@ -1,9 +1,11 @@
 <?php
 
 use SMW\ApplicationFactory;
 use SMW\DataValueFactory;
+use SMW\RequestOptions;
+use SMW\StringCondition;

@@ -54,23 +56,36 @@ class SMWPropertyPage extends SMWOrderedListPage {
 	 *
 	 * @return string
 	 */
 	protected function getTopText() {
 
+		$propertyName = htmlspecialchars( $this->mTitle->getText() );
+		$usageCount = '';
+
+		$requestOptions = new RequestOptions();
+		$requestOptions->limit = 1;
+		$requestOptions->addStringCondition( $propertyName, StringCondition::STRCOND_PRE );
+		$cachedLookupList = $this->store->getPropertiesSpecial( $requestOptions );
+		$usageList = $cachedLookupList->fetchList();
+
+		if ( $usageList && $usageList !== array() ) {
+			$usage = end( $usageList );
+			$usageCount = wfMessage( 'smw-pa-property-usage', $propertyName, $usage[1], $this->getContext()->getLanguage()->timeanddate( $cachedLookupList->getTimestamp() ) )->parse();
+		}
+
 		if ( !$this->mProperty->isUserDefined() ) {
-			$propertyName = htmlspecialchars( $this->mTitle->getText() );
 			$propertyKey  = 'smw-pa-property-predefined' . strtolower( $this->mProperty->getKey() );
 			$messageKey   = wfMessage( $propertyKey )->exists() ? $propertyKey : 'smw-pa-property-predefined-default';
 
 			return Html::rawElement(
 				'div',
 				array( 'class' => 'smw-pa-property-predefined-intro' ),
-				wfMessage( $messageKey, $propertyName )->parse() . ' ' . wfMessage( 'smw-pa-property-predefined-common' )->parse()
+				wfMessage( $messageKey, $propertyName )->parse() . ' ' . wfMessage( 'smw-pa-property-predefined-common' )->parse() . ' ' . $usageCount
 			);
 		}
 
-		return '';
+		return $usageCount;
```
```json
+	"smw-pa-property-usage": "\"$1\" is registered with an approximate [https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count usage count] of '''$2''' ($3)."
```

and you get 

![image](https://cloud.githubusercontent.com/assets/1245473/12014989/f0967dfe-ad35-11e5-8aed-4a97aead68ed.png)

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count

**Comment by kghbln** [comment]
> https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count

Great, thanks!

**Comment by kghbln** [comment]
Not to forget: Kudos and thanks for helping on this one!

**Comment by kghbln** [comment]
@mwjames I know that the appearance of this was change in a subsequent pull plus the enhancement to show if it is defined by the software or the user (cannot find the pull). Is this behind a configuration setting since it does not show up on smw.o which is on 2.4? sandbox is fine

**Comment by mwjames** [comment]
> Is this behind a configuration setting since it does not show up on smw.o

We rely on [0] to be available with [1] checking if it is available.

[0] https://www.mediawiki.org/wiki/Help:Page_status_indicators
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/articlepages/SMW_OrderedListPage.php#L78-L81

**Comment by kghbln** [comment]
> We rely on [0] to be available with [1] checking if it is available.

Ah, got it. Thanks! I have [added this information](https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count). Also found the [follow up](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1436).
