### ISSUE TITLE
rebuildData.php / --ignore-exceptions

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1327]
In some cases one may just get to many exceptions which interrupt the execution of the "rebuildData.php" script. I some cases this makes even script sitting a painful task. Thus it will be nice to have an option which allows to ignore these exceptions and let the script run till the end without the need for special attention.

Such a request was raised on the mailing list a couple of times and I personally like it.

**Comment by mwjames** [comment]
> have an option which allows to ignore these exceptions and let the script run till the end without the need for special attention.

What happens with those exceptions when ignored? The exception are raised for a reason so someone has to work on them sooner or later.

**Comment by kghbln** [comment]
> What happens with those exceptions when ignored?

If possible they should be logged or a not should be issued that there were worries. Indeed these exception should be dealt with.

After the 100+ exception an 60 minutes of sitting I gave up running the script for a wiki we all know. Will create issues for them soon.

**Comment by mwjames** [comment]
> If possible they should be logged or a not should be issued that there were worries.

The questions how to log them and I'm not sure a simple

```
try {
    $byIdDataRebuildDispatcher->dispatchRebuildFor( $id );
} catch (Exception $e) {
    echo 'Karsten went berserk because of: ',  $e->getMessage(), "\n";
}
```

at [0] is sufficient.

> After the 100+ exception and 60 minutes of sitting I today gave up running the script for a wiki we all know. Will create issues for them soon

マジ

I thought for once I could work on some exciting stuff and not sitting through a bunch of issues :-(

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Maintenance/DataRebuilder.php#L247

**Comment by kghbln** [comment]
> I thought for once I could work on some exciting stuff and not sitting through a bunch of issues :-(

I know exactly how you feel. Please do not ask why it took a week to actually move the wiki. :(

**Comment by jamesmontalvo3** [comment]
I also would love a way to handle exceptions in a method other than blindly quitting `rebuildData.php`. When I run `rebuildData.php` on hundreds of thousands of IDs before going to bed, knowing it'll take hours, it's unfortunate to find in the morning that it stopped processing IDs in the first thousand. It would be great if it skipped the failures, and at the end said "231262 IDs attempted with 6 failures" and either printed the failures to the terminal or dumped them into a log.

**Comment by mwjames** [comment]
Done with #1433.

**Comment by mwjames** [comment]
An example on how `--ignore-exceptions` is expected to work https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1448#issuecomment-195357402.
