### ISSUE TITLE
DocumentationParserFunction fails with "Undefined index: language"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1328]
* MW: 1.25.3
* SMW: 2.3.0
* SESP: 1.3.1
* PHP: 5.6.11
* SQL: 5.6.27
```
PHP Notice:  Undefined index: language in /.../w/extensions/SemanticMediaWiki/includes/parserhooks/DocumentationParserFunction.php on line 40
PHP Fatal error:  Call to a member function getValue() on null in /.../w/extensions/SemanticMediaWiki/includes/parserhooks/DocumentationParserFunction.php on line 40
```
This issue somehow sounds familiar to me. This happened when trying to run "refreshLinks.php".

**Comment by mwjames** [comment]
> This happened when trying to run "refreshLinks.php".

Can try to find out on which page or template this happening?

Try adding to [0]

```php
		if ( !isset( $parameters['language'] ) ) {
			throw new \Exception( "Karsten is angry with " . $parser->getTitle()->getPrefixedDBKey() );
		}
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/includes/parserhooks/DocumentationParserFunction.php#L39-L40

**Comment by mwjames** [comment]
Anyway we can figure out the root cause of the issue?

**Comment by kghbln** [comment]
Refs: [Help:Incoing_format](https://www.semantic-mediawiki.org/wiki/Thread:Semantic-mediawiki.org:Community_portal/Help:Incoming_format)

So #smwdoc is the transgressing entity.

Step to mitigate for the time being: [Comment out #smwdoc](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AIncoming_format&type=revision&diff=43747&oldid=39379)

**Comment by JeroenDeDauw** [comment]
I checked the code and am not seeing what is wrong. There is a language parameter definition and it has a default value, so it should always be there.

**Comment by JeroenDeDauw** [comment]
I'm guessing the processing is failing for some reason (which is fine). The code is currently assuming this does not happen (which is not fine). I created a task for fixing this: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1485

**Comment by kghbln** [comment]
We still get this one:

Processing all IDs from 4673 to 40901 ...
PHP Notice:  Undefined index: language in /.../w/extensions/SemanticMediaWiki/src/ParserFunctions/DocumentationParserFunction.php on line 40
PHP Fatal error:  Call to a member function getValue() on null in /.../w/extensions/SemanticMediaWiki/src/ParserFunctions/DocumentationParserFunction.php on line 40

**Comment by kghbln** [comment]
[cool](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AIncoming_format&type=revision&diff=44463&oldid=43747)
