### ISSUE TITLE
This test did not perform any assertions

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1336]
In the Eclipse/MakeGood Environment some tests are marked with "This test did not perform any assertions". Since this might be unintentionally I am showing an example here:

```
/**
	 * @dataProvider parameterDataProvider
	 */
	public function testInstantiatedSubobject( array $parameters, array $expected ) {

		$subobject = new Subobject( Title::newFromText( __METHOD__ ) );

		$instance = $this->acquireInstance( $subobject );
		$instance->parse( new ParserParameterFormatter( $parameters ) );

		if ( $expected['identifier'] !== null ) {
			$this->assertContains(
				$expected['identifier'],
				$subobject->getSubobjectId()
			);
		}
	}
```

In SubobjectParserFunctionTest.php is flagged like this. It seems that the === null case happens and there is no handling of this. What would be the expected outcome?

**Comment by WolfgangFahl** [comment]
May be it's only a naming problem and this should be  doTestInstantiatedSubobject since otherwise PHPUnit thinks this is a test function ...

**Comment by mwjames** [comment]
> It seems that the === null case happens and 

58f0ae3 turns this into an explicit assertion, so PHPUnit should feel happy.
