### ISSUE TITLE
Follow-up on NumberValue regex/parse, refs #1334

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1337]
Follow-up on the comments from @thiemowmde to avoid having them vanish in the realm of the issue list.

> If you want to support numbers like "4." and "5.e-5" you can replace (?:\' . $decseparator . '\d+)? with (?:\' . $decseparator . '\d*)?.
> 
> Note that the regex below can explode if one of these delimiters is longer than 1 character.
> 
> This looks like you should use html_entity_decode.

See also https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/753#issuecomment-71266131

refs #1334

**Comment by mwjames** [comment]
`trim( str_replace( array( '&nbsp;', '&#160;', '&thinsp;', ' ' ), '', $value ) )` is codified, requires test.

**Comment by alex-mashin** [comment]
Are you sure that this `str_replace` doesn't remove spaces before and inside the unit of measurement?

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
