### ISSUE TITLE
Links to http://semantic-mediawiki.org/doc are broken in www.semantic-mediawiki.org

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1341]
E.g.
https://www.semantic-mediawiki.org/w/index.php?title=Architecture_guide

has links to 
http://semantic-mediawiki.org/doc/classSMWDIWikiPage.html

which need IMHO to point to
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/dataitems/SMW_DI_WikiPage.php

is there a systematic way to get these fixed?

**Comment by JeroenDeDauw** [comment]
I guess these link are not all that common. There is no way to automatically updated them as class names and namespaces changed, so some manual work is required.

**Comment by mwjames** [comment]
> https://www.semantic-mediawiki.org/w/index.php?title=Architecture_guide

This is probably outdated (" SMW 1.5.5. A new revision is underway; the first parts already reflect the status in SMW 1.6.0") and I won't have time to fix this.

See also https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1138

"Architecture guide" would need a general overhaul in terms of structure (DataModel used such as DI -> DV) and covered contents.

If someone wants to take the lead on this, feel free to do so and in case things are unclear or examples are needed just shout.

See also https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/445

> http://semantic-mediawiki.org/doc/classSMWDIWikiPage.html

The address just changed [0].

[0] http://doc.semantic-mediawiki.org/classSMWDIWikiPage.html

@kghbln I think doxygen regularly generates the docs therefore no need to waste man power here.

**Comment by WolfgangFahl** [comment]
I am volunteering to a bit of this and already started a minute ago.
@JeroenDeDauw - it would be very helpful to have the plantUML extension available for this work and while you are at it the __NOCACHE__ Magic word extension is the other thing that would make life easier for the documentation since some  of the pages I could transfer from my other wikis contain this magic word.

**Comment by JeroenDeDauw** [comment]
Ping @kghbln ^

**Comment by kghbln** [comment]
> I think doxygen regularly generates the docs therefore no need to waste man power here.

That's true. This is done once a week on Saturday.

**Comment by kghbln** [comment]
I have now added some rewrite rules to redirect any visitor to the new location automatically.
