### ISSUE TITLE
TODO's in SMW Architecture guide need to be filled and guide needs update to 2.4

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1343]
as outlined in #1341 
there are some sections that have "TODO" in it like:
https://www.semantic-mediawiki.org/wiki/Architecture_guide#Query_answering

The rest of the guide needs to be checked for being in Sync with the current 2.4 release

@JeroenDeDauw - it would be very helpful to have the plantUML extension available for this work and while you are at it the __NOCACHE__ Magic word extension is the other thing that would make life easier for the documentation since some  of the pages I could transfer from my other wikis contain this magic word. 

For the plantuml need see e.g. https://www.semantic-mediawiki.org/wiki/Template:Link

**Comment by kghbln** [comment]
The MagicNoCache extension is already installed and the PlantUML extension will not be installed until it has a maintainer again.

**Comment by WolfgangFahl** [comment]
:-) Just send a message to https://github.com/pjkersten that I am intending to take over the maintainance. That way I can practice for the upcoming MediaWikiBotJ extension.

**Comment by kghbln** [comment]
> intending to take over the maintainance

:+1:  Great since it needs a whole lotta love

> MediaWikiBotJ

A more intuitive name might be an idea but that's a nitpick.

**Comment by WolfgangFahl** [comment]
Found https://www.semantic-mediawiki.org/wiki/Technical_documentation_todo which I think should be made obsolete by this issue

**Comment by mwjames** [comment]
Has been updated to a certain extend. The rest is up to users to keep the wiki content afloat with information that is applicable and relevant.

If clear actionable tasks can be identified and described then this issue can be used to track them but for the time being this has been classified as solved.

**Comment by WolfgangFahl** [comment]
https://www.semantic-mediawiki.org/wiki/Special:Version still doesn't show PlantUML. If installing and extension is not an "actionable task" what is?

**Comment by mwjames** [comment]
> https://www.semantic-mediawiki.org/wiki/Special:Version still doesn't show PlantUML. If installing and extension is not an "actionable task" what is?

Whether "PlantUML" is installed or not has nothing to do with the "SMW Architecture guide". I explicitly stated "keep the wiki content afloat".
