### ISSUE TITLE
Accessing pages containing a hyphen via "Special:Browse"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1349]
When trying to access "Special:Browse" for [Alcatel_OT-C825](http://de.wiki-products.org/Alcatel_OT-C825) via the "Seitenannotationen" link you get to a [blanc field](http://de.wiki-products.org/Spezial:Durchsuchen/Alcatel_OT-C825) so one is required to add "Alcatel_OT-C825" into the field to get to the [requested data](http://de.wiki-products.org/Spezial:Durchsuchen?title=Spezial%3ADurchsuchen&article=Alcatel_OT-C825). I tried to replicate this on the sandbox, but failed. I am still puzzled since the example wiki is not the only one where I observed this. Adding the question label since I an not sure if I am goofing here somehow.

MW 1.25.5, SMW 2.3.0, PHP 5.4.45

**Comment by mwjames** [comment]
The issue is that [0] omits the the encoding `-2DC` which should read [1] as seen in [2].

[0] http://de.wiki-products.org/Spezial:Durchsuchen/Spezial:Durchsuchen/Alcatel_OT-C825
[1] http://de.wiki-products.org/Spezial:Durchsuchen/Alcatel_OT-2DC825

[2] http://sandbox.semantic-mediawiki.org/wiki/Special:Browse/Issue-2F1349_OT-2DC825

**Comment by mwjames** [comment]
We have a battery of tests to ensure [0] that hyphens are correctly encoded and this has not changed since #516.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Unit/UrlEncoderTest.php#L53-L89

**Comment by mwjames** [comment]
[0] is to expected to return `Alcatel_OT-2DC825`, you may want to have a look at it (something like `var_dump( $this->encodePrefixedDBkey() )` as to what is returned).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/BaseTemplateToolbox.php#L80-L82

**Comment by kghbln** [comment]
> [0] var_dump( $this->encodePrefixedDBkey() );

I added this to line 82, so were do I have to expect the output?

**Comment by kghbln** [comment]
This issue is actually not a new one. I discovered it on July 14, 2015 right after upgrading from SMW 1.8.0.5 to 2.2.2 but have not gotten around reporting it yet. This wiki not having a proper article path should not be the cause.

**Comment by mwjames** [comment]
```
	protected function performUpdate() {

		var_dump( $this->encodePrefixedDBkey() ); // HERE

		$this->toolbox['smw-browse'] = array(
			'text' => wfMessage( 'smw_browselink' )->text(),
			'href' => SpecialPage::getTitleFor( 'Browse', $this->encodePrefixedDBkey() )->getLocalUrl(),
			'id'   => 't-smwbrowselink',
			'rel'  => 'smw-browse'
		);

		return true;
	}

	private function encodePrefixedDBkey() {
		return Infolink::encodeParameters( array( $this->skinTemplate->getSkin()->getTitle()->getPrefixedDBkey() ), true );
	}
```
> so were do I have to expect the output?

![image](https://cloud.githubusercontent.com/assets/1245473/12121748/3e79dc12-b3d7-11e5-9502-dea7f57b6ceb.png)

**Comment by kghbln** [comment]
> var_dump( $this->encodePrefixedDBkey() ); // HERE

line 70, this worked and is all working as expected.

Now I discovered the cause of the issue: Since the toolbox is hidden on this wiki I just added `** Special:Browse/{{FULLPAGENAMEE}}|Annotations` to the sidebar to get the links to "Special:Browse" back. So this is what you get. Tough titties! :D 

The only thing I could envision here is to have a magic word or so to add the link to "Special:Browse" to an arbitrary location of the sidebar and/or wiki.

Thanks a ton for your help!

**Comment by mwjames** [comment]
> The only thing I could envision here is to have a magic word or so to add the link to "Special:Browse" to an arbitrary location of the sidebar and/or wiki.

This should work.

```
** http://example.org/index.php/Special:Browse?article={{FULLPAGENAME}} | BROWSE
```

**Comment by kghbln** [comment]
> This should work.

It does! This one was too easy.

**Comment by mwjames** [comment]
@kghbln I think this is the same as in http://sandbox.semantic-mediawiki.org/wiki/Discussion:L'Or%C3%A9al_Men_Expert_Carbon_Protect_4_in_1_Anti-Transpirant_Roll-on_50_ml

**Comment by kghbln** [comment]
> I think this is the same as 

I guess so too. This is an edge case we will have to live with. Not a big deal as a matter of fact.

**Comment by mwjames** [comment]
Blame the side bar that adds the extra encoding, so if you do:

MediaWiki:Sidebar

```
** helppage|help
** http://locahost:8080/mw-27-00-rc1/index.php/Special:Browse?article={{FULLPAGENAME}}|Foo
```

with a page `Foo'Bar` then:
- above link will generate `http://localhost:8080/mw-27-00-rc1/index.php/Special:Browse?article=Foo&#39;Bar` yet
- if you use the standard `Special:Browse`, you get `http://localhost:8080/mw-27-00-rc1/index.php/Special:Browse/Foo%27Bar`.

**Comment by kghbln** [comment]
> Blame the side bar that adds the extra encoding

True, the sidebar is an underdevelopped feature. So many workarounds needed ... :|
