### ISSUE TITLE
"Special:Browse" / Increase size of text field

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1350]
The standard size of the field on "Special:Browse" is 20 which is rather short. Thus I suggest to  double it to 40. I believe all what has to be done is adding size="40" to [line 429](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/specials/SMW_SpecialBrowse.php#L429) of the "SMW_SpecialBrowse.php" file.

Anyhow, any objections to changing the size? @mwjames, @JeroenDeDauw

**Comment by mwjames** [comment]
> Anyhow, any objections to changing the size?

No.
