### ISSUE TITLE
I18n reference pages

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1356]
I believe that the [I18n reference pages](https://www.semantic-mediawiki.org/wiki/Category:I18n_reference_page) should be available in as many languages as possible and make use of the new datatype "monolingual text" the "Semantic Interlanguage Links" extension as well as the "Translate" extension.

I think this will be a nice usecase to demonstrate how this may work.

**Comment by kghbln** [comment]
This weekend I have made [release information](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.4.2) and [news items](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.4.2_released) translatable. I still have to read more intensely through the docu of the Translate extension but I believe the integration with SMW and SIL already works great. These pages are next.

FYI @mwjames @JeroenDeDauw

**Comment by mwjames** [comment]
Considering this done therefore closing this.

**Comment by kghbln** [comment]
> Considering this done therefore closing this.

Not really but having this open or close or ... will have no effect on the progress. It is indeed still somewhere in the pipeline.
