### ISSUE TITLE
Composer mysteries "Why is 2.3.0 not satisfying 2.3"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1359]
Found [0]

```
I'm getting these notes, which I do not really understand. Why is 2.3.0 not satifying 2.3?

mediawiki/semantic-media-wiki: 2.3.0 installed, 2.3 required.
mediawiki/parser-hooks: 1.4 installed, ~1.4 required.
```

[0] https://www.mediawiki.org/w/index.php?title=Topic:Sw33qphusc6uth0o&topic_showPostId=sw33qphusg4x1kyw#flow-post-sw33qphusg4x1kyw

**Comment by mwjames** [comment]
The general recommendation is to use `~2.3` to ensure minor releases can be fetched when available (instead of using a specific point release). As to what `~`, please see [0]

[0] https://www.semantic-mediawiki.org/w/index.php?title=Help:Using_Composer&redirect=no#.7E.2F.5E_usage_and_meaning

**Comment by eFFemeer** [comment]
Thank you for your reaction mwjames. What still puzzles me is the purpose of these messages. My first reaction is the impression that something went wrong, but apparently these messages are just informative.

**Comment by JeroenDeDauw** [comment]
`2.3.0` and `2.3` should definitely match. No tildes or whatnot required. Internally those numbers are the same to Composer.
