### ISSUE TITLE
 3.x addendum (preliminary notes)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1366]
This issue mostly gathers ideas and thoughts for the process of moving towards 3.x. (refs #1365)

> 3.0

What is the vision here besides the technical changes (#698, #1014)? [0] What do we expect 3.x to focus on?
- NoSQL store ?
- ElasticSearch support?
- VE annotation support? (I don't use VE, so no idea about the whole Parsoid/VE stuff @nischayn22 ?) 

2.x was all about:
- incrementing features
- testability improvemens of the software (coverage now by ~80%)
- `SPARQLStore` parity (Virtuoso, Fuseki, Sesame, Blazegraph)

>  I suggest that we switch to 3.x-dev after releasing 2.4.0. 

We should really have a plan for this because it is the only occasion (major number change) where we can break things deliberately, so not taken this opportunity would be unwise. (still thinking on a 2.5)

> Thoughts?

We should send out an email about the preliminary plans for moving towards 3.x including:
- that changes are expected for the supported environment
- that it will most likely contain breaking changes
- that a major release will not be retrieved automatically when using Composer in connection with `~2.` (this is to minimize disruption for any production deployment)
- extension developers are encouraged (probably no one will but later users can not complain that we haven't communicate and addressed the issue early on) to write unit tests so extensions can be tested and possibly catch incompatibilities 

Besides the technical aspect, I'd like to see:
-  #1356 to be done (as multi-language use case)
-  a website relaunch with Chameleon skin (getting tired of Vector) which would require to adapt existing templates and content
- Have some people to commit to above so @kghbln doesn't has to work off his butt
- Always thought how to make use of the "Filtered Format", smw.org could have a "Solution configurator" where based on the filtered options it shows which extension are a best fit (e.g "want to display Maps", "want to manage bibliographies/references" etc.)

Some comments on [0]:
- "Multilingual semantic wikis (localisation of properties" might come with 2.4 or 2.5
- "PostgreSQL" I think is mostly covered with 2.3+
- "Displaying pages with long and intricate inline queries can take very long"  an enabled `CachedValueLookupStore` (`smwgValueLookupCacheType`, 2.3+) with `redis`, and a possible `EmbeddedQueryResultCache` #1251 might help [1]
- "support displaying linked properties like "?a.b"" I have seen a PR for this but needs more testing
- "greater support for ORs and ANDs" ?
- "more up-to-date display of data" `EmbeddedQueryDependencyLinksStore` 2.3+ should help with this
- "free-text search features in queries" maybe #1282 can help

[0] https://www.semantic-mediawiki.org/wiki/SMW_users_survey_results
[1] https://www.semantic-mediawiki.org/wiki/Page_loading_time

**Comment by s7eph4n** [comment]
Right now I am lacking a project, so Chameleon development is pretty slow. I guess it would make sense for me to get involved with the website relaunch.

**Comment by JeroenDeDauw** [comment]
To me changing to 3.0 is about being able to make breaking changes such as the ones we've already collected, most notably bumping the PHP requirement. I don't see why we'd need to have a set of features (especially for theme for the whole 3.x), or a site redesign. Those are all nice, and good to have, but why force them all in the same bucket?

**Comment by mwjames** [comment]
> To me changing to 3.0 is about being able to make breaking 

If we make a change then this should have some meaning and not just be a simple number game to get rid of some outdated PHP version.

> I don't see why we'd need to have a set of features (especially for theme for the whole 3.x), or a site redesign.

In short "have an agenda, communicate the agenda". In an era of WikiData being the hegemon of structured data for a wiki (or so everyone things), SMW needs a mission as to where it goes (and why it is still relevant) and a major release change can be a good time for reflection.

Of course, one could do business as usual but then we could also stick with 2.x.

> changes such as the ones we've already collected

Those are small fishes non of which would warrant a 3.x (I'm looking for the big thing that makes it worthwhile to be a 3).

> Those are all nice, and good to have, but why force them all in the same bucket?

This is a about the broader 3.x hence the title where people can contribute in different ways but all with an overall objective towards a common goal (and switching to 3.x can be used as umbrella).

**Comment by JeroenDeDauw** [comment]
If we want to finally make those breaking changes, we need to go to 3.x. We cannot stick with 2.x as per semver. I'm not sure why we'd need to assign more meaning to such an increment. I suggested we do the 3.0 release #1365 after 2.4 to finally drop all the compat crud. So the 3.x is there purely due to semver.

I agree with the other points you make. Good to have a mission, a big theme, a more comprehensive set of breaking changes, more communication with the users about what they want and what is planned, etc. To me this is very disjoint from the more technical issue of dropping compat crud and incrementing the major version to indicate we made breaking changes.

**Comment by s7eph4n** [comment]
Any news on this? Any new ideas?

**Comment by mwjames** [comment]
> Any news on this? Any new ideas?

Off the top of my head:

- Property page
 - Turn the property page into a JSON content model for structured
handling and easier API updates
 - Provide a standard form to edit related fields (without the need
for PageForms, no template stuff)
 - Some API that pulls multi-lang labels from Wikidata (given that a
corresponding === equivalent property is linked) and imports them
on-demand and is stored in SMW directly
- Allow to restrict the creation of properties and hereby value
annotations (enterprise mode)

Technical / code
- Convert the includes folder to src (implies to get rid of some very
outdated programming paradigms and have each converted class to be
tested)
- Split `SMWSql3SmwIds` into `SqlIdComposer` and `SqlIdFetcher` for
some maintenance sanity and rework the in-memory caching

More advanced topics and technically progressive include:

- A machine learning module to allow some learning mode and use the
results to add property annotations automatically on certain content
groups
- My personal pet project is the integration of elastic search,
including a #ask -> DSL -> elastic search interpreter
- #sparql parser function

SRF

- Implement https://vega.github.io/vega/ and at the same time remove
d3, googlecharts, jqplot, sparkline, timeseries, and JitGraph to lower
the technical depth.

Aside from that, @kghbln maybe ping the "enterprise" segment on some
input, or as it seems on vogue this days in the WMF circle, do a
wishlist.

**Comment by kghbln** [comment]
At lot of things will be covered with 3.0.0 (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1365). If something is of interest to pick up for 3.1.0 it may very well be done. Archiving this at the "Documentation" project.
