### ISSUE TITLE
Linking to a subobject's 'data summary'

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1374]
Thanks to Special:Browse/[insert page name here], it's fairly easy to get a list of a page's outgoing properties and corresponding values. Doing the same thing for subobjects can be quite cumbersome, however. You need to go to Special:Browse/[...] first and then be able to track the right subobject by crawling through a list of subobjects, which are not always recognisable because they may be hash-numbered. 

A direct link to the 'data summary' of each subobject, or a similar output, could be helpful. I'm not sure what's the best approach here but I imagine that the following would be a viable option: 

Find a way for #subobject to refer to itself in such a way that 
(a) ... a direct link to the subobject's data summary could be rendered
or (b) .. a template could act upon it and perform a new query with "data summary" as a result format.

**Comment by mwjames** [comment]
> (a) ... a direct link to the subobject's factbox could be rendered

Already exists as in [0]:

![image](https://cloud.githubusercontent.com/assets/1245473/12352894/39113d8c-bb8a-11e5-935a-ad968710eb98.png)

To make it browsable (instead of linking to `Special:SearchByProperty`) you need to change the `Factbox` so it contains something like:

```php
-						) . $dataValue->getInfolinkText( SMW_OUTPUT_WIKI );
+						) . $this->getInfolink( $dataValue );
 				}
 			}
 
 			// Invoke table content
 			$this->htmlTableRenderer->addCell(
@@ -394,6 +394,21 @@ class Factbox {
 
 			$this->htmlTableRenderer->addRow();
 		}
 	}
 
+	private function getInfolink( $dataValue ) {
+
+		if ( $dataValue->getProperty()->getKey() !== '_SOBJ' ) {
+			return $dataValue->getInfolinkText( SMW_OUTPUT_WIKI );
+		}
+
+		$browselink = SMWInfolink::newBrowsingLink(
+			' +',
+			$dataValue->getWikiValue(),
+			'smwbrowse'
+		);
+
+		return $browselink->getWikiText();
+	}
+
```

To produce a browse link as in:

![image](https://cloud.githubusercontent.com/assets/1245473/12352929/63ba256c-bb8a-11e5-9083-eb68fca3d04f.png)


[0] http://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum

**Comment by Contrafibularity** [comment]
> To make it browsable (instead of linking to Special:SearchByProperty) you need to change the Factbox so it contains something like:

Sounds like a good idea actually! I  always wondered about the discrepancy between the two kinds of factboxes.

>> (a) ... a direct link to the subobject's factbox could be rendered

> Already exists as in [0]:

I was referring to a list of links to subobjects becoming impossible to identify other than by clicking each link and going back and forth. In your example, there's only a single subobject so there won't be any confusion as to which subobject we're dealing with, but if you had 50 of them and they were all hash-numbered - that is, without custom titles to name them - you'd be in a fair bit of trouble making out which subobject you had in mind. I don't currently see how a page's Factbox could be changed to remedy this sort of problem, actually, but what probably would be helpful is this: the ability to somehow produce <strong>inline</strong> links to subobjects' factboxes, which is why I made those comments about self-referentiality and templates. 

To elaborate on (a) and (b) in my previous post. (a) refers to SMW providing a direct (inline) link to each subobject's Factbox, but I'd prefer (b)'s more flexible approach: it basically suggests that using #subobject a user should be able to print the subobject's identifier, along with a template with which to apply formatting. For example:

<pre>{{#subobject:-
   |#|template=Linktosubobjectfactbox
   |property1=value1
   |property2=value2
   |...
 }}
</pre>
(which is the closest approximation to existing syntax I can think of)

...where the hash <tt>#</tt> parameter would represent a request for the subobject's identifier. The template, here Template:Linktosubobjectfactbox, would then construct a link such as <tt>[[Special:Browse/''insert subobject id here''|factbox]]</tt>. 

(I also mentioned "Factbox" as a possible new result format, but please forget that)

**Comment by mwjames** [comment]
> I was referring to a list of links to subobjects becoming impossible to identify ... they were all hash-numbered - that is, without custom titles to name them 

That's the nature of a subobject which is either named or represented by a hash identifier (I think in previous discussions here, on the list, and per email I have reiterated on the concept behind this).

> Factbox

The clarify the naming, if we refer to `Factbox` then we understand the embedded `Factbox` that can be seen on a page. `Special:Browse` and `Factbox` are not the same.

> To elaborate on (a) and (b) in my previous post. (a) refers to SMW providing a direct (inline) link to each subobject's Factbox,

I'm still unable to grasp of what is required and expected here.

**Comment by Contrafibularity** [comment]
> The clarify the naming, if we refer to Factbox then we understand the embedded Factbox that can be seen on a page. Special:Browse and Factbox are not the same.

Thanks for clarifying this. I did use factbox (capitalised or not) as a general term for a complete summary of semantic data belonging to either a page or a subobject - somewhat leaving open the question whether that function should be fulfilled by Special:Browse or something other. "Data summary" would have been more appropriate as a term. I've amended accordingly and hope it makes more sense now. 

>> To elaborate on (a) and (b) in my previous post. (a) refers to SMW providing a direct (inline) link to each subobject's Factbox [edit: data summary],
> I'm still unable to grasp of what is required and expected here.

Well, I did not fill in the possible details for (a) because like I said, I prefer (b) to (a) anyway. 

Does the syntax proposed make sufficient sense?

<pre>{{#set:
 |prop1=val1
 |prop2=val2
 |#|template=...
}}
</pre>

**Comment by kghbln** [comment]
> Sounds like a good idea actually! I always wondered about the discrepancy between the two kinds of data summaries (Factbox and Special:Browse).

This has historic reasons: The factbox was a precursor feature to "Special:Browse" which was originally meant to be removed entirely from the code base. That's the reason why factboxes must now be explicitly be enabled to be shown. However the factbox is still a generally loved feature and this is the reason why it is still there I suppose.

**Comment by Contrafibularity** [comment]
You've been busy!

**Comment by mwjames** [comment]
A direct link to a subobject via the Factbox to `Special:Browse` is provided. No other actionable tasks could be derived from the description therefore closing this issue.

**Comment by Contrafibularity** [comment]
One further question. I tried to link directly to a subobject's data summary in Special:Browse/..., but the link sends me to a data summary of the page holding the subobjects. On closer inspection, it is probably the hash in the subobject's name that causes this issue. I did try 'urlencode' (# --> %23), to no avail. I must be missing something.

**Comment by mwjames** [comment]
>  I did try 'urlencode' (# --> %23), to no avail. I must be missing something.

http://sandbox.semantic-mediawiki.org/wiki/Issue/1374

**Comment by Contrafibularity** [comment]
Right, thanks!
