### ISSUE TITLE
Help needed for extensions that are on gerrit

### ISSUE THREAD

**Issue by paladox** [SemanticMediaWiki/SemanticMediaWiki#1375]
Hi there are semantic extensions on gerrit Wikimedia but the extensions are failing the unit tests because some require the SemanticMediaWiki to be installed first which we have done but fails at the web updater installing the sql.

17:51:12 Creating main page with default content
17:51:12 Could not insert main page: A database error has occurred. Did you forget to run maintenance/update.php after upgrading?  See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
17:51:12 Query: SELECT  smw_id,smw_sortkey  FROM `smw_object_ids`   WHERE smw_title = 'Main_Page' AND smw_namespace = '0' AND smw_iw =  AND smw_subobject =   LIMIT 1  
17:51:12 Function: SMWSql3SmwIds::getDatabaseIdAndSort
17:51:12 Error: 1146 Table 'jenkins_u3_mw.smw_object_ids' doesn't exist (127.0.0.1:3306)

https://integration.wikimedia.org/ci/job/mwext-testextension-zend-composer/672/console

https://gerrit.wikimedia.org/r/#/c/264174/

I would like help to resolve this problem so that extensions that use this extension wont fail on the webupdater.

I believe that you have to do this web updater through a special page in semantic mediawiki to install the sql.

Please support just using the web updater for tests.

**Comment by paladox** [comment]
That is for SemanticMediaWiki on gerrit but extensions requiring it will fail with the same error.

**Comment by mwjames** [comment]
> I believe that you have to do this web updater through a special page in semantic mediawiki to install the sql.

No need for the web updater,  a normal `php maintenance/update.php --quick` suffice after appropriate settings and installation have been finalized.

[0] contains all steps that are necessary to run `composer phpunit` from a command line.

```
  - bash ./tests/travis/install-services.sh
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-mediawiki.sh

before_script:
  - bash ./tests/travis/update-configuration-settings.sh

script:
  - bash ./tests/travis/run-tests.sh
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/

**Comment by paladox** [comment]
Ok.

In the mw-run-update-script.sh file it is set with --quick.

**Comment by paladox** [comment]
Sorry I thought that script is considered a web updater but anyways that is the script that is run on jenkins.

**Comment by paladox** [comment]
@mwjames  do you know where the sql files are or how is the sql generated because I am thinking off adding in support for tests to use the LoadExtensionSchema hook or something similar so that when the config is set to true in testers the sql will be correctly added.

**Comment by hashar** [comment]
If you have all extensions loaded then run the installer, MediaWiki attempts to create the main page rather early on and shows `Creating main page with default content`

Via hooks, some extensions code is triggered, but since the database schema for extensions hasn't been populated yet, it fails.

**Comment by paladox** [comment]
@mwjames do we have to include the configurations that are found in https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/travis

if so what would be the important ones or all of them important and which ones.

**Comment by JeroenDeDauw** [comment]
@hashar are you saying this is a bug in the MW installer?

@paladox the SMW schema is not created via static sql files. A declarative form is dynamically generated with PHP code and then translated to SQL and executed via MWs DB abstraction layer.

**Comment by paladox** [comment]
Oh.

We think it is the way we are executing the code in Jenkins because the none generic version installs MySQL before then installs the extensions but the composer test doesn't it install the extension before so we are thinking that if we follow the non generic way it will work.

**Comment by mwjames** [comment]
> hat if we follow the non generic way it will work.

Not sure what the reference "non generic way" entails but to clarify:

- You install MW (without or with DB)
- You run `composer require` from the MW root [0] or if can't then run `composer install` from the SMW base directory [1]
- Composer ensures that libraries (and yes we do use libraries and those need to be installed and registered before you continue) and classes are autoloaded (PSR-4 approach)
- Then you add some customizing ([2], service stuff can be omitted)
- Finally run `php maintenance/update.php --quick`
- and you ready to go

The above steps are fairly generic.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/install-semantic-mediawiki.sh#L18-L47
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/install-semantic-mediawiki.sh#L62-L70
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/update-configuration-settings.sh 

PS: （昔昔とゆう物語が始まる。。。we were once on Jenkins but due to political manoeuvring we were incapacitated to use Composer, maybe something has changed.

**Comment by paladox** [comment]
I'm talking about the names of the tests we have in jenkins the non generic way is when we include dependacys off other extensions the generic way is when no extension is required to pass the test for that main extension.

**Comment by paladox** [comment]
Maybe if we install the extension after the installation of mw with database that will work since it wont fail the db update since that will run afterwards.

**Comment by paladox** [comment]
https://gerrit.wikimedia.org/r/#/c/264333/

**Comment by mwjames** [comment]
Same note as in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1405#issuecomment-195769059.

**Comment by JanZerebecki** [comment]
#1479 might describe a fix for this.
