### ISSUE TITLE
Changes to collation settings not adopted

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1383]
It has been my assumption, perhaps naively so, that SMW relies on MediaWiki's <tt>$wgCategoryCollation</tt> setting for sorting pages and values of type 'Page' with most of the regular result formats, such as <tt>list</tt>, <tt>template</tt> and <tt>category</tt>. This is also what I added to https://www.semantic-mediawiki.org/wiki/Help:Sorting 

A test case on a private wiki did not quite yield what I expected and hoped for, however. I changed <tt>$wgCategoryCollation</tt> to <tt>uca-default</tt>, which to me is more natural and friendlier when it comes to sorting accented characters, such as é or è (<tt>uppercase</tt> lists them after the letter z). I then did what I thought was necessary for the changes to get effective: run the maintenance script (<tt>updateCollation.php</tt>), upgrade the SMW tables, upgrade SMW data, and execute runJobs.php. The MW categories are now sorted per the configuration changes, but SMW still lists pages as if the old setting (<tt>uppercase</tt>) prevails: pages whose title begin with É or È are listed after Z, whether the result format is <tt>list</tt>, <tt>category</tt> or something else. 

Specifications:
MW 1.25.1 and SMW 2.4-alpha
PHP 5.3.29, MySQL 5.6.24

**Comment by mwjames** [comment]
#783 covers discussion and test cases in connection with `wgCategoryCollation`

**Comment by Contrafibularity** [comment]
Thanks. It looks like those tests focussed primarily on the use of sortkeys customised through DEFAULTSORT, not (yet) taking other use cases into account, so consider this a new addition as well as an enhancement request: 

I've been rummaging around for a bit and found this in ByLanguageCollationMapper.php

> 	public function findFirstLetterForCategory( $string ) {
>		// Currently MW's `uca-default`, `xx-uca-ckb`, `xx-uca-et` are
>		// not supported

Well that might explain things! Is it just those three or anything with an ICU language code?

**Comment by D-Groenewegen** [comment]
Same problem here when using 'uca-ga'. To be clear, I much prefer my queries to be sorted in the same way that pages are sorted in my categories, namely 'uca-ga' or 'uca-default' (which is probably close enough to 'uca-ga'). In fact, I'd say that support for 'uca' is top of my wishlist for Semantic MediaWiki. Would it be very difficult to implement this? 

P.S. #699 and #783 are somewhat related but only seem to cover case-sensitivity and case-order (lowercase / uppercase)

**Comment by Henryfunk** [comment]
It is my understanding that with $wgCategoryCollation set to "uppercase" SMW should treat "example" and "Example" as identical when sorting the result of an ask statement, but this doesn't happen on my Wiki. See for instance the first list on [this page](https://www.irhb.org/wiki/index.php/Public_houses_named_after_Robin_Hood) where "Robin Hood and Little John (Aslackby)" comes after "Robin Hood Tavern (Upper Clapton)". 

The ask statement that generates the list is:

{{#ask:
[[Category:English place-names]]
[[pntype::Public house]]
|format=ul
|limit=1000
|sortcollation=utf8_general_ci
|ordermethod=title
}}

Removing the "sortcollation" parameter makes no difference. 

I am using:
MediaWiki 1.28.0
PHP	7.0.15-0ubuntu0.16.04.4 (apache2handler)
MySQL 5.7.17-0ubuntu0.16.04.2
Semantic MediaWiki 2.4.6.
DB table collation: utf8_general_ci.

Is there a bug or am I doing something wrong?

**Comment by kghbln** [comment]
> It is my understanding that with $wgCategoryCollation set to "uppercase" SMW should treat "example" and "Example" as identical when sorting the result of an ask statement, but this doesn't happen on my Wiki.

This is about sorting on category pages I believe.

However I see your issue. Perhaps in your case it will be possible to add an extra property holding an all uppercase version of the page title and do the sorting by its value but at the same time not showing the sorting propery via the output template.

Admittedly I am not aware of the `sortcollation` and `ordermethod` options you are using in your printout statement.

**Comment by Henryfunk** [comment]
kghbln, thank you very much. I will give your workaround serious consideration, unless there are plans to facilitate choosing collation for the sorting of categories. I will have to set my bot to work :-)

RE "sortcollation" and "ordermethod": I guess they must have slipped in during experiments to make the sort order conform to my expectations. They are holdovers from the time I relied exclusively on DPL (third-party), which I'm still using for a good many things.

**Comment by kghbln** [comment]
> kghbln, thank you very much. I will give your workaround serious consideration, unless there are plans to facilitate choosing collation for the sorting of categories. I will have to set my bot to work :-)

I believe to have seen an issue relating to collation with a "seeks-developer" label. So this will not come at short notice / soon.

**Comment by Henryfunk** [comment]
OK, thanks! I will update page templates and set the bot to work.

**Comment by mwjames** [comment]
> I believe to have seen an issue relating to collation with a "seeks-developer" label.

See #2065.

> So this will not come at short notice / soon.

#2429 is a prototype and is targeted for 3.0 but I'm missing specific examples that can be tested against `$wgCategoryCollation = 'uppercase';` and `$wgCategoryCollation = 'uca-default';`.

**Comment by mwjames** [comment]
This has been addressed with 3.x (#2429) using the `$smwgEntityCollation` setting.

**Comment by Henryfunk** [comment]
Ah, thanks! I only saw your message now.
