### ISSUE TITLE
Alphanumerical sorting (notification)

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1386]
MediaWiki users (myself included) have long complained about the absence of natural (alpha)numerical sorting of pages in categories. SMW has inherited this lack of native support, which has been the subject of a number of discussion threads on the mailing list and elsewhere. 

Fortunately, this feature has finally made its way into the top 10 of Wikimedia's wishlist. Details here: https://phabricator.wikimedia.org/T8948 - hopefully spurring on further development to MediaWiki core.

**Comment by mwjames** [comment]
Addressed with #2429.
