### ISSUE TITLE
PLURAL support needed

### ISSUE THREAD

**Issue by Purodha** [SemanticMediaWiki/SemanticMediaWiki#1390]
The message documentation says "always plural" which is irrelevant as one can learn from [this resource](https://www.mediawiki.org/wiki/Localisation#Be_aware_of_PLURAL_use_on_all_numbers).

* Smw-limitreport-intext-parsertime-value
* Smw-limitreport-pagepurge-storeupdatetime-value

**Comment by kghbln** [comment]
Thanks for reporting. I tweaked the formatting of your report. Hope that this is ok.

**Comment by JeroenDeDauw** [comment]
Thanks @Purodha and @kghbln!
