### ISSUE TITLE
How to delete orphaned properties?

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1402]
see http://stackoverflow.com/questions/28253718/how-to-delete-orphaned-properties

At Special:Properties redlinks show up for properties that are referenced by deleted pages. Basically the question is the same as in: http://sourceforge.net/p/semediawiki/mailman/message/31901925/

How do i  get rid of such useless properties that make no sense since they are only referenced in deleted pages ...?

**Comment by mwjames** [comment]
In 2.4, running `rebuildData.php` will check with the `PropertyTableOutdatedReferenceDisposer` (#1216) whether an entity is without reference (including user-defined properties) and mark them as disposable hence should no longer appear in queries or lists. If the `EmbeddedQueryDependencyLinksStore` is enabled then properties remain available (as we need to keep the ID reference to those components) when referenced in a query condition or as printout parameter (#1323) .

> How do i get rid of such useless properties that make no sense since they are only referenced in deleted pages ...?

Not sure what this means.

**Comment by mwjames** [comment]
In case the `rebuildData.php` is not able to remove outdated properties [0] then [1] might come to rescue.

[0] https://www.semantic-mediawiki.org/wiki/Help:Outdated_properties
[1] https://www.semantic-mediawiki.org/wiki/Help:Object_ID_disposal
