### ISSUE TITLE
SemanticNearBy (new repo)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1404]
> That gets you the information in the clients browser, not on the server side. So I still don't see how this can work for Semantic Maps.

After I was bored on the plane and having looked at https://github.com/JeroenDeDauw/Maps/issues/98, I made a small extension called `SemanticNearBy` that uses the existing infrastructure, adds some simple ajax, and combine this with a `#nearby` parser function and you get https://youtu.be/lT62-dRDJA4.

Of course, not all nearby are meant to use a map, anyway:

-  template: specifies the template that contains the actual `#ask` query and any condition one wishes to display (knock yourself out)
doesn't work or is disabled
- maps: in case the template contains a map query then we routing it through
- detectlocation: whether HTML5 geolocation should be used or not
- watchlocation: monitor the location and adjust if necessary
- coordinates: can be set as starting parameters in case [geolocation](https://dev.w3.org/geo/api-/spec-source.html) class: a simple css class to manipulate the output display
- controls: slider or button
```
{{#nearby:
 |template=Local libraries,Point of interest
 |coordinates=47° 37' 13.9368'' N,122° 20' 56.8860'' W
 |radius=300 m
 |interval=450
 |maps=googlemaps
 |detectlocation=false
 |watchlocation=false
 |controls=slider
 |class=extra-nearby-location
}}
``` 
![image](https://cloud.githubusercontent.com/assets/1245473/12870333/689794bc-cd40-11e5-89a7-e3931ef5a631.png)

![image](https://cloud.githubusercontent.com/assets/1245473/12870348/e517c85e-cd40-11e5-9216-51b12fcb19d7.png)

PS: How you design the templates or queries is entirely up to you, `SemanticNearBy` doesn't really care for it.

**Comment by mwjames** [comment]
@JeroenDeDauw I came across some hacks, I'd rather avoid them:

Since the template (and its content including the maps) are parsed in the background (through the API), I had to manually load (took me sometime to find those things!!) to make sure that maps apis are loaded since the embedding page doesn't use the parser function itself.

Would be nice to have some kind of accessor, so I don't have to know any internals of Maps/SM such and can just inject this to the `ParserOutput`.

```
	$parser->getOutput()->addJsConfigVars( 'egMapsScriptPath', $GLOBALS['wgScriptPath'] . '/extensions/Maps/' );
	$parser->getOutput()->addHeadItem( \Html::linkedScript( '//maps.googleapis.com/maps/api/js?' . wfArrayToCgi( array() ) ), 'link' );
```

Each execution via JS/API/Promise generates a new `div` and needs to trigger a maps/openlayers specific event in JS, it would be nice to a have service/class I just call without me having to know the Maps/SM details `maps = new Maps( self.container ); maps.render( 'googlemaps' ); maps.render( 'openlayers' )`.

```
			// PLEASE a service 
			self.container.find( '.maps-googlemaps3' ).each( function() {
				var $this = $( this );
				$this.googlemaps( $.parseJSON( $this.find( 'div').text() ) );
			} );

			self.container.find( '.maps-openlayers' ).each( function() {
				var $this = $( this),
					mapData = $.parseJSON( $this.find( 'div').text() );

				$this.openlayers( $this.attr( 'id' ), mapData );
			} );
```

The `SMMapPrinter` is missing a `userparm` which in case of `NearBy` is used to route the geolocation to the `Template:Distance Popup` instead of having it fixed.

```

		$params['userparam'] = array(
			'default' => '',
		);
...
		$queryHandler->setUserParam( $params['userparam'] );
```

**Comment by JeroenDeDauw** [comment]
I'm not understanding all of this, though the parts I do are pretty cool.

Do you want to create a new "SemanticNearBy" extension to hold this `nearby` parser function? Seems to me that while this can be integrated with SMW functionality, there is nothing inherently semantic about it, in which case a "near by" extension with some features that only get enabled when SMW is also installed, might be better.

It's been several years now since I actively worked on Maps and Semantic Maps, so I can't really give you much advice. What I can say is that there is some weird design, and that the JS code is quite a mess (and has no tests whatsoever). As I do not have a MW installation, or even a webserver, its not easy for me to help with this either further than some CR and such.

**Comment by mwjames** [comment]
> Do you want to create a new "SemanticNearBy" extension to hold this nearby parser function? Seems to me that while this can be integrated with SMW functionality, there is nothing inherently semantic about it, 

In a strict yes but without any SMW data there is no point in asking for sightseeing spots near by, just having a map doesn't make much sense so in this regards annotated values (plus coordinates) are what makes this requiring SMW and SM specifically.

Strong dependency with Maps, weak dependency on SM/SMW (for the cited reasons)

> I'm not understanding all of this, though the parts I do are pretty cool.

Its a simple parser function to collect some parameters, throw them to the JS, the JS just tries to find the geolocation of the current browser (using HTML5), puts it all back to MW via the API where we expect a template to contain `#ask` queries.

>  new "SemanticNearBy" extension

Since it doesn't fit with any other extension and using HTML5/geolocation might raise privacy concerns it is best placed outside of any of the existing extensions (you can generally disable geolocation detection but that's not the point).

**Comment by kghbln** [comment]
I think this will be a very useful extension for people working heavily with maps. Personally the name "Semantic Vicinity" sounds cooler than "Semantic Near By" though the latter seems to be established term for this kind of feature.

**Comment by JeroenDeDauw** [comment]
Again thanks for all the cool work done here already. Unfortunately I'm really swamped with work, so cannot get to this for some time. I have a tabgroup open with the relevant issues so I don't forget.

> no point in asking for sightseeing spots near by, just having a map doesn't make much sense so in this regards annotated values

How about someone that has a list of locations that they want to display on such a map, but don't want to do anything with they need SMW for?

**Comment by mwjames** [comment]
> How about someone that has a list of locations that they want to display on such a map, but don't want to do anything with they need SMW for?

Well, a template may contain anything as long as it doesn't break the MW API parse but yes s(he) can use it without SMW.

I'm hesitant to call it `Nearby` extension just to indicate that it can be used without SMW.

**Comment by mwjames** [comment]
What about `WhatsNearby` as name for the extension?

**Comment by JeroenDeDauw** [comment]
Sounds reasonable. Alternate suggestion: Nearby Locations. Or to make @kghbln sense of coolness happy: Vicinicator (Vicinity and locator)

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/WhatsNearby
