### ISSUE TITLE
Help to fix SemanticMediawiki tests on jenkins (wikimedia)

### ISSUE THREAD

**Issue by paladox** [SemanticMediaWiki/SemanticMediaWiki#1405]
Could we have help to fix the tests on Wikimedia jenkins for SemanticMediaWiki since some extensions require it and fails because SemanticMediaWiki errors out.

Please see error at https://integration.wikimedia.org/ci/job/mwext-SemanticMediaWiki-testextension-hhvm/21/console

https://gerrit.wikimedia.org/r/#/c/269706/

**Comment by paladox** [comment]
I used composer update just now to check things and looking at there is no such class as SMW\Store or any other in class_alias. They should be changed around so that it looks like this

class_alias( 'SMWStore', 'SMW\Store' );

**Comment by paladox** [comment]
That fails too.

I'm not sure why the class insent being found.

**Comment by mwjames** [comment]
> I used composer update just now to check things and looking at there is no such class as SMW\Store or any other in class_alias. They should be changed around so that it looks like this
> class_alias( 'SMWStore', 'SMW\Store' );

No, this is not going to work .

[0] is described as `bool class_alias ( string $original , string $alias [, bool $autoload = TRUE ] )` with `SMW\Store` being the original [1].

Again, this is a classic symptom of the autoloader not being invoked and loaded correctly. I think, I tried to explain before (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1375#issuecomment-172196302) that if you do a proper `composer require ...` then the autoloading and with it the `SemanticMediaWiki.php` (where class aliases are defined [2]) are loaded in order.

[0] http://php.net/manual/en/function.class-alias.php

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SMW_Store.php

[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.php#L53-L117

**Comment by paladox** [comment]
Oh yes sorry.

**Comment by mwjames** [comment]
I'd say once WMF allows to install software via Composer on Jenkins (as it is required by SMW) we can provide assistance if necessary (which I doubt because the `install.md` is clear about what steps are required) but until then, there is no actionable task for us to follow-up and therefore closing this one.

**Comment by paladox** [comment]
Hi they do.

**Comment by paladox** [comment]
extension-unittests-composer

**Comment by paladox** [comment]
I belive it is todo with the way they are installing MySQL which I have uploaded a patch for and waiting for it to be merged. integration/config.
