### ISSUE TITLE
Smw-ask-query-search-info i18n issue

### ISSUE THREAD

**Issue by liuxinyu970226** [SemanticMediaWiki/SemanticMediaWiki#1412]
From https://phabricator.wikimedia.org/T127609:

What is $2? There is no documentation.

**Comment by kghbln** [comment]
I am pretty much confused. It used to be that I get an support request on translatewiki.net directly. Now things like this are cluttered all over the place: twn, phab, wherever ... However this is another story I believe.

I will look into this soon.

**Comment by kghbln** [comment]
This is the [message in question](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/i18n/en.json#L203)

**Comment by kghbln** [comment]
Done with this [edit](https://translatewiki.net/w/i.php?title=MediaWiki:Smw-ask-query-search-info/qqq&oldid=6707806).
