### ISSUE TITLE
Ask-query: first article in result is missing!

### ISSUE THREAD

**Issue by stefankaifer** [SemanticMediaWiki/SemanticMediaWiki#1413]
Hello

my system:
SMW 2.3.1
MediaWiki 1.26.2
PHP 5.6.9
MariaDB 5.3.45
Used seamntic extensions: Semantic Drilldown 2.0.1, Semantic Extra Special Properties	1.3.1, Semantic Forms Inputs	0.10.1, Semantic Maps	3.2, Semantic Result Formats 2.3, Semantic forms 3.4.3

**I've 125 articles** in the Category software, all of them has some properties. The following query in an article gives me **only 124 articles** as the result. **The first article** (Aasta ...) in the alphabetic order is missing.

The query:

`{{#ask:
[[Category:Software]]
|?Software vendor
|?Business-Process
|?Process-Owner
|?Key-User
|?Service-Owner
|?Service-Owner StV
|?Regulatorische Risikoeinstufung
|?Datenschutzintegrität
|?Datenschutzverfügbarkeit
|?Datenschutzvertraulichkeit
|format=broadtable|limit=500|link=all|sort=Software name|headers=show|mainlabel=Software name|searchlabel=… weitere Ergebnisse|class=sortable wikitable smwtable}}
`

I think, that is a bug.
Can you confirm it?

Regards,

Stefan

**Comment by s7eph4n** [comment]
Does `Aasta` have the property `Software name` set?

**Comment by stefankaifer** [comment]
Yes, see:

![properties](https://cloud.githubusercontent.com/assets/17417801/13235630/4396efec-d9bf-11e5-9767-7e9e4a71edd6.png)

**Comment by s7eph4n** [comment]
A common problem with sorted queries is, that the property used for sorting (`Software name` in this case) needs to be available for all result items. If not, the resprective item will be dropped from the result set. 
If that is not the problem in this case I have no idea.

**Comment by stefankaifer** [comment]
Yes, you're right. I've checked the list and found the missing property. It was my fault. Please close this case. Thank you very much for your support!
