### ISSUE TITLE
Add options for displaying images in query results (T32002)

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#1418]
continued from: https://phabricator.wikimedia.org/T32002

summary: allow to set the thumb size in query results like

```
{{#ask: ...
   ?my image property#130px
 }}
```

There has already been a patch for this which. See Phabricator.

Would be cool to get this feature into SMW.

**Comment by kghbln** [comment]
The patch suggested:
```
--- SemanticMediaWiki/includes/datavalues/SMW_DV_WikiPage.php	Fri Aug 03 16:33:57 2012
+++ SemanticMediaWiki/includes/datavalues/SMW_DV_WikiPage.php	Fri Aug 03 16:33:30 2012
@@ -193 +193 @@
-				$defaultCaption = '|' . $this->getShortCaptionText() . '|frameless|border|text-top';
+				$defaultCaption = '|' . $this->getShortCaptionText() . '|frameless|border|' . $this->m_outformat . '|text-top';
```

**Comment by mwjames** [comment]
> +               $defaultCaption = '|' . $this->getShortCaptionText() . '|frameless|border|' . $this->m_outformat . '|text-top';

Maybe the parsing should be a bit more sophisticated oppose to of just placing `$this->m_outformat` as plain string (sth. more expressive such as ` |?MyFile#-s[130px]`)

PS: I marked this issue as `easy` which means that I will __not__ engage and expect the community to pick them up but of course I will give assistance as needed.
