### ISSUE TITLE
Create extension.json in favor of new extension registration method

### ISSUE THREAD

**Issue by codynguyen1116** [SemanticMediaWiki/SemanticMediaWiki#1420]
SemanticMediaWiki should have an extension.json file to support the new extension registration method, `wfLoadExtension()`. 

https://www.mediawiki.org/wiki/Manual:Extension_registration

**Comment by mwjames** [comment]
> SemanticMediaWiki should have an extension.json file to support the new extension registration method,

My position on this topic is outline in #1367.

**Comment by kghbln** [comment]
Closed in favour of the [mentioned](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1420#issuecomment-189135299) issue
