### ISSUE TITLE
hardcoded colors on Special:Ask

### ISSUE THREAD

**Issue by timriker** [SemanticMediaWiki/SemanticMediaWiki#1426]
MediaWiki 1.25.1
SematicMediaWiki: 2.3.1
deployed from composer.json settings into cloud foundry instance. Not available publicly.

There are two lines in
extensions/SemanticMediaWiki/includes/specials/SMW_QuerySpecialPage.php
That set style background to either white or #eee. This does not work for a mediawiki dark theme.

Example: after setting:
$wgAllowUserJs = true;
$wgAllowUserCss = true;
$wgAllowUserCssPrefs = true;
$wgAllowSiteCSSOnRestrictedPages = true;

load this as MediaWiki:Vector.css 
https://www.mediawiki.org/wiki/Skin:Vector-DarkCSS

Suggestion:

reference styles instead and add these styles to
res/smw/special/ext.smw.special.ask.css

**Comment by kghbln** [comment]
The lines in question:
- [L99](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/specials/SMW_QuerySpecialPage.php#L99)
- [L109](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/specials/SMW_QuerySpecialPage.php#L109)
