### ISSUE TITLE
Content missing from Property pages after upgrade

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#1446]
Dear all,

Today I tried to upgrade from SMW 2.1 (MW 1.24.2) to the latest stable version, 2.3.1, by transferring the files and the database to a local PC and doing the upgrade from there. I managed to import the database, although there was an error message saying that the variable ‘time_zone’ can’t be set to the value of ‘NULL’. I then followed instructions from https://www.semantic-mediawiki.org/wiki/Help:Installation/Upgrade_from_SMW_1.9%2B_for_MW_1.22%2B. Everything seemed to be in order, as far as I could see, until the final part involving use of SMW_refreshData.php. The refresh got stuck at ID 2029 out of 2225166. 

When I took a closer look at the site, I noticed that pages in the Property namespace were only showing the automatic queries that come with SMW but any content I added manually was invisible on the page (except in the source code). I depend very heavily on a form and template to organise the use of properties, including their datatypes; one of the unfortunate consequences of this is that all properties have now defaulted to the Page datatype, basically causing havoc to the entire site.

I've re-triggered SMW_refreshData.php, so hopefully things will get back to normal in the process. Sadly, I don't know if it is worth the wait as it is taking an awful lot of time.

**Comment by mwjames** [comment]
I'm a bit at loss with above description.

> Today I tried to upgrade from SMW 2.1 (MW 1.24.2) to the latest stable version, 2.3.1, by transferring the files and the database to a local PC and doing the upgrade from there.

What exactly does this entail? SMW 2.1 (MW 1.24.2)  to SMW 2.3.1 (MW 1.24.2) ?

>  I managed to import the database

Import, how? Did you copy the smw* tables? @kghbln I'm not a expert on administration, maybe you can shed some light on this.

> Everything seemed to be in order, as far as I could see, until the final part involving use of SMW_refreshData.php. The refresh got stuck at ID 2029 out of 2225166.

Stuck and what happen next? Did it remain? Did it output an exception?

> I noticed that pages in the Property namespace were only showing the automatic queries that come with SMW but any content I added manually was invisible on the page (except in the source code).

This might indicate that smw* tables content are missing.

> automatic queries that come with SMW

Not sure what you mean by "automatic queries".

>  one of the unfortunate consequences of this is that all properties have now defaulted to the Page datatype, 

This can only happen when a property page was not parsed and the associated `SemanticData` in the underlying tables are empty or have not been populated.

> Sadly, I don't know if it is worth the wait as it is taking an awful lot of time.

https://www.semantic-mediawiki.org/wiki/Help:RebuildData.php#Quick_and_slow_progress

**Comment by D-Groenewegen** [comment]
Thanks for the response, mwjames! I'll go over your questions and comments
point by point

| SMW 2.1 (MW 1.24.2) to SMW 2.3.1 (MW 1.24.2) ?

exactly

| Import, how?

Exported an .sql dump from the web server and imported this locally in
Phpmyadmin, on a Windows computer. I then used the imported database to
initiate the MW installation locally, of course using the files from the
remote server. Everything looked alright at this point. I had a near
identical copy of the website running on my computer and the queries were
working. The only thing I needed to change was the URL system (switched
from short to long URLs).

| Stuck and what happen next?

Nothing happened.
A second run of SMW_refreshData.php did

> "PHP Catchable fatal error: argument 1 passed to
.../Subobject::__construct must be an instance of Title, null given, called
in ... QueryProfileAnnotatorFactory on line 29 defied ...Subobject.php on
line [?}.

| Not sure what you mean by "automatic queries".

Pages in the 'Property' namespace are automatically populated with queries
under the subheading 'Pages using the property ...'.

| This can only happen when a property page was not parsed and the
associated SemanticData in the underlying tables are empty or have not been
populated.

Template:Property - the template I add to pages in the 'Property' namespace
- is used to ensure that the right datatype is specified and stored for
each property, but the templates were no longer parsed after the upgrade,
hence the rest of the story. I assume that the templates were correctly
parsed before the upgrade, based on the fact that the queries were working
beforehand - that line of reasoning may not be entirely solid though.

*New*: Template:Property is not parsed either if it used in the main
namespace. This is evidently an important clue because it suggests that the
problem probably does not lie with SMW, which should be good news, in a
way. I'll focus on javascript errors and potential conflicts caused by
other extensions.

|
https://www.semantic-mediawiki.org/wiki/Help:RebuildData.php#Quick_and_slow_progress

Per the documentation, I used SMW_refreshData.php, not rebuildData.php.
Should I give the other one a go?

Best,
Dennis


2016-03-10 11:38 GMT+01:00 mwjames <notifications@github.com>:

**Comment by D-Groenewegen** [comment]
A couple of updates:

First, I should modify my description slightly. Any user-added content that failed to render did so only when Template:Property was being used/transcluded anywhere on the page.  

Second, there is some good news. At the moment, property pages are gradually returning to normal. What I did was take a good look at Template:Property to see what could be contributing to this issue. I may have found the perpetrator or at least an accomplice: embedded within this template is a variant of Template:CategoryTOC (see mediawiki.org). This is working fine on the live site but may be too much for my PC when the database is still in being rebuilt: the CategoryTOC template involves a lot of calls to both the 'fullurl' parser and the FULLPAGENAME magic word; by "a lot" I mean one call per each single letter or number, e.g. [{{fullurl:{{FULLPAGENAME}}|from=y}} y]. Template:Property became functional again after I removed from it any call to Template:CategoryTOC. At the moment, Template:CategoryTOC usually still fails to get parsed on transclusion but there are occasions, perhaps when traffic is relatively low, when it is working all of a sudden. 

As for the "PHP Catchable fatal error", I'm aware now that this is essentially a separate issue and has been addressed by #1318.

**Comment by D-Groenewegen** [comment]
We should be OK here. Multiple things were going on, so let me reiterate
the main points:

#1. PHP Catchable fatal error:
* The first rebuild was interrupted because of an issue with XML. Without
having a firm grip on this, I won't waste your time on this. Thanks for the
tip about ignoring exceptions.
* The second rebuild was interrupted because of an issue that is known and
has been sufficiently addressed.

#2. Precisely why and under which circumstances Template:CategoryTOC is
giving me such a headache is unclear. While the issue only appeared after
an upgrade of SMW, it's not at all evident that SMW has any part in it. To
the extent that SMW may be responsible, it deserves a separate report
anyway.

#3. SMW_refreshData.php is depreciated in favour of rebuildData.php



2016-03-10 13:59 GMT+01:00 Dennis Groenewegen <dennisgroenewegen@gmail.com>:

**Comment by mwjames** [comment]
Can we close this?

**Comment by D-Groenewegen** [comment]
We can, that's what I meant.



2016-03-13 22:56 GMT+01:00 mwjames <notifications@github.com>:
