### ISSUE TITLE
Replace inContentLanguage

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1452]
I just realized that most errors are displayed in or by using `inContentLanguage` which isn't really what we want, so either remove this or explicitly use `inLanguage( ... )`to ensure that messages are displayed in the user language selected.

http://sandbox.semantic-mediawiki.org/wiki/Issue/1243_%28Make_failed_queries_discoverable%29

Content language being FR, user language is EN but the error is displayed in FR.

**Comment by mwjames** [comment]
@kghbln Maybe should make an analysis where such change makes most sense.

**Comment by JeroenDeDauw** [comment]
What errors is this about? What you are saying makes sense to me for special pages and such things that are not cached. Not for things that are cached, such as the content of pages.

**Comment by mwjames** [comment]
Mostly happened with #1768.

It may that we missed something but those should appear in the `Special:ProcessingErrorList` as not "translatable" when a user switches its language.
