### ISSUE TITLE
'off ... on' surrounding queried text in text values

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#1453]
Continuing from #1448
> Another odd thing I noticed is the appearance of the words 'off' and 'on' surrounding a link when that link is produced by a query. The link comes from a value of a property that has the datatype 'Text'. 

Well, I've learned since then that it is not necessarily linked text which gets them. What I'm referring to is now also demonstrated at the SMW sandbox site;

http://sandbox.semantic-mediawiki.org/wiki/Offon/annotated_page

The query below shows how 'off ... on' intrude into the text, while the "facts about" section signals issues with the text value. 

I never experienced this on SMW 2.1.3.

**Comment by mwjames** [comment]
> now also demonstrated at the SMW sandbox site;

A bonus point for the comprehensive use case.

Relates to #1320 which makes sure that annotations within a text output are not imported by removing `[[ ... ]]` (which signals to the `InTextAnnotationParser` to parse a text and find possible annotations).

> http://sandbox.semantic-mediawiki.org/wiki/Offon/annotated_page

The example has been added to our integration test suite.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/bug-1453/tests/phpunit/Integration/ByJsonScript/Fixtures/f-0802.json

**Comment by D-Groenewegen** [comment]
Thanks and even more bonus points to yourself for doing a wonderful job!



2016-03-13 23:42 GMT+01:00 mwjames <notifications@github.com>:
