### ISSUE TITLE
HHVM test failures 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1456]
relates to the discussion in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1424#issuecomment-196066449

> Starting test 'SMW\Tests\IntlTimeFormatterTest::testFormat with data set #3 ('2/1300/11/02/12/03/25.888499949', 'Y-m-d H:i:s.u', '1300-11-02 12:03:25.888500 JL')'.
> F
> Starting test 'SMW\Tests\IntlTimeFormatterTest::testFormat with data set #4 ('2/1300/11/02/12/03/25.888499949', 'H:i:s.u', '12:03:25.888500')'.
> F

Was reported with https://github.com/facebook/hhvm/issues/6899.

> Fatal error: Cannot access protected property SMWQuantityValue::$m_unitin

Caused by https://github.com/facebook/hhvm/issues/5128.

>  Undefined index: json

Was reported with https://github.com/facebook/hhvm/issues/7402 (https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/9e5182715f8f83926db1c2cbc993702ca8eb4eaf)

**Comment by ochaochaocha3** [comment]
@mwjames Do you plan to fix the assertion failure of SMWQuantityValue::$m_unitin? It's bothersome to unquote `'$this->m_unitfactors[$this->m_unitin] != 0'` after every update.

**Comment by mwjames** [comment]
@JeroenDeDauw ??

**Comment by mwjames** [comment]
@ochaochaocha3 私の場合は今ちょっと忙しいので、PRをしていただければ幸いです。

**Comment by JeroenDeDauw** [comment]
> @JeroenDeDauw ??

huh?

**Comment by mwjames** [comment]
> Do you plan to fix the assertion failure of SMWQuantityValue::$m_unitin? It's bothersome to delete the quotes of '$this->m_unitfactors[$this->m_unitin] != 0' after every update.

Fixed with #1784
