### ISSUE TITLE
Parsing trouble with the Replaceset extension (SMW 2.4alpha)

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#1458]
Here's another test report for SMW 2.4alpha.

Since upgrading to SMW 2.4alpha (MW 24.2), I get a lot of messages saying that <pre><strong class="error">The ReplaceSet call limit (600) has been reached</strong></pre>. The error message comes from the ReplaceSet extension and the limit ('600') represents a configuration setting. The #replaceset parser is mainly used, using templates, to do two things: 

#1 to change a page's default sortkey automatically

#2 to substitute square brackets for html code: Template:Reference is used to let a citation for a book article (text value) import part of the citation from the book to which it belongs (queried text value). Because SMW has, or had, difficulties with importing square brackets even if they were html-encoded originally, I used #replaceset to convert them back to html code again in the titles of book articles. 

The problem:

#1 The error message above (beginning in a less-than sign) replaces the value of the default sortkey and so many pages end up in the wrong category section. This is bad alright and I can't really explain this. I've had to remove the call to #replaceset and this is gradually taking effect. 

#2 The imported part of the citation (book citation) is not stored correctly. Instead it shows <strong class="error">The ReplaceSet call limit (600) has been reached</strong>. For instance:

> Jaski, Bart, “kings and kingship”, in: <strong class="error">The ReplaceSet call limit (600) has been reached.</strong>. 251–254

Although resaving pages temporarily helps to restore things, I could not get rebuildData.php or maintenance/update.php to do this for the entire wiki and in fact, rebuildData.php with maintenance/runJobs.php seems to reinstate the unwanted behaviour. 

The issues are not transparent to me and I've seen another instance in which even uncomplicated use of #replaceset was enough to trigger the same error message. I hesitated to bring this up but the underlying problem may be more important than the immediate issue at hand (incompatibility with the ReplaceSet extension). One of SMW's new features is the 'In-text annotation parser', which appears to be invoked on every page. Could it be that this somehow ends up creating a loop of some sort?

**Comment by mwjames** [comment]
> The imported part of the citation (book citation) is not stored correctly. Instead it shows The ReplaceSet call limit (600) has been reached.

I don't know this extension and I'm not sure I understand the circumstances in how SMW could be involved. Unless there is a stack trace or direct correlating evidence that would indicate the cause I'm not sure what SMW can do.

I'm guessing the error message is emitted by/from [0].

> The #replaceset parser is mainly used, using templates, to do two things:

SMW core has not changed in a way templates are used, it only renders templates in connection with `format=template` and `#set` (if the template parameter is used).

>  One of SMW's new features is the 'In-text annotation parser', which appears to be invoked on every page. Could it be that this somehow ends up creating a loop of some sort?

No. The so-called `'In-text annotation parser'` is in existence since the beginning of SMW and is nothing new or has been changed in recent releases [0]. This parser is responsible for finding `[[ ..  :: .. ]]` annotations, filter property/value assignments, and replace the content to follow normal wiki text output rules (based on the type).

`'In-text annotation parser'` is called from the `InternalParseBeforeLinks` hook which happens after all internal parser functions like `#replaceset`, `#set` etc. have been processed.

[0] https://github.com/wikimedia/mediawiki-extensions-ReplaceSet/blob/master/ReplaceSet.class.php#L21-L23

**Comment by mwjames** [comment]
>  Instead it shows The ReplaceSet call limit (600) has been reached.

If you want to find out why `if ( $called > $egReplaceSetCallLimit ) {` is reached try amending `ReplaceSet.class.php` with something like:

```
		if ( $called > $egReplaceSetCallLimit ) {
			wfDebugLog( 'replaceset', wfGetAllCallers( 5 ) );
			//return self::error( 'replaceset-error-calllimit', $egReplaceSetCallLimit );
		}
```

and log these calls via LocalSettings:

```
$wgDebugLogGroups  = array(
	'replaceset' => "myLocationOfTheLogFile/replaceset.log"
);
```

You may need to adjust the `wfGetAllCallers( 5 )` limit (mostly by trial and error as it relies on the internal stack trace) to find out when and by whom the parser is invoked.

For a description of `wfGetAllCallers`, see [0].

[0] https://github.com/wikimedia/mediawiki/blob/5b119a0e442306d90198deead25f6a975513e65e/includes/GlobalFunctions.php#L1621-L1635

**Comment by D-Groenewegen** [comment]
Thanks for the details and lightning response! I tried what you suggest and will keep an eye on the log to find out if the issue can be reproduced. 

The ReplaceSet extension is a useful extension if you need to replace invalid or unwanted characters automatically. But at this moment I'm not relying on it very extensively. I just changed the category collation to <tt>uca-ga</tt> (Unicode collation algorithm for Irish) so hopefully I won't need to fiddle around with <tt>{{DEFAULSORT}}</tt> (a 'magic word' for changing default sortkeys) any longer. 

Unless SMW can be shown to play a part in this, I think you can close this topic for now.
