### ISSUE TITLE
ParameterInput causes "HTML attribute value can not contain a list of values"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1473]
### Setup and configuration

- SMW version: 2.4-alpha
- MW version:
- DB (MySQL etc.):

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
[5ec25b63] /w/index.php?title=Sp%C3%A9cial%3AAsk&q=%5B%5BHas+coordinates%3A%3A%2B%5D%5D&po=Has+coordinates&eq=yes&p%5Bformat%5D=openlayers&sort_num=&order_num=ASC&p%5Bsource%5D=&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%26hellip%3B+autres+r%C3%A9sultats&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&eq=yes MWException from line 572 of /var/www/htdocs/mw/02100/w/includes/Html.php: HTML attribute value can not contain a list of values

Backtrace:

#0 /var/www/htdocs/mw/02100/w/includes/Html.php(307): Html::expandAttributes(array)
#1 /var/www/htdocs/mw/02100/w/includes/Html.php(219): Html::openElement(string, array)
#2 /var/www/htdocs/mw/02100/w/includes/Html.php(247): Html::rawElement(string, array, string)
#3 /var/www/htdocs/mw/02100/w/includes/Html.php(724): Html::element(string, array)
#4 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/ParameterInput.php(181): Html::input(string, array, string, array)
#5 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/ParameterInput.php(118): SMW\ParameterInput->getStrInput()
#6 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/specials/SMW_QuerySpecialPage.php(154): SMW\ParameterInput->getHtml()
#7 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/specials/SMW_QuerySpecialPage.php(66): SMWQuerySpecialPage->showFormatOption(ParamProcessor\Definition\StringParam, boolean)
#8 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(427): SMWQuerySpecialPage->showFormatOptions(string, array)
#9 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(361): SMWAskPage->getInputForm(string, string, string, string)
#10 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(63): SMWAskPage->makeHTMLResult()
#11 /var/www/htdocs/mw/02100/w/includes/specialpage/SpecialPage.php(384): SMWAskPage->execute(NULL)
#12 /var/www/htdocs/mw/02100/w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run(NULL)
#13 /var/www/htdocs/mw/02100/w/includes/MediaWiki.php(263): SpecialPageFactory::executePath(Title, RequestContext)
#14 /var/www/htdocs/mw/02100/w/includes/MediaWiki.php(634): MediaWiki->performRequest()
#15 /var/www/htdocs/mw/02100/w/includes/MediaWiki.php(482): MediaWiki->main()
#16 /var/www/htdocs/mw/02100/w/index.php(41): MediaWiki->run()
#17 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

- http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AAsk&q=[[Has+coordinates%3A%3A%2B]]&po=Has+coordinates&eq=yes&p[format]=openlayers&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=%26hellip%3B+autres+r%C3%A9sultats&p[default]=&p[class]=sortable+wikitable+smwtable&p[sep]=&eq=yes

**Comment by mwjames** [comment]
Caused by `ParameterInput::getValueToUse` with returns an empty array and causes the HTML class to fall over:

### Solution
```
@@ -138,10 +138,14 @@ class ParameterInput {
 
 		if ( $this->param->isList() && is_array( $value ) ) {
 			$value = implode( $this->param->getDelimiter(), $value );
 		}
 
+		if ( $value === array() ) {
+			$value = '';
+		}
```

**Comment by djflux** [comment]
I am having this issue (screenshot similar to https://github.com/fuerthwiki/wiki/issues/97) and want to see if I should open a separate issue.

Here are my versions.

Product | Version
-- | --
MediaWiki | 1.31.0 (5cfc9ac)2018-06-13T10:34:24
PHP | 7.0.31 (apache2handler)
MariaDB | 5.5.60-MariaDB
ICU | 50.1.2
Elasticsearch | 5.6.11
Semantic MediaWiki | 2.5.6
Page Forms | 4.3.1 (0ba6735)2018-06-18T15:35:28

**Comment by mwjames** [comment]
> I am having this issue (screenshot similar to
> https://github.com/fuerthwiki/wiki/issues/97) and want to see if I should
> open a separate issue.

As indicated at the top, the issue relates to `Special:Ask` and the
`ParameterInput` component and is not related to the PageForms
extension.

A similar same error message (most likely created by
`Html::expandAttributes` [0]) does not indicate the same causation, so
unless a stack trace is produced (similar to what can be seen at the
top) that identifies a SMW function a center of the cause, I would
refer you back to the PageForms extension and its maintainer.

[0] https://github.com/wikimedia/mediawiki/blob/379407a640f68c9abf10e1da88c8687826d45be0/includes/Html.php#L540

Cheers
