### ISSUE TITLE
Make SMW compatible with current MW extension loading practices

### ISSUE THREAD

**Issue by JanZerebecki** [SemanticMediaWiki/SemanticMediaWiki#1479]
I haven't read all the discussions regarding this, so I'm likely missing something, but I'll just create this task now...

https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1405#issuecomment-195769059

> I'd say once WMF allows to install software via Composer on Jenkins

The CI setup that is hosted on WMF provided nodes does allow using composer. Wikibase does do successfully.

I think the problem we need to fix is that SMW enables itself (as in the Mediawiki extension) when the composer autoloader is `require`ed by Mediawiki core. Mediawiki core does not expect this. Wikibase also did this in the past and was fixed.
SMW extensions may have the same problem.

**Comment by JanZerebecki** [comment]
If my memory serves me right deleting the line https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/25d78f6/composer.json#L73 would make it not fail. But maybe there is more.

**Comment by mwjames** [comment]
> I haven't read all the discussions regarding this, so I'm likely missing something, but I'll just create this task now...
> I think the problem we need to fix is that SMW enables itself (as in the Mediawiki extension)

My position on this topic has been outlined in #1367.

**Comment by JanZerebecki** [comment]
This is not about extension.json, but only about not enabling the extension when the composer autoloader is required by Mediawiki core as it is not ready at that time to enable the extension, but enable it at a time when core is ready for it.

**Comment by mwjames** [comment]
> This is not about extension.json, but only about not enabling the extension when the composer autoloader is required by Mediawiki core

Well, SMW requires the Composer autoloader as we expect PSR-4 to work (manual class registration is no longer supported and highly discouraged).

> If my memory serves me right deleting the line https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/25d78f6/composer.json#L73 would 

`class_alias` being registered by the time of the invocation and removing the file will most likely cause SMW to fail.

> y Mediawiki core as it is not ready at that time to enable the extension, but enable it at a time when core is ready for it.

How would this look like as I'm unaware of any way that would be accomplished without introducing some special MW hack.

You are aware that our tests do work on Travis without any special treatment and I'm wondering why WMF/Jenkins is unable to follow.

**Comment by mwjames** [comment]
> You are aware that our tests do work on Travis without any special treatment and I'm wondering why WMF/Jenkins is unable to follow.

I don't want to sound like a broken record (as already outlined in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1375#issuecomment-172196302) but to help clarify the issue:

- You install MW (without or with DB)
- You run `composer require` from the MW root
- Composer ensures that libraries (and yes we do use libraries and those need to be installed and registered before you continue) and classes are autoloaded (PSR-4 approach)
- You then add some customizing
- Run `php maintenance/update.php --quick`
- and that's it

**Comment by paladox** [comment]
Yes I think that's how we do it on jenkins but its when the db is installed is the problem. If you install the db before installing the extension that's fine then you run the db update after. But if you install extension then do the db install that is where the problem comes in.

**Comment by JanZerebecki** [comment]
> > This is not about extension.json, but only about not enabling the extension when the composer autoloader is required by Mediawiki core

> Well, SMW requires the Composer autoloader as we expect PSR-4 to work (manual class registration is no longer supported and highly discouraged).

With required I meant core its `require_once "$IP/vendor/autoload.php";` ( at https://phabricator.wikimedia.org/diffusion/MW/browse/master/includes/WebStart.php;fbe9167b89baa2edb42eb1367aa860bb2d10cdba$82 or https://phabricator.wikimedia.org/diffusion/MW/browse/master/maintenance/doMaintenance.php;fbe9167b89baa2edb42eb1367aa860bb2d10cdba$75 ). At that point in the initialization no extension may register/load itself, as the Mediawiki installer may yet need to run. 

Doing any side effects when the autoloader is require_once-ed is a bad code smell even without this special requirement by Mediawiki core.

> > If my memory serves me right deleting the line https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/25d78f6/composer.json#L73 would

> class_alias being registered by the time of the invocation and removing the file will most likely cause SMW to fail.

Why would SMW fail if you require_once that file later?

> I don't want to sound like a broken record (as already outlined in #1375 (comment)) but to help clarify the issue:

Those installation instructions are not compatible with current versions of Mediawiki core.

> You install MW (without or with DB)

How do you do that without running composer? Mediawiki needs composer provided libraries.

> You are aware that our tests do work on Travis without any special treatment and I'm wondering why WMF/Jenkins is unable to follow.

It runs composer update once with the composer-merge-plugin for core and the selected extensions together. Afterwards the Mediawiki installer needs to run.

**Comment by mwjames** [comment]
> The CI setup that is hosted on WMF provided nodes does allow using composer. Wikibase does do successfully.

As of #2080, Semantic* extensions are no longer available in the WMF repository and with the removal of those a discussion about CI integration or MediaWiki loading practice seems rather a rhetorical discourse than that of one with practical relevance.

Thanks for the discussion and elaboration.
