### ISSUE TITLE
#smwdoc fatals if not listed

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1484]
Refs: [Help:Incoing_format](https://www.semantic-mediawiki.org/wiki/Thread:Semantic-mediawiki.org:Community_portal/Help:Incoming_format)

When trying to access the [docu page](https://www.semantic-mediawiki.org/wiki/Help:Incoming_format) the following fatal appears (blanc page):

```
Notice: Undefined index: language in /.../w/extensions/SemanticMediaWiki/includes/parserhooks/DocumentationParserFunction.php on line 40
Fatal error: Call to a member function getValue() on null in /.../w/extensions/SemanticMediaWiki/includes/parserhooks/DocumentationParserFunction.php on line 40
```

Step to mitigate for the time being: [Comment out #smwdoc](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AIncoming_format&type=revision&diff=43747&oldid=39379)

**Comment by mwjames** [comment]
Is #1328 the same issue?

**Comment by kghbln** [comment]
@mwjames Apparently. Admittedly I lost track of a couple of things. :(
