### ISSUE TITLE
Add error handling to DocumentationParserFunction and InfoParserFunction

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1485]
They both do `$parameters = $result->getParameters();` and then do things with `$parameters`. Should first check if the processing was valid, and if not, display some kind of error. Something like

``` php
if ( $result->hasFatal() ) {
    return $this->getOutputForErrors( $result->getErrors() );
}
```

**Comment by JeroenDeDauw** [comment]
The PHP errors are now avoided by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1717

The `getOutputForErrors` methods should get a real implementation though:

* [ ] Display what went actually wrong, so the user can fix it
* [ ] Internationalization of the text

**Comment by mwjames** [comment]
Moving this to [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4
