### ISSUE TITLE
ExportRDF produces XML Parsing Error: « xmlns:="" »

### ISSUE THREAD

**Issue by infinite-dao** [SemanticMediaWiki/SemanticMediaWiki#1488]
### Setup and configuration

- SMW version: 2.3.1 
- MW version: 1.26.2
- DB (MySQL etc.): MySQL

### Issue

Special:ExportRDF produces not well or invalid XML:
`XML Parsing Error: not well-formed`
`Location: http://terms.tdwg.org/wiki/Special:ExportRDF/xmpRights:WebStatement`
`Line Number 21, Column 8:`
`xmlns:=""`
`------^`

an empty here. Digging in the PHP code I only see that it has to do with extra_namespaces stuff which I do not understand completely. My guess is that in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/includes/export/SMW_Serializer.php#L199 somehow empty values get evaluated because the RDF exporter produces `<rdf:RDF ... xmlns:="" >` which appears to be invalid XML.

Has it to do with Import name spaces?
Is there something not specified, which should be specified?

**Comment by mwjames** [comment]
Could you try creating an isolate example on the sandbox [0] otherwise it will take some time before I have look at it (== also to verify that the issue still occurs with 2.4-alpha).

[0] http://sandbox.semantic-mediawiki.org

**Comment by infinite-dao** [comment]
I realize that after an update MW 1.207 to 1.26.2 many pages are displaying on "Browse properties" Imported from: '' (value not understood). After a no-edit-save of the page the Imported-from-value is saved correctly and does show up in the RDF XML which previously had not. Somehow the undefined or empty values of "Imported from" cause the serializer to print empty name spaces. I now running maintenance runJobs.php in the hope that this refreshes the data or use the rebuildData.php thing.

But in any case: are empty "Imported from" filtered out somehow to cause invalid XML? I understand it's a difficult case here to fetch all possible failures that may come from the semantic data and have a meaningful work around or warning in place.

**Comment by mwjames** [comment]
> After a no-edit-save of the page the Imported-from-value is saved correctly and does show up in the RDF XML which previously had not. Somehow the undefined or empty values of "Imported from" cause the serializer to print empty name spaces.

As noted in [0, 1], #891 enforces strict typing of imported properties which means that the imported type is now directly linked (or better is made mandatory) to the property that makes the import reference to avoid having a vocab to define a type while somehow a local declared property uses a contradictory type.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-2.2.0.md#new-features
[1] https://www.semantic-mediawiki.org/wiki/Help:Import_vocabulary_%28Vocabulary_definition%29

**Comment by mwjames** [comment]
I'm not sure how to prevent this issue other than to throw a `RuntimeException` if the NS is empty which normally should not happen.

I believe that due to a missing `rebuildData` particular after #891 caused a temporary unmatched `Imported from` annotation state where [0] returned an empty string and by the time the Serializer got hold of the value representation a `xmlns:=""` was generated, causing the XML to cry for help.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Exporter/DataItemToExpResourceEncoder.php#L216

**Comment by mwjames** [comment]
> After a no-edit-save of the page the Imported-from-value is saved correctly and does show up in the RDF XML which previously had not.

A note has been added to [0].

[0] https://www.semantic-mediawiki.org/wiki/Help:Import_vocabulary_%28Vocabulary_definition%29
