### ISSUE TITLE
Fatal error: Class 'SMW\SMWDIProperty' not found (RdfResultPrinter.php on line 94)

### ISSUE THREAD

**Issue by infinite-dao** [SemanticMediaWiki/SemanticMediaWiki#1489]
### Setup and configuration

- SMW version: 2.3.1
- MW version: 1.26.2
- DB (MySQL etc.): MYSQL

### Issue
Export a category in `#ask` result in fatal error: on http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:ExpandTemplates insert:
`{{#ask: [[Category:Colour‏‎]] `
`|?Catégorie`
`|?Has boolean`
`| format=RDF}}`

Produces a link which is:

http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Ask/-5B-5BCategory:Colour-5D-5D/-3FCat%C3%A9gorie/-3FHas-20boolean/mainlabel%3D/limit%3D100/offset%3D0/format%3DRDF

and this produces an empty page. The same on the wiki I administer. It reports:
`Fatal error: Class 'SMW\SMWDIProperty' not found in `/extensions/SemanticMediaWiki/includes/queryprinters/RdfResultPrinter.php on line 94`

Checking the PHP code in [RdfResultPrinter.php on line 94](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/includes/queryprinters/RdfResultPrinter.php#L94) there is no SMWDIProperty defined in the namespace SMW only a DIProperty (SMW_DI_Property.php)
Should it not read `DIProperty` instead of `SMWDIProperty` on line 94? At least it works changing `SMWDIProperty` to `DIProperty` on line 94 in RdfResultPrinter.php

**Comment by JeroenDeDauw** [comment]
Might be fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1490

**Comment by mwjames** [comment]
> Checking the PHP code in RdfResultPrinter.php on line 94 there is no SMWDIProperty defined in the namespace SMW only a DIProperty (SMW_DI_Property.php)

Right, something didn't really match here (namespace wise) and the sad thing is that no one has noticed it before and with no test in place the particular code path was never executed.

As for the missing test, #1491 should address this deficiency.
