### ISSUE TITLE
smwgNamespacesWithSemanticLinks not working

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#1519]
### Setup and configuration

- SMW version: 2.2.2 (17831fb)
- MW version: 1.25.5 (adacd21)
- DB: MySQL

### Issue

The $smwgNamespacesWithSemanticLinks setting doesn't seem to work.  Setting it has no effect.  Looking at #184 shows that twn saw a similar problem, but setting the variable before or after SMW is loaded seems to have no affect.  I even tried setting it in index.php before anything else, but, again, no affect was seen.

I suspected caching of some sort but restarting everything didn't seem to do anything.

**Comment by kghbln** [comment]
@hexmode Is this a fresh install? If not you need to run "rebuildData.php" to get the data for already existing pages in.

This setting must be after the `enableSemantics(...);` call and after all the namespaces are defined for the wiki. Could you post your configuration setting for this, but I believe it will be something like `$smwgNamespacesWithSemanticLinks[NS_TALK] = true;` so I do not expect much from this. Just did this two days ago on one of my wikis without worries.

**Comment by hexmode** [comment]
Note that I ended up getting [this error in ApprovedRevs](https://phabricator.wikimedia.org/T132807) that I'm currently working around.

**Comment by kghbln** [comment]
So if I interpret your response correctly this is working for you again though giving other worries.

**Comment by hexmode** [comment]
yes, I think we can assume that rebuildData is going to fix it.  I've found a fix for the ApprovedRevs issue and it is chugging along.   I should know by tomorrow.

**Comment by kghbln** [comment]
A great. I hope that ApprovedRevs is going to be cool soon, too!

**Comment by hexmode** [comment]
Note that this is solved, but rebuildData.php didn't solve the problem.  The problem ended up with the way I was setting $smwgNamespacesWithSemanticLinks.  I assumed it worked like a some other namespace variables ($[wgCollectionArticleNamespaces](https://www.mediawiki.org/wiki/Extension:Collection), $[wgVisualEditorNamespaces](https://www.mediawiki.org/wiki/Extension:VisualEditor#Old_configuration_parameters), $[egApprovedRevsNamespaces](https://www.mediawiki.org/wiki/Extension:Approved_Revs#Setting_pages_as_approvable)) and not like $[wgNamespacesToBeSearchedDefault](https://www.mediawiki.org/wiki/Manual:$wgNamespacesToBeSearchedDefault) or $[wgNamespacesWithSubpages](https://www.mediawiki.org/wiki/Manual:$wgNamespacesWithSubpages).

**Comment by mwjames** [comment]
>  The problem ended up with the way I was setting $smwgNamespacesWithSemanticLinks. I assumed it worked like a some other namespace variables

I assumed the documentation [0] to be rather clear on the expected setting. If you think it needs a clarifying comment maybe adding a word or two can help others to avoid making the same assumption.

[0] https://www.semantic-mediawiki.org/wiki/Help:$smwgNamespacesWithSemanticLinks

**Comment by hexmode** [comment]
mwjames writes:

> I assumed the documentation [0] to be rather clear on the expected
> setting.

You're right.  It is clear.

I didn't look at the documentation for the variable because I didn't
think about the way namespace-related variables have this inconsistancy
in how they are set.

FWIW, I wish developers would standardize the way they use variables
like this and I think SMW is using the "right" way.  VE, for example,
recently changed from the wrong way with $wgVisualEditorNamespaces to
the right way with $wgVisualEditorAvailableNamespaces.
