### ISSUE TITLE
semanticmediawiki.org

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#1528]
http://semanticmediawiki.org serves stylesheets incorrectly. HTTPS works fine.

**Comment by kghbln** [comment]
Thanks for reporting. This one is actually still pointing to the old server so the DNS record needs to be rectified.

**Comment by JeroenDeDauw** [comment]
Anyone know who has control over that domain?

**Comment by JeroenDeDauw** [comment]
Perhaps we ought to list that at https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_services_accounts ? I just realized the new server and hetzner where missing and have added them. Sandbox still missing

**Comment by kghbln** [comment]
@JeroenDeDauw Well, if you have access to the Hetzner account you should be able to manipulate the DNS entries provided that the domain is hosted with them. Otherwise @mkroetzsch is the one in control here.

**Comment by mwjames** [comment]
If this is still an issue then it should be moved to https://github.com/SemanticMediaWiki/semantic-mediawiki.org.
