### ISSUE TITLE
"Linked Data Fragments" something for SMW (SPARQLStore) to consider?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1536]
I just came across some links (I neither browsed or read them) therefore dumping them for future reference.

- http://linkeddatafragments.org/
- https://www.w3.org/community/hydra/2014/06/20/hydra-welcomes-linked-data-fragments/
- http://ruben.verborgh.org/publications/vanherwegen_iswc_2015/

**Comment by JeroenDeDauw** [comment]
I've looked at that stuff a tiny bit some months ago and decided to not spend more time on it, as the thing seems to be quite local and far from any real adoption. Lots of marketing fluff tho
