### ISSUE TITLE
Simplify high complexity/risk methods

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1540]
Methods with CRAP > 100
## 

Reported by [0]:

![image](https://cloud.githubusercontent.com/assets/1245473/14908747/8705beca-0ddb-11e6-90ec-8b6f430de43a.png)

[0] https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticMediaWiki/code-structure/master?elementType=operation&orderField=crap&order=desc&changesExpanded=0

**Comment by mwjames** [comment]
In case someone wants to contribute to SMW then picking one of the outlined methods and try to turn them into a more sane (and tested) method would be highly appreciated.

**Comment by kghbln** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
