### ISSUE TITLE
SemanticMaps not displayed

### ISSUE THREAD

**Issue by gnikoloudis** [SemanticMediaWiki/SemanticMediaWiki#1547]
### Setup and configuration

- SMW version: 3.5
- MW version: 1.26.2
-PHP 	5.6.20-0+deb8u1 (apache2handler)
- MySQL 	5.5.47-0+deb8u1

### Issue
 HiI have installed the mediawiki, the SemanticMaps and all the dependencies but the extension is not working.For your reference I am sending you the below ink

http://mediawiki.convergence.solutions/index.php/Test_pageI do not get any error in the logs.The 

Maps extension is working without a problem. I would appreciate your help and any idea that you might have.
Thanks a lot
George

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

**Comment by kghbln** [comment]
This is actually not the correct spot for this issue thus I created one there: https://github.com/SemanticMediaWiki/SemanticMaps/issues/66
