### ISSUE TITLE
Travis Composer cache usage 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1557]
[0] states "Not only will open source projects get caching, private repositories running on GCE ...". 

@JeroenDeDauw not sure this `- $HOME/.composer/cache` is actually working since Travis outputs:

```
+composer install --prefer-source
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing wikimedia/composer-merge-plugin (v1.3.1)
    Cloning 0bdf8543d445ee067c9ba7d5d4a5dde70b9785f4
  - Installing composer/semver (1.4.0)
    Cloning 84c47f3d8901440403217afc120683c7385aecb8
  - Installing cssjanus/cssjanus (v1.1.2)
    Cloning b7efe237794856acec641cb82dcd6613c1aba2b4
  - Installing liuggio/statsd-php-client (v1.0.18)
    Cloning c42e6d6687b7b2d7683186ec7f4f03351cc3dbca
```

[0] https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Comment by JeroenDeDauw** [comment]
The cache does not work for git clones. So perhaps time to disable the "prefer source" option? This is the config we've been using for https://github.com/wmde/FundraisingFrontend since the beginning, and its not causing problems

**Comment by mwjames** [comment]
> ... So perhaps time to disable the "prefer source" option

Removed `prefer source`and it seems Travis fetches libs from cache.

```
 - Installing composer/installers (v1.0.25)
    Loading from cache
  - Installing onoi/event-dispatcher (1.0.0)
    Loading from cache
  - Installing onoi/cache (1.2.0)
    Loading from cache
  - Installing onoi/blob-store (1.2.0)
    Loading from cache
  - Installing data-values/interfaces (0.2.1)
    Loading from cache
```

**Comment by JeroenDeDauw** [comment]
\o/
