### ISSUE TITLE
1.25* Travis broken due to " wikimedia/composer-merge-plugin 1.0.0 -> satisfiable by wikimedia/composer-merge-plugin[v1.0.0]."

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1569]
### Setup and configuration

- SMW version: all
- MW version: 1.25*
- DB (MySQL etc.):

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
Problem 1
    - Installation request for wikimedia/composer-merge-plugin 1.0.0 -> satisfiable by wikimedia/composer-merge-plugin[v1.0.0].
    - wikimedia/composer-merge-plugin v1.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

**Comment by mwjames** [comment]
https://lists.wikimedia.org/pipermail/wikitech-l/2016-May/085588.html

https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/129616804

**Comment by mwjames** [comment]
@bd808 Any swift action on this issue would be highly appreciated.

**Comment by jamesmontalvo3** [comment]
@mwjames FYI patch submitted [0] but build failing for two items:

mediawiki-extensions-hhvm FAILURE in 51s
mediawiki-extensions-qunit FAILURE in 58s

[0] https://gerrit.wikimedia.org/r/#/c/288349/

**Comment by bd808** [comment]
Build failures for my REL1_25 patch [are resolved](https://gerrit.wikimedia.org/r/#/c/288349/2/). I forgot to add a matching mediawiki/vendor.git patch with the original submission.

**Comment by kghbln** [comment]
Affirmative. Now with 1.25.6 released things are [fluffy again](https://github.com/wikimedia/composer-merge-plugin/issues/119). Just switched all my affected wikis back to normal again.

**Comment by mwjames** [comment]
> Now with 1.25.6 released things are fluffy again. Just switched all my affected wikis back to normal again.  I guess this one may be closed.

Travis seems happy .
