### ISSUE TITLE
1.28.0-alpha / Change T135170 (PurgeAction) causes viewing disruption 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1585]
### Setup and configuration

- SMW version: all
- MW version: 1.28.0-alpha
- DB (MySQL etc.):

### Issue

During testing of \[0] (as it was small enough and relates to the whole TransactionProfiler topic, GET/POST updates) it emerged that it is visually impacting the viewing experience.

Now, every time one does a refresh, a  logged-in user is being redirected to a confirmation screen which causes a disruption in the reading flow. Prior to [0], a normal refresh (or purge) would have not caused a redirection for logged-in users.

![image](https://cloud.githubusercontent.com/assets/1245473/15240687/97c890a0-18eb-11e6-80bb-1b39258bd62a.png)

While the intention of [0] is understood, it is not clear whether the change is in favour of users that do not edit Wikipedia.

refs #1499

[0] https://phabricator.wikimedia.org/T135170, https://gerrit.wikimedia.org/r/#/c/288462/

**Comment by mwjames** [comment]
After several of hours trying working with the patch, I had to remove it as turned out to be utterly inconvenient.

**Comment by mwjames** [comment]
@kghbln @cicalese @hexmode I would appreciate some input on this from third-party wiki users.

If this is a none issue then I will close this one.

PS: [0] is considered not a real option as it would require develop time of volunteers to match the change.

PSS: [0] has mentioned a security aspect which is considered as well to be a really weak argument (we are talking about logged-in users, anonymous users are required to confirm even before [0]).

[0] https://phabricator.wikimedia.org/T135170#2310146

**Comment by kghbln** [comment]
> Now, every time one does a refresh, a logged-in user is being redirected to a confirmation screen which causes a disruption in the reading flow.

That's what anons have to do. So if I understand the issue correctly in future also logged in user have to do this? If this is the case than it is not just an third-party issue but also a wmf issue since it is imperative that this does not happen. I believe this is not even worth discussing, it is just ridiculous to even consider this.

**Comment by mwjames** [comment]
> That's what anons have to do. So if I understand the issue correctly in future also logged in user have to do this? 

Yes.

with GWicke clarifying:
> "The only difference is that all users will be shown a form with a submit button, while previously this was only done for anons / those without the specific rights.".

Feel free to comment on the phab issue.

>  I believe this is not even worth discussing, it is just ridiculous to even consider this.

Apparently it is.

**Comment by mwjames** [comment]
This was merged with [0], users who feel that this may impact them negatively should contact their local WMF developer office.

[0] https://github.com/wikimedia/mediawiki/commit/c2ce6a1b6085cf0cbf0fc2c3542fd36096bf2948

**Comment by kghbln** [comment]
@mwjames There was a [pull](https://github.com/Hutchy68/Purge/pull/8) for the Purge extension bringing back the old behaviour. If it is just about getting the same code into SMW I could probably try to immitate this pull.

**Comment by mwjames** [comment]
Hi,

> getting the same code into SMW I could probably try to immitate this pull.

+1.

There is one small glitch with the linked code "var postArgs = {
action: 'purgee', titles ..." because it should be `purge` not
`purgee`.

Cheers

**Comment by mwjames** [comment]
> SMW I could probably try to immitate this pull.

If you need a hand, just shout.

**Comment by kghbln** [comment]
> If you need a hand, just shout.

I will try to give it a shot after tea. You will see the disaster I believe ... ;)
