### ISSUE TITLE
Packagist with outdated dev-master reference

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1592]
This is the second time that [0] reports with an outdated reference (2016-05-15 14:32 UTC, f15052f3d).

[0] https://packagist.org/packages/mediawiki/semantic-media-wiki#dev-master

**Comment by JeroenDeDauw** [comment]
The service hook thing here on GH seems to be fine. Though I am guessing the problem lies there anyway

**Comment by mwjames** [comment]
Closing this for now.
