### ISSUE TITLE
Native displaytitle rendering has issues with ampersand character

### ISSUE THREAD

**Issue by Fannon** [SemanticMediaWiki/SemanticMediaWiki#1611]
### Setup and configuration
- SMW version: 2.4
- MW version: 1.25
- DB MySQL

### Issue
When using an Ampersand (&) as part of the Displaytitle, the resulting link title will contain the corresponding HTML entity `&amp;` 

### Steps to reproduce the observation:
* Create a new page "Web_-26_Wine", containing:
```
{{DISPLAYTITLE:Web & Wine}}
```
* Go To Browse Properties. The title will be: `Web &amp; Wine`
* Do an ASK Query: [[Web & Wine]] - the title will be `Web &amp; Wine`

This seems to be caused, because SMW created the display title itself. If I create a link to the page somewhere else, the Semantic Title Extension will rewrite the title in a correct way. `Web & Wine`

### Probably related:
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1410
* https://phabricator.wikimedia.org/T136092

**Comment by gesinn-it** [comment]
To reproduce, create a page "Web & Wine" including the ampersand, e.g. via Redlink. MW will automatically create the urlencoded (%26) page as mentioned by @Fannon .

**Comment by JeroenDeDauw** [comment]
Thank you both for reporting this issue

**Comment by mwjames** [comment]
Are we clear on this one?

**Comment by Fannon** [comment]
Yes, this issue should be resolved!

2016-05-26 12:36 GMT+02:00 mwjames <notifications@github.com>:
