### ISSUE TITLE
Localization and multilingual content

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1621]
In light of the upcoming 2.4 release and with multilingual wikis becoming (or maybe already are) a hot-button topic, I gave it quick and dirty write-up on how SMW can be used to manage content in different languages. I'll invite interested parties to review and improve [0] the text and/or in case something is unclear to post a question here.

While alternative property labels (those with a language tag) are not yet supported, I think we come a long way from being mono restricted and provide a lean and mean conceptional framework for users to create multilingual content.

[0] https://www.semantic-mediawiki.org/wiki/Localization_and_multilingual_content

refs #594

**Comment by nemobis** [comment]
Is there some part on which you most need/desire comments?

Do I understand correctly that in your opinion making SMW multilingual boils down to making links language-aware?
