### ISSUE TITLE
Running from a symbolically linked directory fails

### ISSUE THREAD

**Issue by agharbeia** [SemanticMediaWiki/SemanticMediaWiki#1623]
### Setup and configuration

- SMW version: 2.3.1
- MW version: 1.26.3
- DB (MySQL etc.): MariaDB

### Issue

When the SMW code directory is placed outside of `extensions` and symbolically linked to from within it, then running `maintenance/update.php` yields the following:
> PHP Warning:  Class 'SMW\Store' not found in /var/www/wikido.xyz/extensions/SemanticMediaWiki-2.3.1/SemanticMediaWiki.php on line 54
> PHP Warning:  Class 'SMW\MediaWiki\Jobs\UpdateJob' not found in /var/www/wikido.xyz/extensions/SemanticMediaWiki-2.3.1/SemanticMediaWiki.php on line 55
> PHP Warning:  Class 'SMW\MediaWiki\Jobs\RefreshJob' not found in /var/www/wikido.xyz/extensions/SemanticMediaWiki-2.3.1/SemanticMediaWiki.php on line 56
> PHP Warning:  Class 'SMW\SemanticData' not found in /var/www/wikido.xyz/extensions/SemanticMediaWiki-2.3.1/SemanticMediaWiki.php on line 57
> PHP Warning:  Class 'SMW\DIWikiPage' not found in /var/www/wikido.xyz/extensions/SemanticMediaWiki-2.3.1/SemanticMediaWiki.php on line 58
> PHP Warning:  Class 'SMW\DIProperty' not found in /var/www/wikido.xyz/extensions/SemanticMediaWiki-2.3.1/SemanticMediaWiki.php on line 59
and similar other errors pertaining to not being able to load classes.

The MW1.26.3 code is based at `/var/www/wikido.xyz/w`, which is itself a symbolic link to a `./mediawiki-1.26.3` in the same level.

Moving the SMW code directory to be physically under `extensions` solves the problem.
However this is the only extension I know of and use other than [Flow](https://phabricator.wikimedia.org/T134762) that exhibits the same issue. I run many other extensions via linking without any problems.

I think it has to do with paths are constructed|assumed to be in `SemanticMediaWiki-2.3.1/SemanticMediaWiki.php` and probably other files.

**Comment by agharbeia** [comment]
sorry. Something is wrong with my report. I need to reproduce and check.

**Comment by mwjames** [comment]
Some information about the use of symbolic links can be found at https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_symbolic_links.
