### ISSUE TITLE
Missing custom namespace in rebuildData.php

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#1647]
### Setup and configuration

- SMW version: 2.4 (master)
- MW version: 1.25.x
- DB (MySQL etc.): MySQL

### Issue
When executing rebuildData, I see the following output which seems to miss its "Organization" namespace:

`(818/127782)    Finished processing ID 2279* (:MyTestCompany_GmbH_-_Germany_-_Rehau)`

Is this a processing issue or just the console output?

**Comment by gesinn-it** [comment]
When executing:

`php rebuildData.php --query='[[Category:Organization]]' -v`

I get:

```
Running for storage: SMWSQLStore3

Refreshing selected pages (queries).
PHP Fatal error:  Call to a member function getPrefixedDBkey() on a non-object in /var/www/www.myserver.com/wiki-wiki_2016.9.0/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php on line 263
```

**Comment by mwjames** [comment]
> Is this a processing issue or just the console output?

I don't know.

> Finished processing ID 2279* (:MyTestCompany_GmbH_-_Germany_-_Rehau)

Well, have a look at [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Maintenance/DataRebuilder.php#L274

**Comment by mwjames** [comment]
> PHP Fatal error:  Call to a member function getPrefixedDBkey()

Different issue and needs to be tracked in another thread.

**Comment by gesinn-it** [comment]
@mwjames thanks for the hint. Mhh, according to [1] `getPrefixedDBkey` (called in `getHumanReadableTextFrom`) should return

> The prefixed title, with underscores and any interwiki and namespace prefixes 

I'll need to investigate, why this seems to be not the case in my wiki. Maybe an issue with the LocalSettings...

[1] https://doc.wikimedia.org/mediawiki-core/1.25.5/php/classTitle.html#a596f5441644c1412999001fc5ef01703

**Comment by gesinn-it** [comment]
In my LocalSettings I include configuration files like:

```
foreach (glob("includes/confs/10-*.php") as $filename) {
  require_once($filename);
}
```

which works fine but fails during rebuildData. Namespaces are also defined in one of these configuration files.

**Comment by mwjames** [comment]
> In my LocalSettings I include configuration files like:

Configuration isn't my "thing", so maybe @kghbln has some input.

**Comment by gesinn-it** [comment]
solved. I need to execute rebuildData from the "right" place like

`php extensions/SemanticMediaWiki/maintenance/rebuildData.php -v`

@mwjames thanks for superfast response :-)
