### ISSUE TITLE
Wildcards for page names

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#1652]
I need to search page names using wildcards, e.g. something like `[[File:Foo+]]` or `[[~File:Foo*.pdf]]`. I could easily add a special property `has page name` of type Text or File to [SemanticExtraSpecialProperties](/SemanticMediaWiki/SemanticExtraSpecialProperties), but how hard would it be to directly add this ability to SMW?

**Comment by mwjames** [comment]
> I need to search page names using wildcards, e.g. something like [[File:Foo+]]

This would entail a string match (pages are internally handled as s_id/o_id) therefore we would need to match against a string representation which is currently done by comparing against the `sortkey` field which does not contain any namespace prefixes. 

What about a conjunction such as `[[File:+]] [[~Foo*]]`?

> but how hard would it be to directly add this ability directly to SMW?

The `QueryParser` would need to translate  `[[File:Foo+]]` into something like `[[File:+]] [[~Foo*]]`.

**Comment by s7eph4n** [comment]
The number of namespaces is usually very limited, so the conjunction solution should not be a problem. (If I need to query more than one namespace I could easily put them in a subquery.)

**Comment by mwjames** [comment]
> What about a conjunction such as [[File:+]] [[~Foo*]]?

Expected to be solved and addressed with #1847.
