### ISSUE TITLE
Replace Image Upload Issue in NewRevisionFromEditComplete

### ISSUE THREAD

**Issue by robksawyer** [SemanticMediaWiki/SemanticMediaWiki#1653]
### Setup and configuration

- SMW version: Latest
- MW version: 1.26
- DB (MySQL etc.): Postgres

### Issue

The following gets thrown when I try to replace an image. Note: I'm using [LocalS3Repo](https://www.mediawiki.org/wiki/Extension:LocalS3Repo) for image uploads.
```
PHP Catchable fatal error:  Argument 1 passed to SMW\MediaWiki\EditInfoProvider::__construct() must be an instance of WikiPage, instance of ImagePage given, called in /app/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php on line 78 and defined in /app/extensions/SemanticMediaWiki/src/MediaWiki/EditInfoProvider.php on line 44 
```

**Comment by mwjames** [comment]
> I'm using LocalS3Repo for image uploads.

This relies on `$wgLocalFileRepo`.

> must be an instance of WikiPage, instance of ImagePage given, called i

Interesting, could you try changing `SMW\MediaWiki\EditInfoProvider` to

```
-use WikiPage;
+use Page;
 
 /**
  * @license GNU GPL v2+
  * @since 2.0
  *
@@ -39,11 +39,11 @@ class EditInfoProvider {
 	 *
 	 * @param WikiPage $wikiPage
 	 * @param Revision $revision
 	 * @param User|null $user
 	 */
-	public function __construct( WikiPage $wikiPage, Revision $revision, User $user = null ) {
+	public function __construct( Page $wikiPage, Revision $revision, User $user = null ) {
```

According to [0] "$article: the article edited. This is a WikiPage object as of MediaWiki 1.19, and an Article one before" therefore we rely on `WikiPage` as type check.

[0] https://www.mediawiki.org/wiki/Manual:Hooks/NewRevisionFromEditComplete

**Comment by mwjames** [comment]
I just saw that [0] calls `wfRunHooks( 'NewRevisionFromEditComplete', array( $article, $nullRevision, $latest, $user ) );` (which is not the standard invocation but invoked by the LocalS3Repo extension) where it creates a `$article = new ImagePage( $descTitle );` instance.

As cited above, when using standard hooks the call signature should comply with the outlined interface which in case of `NewRevisionFromEditComplete` is "... $article: the article edited. This is a WikiPage object ...".

`LocalFile` [1] shows how to use `$wikiPage = new WikiFilePage( $descTitle );`.

[0] https://github.com/robksawyer/preciousplasticwiki/blob/abc55d8d2a45cab538d7472163815ce4243598db/extensions/LocalS3Repo/LocalS3File.php#L1115

[1] https://github.com/wikimedia/mediawiki/blob/471ab05ea26bd1c844237bc752043536d9d2c284/includes/filerepo/file/LocalFile.php#L1359-L1402

**Comment by mwjames** [comment]
@kghbln FYI, If someone uses the LocalS3Repo extension and trips over the mentioned issue above then https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1653#issuecomment-225870615 is the cause.

**Comment by kghbln** [comment]
Yeah, this extension was abandoned quite some time ago. Now there are forks all across of different quality. I now marked this one visibly as "unmaintained" as well as adding an info [about this issue here](https://www.mediawiki.org/w/index.php?title=Extension%3ALocalS3Repo&type=revision&diff=2163197&oldid=2163196)

**Comment by robksawyer** [comment]
@mwjames First off, thanks for the help. I'm new to Mediawiki, so this was a good lead. I took a look at https://www.mediawiki.org/wiki/Manual:$wgLocalFileRepo and it seems that I'm using it properly. If you have a moment, please take a look below and let me know if you see any issues.

```
// $wgUploadDirectory is the directory in your bucket where the image directories and images will be stored.
// If "images" doesn't work for you, change it.
$wgUploadDirectory = getenv('UPLOAD_DIRECTORY');
$wgUploadS3Bucket = getenv('S3_BUCKET_NAME');
$wgUploadS3SSL = false; // true if SSL should be used
$wgPublicS3 = true; // true if public, false if authentication should be used

$wgS3BaseUrl = "http".($wgUploadS3SSL?"s":"")."://s3.amazonaws.com/$wgUploadS3Bucket";

//viewing needs a different url from uploading. Uploading doesnt work on the below url and viewing doesnt work on the above one.
$wgS3BaseUrlView = "http".($wgUploadS3SSL?"s":"")."://".$wgUploadS3Bucket.".s3.amazonaws.com";
$wgUploadBaseUrl = "$wgS3BaseUrlView/$wgUploadDirectory";

// leave $wgCloudFrontUrl blank to not render images from CloudFront
$wgCloudFrontUrl = "http".($wgUploadS3SSL?"s":"").'://'.getenv('CLOUDFRONT_SUBDOMAIN').'.cloudfront.net/';
$wgLocalFileRepo = array(
	'class' => 'LocalS3Repo',
	'name' => 's3',
	'directory' => $wgUploadDirectory,
	'url' => $wgUploadBaseUrl ? $wgUploadBaseUrl . $wgUploadPath : $wgUploadPath,
	'urlbase' => $wgS3BaseUrl ? $wgS3BaseUrl : "",
	'hashLevels' => $wgHashedUploadDirectory ? 2 : 0,
	'thumbScriptUrl' => $wgThumbnailScriptPath,
	'transformVia404' => !$wgGenerateThumbnailOnParse,
	'initialCapital' => $wgCapitalLinks,
	'deletedDir' => $wgUploadDirectory.'/deleted',
	'deletedHashLevels' => $wgFileStore['deleted']['hash'],
	'AWS_ACCESS_KEY' => getenv('AWS_ACCESS_KEY_ID'),
	'AWS_SECRET_KEY' => getenv('AWS_SECRET_KEY'),
	'AWS_S3_BUCKET' => $wgUploadS3Bucket,
	'AWS_S3_PUBLIC' => $wgPublicS3,
	'AWS_S3_SSL' => $wgUploadS3SSL,
	'cloudFrontUrl' => $wgCloudFrontUrl
);

$wgAllowImageMoving = true;

// s3 filesystem repo - end
```

**Comment by mwjames** [comment]
>  I'm new to Mediawiki, so this was a good lead

No worries.

> I took a look at https://www.mediawiki.org/wiki/Manual:$wgLocalFileRepo and it seems that I'm using it properly. If you have a moment, please take a look below and let me know if you see any issues.

The problem is not the configuration, it is the code within [0] which should use `WikiFilePage` instead of `ImagePage` as outlined in [1]. Otherwise those who rely on `NewRevisionFromEditComplete` (which is a global hook that is defined in various places [2]) with  a strict typing (like SMW) will fail because the `NewRevisionFromEditComplete` should return a WikiPage object as specified in [3].

[0] https://github.com/robksawyer/preciousplasticwiki/blob/abc55d8d2a45cab538d7472163815ce4243598db/extensions/LocalS3Repo/LocalS3File.php#L1115
[1] https://github.com/wikimedia/mediawiki/blob/471ab05ea26bd1c844237bc752043536d9d2c284/includes/filerepo/file/LocalFile.php#L1359-L1402
[2] https://github.com/wikimedia/mediawiki/search?utf8=%E2%9C%93&q=NewRevisionFromEditComplete
[3] https://www.mediawiki.org/wiki/Manual:Hooks/NewRevisionFromEditComplete

**Comment by mwjames** [comment]
> If you have a moment, please take a look below and let me know if you see any issues.

To be honest I've no real input on the LocalFileRepo/ForeignFileRepo settings but maybe @kghbln can help.

@robksawyer If you modify the LocalS3File extension you may provide it as fork, so others can use it as well given that "...Yeah, this extension was abandoned quite some time ago. Now there are forks all across of different quality..."

**Comment by robksawyer** [comment]
@mwjames Gotcha, yeah I'm trying to hack around on it. And I currently have it as a fork at https://github.com/robksawyer/LocalS3Repo. Tricky because I'm not familiar with all of the Mediawiki hooks. However, I just upgraded it to use the new 'wfLoadExtension' syntax, which'll hopefully be helpful.

**Comment by robksawyer** [comment]
Well I've managed to fix the main issue of replacing and updates images. (My initial one.) I'm not quite sure how stable my fork (https://github.com/robksawyer/LocalS3Repo) is though. I ended up doing quite a bit of refactoring to the code in order to get S3 from being a global variable. It just seemed wrong. **shrug** And I separated some classes from the original ones because they didn't need to be in the same file. Yuck.

You can find a working version is at http://www.preciousplasticwiki.com/. Also, I realize that this is probably not the issue to be commenting on because you folks have your own bugs to squash, but feel free to test the image uploading and such. I really would like the LocalS3Repo extension to be solid.

**Comment by kghbln** [comment]
@robksawyer You seem to know you way around programming. :) 

Since the original author obviously abandoned this extension you could probably take over maintaining it and pipe users to your repo as the canonical repo. Thus also the scary warnings I precautiously added to the extension's page could be removed.

**Comment by robksawyer** [comment]
@kghbln I've been doing it a while. 

I'd be open to taking it over – thanks for recommending. Just submitted a request at https://phabricator.wikimedia.org/T137991.
