### ISSUE TITLE
Remove usages of deprecated ResultPrinter::getParameters

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1654]
This method is deprecated since 1.8 yet still used by CategoryResultPrinter, EmbeddedResultPrinter and ListResultPrinter. Should not be hard to refactor

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/search?utf8=%E2%9C%93&q=getParameters

**Comment by JeroenDeDauw** [comment]
To clarrify: this task if about removing the usages of this function in SMW. Not removing the function itself. Of course removing such usages in Semantic Result Formats is also nice.

**Comment by kghbln** [comment]
Here we are: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/162
