### ISSUE TITLE
Wiki extremely slow

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1687]
I'm noticing that the SMW wiki is currently extremely slow. Takes over 10 seconds for something to load... not sure what is going on.

**Comment by kghbln** [comment]
I believe that this was a flooding attack, at least this is what happened to sandbox and the reason why I took it off-line during the night.

**Comment by kghbln** [comment]
Indeed this is a flooding attack by IP 62.210.78.104

**Comment by JeroenDeDauw** [comment]
> Indeed this is a flooding attack by IP 62.210.78.104.

![flood](https://cloud.githubusercontent.com/assets/146040/16303701/647ec0f2-3952-11e6-96d5-2d89ece3a597.gif)

> The server load is currently at 60 while an acceptable max is at about 3 for the two cores we have.

How do you figure 3 is the max, and how can I see the load when I ssh into the box?

**Comment by kghbln** [comment]
With acceptable max I mean a max which will go unnoticed by the users. It's a rough estimate which may vary, so 4 may still be cool too.

Just issue `top` when being on the sever which will also show you other data too.

**Comment by kghbln** [comment]
Things like this one should go to [this place](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues) in the future.

**Comment by kghbln** [comment]
Always trouble with the tribbels, however it seems to be over.

**Comment by mwjames** [comment]
> Always trouble with the tribbels, however it seems to be over.

Would it help to return a custom 404 page instead and let users know that servers are currently unavailable?

**Comment by kghbln** [comment]
> Would it help to return a custom 404 page instead and let users know that servers are currently unavailable?

I guess this would make sense in connection with Apache's "mod_reqtimeout". But also adding "mod_qos" and "mod_security" make sense in this connection though these are add-ons which I have to investigate further in the sense of how to handle these best.
