### ISSUE TITLE
Getting language fallback to work for special properties

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1691]
When creating a wiki with instance language "de-ch" the special properties are still generated in English. Namespaces and special pages are correctly shown in German. I was wondering if just adding a file like [SMW_LanguageDe_formal.php
](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/languages/SMW_LanguageDe_formal.php) for "de-ch" will help the cause. 

"de-formal" which also has a fallback to "de" is e.g. correctly generating the special properties in German. Since "de-ch" also falls back to "de" an extra file like the one linked may probably do the trick.

**Comment by mwjames** [comment]
This might be closed after you confirmed that #1848 solved this issue.

**Comment by kghbln** [comment]
> This might be closed after you confirmed that #1848 solved this issue.

Affirmative. Just tested on sandbox by setting it to "de-ch"! Great job!
