### ISSUE TITLE
Exception when running jobs

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/SemanticMediaWiki#1695]
### Setup and configuration

MediaWiki	1.26.3 (81ae24d)
PHP	5.5.37
MySQL	5.1.73
LuaSandbox	2.0.12
Lua	5.1.4
Semantic MediaWiki	2.4.0-rc1 (a0633e3)

### Issue

When running the runJobs.php maintenance script from the command line, I see the following exception:
```
2016-06-27 14:40:24 refreshLinks File:Regripper.gif pages=array(1) rootJobSignature=41c7da01e066899b651fb3b4c2629d1d2f7f1c4c rootJobTimestamp=20160622182135 masterPos= (id=117307,timestamp=20160627143841) t=468 error=RuntimeException: DB connection was already closed.
#0 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/db/Database.php(1027): DatabaseBase->assertOpen()
#1 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(247): DatabaseBase->query('CREATE TEMPORAR...', 'SMW\\SQLStore\\Qu...', false)
#2 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(189): SMW\MediaWiki\Database->query('CREATE TEMPORAR...', 'SMW\\SQLStore\\Qu...')
#3 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(123): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#4 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(112): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#5 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(221): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doExecuteSubqueryJoinDependenciesFor(13)
#6 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(402): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(Object(SMWQuery))
#7 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(392): SMWSQLStore3->fetchQueryResult(Object(SMWQuery))
#8 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(455): SMWSQLStore3->getQueryResult(Object(SMWQuery))
#9 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(194): SMWQueryProcessor::getResultFromQuery(Object(SMWQuery), Array, 2, 1)
#10 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(115): SMW\AskParserFunction->doFetchResultsForRawParameters(Array)
#11 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(277): SMW\AskParserFunction->parse(Array)
#12 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Object(Parser), '[[Category:Rela...', 'format=count')
#13 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Parser.php(3805): call_user_func_array(Object(Closure), Array)
#14 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Parser.php(3539): Parser->callParserFunction(Object(PPTemplateFrame_DOM), '#ask', Array)
#15 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Preprocessor_DOM.php(1177): Parser->braceSubstitution(Array, Object(PPTemplateFrame_DOM))
#16 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Preprocessor_DOM.php(1266): PPFrame_DOM->expand(Object(DOMNodeList), 0)
#17 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Parser.php(3681): PPFrame_DOM->expand(Object(PPNode_DOM))
#18 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Preprocessor_DOM.php(1177): Parser->braceSubstitution(Array, Object(PPFrame_DOM))
#19 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Parser.php(3358): PPFrame_DOM->expand(Object(PPNode_DOM), 0)
#20 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Parser.php(1244): Parser->replaceVariables('{{Tool\n|name=Re...')
#21 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/parser/Parser.php(444): Parser->internalParse('{{Tool\n|name=Re...')
#22 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/content/WikitextContent.php(331): Parser->parse('{{Tool\n|name=Re...', Object(Title), Object(ParserOptions), true, true, 35070)
#23 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Object(Title), 35070, Object(ParserOptions), false, Object(ParserOutput))
#24 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/jobqueue/jobs/RefreshLinksJob.php(183): AbstractContent->getParserOutput(Object(Title), 35070, Object(ParserOptions), false)
#25 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/jobqueue/jobs/RefreshLinksJob.php(99): RefreshLinksJob->runForTitle(Object(Title))
#26 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/jobqueue/JobRunner.php(180): RefreshLinksJob->run()
#27 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/maintenance/runJobs.php(85): JobRunner->run(Array)
#28 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/maintenance/doMaintenance.php(103): RunJobs->execute()
#29 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/maintenance/runJobs.php(103): require_once('/GESTALT/MEDIAW...')
#30 {main}
```

**Comment by mwjames** [comment]
> 2016-06-27 14:40:24 refreshLinks File:Regripper.gif pages=array(1) rootJobSignature=41c7da01e066899b651fb3b4c2629d1d2f7f1c4c rootJobTimestamp=20160622182135 masterPos= (id=117307,timestamp=20160627143841) t=468 error=RuntimeException: DB connection was already closed.

> #0 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/db/Database.php(1027): DatabaseBase->assertOpen()

> #22 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/content/WikitextContent.php(331): Parser->parse('{{Tool\n|name=Re...', Object(Title), Object(ParserOptions), true, true, 35070)
#23 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Object(Title), 35070, Object(ParserOptions), false, Object(ParserOutput))
#24 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/jobqueue/jobs/RefreshLinksJob.php(183): AbstractContent->getParserOutput(Object(Title), 35070, Object(ParserOptions), false)
#25 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/jobqueue/jobs/RefreshLinksJob.php(99): RefreshLinksJob->runForTitle(Object(Title))
#26 /GESTALT/MEDIAWIKI/mediawiki-REL1_26/includes/jobqueue/JobRunner.php(180): RefreshLinksJob->run()

Not sure was this means but SMW itself doesn't drop any DB connection.

**Comment by mwjames** [comment]
Maybe https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1606?

**Comment by cicalese** [comment]
I just tested on a new MW 1.27 installation. I see this issue with MW 1.26 and MW 1.27 and with MySQL 5.1.73 and MySQL 5.6.31.

MediaWiki 1.27.0 (a51acbb)
PHP	5.5.37
MySQL 5.6.31
LuaSandbox 2.0.12
Lua 5.1.4

**Comment by mwjames** [comment]
Well, I cannot reproduce this since this is environmental specific on how the JobQueue and `refreshLinks` are setup.

What I can see (while looking at the stack) is that `refreshLinks` on Page `File:Regripper.gif` (or maybe its another page) encounters a #ask query and this #ask query requires a `Database.php(247): DatabaseBase->query('CREATE TEMPORAR...', 'SMW\\SQLStore\\Qu...', false)` due to some `[[Category:Rela...` category query but when the `SQLStore` tries the create the TEMP table (for internal hierarchy computation) then the DB connection reference [0] has been closed which of course let the `DatabaseBase` raise an Exception about not being able to create a TEMP table.

As to why the DB connection was closed, I have no idea and the stack doesn't allow me to make any assumption let alone a conjecture about it. 

You should also investigate about what the `LoadBalancer` is reporting in the standard log file before and after the incident.

As suggested above, you may try disabling  #1606 which would force to keep the DBA_TRX but goes contrary to the observation made by Wikia.

If I have an exact description on how to reproduce the issue, I may spent some time on it in two weeks time but without a reproducible description chances are very slim for me hacking the MW JobQueue or `refreshLinks` any time soon.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/LazyDBConnectionProvider.php#L61

**Comment by cicalese** [comment]
I am working on coming up with a minimal repeatable test case for you. In the meantime, I have some additional information.

This is a transient problem, making it difficult to reproduce on demand. The observable symptom that we have been seeing in our wikis when this problem occurs running jobs is that the displaytitle page property does not get set properly for the page. However, the Display title of property of the page does get set to the correct value. The displaytitle page property gets saved to the database relatively late in the parsing process. My theory is that the exception causes the page parsing to be aborted midway through, but relatively late in the parsing process. We have also noticed that this problem (displaytitle not being set properly, but the Display title of property being set ok) occurs (transiently) when other MW maintenance scripts are run (e.g. edit.php). I *think* that the code being executed from a maintenance script is the key. Editing a page in the browser does not cause the problem for the page being edited, but if the edit causes another page to have a refresh job put on the job queue, that other page is in danger of having the displaytitle not set properly.

Further, I reverted to MW 1.25, and we see exactly the same problem. But, if I revert SMW from 2.4 RC1 to 2.3.1, all is good. So, I believe, based upon these observations, that this is a bug introduced in SMW 2.4 RC1.

I will continue to try to create a minimal reproducable test case for you.

**Comment by mwjames** [comment]
>  maintenance script is the key. Editing a page in the browser does not cause the problem for the page being edited, but if the edit causes another page to have a refresh job put on the job queue

I tried to run the `refreshLinks` and `runJobs` script in parallel on a different wiki (~4000 pages) to see if I'm able to find __at least one__ `Exception` but this was a shot in the dark. (The only additional extensions enabled are `ParserFunctions` and the one found in the https://github.com/SemanticMediaWiki repo)

```
Semantic MediaWiki	2.4.0-rc1 (83072ec)
MediaWiki	1.23.9
PHP	5.6.8 (apache2handler)
MySQL	5.6.24
```

All I get is (which goes on for an hour long log):

```
[Preprocessor] Loaded preprocessor XML from memcached (key mw-23-01:preprocess-xml:8de33c209452d9f29d659d05aba1d275:0)
Saved in parser cache with key mw-23-01:pcache:idhash:1735-0!*!0!default!*!en!*!* and timestamp 20160702005653 and revision id 3639
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
[runJobs] refreshLinks Template:InterlanguageLinksTemplate pages=array(1) rootJobSignature=9756816598d3f2413c6fd4657558f8da2c980146 rootJobTimestamp=20160702003422 masterPos= t=1342 good
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
[runJobs] refreshLinks Template:InterlanguageLinksTemplate pages=array(1) rootJobSignature=9756816598d3f2413c6fd4657558f8da2c980146 rootJobTimestamp=20160702003422 masterPos= STARTING
Title::getRestrictionTypes: applicable restrictions to [[Habitasse/55715812999f5/633]] are {edit,move}
[Preprocessor] Loaded preprocessor XML from memcached (key mw-23-01:preprocess-xml:8de33c209452d9f29d659d05aba1d275:0)
[Preprocessor] Loaded preprocessor XML from memcached (key mw-23-01:preprocess-xml:c45feb3b949b673ac92e807747419aa5:0)
```

@kghbln Any similar observations on your wikis running on 2.4?

> So, I believe, based upon these observations, that this is a bug introduced in SMW 2.4 RC1.

You could try a git-bisect [0] to narrow down the potential area.

[0] http://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination

**Comment by cicalese** [comment]
I found the problematic commit using git bisect. Thanks for the suggestion. Further, I have discovered that the problem only occurs when I use the --procs flag on runJobs.php. For the test, I used --procs=16.

2fc693ac6309c4fd5ec455e2cb39fdbcbff2f128 is the first bad commit
commit 2fc693ac6309c4fd5ec455e2cb39fdbcbff2f128
Author: mwjames <jamesin.hongkong.1@gmail.com>
Date:   Sun May 22 15:49:36 2016 +0200

    Add resetTransactionProfiler to DatabaseConnectionProvider, refs #1499

:040000 040000 1afbf8aa6e9c8a2044f0d29741882ee45692bef8 7b74952628ddd19d0a0650c0
357b0043b584d20e M      includes
:040000 040000 890fc816e93d50b08b1dd61ab7c6aeffffee0398 aba25fe634368b0b9f96b2f0
eb8360bceef8c595 M      src

**Comment by mwjames** [comment]
>  I have discovered that the problem only occurs when I use the --procs flag on runJobs.php. For the test, I used --procs=16

I cannot test this option since I'm on Windows which doesn't support the `ForkController` and for that matter ` --procs`.

> Add resetTransactionProfiler to DatabaseConnectionProvider, refs #1499

I do really wonder about this.The PR adds the `setTransactionProfiler` [0] which is only relevant for Logging.

If your hypothesis is correct then commenting line [1] should make the exception go away since the PR is about setting an empty `TransactionProfiler` (similar to [2]).

>  I reverted to MW 1.25, and we see exactly the same problem. But, if I revert SMW from 2.4 RC1 to 2.3.1, all is good. So, I believe, based upon these observations, that this is a bug introduced in SMW 2.4 RC1.

MW's `Database::setTransactionProfiler` was only added with 1.27 [3] \(and we check on its existence), so a correlation with MW 1.25 and the cited PR seems odd.

[0] https://github.com/wikimedia/mediawiki/blob/9e23ffa3951dd4222ae780bb512a6874c5fe4a83/includes/db/loadbalancer/LoadBalancer.php#L852
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/Setup.php#L121
[2] https://github.com/wikimedia/mediawiki/blob/2e0cf64db7ec7605229d69f857d29ebb09ba5037/includes/objectcache/SqlBagOStuff.php#L156-L159
[3 https://github.com/wikimedia/mediawiki/blob/master/includes/db/Database.php#L302-L307

**Comment by mwjames** [comment]
> Maybe #1606 

My favourite for the described observation is still #1606 therefore I'd recommend to temporary comment line [0] to see whether the `Exception` appears or not.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/QueryEngine.php#L163

**Comment by cicalese** [comment]
> My favourite for the described observation is still #1606 therefore I'd recommend to temporary comment line [0] to see whether the Exception appears or not.

The line in question was added in commit 8bc7ce6ffbf779d9dd7331d7d3ee36cdbd778b27, which was added 6 commits after the problematic commit, 2fc693ac6309c4fd5ec455e2cb39fdbcbff2f128. Therefore, the line isn't there to comment out. Also, the description of the issue mentions MySQL 5.6, but I'm running MySQL 5.5.48 - although it could still be an issue in that MySQL version, I suppose.

> If your hypothesis is correct then commenting line [1] should make the exception go away since the PR is about setting an empty TransactionProfiler (similar to [2]).

I will try that next.

> MW's Database::setTransactionProfiler was only added with 1.27 [3] (and we check on its existence), so a correlation with MW 1.25 and the cited PR seems odd.

The git bisect that found the issue was done with MW 1.26. If that function wasn't added until MW 1.27, then that is odd.

**Comment by cicalese** [comment]
> If your hypothesis is correct then commenting line [1] should make the exception go away since the PR is about setting an empty TransactionProfiler (similar to [2]).

Yes, commenting out that line makes the exception go away, and adding it back it makes it reappear.

**Comment by mwjames** [comment]
> Yes, commenting out that line makes the exception go away, and adding it back it makes it reappear.

Okay, this doesn't make any sense.We explicitly check for `setTransactionProfiler` and if it is not available (as for MW 1.26) then this is never going to be called.

Doing 

```php
//$queryengineConnectionProvider->resetTransactionProfiler();
```

```php
	function resetTransactionProfiler() {
		// MW 1.27
		if ( method_exists( $this->writeConnection(), 'setTransactionProfiler' ) ) {
			$this->writeConnection()->setTransactionProfiler( new \TransactionProfiler() );
		}
	}
```

Maybe the connection is established to early and causes an issue. Could try changing the following code [0] without commenting the suspected line.

```
@@ -16,10 +16,15 @@ class DatabaseConnectionProvider implements DBConnectionProvider {
 	 * @var Database
 	 */
 	private $connection = null;
 
 	/**
+	 * @var boolean
+	 */
+	private $resetTransactionProfiler = false;
+
+	/**
 	 * @see DBConnectionProvider::getConnection
 	 *
 	 * @since 2.1
 	 *
 	 * @return Database
@@ -37,11 +42,11 @@ class DatabaseConnectionProvider implements DBConnectionProvider {
 	 * @see #1499
 	 *
 	 * @since 2.4
 	 */
 	public function resetTransactionProfiler() {
-		$this->getConnection()->resetTransactionProfiler();
+		$this->resetTransactionProfiler = true;
 	}
 
 	/**
 	 * @see DBConnectionProvider::releaseConnection
 	 *
@@ -58,9 +63,14 @@ class DatabaseConnectionProvider implements DBConnectionProvider {
 			new LazyDBConnectionProvider( DB_MASTER )
 		);
 
 		$connection->setDBPrefix( $GLOBALS['wgDBprefix'] );
 
+		// #1695
+		if ( $this->resetTransactionProfiler ) {
+			$connection->resetTransactionProfiler();
+		}
+
 		return $connection;
 	}
 
 }
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/DatabaseConnectionProvider.php

**Comment by cicalese** [comment]
Yes, that fixes the problem as well. I added some debugging statements that show that it does enter  the resetTransactionProfiler() function in DatabaseConnectionProvider as well as the if statement that calls $connection->resetTransactionProfiler().

**Comment by mwjames** [comment]
> Yes, that fixes the problem as well. I added some debugging statements that show

Thanks.

It is still is somewhat unsatisfactory because the symptom (exception) and the cause (active DB connection) doesn't seems to correlate in a way I would have expected, especially under the condition that the issue only appears for "--procs flag on runJobs.php". I somehow can't shake the feeling that something on the MW side contains the real cause, since it shouldn't matter for us whether a connection is created early or not.

It is furthermore displeasing that we cannot test this (we don't know the real cause hence we just treated the symptom) as it happens beyond the SMW border, so there is no way to avoid something similar happening in future and us noticing it in advance.

**Comment by cicalese** [comment]
Thank you for the fix. I share your concern. We've been having similar transient errors after editing pages, but I have yet to be able to catch them to discover if they result in a similar stack trace to this runJobs error. I'm hoping this fix will help with that problem, too, but I worry that there may be an underlying MediaWiki issue. If I discover anything more, I will report back here.
