### ISSUE TITLE
 Undefined index: language in "DocumentationParserFunction.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1697]
### Setup and configuration

* MediaWiki 	1.25.6 (01b4001)
* PHP 	5.6.11-1ubuntu3.4 (apache2handler)
* MySQL 	5.6.30-0ubuntu0.15.10.1
* SMW  2.3.1 (f7543bc)

### Issue

When trying to access the docu page on [yahoomaps](https://www.semantic-mediawiki.org/wiki/Help:Ergebnisformat_yahoomaps) I get the following notice followed by a fatal:

```
Notice: Undefined index: language in /.../w/extensions/SemanticMediaWiki/includes/parserhooks/DocumentationParserFunction.php on line 40

Fatal error: Call to a member function getValue() on null in /.../w/extensions/SemanticMediaWiki/includes/parserhooks/DocumentationParserFunction.php on line 40
```
The cause is likely to be `{{#smwdoc:yahoomaps}}` which is no longer available. `#smwdoc` should not fatal if an invalid or obsolete string is added.

**Comment by kghbln** [comment]
Same on sandbox when trying to create a page with `{{#smwdoc:yahoomaps}}`.

**Comment by mwjames** [comment]
I'm guessing this to be #1328, no?

**Comment by kghbln** [comment]
> I'm guessing this to be #1328, no?

Indeed. I wonder why I did not see this issue when searching for this. Senior moments ...
