### ISSUE TITLE
Can we make `rebuildData` to operate faster?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1698]
For users with a page volume of 20k+(https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1690#issuecomment-228883175, https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1688#issue-161915395) doing a simple `rebuildData` run posses an inherent problem of time vs effort.

The bottleneck for the `rebuildData` script is not running an insert transaction to the DB backend (with either `SQLStore` or `SPARQLStore` active) and it is also not its own `InTextAnnotationParser` (which only takes a fraction of time to process a raw text to filter `[[ ... :: ...]]` annotations and transform them into `DataValues`) but the necessary reliance on the MediaWiki's `Parser` to:
- expand templates and provide access to annotation values in context of that target page that is embedding the template
- resolve the `Parser::Marker` that hides any #parser function (including `#subobject`, `#set`, and `#ask`) after the pre-processing
- process all registered `Parser` functions registered by other extensions (which may add or manipulate the text)

Most time is spend waiting on the `Parser::parse` to return a processed document in form of a `ParserOutput` instance which then can be "send" to the `StoreUpdater` to finalize the DB transaction.
## How about just using the raw text?

As outlined above, using `InTextAnnotationParser` alone is insufficient as this would only result in filtering `[[ ... :: ...]]` annotations, leaving things like `#subobject`, `#set`, and `#ask` hidden from the processing since those need to be parsed by the `Parser::parse` to allow for a correct content interpretation.

Parsing the raw text without involving the `Parser` would further dilute value annotations that are bound to the outcome of a MediaWiki specific context such as `Modification date`, `{{DEFAULTSORT:...}}`, `{{DISPLAYTITLE:...}}` or registered extension that add on-the-fly information during the parse process.
## What about the `--procs` option?

Apparently `runJobs` provides an option to run processes in parallel using the `ForkController` (which requires the PHP posix and pcntl extensions and are only available on Linux/Unix derivatives) and as commented in other threads (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1690#issuecomment-228896038 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/927#issuecomment-89262404) due to this limitation, I personally cannot provide any insides to this option as far as it concerns performance or execution.
## See also
- https://www.semantic-mediawiki.org/wiki/Help:RebuildData.php#Quick_and_slow_progress
- https://www.semantic-mediawiki.org/wiki/Incremental_and_continues_data_rebuild

**Comment by mwjames** [comment]
With an experimental `ShadowCache` (using `redis`) which runs asymmetrical to any DB transaction/read/write results are: 

```
1083 IDs refreshed.

Memory used: 17389776 (b: 11381480, a: 28771256) with a runtime of 47.85 sec
```

vs.

```
1083 IDs refreshed.

Memory used: 27963656 (b: 11381480, a: 39345136) with a runtime of 88.87 sec (1.48 min)
```

The simple idea behind the `ShadowCache` is that during each `updateStore` transaction (any modification is caught and overrides the existing data for the same hash) it makes a clone and stores it as serialized `SemanticData`.

```php
$shadowCache = $applicationFactory->newCacheFactory()->newShadowCache();
$shadowCache->addSemanticData( $this->semanticData );
$shadowCache->doUpdate();
```

Later during the `rebuildData`run it tries to retrieve its shadow and if successful uses it instead of making a full `Parser:parse`.

```php
$parserData = $this->applicationFactory->newParserData(
	$this->getTitle(),
	new \ParserOutput()
);

$hasCopy = $parserData->copyFromShadow();

if ( $hasCopy ) {
	return $this->updateStore( $parserData );
}
```

Depending on the size of the object, operational performance is expected to be similar to:

```
SMW\ShadowCache::doUpdate procTime (sec) 0.00098
SMW\ShadowCache::get procTime (sec) 0.00114

SMW\ShadowCache::get procTime (sec) 0.00108
SMW\ShadowCache::get procTime (sec) 0.00072
SMW\ShadowCache::doUpdate procTime (sec) 0.00026
```

## Notes

- Trying to pull out data from the `ParserCache` [0] before the actual `parse` doesn't really work (canonical cache key isn't what we are looking for)
- Trying to store a serialized `SemanticData` [1] as shadow to the `PageProps` isn't working as it can happen that the size (it so happens in one test case) of the object is larger as the permitted size and would result in an issue during the unseralization

[0] via `ParserCache::singleton()->getDirty` as shown in `RefreshLinksJob`
[1] via `ParserOutput::setProperty`

**Comment by Nikerabbit** [comment]
With regards to ForkController, it is going to be replaced with a new system: https://phabricator.wikimedia.org/T201970. It may or not have alternative implementation for Windows systems.

**Comment by kghbln** [comment]
> ## What about the `--procs` option?

This is just a remark. I did not use the procs option however I ran the e.g. following in parallel to speed up the data rebuild.
```
php extensions/SemanticMediaWiki/maintenance/rebuildData.php -v --skip-properties --with-maintenance-log --ignore-exceptions --exception-log="/logs/mediawiki/smw/" -s 0 -e 100000
```
```
php extensions/SemanticMediaWiki/maintenance/rebuildData.php -v --skip-properties --with-maintenance-log --ignore-exceptions --exception-log="/logs/mediawiki/smw/" -s 99000 -e 200000
```
Most of the time this works, however sometime the database throws an error:

```
[f4259a567f9bd192fd5c41bd] [no req]   Wikimedia\Rdbms\DBTransactionStateError from line 1423 of /app/includes/libs/rdbms/database/Database.php: Cannot execute query from SMW\SQLStore\Rebuilder\Rebuilder::getMaxId while transaction status is ERROR.
Backtrace:
#0 /app/includes/libs/rdbms/database/Database.php(1192): Wikimedia\Rdbms\Database->assertTransactionStatus(string, string)
#1 /app/includes/libs/rdbms/database/Database.php(1784): Wikimedia\Rdbms\Database->query(string, string)
#2 /app/includes/libs/rdbms/database/Database.php(1609): Wikimedia\Rdbms\Database->select(string, string, string, string, array, array)
#3 /app/includes/libs/rdbms/database/DBConnRef.php(53): Wikimedia\Rdbms\Database->selectField(string, string, string, string, array)
#4 /app/includes/libs/rdbms/database/DBConnRef.php(284): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#5 /app/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(625): Wikimedia\Rdbms\DBConnRef->selectField(string, string, string, string, array)
#6 /app/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(166): SMW\MediaWiki\Connection\Database->selectField(string, string, string, string)
#7 /app/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(353): SMW\SQLStore\Rebuilder\Rebuilder->getMaxId()
#8 /app/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(200): SMW\Maintenance\DataRebuilder->rebuild_all()
#9 /app/extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#10 /app/maintenance/doMaintenance.php(96): SMW\Maintenance\RebuildData->execute()
#11 /app/extensions/SemanticMediaWiki/maintenance/rebuildData.php(261): require_once(string)
#12 {main}
```
This happens about ten times on a wiki with about 500,000 entities and 5,000,000 objects. I guess this is the result of the two scripts trying to work on the same entity or object.

**Comment by mwjames** [comment]
> [f4259a567f9bd192fd5c41bd] [no req]
> Wikimedia\Rdbms\DBTransactionStateError from line 1423 of
> /app/includes/libs/rdbms/database/Database.php: Cannot execute query from
> SMW\SQLStore\Rebuilder\Rebuilder::getMaxId while transaction status is
> ERROR.

As for the error, see [0] for similar messages. To be honest I
wouldn't know why a simple `selectField` query (which the `getMaxId`
method [1] does) would cause (or fails with) a transaction error given
that it is a read request not a write one.

[0] https://phabricator.wikimedia.org/search/query/euTnBQwRFGQv/#R
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/45610438ca930101ed2a0c663752d6a7e829c492/src/SQLStore/Rebuilder/Rebuilder.php

**Comment by kghbln** [comment]
> To be honest I wouldn't know why a simple `selectField` query (which the `getMaxId`
method [1] does) would cause (or fails with) a transaction error given
that it is a read request not a write one.

This is probably a mystery since no apparent logic for the failure is visible, However it is happening in reality.
