### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class SemanticMediaWiki (Tarball)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1699]
[0] reported:

```
PHP Fatal error:  Cannot redeclare class SemanticMediaWiki in 
(...)/public_html/w/extensions/SemanticM 
ediaWiki/SemanticMediaWiki.php on line 42 

Judging from the comments in the file itself it sounds like this particular 
release is something I should install with composer. That's not available 
to me, I wasn't able to install it on my shared hosting account. Any way 
around this? A 2.4RC1 release that does not rely on composer? 
```

Verified using the zip from the tarball release from https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases/tag/2.4.0-RC1.

[0] http://wikimedia.7.x6.nabble.com/SMW-Erratic-behaviour-tp5065244p5065420.html

**Comment by mwjames** [comment]
The generated and deployed `autoload_real.php` in the vendor directory with the `require` (should be a `require_once`) clause causes the issue [0] when invoked in the `LocalSettings` with:

```
include_once "$IP/extensions/SemanticMediaWiki/SemanticMediaWiki.php";
enableSemantics( 'example.org' );
```
```
function composerRequire3741191bb7a7a054bcca8dd140f17d02($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
```
https://github.com/composer/composer/issues/5481

**Comment by JeroenDeDauw** [comment]
Don't put a class in the entry point files then. That goes against PSR-1 btw.

**Comment by JeroenDeDauw** [comment]
There is an actual infrastructure issue here: we should catch breakage in the tarballs... Long ago I added some to TravisCI to check, not sure what the state of that is tho: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/.travis.yml#L26

**Comment by mwjames** [comment]
> There is an actual infrastructure issue here: we should catch breakage in the tarballs... Long ago I added some to TravisCI to check, not sure what the state of that is tho:

`tarballs` queue are running, unfortunately this particular issue can not be caught (just tried it locally).

**Comment by JeroenDeDauw** [comment]
Why can this issue not be caught? The scenario that causes it can be reproduced on Travis no?

**Comment by HalliHalloSchatz** [comment]
I have the problem, when I use composer.json from MediaWiki and enable the composer.local.json and add in composer.local.json "mediawiki/semantic-media-wiki": "*".

After "composer update --no-dev" wiki running fine.
After a second "composer update --no-dev" I get a " PHP Fatal error:  Cannot redeclare..." error. I found that is a problem with the autoload generation of composer.

Reproduce:
- I remove the "mediawiki/semantic-media-wiki": "*" in composer.local.json
- composer update --no-dev and after that wiki works fine.
- add in composer.local.json "mediawiki/semantic-media-wiki": "*"
- composer update --no-dev and after that wiki works fine.
- composer dump-autoload -o --no-dev RESULT: wiki get the PHP FAtal error.

in the vendor/composer/autoload_classmap.php, autoload_files.php, autoload_psr4.php and autoload_static.php have the Semantic-media-wiki files double.

I think it is a problem that there is no "require one switch" for the "autoload" section.
"extensions/SemanticMediaWiki/composer.json" and "composer.json" with included "composer.local.json" have both a "autoload" section.

**Comment by mwjames** [comment]
There have been no recent reports on this issue and locally I cannot replicate to reported observation hence closing this one.
