### ISSUE TITLE
External identifier type

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1708]
Add a new type called `External identifier` (`[[Has type::External identifier]]`) to transform a string literal into an external resource uri.

The `External identifier` type will require a `External formatter uri` annotation in order for the property declaration to be valid, so that an input like `[[NDL ID::00564222]]` is referenced as `https://id.ndl.go.jp/auth/ndlna/00564222`. 

Other attributes such as `Allows pattern` or `Has uniqueness constraint` can be applied as well but are not required to form a valid property declaration.

![image](https://cloud.githubusercontent.com/assets/1245473/16670583/34acff48-449b-11e6-9584-5a634e083183.png)

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Type_External_identifier

**Comment by kghbln** [comment]
@mwjames I just created special property docu for [external identifier](https://www.semantic-mediawiki.org/wiki/Help:Special_property_External_identifier). Could you please set up an usage example for it on sandbox?

**Comment by mwjames** [comment]
>  I just created special property docu for external identifier. Could you please set up an usage example for it on sandbox?

You mean?

- https://sandbox.semantic-mediawiki.org/wiki/Attribut:EC_number
- https://sandbox.semantic-mediawiki.org/wiki/Attribut:P3520
- https://sandbox.semantic-mediawiki.org/wiki/Attribut:NDL_ID

**Comment by kghbln** [comment]
> You mean?

I was wondering how the special property comes into play: https://sandbox.semantic-mediawiki.org/wiki/Attribut:External_identifier

**Comment by mwjames** [comment]
> I was wondering how the special property comes into play: https://sandbox.semantic-mediawiki.org/wiki/Attribut:External_identifier

Actually there is no use case for this property alone since you always need a `External formatter URI`. I mostly added them so the there are reserved and cannot be occupied by a user defined property and hereby create confusion about the usage.

**Comment by kghbln** [comment]
Thanks for the insight. Documented on wiki!
