### ISSUE TITLE
Format "feed" - emit page title rather than page name

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1741]
When using e.g. `|format=feed |type=rss` in a query the actual name of the page is emitted which is indeed the expected behaviour. When using the [Semantic Title](https://www.mediawiki.org/wiki/Extension:Semantic_Title) extension it may be desirable not to get the page name but rather the page title set via that extension.

Is something like this doable from the technical point of view? If yes, support for this will be cool. @cicalese @mwjames 

Opening this question/feature request here since this format is provided by Semantic MediaWiki. It may very well be that also the Semantic Title extension needs to cater for something like this too.

**Comment by mwjames** [comment]
> When using e.g. |format=feed |type=rss in a query the actual name of the page is emitted which is indeed the expected behaviour.

I'm not sure I understand the full context but an individual `FeedItem` [0] uses `$subject->getPrefixedText()` as title value [1], so I suspect that this is the point where you expect some thing other than the `getPrefixedText`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/FeedResultPrinter.php#L283-L289

[1] https://github.com/wikimedia/mediawiki/blob/c42f06642091e1cb1142066b0a52a69a0c7e783d/includes/Feed.php#L56-L74

**Comment by kghbln** [comment]
It totally missed this. As far as I remember this is about pages like [this one](https://www.semantic-mediawiki.org/wiki/Help:Setting_values/Working_with_the_separator_parameter). The page name is "Help:Setting_values/Working_with_the_separator_parameter" while the page title is "Working with the #set "separator" parameter". The feed format emits the name and not the title.

**Comment by mwjames** [comment]
> page name is "Help:Setting_values/Working_with_the_separator_parameter" while the page title is "Working with the #set "separator" parameter".

Given that we are talking about the DISPLAYTITLE and on very fleeting look, the following should do what you are asking for:

```
@@ -278,12 +278,18 @@ final class FeedResultPrinter extends FileExportPrinter {
 
 	private function newFeedItem( $subject, $rowItems ) {
 		$wikiPage = WikiPage::newFromID( $subject->getArticleID() );
 
 		if ( $wikiPage !== null && $wikiPage->exists() ){
+
+			// #1741
+			$dataValue = DataValueFactory::getInstance()->newDataValueByItem(
+				DIWikipage::newFromTitle( $subject )
+			);
+
 			$feedItem = new FeedItem(
-				$subject->getPrefixedText(),
+				$dataValue->getPreferredCaption(),
 				$this->feedItemDescription( $rowItems, $this->getPageContent( $wikiPage ) ),
 				$subject->getFullURL(),
 				$wikiPage->getTimestamp(),
 				$wikiPage->getUserText(),
 				$this->feedItemComments()
```

PS: I haven't tested this extensively whether it collides with some other feed item assumptions or not.
