### ISSUE TITLE
PHP array to string conversion on wikitech in SMW 1.8.x

### ISSUE THREAD

**Issue by dereckson** [SemanticMediaWiki/SemanticMediaWiki#1743]
### Setup and configuration

- SMW version: 1.8
- MW version: last wmf branch
- DB (MySQL etc.): MySQL

### Issue

```
PHP Notice:  Array to string conversion in /srv/mediawiki/php-1.27.0-wmf.11/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php on line 384
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

Spotted in production on WMF cluster — reported downstream as https://phabricator.wikimedia.org/T124235

**Comment by kghbln** [comment]
Thanks for reporting. This indeed was an issue with SMW 1.8.x and MediaWiki 1.23+ but has been fixed in the meantime. I do not recall which version of SMW provided the fix exactly. The solution will be to upgrade to latest SMW since SMW 1.8.x was obsoleted in January 2014.

**Comment by mwjames** [comment]
> SMW version: 1.8

Please keep in mind that the mentioned version is no longer officially maintained or catered for.

> I do not recall which version of SMW provided the fix exactly.

Git is your friend and I'm guessing you are looking for https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/60002797.

> The solution will be to upgrade to latest SMW since SMW 1.8.x was obsoleted in January 2014.

wikitech ... not going to happen
