### ISSUE TITLE
Search by property not working correctly with "-" sign 

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticMediaWiki#1744]
### Setup and configuration
- SMW version: 2.5.0-alpha (c193d17) 02:54, 31 July 2016
- MW version: 1.27.0 (758cd9d) 22:24, 28 June 2016
- DB (MySQL etc.): 10.0.26-MariaDB-1~jessie
### Issue

Ii seems that **Search by property** breaks when a **"-"** sign is used (United States-International kerboard, ascii HEX D2) in a property name. The minus sign is followed by **D2** in the generated URL and this breaks the search. 

See: **http://sandbox.semantic-mediawiki.org/wiki/Attribut:Search_by_property_value_2** for example. 

For:  **[Search by property Test Page 1](http://sandbox.semantic-mediawiki.org/wiki/Search_by_property_Test_Page_1)** the following URL is generated: 

http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SearchByProperty/Search-20by-20property-20value-202/AA-2D10

The actual value that should be searched is: **AA-10**

We use property names with a minus sign since day one and searching on property names worked just fine in the past. I did noticed it not working a long time ago but never investigated any further. Because our users are getting smarter and smarter every day they are starting to notice :)

Is this a bug or some kind of regional setup thingy?

**Comment by jaideraf** [comment]
And the '&' character is showing '&amp;'. 
For example, the page 'Angels & demons' is showing 'Angels &amp; demons'.

**Comment by mwjames** [comment]
> See: http://sandbox.semantic-mediawiki.org/wiki/Attribut:Search_by_property_value_2 for example.

:+1: 

> http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version

:-1:

I'd appreciate if those where filled as mentioned in the template because in future the link will not reflect the setup as to when the issue was uncovered.

> Is this a bug or some kind of regional setup thingy?

It is an oversight (== currently untested).

> For example, the page 'Angels & demons' is showing 'Angels &amp; demons'.

Where? How? [0] doesn't mirror the observation. Again, I'd appreciate an example to avoid us (mostly me) second guess the issue.

[0] http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ASearchByProperty&property=Search+by+property+value+2&value=Angels+%26+demons

**Comment by jongfeli** [comment]
> I'd appreciate if those where filled as mentioned in the template because in future the link will not reflect the setup as to when the issue was uncovered.

Done, see on top.

> Where? How? [0] doesn't mirror the observation. Again, I'd appreciate an example to avoid us (mostly me) second guess the issue.

See: http://sandbox.semantic-mediawiki.org/wiki/Attribut:Search_by_property_value 

It seems that the "**&**" character is not causing any problems.

**Comment by jaideraf** [comment]
Sorry. 
## Setup and configuration

- SMW version: 2.5.0-alpha (0ab9ae7) 04:34, 1 August 2016
- MW version: 1.27.0 (758cd9d) 18:24, 28 June 2016
- PHP version: 7.0.9 (cgi-fcgi)
- DB (MySQL etc.): MySQL 5.5.32-cll-lve
- [Special:Version](http://wikincat.org/wiki/Special:Version)

I could not reproduce the error on sandbox. 
You can see what I mean [here](http://wikincat.org/w/index.php?title=Especial%3APesquisa+por+propriedade&property=Has+as+subject+the+topic&value=Fic%C3%A7%C3%A3o+americana&uselang=en) and [here](http://wikincat.org/wiki/Especial:Navegar/Obra:Angels_-26_demons?uselang=en).

Look, for instance, at "Has query", which is automaticaly created by SMW.

**Comment by mwjames** [comment]
> Done, see on top.

Thanks.

>Look, for instance, at "Has query", which is automaticaly created by SMW.
>UPDATE: I have created a new Angels & demons 2 page and everything worked well. 

I'm guessing this relates to #1611 since the instance is using the `DisplayTitle`. (PS: You could try replicating your page on the sandbox with the template `#invoke` call to confirm the correct behaviour).

**Comment by jaideraf** [comment]
> I'm guessing this relates to #1611 since the instance is using the DisplayTitle. (PS: You could try replicating your page on the sandbox with the template #invoke call to confirm the correct behaviour).

No need. I run `rebuildData.php` and everything works fine by now. So, the _"& case"_ is closed to me.

@jongfeli sorry for distracting your bug report. I thought the "& case" was related to your case. 
So, the real case here is the **"-"** sign in the **Search by property** special page.

**Comment by mwjames** [comment]
@jaideraf FYI. Just removed unrelated comments to stay clear on this issue.
@jongfeli I have fix somewhere but this issue ranks comparatively low as of now but is aimed to be solved with 2.5.
