### ISSUE TITLE
Using two consecutive colon inside images and links breaks them

### ISSUE THREAD

**Issue by ciencia** [SemanticMediaWiki/SemanticMediaWiki#1747]
### Setup and configuration

- SMW version: 2.4-alpha (2eea54d)
- MW version: 1.25.3

### Issue

Inside images, two consecutive colon characters inside the caption/title, alt text or link, cause the image to not display. A link is displayed instead, the target is the part after the consecutive colon until the pipe or end of link, and the displayed text is what's after that.

Apparently SMW is giving priority to the 2 consecutive colon, without checking first if they appear inside the link target.

[See examples here](https://wikiapiary.com/w/index.php?title=User:Ciencia_Al_Poder/SMW_consecutive_colons&oldid=2978826)

```
[[File:Example.png|alt=Semantic::Mediawiki|Caption]]
[[File:Example.png|link=Semantic::Mediawiki|Caption]]
[[File:Example.png|Semantic::Mediawiki|link=Wikiapiary]]
[[Mediawiki|Semantic::Mediawiki]]
```

To my understanding, SMW should only try to parse the link target, not the displayed text nor other attributes in case of embedded images.

**Comment by JeroenDeDauw** [comment]
Thanks for reporting.

Not sure what to label this. It's a known limitation that SMW has had since forever. Perhaps the inline property-value syntax parsing can be improved.

**Comment by mwjames** [comment]
Please see #1747. I'd like to see its behaviour confirmed by external testers prior merging.

**Comment by JeroenDeDauw** [comment]
I think you wanted to link https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1753 instead

**Comment by mwjames** [comment]
> Perhaps the inline property-value syntax parsing can be improved.

Done with #1753.
