### ISSUE TITLE
SMW_PageSchemas.php escaping

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#175]
This file appears to have some code that does not do proper escaping.

Spotted in https://gerrit.wikimedia.org/r/#/c/110632/1/includes/SMW_PageSchemas.php

**Comment by JeroenDeDauw** [comment]
@yaronkoren given that this is a security issue, it'd be really cool if you could fix it

**Comment by yaronkoren** [comment]
Oh, I must have missed this back a year ago. Well, if you're talking about that code that's generating the XML, I admit that it's not the prettiest code, but I don't think there's a security issue there. The XML being generated there is not getting displayed in the browser, but rather being saved to the page; anything that a user could enter via that interface, they could also put directly on the page via the regular edit tab.

**Comment by JeroenDeDauw** [comment]
Ok, that's good :)

Just a bug then

**Comment by mwjames** [comment]
> I don't think there's a security issue there.

I take the word and leave it at that.
