### ISSUE TITLE
Maintenance reminder on outdated entities and cache

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1754]
We may want to reiterate that maintenance work is important (now that 2.3/2.4 is highlighting those issues a bit more clearly [0, 1]).

![image](https://cloud.githubusercontent.com/assets/1245473/17330478/390dc8fc-58c7-11e6-864f-06ca723d7dbe.png)

![image](https://cloud.githubusercontent.com/assets/1245473/17330570/9618487e-58c7-11e6-888a-11288fe7a403.png)

[0] https://www.semantic-mediawiki.org/wiki/Help:Outdated_entities
[1] https://www.semantic-mediawiki.org/wiki/Help:Property_annotation_health

**Comment by mwjames** [comment]
@kghbln Maybe an email or tweet or?

**Comment by mwjames** [comment]
- If you just want to remove outdated entities then running `rebuildData.php --skip-properties -s 1 -e 1` should do the trick.
- Fixing improper value assignments is to be done manually, using `Property::Has processing error text` should allow for a quicker access to the issues at hand (http://sandbox.semantic-mediawiki.org/wiki/Attribut:Has_processing_error_text)

**Comment by kghbln** [comment]
While I am at it I should fluff the pages on the maintenance scripts prior to doing this.

**Comment by kghbln** [comment]
The ["rebuildData.php"](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AMaintenance_script_%22rebuildData.php%22&type=revision&diff=45259&oldid=44335) is at least complete now. Examples should probably go to separate pages but is will not be a holdup for this task.

**Comment by mwjames** [comment]
> Fixing improper value assignments is to be done manually, using Property::Has processing error text should allow for a quicker access

See #1779

**Comment by kghbln** [comment]
Now a "To do" for the documentation project.

Still need to update the maintenance script pages as well as extending the overview page with general recommendations.
