### ISSUE TITLE
Add `--quick` option to "rebuildFulltextSearchTable.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1763]
To be able to skip the five second countdown sequence it will be nice to have an additional ``--quick`` option to the "rebuildFulltextSearchTable.php" script.

**Comment by mwjames** [comment]
Done with #1769.

**Comment by kghbln** [comment]
> Done with #1769.

Awesome and [documented](https://www.semantic-mediawiki.org/wiki/Help:RebuildFulltextSearchTable.php) now!
