### ISSUE TITLE
Add `--with-maintenance-log` to to "rebuildFulltextSearchTable.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1764]
To be nice to be able to enable event logging with the additional ``--with-maintenance-log`` option to the "rebuildFulltextSearchTable.php" script like it is done for e.g. "rebuildData.php". See https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1361.

**Comment by kghbln** [comment]
@mwjames I think this may just be a matter of imitating https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/183c916cc6ce7c25015086e80d0811dfac3a2383 for "rebuildConceptCache.php"?

**Comment by mwjames** [comment]
> I think this may just be a matter of imitating 183c916 for "rebuildConceptCache.php"?

Exactly.

**Comment by kghbln** [comment]
This is [documented](https://www.semantic-mediawiki.org/w/index.php?title=Help:Maintenance_script_%22rebuildFulltextSearchTable.php%22&diff=next&oldid=45234).
