### ISSUE TITLE
Provide missing system message

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1766]
System message "smw-paramdesc-import-annotation" is missing. See the help page on the [template format](https://www.semantic-mediawiki.org/wiki/Help:Template_format#Parameters).

**Comment by mwjames** [comment]
This is most likely related to #1257.

A quick search on [0] returns tests in reference to #1257:
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/ByJsonScript/Fixtures/p-0406.json
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/ByJsonScript/Fixtures/p-0701.json
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/ByJsonScript/Fixtures/p-0205.json

[0] https://www.semantic-mediawiki.org/wiki/Help:Integration_tests

**Comment by kghbln** [comment]
@mwjames Thanks for pointing me to the rationale of this message.

As possible texts the following two come to my mind:

1. "Allow to copy annotation data in to the template during parsing"
2. "The annotated data should be copied into the template during parsing"

For consistency with the other system messages the second suggestion should be used. 

This is just to make sure that I am not far off.

**Comment by mwjames** [comment]
> "The annotated data should be copied into the template during parsing"

How about "Additional annotated data are to be copied during the parsing of a subject"? where "are to be copied" is referring to a likelihood, possibility, or in the event of.

The imperative of "Should" is rather strong and while the IEEE Standards Style Manual clarifies that "The word should is used to indicate that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others ..." [0], you could use "shall" instead to lessen the connotation.

But what do I know, @kghbln as master (or shall I say overlord) of the [SMW-universe](https://en.wikipedia.org/wiki/Masters_of_the_Universe_(film)) do as you see fit.

[0] http://grouper.ieee.org/groups/1057/2000Style.pdf

**Comment by kghbln** [comment]
> How about "Additional annotated data are to be copied during the parsing of a subject"? 

I just wanted to make sure that we have the best fit here so here we are :) I was not aware of the wider implications of "should" ;) - the master has spoken!
