### ISSUE TITLE
Support unique constraint for property

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMediaWiki#178]
It would be really useful if Semantic MediaWiki could support a unique constraint for a property. I would suggest a property setting like:

[[Has constraint::unique]]

The effect seems obvious, to require the property be unique.

I currently attack this problem in the Template and do an ask query for a property with count and if the value is not zero, I often display a warning about a duplicate being detected and might also put it in a category. It would be interesting if violating a constraint could do something like add to a category, but just enforcing the uniqueness would be a great start. 

It's possible this has all been discussed but figured I would throw it out there for consideration. 

Other constraints could be envisioned using this syntax.

**Comment by mwjames** [comment]
Done with #1463.
