### ISSUE TITLE
SMW and HHVM RepoAuthoritative bytecode 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1790]
It seems MediaWiki is experimenting with HHVM RepoAuthoritative bytecode [0] and I think #1784 was added [1] because of it. Anyone with a running HHVM instance and some time may want to follow-up on this.

This task is non-actionable for the core team and only serves as anchor point for possible future changes.

[0] https://gerrit.wikimedia.org/r/#/c/304768/
[1] https://gerrit.wikimedia.org/r/#/c/304772/

**Comment by Nikerabbit** [comment]
I might do experiments on some of my hhvm + smw installs (but don't count on it) and will report here the results.

**Comment by mwjames** [comment]
At this point (after a year), I cannot see any actionable tasks that are required by the project on behalf of "HHVM RepoAuthoritative bytecode" therefore I'm inclined to close this issue.
