### ISSUE TITLE
rebuildData, exceptions, and third-party extensions 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1797]
[0] is a bleak example of what happens when a third-party extension causes a disruption of the `rebuildData.php` run.

As noted in [1], `rebuildData.php` is running through the complete processing chain (including hooks registered by other third-party extensions) to ensure that the final data input for the `StorageEngine` takes into account manipulated data set forth by other extensions (including semantic and non-semantic extension).

If it happens that during a `rebuildData.php` run an error or exception is encountered then under normal circumstances the process is stopped because the situation was unanticipated. While this can can be important for the maintainer of the extension, it can be disrupting for the users and for SMW as data consumer.

In case the stack trace [2] indicates that SMW is not directly at fault (in the example `SmoothGallery` is hinted to have an issue), it is best to use option `--ignore-exceptions` introduced with #1327 to allow `rebuildData.php` to finish its processing. Yet, as the name `--ignore-exceptions` suggests it only ignores the exception during the run and mostly likely will resurface if not remedied in due time.

```
..[d94c685d] [no req]   MWException from line 6371 of /data/www/html/test3/includes/parser/Parser.php: Parser state cleared while parsing. Did you call Parser::parse recursively?

Backtrace:
#0 /data/www/html/test3/includes/parser/Parser.php(402): Parser->lock()
#1 /data/www/html/test3/includes/content/WikitextContent.php(333): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#2 /data/www/html/test3/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#3 /data/www/html/test3/includes/filerepo/file/LocalFile.php(1747): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#4 /data/www/html/test3/extensions/SmoothGallery/SmoothGalleryParser.php(238): LocalFile->getDescriptionText()
#5 /data/www/html/test3/extensions/SmoothGallery/SmoothGalleryParser.php(164): SmoothGalleryParser->parseImage(Title, Parser, array, string)
#6 /data/www/html/test3/extensions/SmoothGallery/SmoothGalleryParser.php(104): SmoothGalleryParser->parseGallery(string, Parser)
#7 /data/www/html/test3/extensions/SmoothGallery/SmoothGalleryParser.php(11): SmoothGalleryParser->parseGalleries(string, Parser)
#8 /data/www/html/test3/extensions/SmoothGallery/SmoothGallery.php(115): SmoothGalleryParser->__construct(string, array, Parser, boolean)
#9 /data/www/html/test3/extensions/SmoothGallery/SmoothGallery.php(104): initSmoothGallery(string, array, Parser)
#10 [internal function]: initSmoothGalleryPF(Parser, string, string, string, string, string, string, string, string)
#11 /data/www/html/test3/includes/parser/Parser.php(3771): call_user_func_array(string, array)
#12 /data/www/html/test3/includes/parser/Parser.php(3505): Parser->callParserFunction(PPFrame_DOM, string, array)
#13 /data/www/html/test3/includes/parser/Preprocessor_DOM.php(1169): Parser->braceSubstitution(array, PPFrame_DOM)
#14 /data/www/html/test3/includes/parser/Parser.php(3322): PPFrame_DOM->expand(PPNode_DOM, integer)
#15 /data/www/html/test3/includes/parser/Parser.php(1231): Parser->replaceVariables(string)
#16 /data/www/html/test3/includes/parser/Parser.php(434): Parser->internalParse(string)
#17 /data/www/html/test3/extensions/SemanticMediaWiki/includes/ContentParser.php(202): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#18 /data/www/html/test3/extensions/SemanticMediaWiki/includes/ContentParser.php(147): SMW\ContentParser->fetchFromParser()
#19 /data/www/html/test3/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(136): SMW\ContentParser->parse()
#20 /data/www/html/test3/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(119): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#21 /data/www/html/test3/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(88): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#22 /data/www/html/test3/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#23 /data/www/html/test3/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#24 /data/www/html/test3/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#25 /data/www/html/test3/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#26 /data/www/html/test3/extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#27 /data/www/html/test3/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#28 /data/www/html/test3/extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#29 /data/www/html/test3/extensions/SemanticMediaWiki/maintenance/SMW_refreshData.php(9): require_once(string)
#30 {main}
```

[0] https://www.mediawiki.org/w/index.php?title=Topic:T9thuj95ek3jby4i&topic_showPostId=t9thujetmp1godxe#flow-post-t9thujetmp1godxe
[1] https://www.semantic-mediawiki.org/w/index.php?title=Help:Maintenance_script_%22rebuildData.php%22&redirect=no#Quick_and_slow_progress
[2] https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
> Yet, as the name --ignore-exceptions suggests it only ignores the exception during the run and mostly likely will resurface if not remedied in due time.

That is indeed true but given the users experience in the particular case it did not seem preferable to open up another front. Yes, the best way will be to also use the `--exception-log` option.

**Comment by mwjames** [comment]
I just thought to write some additional lines for future reference instead of saying "isn't our fault" in order for users to understand the situation a bit better.

**Comment by kghbln** [comment]
> I just thought to write some additional lines for future reference instead of saying "isn't our fault" in order for users to understand the situation a bit better.

A good idea and no objections at all. It is indeed good to have a wrap-up like this one. Probably this should go to the wiki, too.
