### ISSUE TITLE
Memory usage, static arrays, and InMemoryPoolCache

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1799]
The attached output should make it immediately visible as to why we cache intermediary results and have replaced most of the static arrays in SMW with `InMemoryPoolCache`.

Any invoked `InMemoryPoolCache` member is limited to a max amount of elements (with the least recently used [0] being evicted once the max is reached, leaving only the "most" valuable elements to be available in cache) to provide a ceiling on its assigned memory.

Growing memory usage (or for that matter missed garbage collection of unused object references) is certainly an issue for a long running `rebuildData.php` but I'd expect `Parser:parse` to take most of the memory foothold.

```
200 IDs refreshed.

Memory used: 43645600 (b: 12548192, a: 56193792) with a runtime of 249.79 sec (2.16 min)

- message.cache
  - inserts 1100
  - deletes 0
  - max 1000
  - count 147
  - hits 79611
  - misses 147
  - hit ratio 0.9982, miss ratio 0.0018
- property.spec.lookup.cache
  - inserts 204
  - deletes 0
  - max 500
  - count 204
  - hits 82176
  - misses 0
  - hit ratio 0.9975, miss ratio 0.0025
- sil.pagecontentlanguage
  - inserts 375
  - deletes 0
  - max 500
  - count 375
  - hits 89000
  - misses 375
  - hit ratio 0.9958, miss ratio 0.0042
- sql.store.id.cache
  - inserts 12264
  - deletes 0
  - max 500
  - count 500
  - hits 13
  - misses 24
  - hit ratio 0.3514, miss ratio 0.6486
- sql.store.id.dataitem.finder
  - inserts 10325
  - deletes 0
  - max 500
  - count 500
  - hits 220
  - misses 0
  - hit ratio 0.0209, miss ratio 0.9791
- sql.store.redirect.infostore
  - inserts 308
  - deletes 2
  - max 500
  - count 305
  - hits 8617
  - misses 0
  - hit ratio 0.9655, miss ratio 0.0345
- store.redirectTarget.lookup
  - inserts 5
  - deletes 1
  - max 500
  - count 4
  - hits 2290
  - misses 36700
  - hit ratio 0.0587, miss ratio 0.9413
```

[0] https://en.wikipedia.org/wiki/Cache_algorithms#LRU

**Comment by JeroenDeDauw** [comment]
> - sql.store.id.dataitem.finder
  - inserts 10325
  - deletes 0
  - max 500
  - count 500
  - hits 220
  - misses 0
  - hit ratio 0.0209, miss ratio 0.9791

That is a rather abysmal hit ratio. Worth having the cache if that is actually what happens in typical production situations?

**Comment by mwjames** [comment]
> That is a rather abysmal hit ratio. Worth having the cache if that is actually what happens in typical production situations?

I don't remember (or at least I don't have any numbers right now) but I think that those numbers improve to a better end when used with the `SPARQLStore`.
