### ISSUE TITLE
Concept definition to support printout statement

### ISSUE THREAD

**Issue by kriegfrj** [SemanticMediaWiki/SemanticMediaWiki#1815]
Dear all,

I have been using SMW internally for about 6 months now for a system that has evolved into a full-on client management database. One feature that I have been thinking would really help is the flexibility to be able to define a concept by other than the subject of the query by specifying a printout statement. 

To explain in more detail, a use case might help., I have a class of pages that define client sessions, and another class defining the clients. I want to define a concept that lists all clients who are involved in sessions of a certain type. There are too many sessions to try and use the `<q>` syntax in the query filter. On the other hand, I can (using an `#ask` query) easily find all sessions of a certain type and use a printout to list their participants. If I could somehow take this "column" from the query output and use it as the concept definition, it would achieve what I want. I'm thinking that a syntax something like the following would work:

```
{{#concept: [[Category:Session]] [[Has session type::Dance class]]
|?Has participant
|Concept listing all clients who are participants of the Dance class.}}
```

The `#concept` parser function would recognise the printout and use it as the definition of the concept members rather than the query result's subject (ie, a list of participants rather than a list of sessions). Obviously this would only make sense if the printout referred to a property of type Page - otherwise the parser function should generate an error, or perhaps a warning while defaulting back to defining the concept by the query result subject.

I apologise if this feature has already been added or if this is a duplicate issue - I searched the open/closed issues and couldn't find anything that looked like it. I'm not sure how easy it is, but if I get a chance (and no one else beats me to it) I might have a look at it.

**Comment by D-Groenewegen** [comment]
I don't think that such a feature is necessary, or at least not in the case
of the example you bring up. It can be rephrased with an inverse query as
follows:

{{#concept: [[-Has participant::<q>[[Category:Session]] [[Has session
type::Dance class]]</q>]]
|Concept listing all clients who are participants of the Dance class.
}}

Best,
Dennsi

2016-08-30 5:49 GMT+02:00 Fr Jeremy Krieg <notifications@github.com>:

**Comment by kriegfrj** [comment]
Thanks for your comment Dennsi. I'll try and have a bit more of a look into your suggestion. I have tried it with simpler cases and it works fine, but I seem to remember cases where I thought the inverse trick wouldn't work. I had assumed that in cases where the inner query `<q>[[Category:Session]] [[Has session type::Dance class]]</q>` returns a lot of records then the outer query would fail the query term complexity test (there are tens of thousands of sessions).

One complicating factor in my use case is that, the `Has participant` property is actually of type record rather than a plain page reference, and (to my knowledge) inverse properties do not work with these. Maybe it would be more fruitful to come up with a syntax that supports some kind of inverse for record types.

**Comment by mwjames** [comment]
I haven't read the issue in its entirety but just to clarify:

> One feature that I have been thinking would really help is the flexibility to be able to define a concept by other than the subject of the query by specifying a printout statement.

By its very nature, a concept is a collection of pre-computed subjects as a result of a specific conditional criteria (or in short a rule-base classification schema). [0]

> The #concept parser function would recognise the printout and use it as the definition of the concept members rather than the query result's subject (ie, a list of participants rather than a list of sessions). 

` #concept` is responsible for handling a condition not a derived statement from a matched condition (as in case of a printout).

> and (to my knowledge) inverse properties do not work with these. Maybe it would be more fruitful to come up with a syntax that supports some kind of inverse for record types.

Would you mind providing an example where this observation is evident (preferably on the sandbox)? [1] works as expected unless we are talking about a different syntax.

[0] https://www.semantic-mediawiki.org/wiki/Help:Concepts
[1] http://sandbox.semantic-mediawiki.org/wiki/Issue/1815_%28Inverse_record_query%29

**Comment by kriegfrj** [comment]
For the record, I tried the inverse property trick and it seemed to work. I think my concerns about the inner query being too large may have proven unfounded.

When I get a chance I'll do the sandbox example to demonstrate the issue with inverse properties and record types.

**Comment by mwjames** [comment]
I think I answered the question as to what is supported and what not.
