### ISSUE TITLE
#ask sorting via defaultsort when disabled

### ISSUE THREAD

**Issue by Betacommand** [SemanticMediaWiki/SemanticMediaWiki#1823]
### Setup and configuration

- SMW version: 2.4.1
- MW version: 1.27.1 (17e44c4)
- DB (MySQL etc.):PHP 	7.0.8-0ubuntu0.16.04.2 (apache2handler)
MariaDB 	10.0.25-MariaDB-0ubuntu0.16.04.1

### Issue
After upgrading to 2.4 SMW uses defaultsort values for #ask display values and sorting. This doesnt work for my wiki, and broke a few things. Following the mailing list and instructions at https://www.semantic-mediawiki.org/wiki/Help:Special_property_Display_title_of I set:

$GLOBALS['smwgDVFeatures'] = $GLOBALS['smwgDVFeatures'] & ~SMW_DV_WPV_DTITLE;

this corrected the result display format, However the sorting of #ask is still based off displaytitle and not pagetitle.

I have tried rebuildall.php (core script) rebuilddata.php with and without the -f flag. however default results for #ask still use DISPLAYTITLE values.

**Comment by mwjames** [comment]
> this corrected the result display format, However the sorting of #ask is still based off displaytitle and not pagetitle.

To clarify, DEFAULSORT (DISPLAYTITLE has been disabled per comment above) is not used or set for those entities?

**Comment by Betacommand** [comment]
double checking, I do see a _Display title of_  property which shouldnt be there

**Comment by mwjames** [comment]
> double checking, I do see a Display title of property which shouldnt be there

I had a quick look at it and expect #1829 to solve this given the note about a persistent `Display title of` property.

**Comment by Betacommand** [comment]
Any idea how to get this besides waiting for 2.5 to release?

**Comment by mwjames** [comment]
> Any idea how to get this besides waiting for 2.5 to release?

I pushed #1829 to the 2.4.x branch as well which comes down to someone making a point release (I won't have time for this).

- https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.4.x?expand=1
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1751

**Comment by JeroenDeDauw** [comment]
You can `2.4.x@dev` in `composer.json` if it's on that branch
