### ISSUE TITLE
Count result format limit

### ISSUE THREAD

**Issue by lalquier** [SemanticMediaWiki/SemanticMediaWiki#1833]
### Setup and configuration
- SMW version: 2.4.1
- MW version: 1.27.1
- DB (MySQL etc.): 5.6.27-log
### Issue

Since I upgraded to SMW 2.4.1, I have a query using the 'count' result format returning a maximum value of 10000.

According to this page - https://www.semantic-mediawiki.org/wiki/Help:Count_format - the 'count' result format is not subject to the $smwgQMaxInlineLimit variable. 

However, I got the right value for the query after bumping up the variable for MaxInlineLimit.

Should the wiki page be amended or is this a bug I should report on github?

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

1- Generate a query that is likely to return a large number of pages

For example: 

> {{#ask:[[Creation date::+]]|format=count}} pages with dates

2- Set the  $smwgQMaxInlineLimit variable in LocalSettings.php to a value lower than the result of the query above.

For example, if the query returns a count of 1200 pages, setting the variable to 1000 with make the query return a value of 1001.

**Comment by mwjames** [comment]
The SELECT code that executes the count [0] has not been altered since 1.9 [1].

You have a `$sql_options = array( 'LIMIT' => $query->getLimit() + 1, 'OFFSET' => $query->getOffset() );` which may limit the SELECT but that has been part of the query at least since [1].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/QueryEngine.php#L358-L377
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.9.2/includes/storage/SQLStore/SMW_SQLStore3_Queries.php#L428-L437

**Comment by mwjames** [comment]
As for the `$query->getLimit()`, it remained unchanged [0, 1].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/includes/query/SMW_Query.php#L231-L247
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.9.2/includes/query/SMW_Query.php#L162-L178

**Comment by mwjames** [comment]
@kghbln Any change in behaviour you might have observed in regards to count?

**Comment by lalquier** [comment]
I upgraded from SMW 1.16 (!)
The query returned a count regardless of the default value of $smwgQMaxInlineLimit, as indicated on the Help:Count_format

My question is really 'There is a contradiction between what that Help page says and how queries behave'. If this is an expected behavior (if nobody reported it after all this time, maybe it is), then maybe the Help page should be updated.

**Comment by kghbln** [comment]
> I upgraded from SMW 1.16 (!)

Probably 1.6 is meant here. Admittedly I never had more than 10,000 results which needed to be counted so I cannot tell. Still this format adhering to the mentioned setting would be consistent to other formats I guess. And yes, if the docu is wrong it should be amended. Would still like @JeroenDeDauw to have a peep at this for an opinion.

**Comment by lalquier** [comment]
@kghbln - I did mean 1.16 :) (no comment)

@JeroenDeDauw already commented on the mailing list that this looks like a bug by the way.

**Comment by mwjames** [comment]
> @JeroenDeDauw already commented on the mailing list that this looks like a bug by the way.

To extended on https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1833#issuecomment-245820098, the `limit` as option is not applied to a SQL query that only returns one row \[0], so the limit has no effect on the count query.

I'm not sure what you are observing but whether limit (through `smwgQMaxInlineLimit` or `smwgQMaxLimit`) is set or not to a specific level it does not alter the return result of a count query.

Doing `{{#ask: [[Modification date::+]] |format=count |limit=10 }}` or `{{#ask: [[Modification date::+]] |format=count }}` with `smwgQMaxInlineLimit =1` and `smwgQMaxLimit=1` will not change the result of a count query (both return the same result).

Unless evidence is provided that the behaviour is not as described (with an example that would illustrate the difference in behaviour), I cannot provide further assistance.

[0] http://stackoverflow.com/questions/17020842/mysql-count-with-limit

**Comment by jongfeli** [comment]
When  `$smwgQMaxInlineLimit=500` we get the following result on our wiki:

No limit
-`{{#ask:[[Modification date::<14 September 2012]]|format=count}}` : 174
-`{{#ask:[[Modification date::<14 September 2013]]|format=count}}` : 3896
-`{{#ask:[[Modification date::<14 September 2014]]|format=count}}` : 6962
-`{{#ask:[[Modification date::<14 September 2015]]|format=count}}` : 13066
-`{{#ask:[[Modification date::<14 September 2016]]|format=count}}` : 32825

With limit
-`{{#ask:[[Modification date::<14 September 2012]]|format=count|limit=10}}` : 174
-`{{#ask:[[Modification date::<14 September 2013]]|format=count|limit=10}}` : 3896
-`{{#ask:[[Modification date::<14 September 2014]]|format=count|limit=10}}` : 6962
-`{{#ask:[[Modification date::<14 September 2015]]|format=count|limit=10}}` : 13066
-`{{#ask:[[Modification date::<14 September 2016]]|format=count|limit=10}}` : 32825

**Comment by kghbln** [comment]
> When $smwgQMaxInlineLimit=500 we get the following result on our wiki (SMW sandbox does not have enough pages):

So it appears to be working and the docu is correct.

> However, format=sum also returns just one value

"count" is actually not a math format. Need to change this on the wiki. We should not mix other formats into this thread. If there is an issue with "sum" it should be reported separately.

**Comment by mwjames** [comment]
Given the arguments above, closing this as a non-issue.
