### ISSUE TITLE
Use WikiPage::prepareContentForEdit() instead of the deprecated WikiPage::prepareTextForEdit() 

### ISSUE THREAD

**Issue by brightbyte** [SemanticMediaWiki/SemanticMediaWiki#1850]
Please use `WikiPage::prepareContentForEdit()` instead of `WikiPage::prepareTextForEdit()`. 

`prepareTextForEdit()` has been deprecated since MW 1.21. We are preparing for removing it, see <https://phabricator.wikimedia.org/T146170> and for context <https://phabricator.wikimedia.org/T145728>.

**Comment by kghbln** [comment]
Thanks for reporting this!

**Comment by JeroenDeDauw** [comment]
We can actually do this now since we're finally dropping 1.19 compat in the next rel.

**Comment by brightbyte** [comment]
Are you also dropping 1.20 support?

If you need to keep backwards compat, it would be ok to work around this using if ( method_exists( ... ) ). Then there is no hard dependency on the old method, so we can finally drop it from core. Not pretty of course, but would solve the problem we currently have with this in core.

Please also check if SMW is using any other deprecated methods mentioned in <https://phabricator.wikimedia.org/T145728>.

**Comment by mwjames** [comment]
> If you need to keep backwards compat, it would be ok to work around this using if ( method_exists( ... ) ). 

To my knowledge, we already doing this in:

- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/d6011d08f1cccc857432488b38c56374a7d8762c/src/MediaWiki/EditInfoProvider.php#L73-L78
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/9ee1dcca85d1d0e19f00a309f6db50e023094ba2/tests/phpunit/Utils/Page/PageEditor.php#L59-L104

> Please also check if SMW is using any other deprecated methods mentioned in https://phabricator.wikimedia.org/T145728.

Personally, I cannot provide assistance to non related SMW tasks therefore I would expect to receive a list with possible necessary changes that would greatly reduce my effort to follow WMF infused changes.
