### ISSUE TITLE
@@@ syntax to generate a property link

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1855]
Creating a property link (as to be used in infoboxes or by templates) within a wiki-text requires some additional work and even though it can be done it will not allow to take advantage of auto-property descriptions (displayed as tooltip etc.) or in future to change to a preferred label (based on the user language).

To generate a property link within a text or template, the special syntax `[[Foo::@@@]]` is introduced, where `@@@` will signal to the `InTextAnnotationParser` to handle it as non-value annotation and instead output a property link as seen in the examples.

Going with the special syntax seems more appropriate (and is less work) than introducing yet another parser function.

## Examples

![image](https://cloud.githubusercontent.com/assets/1245473/18569275/e576eb12-7ba1-11e6-96c2-caef7a89ad18.png)

![image](https://cloud.githubusercontent.com/assets/1245473/18569314/1d94f552-7ba2-11e6-85af-dd3ab3186427.png)

![image](https://cloud.githubusercontent.com/assets/1245473/18569445/e6aa40b4-7ba2-11e6-9176-ea35448f84e6.png)

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
* https://www.semantic-mediawiki.org/wiki/Help:Property_links

**Comment by krabina** [comment]
> Placeholder: https://www.semantic-mediawiki.org/wiki/Help:Property_links

I added some more wikidoku for this....

**Comment by krabina** [comment]
This is a great feature, but there are several use cases where in you wiki you don't want user to visit property pages. 

So my question is if it would be possible to use the feature of having the preferred property label and property description showing up in a tooltip, but without the possibility to actualle click on it an got to the property page?
Could be achieved by something like [[Foo::@@@|@@@]].

The workaround is to use something like
`{{#show:Property:Foo|?has preferred property label|+lang={{USERLANGUAGECODE}}}}` 
to display the correct name of the poperty and then also do the tooltip in a similar way which is a lot of coding and querying in templates...

**Comment by mwjames** [comment]
> So my question is if it would be possible to use the feature of having the
> preferred property label and property description showing up in a tooltip,
> but without the possibility to actualle click on it an got to the property
> page?
> Could be achieved by something like [[Foo::@@@|@@@]].

If you create a feature request for `[[Foo::@@@|@@@]]` (where `|@@@]]`
indicates a no link) then I may have a look at it.

**Comment by krabina** [comment]
documented here: https://www.semantic-mediawiki.org/wiki/Help:Property_links
