### ISSUE TITLE
Query with Like operator with incomplete result set

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1882]
### Setup and configuration

this happens on http://www.semantic-mediawiki.org 
### Issue

According to 
https://www.semantic-mediawiki.org/wiki/Help:Selecting_pages_1.5

the like operator ~ together with wildcards should be able to select from string type properties those pages that have the property with a comparable string. 

Thus the property 
https://www.semantic-mediawiki.org/w/index.php?title=Property:Attendee_events&limit=500&offset=0

should be selectable as in
https://www.semantic-mediawiki.org/wiki/A_list_of_attendees_to_SMWCon_Fall_2016

with the query:

```
[[Attendee events::~*Fall 2016*]]
```

Unfortunately a few entries are not selected if the pages are not modified:
- https://www.semantic-mediawiki.org/wiki/User:Toniher
- https://www.semantic-mediawiki.org/wiki/User:Nicolas_NALLET
- https://www.semantic-mediawiki.org/wiki/User:Jeroen_De_Dauw
- ...

e.g.  the String  SMWCon Fall 2016 has to be put at the beginning of "events=" to work.

To find out what is wrong I created:
- http://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/1882

And as it looks the "*" operator which should _match any sequence of characters_ does not match an empty string. This is strange and IMHO should be fixed.

What is strange is that the _Fall 2016_ query works for Toniher's event string:
SMWCon Fall 2010, SMWCon Fall 2011, SMWCon Fall 2012, SMWCon Fall 2013, SMWCon Fall 2014, SMWCon Fall 2015, SMWCon Fall 2016,

but does not work for https://www.semantic-mediawiki.org/wiki/A_list_of_attendees_to_SMWCon_Fall_2016

**Comment by mwjames** [comment]
The `Like` operator is be definition applied to a reduced blob element [0], for longer texts the full-text #1481 is expected to provided the necessary infrastructure and result matches.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/EntityStore/DIHandlers/DIBlobHandler.php#L22-L40
