### ISSUE TITLE
Remove alias of datatype "String" to datatype "Text"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1893]
I think the 3.0 release offers the chance to also remove the alias of datatype "String" to datatype "Text". This was documented on the help page to [datatype "Text"](https://www.semantic-mediawiki.org/w/index.php?title=Help:Type_Text&diff=26446&oldid=17725) since February 2013 (Compatibility note) and just [made more precise](https://www.semantic-mediawiki.org/w/index.php?title=Help:Type_Text&diff=46707&oldid=46703) as of October 2015.

@mwjames @JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
Mhh idk. Presumably it's basically free on the software side to have this alias. So then the remaining question is if it is really better for the user to have it or not. Do we really want to force wikis from 2012 to migrate this? That's a cost. For benefit I can think of "more consistency" and "less confusion", though both seems a lot less significant in this case. Then again, I'm not an active user, so what do I know...

**Comment by kghbln** [comment]
Actually the painful part of the conversion was adapting my forms to the change. I for example had to manually change all my former fields for string properties (90% of all fields) to explicitly use input type "text" to avoid text areas. That was about 99% of the work since this affected masses of fields. I believe all wikis have done this work already if they updated since. Doing a search and replace in namespace "Property" for "String" and change it to "Text" was a thing of a couple of minutes.

I however do not how much code this currently involves. If it is just a couple of lines when we have probably something for SMW 4.0 I guess.

**Comment by JeroenDeDauw** [comment]
> I believe all wikis have done this work already if they updated since. 

Why do you think that? Not everyone is as determined to fluff things as you :)

**Comment by kghbln** [comment]
> Why do you think that?

Forms just appear totally borked if you do not do this after an upgrade. Indeed the part on changing String to Text on property pages is however debatable.

> Not everyone is as determined to fluff things as you :)

Still I am under the strong impression of losing ground in this respect as you were able to experience at SMWCon past. :(

**Comment by JeroenDeDauw** [comment]
Not knowing how this evil slide engine works is quite different than not being dedicated to the fluff!

**Comment by mwjames** [comment]
> I think the 3.0 release offers the chance to also remove the alias of datatype "String" to datatype "Text".

I think some wikis use `String` as type and given that the cost [0] of keeping it as synonym is more or less zero compared to a possible disruption for users who rely on that type, I'd rather keep it as it is with the documentation clearly recommending to use of `Text` as literal while keeping silent on the `String` usage.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=_str

**Comment by mwjames** [comment]
> Still I am under the strong impression of losing ground in this respect

Something you care to share?

**Comment by kghbln** [comment]
> Something you care to share?

I messed up the talk with Jeroen. Though I went through it heaps of times I failed to get in the correct order of the slides. You will see the vid. :(

**Comment by kghbln** [comment]
> I'd rather keep it as it is with the documentation clearly recommending to use ...

Fair enough. This is indeed not to much to schlepp in future releases. Since there are clear notes on this topic on the wiki ...

**Comment by alex-mashin** [comment]
Don't.

**Comment by kghbln** [comment]
> Don't.

This was indeed the conclusion.
