### ISSUE TITLE
Add MediaWikiLogger (PSR\LoggerInterface)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1903]
It would be great if someone could create a `MediaWikiLogger` (implementing the `PSR\LoggerInterface`) to encapsulate `wfDebugLog('smw' ... )` calls in SMW.

`wfDebugLog` provides an invaluable source when trying to debug some issues or monitor new features and since we want to reduce the technical MW debt, having such a class that provides that service would be surely helpful.

If a class is constructed using the `ApplicationFactory` or via the DI container then `PSR\LoggerAwareInterface` can be be used to inject the Logger and for all other cases we would rely on a static access point until such service can be injected.

https://github.com/php-fig/log

**Comment by legoktm** [comment]
See also https://www.mediawiki.org/wiki/Structured_logging

**Comment by mwjames** [comment]
Part of #1251 added `ApplicationFactory::getInstance()->getMediaWikiLogger()` to return a `LoggerInterface` instance.
