### ISSUE TITLE
Case insensitive LIKE matching for _wpg type entities (MySQL)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1912]
Some notes to a question [0] that came up on the mailing-list:

> As far as I know it was not possible in SMW 2.3, did it change or maybe
> there is some kind of workaround exists?

To support case insensitive matching for `_wpg` type entities one could make the following changes to the SMW 2.5 table settings (this is only tested in connection with MySQL, I'm not sure this works with  SQLite or Postgres).

`!~/~` queries will use the `smw_sortkey` field of the ID_TABLE (`smw_object_ids`) to match expressions, yet exact queries like `[[Has title::CAseInSensitiveSearch]]` will be matched against the `smw_title` field of the same table which remains case sensitive and therefore only returns exact matches to the `CAseInSensitiveSearch` value.

I'm not sure about the performance implications by changing from `VARBINARY(255)` to `VARCHAR(255) CHARSET utf8 COLLATE utf8_general_ci` and therefore hasn't been considered to be the default setting. Also, SQLite and Postgres would require similar table settings to ensure feature parity.
## Example

```
Has title -> Page type

[[Has title::CAseInSensitiveSearch]]

{{#ask: [[Has title::~CASEIN*]]
 |?Has title
}}

{{#ask: [[Has title::~casein*]]
 |?Has title
}}
```
## SQLStore

`SMWSQLStore3SetupHandlers`

```
-                   'smw_sortkey' => $dbtypes['t']  . ' NOT NULL',
+                   'smw_sortkey' => $dbtypes['s'] . ' NOT NULL',
```

`MySQLTableBuilder`

```
            case 'sort':
-           return 'VARCHAR(255)';
+           return 'VARCHAR(255) CHARSET utf8 COLLATE utf8_general_ci';
```
## SPARQLStore

`ValueDescriptionInterpreter`

```
-           return new FilterCondition( "$comparator( ?$joinVariable, \"$pattern\", \"s\")", array() );
+           return new FilterCondition( "$comparator( ?$joinVariable, \"$pattern\", \"i\")", array() );
        }

        if ( $dataItem instanceof DIUri ) {
            return new FilterCondition( "$comparator( str( ?$joinVariable ), \"$pattern\", \"i\")", array() );
        }
@@ -248,11 +248,11 @@ class ValueDescriptionInterpreter implements DescriptionInterpreter {
        $filterVariable = $this->compoundConditionBuilder->getNextVariable();

        $condition->condition = "?$joinVariable " . $skeyExpElement->getQName(). " ?$filterVariable .\n";
        $condition->matchElement = "?$joinVariable";

-       $filterCondition = new FilterCondition( "$comparator( ?$filterVariable, \"$pattern\", \"s\")", array() );
+       $filterCondition = new FilterCondition( "$comparator( ?$filterVariable, \"$pattern\", \"i\")", array() );

```
## Notes
#1481 introduces support for case insensitive text value matching by relying on a dedicated MySQL/SQLite full-text index (no support for Postgres is planned but if someone wants to make a code contribution, please go ahead).

[0] http://wikimedia.7.x6.nabble.com/SMW-case-insensitive-comparison-td5068163.html

**Comment by mwjames** [comment]
> SMWSQLStore3SetupHandlers

`SMWSQLStore3SetupHandlers` was made obsolete in 2.5 and has been replaced by the `TableSchemaManager` (#1940, #1961).

`FieldType::TYPE_CHAR_NOCASE` has been added (but isn't used by default) and would allow for a DB field to be case insensitive.

`TableSchemaManager`:

```
-		$table->addColumn( 'smw_sortkey', array( FieldType::FIELD_TITLE, 'NOT NULL' ) );
+		$table->addColumn( 'smw_sortkey', array( FieldType::TYPE_CHAR_NOCASE ) );
```
  
- MySQL `VARCHAR(255) CHARSET utf8 COLLATE utf8_general_ci`,
- SQLite `VARCHAR(255) NOT NULL COLLATE NOCASE`, and
- Postgres `citext NOT NULL`

For Postgres,`citext` type [0] is used and for SQLite, see [1].

[0] http://nandovieira.com/using-insensitive-case-columns-in-postgresql-with-citext
[1] https://sqlite.org/datatype3.html#collation

**Comment by mwjames** [comment]
See #2499.

**Comment by kghbln** [comment]
@mwjames blob is used for datatypes text and page and uri for datatypes url and annotation uri? Is something missing?

**Comment by kghbln** [comment]
Hmm, page is not blob I gues.

**Comment by mwjames** [comment]
To clarify, the ..._NOCASE flag relates to page, blob, and uri types
while the ..._LONG is only concerned with the length of blob and uri
fields to avoid changing the length of matchable entities in the
smw_object_ids table since the max length of any wiki page title is
255.

On the 300 char restriction, I already explained on one of tickets
that it has its origin in the limitation of creating an index in
MySQL/MariaDB.

**Comment by mwjames** [comment]
It goes without saying that any change to `$smwgFieldTypeFeatures`
requires to run `setupStore.php` or an equivalent script to execute
modifications of field types on selected tables.

**Comment by kghbln** [comment]
> To clarify, the ..._NOCASE flag relates to page, blob, and uri types while the ..._LONG is only concerned with the length of blob and uri fields to avoid changing the length of matchable entities in the smw_object_ids table since the max length of any wiki page title is 255.

Thanks. What I am still not sure about is which datatypes are meant if you refer to blob. So text is blob, but what about e.g. code....

Indeed the LONG search was already working up to 255 chars in the past for pages. Used as a very dirty trick to break out of the 72 chars limit.

> On the 300 char restriction, I already explained on one of tickets that it has its origin in the limitation of creating an index in MySQL/MariaDB.

Understood this and already documented accordingly.

**Comment by mwjames** [comment]
> Thanks. What I am still not sure about is which datatypes are meant if you
> refer to blob. So text is blob, but what about e.g. code....

When referring to a string or text type in a technical space (as here
on github) we do refer to them as blob [0] since our table definition
declares them as blob item/type.

> Indeed the LONG search was already working up to 255 chars in the past for
> pages. Used as a very dirty trick to break out of the 72 chars limit.

This is because the field `smw_sortkey` (which since we have
`smw_sort` isn't actually a sort field but a search field but that's a
different discussion) in `smw_object_ids` is stored unaltered and is
used to match page titles on a proximity search (~/!~) while text/uri
types are stored differently.

[0] https://stackoverflow.com/questions/11624807/what-are-the-differences-between-the-blob-and-text-datatypes-in-mysql
