### ISSUE TITLE
Add unit tests to DataItemHandlers

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1913]
#1909 moved the `DataItemHandler` classes to a new place and those listed below require rudimentary test coverage.

⇢ A   DIBlobHandler 
⇢ A   DIBooleanHandler 
⇢ A   DIConceptHandler 
⇢ A   DIGeoCoordinateHandler 
⇢ A   DINumberHandler 
⇢ A   DITimeHandler 
⇢ A   DIUriHandler 

I extended the existing unit test for `DIWikiPageHandler`.

**Comment by kghbln** [comment]
This can probably be moved to the 3.0 milestone?

**Comment by mwjames** [comment]
> ⇢ A DIBlobHandler
> ⇢ A DIUriHandler

Added in #2499.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
