### ISSUE TITLE
Translation of namespaces

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1918]
### Setup and configuration

- Semantic MediaWiki	2.5.0-alpha (69f35c7) 23:36, 9. Okt. 2016
- MediaWiki 	1.27.1 (a52d35d) 06:46, 23. Aug. 2016
- PHP 	5.6.26-0+deb8u1 (apache2handler)
- MariaDB 	10.0.27-MariaDB-1~jessie

### Issue

Currently translations are provided via  "SemanticMediaWiki/i18n/extra/SemanticMediaWiki.namespace.php" and via the json files in " SemanticMediaWiki/i18n/extra/". I am not sure which file is being checked by the software first.

Following up to https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1896#discussion_r82473062 I suggest dropping the "SemanticMediaWiki.namespace.php" file and use the json-files until there is support for this via twn sometime in the presumably rather distant future.

**Comment by mwjames** [comment]
>  I suggest dropping the "SemanticMediaWiki.namespace.php" file and use the json-files until there is support for this via twn sometime in the presumably rather distant future.

I'll leave the judgement to you. On the issue on dropping and for encouragement :+1: .
