### ISSUE TITLE
Import tools override existing data?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1920]
Referring to [0]:

> Recurring question/concern at #SMWCon: various import tools override existing data. Hint hint @SemanticMW devs? :)

I'm a bit unclear about this use case since I would expect that any data imported has a corresponding wiki page and in cases where this is not the case then how do you import those data into SMW in the first place?

Under the assumption that one uses the MW/SMW API to write some data (without a page that hosts the "raw" text), I would also expect that the IW (interwiki) field is set to those entities in order for them to be distinguished from each other (which also avoids conflicting names in case a subject with the same title already exists).

Clarifying comments and use case are welcome.

[0] https://twitter.com/JeroenDeDauw/status/781848638502862848

**Comment by mwjames** [comment]
This issue has an unclear premise and narrative therefore closing it on lacking information and use cases.

**Comment by kghbln** [comment]
Well this is strongly connected to page revisions. If you add a new revision the old one gets overwritten. So a tool e.g. importing content should/could look for existing and only selectively adding or removing information. This is not really SMW specific.
