### ISSUE TITLE
Joining the team of testers

### ISSUE THREAD

**Issue by DengroWikibase** [SemanticMediaWiki/SemanticMediaWiki#1928]
### Issue

A comment - from a potential new tester - about the file CONTRIBUTING.md, where anyone who is prepared to contribute to SMW by joining the testers is encouraged to visit this url:

https://github.com/orgs/SemanticMediaWiki/teams/testers

Unfortunately, this appears to be the wrong URL at the moment or the intended page was not created at all.

**Comment by JeroenDeDauw** [comment]
I assume you want to join this team and have send you an invitation.

That link is correct though you cannot access it when not logged in.

**Comment by DengroWikibase** [comment]
Thanks for clarifying this.

> I assume you want to join this team and have send you an invitation.

I do. The invitation has been sent to the community more than once - through the mailing list, the website and here. 

> That link is correct though you cannot access it when you are not part of the SMW org.

Although I do have an account over at semantic-mediawiki.org, it is not linked to my Github account.

**Comment by JeroenDeDauw** [comment]
Thanks for joining!

**Comment by kghbln** [comment]
@DengroWikibase I wonder who you are in reality. :) Welcome and thanks for joining the team of testers!
