### ISSUE TITLE
`smwsearchicon` reference in i18n message files

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1932]
Things like `<span class=\"smwsearchicon\">+</span>` [0] should not be part of a message description.

![image](https://cloud.githubusercontent.com/assets/1245473/19540610/f338d9de-9660-11e6-9026-9f4980c6c3cf.png)

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?l=JSON&q=smwsearchicon&utf8=%E2%9C%93

**Comment by kghbln** [comment]
These are obviously precursor translations dating back to a pre 2008 message string. Amended messages will roll in with the next translation update from twn.
