### ISSUE TITLE
`$smwgLinksInValue` leading to PHP crashes when set to "true"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1963]
### Setup and configuration

- Semantic MediaWiki: 2.5.0-alpha (9a82356)
- MediaWiki: 	1.27.1 (a52d35d)
- PHP: 	5.6.27
- MariaDB: 	10.0.27

### Issue

The help page on [`$smwgLinksInValues`](https://www.semantic-mediawiki.org/wiki/Help:$smwgLinksInValues) still warns about possible PHP crashes if set the configuration parameter is set to "true" due to an eight year old [warning](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.3/includes/SMW_Settings.php#L101-L110).

Quote @mwjames: 

> So it is time to reevaluate the truthfulness of this statement or at least given an indication of how many links would break the wiki. For example a text with xyz characters and x amount of links in values would break the wiki for the PCRE y version.

It is however now possible to avoid changing this setting by using the `#set'` parser function as these [examples show](https://www.semantic-mediawiki.org/wiki/Demo:Links_in_values) but what about in-text annotations?

To be able to test I have changed the [configruation of sandbox](http://sandbox.semantic-mediawiki.org/w/index.php?title=SMW_Sandbox%3ASetup_information&type=revision&diff=4400&oldid=4393) to `$smwgLinksInValues = true;`.

A test page for this issue can be found [here](http://sandbox.semantic-mediawiki.org/wiki/Issue/1963).

**Comment by kghbln** [comment]
On the spot which caused https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1961#issuecomment-256417048 to exit I get this in the promt:

```
(3371/3427)     Finished processing ID 3376 (Utilisateur:Lalquier)
(3373/3427)     Finished processing ID 3378 (This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_by_Semantic_MediaWiki._For_a_comprehensive_description_on_how_to_use_annotations_or_the#0#ask_parser_function,_please_have_a_look_at_the_getting_started,_in-text_annotation,_or_inline_queries_help_page.This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_)
(3374/3427)     Finished processing ID 3379 (Utilisateur:Emilzola)
(3378/3427)     Finished processing ID 3401 (Subobject_and_"best"_value_query#0#_QUERYcd0dd34fd10ddcd0907e4b6a34e98dfd)
(3379/3427)     Finished processing ID 3402 (Subobject_and_"best"_value_query#0#_QUERY5ee3d99470eef1e74c20c3fd9f5eeb48)
(3380/3427)     Finished processing ID 3403 (Subobject_and_"best"_value_query#0#_QUERY5d5addc5ff705e4301fa60f45f3fafa3)
(3381/3427)     Finished processing ID 3404 (SEA:Internal#0#_QUERYc14b0a6b4f5c29750d69874553aaf8d3)
(3382/3427)     Finished processing ID 3405 (SEA:Internal#0#_QUERYc62ef87cee27cd0afd3f6a2ad07efd95)
(3383/3427)     Finished processing ID 3406 (This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_by_Semantic_MediaWiki._For_a_comprehensive_description_on_how_to_use_annotations_or_the#0#ask_parser_function,_please_have_a_look_at_the_getting_started,_in-text_annotation,_or_inline_queries_help_page.This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_)
(3392/3427)     Finished processing ID 3428 (This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_by_Semantic_MediaWiki._For_a_comprehensive_description_on_how_to_use_annotations_or_the#0#ask_parser_function,_please_have_a_look_at_the_getting_started,_in-text_annotation,_or_inline_queries_help_page.This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_)
(3412/3427)     Finished processing ID 3448 (This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_by_Semantic_MediaWiki._For_a_comprehensive_description_on_how_to_use_annotations_or_the#0#ask_parser_function,_please_have_a_look_at_the_getting_started,_in-text_annotation,_or_inline_queries_help_page.This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_)
```
This does not really look healthy.

**Comment by mwjames** [comment]
> (3373/3427)     Finished processing ID 3378 (This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_by_Semantic_MediaWiki._For_a_comprehensive_description_on_how_to_use_annotations_or_the#0#ask_parser_function,_please_have_a_look_at_the_getting_started,_in-text_annotation,_or_inline_queries_help_page.This_page_supports_semantic_in-text_annotations_(e.g._"Is_specified_asWorld_Heritage_Site")_to_build_structured_and_queryable_content_provided_)

This is the text shown above the the Edit window, so yes this looks strange (well the message text contains `[[ .. ]]` links).

**Comment by kghbln** [comment]
> This is the text shown above the the Edit window, so yes this looks strange (well the message text contains [[ .. ]] links).

Though not the nicest outcome but still a good to know thing what may be worked upon. Anther insight form this: [using `#set` works](https://www.semantic-mediawiki.org/wiki/Demo:Links_in_values).

**Comment by kghbln** [comment]
So the answer is "yes".
