### ISSUE TITLE
Rework "INSTALL.md"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1965]
### Issue

Since the upcoming 2.5 branch of SMW breaks compatibility with versions of MediaWiki 1.23.0 and lower the "INSTALL.md" should be reworked as it makes a lot of now unnecessary references to earlier versions and does not at all mention the worries introduced by MediaWiki 1.25+ ("composer.local.json"), etc.

**Comment by mwjames** [comment]
"... Thanks, and in the mean time I can see in a readme.md that MS SQL is not supported by Semantic Mediawiki - would be nice if that was clearly stated in the installation guide..." [0]

[0] https://www.mediawiki.org/wiki/Topic:Tep32zhstc7x2gro

**Comment by kghbln** [comment]
> would be nice if that was clearly stated in the installation guide...

Well, what about reading [COMPAT](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md). Anyway why not adding a note and also include Oracle which is another one not supported.

**Comment by kghbln** [comment]
> "... Thanks, and in the mean time I can see in a readme.md that MS SQL is not supported by Semantic Mediawiki - would be nice if that was clearly stated in the installation guide..." [0]

We are already clearly referring to the compat document in the installation document. However an explicit info about these two backends was missing there. Thus just added with a7e5abb.
