### ISSUE TITLE
(Bug 57312) Inline query table result "bug" when starting with "*" or "#".

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticMediaWiki#197]
This one is also on Bugzilla (https://bugzilla.wikimedia.org/show_bug.cgi?id=57312).

When using {{#ask:... | format=table the first line of the property content is not handled correctly when they start with a "*" or "#" . When manually creating a table with semantic data you can "program" around this by starting at a new line on your page or template to show the property value. To make it more clear I made an example on: http://scratchpad.referata.com/wiki/Table_test

Scratchpad.referata runs on SMW 1.8.0.5 but the same thing happens in SMW 1.9.1

I think this is a general issue when the results of an inline query are shown in a table format.

Regards,

Felipe.

**Comment by mwjames** [comment]
I think this has been addressed with #1513.

http://sandbox.semantic-mediawiki.org/wiki/Issue/1513

**Comment by jongfeli** [comment]
Yes it is, thank you very much @mwjames. :thumbsup:
