### ISSUE TITLE
`$smwgPropertyZeroCountDisplay = false;` not working as expected

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1976]
### Setup and configuration

- SMW version: 2.5.0-alpha (6916295)
- MW version: 	1.27.1 (a52d35d) / same behaviour with 1.23.15
- PHP version: 5.6.27
- DB (MySQL etc.): MariaDB 10.0.28

### Issue

Yesterday I added `$smwgPropertyZeroCountDisplay = false;` on [sandbox](http://sandbox.semantic-mediawiki.org) to hide the properties with no value assignment on special page "Properties".

The properties are indeed hidden but one still gets the numbered listing and the search icon. Example screen shot:

![bildschirmfoto vom 2016-11-03 13 36 06](https://cloud.githubusercontent.com/assets/1104078/19966138/c14b55ee-a1ca-11e6-80fb-42c2cbea15d1.png)

I would expect that the counting starts with "1." for the "20160212 Month" property which is still at "2."

**Comment by mwjames** [comment]
Should be fixed with 1979. I'm not sure this just sneaked in with 2.5 or was already present with 2.4*.

**Comment by kghbln** [comment]
> I'm not sure this just sneaked in with 2.5 or was already present with 2.4*.

I actually detected it on a MW 1.23 with SMW 2.4.1 and as a result added the setting to sandbox. So it was in 2.4. However, thanks a lot for the fix.
