### ISSUE TITLE
Resource Loader: Unexpected general module

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1977]
### Setup and configuration

- Semantic MediaWiki	2.5.0-alpha (c4cfb88) 08:03, 3. Nov. 2016
- MediaWiki 	1.28.0-rc.0 (7625c75) 15:14, 3. Nov. 2016
- PHP 	5.6.27-0+deb8u1 (apache2handler)
- MariaDB 	10.0.28-MariaDB-1~jessie

### Issue

The resourceloader log is throwing the following issues in masses:

```
2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.smw.style" in styles queue.
2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.smw.tooltip.styles" in styles queue.
2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.semanticbreadcrumblinks" in styles queue.
2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.smw.style" in styles queue.
2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.smw.tooltip.styles" in styles queue.
```
This issue is present for quite some time so not restricted to the version combination mentioned above.

**Comment by mwjames** [comment]
> MediaWiki 1.28.0-rc.0

See https://phabricator.wikimedia.org/T142438.

> Your module is seen as a general module instead of a style module because it has dependencies, which have never been supported on style modules. Things probably work fine for you because it either doesn't really depend on it, or because you're already loading that module.
> Removing the dependencies property should fix the warning.

I have no immediate plans on fixing this but given the "... Removing the dependencies property ..." maybe only listed sources require a touch up:

- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/Resources.php#L32-L41
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/Resources.php#L139-L147

**Comment by kghbln** [comment]
Thanks to your insight on this. So it seems to be more of an code quality issue. Does not look utmost important to fix right now but good to keep in mind.

**Comment by mwjames** [comment]
> Does not look utmost important to fix right now but good to keep in mind.

Fixed with #2018 and came with the weekly tidy train.

**Comment by kghbln** [comment]
Cool, not just my logs will much like this!

**Comment by kghbln** [comment]
@mwjames I do not like to tell but the resourceloder log continues to issue these errors galore.

**Comment by mwjames** [comment]
> resourceloder log continues to issue these errors galore.

... with the same messages I guess.

**Comment by mwjames** [comment]
> 2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.semanticbreadcrumblinks" in styles queue

This one isn't fixed.

>  Unexpected general module "ext.smw.style" in styles queue.
2016-11-04 12:54:19 phalaris 0210020150926-02100_: Unexpected general module "ext.smw.tooltip.styles" in styles queue.

Those two still appear?

**Comment by kghbln** [comment]
> This one isn't fixed.

This should be an issue at SBL. Will open to move it out of this issue.

> Those two still appear?
Affirmative "Unexpected general module "ext.smw.tooltip.styles" in styles queue." is still out in the wild.

**Comment by mwjames** [comment]
> Affirmative "Unexpected general module "ext.smw.tooltip.styles" in styles queue." is still out in the wild.

Let's see whether https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/7f351b7620e4e5b2d9b9b2c3b467aca85c3529a6 fixes it or not.

**Comment by kghbln** [comment]
SBL now reported https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/issues/21

**Comment by kghbln** [comment]
> Let's see whether 7f351b7 fixes it or not.

It does. No more unexpected general modules!

**Comment by mwjames** [comment]
> Let's see whether 7f351b7 fixes it or not.

I saw some out of place CSS, hopefully ee70e49f3b fixes it.

![image](https://cloud.githubusercontent.com/assets/1245473/20645175/b7f644fc-b455-11e6-9307-451e8b937124.png)

**Comment by kghbln** [comment]
> I saw some out of place CSS, hopefully ee70e49 fixes it.

It appears to have done the job!
