### ISSUE TITLE
Tablebuilder forces index creation on an unaltered schema definition

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1978]
### Setup and configuration

- SMW version: 1.8+
- MW version: all
- PHP version: all
- DB (MySQL etc.): MySQL, Postgress

### Issue

Relates to https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/17.

```
Checking index structures for table smw_ft_search ...
   ... index s_id is fine.
   ... index p_id is fine.
   ... index o_sort is fine.
   ... removing index o_text ...done.
   ... creating new index o_text ...done.
   ... done.

Checking index structures for table smw_prop_stats ...
   ... removing index p_id ...done.
   ... index usage_count is fine.
   ... creating new index p_id ...done.
   ... done.
```

In both cases above the `TableBuilder` (`SMWSQLHelpers` before 2.5) should not recreate the index on an unaltered schema definition. The index definition encapsulate by an array causes \[0] (using `array_search`) to fail on a nested array and returns `false` resulting in first the removal and then the creation an unaltered index which may lead to unnecessary conversion time pending the size of a DB.

The problematic line has been copied over to the refactored `TableBuilder`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8.0.5/includes/storage/SMW_SQLHelpers.php#L354
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/TableBuilder/MySQLTableBuilder.php#L236

**Comment by kghbln** [comment]
Perhaps that is something that should even still go into 2.4

**Comment by mwjames** [comment]
#1984 is expected to fix this issue.

> Perhaps that is something that should even still go into 2.4

One would have to touch `SMWSQLHelpers`  (which has not tests whatsoever) with the issue being resident since 1.8 hence no recent regression.

In 2.5, the `TableBuilderIntegrationTest` allows to check (with a real table) that the expected behaviour actual occurs and does what it says for all three MySQL, Postgres, and SQLite.

For example, the test found another glitch in SQLite [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1984/files#diff-3a741701a1d588e142a22ed7cf29179fR166

**Comment by kghbln** [comment]
> One would have to touch SMWSQLHelpers (which has not tests whatsoever) with the issue being resident since 1.8 hence no recent regression.

All right. Fair enough. :)

**Comment by kghbln** [comment]
Fixed as "update.php" shows:

```
Checking index structures for table smw_ft_search ...
   ... index s_id is fine.
   ... index p_id is fine.
   ... index o_sort is fine.
   ... index o_text is fine.
   ... done.
```
and 
```
Checking index structures for table smw_prop_stats ...
   ... index p_id is fine.
   ... index usage_count is fine.
   ... done.
```
