### ISSUE TITLE
qtip JS lib breaks when AMD is available

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1994]
SMW 2.4.1

> Wikia uses AMD for several of its JS modules. qtip detects that AMD is present and working and so it uses it to define itself, but rest of Semantic MediaWiki is using the global jQuery object - which does not have the qtip function because AMD was used instead of the global instance. -- @TK-999

See https://github.com/Wikia/SemanticMediaWiki/commit/7ff008a0b8f006da70845e9164263987b081f834

**Comment by mwjames** [comment]
I'm not sure this is an actual SMW issue.

**Comment by JeroenDeDauw** [comment]
Somehow we should make the lib not use AMD even when available. If that is not possible, we could file an upstream feature request.

**Comment by TK-999** [comment]
This is a tricky situation. Almost all jQuery extensions include such functionality to determine if AMD is present, and they proceed to assume either AMD or the global jQuery object is used, _and only one of these_. The conflict in this situation stems from Wikia's simultaneous use of AMD as well as ResourceLoader. So the question is if it is common for a vanilla MediaWiki install to make use of AMD, given that the preferred method of client-side encapsulation, modularization and dependency handling in MediaWiki is ResourceLoader.

**Comment by JeroenDeDauw** [comment]
Thanks for explaining. If this is a problem that occurs with MediaWiki and those jQuery plugins, then it indeed is not something we should address in SMW.
