### ISSUE TITLE
Avoid pulling in too new PHP code in the build script

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2016]
For https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/build/release/build_tarballs.sh, it will pull in SMW dependencies needing [insert new PHP version] if the build machine supports it, thus breaking all consumers that don't have this new version.

**Comment by legoktm** [comment]
I believe you can use <https://getcomposer.org/doc/06-config.md#platform> to set your lowest supported PHP version, and then it'll pull in dependencies that match that platform requirement.

**Comment by JeroenDeDauw** [comment]
This script needs to be modified to insert the platform information into the composer.json file and then do a composer update https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/build/release/build_tarballs.sh

**Comment by kghbln** [comment]
I knew the file but did on think of

> This script needs to be modified to insert the platform information into the composer.json file

So something like
```sh
PHPVERSION="$3"

if [ "$PHPVERSION" == "" ]; then
	sed -e '"support": {\[.*\]},/a "platform": { "php": "${PHPVERSION}" },/n' composer.json' 
fi
```

**Comment by legoktm** [comment]
Might be easier to just manipulate the JSON file with PHP instead of trying to do it in sed? :)

**Comment by kghbln** [comment]
> Might be easier to just manipulate the JSON file with PHP instead of trying to do it in sed? :)

So my suggestion does not work which also does not come as a surprise. Just tried to get painkillers moving. ;) I guess I should rather leave this to Jeroen.

**Comment by JeroenDeDauw** [comment]
I actually tried the sed approach but this bash magic really is no my thing

> Might be easier to just manipulate the JSON file with PHP instead of trying to do it in sed? :)

This requires changing the bash script into a PHP script, so perhaps not

**Comment by legoktm** [comment]
Is using PHP a deal breaker? You could also use `php -r ...` or I suspect you could probably use jq if you really want to use bash.

**Comment by kghbln** [comment]
Thought it will have been nice I do not see this as a hold up for SMW 2.4.4 since I can add the platform magic prior to creating the release tarballs.

Why is bash so bad? Is is just quaint or so? I think it might just be a matter of figuring out the regex fu for sed.

**Comment by JeroenDeDauw** [comment]
I'm fine with the script being PHP. PR welcome.

Using a regex is kind hacky, using PHPs `json_decode` and `json_encode` is nicer. Same with the `jq` thing.

I agree to not block a release on this, like you say you can just do it manually.

**Comment by kghbln** [comment]
I have the feeling that this issue will most likely degenerate into issue rot.

**Comment by kghbln** [comment]
So just adding [this](https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/ae273872b80feb6d394bdda2dd205f08a46b6b44) does not help as [that](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2015#issuecomment-267544170) shows. The only thing I can think of is setting an explicit version. Apart from that we are probably running out of luck which no antediluvian environment at hand to generate the tarballs.

**Comment by JeroenDeDauw** [comment]
Perhaps you did something wrong in the workflow. I will give this a try and see what happens. Next week, once I am no longer doing two jobs at the same time...

**Comment by kghbln** [comment]
> I will give this a try and see what happens. Next week, once I am no longer doing two jobs at the same time...

No worries, time will tell. :)

> Perhaps you did something wrong in the workflow.

I will be curious to lean the workflow. What I did was to install SMW, manipulate "composer.json", manipulate "build.sh" and then run "build_tarballs.sh". Appeared to be a logical sequence of action to me.

**Comment by kghbln** [comment]
@JeroenDeDauw What about fluffing this one? I know that I am being cruel here. :)

**Comment by mwjames** [comment]
Serious question, do we expect some actionable task here? If not, close it.

**Comment by kghbln** [comment]
> Serious question, do we expect some actionable task here? If not, close it.

@JeroenDeDauw It will be cool if you could add in some lines of code to overcome this issue. As soon as I upgraded the server serving the sandbox wiki, we will again run into this issue.

Another solution I also can think of is to set up an virtual box which uses the minimum requirements.

**Comment by kghbln** [comment]
> Another solution I also can think of is to set up an virtual box which uses the minimum requirements.

Probably this is the easier way. Should I open an actionable issue at [this place](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues)?

**Comment by JeroenDeDauw** [comment]
The problem and acceptance criteria should be clear from the title and description. That no one is poking at this does not make the task any less important or valid.

**Comment by kghbln** [comment]
I added this with status "open" to the "Enhancements and features" board, meaning that even if I closed it may be picked up to improve SMW.

**Comment by mwjames** [comment]
Marking this as done, @kghbln provided https://github.com/SemanticMediaWiki/IndividualFileRelease and the project no longer maintains tarballs (#3382, #3347).
