### ISSUE TITLE
Use of Revision::getText was deprecated in MediaWiki 1.21 (SMW\\ContentParser::fetchFromParser)

### ISSUE THREAD

**Issue by nemobis** [SemanticMediaWiki/SemanticMediaWiki#2038]
### Setup and configuration

- SMW version: 2.4.2
- MW version: 1.29-alpha

### Issue

```
09.45 -rakkaus:#mediawiki-i18n- (27 lines skipped) \nDeprecated: Use of Revision::getText was deprecated in MediaWiki 1.21. [Called from SMW\\ContentParser::fetchFromParser in /.../extensions/SemanticMediaWiki/includes/ContentParser.php at line 202] in /.../includes/debug/MWDebug.php on line 311
```

**Comment by kghbln** [comment]
Thanks for reporting. Pls somehow try to provide all setup information. Thanks.
* HHVM 	3.15.3 (srv)

**Comment by mwjames** [comment]
A complete stack trace would be nice, anyway I think:
- `SMW\UpdateJob` used the `$contentParser->forceToUseParser();` [0] option which ultimately leads to a
- `SMW\\ContentParser::fetchFromParser` call which internally relies on `Revision::getText`.

The call to `forceToUseParser` in `SMW\UpdateJob` has been removed with #1911, so it should no longer output a message in MW 1.28+.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/141b8e8e2841916ea00c31363fe16d125d7d022b#diff-8bbe1fc6b35164362d2aa8f346b2f77dL135
