### ISSUE TITLE
Recurring events in templates?

### ISSUE THREAD

**Issue by slushpuppy** [SemanticMediaWiki/SemanticMediaWiki#2039]
### Setup and configuration

- SMW version: 2.4.3
- MW version: 1.27
- PHP version: 5.6
- DB (MySQL etc.): MariaDB

### Issue

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

http://sandbox.semantic-mediawiki.org/wiki/Test_recurring
http://sandbox.semantic-mediawiki.org/wiki/Mod%C3%A8le:Test_recurring

It appears the recurring events don't seem to be working in templates- or unless my demo is wrong.

Please kindly assist!

**Comment by slushpuppy** [comment]
Mistake on my end.

Make sure the following

 |property=<>

and

 |group=<>

Are set properly

**Comment by kghbln** [comment]
@slushpuppy No worries. Yeah this feature requires to thoroughly stick to the structure.
