### ISSUE TITLE
ORDER BY/INNER JOIN query is painfully slow

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2040]
### Setup and configuration

- SMW version: all (1.8+)
- MW version: all

refs #1234

### Issue

Based on a small benchmark instance with the purpose to investigate some long running queries (the high volume on properties are be design):

```
Property values (total)	322,503
Property values (improper annotations)	0
Properties (total)	29
Properties (registered with a page)	21,023
Properties (assigned to a datatype)	11,022
Outdated entities (marked for removal)	532
Subobjects	52,738
```
A "simple" query executed by `SMWSQLStore3Readers::getPropertySubjects` with the only objective to:

- Select entities that match `p_id='21134'` in table `smw_di_blob`
- Order them by sortkey found in `smw_object_ids`
- Selected `s_id` from `smw_di_blob`, match those against `smw_object_ids` and select `smw_title, smw_namespace, smw_iw, smw_sortkey, smw_subobject` fields

#### `INNER JOIN` (with `ORDER BY` and is the current query plan) 

- `5.6740 sec`	

```
SELECT DISTINCT smw_title, smw_namespace, smw_iw, smw_sortkey, smw_subobject
 FROM `smw_object_ids`
 INNER JOIN `smw_di_blob` AS t1 ON t1.s_id=smw_id
 WHERE t1.p_id='21134' AND smw_iw!=':smw' AND smw_iw!=':smw-delete'
 ORDER BY smw_sortkey
 LIMIT 25	
```

SQL Explain shows:

```
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	t1	index	s_id,p_id,s_id_2	s_id	8	NULL	58761	Using where; Using index; Using temporary; Using filesort
1	SIMPLE	smw_object_ids	eq_ref	PRIMARY,smw_id,smw_iw	PRIMARY	4	bench-01.t1.s_id	1	Using where
```

The problem is the `Using filesort` on `58761` rows because of the `ORDER BY` with the `INNER JOIN` doing a full scan in order to apply the sortkey order that is kept in the `smw_object_ids` table.

#### `INNER JOIN` (without `ORDER BY`)

- `0.0035 sec`
- Running the same query without `ORDER BY` will result in a `0.0035 sec` response which is a magnitude in comparison to the `ORDER BY` query but contains unsorted results

```
SELECT DISTINCT smw_title, smw_namespace, smw_iw, smw_sortkey, smw_subobject
FROM  `smw_object_ids` 
INNER JOIN  `smw_di_blob` AS t1 ON t1.s_id = smw_id
WHERE t1.p_id =  '21134'
AND smw_iw !=  ':smw'
AND smw_iw !=  ':smw-delete'
LIMIT 25
```

#### Sub-query + `INNER JOIN` + `ORDER BY`

- `0.0045 sec`
- Based on [0], we need to match the sortkey against an entity hence I added the `s_sort` field to the individual table
- INNER JOIN returns a sub-query where `ORDER BY` is applied and limited
- NO filesort
- Making use of the `s_sort` index within the sub-query

```
SELECT DISTINCT smw_title, smw_namespace, smw_iw, smw_sortkey, smw_subobject
FROM `smw_object_ids`
INNER JOIN (
	SELECT s_id FROM `smw_di_blob` 
	WHERE p_id='21134'
	ORDER BY s_sort
	LIMIT 25
 ) AS t1 ON t1.s_id=smw_id
 WHERE smw_iw!=':smw' AND smw_iw!=':smw-delete
```
```
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	PRIMARY	<derived2>	ALL	NULL	NULL	NULL	NULL	25	Using temporary
1	PRIMARY	smw_object_ids	eq_ref	PRIMARY,smw_id,smw_iw	PRIMARY	4	t1.s_id	1	Using where
2	DERIVED	smw_di_blob	index	p_id	s_sort	258	NULL	58761	Using where
```
## Notes 

- [0] http://dba.stackexchange.com/questions/31636/very-slow-mysql-queries-even-with-indexes
- http://stackoverflow.com/questions/3015391/mysql-slow-query-inner-join-order-by-causes-filesort
- https://www.percona.com/blog/2006/09/01/mysql-order-by-limit-performance-optimization/
- https://explainextended.com/2009/10/23/mysql-order-by-limit-performance-late-row-lookups/
- http://forums.mysql.com/read.php?115,519488,519488#msg-519488

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.

**Comment by davidmartos96** [comment]
I am experiencing the exact same behaviour in a SQLite 3 database. Adding the ORDER BY clause implies the query not ending at all, due to it being slow. Removing it makes the query return in around 80 ms.
¿Could this be related?
