### ISSUE TITLE
New setting smwgAdminSetupStore?

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2047]
Then going through https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2044 I realised that it may also be as scary if someone is able to setup the store from the GUI as triggering a data refresh.

So a setting `$smwgAdminSetupStore` allowing to hide the button and instead showing a permission notice may be useful. Perhaps `$smwgAdminRefreshStore` could be extended to disable both actions at the same time though I think two settings are better in the end.

**Comment by kghbln** [comment]
@JeroenDeDauw @mwjames What are your feelings about this?

**Comment by mwjames** [comment]
Fine with me, the re-factored code should make this a rather simple task.

**Comment by mwjames** [comment]
Added with #2056.

**Comment by kghbln** [comment]
Absolutely cool! Thanks a lot.
