### ISSUE TITLE
Code coverage job run reached limit with XDebug / PHP 7

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2057]
Travis-CI maintains a limit of 50 min for long running jobs and our code coverage job with XDebug / PHP 7 has now reached that limit [0] which means code coverage reports more or less will fail from this point forward.

```
+composer phpunit -q -- --coverage-clover /home/travis/build/SemanticMediaWiki/SemanticMediaWiki/tests/coverage.clover
Using PHP 7.0.13

Semantic MediaWiki: 2.5.0-alpha (SMWSQLStore3, mysql)
MediaWiki:          1.27.1 (Extension vendor autoloader)
Site language:      en

Execution time:     2016-11-27 05:25
Xdebug:             2.4.1 (enabled)

PHPUnit 4.8.29 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.13 with Xdebug 2.4.1
Configuration:	/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/phpunit.xml.dist

.............................................................   61 / 4281 (  1%)
...
SMW\Tests\Integration\MediaWiki\Import\PageWithTemplateInclusionTest testImportToVerifyAnnotationByTemplateInclusion ran for 13.729 seconds

.SMW\Tests\Integration\MediaWiki\Import\RecordDataTypeTest testImportOfRecordValues ran for 43.402 seconds

.SMW\Tests\Integration\MediaWiki\Import\RedirectPageTest testPageImportToCreateRedirect ran for 12.771 seconds

The job exceeded the maximum time limit for jobs, and has been terminated.
```

There is possibility to use `phpdbg` [1, 2] instead of `XDebug` but `phpdbg` doesn't like to play with MediaWiki [3].

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/179153489
[1] http://phpdbg.com/docs
[2] https://thephp.cc/news/2015/08/phpunit-4-8-code-coverage-support
[3] https://phabricator.wikimedia.org/T147791

**Comment by kghbln** [comment]
Pooh

**Comment by mwjames** [comment]
This ticket isn't going anywhere, I have experimented with partial uploads of coverage reports to split queues [0] by unit, integration etc., so besides that there isn't a lot we can do since the amount of tests will increase and inherently the time it requires to run those tests/coverage reports.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/coverage
