### ISSUE TITLE
Translation reminder

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2062]
Recently a lot of new system messages were added to SMW. It is now time to remind the community to provide translations via [twn](https://translatewiki.net/w/i.php?title=Special%3AMessageGroupStats&x=D&group=mwgithub-semanticmediawiki&suppressempty=1#sortable:3=asc) and by doing patches due to https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1848

**Comment by kghbln** [comment]
Hopefully [this reminder of today, January 20, 2017](http://wikimedia.7.x6.nabble.com/Preparing-translations-for-the-next-major-release-of-Semantic-MediaWiki-td5070976.html) gets more attention than the [previous one of June 6, 2017](http://wikimedia.7.x6.nabble.com/Preparing-translations-td5064431.html).

**Comment by Nikerabbit** [comment]
I took the liberty of adding a note today to translatewiki.net sitenotice as well.

**Comment by kghbln** [comment]
@Nikerabbit Thats awesome and much appreciated. Thanks a lot!

**Comment by kghbln** [comment]
REM Some [relevant docu](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/ExtraneousLanguage/README.md).

**Comment by kghbln** [comment]
Just sent [a kind reminder](http://wikimedia.7.x6.nabble.com/Preparing-translations-for-the-next-major-release-of-Semantic-MediaWiki-td5070976.html)
