### ISSUE TITLE
DB Lock contention and "Lock wait timeout exceeded"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2063]
### Setup and configuration

- SMW version: 2.3.1 
- MW version: 1.26.2 
- PHP version: 5.6.27 (apache2handler)
- DB (MySQL etc.): 5.6.16 

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
UPDATE `smw_object_ids` SET smw_proptable_hash = 'a:4:{s:12:\"smw_fpt_inst\";s:32:\"7d64be00f71203050c0d0c59a1fb8e46\";s:12:\"smw_fpt_mdat\";s:32:\"4e7269fa53d4731baf4a114805230244\";s:12:\"smw_fpt_cdat\";s:32:\"d56a3ead28b78ca64c1833f7ef3cfdef\";s:12:\"smw_fpt_newp\";s:32:\"ff8259d43dfc5a27a4cefdaabbf38760\";}' WHERE smw_id = '3809'
Function: SMWSql3SmwIds::setPropertyTableHashes
Error: 1205 Lock wait timeout exceeded; try restarting transaction (CHISD91228)
Backtrace:

#0 ...\includes\db\Database.php(1076): DatabaseBase->reportQueryError('Lock wait timeo...', 1205, 'UPDATE `smw_ob...', 'SMWSql3SmwIds::...', false)
#1 ...\includes\db\Database.php(2027): DatabaseBase->query('UPDATE `smw_ob...', 'SMWSql3SmwIds::...')
#2 ...\extensions\SemanticMediaWiki\src\MediaWiki\Database.php(334): DatabaseBase->update('smw_object_ids', Array, Array, 'SMWSql3SmwIds::...', Array)
#3 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_Sql3SmwIds.php(1112): SMW\MediaWiki\Database->update('smw_object_ids', Array, Array, 'SMWSql3SmwIds::...')
#4 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(381): SMWSql3SmwIds->setPropertyTableHashes(3809, Array)
#5 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(256): SMWSQLStore3Writers->writePropertyTableUpdates(3809, Array, Array, Array)
#6 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(149): SMWSQLStore3Writers->doFlatDataUpdate(Object(SMW\SemanticData))
#7 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3.php(338): SMWSQLStore3Writers->doDataUpdate(Object(SMW\SemanticData))
#8 ...\extensions\SemanticMediaWiki\includes\storage\SMW_Store.php(229): SMWSQLStore3->doDataUpdate(Object(SMW\SemanticData))
#9 ...\extensions\SemanticMediaWiki\includes\StoreUpdater.php(183): SMW\Store->updateData(Object(SMW\SemanticData))
#10 ...\extensions\SemanticMediaWiki\includes\StoreUpdater.php(125): SMW\StoreUpdater->doRealUpdate(NULL)
#11 ...\extensions\SemanticMediaWiki\includes\StoreUpdater.php(92): SMW\StoreUpdater->performUpdate()
#12 ...\extensions\SemanticMediaWiki\includes\ParserData.php(261): SMW\StoreUpdater->doUpdate()
#13 ...\extensions\SemanticMediaWiki\src\MediaWiki\Hooks\LinksUpdateConstructed.php(62): SMW\ParserData->updateStore()
#14 ...\extensions\SemanticMediaWiki\src\MediaWiki\Hooks\HookRegistry.php(287): SMW\MediaWiki\Hooks\LinksUpdateConstructed->process()
#15 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(Object(LinksUpdate))
#16 ...\includes\Hooks.php(201): call_user_func_array(Object(Closure), Array)
#17 ...\includes\deferred\LinksUpdate.php(137): Hooks::run('LinksUpdateCons...', Array)
#18 ...\includes\content\AbstractContent.php(234): LinksUpdate->__construct(Object(Title), Object(ParserOutput), false)
#19 ...\includes\page\WikiPage.php(2183): AbstractContent->getSecondaryDataUpdates(Object(Title), NULL, false, Object(ParserOutput))
#20 ...\includes\page\WikiPage.php(1861): WikiPage->doEditUpdates(Object(Revision), Object(User), Array)
#21 [internal function]: WikiPage->doEditContent(Object(WikitextContent), '', 114, false, Object(User), 'text/x-wiki')
#22 ...\includes\page\Article.php(2049): call_user_func_array(Array, Array)
#23 ...\includes\EditPage.php(1957): Article->__call('doEditContent', Array)
#24 ...\includes\EditPage.php(1957): Article->doEditContent(Object(WikitextContent), '', 114, false, Object(User), 'text/x-wiki')
#25 ...\includes\EditPage.php(1331): EditPage->internalAttemptSave(Array, true)
#26 ...\includes\EditPage.php(560): EditPage->attemptSave(Array)
#27 ...\includes\actions\EditAction.php(58): EditPage->edit()
#28 ...\includes\actions\SubmitAction.php(40): EditAction->show()
#29 ...\includes\MediaWiki.php(490): SubmitAction->show()
#30 ...\includes\MediaWiki.php(287): MediaWiki->performAction(Object(Article), Object(Title))
#31 ...\includes\MediaWiki.php(714): MediaWiki->performRequest()
#32 ...\includes\MediaWiki.php(508): MediaWiki->main()
#33 ...\index.php(41): MediaWiki->run()
#34 {main}
```
- relates to http://wikimedia.7.x6.nabble.com/help-with-SMW-amp-lock-contention-td5069690.html
- refs #1709

**Comment by mwjames** [comment]
> Function: SMWSql3SmwIds::setPropertyTableHashes 
> Error: 1205 Lock wait timeout exceeded; try restarting transaction

Normally, lock contention happens because updates on the same table are followed rapidly in sequence with the DB handler unable to release the lock fast enough to provided the next handle for an update operation.

As far as I know (this is more of MediaWiki core topic), lock contention or a lock wait is the consequence of an active lock during a transaction process that hasn't been released by the DB LockManager [1]. As to why there is an unreleased lock, I'm unable to say but the method `setPropertyTableHashes` is only called once within an update transaction making a competing update cycle on the same row within the same transaction unlikely.

Any other process that tries to update [2] the `smw_object_ids` table get its own `beginAtomicTransaction/endAtomicTransaction` and should be released with the commit of the transaction.

I'm not entirely sure how the DB LockManager works, whether its locks the whole table, a row, or just column I cannot say.

The "Error: 1205 Lock wait timeout exceeded" issue is not uncommon [3] in a MediaWiki environment (unrelated to SMW).

Since the mentioned issue isn't very common in/for SMW, try to make an upgrade, if this doesn't solve the issue then maybe changing the caller to rely on `Database::onTransactionIdle` may prove valid (see [4]).

[0] https://www.semantic-mediawiki.org/wiki/Deferred_updates
[1] https://github.com/wikimedia/mediawiki/blob/090d0267daa4721ffb154e7e604804201365f9dd/includes/libs/lockmanager/DBLockManager.php
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_Sql3SmwIds.php#L647
[3] https://phabricator.wikimedia.org/search/query/i2aJS0LBje44/#R
[4] https://phabricator.wikimedia.org/T62600

**Comment by kghbln** [comment]
Adding @hexmode to the loop here.

**Comment by hexmode** [comment]
Thanks, @kghbln.

**Comment by hexmode** [comment]
By looking at the MySQL's "show processlist", they were able to narrow this down to the older CategoryWatch extension.  After disabling it, they have seen fewer problems.  We should know within the week if this was really the cause.  (I'm suspicious because AFAIK, CategoryWatch doesn't do anything with the SMW data.)

Oh, PHP Version: 5.6.27 (apache2handler)

**Comment by mwjames** [comment]
> I'm suspicious because AFAIK, CategoryWatch doesn't do anything with the SMW data.)

The issue does not necessarily have to do anything with SMW as we rely on the DB backend to perform the updates in a timely manner, yet if resources aren't available then sooner or later other processes will suffer including the job queue, DB updates etc.

Some more reading:

- http://stackoverflow.com/questions/5836623/getting-lock-wait-timeout-exceeded-try-restarting-transaction-even-though-im
- http://stackoverflow.com/questions/6000336/how-to-debug-lock-wait-timeout-exceeded
- http://dba.stackexchange.com/questions/100984/mysql-lock-wait-timeout-exceeded-try-restarting-transaction

**Comment by hexmode** [comment]
I talked to them some more today and was given more info.  They had modified CategoryWatch so that it ended up in an infinite loop of queries.  That was the cause of the problem.

**Comment by kghbln** [comment]
Thanks for reporting back and good that we do not have an issue here. Thanks @mwjames also for proving guidance and hints.
