### ISSUE TITLE
Local-specific (ICU) sorting and collation

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2065]
MySQL docs describe a collation as a "set of rules for comparing characters in a character set" [0].

Currently it is not possible to support local-specific sorting/collation (e.g. using ICU) because the sortfield [1] defined by the `smw_object_ids` table is at the same used as string matching field making it impossible to store sort modified representation of a value (which in case of ICU would not be a plain string but a computed UTF-8 character set).

To support local-specific sorting (preferable using the same setting as in $wgCategoryCollation) some changes are required:

- Add an extra sort field that can store  the representation returned by the ICU collator
- `DataItemHandler` is to return the expected sortfield instead of the current fixed `smw_sortkey`
- Modify `DescriptionInterpreter` and `EntityLookup` to use the new sortfield instead of  `smw_sortkey`

refs #1383, #2040

[0] http://dev.mysql.com/doc/refman/5.7/en/charset-general.html
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/TableSchemaManager.php#L108

## See also

- http://php.net/manual/en/intro.intl.php
- https://www.mediawiki.org/wiki/Manual:$wgCategoryCollation

**Comment by DengroWikibase** [comment]
Thanks a lot for this, James! It's good to see things moving forward on this front.


________________________________

**Comment by mwjames** [comment]
#2429 contains a prototype, yet we are missing specific examples that would allow a design of some integration tests for at least the following settings:

* `$wgCategoryCollation = 'uca-default';`
* `$wgCategoryCollation = 'uppercase';`

I only found [0] as authority source but this is a bit narrow to create something from it.

@kghbln Would be nice if we could somehow consolidate all issues relating to collation in one place.

[0] https://dev.mysql.com/doc/refman/5.7/en/charset-collation-effect.html
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/CONTRIBUTING.md#feature-requests

PS: As I reminder, please read [1].

**Comment by mwjames** [comment]
Addressed with #2429 (3.0.x)
