### ISSUE TITLE
MySQL 5.7 causes "UPDATE - SET; Data too long for column" 

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2089]
### Setup and configuration

- MediaWiki 	1.27.1 (8c593e7) 23:49, 26 October 2016
- PHP 	7.0.8-0ubuntu0.16.04.3 (apache2handler)
- MySQL 	5.7.16-0ubuntu0.16.04.1
- Semantic MediaWiki master (https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/999fcb76b8697f1c168bc9951715eb425edd4e5f)

### Issue
Result of the server upgrade [from Ubuntu 15.10 to Ubuntu 16.04.1](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/1) which brought MySQL 5.7 and originally mentioned here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2078#issuecomment-266205480.

After updating to get the fix for https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2078 I tried running `php rebuildData.php -v` and got the following:

```
(316/50617)     Finished processing ID 321* (Help:Count_format)
A database query error has occurred.
```

#### Query:
```
UPDATE  `smw_object_ids` SET smw_sortkey = 'Embedded format#This new version is a minor release and provides bugfixes for the current 2.4 branch of Semantic MediaWiki. Please refer to the help page on [[Help:Installation 2.x|installing]] Semantic MediaWiki to get detailed instructions on how to install or upgrade.;en' WHERE smw_id = '50856'
```
#### Function:
SMWSql3SmwIds::makeDatabaseId

#### Error:
1406 Data too long for column 'smw_sortkey' at row 1 (localhost)

**Comment by kghbln** [comment]
Originally suggested here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2078#issuecomment-266206230

>Error: 1406 Data too long for column 

- http://stackoverflow.com/questions/15949038/error-code-1406-data-too-long-for-column-mysql

I'm wild guessing and I think the sorkey is tooooooooo long (which got truncated in prev. version) and now just falls flat.

You need to change it by hand since I cannot test this.

- Find [0] and
- Add those with a plus

```
 		if ( $id == 0 ) {
 			$sortkey = $sortkey ? $sortkey : ( str_replace( '_', ' ', $title ) );
 			$sequenceValue = $db->nextSequenceValue( $this->getIdTable() . '_smw_id_seq' ); // Bug 42659
 
+			$sortkey = substr( $sortkey, 0, 254 );
+
 			$db->insert(
 				self::TABLE_NAME,
 				array(
 					'smw_id' => $sequenceValue,
 					'smw_title' => $title,
@@ -681,10 +683,13 @@ class SMWSql3SmwIds {
 			if ( $fetchHashes ) {
 				$this->setPropertyTableHashesCache( $id, null );
 			}
 
 		} elseif ( $sortkey !== '' && $sortkey != $oldsort ) {
+
+			$sortkey = substr( $sortkey, 0, 254 );
+
 			$db->update(
 				self::TABLE_NAME,
 				array( 'smw_sortkey' => $sortkey ),
 				array( 'smw_id' => $id ),
 				__METHOD__
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/includes/storage/SQLStore/SMW_Sql3SmwIds.php#L644-L687

**Comment by kghbln** [comment]
> You need to change it by hand since I cannot test this.

Done so and the script is running. Probably needs another 40 mins to complete. However, we are already well past the transgressing page.

**Comment by mwjames** [comment]
> Done so and the script is running. 

Maybe after that create, delete, and move some pages to verify the behaviour. After confirmation, I'll work on a proper patch.

**Comment by kghbln** [comment]
32528 IDs refreshed.

Memory used: 74389664 (b: 13874200, a: 88263864) with a runtime of 3436.66 sec (57.28 min)

Now doing a field test.

**Comment by kghbln** [comment]
> Now doing a field test.

Done this and now the script is running again.

**Comment by kghbln** [comment]
```
32073 IDs refreshed.

Memory used: 61482904 (b: 13874200, a: 75357104) with a runtime of 2598.35 sec (43.31 min)
```
All went smooth and cool.
 
We also need a backport of this one.

**Comment by mwjames** [comment]
> All went smooth and cool.
>We also need a backport of this one.

I should call Lary and ask for a paycheck and an overtime slip after this mess.

**Comment by mwjames** [comment]
> We also need a backport of this one.

Did happen with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/d043d1390e94ce422c09f5c26ad7c1a071329cec.

**Comment by JeroenDeDauw** [comment]
> I should call Lary and ask for a paycheck

Who is Lary? Can I also get a paycheck from him?

**Comment by mwjames** [comment]
Larry Ellison -> Oracle - > MySQL

**Comment by kghbln** [comment]
> I should call Lary and ask for a paycheck and an overtime slip after this mess.

From his perspective we are just mosquitos, I'm afraid.
