### ISSUE TITLE
Ask wikitext parser and formatter

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#209]
### Premise

SMW has a set of domain model objects that represent its [Ask query language](https://semantic-mediawiki.org/wiki/Ask_query_language). It also has code to turn these objects into a wikitext representation, or to turn a wikitext representation into the equivalent objects. Recently a [fresh implementation of the Ask language](https://github.com/wmde/Ask) was created. It is planned that SMW will switch to using the new implementation, ad the code is a lot cleaner. What is however lacking is a fresh implementation of the code parsing and generating the wikitext representation. 
### Task

Implement a new parser for the existing wikitext representation of the Ask language build on top of the new Ask library. Similarly create a new formatter that does the reverse.

Further goals and requirements include:
- A good solid design and clean implementation
- Feture parity with the existing implementation in SMW
- The resulting code should be a library that depends on the Ask library, though not on MediaWiki or SMW, so it is easily reusable in other contexts.
- Compatibility with PHP 5.3.2 up to at least 5.5.
- Unit test coverage for all code, plus additional integration tests for things such as roundtripping
- High level technical documentation describing how to interact with the library

Some recommendations:
- Make the library installable via [Composer](http://getcomposer.org/). The Ask library can be used as an example here.
- Follow the same [coding guidelines used for the Ask library](https://www.mediawiki.org/wiki/Wikibase/Coding_conventions).
- The existing implementation can be used as partial conceptual basis, as long as one keeps in mind it is typical legacy code, and contains many issues that should not be replicated.
- Have the tests run on CI platform, for instance TravisCI, as done for SMW and the Ask library.
- Understanding the new implementation of the Ask language is easier to understand the old one, as it is less tangled up with other concerns. Therefore it is best to first look at it, before looking at the code in SMW to understand the current parsing and formatting implementation.
- The new Ask library has technical documentation on how the language is defined and typically used.
### Pointers
- [Ask library on GitHub](https://github.com/wmde/Ask) (includes technical documentation) 
- Existing implementation in SMW of query parsin and formatting is located in: 
  - SMWDescription and deriving classes (currently in includes/query/[SMW_Description.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/query/SMW_Description.php)) 
  - SMWQueryParser (includes/query/[SMW_QueryParser.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/query/SMW_QueryParser.php)) 
  - Other classes used by the above ones, mostly in [includes/query](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/includes/query)

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
