### ISSUE TITLE
SMW not picking up types after update to 2.4.4 from 2.3.1

### ISSUE THREAD

**Issue by KenanSulayman** [SemanticMediaWiki/SemanticMediaWiki#2105]
### Setup and configuration

- SMW: 2.4.4
- MW: 1.26.4 (2e3e739)
- PHP: HHVM 3.15.2 (srv)
- MySQL: 5.7.16
- ICU: 52.1
- Lua: 5.1.5

rebuildData.php is executed in an isolated HHVM docker container after all data was removed and all caches cleared.

### Issue

We've been eager to release an SMW-based GraphQL API for PsychonautWiki and didn't think too much about the consequences of executing rebuildData.php. After around 10000 pages, SMW failed - that's because the Flow extension has changed the `content-model` for some pages to `flow-board` - and we removed the extension, rendering anything useless that tries to parse or display the page. We didn't notice for over a year, as we never executed rebuildData.php.

After SMW failed in the process, any subsequent invocation would yield (something like): "job dispatcher: $title is not of type Title (null)". SMW was corrupted. The only reason we're still online right now (https://psychonautwiki.org) is extremely aggressive caching. Some pages are starting to fall apart (https://psychonautwiki.org/wiki/Pregabalin).

I patched the MySQL database to NULL all `content-model` and `content-format` fields of revisions and pages tainted by Flow, allowing them to render again.

Since the system is somewhat working still, I decided to spawn a mirror server and come up with a viable recovery strategy that allows me to maintain uptime.

On the mirror, I updated SMW from 2.3.1 to 2.4.4 and proceeded to delete all SMW data using `hhvm setupStore.php --delete`. I ran the MediaWiki update script and cleared Redis using `flushall`. After initializing the tables using `hhvm setupStore.php`, I verified that all property pages included their respective type (i.e., has type::number) and proceeded to rebuild the data using `hhvm rebuildData.php`.

To my surprise, SMW this time didn't fail to process the pages and exited without an error.

I navigated to the previously mentioned article (Pregabalin) and noticed red links:

<img width="276" alt="screen shot 2016-12-14 at 20 40 01" src="https://cloud.githubusercontent.com/assets/280212/21197926/833fbae0-c23d-11e6-81c3-7b3ef13c83d6.png">

Realising SMW shouldn't render the text of a property of the type `text` as a link, I headed to the API to check the types of the properties in said article:

<img width="342" alt="screen shot 2016-12-14 at 20 42 14" src="https://cloud.githubusercontent.com/assets/280212/21197994/d15a2f12-c23d-11e6-885e-ae287a54e69c.png">

SMW has declared all properties to be of type `Page`, I thought. Then I considered the option that the property pages might have been corrupted somehow and I checked the property page of `Oral_onset_time_units`, which should be of type `Text`:

<img width="615" alt="screen shot 2016-12-14 at 20 44 56" src="https://cloud.githubusercontent.com/assets/280212/21198077/36940998-c23e-11e6-9a9c-f3a3cfdc4055.png">

Indeed, all properties are now of type `Page`:

<img width="432" alt="screen shot 2016-12-14 at 20 46 15" src="https://cloud.githubusercontent.com/assets/280212/21198128/6bd3210c-c23e-11e6-8199-f241eae6768e.png">

Naturally, I noticed the little warning symbols:

<img width="532" alt="screen shot 2016-12-14 at 20 46 58" src="https://cloud.githubusercontent.com/assets/280212/21198164/83cc4054-c23e-11e6-9168-5d8a2679c0e9.png">

I tried to wrap my head around this and couldn't come up with a reasonable explanation. I figured I must have failed at configuring rebuildData.php correctly. But I'm not sure how.

Does anyone have an idea what could cause this?

🐳

**Comment by kghbln** [comment]
Thanks for reporting. Is namespace "property" part of the array defined with configuration setting `$smwgNamespacesWithSemanticLinks`? If not try to add it there.

**Comment by KenanSulayman** [comment]
Thanks for you suggestion, @kghbln.

These lines were added to the configuration file, right after `enableSemantics`:

```
$GLOBALS['wgNamespacesToBeSearchedDefault'][SMW_NS_PROPERTY] = true;
$GLOBALS['smwgNamespacesWithSemanticLinks'][SMW_NS_PROPERTY] = true;
```

I added the latter, `wgNamespacesToBeSearchedDefault`, when the first didn't work out. Unfortunately, neither fixed it.

As this matter is a bit opaque, I created a public endpoint for you to access the mirror server: 

https://pw-smw-testmirror.apx.pub/

The following is the browse API for the *LSD* article:

https://pw-smw-testmirror.apx.pub/w/api.php?action=browsebysubject&subject=LSD

**Comment by mwjames** [comment]
Hi,

> https://pw-smw-testmirror.apx.pub/
>
> The following is the browse API for the *LSD* article:
>
> https://pw-smw-testmirror.apx.pub/w/api.php?action=browsebysubject&subject=LSD

By looking at [0] we know (or better conjecture that since
Special:Browse isn't accessible) that the Property: namespace is not
enabled for annotations which is the reason why [[Has type: ...]]
aren't working as expected and fall back to the default Page type.

When generating the "Settings list" from Special:SMWAdmin then we
should see something similar to (102 === SMW_NS_PROPERTY):

```
  "smwgNamespacesWithSemanticLinks": {
        "102": true,
        "103": false,
        "104": true,
        "105": false,
        "108": true,
        "109": false,
        "0": true,
        "1": false,
        "2": true,
        "3": false,
        "4": true,
        "5": false,
        "6": true,
        "7": false,
        "8": false,
        "9": false,
        "10": false,
        "11": false,
        "12": true,
        "13": false,
        "14": true,
        "15": false
    },


    "smwgCanonicalNames": {
        "102": "Property",
        "103": "Property_talk",
        "104": "Type",
        "105": "Type_talk",
        "108": "Concept",
        "109": "Concept_talk"
    }
```

[0] https://pw-smw-testmirror.apx.pub/wiki/Property:Oral_max_afterglow_time

Cheers

**Comment by KenanSulayman** [comment]
Thanks for your input, @mwjames.

I couldn't verify your claim that [`Special:Browse`](https://pw-smw-testmirror.apx.pub/wiki/Special:Browse) is inaccessible, but I guess that doesn't change the answer intrinsically.

The data you have been discussing is actually in place  and looking healthy:

**smwgNamespacesWithSemanticLinks**

```
{
    "102": true,
    "103": false,
    "104": true,
    "105": false,
    "108": true,
    "109": false,
    "0": true,
    "1": false,
    "2": true,
    "3": false,
    "4": true,
    "5": false,
    "6": true,
    "7": false,
    "8": false,
    "9": false,
    "10": false,
    "11": false,
    "12": true,
    "13": false,
    "14": true,
    "15": false
}
```

**smwgCanonicalNames**

```
    {
        "102": "Property",
        "103": "Property_talk",
        "104": "Type",
        "105": "Type_talk",
        "108": "Concept",
        "109": "Concept_talk"
    }
```

It *should* be annotated from what I understood.

**Comment by mwjames** [comment]
Hi,

> I couldn't verify your claim that
> [`Special:Browse`](https://pw-smw-testmirror.apx.pub/wiki/Special:Browse) is
> inaccessible, but I guess that doesn't change the answer intrinsically.

When you look at [0] then you would normally have a link to
`Special:Browse` (below the "Page information" link) in the sidebar if
the namespace is enabled and in case it is not enabled it will not
appear.

Using [1] will show no annotations which only leaves the conclusion
that SMW_NS_PROPERTY namespace is disabled.

> It *should* be annotated from what I understood.

It should and I'm currently not sure what happens on your system.

You could find the class `SMW\MediaWiki\Hooks\BaseTemplateToolbox`
(src/ directory) and add:

```
 	public function process() {
+		var_dump(
+			$this->skinTemplate->getSkin()->getTitle()->getNamespace(),
+			'smwgNamespacesWithSemanticLinks:',
+			ApplicationFactory::getInstance()->getSettings()->get(
'smwgNamespacesWithSemanticLinks' )
+		);
```
to see which settings are available when you visit [0].

[0] https://pw-smw-testmirror.apx.pub/wiki/Property:Oral_max_afterglow_time

[1] https://pw-smw-testmirror.apx.pub/wiki/Special:Browse/Property:Oral_max_afterglow_time

Cheers

**Comment by KenanSulayman** [comment]
Indeed, the constant isn't set on `smwgNamespacesWithSemanticLinks` at the time of invocation.

```
 int(102) string(32) "smwgNamespacesWithSemanticLinks:" array(24) {
     [0]=> bool(true)
     [1]=> bool(false)
     [2]=> bool(true)
     [3]=> bool(false)
     [4]=> bool(true)
     [5]=> bool(false)
     [6]=> bool(true)
     [7]=> bool(false)
     [8]=> bool(true)
     [9]=> bool(false)
     [10]=> bool(true)
     [11]=> bool(false)
     [12]=> bool(true)
     [13]=> bool(false)
     [14]=> bool(false)
     [15]=> bool(false)
     [16]=> bool(false)
     [17]=> bool(false)
     [18]=> bool(true)
     [19]=> bool(false)
     [20]=> bool(true)
     [21]=> bool(false)
     [22]=> bool(true)
     [23]=> bool(false)
 } 
```

This file is included in the autoload manifest generated by Composer. Is it guaranteed to notice the namespace changes in the configuration file?

**Comment by mwjames** [comment]
Hi,

Could you try adding the following to `\SMW\NamespaceManager) (src/
directory) to see if it helps retain the settings.

```
@@ -49,10 +49,12 @@ class NamespaceManager {

 		// Legacy seeting in case some extension request a `smwgContLang` reference
 		if ( empty( $this->globalVars['smwgContLang'] ) ) {
 			$this->globalVars['smwgContLang'] =
$this->extraneousLanguage->fetchByLanguageCode(
$this->globalVars['wgLanguageCode'] );
 		}
+
+		$this->addNamespaceSettings();
 	}

 	/**
 	 * @see Hooks:CanonicalNamespaces
 	 * CanonicalNamespaces initialization
@@ -197,10 +199,16 @@ class NamespaceManager {
 			SMW_NS_TYPE_TALK => false,
 			SMW_NS_CONCEPT => true,
 			SMW_NS_CONCEPT_TALK => false,
 		);

+		if ( !array_key_exists( 'smwgHistoricTypeNamespace', $GLOBALS ) ||
!$GLOBALS['smwgHistoricTypeNamespace'] ) {
+			unset( $smwNamespacesSettings[SMW_NS_TYPE] );
+			unset( $smwNamespacesSettings[SMW_NS_TYPE_TALK] );
+			unset( $this->globalVars['wgNamespacesWithSubpages'][SMW_NS_TYPE_TALK] );
+		}
+
```

PS: I'm traveling right now therefore I can only provide rudimentary
support via email.

Cheers

**Comment by KenanSulayman** [comment]
It works!

**Comment by KenanSulayman** [comment]
Given the fact that the LSD property has now correctly been displayed as a number, I'm trying executing `rebuildData.php`.

**Comment by mwjames** [comment]
Hi,

> This file is included in the autoload manifest generated by Composer. Is it
> guaranteed to notice the namespace changes in the configuration file?

It is but SMW_NS* are special because the ID can change with [0] hence
requires a computed assignment to ensure NS shifting can take place
before there are registered as constant [1].

Since we had to move the registration of the canonical NS to an
earlier entry point (due to some conflicts with extension.json
extensions that access those setting very early) we somehow have to do
extra legwork to keep them set.

[0] https://www.semantic-mediawiki.org/wiki/Help:$smwgNamespaceIndex
[1] http://php.net/manual/en/function.constant.php

Cheers

**Comment by KenanSulayman** [comment]
The rebuild operation has finished and I verified all data to be correct. Thanks, @kghbln and @mwjames!

🍺

**Comment by mwjames** [comment]
> The rebuild operation has finished and I verified all data to be correct. 

Thanks for the confirmation.

I added the propose change to 2.5 and back-ported it to 2.4.* (e3689e67). I'll leave to judgement on the timing for a 2.4 bug release to you guys.

**Comment by kghbln** [comment]
> I added the propose change to 2.5 and back-ported it to 2.4.* (e3689e6). I'll leave to judgement on the timing for a 2.4 bug release to you guys.

Thanks a lot. I guess we may wait for mid January and see if perhaps another backport comes in. In the meantime "2.4.x@dev" will allow to get the code in production.
