### ISSUE TITLE
PHP Fatal error:  Call to a member function getHash() on null

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2126]
### Setup and configuration

- MediaWiki 	1.28.0 (e92ed15) 22:16, 28. Nov. 2016
- PHP 	5.6.29-0+deb8u1 (apache2handler)
- MariaDB 	10.0.28-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0-alpha (fa1d402) 07:48, 19. Dez. 2016
- Semantic Compound Queries	1.0.0 (e38dbf5) 17:30, 15. Jun. 2016 patched with [pull 23](https://github.com/SemanticMediaWiki/SemanticCompoundQueries/pull/23)

### Issue
When trying to execute a compound query the following error is emitted:

`PHP Fatal error:  Call to a member function getHash() on null in /.../w/extensions/SemanticMediaWiki/includes/query/SMW_Query.php on line 451`

### Test page
I have set up an [example page on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Stores_and_restaurants).

**Comment by mwjames** [comment]
Hi,

Adding the following lines should help guard against a null (which
would only appear with 2.5).

```
@@ -441,12 +441,15 @@ class SMWQuery implements QueryContext {
 			return HashBuilder::createFromArray( $this->toArray() );
 		}

 		// For an optimal (less fragmentation) use of the cache, only use
 		// elements that directly influence the result list
-		$serialized = array();
+		if ( $this->description === null ) {
+			return '';
+		}

+		$serialized = array();
```

Cheers

**Comment by kghbln** [comment]
Thanks a lot @mwjames! This fixes the issue and SCQ is doing it's job. Thus created https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2127

**Comment by kghbln** [comment]
> Adding the following lines should help guard against a null (which would only appear with 2.5). 

Still have to note that the 2.4 branch of SMW is indeed not affected, at least that's what the field test resulted in. :)
