### ISSUE TITLE
Missing dependency while reporting errors

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#2147]
### Setup and configuration

- SMW version: 2.4.1
- MW version: 1.27.0, 1.28.0
- PHP version: HHVM 3.15-3.17
- DB (MySQL etc.): MariaDB 10.1.20

### Issue
An `{{#ask:}}` query (an incorrect one, with conditions not in the first place) crashes 
MW with the following messages in the error log. I have run `composer 
update --prefer source` in both MW and SMW directories, yet some method 
is missing. What may the missing dependency be and how to install it?

```
Fatal error: Uncaught Error: Call to undefined method 
__SystemLib\\Error::getProperty() in 
/var/www/wiki/w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php:229
Stack trace:
#0 
/var/www/wiki/w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(216): 
SMW\\AskParserFunction->createQueryProfile()
#1 
/var/www/wiki/w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(115): 
SMW\\AskParserFunction->doFetchResultsForRawParameters()
#2 
/var/www/wiki/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(277): 
SMW\\AskParserFunction->parse()
#3 /var/www/wiki/w/includes/parser/Parser.php(3817): 
Closure$SMW\\ParserFunctionFactory::newAskParserFunctionDefinition()
#4 /var/www/wiki/w/includes/parser/Parser.php(3552): 
Parser->callParserFunction()
#5 /var/www/wiki/w/includes/parser/Preprocessor_Hash.php(1075): 
Parser->braceSubstitution()
#6 
/var/www/wiki/w/extensions/ParserFunctions/ParserFunctions_body.php(137): 
PPFrame_Hash->expand()
#7 /var/www/wiki/w/includes/parser/Parser.php(3817): 
ExtParserFunctions::ifObj()
#8 /var/www/wiki/w/includes/parser/Parser.php(3552): 
Parser->callParserFunction()
#9 /var/www/wiki/w/includes/parser/Preprocessor_Hash.php(1075): 
Parser->braceSubstitution()
#10 /var/www/wiki/w/includes/parser/Parser.php(3694): PPFrame_Hash->expand()
#11 /var/www/wiki/w/includes/parser/Preprocessor_Hash.php(1075): 
Parser->braceSubstitution()
#12 /var/www/wiki/w/includes/parser/Parser.php(3366): PPFrame_Hash->expand()
#13 /var/www/wiki/w/includes/parser/Parser.php(1248): 
Parser->replaceVariables()
#14 /var/www/wiki/w/includes/parser/Parser.php(446): Parser->internalParse()
#15 /var/www/wiki/w/includes/content/WikitextContent.php(331): 
Parser->parse()
#16 /var/www/wiki/w/includes/content/AbstractContent.php(497): 
WikitextContent->fillParserOutput()
#17 /var/www/wiki/w/includes/poolcounter/PoolWorkArticleView.php(140): 
AbstractContent->getParserOutput()
#18 /var/www/wiki/w/includes/poolcounter/PoolCounterWork.php(123): 
PoolWorkArticleView->doWork()
#19 /var/www/wiki/w/includes/page/Article.php(666): 
PoolCounterWork->execute()
#20 /var/www/wiki/w/includes/actions/ViewAction.php(44): Article->view()
#21 /var/www/wiki/w/includes/MediaWiki.php(503): ViewAction->show()
#22 /var/www/wiki/w/includes/MediaWiki.php(288): MediaWiki->performAction()
#23 /var/www/wiki/w/includes/MediaWiki.php(745): MediaWiki->performRequest()
#24 /var/www/wiki/w/includes/MediaWiki.php(519): MediaWiki->main()
#25 /var/www/wiki/w/index.php(43): MediaWiki->run()
#26 {main}
```

**Comment by kghbln** [comment]
Thank you for reporting. Well, at least SMW should fail gracefully in such a situation.

**Comment by mwjames** [comment]
> Fatal error: Uncaught Error: Call to undefined method 
__SystemLib\\Error::getProperty() in 

`Error` is available in the `SMW` namespace [0, 1] with the error suggesting a `__SystemLib\\Error` but 2.4+ is referencing to the `SMW\Error`. I unable to say why your system omits the `SMW` namespace and replaces it with `__SystemLib` (maybe this is a HHVM issue).

> Missing dependency while reporting errors

There is nothing missing, your system uses `__SystemLib\\Error::getProperty()` but should use `SMW\\Error::getProperty()` instead and our tests including HHVM 3.6 does work as specified.

> Well, at least SMW should fail gracefully in such a situation.

Such issue would get caught during the tests but since it didn't, it means there is no apparent issue.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/src/Error.php#L3
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/includes/parserhooks/AskParserFunction.php#L226

**Comment by kghbln** [comment]
>> Well, at least SMW should fail gracefully in such a situation.

> Such issue would get caught during the tests but since it didn't, it means there is no apparent issue.

[This example](https://sandbox.semantic-mediawiki.org/wiki/Page_selection_after_display_parameters) also shows that SMW is actually failing gracefully with an error message rather than a fatal.

**Comment by kghbln** [comment]
I believe the cause of the issue was elaborated in detail and appears to not be caused by SMW itself. Please reopen if this assumption is incorrect and new details on how SMW is connected arise.

**Comment by mwjames** [comment]
> Fatal error: Uncaught Error: Call to undefined method
> __SystemLib\Error::getProperty() in

This is an HHVM issue, for details see [0].

[0] https://github.com/facebook/hhvm/issues/7741
