### ISSUE TITLE
Special properties are shown on special page "UnusedProperties"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2182]
### Setup and configuration

- MediaWiki 	1.28.0 (e92ed15) 22:16, 28 November 2016
- PHP 	5.6.29-0+deb8u1 (apache2handler)
- MariaDB 	10.0.29-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0-alpha (f2f6e83) 21:12, 15 January 2017

### Issue

Special properties are shown on special page "UnusedProperties" in case no value assignments form them exist. Since there is nothing to garden, the special property will always be defined, there is no big point for including them on this special page.

### Examples
link: [property "URL" on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Attribut:URL)
pic: 
![20170116_special properties on special unusedproperties 1](https://cloud.githubusercontent.com/assets/1104078/21985340/6f646f30-dbfa-11e6-8650-fdb5a374c767.png)

**Comment by mwjames** [comment]
Fixed with #2194.

**Comment by kghbln** [comment]
> Fixed with #2194.

Great!

**Comment by kghbln** [comment]
Now [documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASpecial%3AUnusedProperties&type=revision&diff=48784&oldid=48417) on wiki.

**Comment by kghbln** [comment]
[Looks really great now!](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Propri%C3%A9t%C3%A9s_inutilis%C3%A9es)

**Comment by mwjames** [comment]
> Looks really great now!

... and you got some extra cosmetics with #2204.
