### ISSUE TITLE
Cleared properties are shown on special page "UnusedProperties"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2183]
### Setup and configuration

- MediaWiki 	1.28.0 (e92ed15) 22:16, 28 November 2016
- PHP 	5.6.29-0+deb8u1 (apache2handler)
- MariaDB 	10.0.29-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0-alpha (f2f6e83) 21:12, 15 January 2017

### Issue

Cleared properties, i.e. properties with no explicit datatype assigned and with no existing value assignments are still shown on special page "UnusedProperties". Since there is nothing further to garden, there is no big point for including them on this special page.

Probably a solution like is is available for special page "Properties" (`$smwgPropertyZeroCountDisplay = false;` is a way out to avoid these artefacts being shown. Here a default should be "false" meaning not to show them.

Not showing them will avoid frustration "of seeing no progress" for good wiki gardeners.

### Examples
link: [property "Trocton" on sandbox](https://sandbox.semantic-mediawiki.org/w/index.php?title=Attribut:Troncon&action=edit&redlink=1)
pic:
![20170116_cleared properties on special unusedproperties 1](https://cloud.githubusercontent.com/assets/1104078/21985641/03b43a5c-dbfc-11e6-9a9d-1c2267b9f730.png)

**Comment by mwjames** [comment]
Fixed with #2200.

**Comment by kghbln** [comment]
> Fixed with #2200.

Thanks a ton!
