### ISSUE TITLE
Error message appears when accessing special page "Special:Browse"

### ISSUE THREAD

**Issue by pertineze** [SemanticMediaWiki/SemanticMediaWiki#2184]
### Setup and configuration

- SMW version: 2.5.0-alpha (1f2bb38)
- MW version:1.28.0
- PHP version: 5.5.9-1ubuntu4.20 (apache2handler)
- DB (MySQL etc.): MySQL 5.5.53-0ubuntu0.14.04.1

I've installed a local MediaWiki with the Semantic MediaWiki extension. When I access to special page "Special:Browse" I obtain the following error:

The subject validation returned with a "The wikipage input value is empty (e.g. <code>[[SomeProperty::]], [[]]</code>) and therefore it cannot be used as a name or as part of a query condition." error.

### Example
See [this issue on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir)

**Comment by kghbln** [comment]
Thanks a lot for reporting this issue. Indeed special page "Browse" should show an input field for specifing the page to browse instead of emitting the error message like it is done [here](https://www.semantic-mediawiki.org/wiki/Special:Browse). So for the time being you could append the page name as [shown in this URL](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/Main_Page) or alternativly access this special page via the link provided in the sidebar of every wiki page.

**Comment by kghbln** [comment]
@mwjames This appears to be a 2.5 regression since 2.4.x is working fine.

**Comment by mwjames** [comment]
Hi,

> @mwjames This appears to be a 2.5 regression since 2.4.x is working fine.

Good to know that people test before we release! Yes, indeed this is a
regression, the following should fix the issue and if not otherwise I
will create a PR during the weekend.

`SMW\MediaWiki\Specials\SpecialBrowse`

```
-		$isEmptyRequest = $query === null && $webRequest->getVal( 'article' ) === '';
+		$isEmptyRequest = $query === null && ( $webRequest->getVal(
'article' ) === '' || $webRequest->getVal( 'article' ) === null );
```

Cheers

**Comment by kghbln** [comment]
> Good to know that people test before we release!

That's I thought, too.

> the following should fix the issue

It does as the [field test](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir) shows. Thus #2186.

**Comment by kghbln** [comment]
Code changes were overwritten in the meantime but trust me the field test worked. :)

**Comment by pertineze** [comment]
Hi! I've instaled the version 2.4.5 of semantic mediawiki and the error doesn't appear but now, when I create a page with semantic properties, they are not registered in the special page "special:properties". I try to update the tables of the database with the order php5 maintenace/update.php but it does not work, any suggestion?

**Comment by kghbln** [comment]
> but now, when I create a page with semantic properties, they are not registered in the special page "special:properties". I try to update the tables of the database with the order php5 maintenace/update.php but it does not work, any suggestion?

Starting to mix issues is not advisable, so it is better to create an new report. However, probably [$smwgCacheUsage](https://www.semantic-mediawiki.org/wiki/Help:$smwgCacheUsage) kicks in on your wiki.
