### ISSUE TITLE
Accepting negative ISO dates

### ISSUE THREAD

**Issue by toniher** [SemanticMediaWiki/SemanticMediaWiki#2218]
### Setup and configuration

Tested in sandbox instance at: https://sandbox.semantic-mediawiki.org/wiki/Negative_date

### Issue

I was wondering whether could be possible to accept negative dates in a format such as:
-0341-01-01T00:00:00Z

I think this format is ISO 8601, isn't it? 

I actually retrieved this date from Wikidata: https://www.wikidata.org/wiki/Special:EntityData/Q43216.json So, it might be convenient to accept this format without further parsing.

**Comment by toniher** [comment]
I included a couple of additional examples, from the same source, which actually shows it's failing also replacing 'starting -' with a BC suffix. I imagine because of 00 month and day.

**Comment by mwjames** [comment]
> I included a couple of additional examples

:+1: 

> I think this format is ISO 8601, isn't it?

A quick look on the net [0, 1] shows that dates like `-0166-11-01T17:00:00+00:00` are accepted and represent `5th of November 167 BC at 5pm`, so yes negative dates are supported in ISO.

> I was wondering whether could be possible to accept negative dates in a format such as:
-0341-01-01T00:00:00Z

Just to clarify this isn't a regression (tested it on an old 1.9.2 which equally fails for the examples).

## Solution 

I have spent 10 min on issue and therefore did not extensively test this (but works for the cited examples). It requires extra integration tests [2] and to pass of our test suite.

```
* [[Date::-0641-01-01T00:00:00Z]]
* [[Date::-0642-00-00T00:00:00Z]]
* [[Date::0342-00-00T00:00:00Z BC]]
* [[Date::600 BC]]
* [[Date::0341-01-01T00:00:00Z BC]]
* [[Date::-0741-01-01T00:00:00Z BC]]
```
```
@@ -327,10 +327,27 @@ class SMWDITime extends SMWDataItem implements CalendarModel {
 
 		return new DateTime( $time );
 	}
 
 	/**
+	 * @since 2.5
+	 *
+	 * @param string $iso
+	 *
+	 * @return SMWDITime|false
+	 */
+	public static function newFromISO( $iso ) {
+
+		// 0341-01-01T00:00:00Z BC / -0341-01-01T00:00:00Z BC
+		if ( strpos( $iso, 'BC' ) !== false && substr( $iso, 0, 1 ) !== '-' ) {
+			$iso = '-' . $iso;
+		}
+
+		return self::newFromDateTime( new DateTime( $iso ) );
+	}
```
```
@@ -126,11 +126,18 @@ class SMWTimeValue extends SMWDataValue {
 		}
 		$this->m_dataitem = null;
 
 		$datecomponents = array();
 		$calendarmodel = $era = $hours = $minutes = $seconds = $microseconds = $timeoffset = $timezone = false;
-		if ( $this->isInterpretableAsYearOnly( $value ) ) {
+
+		if ( $this->isISO( $value ) ) {
+			try {
+				$this->m_dataitem = SMWDITime::newFromISO( $value );
+			} catch ( SMWDataItemException $e ) {
+				$this->addErrorMsg( array( 'smw-datavalue-time-invalid', $value, $e->getMessage() ) );
+			}
+		} elseif ( $this->isInterpretableAsYearOnly( $value ) ) {
 			try {
 				$this->m_dataitem = new SMWDITime( $this->getCalendarModel( null, $value, null, null ), $value );
 			} catch ( SMWDataItemException $e ) {
 				$this->addErrorMsg( array( 'smw-datavalue-time-invalid', $value, $e->getMessage() ) );
 			}
@@ -809,10 +816,15 @@ class SMWTimeValue extends SMWDataValue {
 
 	private function isInterpretableAsYearOnly( $value ) {
 		return strpos( $value, ' ' ) === false && is_numeric( strval( $value ) ) && ( strval( $value ) < 0 || strlen( $value ) < 6 );
 	}
 
+	private function isISO( $value ) {
+		// 0341-01-01T00:00:00Z BC / -0341-01-01T00:00:00Z BC
+		return ( substr( $value, 0, 1 ) === '-' && substr( $value, 11, 1 ) === 'T' ) || ( ( strlen( $value ) > 4 && substr( $value, 10, 1 ) === 'T' ) );
+	}
+
```

[0] http://yoranbrondsema.com/iso8601-negative-years-ruby-javascript/
[1] https://phabricator.wikimedia.org/T93256
[2] https://www.semantic-mediawiki.org/wiki/Help:Integration_tests

**Comment by toniher** [comment]
Hi @mwjames, I'll try your patch and I'll check documentation if I can manage to create a test for this. Thanks!

**Comment by toniher** [comment]
Testing the code above (updating in sandbox) I see that dates are interpreted according to the Julian Calendar, but if they are ISO, I think they should follow the Gregorian proleptic by definition. I'll play a bit more with it.

**Comment by toniher** [comment]
Not strictly related, I noticed in this test:
https://sandbox.semantic-mediawiki.org/wiki/Zero_year
and RDF output:
https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Export_RDF/Zero_year&syntax=rdf

that RDF dates would seem to be in ISO 8601 format. However I would expect that '7 Jan 2 BC, 06:25:12' would be '-0001-01-05T06:25:10Z' rather than '-0003-01-05T06:25:10Z'...

**Comment by toniher** [comment]
@mwjames, is it OK I create a separate issue for this RDF problem?

**Comment by mwjames** [comment]
>  is it OK I create a separate issue for this RDF problem?

Yes, if possible issues should be separated to make commenting or testing easier.

**Comment by toniher** [comment]
Created at #2233 I will study that first!

**Comment by kghbln** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
