### ISSUE TITLE
Class 'SMW\Parser\linksProcessor' not found

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#2223]
### Setup and configuration

- SMW version: 2.5.0-alpha (886138d) 16:47, 30 January 2017
- MW version: 1.29.0-alpha (ec84fa3) 20:04, 3 February 2017
- PHP version: 7.0.13-0ubuntu0.16.04.1 (apache2handler)
- DB: MySQL 5.7.17-0ubuntu0.16.04.1

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
[6e49e811e0af67948049790a] /w/index.php/Special:SearchByProperty/:Alternate-20name/Aarschot Error from line 266 of /home/stephan/website/mw/extensions/SemanticMediaWiki/src/InTextAnnotationParser.php: Class 'SMW\Parser\linksProcessor' not found

Backtrace:

#0 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/Parser/Obfuscator.php(108): SMW\InTextAnnotationParser::getRegexpPattern(boolean)
#1 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/InTextAnnotationParser.php(209): SMW\Parser\Obfuscator::removeAnnotation(string)
#2 /home/stephan/website/mw/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(205): SMW\InTextAnnotationParser::removeAnnotation(string)
#3 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SearchByProperty/QueryResultLookup.php(139): SMWResultArray->getNextDataValue()
#4 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SearchByProperty/PageBuilder.php(189): SMW\MediaWiki\Specials\SearchByProperty\QueryResultLookup->doQueryForNearbyResults(SMW\MediaWiki\Specials\SearchByProperty\PageRequestOptions, integer, boolean)
#5 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SearchByProperty/PageBuilder.php(161): SMW\MediaWiki\Specials\SearchByProperty\PageBuilder->getNearbyResults(array, integer)
#6 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SearchByProperty/PageBuilder.php(78): SMW\MediaWiki\Specials\SearchByProperty\PageBuilder->getResultHtml()
#7 /home/stephan/website/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialSearchByProperty.php(72): SMW\MediaWiki\Specials\SearchByProperty\PageBuilder->getHtml()
#8 /home/stephan/website/mw/includes/specialpage/SpecialPage.php(522): SMW\MediaWiki\Specials\SpecialSearchByProperty->execute(string)
#9 /home/stephan/website/mw/includes/specialpage/SpecialPageFactory.php(576): SpecialPage->run(string)
#10 /home/stephan/website/mw/includes/MediaWiki.php(284): SpecialPageFactory::executePath(Title, RequestContext)
#11 /home/stephan/website/mw/includes/MediaWiki.php(859): MediaWiki->performRequest()
#12 /home/stephan/website/mw/includes/MediaWiki.php(520): MediaWiki->main()
#13 /home/stephan/website/mw/index.php(43): MediaWiki->run()
#14 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
see e.g. https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Recherche_par_propri%C3%A9t%C3%A9/:Age/10

**Comment by JeroenDeDauw** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2224

**Comment by mwjames** [comment]
> [6e49e811e0af67948049790a] /w/index.php/Special:SearchByProperty/:Alternate-20name/Aarschot Error from line 266 of /home/stephan/website/mw/extensions/SemanticMediaWiki/src/InTextAnnotationParser.php: Class 'SMW\Parser\linksProcessor' not found

I'm sorry for the inconvenience and while I try to be careful when refactoring classes (#2214) those things will continue to happen until our test environment is failing in those cases. 

With ~4300 tests at bay, none of them caught the issue (and it should have, if not at all by this [0] one), anyway thanks for testing and saving us from some embarrassing moments.

> #2224

Thanks

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/s-0010.json

**Comment by mwjames** [comment]
> Steps to reproduce the observation (recommendation is to use the sandbox):
see e.g. https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Recherche_par_propri%C3%A9t%C3%A9/:Age/10

Fixed for the cited example.

**Comment by s7eph4n** [comment]
That was fast. Thanks!
