### ISSUE TITLE
Properties and Value text boxes in the "Search by property" interpret hexadecimal codes when preceeded by -

### ISSUE THREAD

**Issue by xavier-atero** [SemanticMediaWiki/SemanticMediaWiki#2257]
### Setup and configuration

- SMW version: 2.4.5
- MW version: 1.27.1
- PHP version: 7.0.13-0ubuntu0.16.04.1
- DB (MySQL etc.): 5.7.17-0ubuntu0.16.04.1

### Issue

Properties and Value text boxes in the "Search by property" interpret hexadecimal codes and transform them into the equivalent ascii character when preceeded by -

Steps to reproduce the observation:

1. Go to Search by property page: https://www.semantic-mediawiki.org/w/index.php?title=Special%3ASearchByProperty
2. Enter the following values:
   - Property: Test-51
   - Value: Test-6D
3. Click on Find Results button

https://www.semantic-mediawiki.org/w/index.php?title=Special%3ASearchByProperty&property=Test-51&value=Test-6D

Expected result:
   Text boxes containing:
   - Property: Test-51
   - Value: Test-6D

Actual result:
   Text boxes contain:
   - Property: TestQ
   - Value: Testm

**Comment by kghbln** [comment]
Thanks for reporting!

**Comment by mwjames** [comment]
Hi,

> https://www.semantic-mediawiki.org/w/index.php?title=Special%3ASearchByProperty&property=Test-51&value=Test-6D
>
> Expected result:
>    Text boxes containing:
>    - Property: Test-51
>

I'm pretty sure this is fixed and I would suggest you use the sandbox
for verification. I don't have an issue number at hand but somewhere
in the 2.5 stack it got addressed together with some extra tests.

Cheers

**Comment by kghbln** [comment]
> I'm pretty sure this is fixed

Indeed it is. Now that you mention it I remember we had this before. @jongfeli reported this with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1744 and you fixed it with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2005

--> [field test on sandbox](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARecherche+par+propri%C3%A9t%C3%A9&property=Test-51&value=Test-6D)
