### ISSUE TITLE
Support for ElasticSearch

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2274]
There are several implementations [0, 1] that use SOLR as basis for a better retrieval system in combination with SMW but maybe it is time that SMW-core provides a lean interface that allows to replicate its data into `ElasticSearch` more easily and may build a wrapper around ES DSL [2] to seamlessly integrate searches from and to `ElasticSearch`.

## Questions

* Would it make sense for SMW to support `ElasticSearch`?
* Any reason for not supporting `ElasticSearch` natively?
* What benefits would SMW gain by supporting `ElasticSearch`?
* Why `ElasticSearch`? Are there any other search engines that are more preferable (such as SOLR/Lucene)?

[0] https://packagist.org/packages/diqa/enhanced-retrieval
[1] https://www.mediawiki.org/wiki/Extension:SolrStore
[2] https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html

**Comment by kghbln** [comment]
The current situation is a bit split between ElasticSearch and SOLR/Lucene. While MediaWiki as such integrates with ElasticSearch, all advanced implementations involving SMW which require more complexity use SOLR/Lucene [3,4].

The rationale of WMF for choosing ElasticSearch over SOLR/Lucene is described here: [5].

They may however be right about SOLR/Lucene being more painful so I'd opt for ElasticSearch. If other want to add to this a separate extension will be needed as it is already done now.

[3] [ExtendedSearch - BlueSpice](https://github.com/wikimedia/mediawiki-extensions-BlueSpiceExtensions/tree/master/ExtendedSearch)
[4] [SolrStore - Gesis](https://www.mediawiki.org/wiki/Extension:SolrStore)
[5] [Search infrastructure maintenance and overhaul - rationale](https://www.mediawiki.org/wiki/Search/Old#Rationale)

**Comment by jaideraf** [comment]
> I'd opt for ElasticSearch.

Me too. Firstly, because we can have MediaWiki wikis using [Cirrus](https://www.mediawiki.org/wiki/Extension:CirrusSearch) (which requires ElasticSearch)  and SMW together (if SMW would integrate with Solr, one would have to install MW, SMW, ElasticSearch AND Solr, which is not desired at all). 

So, the challenge (and feature) would be to use ElasticSearch for both MW and SMW. 
A faceted search (customized with SMW properties) would be great like in these [images here](https://www.mediawiki.org/wiki/Extension:ExtendedSearch).

As [an example](
http://wikincat.org/wiki/Wikis_(Ciência_da_computação)?uselang=en) of what is already done by me is the use of [Filtered format](https://www.semantic-mediawiki.org/wiki/Help:Filtered_format) from SRF.

I think, as we have a Semantic Scribunto extension, maybe we could have a Semantic Cirrus extension.

Secondly, ElasticSearch seems to be easier to install than Solr. :wink:

**Comment by kghbln** [comment]
Update: [BlueSpice will go elastic](https://blog.bluespice.com/2017/02/23/coming-soon-with-bluespice-3-a-look-at-the-road-map/) next year. This was the only major distribution working with SOLR. So if SMW was to support a search engine natively it should be ElasticSearch.

**Comment by gesinn-it** [comment]
+1 for Elastic. We too use it in our [semantic::core distributions](https://sourceforge.net/projects/semantic-core-go).

**Comment by mwjames** [comment]
Someone ask me on a private channel to share some technical insights on the integration with ES since it was recorded that some users think that replacing the `QueryEngine` with ES should be a "piece of cake" while dumping the `SQLStore` entirely.

## Mappings, types, and serialization

Serializing (and hereby deserialzing) the `SemanticData` as JSON isn't an issue and can be done without much technical effort. Dumping those blob data into ES (I tested this once) isn't a big effort but it is hardly be sufficient because in order to use the ES DSL [0] you are required to create index mappings [1] and typed fields.

As for mappings, ES defines it as "... the process of defining how a document, and the fields it contains, are stored and indexed." [2]

While adding new fields (properties) with type definition can be done easily using the *dynamic mapping* approach, changing an existing type will require reindexing [3] the __entire__ dataset.

Changing a property type, say for example from `[[Has type::Page]]` to `[[Has type::Text]]` requires to run the `rebuildData` from scratch.

## ES DSL + #ask

![image](https://user-images.githubusercontent.com/1245473/31304139-5d35ede4-ab56-11e7-8ba6-a66abc1de57c.png)

To provide the same interface you would have to write a #ask `Description` mapper that would convert the `Description` object into an ES DSL equivalent.

Also, when writing such mapper, parity should be available for all expressions currently supported by the `SQLStore` and `SPARQLStore`.

### Hierarchies and property paths 

As far as I remember (I'd may be mistaken, and it has been a while since I looked at this) it is not possible to build hierarchies or property paths while relying solely on ES.

[0] https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html 
[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
[3] https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_updating_existing_mappings

**Comment by rglasnap** [comment]
I'm currently using Sphinx for the MW+SMW wiki that I administer; however, I would happily switch over to ElasticSearch if there was SMW integration with the search engine so my users could find what they need easier. 

I get a lot of complaints about search, but there's not usually a lot I can do since the technical groups I support use similar terminology (and they're looking for their documentation, not someone elses).

**Comment by m-art-in** [comment]
Any progress about SMW and ES? I just started with elastica end cirrus, hope to combine these extension with SMW, too. Maybe SemanticDrilldown could also enrich the ES-index?

**Comment by johnss** [comment]
It seems that ElasticSearch has some kind of native graph capability

https://www.elastic.co/guide/en/x-pack/current/index.html
Old version
https://www.elastic.co/guide/en/graph/current/graph-api-rest.html

ES is much more popular than any triple store jena, virtuosso, etc and more popular than any graph database like neo4j.

If have any issue with it, and post a question on stackoverflow or other QnA sites, you likely will get more answer from the community.

Given the popularity of ES, So I think ES support is a must have feature.

**Comment by agcunha** [comment]
@rglasnap the complaints that you've had is about MW default search? It's suposed to be the same search that Wikipedia uses. I defend the idea to decouple MW+SMW architecture from the search engines architecture (like the web does). I mean: MW as human knowledge base, SMW to help creating machine knowledge bases(graph) and a semantic search (like google) to index, ocr, ner, nlp, and IA assistants. The last topic, solr or elastic helps accomplish.

**Comment by mwjames** [comment]
I'm trying to give a short answer to https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3054#issuecomment-379897341:

> I'm an enterprise user, interested in continue using sparql store for graphs. AWS launches Neptune that will be a nice, fast and robust option for creating knowledge bases.

I have no specific knowledge about AWS Neptune therefore I cannot comment but form a project point of view, SMW will remain dedicated to support connectors to various SPARQL/triple store vendors.

> What is the motivation to use Elastic in the architecture of SMW? 

As mentioned before the `SQLStore` is a compact solution for users with limited technical know-how or requirements and runs out of the box without any third-party software.

The truth is that we have very few (or that we know of) that are willing or knowledgeable in maintaining a triple store [a.1] which means we need a solution for enterprise/wiki-farm users that is easily adaptable without increasing the technical cost for those user groups.

We have learned that we need to provide a different solution because running a dedicated triple store seems to incur technical challenges that most users are not willing to take. Selecting ES became an obvious choice since it is very likely that an enterprise/wiki-farm user has been running an instance [0, 1] or has an employee with some experience in that particular area.

From a technical perspective, the tree structure (leaf and nodes) is a good fit for SMW's data structure and allows us to combine structured and full-text searches within a single technical framework. Most triple stores can integrate a full-text engine [2, 3, 4, 5, 6] but those solutions require technical knowledge and effort that most users are unlikely to have or in need to acquire.

Elasticsearch (or better Lucene) has an excellent inverted index which makes structured (term) searches very fast compared to a pure SQL solution especially when you combine various conjunctive/disjunctive conditions and sorting. On top you have a tool that can handle full-text searches in a blink of an eye without making your DB engine call 911.

For example, I run a test wiki with ~50K pages including ~1.5M full-text rows (MariaDB) where when restricted queries are executed response times are fine but as soon as those query conditions get elevated (AND + OR + ... ) no matter how hard you try to create an appropriate DB index the database will start to cough blood not because the SELECT itself is slow but because of the requirement to SORT (ORDER BY) the results. The sort makes the DB choose a semi-optimized query plan and ruins any acceptable response time. On the matter of text searches and SPARQL running regex queries is not very efficient either and doesn't scale.

I haven't seen any discussion about advanced topics like OWL reasoner and inference scheme in connection with SMW recently and even if we did, they cannot be combined directly with or without Elasticsearch (maybe you could by codifying the rules and use percolate queries but that's a different story) and is not the objective for most users who want a fast "machine" to match entities.

> knowledge bases. In my point of view, key/value stores, like lucene used in Elastic or Solr, aren't the best architecture for knowledge representation.

The question is not so much about knowledge representation in connection with ES (this is done in SMW) but what sort of application users are interested in, and I'd say we have a few users that are clear about the concept of OWL, RDF, etc. and some with less ambitions in regards to modeling and reasoning including SPARQL and a graph database.

It is all about choices and so far Elasticsearch and the ElasticStore have not created any reason for questioning that direction.

[a.1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1690#issuecomment-356353790
[0] https://www.elastic.co/use-cases
[1] https://globenewswire.com/news-release/2017/03/07/933125/0/en/Elastic-Reaches-100-Million-Downloads-for-the-Elastic-Stack.html
[2] http://ad-publications.informatik.uni-freiburg.de/CIKM_broindex_BB_2013.pdf
[3] http://docs.openlinksw.com/virtuoso/rdfsparqlrulefulltext/
[4] https://wiki.blazegraph.com/wiki/index.php/FullTextSearch
[5] https://pdfs.semanticscholar.org/681a/4ce9f4251a31dda3764b739818dc4d49ea4c.pdf
[6] https://jena.apache.org/documentation/query/text-query.html

**Comment by krabina** [comment]
I am not a search expert and appreaciate everything that makes it easier to integrate better search options into SMW powered MediaWikis.
Have never tried it myself, but want to make sure you guys know about: https://www.opensemanticsearch.org/

**Comment by mwjames** [comment]
Experimental support has been merged. refs #2274
