### ISSUE TITLE
update 2.4.5 -> 2.4.6 -> fatal error

### ISSUE THREAD

**Issue by ukcb** [SemanticMediaWiki/SemanticMediaWiki#2276]
### Setup and configuration

- SMW version: 2.4.6
- MW version: 1.27.1
- PHP version: 5.6.30-0+deb8u1 (debian/stable)
- DB (MySQL etc.): 5.5.54

### Issue

Version 2.4.5 worked perfectly, after the update to 2.4.6 nothing more

Fatal error: Class 'SMW\SQLStore\TableBuilder\TemporaryTableBuilder' not found in /var/www/mediawiki/htdocs/public/vendor/extensions/SemanticMediaWiki/src/SQLStore/QueryEngineFactory.php on line 105

**Comment by ukcb** [comment]
After reboot it does again! Sorry, for the panic...

**Comment by kghbln** [comment]
Rebooting is an interesting solution. Glad it worked out! Anyhow 2.4.6 only contained https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2235 so another solution would have been to revert back to 2.4.5 in case you do not enforce GTID consistency checks with your MySQL backend.

**Comment by ukcb** [comment]
On two other installations with the same configuration, this update ran without errors.
My setup is default with two minor changes:

enableSemantics('xxxx');
$smwgPageSpecialProperties = array_merge(
  $smwgPageSpecialProperties, array( '_CDAT', '_NEWP', '_LEDT' )
);

No idea what was going on, right now everything works. Maybe it was a temporary issue with my memcached configuration. I dont know.
