### ISSUE TITLE
Status of page being `Is translated`?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2300]
@Nikerabbit Is it possible that the `Translate` extension can set a page props [0] `ParserOutput::setProperty` property of pages that are (have been) translated via the extension?

It would helpful to other processes or extensions (in this case SMW) to distinguish "real" content from translated content (as a copy of the original) during parsing. If the page props is set then the `ParserAfterTidy` hook can be used to set a SMW property of its own to reflect the status of such page.

[0] https://www.mediawiki.org/wiki/Manual:Page_props_table

**Comment by Nikerabbit** [comment]
Are you speaking about [translatable pages](https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_administration) or more general thing?

**Comment by Nikerabbit** [comment]
Are you speaking about [translatable pages](https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_administration) or more general thing?

**Comment by mwjames** [comment]
Hi,

> Are you speaking about [translatable
> pages]

When using the Translate extension as shown in case of [0], subsequent
pages added by the extension contain translated content [1] and for
those translated pages [1], the page props property should be set
during processing.

In general, translated pages are blocked from editing "This page
cannot be updated manually. This page is a translation of the page..."
but checking the protection status during the edit/translation process
isn't viable as the protection is only set after the update which is
most likely to late for standard hooks.

If the Translate extension considers to set a page props property for
pages like [1] early on (as I'm unfamiliar with the extension, I'm
unable to pinpoint to the earliest possible opportunity) then SMW
would be able to use that information in standard parser hooks and
filter it before the update event finalizes.

PS: Using a constant via `ParserOutput::setProperty(
Translate::TRANSLATED_CONTENT) `/`ParserOutput::getProperty(
Translate::TRANSLATED_CONTENT)` (or similar) as identifier would help
reduce dependencies on the Translate extension's internal state.

[0] https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.4.5_released
[1] https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.4.5_released/el

Cheers

**Comment by Nikerabbit** [comment]
So basically you are asking something similar to the wgTranslatePageTranslation **JavaScript** variable.

On quick look, I think I could amend the existing code that is using hook `ParserBeforeStrip` to add the property. Is that early enough?

**Comment by mwjames** [comment]
> I think I could amend the existing code that is using hook ParserBeforeStrip to add the property. Is that early enough?

That should work as it is called before the `ParserAfterTidy` hook.

**Comment by Nikerabbit** [comment]
I was reading the documentation for setProperty:
```
         * @note Do not use setProperty() to set a property which is only used
         * in a context where the ParserOutput object itself is already available,
         * for example a normal page view. There is no need to save such a property
         * in the database since the text is already parsed. You can just hook
         * OutputPageParserOutput and get your data out of the ParserOutput object.
         *
         * If you are writing an extension where you want to set a property in the
         * parser which is used by an OutputPageParserOutput hook, you have to
         * associate the extension data directly with the ParserOutput object.
         * Since MediaWiki 1.21, you can use setExtensionData() to do this:
         *
         * @par Example:
         * @code
         *    $parser->getOutput()->setExtensionData( 'my_ext_foo', '...' );
         * @endcode
         *
         * And then later, in OutputPageParserOutput or similar:
         *
         * @par Example:
         * @code
         *    $output->getExtensionData( 'my_ext_foo' );
         * @endcode
```

Would `setExtensionData` (i.e. skipping the database) be sufficient for SMW, or would SMW need to check this during page views?

**Comment by mwjames** [comment]
> Would setExtensionData (i.e. skipping the database) be sufficient for SMW, or would SMW need to check this during page views?

Yes, this should work and an instead of just a boolean value, using the `code` should provide a better queryable representation.

## Translate extension

```
@@ -47,19 +47,22 @@ class PageTranslationHooks {
 		$page = TranslatablePage::isTranslationPage( $title );
 		if ( !$page ) {
 			return true;
 		}
 
 		self::$renderingContext = true;
 		list( , $code ) = TranslateUtils::figureMessage( $title->getText() );
 		$name = $page->getPageDisplayTitle( $code );
 		if ( $name ) {
 			$name = $parser->recursivePreprocess( $name );
 			$parser->getOutput()->setDisplayTitle( $name );
 		}
 		self::$renderingContext = false;
 
+		$parser->getOutput()->setExtensionData( 'ext-translate-code', $code );
+
```

## Semantic MediaWiki

```
@@ -133,10 +133,15 @@ class ParserAfterTidy extends HookHandler {
 			$propertyAnnotator,
 			$this->parser->getOutput()->getProperty( 'displaytitle' ),
 			$this->parser->getDefaultSort()
 		);
 
+		$propertyAnnotator = $propertyAnnotatorFactory->newTranslatedContentLanguagePropertyAnnotator(
+			$propertyAnnotator,
+			$this->parser->getOutput()->getExtensionData( 'ext-translate-code' )
+		);
+
```
```
@@ -9,10 +9,11 @@ use SMW\PropertyAnnotators\MandatoryTypePropertyAnnotator;
 use SMW\PropertyAnnotators\NullPropertyAnnotator;
 use SMW\PropertyAnnotators\PredefinedPropertyAnnotator;
 use SMW\PropertyAnnotators\RedirectPropertyAnnotator;
 use SMW\PropertyAnnotators\SortKeyPropertyAnnotator;
 use SMW\PropertyAnnotators\EditProtectedPropertyAnnotator;
+use SMW\PropertyAnnotators\TranslatedContentLanguagePropertyAnnotator;
 use SMW\Store;
 use Title;
 
 /**
  * @license GNU GPL v2+
@@ -130,10 +131,28 @@ class PropertyAnnotatorFactory {
 
 		return $displayTitlePropertyAnnotator;
 	}
 
 	/**
+	 * @since 3.0
+	 *
+	 * @param SemanticData $semanticData
+	 * @param string $translatedContentLanguage
+	 *
+	 * @return TranslatedContentLanguagePropertyAnnotator
+	 */
+	public function newTranslatedContentLanguagePropertyAnnotator( PropertyAnnotator $propertyAnnotator, $translatedContentLanguage = '' ) {
+
+		$translatedContentLanguagePropertyAnnotator = new TranslatedContentLanguagePropertyAnnotator(
+			$propertyAnnotator,
+			$translatedContentLanguage
+		);
+
+		return $translatedContentLanguagePropertyAnnotator;
+	}
```
```
new file mode 100644
@@ -0,0 +1,52 @@
+<?php
+
+namespace SMW\PropertyAnnotators;
+
+use SMW\PropertyAnnotator;
+
+/**
+ * @license GNU GPL v2+
+ * @since 3.0
+ *
+ * @author mwjames
+ */
+class TranslatedContentLanguagePropertyAnnotator extends PropertyAnnotatorDecorator {
+
+	/**
+	 * @var string
+	 */
+	private $translatedContentLanguage;
+
+	/**
+	 * @since 3.0
+	 *
+	 * @param PropertyAnnotator $propertyAnnotator
+	 * @param string $translatedContentLanguage
+	 */
+	public function __construct( PropertyAnnotator $propertyAnnotator, $translatedContentLanguage = '' ) {
+		parent::__construct( $propertyAnnotator );
+		$this->translatedContentLanguage = $translatedContentLanguage;
+	}
+
+	protected function addPropertyValues() {
+
+		if ( $this->translatedContentLanguage === '' || $this->translatedContentLanguage === null ) {
+			return;
+		}
+
+		$dataItem = $this->dataItemFactory->newDIBlob(
+			$this->translatedContentLanguage
+		);
+
+		$this->getSemanticData()->addPropertyObjectValue(
+			$this->dataItemFactory->newDIProperty( '_TCLC' ),
+			$dataItem
+		);
+	}
+
+}
```
```
@@ -479,10 +479,11 @@ class PropertyRegistry {
 			'_ASKPA' => array( '_cod', true, false ), // "Query parameters"
 			'_MEDIA' => array( '_txt', true, false ), // "has media type"
 			'_MIME'  => array( '_txt', true, false ), // "has mime type"
 			'_PREC'  => array( '_num', true, true ), // "Display precision of"
 			'_LCODE' => array( '__lcode', true, true ), // "Language code"
+			'_TCLC' => array( '__lcode', true, false ), // "Translated content language"
```

**Comment by mwjames** [comment]
Code examples have been provided, if and when this will be available is unknown. Currently there is no actionable task for the project to handle.

If somehow this feature becomes available the task can be reopened, moving this to [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4

**Comment by Nikerabbit** [comment]
https://gerrit.wikimedia.org/r/387548 has been merged. I'll leave it to you to decide how to use it.

**Comment by kghbln** [comment]
@Nikerabbit Thanks a lot for authoring and moving the code in!

@mwjames Since the current Translate extension is no longer compatible with MW 1.27 I will not be able to use any improvement on smw.o prior to end of June 2018 (this is when I will upgrade the wiki to 1.31)

**Comment by mwjames** [comment]
> https://gerrit.wikimedia.org/r/387548 has been merged. I'll leave it to you to decide how to use it.

Much appreciated.
