### ISSUE TITLE
Commit 10k better be good! :)

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2307]
![better-mawk-it-good](https://cloud.githubusercontent.com/assets/146040/23583866/5db96ec2-0150-11e7-92af-964d1ca039a0.png)

**Comment by mwjames** [comment]
If you prepare a PR with some non-sense 10000 comment, I will gladly merge it before any other!

**Comment by mwjames** [comment]
![image](https://cloud.githubusercontent.com/assets/1245473/23584493/cc3127cc-01a6-11e7-96ed-abb18cbf538d.png)

**Comment by kghbln** [comment]
@JeroenDeDauw What happened to the tweet and the mail to the mailing-lists?

**Comment by JeroenDeDauw** [comment]
I figured that fell into the hands of the Department of Fluff :)

**Comment by kghbln** [comment]
So now we have a tweet by you and a mail by me. :)
