### ISSUE TITLE
rebuildData.php fails on MW 1.29.0-wmf.9

### ISSUE THREAD

**Issue by dm-mitre** [SemanticMediaWiki/SemanticMediaWiki#2319]
### Setup and configuration

- SMW version: 2.4.6
- MW version: 1.29.0-wmf.9
- PHP version: 5.6.30
- DB: MySQL 5.7.17

### Issue

MW 1.29.0 removes the deprecated function Revision::getText() which is used in includes/ContentParser.php on line 196. This causes rebuildData.php to fail with:
```
Fatal error: Call to undefined method Revision::getText() in /var/www/html/extensions/SemanticMediaWiki/includes/ContentParser.php on line 196
```

Steps to reproduce:
- On 1.29.0-wmf.9 run rebuildData.php in otherwise vanilla wiki

MediaWiki commit: https://github.com/wikimedia/mediawiki/commit/0958f53373671e212f01bf3987e405c6121a2d70
related bug in FlaggedRevs: https://phabricator.wikimedia.org/T156310

**Comment by kghbln** [comment]
Thanks for reporting! This is basically a subtask of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2079 and the transgressing code is also still in [2.5.0-rc.1](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/ContentParser.php#L196)

@mwjames I guess it will be nice to tackle this for 2.5.0

**Comment by mwjames** [comment]
Hi,

> SMW version: 2.4.6
> @mwjames I guess it will be nice to tackle this for 2.5.0

The 2.5 branch is working and tested with the available 1.29-alpha and
#2038 is containing some comments in regards to deprecated functions
and fixes for 1.28+.

I recall that the compatibility matrix has specified the limitations
of the 2.4.x branch which becomes even more apparent now that
functions has been removed from MediaWiki.

> MW version: 1.29.0-wmf.9

While 1.29-alpha is tested to the point of availability, it needs to
be seen whether this remains so for an actually MW release with
observations that functionality were removed [0] without adding
deprecation notices or consulting extension developers first.

Furthermore, several phab thickets relating to 1.29 remain open (for
at least two month) without a response from WMF developers which means
that we can only confirm 1.28 to work as expected.

> of #2079 and the transgressing code is also still in 2.5.0-rc.1

There is a check to make it work before and after 1.28+.

PS: Now with 2.5 in the release process, 2.4.x is no longer regarded
as maintainable release (please see the drafted release process
notes).

PSS: If someone wants to check in backports then s(he) is free to do
so and as long as the tests pass we will merge them but it should be
noted that it is unlikely that a core developer will provide
verification or manually testing for these backportes (given the
unmaintained release branch status).

[0] https://phabricator.wikimedia.org/T155625

Cheers

**Comment by kghbln** [comment]
> Now with 2.5 in the release process, 2.4.x is no longer regarded as maintainable release

My comment was only about fluffing 2.5.x and not 2.4.x. That's why I added the 2.5.0 milestone.

> The 2.5 branch is working and tested with the available 1.29-alpha

master is actually failing automated tests but configured as allowed failure.

> The 2.5 branch is working and tested with the available 1.29-alpha and #2038 is containing some comments in regards to deprecated functions and fixes for 1.28+.

So this has to be applied to make 2.5 work again. Since 1.29 is just 9 weeks away ...

**Comment by mwjames** [comment]
Hi,

> master is actually failing automated tests but configured as allowed
> failure

One reason is because of HHVM (a different tickets contains some
comments on it) next to the comments about the open phab tickets.

> So this has to be applied to make 2.5 work again. Since 1.29 is just 9 weeks
> away ...

It has been applied to make it work with 1.28+ and is the reason why
2.4.x is limit to 1.27.

Cheers

**Comment by kghbln** [comment]
Hmm, 2.5.x contains the very same line as 2.4.x so I would guess that 2.5.x should fail alike. Or do you mean that a fix will only be done after 1.29 was released?

**Comment by mwjames** [comment]
Hi,

> Hmm, 2.5.x contains the very same line as 2.4.x so I would guess that 2.5.x
> should fail alike. Or do you mean that a fix will only be done after 1.29
> was released?

See my comments in #2038. (Unfortunately the user missed to report a
full stack trance then you would become clear the `forceToUseParser`
usage)

Cheers

**Comment by kghbln** [comment]
You lost me completely. I will install a MW 1.29 and try to get a stacktrace for this issue. However I will not manage prior to the 2.5.0 release.

**Comment by mwjames** [comment]
Hi,

> You lost me completely. I will install a MW 1.29 and try to get a stacktrace
> for this issue. However I will not manage prior to the 2.5.0 release.

2.4.x is not made to support 1.27+ (as of now), 2.5.x is expected to
work with 1.28 and 1.29-alpha.

The compatibility matrix should note that 2.5 is expected to support
1.23 -> 1.29 (at best).

Cheers

**Comment by kghbln** [comment]
> 2.4.x is not made to support 1.27+ (as of now), 2.5.x is expected to work with 1.28 and 1.29-alpha.

There was never any doubt about this. My point was that the code failing for 2.4.6 is identical to the code we still have in 2.5. However I may still have misunderstood: So there may be other changes done already in 2.5 which make this identical code not to fail. I guess this is what your are trying to get into my head. :)

**Comment by mwjames** [comment]
Hi,

> So there may be other changes done already in 2.5 which
> make this identical code not to fail. I guess this is what your are trying
> to get into my head. :)

+1

PS: The code is adjusted on a different end (see #2038) to avoid
messing with the existing to code which would require additional labor
work (reworking tests etc.).

Cheers

**Comment by kghbln** [comment]
Cool, I am back in business. This was indeed not one of my finest hours I suppose. :|

So one thing @dm-mitre could do is test the release candidate of 2.5 to verify in a field test that there is no issue for 2.5

**Comment by dm-mitre** [comment]
@kghbln tested 2.5.0-rc.1 with 1.29.0-wmf.9 and I did not encounter any issues

**Comment by kghbln** [comment]
@dm-mitre Thanks a lot for testing and confirming. 2.5.0 is short ahead. Stay tuned!
