### ISSUE TITLE
Geographic Coordinates get truncated

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#2320]
When you assign a property of type Geographic Coordinate as decimal, this is supported by SMW. It is internally by default transferred into degrees, minutes and seconds. The problem now is that if the seconds are converted that include commas, they get truncated.

An example:
Assigning the coordinates 48,19751582569160, 16,26471409412160
results in 48° 11' 51", 16° 15' 52"
but should be (at least): 48° 11'  51.054'', 16° 15'  52.97''

This results in maps that might work on a large scale, but once you zoom in, you can see that it is not as exactly as it was in the original coordinates. And it results in SMW changing values that are input into it whicht it never should do...

Reproduced at: 
https://sandbox.semantic-mediawiki.org/wiki/Vienna

**Comment by krabina** [comment]
see e. g here http://www.earthpoint.us/Convert.aspx

Latitude 48.19751582569160, Longitude	16.26471409412160
results in
Degrees Minutes Seconds  48°11'51.0570", 016°15'52.9707"

**Comment by JeroenDeDauw** [comment]
> It is internally by default transferred into degrees, minutes and seconds.

I don't think so... I suspect the issue occurs after the data is retrieved from SMW, when Maps displays it. Anyway, will investigate

**Comment by mwjames** [comment]
> The problem now is that if the seconds are converted that include commas, they get truncated.

The storage of values in SMW-core doesn't get truncated therefore it is not an issue with SMW itself as can be seen from the attached image (actual DB content storage).

```
[[Has coordinates::48.19751582569160, 16.26471409412160]]
```
![image](https://cloud.githubusercontent.com/assets/1245473/23802322/49aa4c26-05f6-11e7-93bf-15d7d048ca23.png)

**Comment by krabina** [comment]
its a good thing that it is correctly in the database, but the sandbox example shows that it is not displayed/output correctly. So it seems to be truncated in the output which is an SMW issue. I am not using maps at this stage...

**Comment by JeroenDeDauw** [comment]
Right... SMW now actually does have the table even when (Semantic) Maps is not installed. That's been true since 1.6 but I'm still not used to it :)

While it might have the table, the actual user interaction part (parsing and formatting) does require Maps. I'm somewhat surprised that you got the stuff into SMW without.

**Comment by kghbln** [comment]
> I suggest to open an issue with https://github.com/JeroenDeDauw/Maps to keep track of the issue.
+1 + reference to here :)
