### ISSUE TITLE
Fatal error: Call to undefined method SMW\ConceptPage::getTopIndicators()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2321]
### Setup and configuration

- MediaWiki 	1.28.0 (e92ed15) 22:16, 28 November 2016
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.30-MariaDB-1~jessie
- ICU 	52.1
- Semantic MediaWiki	2.5.0-rc.1 (6c265a0) 14:56, 7 March 2017

### Issue
```
 Fatal error: Call to undefined method SMW\ConceptPage::getTopIndicators() in /.../w/extensions/SemanticMediaWiki/includes/articlepages/SMW_OrderedListPage.php on line 82
```

Steps to reproduce:

This happens when trying to access a [concept page](https://sandbox.semantic-mediawiki.org/wiki/Concept:InversePageCreatorLastEditorIs).

**Comment by mwjames** [comment]
Hi,

>  Fatal error: Call to undefined method SMW\ConceptPage::getTopIndicators()
> in

It's an oversight and due to its legacy code doesn't have a proper
integration test. A quick fix should include:

```
@@ -78,8 +78,8 @@ abstract class SMWOrderedListPage extends Article {
 		if ( !isset( $diff ) || !$diffOnly ) {

 			// MW 1.25+
-			if ( method_exists( $outputPage, 'setIndicators' ) ) {
-				$outputPage->setIndicators( $this->getTopIndicators() );
+			if ( method_exists( $outputPage, 'setIndicators' ) && (
$indicators = $this->getTopIndicators() ) !== '' ) {
+				$outputPage->setIndicators( $indicators );
 			}

 			$outputPage->addHTML( $this->getIntroductoryText() );
@@ -116,7 +116,7 @@ abstract class SMWOrderedListPage extends Article {
 	 *
 	 * @return string
 	 */
-	protected function getTopIndicator() {
+	protected function getTopIndicators() {
 		return '';
 	}
```

Cheers

**Comment by kghbln** [comment]
> A quick fix should include:

Field test returned fluff.
