### ISSUE TITLE
unset($wgFooterIcons) is not supported 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#233]
Doing an arbitrary change such as `unset($wgFooterIcons)` has no influence over SMW related settings that happen outside of an object that invokes the setting.

A possible core change in `Setup` could be:

```
if( isset( $this->globals['wgFooterIcons']['poweredby']['semanticmediawiki'] ) ) {
	return true;
}

$this->globals['wgFooterIcons']['poweredby']['semanticmediawiki'] = array(
	'src' => $this->globals['wgScriptPath'] . '/extensions/'
		. end( ( explode( DIRECTORY_SEPARATOR . 'extensions' . DIRECTORY_SEPARATOR , __DIR__, 2 ) ) )
		. '/../resources/images/smw_button.png',
	'url' => 'https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki',
	'alt' => 'Powered by Semantic MediaWiki',
);
```
If `$GLOBALS['wgFooterIcons']['poweredby']['semanticmediawiki']` is preset (with an empty array() or `FALSE` in `LocalSettings`) the `Setup` will no longer try to set a value and is treated with an empty entry instead.

In case the above change is implemented, SetupTest needs adoption as well.

**Comment by mwjames** [comment]
SMW 2.3 / use `$GLOBALS['wgFooterIcons']['poweredby']['semanticmediawiki'] = false` to disable the display.

**Comment by kghbln** [comment]
This is cool, too. Great. Works also with alternate more familiar parameter syntax `$wgFooterIcons['poweredby']['semanticmediawiki'] = false;`

**Comment by kghbln** [comment]
Added a [tip](https://semantic-mediawiki.org/wiki/Help:Remove_the_footer_icon_added_by_Semantic_MediaWiki) about this on smw.o
