### ISSUE TITLE
`InvalidArgumentException` from line 69 of "LatLongValue.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2341]
Originally reported here: https://github.com/DataValues/Geo/issues/98

**Setup**
- MediaWiki 	1.28.0 (fec3e69) 18:52, 1 March 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.30-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0 (73c1844) 08:19, 13 March 2017
- Maps	4.0.5 (2a751f5) 09:00, 6 March 2017
- data-values/geo	1.2.1

**Issue**
[925cecf32043ae73a6bac3f4] /wiki/Berlin InvalidArgumentException from line 69 of /.../w/vendor/data-values/geo/src/Values/LatLongValue.php: Can only construct LatLongValue with a numeric latitude

**Backtrace**
```
#0 /.../w/vendor/data-values/geo/src/Values/LatLongValue.php(57): DataValues\Geo\Values\LatLongValue->assertIsLatitude(NULL)
#1 /.../w/extensions/Maps/SemanticMaps/src/SM_GeoCoordsValue.php(66): DataValues\Geo\Values\LatLongValue->__construct(NULL, NULL)
#2 /.../w/extensions/Maps/SemanticMaps/src/SM_GeoCoordsValue.php(34): SMGeoCoordsValue->getFormattedCoord(SMWDIGeoCoord)
#3 /.../w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(217): SMGeoCoordsValue->loadDataItem(SMWDIGeoCoord)
#4 /.../w/extensions/SemanticMediaWiki/src/DataValueFactory.php(171): SMWDataValue->setDataItem(SMWDIGeoCoord)
#5 /.../w/extensions/SemanticMediaWiki/src/Factbox/Factbox.php(374): SMW\DataValueFactory->newDataValueByItem(SMWDIGeoCoord, SMW\DIProperty)
#6 /.../w/extensions/SemanticMediaWiki/src/Factbox/Factbox.php(288): SMW\Factbox\Factbox->getTableContent(SMW\SemanticData)
#7 /.../w/extensions/SemanticMediaWiki/src/Factbox/Factbox.php(238): SMW\Factbox\Factbox->createTable(SMW\SemanticData)
#8 /.../w/extensions/SemanticMediaWiki/src/Factbox/Factbox.php(112): SMW\Factbox\Factbox->fetchContent(integer)
#9 /.../w/extensions/SemanticMediaWiki/src/Factbox/CachedFactbox.php(236): SMW\Factbox\Factbox->doBuild()
#10 /.../w/extensions/SemanticMediaWiki/src/Factbox/CachedFactbox.php(146): SMW\Factbox\CachedFactbox->rebuild(Title, ParserOutput, RequestContext)
#11 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/OutputPageParserOutput.php(85): SMW\Factbox\CachedFactbox->prepareFactboxContent(OutputPage, ParserOutput)
#12 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/OutputPageParserOutput.php(58): SMW\MediaWiki\Hooks\OutputPageParserOutput->performUpdate()
#13 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(194): SMW\MediaWiki\Hooks\OutputPageParserOutput->process()
#14 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(OutputPage, ParserOutput)
#15 /.../w/includes/Hooks.php(195): call_user_func_array(Closure, array)
#16 /.../w/includes/OutputPage.php(1785): Hooks::run(string, array)
#17 /.../w/includes/OutputPage.php(1823): OutputPage->addParserOutputMetadata(ParserOutput)
#18 /.../w/includes/page/Article.php(589): OutputPage->addParserOutput(ParserOutput)
#19 /.../w/includes/actions/ViewAction.php(71): Article->view()
#20 /.../w/includes/MediaWiki.php(495): ViewAction->show()
#21 /.../w/includes/MediaWiki.php(289): MediaWiki->performAction(Article, Title)
#22 /.../w/includes/MediaWiki.php(851): MediaWiki->performRequest()
#23 /.../w/includes/MediaWiki.php(512): MediaWiki->main()
#24 /.../w/index.php(43): MediaWiki->run()
#25 {main}
```

**Example**
* [Berlin on sandbox.s-mw.o](https://sandbox.semantic-mediawiki.org/wiki/Berlin)

What wonders me is that today, just ten hours later, this issue is no longer appearing. Still posting to avoid that something gets overlooked.

**Comment by kghbln** [comment]
@JeroenDeDauw FYI

**Comment by kghbln** [comment]
@mwjames Perhaps this was also a result of incongruent software updating. If you do not see an issue at first glance which may be fixed I think we could close this for now thus keeping it for possible future reference. I guess this is ok since the issue did not show at any later point by now.

**Comment by mwjames** [comment]
> ... I guess this is ok since the issue did not show at any later point by now.

Fine be me, however I think [0] should shield itself against a `null` before calling `LatLongValue`.

[0] https://github.com/JeroenDeDauw/Maps/blob/master/SemanticMaps/src/SM_GeoCoordsValue.php#L59

**Comment by kghbln** [comment]
> Fine be me, however I think [0] should shield itself against a null before calling LatLongValue.

So this is a Maps issue after all. ;) @JeroenDeDauw Some thoughts ...

**Comment by kghbln** [comment]
Ping @JeroenDeDauw Any opinion on this?

**Comment by JeroenDeDauw** [comment]
You can argue that the maps code should be more robust and not fail when it gets wrong values from SMW, though you can also argue it should not silently hide such an issue.

Either way, there is an issue in SMW. At the very least, if the getLat and getLon methods are allowed to return null, the docs should be fixed to reflect that. But it does not look like they should.... which means there is a bug in SMW.

**Comment by JeroenDeDauw** [comment]
I am looking at this now btw. Not seeing anything wrong in SMWDIGeoCoord... perhaps we should add some safeguards there so things fail earlier.

**Comment by JeroenDeDauw** [comment]
@mwjames you sure this does not cause any trouble? https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/9e13dc624c978628ce48d01b844cb48c6dc6714f

**Comment by JeroenDeDauw** [comment]
Safeguards added in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2383

**Comment by kghbln** [comment]
> Safeguards added in #2383

Cool, thanks for fluff. :)
