### ISSUE TITLE
Remove deprecated configuration parameters

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2343]
Starting with SMW 2.5.0 this configuration parameter was depreciated in favour of the `$smwgAdminFeatures` configuration parameter. I believe an overly long migration period is not required for this configuration parameter. Thus it may be removed.

**Comment by mwjames** [comment]
Done so in #2362 with a little twist that if it is still used, it will appear in `Special:SemanticMediaWiki`. If you want to remove it then you have to:

- Remove the legacy mapping in `Settings`
- Move the entry in `DeprecationNoticeTaskHandler` from `deprecatedConfigList` to `removedConfigList`

![image](https://cloud.githubusercontent.com/assets/1245473/24321304/7bf57c4a-118c-11e7-8e7f-675fe86a0a67.png)

**Comment by kghbln** [comment]
>  Done so in #2362 with a little twist that if it is still used, it will appear in Special:SemanticMediaWiki. If you want to remove it then you have to:

Great idea! Thanks a lot.

**Comment by kghbln** [comment]
This was originally only about `$smwgAdminFeatures` but now adding in `smwgQueryDependencyPropertyExemptionlist` and `smwgQueryDependencyAffiliatePropertyDetectionlist` as stated #2384

**Comment by krabina** [comment]
Guess this can this be closed? the above mentioned PRs are merged
