### ISSUE TITLE
SpecialURIResolver emitted "Notice: Undefined index: HTTP_ACCEPT"

### ISSUE THREAD

**Issue by nemobis** [SemanticMediaWiki/SemanticMediaWiki#2344]
### Setup and configuration

- SMW version: 2.4.6
- MW version: 1.29.0-alpha
- PHP version: HHVM 3.18.1 
- DB (MySQL etc.): 10.0.29-MariaDB-0ubuntu0.16.04.1

### Issue

```
-rakkaus:#mediawiki-i18n- (1 lines skipped) [Mon Mar 20 21:02:43 2017] [hphp] [11855:7f67d7bff700:194946:000001] [] \nNotice: Undefined
          index: HTTP_ACCEPT in
          /srv/mediawiki/tags/2017-03-08_09:31:59/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialURIResolver.php on line 51
```

**Comment by kghbln** [comment]
Thanks for reporting. Since the respective code did not change in two years this is also applicable to 2.5.x.

**Comment by Nikerabbit** [comment]
Same notice also happened on line 31 of the same file.
