### ISSUE TITLE
SMW off/on in API ?action=expandtemplates

### ISSUE THREAD

**Issue by Clubfan22** [SemanticMediaWiki/SemanticMediaWiki#2371]
### Setup and configuration
The same as #2370 

* [Setup A](http://wiki.liquipedia.space/commons/index.php?title=Special:Version):
- SMW version: 2.5.0
- MW version: 1.27.1
- PHP version: 5.6.30-0+deb8u1 (apache2handler)
- DB (MySQL etc.):  	5.5.54-0+deb8u1

* [Setup B](http://wiki.teamliquid.net/dota2/Special:Version?detail=1):
- SMW version: 2.2.2
- MW version: 1.25.2
- PHP version: 5.6.30-0+deb8u1 (fpm-fcgi)
- DB (MySQL etc.):  	10.1.22-MariaDB-1~jessie

### Issue

When using wikicode with SMW queries in the API action=expandtemplates, [[SMW:off]] and [[SMW:on]] annotations are returned.

Our use case is that we are caching very slow wiki queries by expanding them once and then storing  them as (almost) plain HTML on the wiki. For the first part, we are using [action=expandtemplates](http://wiki.liquipedia.space/commons/api.php?action=help&modules=expandtemplates) with the query code.

For following wikicode
```
<div class="table-responsive">
{{Test table/intro}}
{{#ask: [[has placement::+]] [[has player pages::TaeJa]]
|?has placement
|?has prizemoney
|?has date#ISO
|?has player pages
|link=none
|format=template
|template=Test table/row
|sort=has date
|order=desc
|limit=5000
}}
{{Table/outro}}
</div>
```

we get the following URL:
http://wiki.liquipedia.space/commons/api.php?action=expandtemplates&format=xml&text=%3Cdiv+class%3D%22table-responsive%22%3E%0A%7B%7BTest+table%2Fintro%7D%7D%0A%7B%7B%23ask%3A+%5B%5Bhas+placement%3A%3A%2B%5D%5D+%5B%5Bhas+player+pages%3A%3ATaeJa%5D%5D%0A%7C%3Fhas+placement%0A%7C%3Fhas+prizemoney%0A%7C%3Fhas+date%23ISO%0A%7C%3Fhas+player+pages%0A%7Clink%3Dnone%0A%7Cformat%3Dtemplate%0A%7Ctemplate%3DTest+table%2Frow%0A%7Csort%3Dhas+date%0A%7Corder%3Ddesc%0A%7Climit%3D5000%0A%7D%7D%0A%7B%7BTable%2Foutro%7D%7D%0A%3C%2Fdiv%3E&title=API .

Everything works as intended, but the output contains [[SMW:off]] and [[SMW:on]] annotations:
```
<div class="table-responsive">
{| class="table table-striped table-full-width sortable" style="text-align:center;"
! Placement
! Prize Money
! Date
! Player
[[SMW::off]]

|-
|1
|1,000
|2017-03-31
|TaeJa[[SMW::on]]
|}
</div>
```

We first noticed it on our main setup (Setup B) and thought it might be related to the rather old MW and SMW versions, but it happens as well on the test wiki (Setup A).

- Definition of subobject: http://wiki.liquipedia.space/commons/index.php?title=Main_Page&action=edit&section=12

Feel free to ask if you need more information about our setup and/or use case.
Thank you already!

Clubfan

**Comment by kghbln** [comment]
Thanks for reporting. Most likely related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2347

**Comment by Clubfan22** [comment]
I already applied #2351 to Setup A, yet the issue remains.

**Comment by mwjames** [comment]
This is not a bug and the behaviour for `?action=expandtemplates&text= ...` in terms of `[[SMW::on]]`/`[[SMW::off]]` has been the same as before 2.2. I just tested an old 1.9.2 which returns the same results on a Semantic MediaWiki 1.9.2, MediaWiki 1.24.2 as for MW 1.28/ SMW 2.5.

```
<?xml version="1.0"?>
<api>
  <warnings>
    <expandtemplates xml:space="preserve">Because no values have been specified for the prop parameter, a legacy format has been used for the output. This format is deprecated, and in the future, a default value will be set for the prop parameter, causing the newformat to always be used.</expandtemplates>
  </warnings>
  <expandtemplates xml:space="preserve">[[SMW::off]][[:Example/0706/2|Example/0706/2]]  [[Tmpl0706withAnnotation::Foo]] [[Tmpl0706withAnnotationExtra::Deep]][[SMW::on]]</expandtemplates>
</api>
```

The reason for any API call is the same as in [0] and since we have no real way (meaning programmatically) to identify whether a parse is called from an API consumer or not, parameter `import-annotation=true` can be used to enter a recursive pre-process which resolves the `[[SMW::off]]` during that process.

For some more information on those markers, see #2372.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/10ed8f775eb8055c198b6c04d6afa2eb53df871c

**Comment by kghbln** [comment]
> parameter `import-annotation=true` can be used to enter a recursive pre-process which resolves the [[SMW::off]] during that process.

Good to know. I believe this solves the issue.
