### ISSUE TITLE
getSQLCondition missing from Description class

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2400]
I noticed that the parents of `SMAreaValueDescription` are not defining the "implemented" `getSQLCondition` method at all. Which confused me for a bit, cause I tough it was dead code.

SomePropertyInterpreter has

```php
$where = $description->getSQLCondition(
```

So it is not dead code, the abstract method is simply missing from the parents.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
