### ISSUE TITLE
Property chains for sorting

### ISSUE THREAD

**Issue by EvenThorbergsen** [SemanticMediaWiki/SemanticMediaWiki#2402]
It would very much add to the SMW functionality to be able to sort by the property of a property.
Say you need a table of cities sorted by, not the name of the country, but by the population of the country.
The notation might be like this, here combined with subsorting by population of the city:
```
{{#ask:
  [[Category:Cities]]
  |mainlabel=City
  |?Located in=Country
  |?Population
  |sort=Located in.Population, Population
}}
```
Here is another case, and really the one I need to express:
You need to make a table of board members based on pages from a Persons category. The Person template carry the property Role pointing to pages of category Roles.

Now you would like to put the chairman first, then vice-chairman, cashier, other board members.
The Role template is given the Number property Rank, where chairman get Rank 1, vice-chairman Rank 2 etc:

```
{{#ask:
  [[Category:Persons]] [[Role::+]]
  | mainlabel=Name
  | ?Role
  | ?Phone
  | ?Address
  | sort=Role.Rank
}}
```

**Comment by mwjames** [comment]
It is unclear from the description above whether this has already been addressed by #1824, #2073 or not and in case it hasn't then a clarification would be necessary as to what is expected and why it is not addressed by #2073.

In general, for any feature request or bug report the following notes [0] should be considered. Please use [1] as an example on how to address [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/CONTRIBUTING.md
[1] https://sandbox.semantic-mediawiki.org/wiki/Issue/2073

**Comment by kghbln** [comment]
Thanks for both of you for being involved here. I will add the "discussion" label for now which may be changed to e.g. "enhancement" as this issue progresses.

**Comment by kghbln** [comment]
> It is unclear from the description above whether this has already been addressed by #1824, #2073 or not and in case it hasn't then a clarification would be necessary as to what is expected and why it is not solved by #2073.

@EvenThorbergsen Some comments?

**Comment by EvenThorbergsen** [comment]
If both printout and sort based in chained properties are already solved, I am thrilled.
I have not found it in the documentation, that is why I have asked for it.
I must admit I do not have the latest SWM version installed, I use 2.2.2.
I will keep quiet at least until I have checked this with the latest version. :-)

**Comment by kghbln** [comment]
Perhaps this was a bit hidden [on the wiki](https://www.semantic-mediawiki.org/wiki/Help:Property_chains_and_paths) but a search for property chain should have gotten you there. ;) Closing for now.

**Comment by EvenThorbergsen** [comment]
I couldn't find anything in the article about sorting based on a chained property, which is my main point.
Described elsewhere?

**Comment by kghbln** [comment]
I am afraid this is all we have right now. I have not fiddled much with property chaining and did not mix in sorting. What happens with your tests?

**Comment by EvenThorbergsen** [comment]
I have started testing in the sandbox wiki, where there are some French challenges. :-)
I did not finish so far.

**Comment by mwjames** [comment]
> I have now tested this property chain functionality (printout and sort) in the sandbox wiki and it works perfectly. :-)

Thanks for effort and I copied your example [0] to a more prominent location. 

[0] https://sandbox.semantic-mediawiki.org/wiki/Issue/2402

**Comment by kghbln** [comment]
> This is very valuable for me.

Something link this is always good to here. So we now have more examples and better documentation - which is good!

**Comment by EvenThorbergsen** [comment]
I have been an enthusiastic user of SMW since 2008 administrating one job wiki, working with semantics,  taking our own medicine, and one private wiki for a wind band, arranging festivals.

**Comment by kghbln** [comment]
> I have been an enthusiastic user of SMW since 2008 administrating one job wiki, working with semantics, taking our own medicine, and one private wiki for a wind band, arranging festivals.

Great to read. You obviously appreciate the advantages of SMW. :)
