### ISSUE TITLE
Sort values by `Allows value` list position

### ISSUE THREAD

**Issue by EvenThorbergsen** [SemanticMediaWiki/SemanticMediaWiki#2411]
Consider having a property specified by a value list (number of "Allows value").
Then it should be possible to sort by the value positions in the list, in stead of the value names.
A typical case is a property "DayOfWeek" with allowed values Sun, Mon, Tue, Wed, Thur, Fri, Sat.
Sorting events, having this property, by the property, places events on Fridays first, then Mondays and so on, not the obvious/proper sequence.

There might be a challenge finding a good notation to signal this.
As value sequence no is involved, an overloaded use of # is natural:
| sort=DayOfWeek#
	 or
| sort=#DayOfWeek

This issue is related to #2402.

**Comment by kghbln** [comment]
Thanks for suggesting. This is probably about making sorting for datatype "Date" smarter by automatically adding in a sortkey referring to the position of the date of week (0 or 1?). Thus sorting by date and sorting by the label of the date an when by date is easier.

**Comment by EvenThorbergsen** [comment]
Date is not the issue here. It is more general  than that. Another case is a property Military rank where you would like to sort persons by their rank,  placing generals first and privates at the bottom not having to rely on the name of the ranks.

**Comment by kghbln** [comment]
> This is because it is possible to create one "Rank" page per rank, each with a degree value corresponding to the position above, and then sort by person's rank's degree.

I was just going to write this. What I do all over the place is adding a helper property that allows me to define a natural order and sort without necessarily exposing it in the results (template format). Dates came to my mind because is a datatype where sorting order may not be natural but still foreseeable. All the rest is basically up to your imagination and it is up to you to define the helper property allowing you to sort naturally  in the way desired.

**Comment by mwjames** [comment]
> Consider having a property specified by a value list (number of "Allows value").
Then it should be possible to sort by the value positions in the list, in stead of the value names.

This is a feature request and as such is moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
