### ISSUE TITLE
(48756) QueryPrinters always uses default limit even though a "original value" is available 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#242]
Bug [48756](https://bugzilla.wikimedia.org/show_bug.cgi?id=48756), where `CsvResultPrinter`, `JsonResultPrinter` show same behaviour on a default limit.

SMWQueryProcessor: Line:138 with `$params['limit']->getValue()` always returns 100 as default value (due to `$params['limit']->setDefault( 100 )`)
### Reference example

`$smwgQMaxInlineLimit = 50000` and `$smwgQMaxLimit = 50000`

```
{{#ask: [[Modification date::+]]
 |?Modification date
 |limit=9999
 |format=json
}}
```

**Comment by ubibene** [comment]
Bug is sitll present in SMW 2.3.1

I had to change 100 to 1000 in CsvResultPrinter.php , ligne 129

See also the discussion here : https://www.semantic-mediawiki.org/wiki/Thread:Help_talk:CSV_format/Limit_ignored_in_CSV_export%3F

**Comment by mwjames** [comment]
> Bug is sitll present in SMW 2.3.1

Yes, no one has fixed this (and I'm too occupied to have look at it).

**Comment by krabina** [comment]
is this bug still present in SMW 2.5.x?

**Comment by ubibene** [comment]
yes it is

**Comment by mwjames** [comment]
Hi,

> is this bug still present in SMW 2.5.x?

It could well be that since I got so irritated two weeks ago by a
"limit" contention that [0] is addressing this very issue (without me
remembering that we had an open ticket).

As for the answer to the original question, I'd suggest you use the
sandbox and report back your findings.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2474

Cheers

**Comment by kghbln** [comment]
> Okay, so what now?

I am sure either @krabina or @ubibene will provide the test case on sandbox soon. Just give them a bit more time.

**Comment by mwjames** [comment]
> will provide the test case on sandbox soon. Just give them a bit more time.

It has been a four days and I don't mind if it takes a month to confirm the issue but I'd like to see a confirmation within a reasonable amount of time so I can affirm that this is not a one-man show.

**Comment by krabina** [comment]
Sorry, I am confused now. Isnt't this https://sandbox.semantic-mediawiki.org/wiki/Issue/2474 exactly what is needed regarding testing in the sandbox?
What else should we test?

**Comment by kghbln** [comment]
> Isnt't this https://sandbox.semantic-mediawiki.org/wiki/Issue/2474 exactly what is needed regarding testing in the sandbox? What else should we test?

I did not see that. Senior moments. So is it now working or not?

**Comment by krabina** [comment]
No, it's not working. I edited the sandbox.
In the first example, limit=5000, there are 1733 values, but only 500 are shown
The second example limit=222 is ok.
Added a third example, without limit. Delivers 100 entries, I am not sure if thats ok, depends on settings of 
$smwgQDefaultLimit which defaults to 50. So must be set to 100 in localsettings of sandbox to be ok.
https://www.semantic-mediawiki.org/wiki/Help:$smwgQDefaultLimit

**Comment by mwjames** [comment]
> No, it's not working. I edited the sandbox.

You see and this why I'm asking people to confirm their observation
because users understand an issue differently.

> In the first example, limit=5000, there are 1733 values, but only 500 are
> shown

This is correct because of $smwgQMaxLimit (should be 500).

> The second example limit=222 is ok.
> Added a third example, without limit. Delivers 100 entries, I am not sure if
> thats ok, depends on settings of

This is the actual use case that was addressed in the mentioned issue.

> $smwgQDefaultLimit which defaults to 50. So must be set to 100 in
> localsettings of sandbox to be ok.
> https://www.semantic-mediawiki.org/wiki/Help:$smwgQDefaultLimit

**Comment by krabina** [comment]
https://www.semantic-mediawiki.org/wiki/Help:$smwgQMaxLimit default is 10000, so it is only ok if it has been set to 500 in localsettings

**Comment by mwjames** [comment]
> https://www.semantic-mediawiki.org/wiki/Help:$smwgQMaxLimit default is
> 10000, so it is only ok if it has been set to 500 in localsettings

Sorry, copied the wrong setting, it is $mwgQMaxInlineLimit because
this is an embedded query.

**Comment by krabina** [comment]
OK it seems this can be closed. But to make sure, I would suggest to set 
https://www.semantic-mediawiki.org/wiki/Help:$smwgQMaxLimit to 1000
and 
https://www.semantic-mediawiki.org/wiki/Help:$smwgQDefaultLimit to 200
and then see if still everything works as expected.

**Comment by kghbln** [comment]
> But to make sure, I would suggest to set ...

[Done and ready for testing](https://sandbox.semantic-mediawiki.org/w/index.php?title=SMW_Sandbox%3ASetup_information&type=revision&diff=6665&oldid=6658)

**Comment by krabina** [comment]
There you have it: nothing changed. Sandbox still delivers 500 (should be 1000) and 100 (should be 200)

**Comment by mwjames** [comment]
The changes shows [0] `$smwgQMaxLimit = 1000;` but as I mentioned
earlier it should be `smwgQMaxInlineLimit`.

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=SMW_Sandbox%3ASetup_information&type=revision&diff=6665&oldid=6658

**Comment by mwjames** [comment]
>  and 100 (should be 200)

Export formats use their own default which is hard-coded to a default
value [0] independent of $smwgQDefaultLimit.

It can be discussed whether this is correct not but the this is the
expected codified behaviour.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/CsvResultPrinter.php#L123

**Comment by krabina** [comment]
If $smwgQMaxInlineLimit = 1000 works (which is to be tested), then we could change that from a bug to a feature request. But the documentation of 
https://www.semantic-mediawiki.org/wiki/Help:$smwgQDefaultLimit
states "Default number of rows returned in a query". As export formats are nothing different than display formats from a user's perspective, the hard coded setting makes no sense and should easily be replacable by the value of $smwgQDefaultLimit

**Comment by mwjames** [comment]
> change that from a bug to a feature request. But the documentation of
> https://www.semantic-mediawiki.org/wiki/Help:$smwgQDefaultLimit
> states "Default number of rows returned in a query". As export formats are
> nothing different than display formats from a user's perspective, the hard
> coded setting makes no sense and should easily be replacable by the value of
> $smwgQDefaultLimit

Please, make it a new issue.

**Comment by krabina** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2505

**Comment by kghbln** [comment]
> If $smwgQMaxInlineLimit = 1000 works (which is to be tested)

It does so we are cool here. I believe that any confusion was overcome.
