### ISSUE TITLE
Parser function `#show` and `#expr` do not play?

### ISSUE THREAD

**Issue by matahombres** [SemanticMediaWiki/SemanticMediaWiki#2425]
### I am editor for a gamepedia and i am not administrator. 

https://ridersoficarus.gamepedia.com/Special:Version
- SMW version: In the link
- MW version: In the link
- PHP version: In the link
- DB (MySQL etc.): In the link

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:
I have in template: https://ridersoficarus.gamepedia.com/Template:Infobox_quest one expression that automatic order numeric the expresion it's: 
`{{#ifeq:{{#show:{{{preceding quest|}}}|?Order mission|link=none}}||1|{{#expr:1+{{#show:{{{preceding quest|}}}|?Order mission|link=none}}}}}}`
The code... calculates Bad and i don't understand because...

Steps to reproduce the observation`
https://ridersoficarus.gamepedia.com/User:Matahombres/sandbox#Testing_Order_expresion

**Comment by kghbln** [comment]
Thanks for reproting.

> 
    SMW version: In the link
    MW version: In the link
    PHP version: In the link
    DB (MySQL etc.): In the link

These are not fixed data so just linking to it does not fix the.

- MediaWiki 	1.27.2 (72be698) 22:14, 21 April 2017
- PHP 	7.0.15-1+deb.sury.org~trusty+1 (fpm-fcgi)
- MySQL 	5.5.41-37.0-55
- Semantic MediaWiki	2.4.1

> The code... calculates Bad and i don't understand because...

"Expression error: Unexpected < operator." tells that one of the values piped into `#expr` contains a "<" so this is not a number. Usually it helps exploding all the parser functions one by one on the non-working example and look that  the output of them are.

**Comment by matahombres** [comment]
Yes... But the error thats not all. If you view list. Left say the correct number, but right repeat numbers. For exmample 3 and 4 the value is =

**Comment by matahombres** [comment]
And because in some shows and others not?

**Comment by kghbln** [comment]
The only way to find out is to isolate the `#show` queries and see what they return before you pipe it into other parser functions for further manipulations. 

Since I do no longer see errors on the referenced page this issue is now sorted out?

**Comment by matahombres** [comment]
yes. the problem solved. In the end I had to "force" to load the page again editing in black. (View source and save changes without making changes)

**Comment by kghbln** [comment]
> yes. the problem solved.

Cool, great to get the confirmation!
