### ISSUE TITLE
Give some language love to deprecation notices

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2430]
The new deprecation notice stuff on Special:SMWAdmin is really cool but has some language and structure issues. I want to improve that a bit. This issue is so that I do not forget.

**Comment by kghbln** [comment]
Meh, I already fluffed. What's the worry with something like e.g. "$smwgAdminRefreshStore is deprecated and will be removed in 3.1.0". Well we could add version to it, but apart from that sysops will understand and manage, no?

**Comment by kghbln** [comment]
@JeroenDeDauw Whole Lotta Love?

**Comment by kghbln** [comment]
@JeroenDeDauw Ping!

**Comment by kghbln** [comment]
@JeroenDeDauw  https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2729 also connecting in.

**Comment by JeroenDeDauw** [comment]
I have not looked at this in the meanwhile. If you say it is fluff already then of course I will believe the minster of fluffness.

**Comment by kghbln** [comment]
Have a look at a [live example](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SemanticMediaWiki#tab-notices).

**Comment by JeroenDeDauw** [comment]
> The following section contains settings that have been deprecated or removed but were detected to be active on this wiki. It is expected that any future release will remove support for these configurations.

"This section lists settings used on this wiki that might require your attention."

> * Notice
> * Replacement
> * Replacement

Switch order and add a line of explanation between the header and bullet points.

* Renamed settings - These settings where renamed or otherwise updated in a previous release. For them to be used on this wiki again, please update their name or format.
* Removed settings - These settings where removed in a previous release. They are not currently used on this wiki and can be removed from your settings file.
* Upcoming changes - Changes to settings used on this wiki that will arrive in a future release.

**Comment by JeroenDeDauw** [comment]
@mwjames are you fine with the text and layout being changed like that? (I'm not asking you to do it, just if you're OK with it)

**Comment by mwjames** [comment]
> @mwjames are you fine with the text and layout being changed like that? (I'm
> not asking you to do it, just if you're OK with it)

+1
