### ISSUE TITLE
PHP Notice:  Undefined index for deprecated configuration parameter

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2431]
### Setup and configuration

- MediaWiki 	1.27.2 (1c409c5) 7. Apr. 2017, 03:42
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MySQL 	5.5.54-0+deb8u1
- Semantic MediaWiki	2.5.1 (568d058) 22. Apr. 2017, 03:52

### Issue
After upgrading from 2.5.0 to 2.5.1 I get the following notices from the job queue:
```
PHP Notice:  Undefined index: smwgQueryDependencyPropertyExemptionList in /.../w/extensions/SemanticMediaWiki/includes/Settings.php on line 158
PHP Notice:  Undefined index: smwgQueryDependencyAffiliatePropertyDetectionList in /.../w/extensions/SemanticMediaWiki/includes/Settings.php on line 159
```
I am aware that this relates to the deprecated `$smwgQueryDependencyAffiliatePropertyDetectionlist` setting still sitting in my "LocalSettings.php" file and which has to be cleared but I guess the configuration parameter should not emit such notices.

**Comment by mwjames** [comment]
Hi,

> ```
> PHP Notice:  Undefined index: smwgQueryDependencyPropertyExemptionList in
> /.../w/extensions/SemanticMediaWiki/includes/Settings.php on line 158
> PHP Notice:  Undefined index:
> smwgQueryDependencyAffiliatePropertyDetectionList in
> /.../w/extensions/SemanticMediaWiki/includes/Settings.php on line 159
> ```

The only way those notices (Settings.php 158, 159) could happen if
they are unknown are not declared in the `DefaultSettings.php` which
I'm sure there are, so I'm not quite clear about the circumstances and
the cause for it.

> After upgrading from 2.5.0 to 2.5.1 I get the following notices from the job
> queue:

Maybe some old jobs containing some outdated references ??!! If those
were not defined then you would get notices within a normal user
session as well.

Cheers

**Comment by kghbln** [comment]
> I'm sure there are, so I'm not quite clear about the circumstances and the cause for it.

Affirmative if "DefaultSettings.php" of 2.5.0 was used before which was apparently the case.

> Maybe some old jobs containing some outdated references ??!! If those were not defined then you would get notices within a normal user session as well.

This happened only once immediately after the upgrade. Since the jobs are run every three minutes for this wiki I do not believe that old jobs were the cause. Perhaps the jobs were created during the update thus causing this for some reason.

Closing this for future reference in case a similar issue arises.
