### ISSUE TITLE
Cannot install Semantic MediaWiki using Composer before setting up the wiki first

### ISSUE THREAD

**Issue by pierreboutet** [SemanticMediaWiki/SemanticMediaWiki#2432]
I realise that semantic mediawiki cannot be install with composer on a wiki not yet initialized, because the installation process (in /mw-config ) load all extensions installed with composer, but as database is not set up yet, it trigger an Exception (see bellow)

The workaround is to install the wiki without semanticMediawiki, execute the set up, and then add the semantic mediawiki , and finish the installation with the script 'maintenance/update.php'

But I think it should be possible to install the whole package in one time.

to reproduce : 
- Download and extract Mediawiki 1.28.1
- run 'composer.phar require mediawiki/semantic-media-wiki' in the directory
- go to you website url tu install it ( ex : http://localhost/w/mw-config ), then the Exception appear, and we can't do the installation

Exception Triggered : 
```
[4eb69185a048af297309d534] /w/mw-config/index.php MediaWiki\Services\ServiceDisabledException from line 340 of /var/www/w/includes/services/ServiceContainer.php: Service disabled: DBLoadBalancer
```
Backtrace:
```
#0 /var/www/w/includes/MediaWikiServices.php(509): MediaWiki\Services\ServiceContainer->getService(string)
#1 /var/www/w/includes/GlobalFunctions.php(3089): MediaWiki\MediaWikiServices->getDBLoadBalancer()
#2 /var/www/w/includes/GlobalFunctions.php(3075): wfGetLB(boolean)
#3 /var/www/w/includes/cache/LinkCache.php(267): wfGetDB(integer)
#4 /var/www/w/includes/Title.php(3222): LinkCache->addLinkObj(Title)
#5 /var/www/w/includes/Title.php(4295): Title->getArticleID(integer)
#6 /var/www/w/includes/Title.php(2572): Title->exists()
#7 /var/www/w/includes/Title.php(2687): Title->getRestrictionTypes()
#8 /var/www/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(79): Title->isProtected(string)
#9 /var/www/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(61): SMW\MediaWiki\Hooks\ParserAfterTidy->canPerformUpdate()
#10 /var/www/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(148): SMW\MediaWiki\Hooks\ParserAfterTidy->process(string)
#11 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(Parser, string)
#12 /var/www/w/includes/Hooks.php(195): call_user_func_array(Closure, array)
#13 /var/www/w/includes/parser/Parser.php(1397): Hooks::run(string, array)
#14 /var/www/w/includes/parser/Parser.php(444): Parser->internalParseHalfParsed(string, boolean, boolean)
#15 /var/www/w/includes/installer/Installer.php(675): Parser->parse(string, Title, ParserOptions, boolean)
#16 /var/www/w/includes/installer/WebInstaller.php(702): Installer->parse(string, boolean)
#17 /var/www/w/includes/installer/WebInstallerLanguage.php(81): WebInstaller->getHelpBox(string)
#18 /var/www/w/includes/installer/WebInstaller.php(279): WebInstallerLanguage->execute()
#19 /var/www/w/mw-config/index.php(81): WebInstaller->execute(array)
#20 /var/www/w/mw-config/index.php(39): wfInstallerMain()
#21 {main}
```

### Setup and configuration

- SMW version: 2.5.1
- MW version: 1.28.1
- PHP version: 5.6
- DB (MySQL etc.): Mysql

**Comment by kghbln** [comment]
From experience this is not an isolated issue of the Semantic MediaWiki extension. Thus I have long ago stopped trying to install MediaWiki and extensions in one go.

**Comment by kghbln** [comment]
@JeroenDeDauw Some thoughts?

**Comment by pierreboutet** [comment]
Thanks for your comments
To me, up to now, this is the only extension who give me such problems.

I am trying to prepare a package ready to deploy with mediawiki and a list of extensions. 
The fact that the extension must be initialized ( i mean here the database update ) after the first set up process is not big problem. But  the simple presence of the extension in the package does fail the install process (even without selecting the extension in the install process) And this make the full process more complicated.

**Comment by mwjames** [comment]
Hi,

> To me, up to now, this is the only extension who give me such problems.
>

See also https://www.mediawiki.org/wiki/Topic:Tlunnqovj0wesefs (non
SMW). As for the stack:

> #0 /var/www/w/includes/MediaWikiServices.php(509): MediaWiki\Services\ServiceContainer->getService(string)
#1 /var/www/w/includes/GlobalFunctions.php(3089):
MediaWiki\MediaWikiServices->getDBLoadBalancer()
#2 /var/www/w/includes/GlobalFunctions.php(3075): wfGetLB(boolean)
#3 /var/www/w/includes/cache/LinkCache.php(267): wfGetDB(integer)
#4 /var/www/w/includes/Title.php(3222): LinkCache->addLinkObj(Title)
#5 /var/www/w/includes/Title.php(4295): Title->getArticleID(integer)
#6 /var/www/w/includes/Title.php(2572): Title->exists()
#7 /var/www/w/includes/Title.php(2687): Title->getRestrictionTypes()

The issue isn't really with SMW as shown by the stack trace, the issue
is that an access to `Title::getArticleID` requires an active DB
connection and with the introduction of the MW `ServiceContainer` the
`DBLoadBalancer` service is disabled for the installation and
ultimately fails with "Service disabled: DBLoadBalancer".

Anyway, I'll have a look at it during my weekend sprint and see if we
can avoid the execution of the hook at the time of the installation.
Again, the issue should be dealt within `Title::getArticleID` when it
cannot access the DBLoadBalancer.

Cheers

**Comment by mwjames** [comment]
> The issue isn't really with SMW as shown by the stack trace, the issue is that an access to `Title::getArticleID` requires an active DB

For reference, I created [0].

> Anyway, I'll have a look at it during my weekend sprint and see if we can avoid the execution of the hook at the time of the installation.

#2434 adds a check to avoid the issue that should actually be tackled by [0]. I'm not so utterly thrilled and happy about this but it would avoid the encountered "Service disabled: DBLoadBalancer".

> I realise that semantic mediawiki cannot be install with composer on a wiki not yet initialized, because the installation process (in /mw-config ) load all extensions installed with composer,

#1732 adds support for the `extension.json` and is preliminary planned for 3.0. It would only load the extension when added to `LocalSettings.php`, yet still be managed by Composer.

[0] https://phabricator.wikimedia.org/T163990

**Comment by kghbln** [comment]
@mwjames I relabeled to enhancement since SMW is now doing something better disregarding the reason for having to do that change, i.e. an issue elsewhere. I also added the SMW 2.5.2 milestone since this could probably be backported.

**Comment by kghbln** [comment]
This will ship with SMW 2.5.2
