### ISSUE TITLE
"composer update" works, but wiki dies...

### ISSUE THREAD

**Issue by JBruceDawson** [SemanticMediaWiki/SemanticMediaWiki#2452]
### Setup and configuration

- SMW version: 2.4.5 
- MW version: 1.28.0
- PHP version: 5.5.9
- DB (MySQL etc.): MySQL 5.5.55

### Issue

After running 'composer update' MediaWiki produces errors whenever I try to go to a page with any SMW properties.

I did the following:
codemeta.com@simon:~/farmergeek/wiki$ composer update
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 13 updates, 13 removals
  - Removing james-heinrich/getid3 (v1.9.12)
  - Removing pimple/pimple (v2.1.1)
  - Removing ruflin/elastica (3.1.1)
  - Removing symfony/process (v3.0.4)
  - Removing pear/mail (1.3.0)
  - Removing pear/net_smtp (1.7.1)
  - Removing pear/net_socket (1.0.14)
  - Removing pear/mail_mime-decode (1.5.5.2)
  - Removing pear/mail_mime (1.10.0)
  - Removing pear/pear-core-minimal (v1.10.1)
  - Removing pear/console_getopt (v1.4.1)
  - Removing pear/pear_exception (v1.0.0)
  - Removing firebase/php-jwt (v3.0.0)
  - Updating composer/installers (v1.2.0 => v1.3.0): Loading from cache
  - Updating onoi/shared-resources (0.3.0 => 0.4.3): Loading from cache
  - Updating param-processor/param-processor (1.3.1 => 1.3.2): Downloading (100%)         
  - Updating wikimedia/textcat (1.1.3 => 1.2.0): Downloading (100%)         
  - Installing onoi/tesa (0.1.0): Downloading (100%)         
  - Updating onoi/callback-container (1.1.0 => 2.0.0): Downloading (100%)         
  - Updating mediawiki/semantic-media-wiki (2.4.5 => 2.5.1): Loading from cache
  - Updating mediawiki/semantic-breadcrumb-links (1.3.0 => 1.3.1): Downloading (100%)         
  - Updating sebastian/recursion-context (1.0.2 => 1.0.5): Downloading (100%)         
  - Updating sebastian/comparator (1.2.2 => 1.2.4): Downloading (100%)         
  - Updating phpspec/prophecy (v1.6.2 => v1.7.0): Downloading (100%)         
  - Updating phpunit/php-timer (1.0.8 => 1.0.9): Downloading (100%)         
  - Updating phpunit/php-token-stream (1.4.9 => 1.4.11): Downloading (100%)         
  - Updating symfony/yaml (v3.2.2 => v3.2.8): Downloading (100%)         
Writing lock file
Generating optimized autoload files

Then, if I go to http://wiki.farmergeek.com/index.php/ResourcesHome, the page works, but when I go to a link that's on the page, say http://wiki.farmergeek.com/index.php/Resource00000Resource, Then I get the attached screen.
![screenshot from 2017-05-08 17 16 29](https://cloud.githubusercontent.com/assets/11779528/25825793/46d888ce-3412-11e7-82a7-af4ceed7f10c.png)

```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

Just run 'composer update' on a SMW 2.4.5 site.

**Comment by JBruceDawson** [comment]
I'll leave this site up for today, but will revert it to SMW 2.4.5 sometime tomorrow. At least that's the plan.

**Comment by mwjames** [comment]
Hi,

>   - Updating mediawiki/semantic-media-wiki (2.4.5 => 2.5.1): Loading from
> cache

Upgrading from 2.4.x to 2.5.x requires to run `update.php` as outlined
in [0] and [1] with:

"Important Note: Please remember to run MediaWiki's "update.php"
maintenance script after the upgrade if you are upgrading from
Semantic MediaWiki 2.4.x or earlier before continuing to work with
Semantic MediaWiki."

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B#Run_maintenance_script_2

[1] https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.5.1

Cheers

**Comment by mwjames** [comment]
Hi,

When reporting an exception (as with the screen dump), please follow
[0] where it is explained how to extract [1] a somewhat more
meaningful message and may help isolate the issue.

[0] https://www.semantic-mediawiki.org/wiki/Help:Reporting_bugs
[1] https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs

Cheers

**Comment by JBruceDawson** [comment]
Thanks for the additional info... Unfortunately, when I run 'php maintenance/update.php', I get the following:
------------------
MediaWiki 1.28.0 Updater

mediawiki/semantic-breadcrumb-links: 1.3.1 installed, ~1.3 required.
Error: your composer.lock file is not up to date. Run "composer update" to install newer dependencies
codemeta.com@simon:~/farmergeek/wiki$ php extensions/SemanticMediaWiki/maintenance/rebuildData.php -d 50 -v

Running for storage: SMWSQLStore3

Removing table entries (marked for deletion).

.Set $wgShowExceptionDetails = true; and $wgShowDBErrorBacktrace = true; at the bottom of LocalSettings.php to show detailed debugging informationcodemeta.com@simon:~/farmergeek/wiki$ 
---------------
It looks like the last line was truncated, so I'm not sure if I have the entire error message or not. And note that running 'composer update' again doesn't do much...
------
codemeta.com@simon:~/farmergeek/wiki$ composer update
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
codemeta.com@simon:~/farmergeek/wiki$ php maintenance/update.php 
MediaWiki 1.28.0 Updater

mediawiki/semantic-breadcrumb-links: 1.3.1 installed, ~1.3 required.
Error: your composer.lock file is not up to date. Run "composer update" to install newer dependencies

**Comment by mwjames** [comment]
Do run `php maintenance/update.php --skip-external-dependencies`, see
[0] for some additional information.

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation/Troubleshooting#Error:_your_composer.lock_file_is_not_up_to_date.

Cheers

**Comment by JBruceDawson** [comment]
OK. That worked! Thanks! Now I can get back to work!
