### ISSUE TITLE
Inquiry: SMW updates on article delete

### ISSUE THREAD

**Issue by TK-999** [SemanticMediaWiki/SemanticMediaWiki#2453]
### Setup and configuration

- SMW version: 2.4.0
- MW version: 1.19
- PHP version: 7.0.7
- DB (MySQL etc.): MySQL 5.7

### Issue
I'd like to inquire about the update jobs which are triggered by SMW on article deletion.

As I understand, the `ArticleDelete` hook handler creates and dispatches an instance of `UpdateDispatcherJob`, which then handles creating and dispatching individual `UpdateJob`s as needed. My question is as follows:

 https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Jobs/UpdateDispatcherJob.php#L99 gets all properties for the page that was deleted, and schedules an `UpdateJob` for all pages which share any of these properties. I'd like to ask about this update - how does the page delete affect the semantic data of other pages which share this property? Are there situations where it's possible to avoid having to update all pages which share any property with the page that was deleted without corrupting data?

**Comment by mwjames** [comment]
Hi,

> how does the page delete affect the semantic data of
> other pages which share this property?

A deleted page maybe used as reference on other pages (displayed as
blue link) and after a delete, a user would expect to see a "red" link
on no longer existing references. The `UpdateJob` is mostly dispatched
to correct (invalidate parser cache, null edit) any possible
references for annotations or queries on those connected pages.

After an entity is deleted (== page), Semantic MediaWiki has no longer
any knowledge or reference that would allow it to query references
therefore the `UpdateDispatcherJob` is invoked before the actual data
is removed from the Store to fetch any properties that connects them.

Why use all properties and not query only possible matches? As I said
before, as soon as the data are removed from the Store, we are no
longer able to query them therefore we choose the more broader
approach and avoid having to run queries during the `ArticleDelete`
transaction and possibly block the transaction and instead post the
workload into the job queue for deferred processing. Of course, by the
time the job queue runs `ArticleDelete` was processed and the Store no
longer has any reference to the deleted entity with
`UpdateDispatcherJob` acting on what was transferred in the job
parameters and execute `Store::getAllPropertySubjects`.

Why not use the incoming properties to limit the pool of properties
with a reference? I made a comment in [0] but never follow-up to see
which is more efficient and requires less resources pre/post the
`ArticleDelete` task.

On second thought, maybe it would be more effective (and efficient) to
just use the incoming properties (as those are indicate a known
reference).

```
		// Instead of Store::getSemanticData, construct the SemanticData by
		// attaching only the incoming properties indicating which entities
		// carry an actual reference to this subject
		$semanticData = new SemanticData(
			$subject
		);

		$properties = $store->getInProperties( $subject );

		foreach ( $properties as $property ) {
			// Avoid doing $propertySubjects = $store->getPropertySubjects(
$property, $subject );
			// as it may produce a too large pool of entities and ultimately
			// block the delete transaction
			// Use the subject as dataItem with the UpdateDispatcherJob only
			// scanning Store::getAllPropertySubjects on the property
			$semanticData->addPropertyObjectValue( $property, $subject );
		}

		$parameters['semanticData'] = $semanticDataSerializer->serialize(
			$semanticData
		);

		$jobFactory->newUpdateDispatcherJob( $title, $parameters )->insert();
```

> Are there situations where it's
> possible to avoid having to update all pages which share any property with
> the page that was deleted without corrupting data?

You can, `UpdateDispatcherJob` was deployed for convenience and before
`QueryDependencyLinksStore` as a means to invalidate page references
in queries.

> Are there situations

May I ask what situations we are talking about?

Do we need a setting to generally disable the update of connected
entities on `ArticleDelete`, I'm not sure but any specific use case
will help clarify the scenario.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/src/MediaWiki/Hooks/ArticleDelete.php#L62-L75

Cheers

**Comment by TK-999** [comment]
Hey James, thanks for the quick response!

Let's take the scenario where an user deletes a set of N articles, each of which has properties that collectively have K members - a common maintenance task for wiki administrators. An `UpdateDispatcherJob` spawns for each of these deletions, and each `UpdateDispatcherJob` proceeds to queue an `UpdateJob` for the K members of the properties of the deleted article. We'd end up with N * K `UpdateJob`s, were it not for JobQueue's built-in deduplication handling, which ensures that only K `UpdateJob`s are filed.

The problem was with our custom Wikia setup, since our background task message queue solution does not support deduplication, so in such situations we ended up with N * K `UpdateJob`s waiting in the queue. Of course, this is not an SMW issue, which is why I filed a simple inquiry, not a bug report. :) While we will implement a way to deduplicate the `UpdateJob`s inserted in this situation - there is no other way -, we wondered if it could be possible to reduce the amount of jobs created by the dispatcher in the first place, since such an improvement would benefit every user of SMW. 

The current `ArticleDelete` handler calls `Store::getSemanticData`, serializes the data, then creates an `UpdateDispatcherJob` passing the serialized data in the parameters. However, when the job itself compiles the list of articles to create an `UpdateJob` for, it fetches all properties and incoming properties from the store, fetches all their members, then goes through the properties in the serialized data passed as parameter and adds their members as well before deduplicating the list in `UpdateDispatcherJob::addUniqueSubjectsToUpdateJobList`. And maybe we could spare the two calls to the Store to get incoming properties here if we only pass incoming properties to the job, like you suggested above:
```
		// Instead of Store::getSemanticData, construct the SemanticData by
		// attaching only the incoming properties indicating which entities
		// carry an actual reference to this subject
		$semanticData = new SemanticData(
			$subject
		);

		$properties = $store->getInProperties( $subject );

		foreach ( $properties as $property ) {
			// Avoid doing $propertySubjects = $store->getPropertySubjects(
$property, $subject );
			// as it may produce a too large pool of entities and ultimately
			// block the delete transaction
			// Use the subject as dataItem with the UpdateDispatcherJob only
			// scanning Store::getAllPropertySubjects on the property
			$semanticData->addPropertyObjectValue( $property, $subject );
		}

		$parameters['semanticData'] = $semanticDataSerializer->serialize(
			$semanticData
		);

		$jobFactory->newUpdateDispatcherJob( $title, $parameters )->insert();
```
and only iterate through and create jobs for the members of these properties. But even if we want to create `UpdateJob`s for every member of every property, not just incoming properties, it seems redundant to query the Store a second time for those when they already seem to be in the serialized `SemanticData` fetched in the hook handler.

**Comment by mwjames** [comment]
> But even if we want to create UpdateJobs for every member of every property, not just incoming properties, it seems redundant to query the Store a second time for those when they already seem to be in the serialized SemanticData fetched in the hook handler.

#2460 contains the proposed changes with a slight modification where parameter `RESTRICTED_DISPATCH_POOL` was added to force the `UpdateDispatcherJob` to iterate only over the available `SemanticData` and should address your concern on lookup redundancy.

You could try the proposed solution (be aware the PR needs a bit modification to be used for 2.4.x, e.g. the `HookHandler` class isn't known in 2.4 etc.) and let us know whether this brings some improvement on your end.

**Comment by kghbln** [comment]
Refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2003

**Comment by TK-999** [comment]
Thanks for your quick response and input! It's great to have a solution that won't compromise data integrity - we will report back once we've reapplied these changes.

**Comment by kghbln** [comment]
Improvements will be served with SMW 2.5.3. Either re-apply or perhaps better even upgrade.
