### ISSUE TITLE
WTF James!

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2464]
87% coverage! VAT!

![waaaat](https://cloud.githubusercontent.com/assets/146040/26084484/a46f354e-39dc-11e7-814e-20a96b373bff.gif)

**Comment by mwjames** [comment]
> 87% coverage! VAT!

We reached the 87% some time ago, unfortunately I had to stop the coverage Travis job as it would time-out after 50 min (official cut-off) and trying to use `phpdbg` (https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/phpdbg) wasn't successful either.

**Comment by JeroenDeDauw** [comment]
One more reason to use libraries and have bounded contexts :)

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2057
