### ISSUE TITLE
Limit the number of queries allowed per page

### ISSUE THREAD

**Issue by Reasno** [SemanticMediaWiki/SemanticMediaWiki#2469]
### Setup and configuration

- SMW version:2.4.6
- MW version:1.28
- PHP version:HHVM 3.19
- DB (MySQL etc.):MySQL 5.6

### Issue

After an investigation in the wiki I maintain, I found out the number of queries user made through smw per page is staggering. The most usual abuse is that they want to chain queries in an exponential way. For example: #ask all countries in a page, then #ask all cities in each country and again #ask all members of city councils in each city. 

Having browsed through Manual: Performance Tuning, I noticed that those tips were more focused on limit complex individual query. In vanilla MediaWiki there are expensive parser function counter which help us to limit db query numbers. I wonder if smw offers something similar? Or if SMW supports expensive parser function counter per se?

**Comment by mwjames** [comment]
> I wonder if smw offers something similar?

No.

> if SMW supports expensive parser function counter per se

Not to my knowledge and I would have to inform myself before I can answer this question in a more detailed fashion on whether this would allow to reduce/limit the the amount of #ask per page and to what extend.

> want to chain queries 

On the topic of chaining results, [0] may reduce the amount and the need of chained queries.

>The most usual abuse is that they want to chain queries in an exponential way.

In cases where queries have the same signature, [1] may help reduce and reuse results from a previous computing cycle. The feature is experimental but we can see from the smw.org statistics [2] that reuse is likely, yet we are still conducting research on how much it can actually lower the requirements for computing resources.

More insights and use cases to the mentioned issue are welcome and any pre-work on the "expensive parser function counter" would help lower the time in gathering information about the topic and possible limitations.

As for "Limit the number of queries allowed per page", you could count the number of #ask iterations per page and cut off (or bail-out) if a specific threshold is reached. Of course, those are discriminatory restrictions without any analysis of the queries or context itself. It would be similar to when a shop owner provides a flat of 10 apples per customer without the customer being able to choose between good or bad apples, all s(he) knows is that 10 apples will be provided by the time they leave the shop.

[0] https://www.semantic-mediawiki.org/wiki/Help:Property_chains_and_paths
[1] https://www.semantic-mediawiki.org/wiki/Help:Query_result_cache
[2] https://gist.github.com/mwjames/94bfcd8ca3a3d322b1905199c3828178

**Comment by Reasno** [comment]
Thanks for the fast reply!

I haven't personally experimented with property chains and query cache, but I am sure they can help a lot in many cases. 

As to our particular problem, the issue never was the existence of a refined query solution. It is all about that inexperienced users try to make a big chunk of inefficient queries in their template hell without even knowing the consequences. Those queries occasionally slow the entire site down, and make the already painful data purging/rebuilding process even more so.

As a side note, our users have a tendency to change properties to text type. This allows them to make complicated string manipulations. Property chains therefore often must be done by hand.

Wikipedia has a philosophy that every end user should be free from the responsibility to care about performance. I wonder if this still holds true in terms of semantic mediawiki. While I am trying to educate them about performance, I want some way to add awareness among editors.

Discriminatory as it is, I still want to reuse "expensive parser function counter". It is the solution mw core is using. I wonder if there is a hook invoked on each #ask, so that I can do that myself?

**Comment by mwjames** [comment]
This is a very quick note off the top of my head and as I mentioned before I haven't look at "expensive parser function counter" on how it can be used in connection with #ask.

> I wonder if there is a hook invoked on each #ask, so that I can do that myself?

The parser function #ask [0] itself has no hook but you may use `SMW::Store::BeforeQueryResultLookupComplete` [1] to suppress any result lookup and return an empty `QueryResult` object that can also contain an error record so that a user gets informed as to why the query was denied.

```
/**
 * Hook to be run before the actual lookup process
 */
Hooks::register( 'SMW::Store::BeforeQueryResultLookupComplete', function ( $store, $query, &$queryResult, $queryEngine ) {

	// Inspect the $query object (SMWQuery)
	//

	// Allow default processing
	return true;


	// Stop further processing
	return false;
};
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/ParserFunctions/AskParserFunction.php
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/hooks.md#smwstorebeforequeryresultlookupcomplete

**Comment by mwjames** [comment]
Hijacking this thread ...

> It is all about that inexperienced users try to make a big chunk of inefficient queries in their template hell without even knowing the consequences.

@kghbln @s7eph4n Quick note for 3.* (minor brainstorming) on:
- allow to define different query user profiles (size, depth, amount per page, per template etc.)
- assignable as role to user and is compared by the time a #ask query is created
- is feasible? is needed? use cases? technical realization?
- what about anon users?

**Comment by kghbln** [comment]
To me integrating with [`$wgExpensiveParserFunctionLimit`](https://www.mediawiki.org/wiki/Manual:$wgExpensiveParserFunctionLimit) or providing a similar SMW related setting appears to be the easiest solution. Once such a limit is reached a semantic wiki will have to knowingly raise the limit and/or deal with ineffective user voodoo regardless who added or uses the queries. Awareness of such an issue on the wiki is thus triggered by the setting.

**Comment by s7eph4n** [comment]
Generating config profiles could help to make the settings more accessible in general, e.g. they could provide sensible combinations of $smwgQMaxDepth, $smwgQMaxInlineLimit, $smwgQMaxLimit, $smwgQMaxSize, $smwgQPrintoutLimit, ....., but I am not sure if/how they could be set on a per user/usergroup basis. For Special:Ask that's probably feasible, but for inline queries?

How would that work with the parser cache? Would that mean that if a sysop refreshes a page they get the whole picture while a normal user only gets a limited result? So each time a user changes a page with such a query they would need a sysop to purge the page?

And to be honest, I am not sure if the effort to develop this feature (and the added complexity SMW users have to deal with) would be justified. I suspect the more complex the data in a wiki is the more limited the number of inexperienced editors will be. The above of course is already a counterexample, so I am probably totally wrong.

I think in the end I am with @kghbln: Offering something similar to `$wgExpensiveParserFunctionLimit` (or maybe a `$smwgQMaxLimitPerPage`) could be all that's needed. Plus educating the users, but that'd be the task of the wiki owner.

**Comment by mwjames** [comment]
> I think in the end I am with @kghbln: Offering something similar to $wgExpensiveParserFunctionLimit (or maybe a $smwgQMaxLimitPerPage) could be all that's needed.

I just wanted to keep an open ear before creating a prototype.

> creating a prototype.

#2476 contains the prototype (without tests so before merging it requires a bit more work) and outlines the direction of what can be supported without increasing complexity and configuration "hell".

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Restrict_query_execution
