### ISSUE TITLE
/i18n vs /languages directory

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#247]
Based on the [gerrit121356][121356] change, having a `/i18n` and a `/languages` directory does not make much sense therefore consolidation is recommended.

[121356]:https://gerrit.wikimedia.org/r/#/c/121356/

**Comment by kghbln** [comment]
Changed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1896 as a follow up to https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1848. Now we only have a /i18n directory.

**Comment by kghbln** [comment]
I understand that magic words and aliases still need to be handled differently in contrast to regular system messages.
