### ISSUE TITLE
Search of part of string is not working with FulltextSearch enabled

### ISSUE THREAD

**Issue by sommer-gei** [SemanticMediaWiki/SemanticMediaWiki#2489]
### Setup and configuration

Setup at https://sandbox.semantic-mediawiki.org/wiki/Special:Version

### Issue

Hi!

In my local environment I enabled `$smwgEnabledFulltextSearch = true;` and my not case-sensitive search worked like a charme! :-)

But then I realised that the **search for a part of property string isn’t working** anymore. − Is that a known problem?

Thanks in advance!

----
**Example** (for my local MW installation and the SMW [sandbox](https://sandbox.semantic-mediawiki.org)):

Search for `[[Foaf:name::~*john*]]` is working well: https://sandbox.semantic-mediawiki.org/w/index.php?title=Special:Ask&x=-5B-5BFoaf%3Aname%3A%3A~%2Ajohn%2A-5D-5D

Search for `[[Foaf:name::~*ohn*]]` is **not** working well: https://sandbox.semantic-mediawiki.org/w/index.php?title=Special:Ask&x=-5B-5BFoaf%3Aname%3A%3A~%2Aohn%2A-5D-5D

(ref. for this issue: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1481#issuecomment-305208840)

**Comment by mwjames** [comment]
Hi,

> Search for `[[Foaf:name::~*john*]]` is working well:
> https://sandbox.semantic-mediawiki.org/w/index.php?title=Special:Ask&x=-5B-5BFoaf%3Aname%3A%3A~%2Ajohn%2A-5D-5D
>
> Search for `[[Foaf:name::~*ohn*]]` is **not** working well:
> https://sandbox.semantic-mediawiki.org/w/index.php?title=Special:Ask&x=-5B-5BFoaf%3Aname%3A%3A~%2Aohn%2A-5D-5D

I'm pretty sure this relates to the min token setting which we check
in [0, 1] and somewhere on the original issue I left some comments
about it.

`>=` (in [0, 1]) means that min is used which by default is 3 as far
as I remember but I cannot recall what the MySQL/MariaDB docu has to
say about it. There is also a difference between InnoDB and Myisam.

If you switch to lower token size (~*oh*) as min then the system
switches on using the "old" LIKE comparison which of course is not a
full-text index.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/Fulltext/SearchTable.php#L226-L228

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/Fulltext/MySQLValueMatchConditionBuilder.php#L43-L50

Cheers

**Comment by mwjames** [comment]
It goes without saying that any change to the settings either SMW or
DB (min token, stop words etc.) related in connection with the
full-text index requires to run the full-text rebuild script.

Cheers

**Comment by kghbln** [comment]
Ah, ok, did not recall [the setting documented here.](https://www.semantic-mediawiki.org/wiki/Help:$smwgFulltextSearchMinTokenSize)

**Comment by sommer-gei** [comment]
Thanks for your input! − I tested a little bit and have to say: no, `$smwgFulltextSearchMinTokenSize` in’t the problem. :-|

Let me show you another example with the sandbox.

Search for `[[Has text::~*reCurring*]]` (= a whole word) is working well (= 26 results): https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&x=-5B-5BHas-20text%3A%3A~%2AreCurring%2A-5D-5D

Search for `[[Has text::~*eCurring*]]` (= **part** of a whole word) is **not** working (= no results): https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&x=-5B-5BHas-20text%3A%3A~%2AeCurring%2A-5D-5D

Sry + thx!

**Comment by mwjames** [comment]
Hi,

> Thanks for your input! − I tested a little bit and have to say: no,
> `$smwgFulltextSearchMinTokenSize` in’t the problem. :-|

For the first cited example it does relate to the token size.

> Search for `[[Has text::~*reCurring*]]` (= a whole word) is working well (=
> 26 results):
> https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&x=-5B-5BHas-20text%3A%3A~%2AreCurring%2A-5D-5D
>
> Search for `[[Has text::~*eCurring*]]` (= **part** of a whole word) is
> **not** working (= no results):
> https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&x=-5B-5BHas-20text%3A%3A~%2AeCurring%2A-5D-5D

This is a different issue that relates to the full-text index itself.

You can test the actual SQL output using the debug=true parameter. The
SQL returns different results for:

`(MATCH(t1.o_text) AGAINST ('*recurring*' IN BOOLEAN MODE) AND
t1.p_id=108)` [0] vs.
`(MATCH(t1.o_text) AGAINST ('*ecurring*' IN BOOLEAN MODE) AND t1.p_id=108)` [1].

This is an issue with index or better how MySQL is creating word
tokens and running the SQL directly on the DB it will result in the
same findings.

Using something like `[[Has text::~*reCurr*]]` or `[[Has
text::~reCurr*]] will definitely work.

I don't really have time to dig through the documentation [2] but I
suspect some answers can be found on stackoverflow [3].

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&debug=true&q=[[Has+text%3A%3A~*reCurring*]]&po=&eq=yes&p[format]=broadtable&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=...+further+results&p[default]=&p[class]=sortable+wikitable+smwtable&p[sep]=&eq=yes

[1] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&debug=true&q=[[Has+text%3A%3A~*eCurring*]]&po=&eq=yes&p[format]=broadtable&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=...+further+results&p[default]=&p[class]=sortable+wikitable+smwtable&p[sep]=&eq=yes

[2] https://dev.mysql.com/doc/refman/5.7/en/fulltext-boolean.html
[3] https://stackoverflow.com/questions/20679696/wildcard-search-in-mysql-full-text-search

Cheers

**Comment by mwjames** [comment]
On a prefixed wildcard search, see also:

* https://stackoverflow.com/questions/7848445/how-to-use-prefix-wildcards-like-abc-with-match-against
* https://forums.mysql.com/read.php?107,113504,113504

[0] notes "The wildcarded word is considered as a prefix that must be
present at the start of one or more words. ..."

[0] https://dev.mysql.com/doc/refman/5.7/en/fulltext-boolean.html

**Comment by mwjames** [comment]
@kghbln Just to paint the full picture, the reason why #2558 was introduced is this use case. Since the full text can not match a wildcard within a word (see above notes on the prefix issue), using `like:`  will give a users a possibility to search within a word using `*` with the limitation that such search can not be applied for strings longer than 255 chars or in case of `SMW_FIELDT_CHAR_LONG` 300 chars at most anything beyond requires the full-text but is prone to the outlined restrictions.

**Comment by mwjames** [comment]
An explanation and an approach to overcome the deficiency for this use case has been outlined hence closing this issue as no more actionable tasks can be assigned.
