### ISSUE TITLE
When mainlabel specified an extra mainlabel parameter is added in the further results link

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#249]
Import from https://bugzilla.wikimedia.org/show_bug.cgi?id=34749

SMW 1.7.0.0.2 MW 1.18

This query:

{{#ask: [[Anything]] 
 | mainlabel=Anymainlabel 
}}

Will be changed to this query, when clicking on "further results":

{{#ask: [[Anything]] 
 | mainlabel=Anymainlabel 
 | ?=Anymainlabel#
}}

Notice that this part is added by the further results URL query string:

?=Anymainlabel#

The relevant further results url query string is:

/Special:Ask/-5B-5BAnything-5D-5D/-3F%3DAnymainlabel-23/mainlabel%3DAnymainlabel/

When it should be:

/Special:Ask/-5B-5BAnything-5D-5D/mainlabel%3DAnymainlabel/

Note that the query string is produced correctly if it starts out as it would otherwise be incorrectly done. This:

{{#ask: [[Anything]] 
 | mainlabel=Anymainlabel 
 | ?=Anymainlabel#
}}

Will produce this:

/Special:Ask/-5B-5BAnything-5D-5D/-3F%3DAnymainlabel-23/mainlabel%3DAnymainlabel/

Just like it should.

This bug is all that look similar when I searched prior to entering this bug. It might be somehow related:

https://bugzilla.wikimedia.org/show_bug.cgi?id=23722

--  badon 2012-02-27 03:48:31 UTC

**Comment by mwjames** [comment]
@kghbln Is this solved by #541?

**Comment by kghbln** [comment]
Affirmative as the [field test](http://sandbox.semantic-mediawiki.org/wiki/Issue/249) shows. Thanks!
