### ISSUE TITLE
Export formats use their own hard-coded default value, but should use $smwgQDefaultLimit

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#2505]
Export formats use their own default value which is hard-coded [0] independent of $smwgQDefaultLimit. 

From a users perspective, there is no difference between displaying data and exporting data, this behaviour is not optimal.
|format=table uses $smwgQDefaultLimit
|format=csv does not use $smwgQDefaultLimit.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/CsvResultPrinter.php#L123

The same might be true with https://www.semantic-mediawiki.org/wiki/Help:$smwgQMaxInlineLimit ...

**Comment by kghbln** [comment]
I believe making the hard coded value into a value obeying to a setting made with a configuration paramter is a good idea. I think it should be `$smwgQDefaultLimit`. Since the csv format does not initially show anything until being clicked `$smwgQMaxInlineLimit` does not fit.

**Comment by krabina** [comment]
fine with me :-)

**Comment by kghbln** [comment]
[Example](https://sandbox.semantic-mediawiki.org/wiki/Issue/2505)
