### ISSUE TITLE
SMW\Exception\SubSemanticDataException from line 206 of SubSemanticData.php

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2507]
### Setup and configuration

- MediaWiki 	1.27.3 (798ceea) 21:03, 30 April 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MySQL 	5.5.55-0+deb8u1
- Semantic MediaWiki	2.5.2 (84007ca) 09:45, 17 May 2017

### Issue
```
SMW\Exception\SubSemanticDataException from line 206 of /../w/extensions/SemanticMediaWiki/src/DataModel/SubSemanticData.php: Data for a subobject of Foo cannot be added to Bar.
```
It could be that invalid values were to be added however the procedure should probably fail more gracefully.

### Backtrace
```
#0 /../w/extensions/SemanticMediaWiki/includes/SemanticData.php(720): SMW\DataModel\SubSemanticData->addSubSemanticData(SMW\DataModel\ContainerSemanticData)
#1 /../w/extensions/SemanticMediaWiki/includes/SemanticData.php(388): SMW\SemanticData->addSubSemanticData(SMW\DataModel\ContainerSemanticData)
#2 /../w/extensions/SemanticMediaWiki/src/Deserializers/SemanticDataDeserializer.php(145): SMW\SemanticData->addPropertyObjectValue(SMW\DIProperty, SMWDIContainer)
#3 /../w/extensions/SemanticMediaWiki/src/Deserializers/SemanticDataDeserializer.php(89): SMW\Deserializers\SemanticDataDeserializer->doDeserializeDataItem(SMW\DIProperty, array, array, SMW\SemanticData)
#4 /../w/extensions/SemanticMediaWiki/src/Deserializers/SemanticDataDeserializer.php(55): SMW\Deserializers\SemanticDataDeserializer->doDeserialize(array, SMW\SemanticData)
#5 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateDispatcherJob.php(148): SMW\Deserializers\SemanticDataDeserializer->deserialize(array)
#6 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateDispatcherJob.php(106): SMW\MediaWiki\Jobs\UpdateDispatcherJob->addUpdateJobsFromDeserializedSemanticData()
#7 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateDispatcherJob.php(69): SMW\MediaWiki\Jobs\UpdateDispatcherJob->dispatchUpdateForSubject(SMW\DIWikiPage)
#8 /../w/includes/jobqueue/JobRunner.php(265): SMW\MediaWiki\Jobs\UpdateDispatcherJob->run()
#9 /../w/includes/jobqueue/JobRunner.php(179): JobRunner->executeJob(SMW\MediaWiki\Jobs\UpdateDispatcherJob, BufferingStatsdDataFactory, integer)
#10 /../w/maintenance/runJobs.php(93): JobRunner->run(array)
#11 /../w/maintenance/doMaintenance.php(103): RunJobs->execute()
#12 /../w/maintenance/runJobs.php(127): require_once(string)
#13 {main}
```

**Comment by mwjames** [comment]
> SMW\Exception\SubSemanticDataException from line 206 of
> /../w/extensions/SemanticMediaWiki/src/DataModel/SubSemanticData.php: Data
> for a subobject of Foo cannot be added to Bar.

The exception is thrown on purpose, and `Foo` and `Bar` seems rather
odd entities.

/../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateDispatcherJob.php(106):
> SMW\MediaWiki\Jobs\UpdateDispatcherJob->addUpdateJobsFromDeserializedSemanticData()

It was triggered from a `UpdateDispatcherJob`, so there aren't much
processes that use the dispatcher, some context would be good.

**Comment by kghbln** [comment]
> The exception is thrown on purpose, and `Foo` and `Bar` seems rather odd entities.

These entities are obfuscated. Need to investigate from the timestamp what happened there. I suspect a fullstop within a property value.

**Comment by kghbln** [comment]
As far as I can see the following was attempted: on page "Bar" a value of "{{{addValue}}}" was attempted to be added to a property of type "Page" within the suboject called "Foo". As a result a user facing warning was issued.

If I interpret your response correctly SMW purposely also logs exceptions for this additionally to telling the user directly that she or he did something wrong.

**Comment by kghbln** [comment]
I am not sure if this is probably to much noise since the user was indeed informed about the issue via the user interface, i.e. wiki page.
