### ISSUE TITLE
Obtain real data (not cached)

### ISSUE THREAD

**Issue by antohabio** [SemanticMediaWiki/SemanticMediaWiki#2508]
### Setup and configuration

- SMW version: current
- MW version: current
- PHP version:
- DB (MySQL etc.): MySQL

### Issue

Caching in 99% of cases is good. However, in some cases, actual data are required.
For example: in the organizations directory it is necessary to obtain the status - at the moment the organization is currently running or not. I compare the current time and schedule of the organization. If I reset the cache, then I see the actual data, and if I do not reset it is not. I can write the status information into a property and request it on another page and again the data is not actual.

Is it possible at this time to get the actual value of the property? Is it planned to implement such a functional?

**Comment by kghbln** [comment]
Have you tried the `__NOCACHE__` behaviour switch provided by the [MagicNoCache extension](https://www.mediawiki.org/wiki/Extension:MagicNoCache). You could also check if [embedded query update feature](https://www.semantic-mediawiki.org/wiki/Help:Embedded_query_update) works for you.

**Comment by mwjames** [comment]
Okay, this needs elaboration!

> Caching in 99% of cases is good. However, in some cases, actual data are
> required.

What cache are we talking about? The page cache (or more precisely the
ParserCache)?

> compare the current time and schedule of the organization. If I reset the
> cache, then I see the actual data, and if I do not reset it is not. I can

What does it mean? Do you press the purge button [0] to reset the cache?

> write the status information into a property and request it on another page
> and again the data is not actual.

Are we talking about a query here?

> Is it possible at this time to get the actual value of the property? Is it
> planned to implement such a functional?

In case we are talking about an auto-query update then I suggest you
have a look at [1].

[0] https://www.semantic-mediawiki.org/wiki/Null_edit
[1] https://www.semantic-mediawiki.org/wiki/Help:Embedded_query_update

Cheers

**Comment by kghbln** [comment]
@antohabio Any thoughts an input?

**Comment by antohabio** [comment]
Sorry for the long answer.
I will give a small example to make it clearer.

I have a page "Company". This page contains property "OpenNow?" (yes/no) {{#set:OpenNow={{{FieldFromTemplate}}} }}
And i have page with list of companies. On this page i request property "OpenNow?" form pages of companies - {{#ask: [[Category:Companies]] |?OpenNow}}

If the property on the company page is not updated, then on the companies page, the same property value will always be displayed.

Is it possible to query the **updated** value on the company page?

**Comment by kghbln** [comment]
It looks like you should make use of the embedded query update feature.

> If the property on the company page is not updated, then on the companies page, the same property value will always be displayed.

If you do not update the company page values on the company list page will not update either. I guess however that the "not" slipped in here by accident.

**Comment by kghbln** [comment]
You could probably also use the `--query` option to the "rebuildData.php" script to do a fine graned data rebuild on a higher frequency, e.g. `php rebuildData.php --quiet --query='[[Category:Company]]'`. However I still believe that the embedded query update as already mentioned should serve your use case.

Feel free to reopen if new information on this arises.
