### ISSUE TITLE
New defined properties do somehow not get registered in SMW

### ISSUE THREAD

**Issue by kettner** [SemanticMediaWiki/SemanticMediaWiki#2511]
### Setup and configuration

- SMW version: 2.5.2
- MW version: 1.28.1
- PHP version: 5.6.30 (fpm-fcgi)
- DB (MySQL etc.): MySQL 5.6.23-log

### Issue

New defined properties do not get registered well such that they can hold a value.
- Property defined at: http://csdms.colorado.edu/wiki/Property:ModelDomain
- Template that holds property: http://csdms.colorado.edu/wiki/Template:Model_identity2
- PageForm that setup page: http://csdms.colorado.edu/wiki/Form:Module_questionnaire
- Example where values assigned to property 'ModelDomain' do not get handled well: http://csdms.colorado.edu/wiki/Model:Testasdfinafg

I have repopulate the SMWSQLStore3 by:
- php ./setupStore.php --delete --backend SMWSQLStore3; followed by:
- php ./rebuildData.php -fv

No luck. Property 'ModelDomain' does show up in the property list: 
- http://csdms.colorado.edu/mediawiki/index.php?title=Special:Properties&limit=500&offset=0 (property 251)
But the list indicates that 'ModelDomain' isn't used (but is on ~280 pages or so).

Any suggestion on what to do to get this fixed?
Albert

**Comment by mwjames** [comment]
> - Example where values assigned to property 'ModelDomain' do not get handled
> well: http://csdms.colorado.edu/wiki/Model:Testasdfinafg

<swivt:page rdf:resource="http://csdms.colorado.edu/wiki/Model-3ATestasdfinafg"/>
<swivt:wikiNamespace
rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">3002</swivt:wikiNamespace>

I suspect you did not enable the namespace [0] as described in [1].

[0] https://www.semantic-mediawiki.org/wiki/Help:Namespaces
[1] https://www.semantic-mediawiki.org/wiki/Help:Custom_namespaces

Cheers

**Comment by kettner** [comment]
I wish it was that simple; the specific namespace 'Model' is included though for SMW: $smwgNamespacesWithSemanticLinks[3002] = true; (defined in LocalSettings.php)
And earlier defined properties for that namespace work totally fine.

**Comment by mwjames** [comment]
> - Property defined at: http://csdms.colorado.edu/wiki/Property:ModelDomain
> - Template that holds property:
> http://csdms.colorado.edu/wiki/Template:Model_identity2

```
| class="model_col1"| Model domain
| class="model_col2"|{{#arraymap:{{{ModelDomain|}}}|,|x|[[ModelDomain:x]]}}
```

Can you see what's wrong with this? I small hint `:` vs. `::`.

**Comment by kettner** [comment]
Ooo, man, this is embarrassing. I'll blame it on the Friday afternoon, brain dead. Thank you!!!!!!
