### ISSUE TITLE
Add  HtmlValidator to improve JSONScript testing

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#2531]
[SRF #227](https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/227) introduced an [HtmlValidator](https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/227/files#diff-dbb23ada6cc8a0c62a9544357e511101) class that allows to make assertions on the HTML structure of the MW parser output in JSONScript integration tests:
* general validity of the HTML
* existence of substructures using CSS-like accessors

See [Filtered-01.json](https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/227/files#diff-64ee1463816d6dcd0875d8903677c517R140) for an example.

I think this could benefit maybe SMW, but certainly other SMW-dependent extensions, like SG, so I'd like to include it in SMW instead of SRF.

Thoughts?

**Comment by mwjames** [comment]
> Thoughts?

Go ahead. (... and maybe a quick note in the README)

**Comment by mwjames** [comment]
@s7eph4n ping!
