### ISSUE TITLE
Multi-database environment, RuntimeException on Error: 1146 Table 'wiki_eva.t3' doesn't exist

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticMediaWiki#2532]
### Setup and configuration

- SMW version: 2.5.2
- MW version: 1.27.2
- PHP version: 5.6.30
- DB (MySQL etc.): 5.5.52-MariaDB DB_MASTER + (1) DB_REPLICA

### Issue

The following error occurs when attempting to view a page with SMW content on it with a DB_MASTER and a single DB_SLAVE configured. The error does **NOT** occur in the following scenarios:

* If the DB_SLAVE is removed from `$wgDBservers` in LocalSettings.php (i.e. a normal single-DB configuration)
* If SMW+SRF are removed via composer and all other SMW-based extensions are removed from LocalSettings.php (i.e. remove SMW and things dependent upon it from the configuration)
* If SMW and all SMW-based extensions are **enabled**, and the second database server is in `$wgDBservers`, but all instances of `DB_SLAVE` in SMW's codebase are converted to `DB_MASTER` via `cd /path/to/smw && sudo find . -type f -exec sed -i 's/DB_SLAVE/DB_MASTER/g' {} +` (i.e. don't ever use DB_SLAVE)

Due to the tests above, I believe that there is at least one case of `DB_SLAVE` that should be `DB_MASTER`. On SMW v2.5.2 I count nine instances of `DB_SLAVE`, so it shouldn't be too difficult to narrow down which are the offenders. I will figure that out tomorrow, but wanted to get this issue in before I go to sleep.

Error message:
```
Exception encountered, of type "RuntimeException"
[WVPYjvrJNCT5cyqAw0wKuQAAAAk] /eva/index.php/STS-72 RuntimeException from line 226 of /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Database.php: A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT DISTINCT t0.smw_id AS id,t0.smw_title AS t,t0.smw_namespace AS ns,t0.smw_iw AS iw,t0.smw_subobject AS so,t0.smw_sortkey AS sortkey,t8.o_sortkey FROM `smw_object_ids` AS t0 INNER JOIN `smw_fpt_inst` AS t2 ON t0.smw_id=t2.s_id INNER JOIN `t3` AS t3 ON t2.o_id=t3.id INNER JOIN `smw_di_wikipage` AS t4 ON t2.s_id=t4.s_id INNER JOIN `smw_di_time` AS t8 ON t0.smw_id=t8.s_id WHERE ((t4.p_id='1908')) AND (t8.p_id='2116') AND t0.smw_iw!=':smw' AND t0.smw_iw!=':smw-delete' AND t0.smw_iw!=':smw-redi' ORDER BY t8.o_sortkey DESC LIMIT 6
Function: SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult
Error: 1146 Table 'wiki_eva.t3' doesn't exist (<redacted IP address of DB_SLAVE>)


#0 /opt/htdocs/mediawiki/includes/db/Database.php(901): DatabaseBase->reportQueryError('Table 'wiki_eva...', 1146, 'SELECT DISTINC...', 'SMW\\SQLStore\\Qu...', false)
#1 /opt/htdocs/mediawiki/includes/db/Database.php(1234): DatabaseBase->query('SELECT DISTINC...', 'SMW\\SQLStore\\Qu...')
#2 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(224): DatabaseBase->select('`smw_object_ids...', 'DISTINCT t0.smw...', '((t4.p_id='1908...', 'SMW\\SQLStore\\Qu...', Array, Array)
#3 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(415): SMW\MediaWiki\Database->select('`smw_object_ids...', 'DISTINCT t0.smw...', '((t4.p_id='1908...', 'SMW\\SQLStore\\Qu...', Array)
#4 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(225): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult(Object(SMWQuery), 0)
#5 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(330): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(Object(SMWQuery))
#6 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(318): SMWSQLStore3->fetchQueryResult(Object(SMWQuery))
#7 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(406): SMWSQLStore3->getQueryResult(Object(SMWQuery))
#8 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(211): SMWQueryProcessor::getResultFromQuery(Object(SMWQuery), Array, 2, 1001)
#9 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(136): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(Array)
#10 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(298): SMW\ParserFunctions\AskParserFunction->parse(Array)
#11 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Object(Parser), '[[Category:Miss...', 'limit =1', 'sort = Launch d...', 'order = desc', 'searchlabel=')
#12 /opt/htdocs/mediawiki/includes/parser/Parser.php(3812): call_user_func_array(Object(Closure), Array)
#13 /opt/htdocs/mediawiki/includes/parser/Parser.php(3547): Parser->callParserFunction(Object(PPTemplateFrame_DOM), '#ask', Array)
#14 /opt/htdocs/mediawiki/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(Array, Object(PPTemplateFrame_DOM))
#15 /opt/htdocs/mediawiki/includes/parser/Parser.php(3689): PPFrame_DOM->expand(Object(PPNode_DOM))
#16 /opt/htdocs/mediawiki/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(Array, Object(PPFrame_DOM))
#17 /opt/htdocs/mediawiki/includes/parser/Parser.php(3361): PPFrame_DOM->expand(Object(PPNode_DOM), 0)
#18 /opt/htdocs/mediawiki/includes/parser/Parser.php(1248): Parser->replaceVariables('{{Mission\n|Miss...')
#19 /opt/htdocs/mediawiki/includes/parser/Parser.php(446): Parser->internalParse('{{Mission\n|Miss...')
#20 /opt/htdocs/mediawiki/includes/content/WikitextContent.php(331): Parser->parse('{{Mission\n|Miss...', Object(Title), Object(ParserOptions), true, true, 115523)
#21 /opt/htdocs/mediawiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Object(Title), 115523, Object(ParserOptions), true, Object(ParserOutput))
#22 /opt/htdocs/mediawiki/includes/poolcounter/PoolWorkArticleView.php(140): AbstractContent->getParserOutput(Object(Title), 115523, Object(ParserOptions))
#23 /opt/htdocs/mediawiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#24 /opt/htdocs/mediawiki/includes/page/Article.php(666): PoolCounterWork->execute()
#25 /opt/htdocs/mediawiki/includes/actions/ViewAction.php(44): Article->view()
#26 /opt/htdocs/mediawiki/includes/MediaWiki.php(493): ViewAction->show()
#27 /opt/htdocs/mediawiki/includes/MediaWiki.php(288): MediaWiki->performAction(Object(Article), Object(Title))
#28 /opt/htdocs/mediawiki/includes/MediaWiki.php(735): MediaWiki->performRequest()
#29 /opt/htdocs/mediawiki/includes/MediaWiki.php(509): MediaWiki->main()
#30 /opt/htdocs/mediawiki/index.php(43): MediaWiki->run()
#31 {main}
Backtrace:
#0 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(415): SMW\MediaWiki\Database->select(string, string, string, string, array)
#1 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(225): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult(SMWQuery, integer)
#2 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(330): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(SMWQuery)
#3 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(318): SMWSQLStore3->fetchQueryResult(SMWQuery)
#4 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(406): SMWSQLStore3->getQueryResult(SMWQuery)
#5 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(211): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#6 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(136): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array)
#7 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(298): SMW\ParserFunctions\AskParserFunction->parse(array)
#8 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string)
#9 /opt/htdocs/mediawiki/includes/parser/Parser.php(3812): call_user_func_array(Closure, array)
#10 /opt/htdocs/mediawiki/includes/parser/Parser.php(3547): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#11 /opt/htdocs/mediawiki/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#12 /opt/htdocs/mediawiki/includes/parser/Parser.php(3689): PPFrame_DOM->expand(PPNode_DOM)
#13 /opt/htdocs/mediawiki/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#14 /opt/htdocs/mediawiki/includes/parser/Parser.php(3361): PPFrame_DOM->expand(PPNode_DOM, integer)
#15 /opt/htdocs/mediawiki/includes/parser/Parser.php(1248): Parser->replaceVariables(string)
#16 /opt/htdocs/mediawiki/includes/parser/Parser.php(446): Parser->internalParse(string)
#17 /opt/htdocs/mediawiki/includes/content/WikitextContent.php(331): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#18 /opt/htdocs/mediawiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#19 /opt/htdocs/mediawiki/includes/poolcounter/PoolWorkArticleView.php(140): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#20 /opt/htdocs/mediawiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#21 /opt/htdocs/mediawiki/includes/page/Article.php(666): PoolCounterWork->execute()
#22 /opt/htdocs/mediawiki/includes/actions/ViewAction.php(44): Article->view()
#23 /opt/htdocs/mediawiki/includes/MediaWiki.php(493): ViewAction->show()
#24 /opt/htdocs/mediawiki/includes/MediaWiki.php(288): MediaWiki->performAction(Article, Title)
#25 /opt/htdocs/mediawiki/includes/MediaWiki.php(735): MediaWiki->performRequest()
#26 /opt/htdocs/mediawiki/includes/MediaWiki.php(509): MediaWiki->main()
#27 /opt/htdocs/mediawiki/index.php(43): MediaWiki->run()
#28 {main}
```

**Comment by mwjames** [comment]
A very quick answer that might accelerate your investigation.

> Query: SELECT DISTINCT t0.smw_id AS id,t0.smw_title AS t,t0.smw_namespace AS ns,t0.smw_iw AS iw,t0.smw_subobject AS so,t0.smw_sortkey AS sortkey,t8.o_sortkey FROM `smw_object_ids` AS t0 INNER JOIN `smw_fpt_inst` AS t2 ON t0.smw_id=t2.s_id INNER JOIN `t3` AS t3 ON t2.o_id=t3.id INNER JOIN `smw_di_wikipage` AS t4 ON t2.s_id=t4.s_id INNER JOIN `smw_di_time` AS t8 ON t0.smw_id=t8.s_id WHERE ((t4.p_id='1908')) AND (t8.p_id='2116') AND t0.smw_iw!=':smw' AND t0.smw_iw!=':smw-delete' AND t0.smw_iw!=':smw-redi' ORDER BY t8.o_sortkey DESC LIMIT 6
Function: SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult
Error: 1146 Table 'wiki_eva.t3' doesn't exist (<redacted IP address of
DB_SLAVE>)

I can infer from your query that it involves a hierarchy (i.e. a
category condition with some form of hierarchy) which is managed as
"t3" temporary table and by all means should be appropriately
replicated to all your DB instances.

I'm guessing that due to your setup something is messing with the temp
tables because under normal circumstances there are no issues with a
`SELECT` in SMW. A `SELECT` is always executed on a `DB_SLAVE`
instance as it only involves reading, not writing data.

In your particular example, the data for `t3` is made available by [0]
and when using `$wgDebugDumpSql  = true;` you should be able to log DB
activities in more granular exposition and is expected to contain
something like:

```
[DBQuery] mw-master SELECT /*
SMW\SQLStore\QueryEngine\QuerySegmentListProcessor::resolveHierarchyForSegment
 */  s_id  FROM `smw_fpt_subc`    WHERE o_id='180867'  LIMIT 1
[DBQuery] mw-master SHOW /*
Wikimedia\Rdbms\DatabaseMysqlBase::serverIsReadOnly  */ GLOBAL
VARIABLES LIKE 'read_only'
[DBQuery] mw-master CREATE /*
SMW\SQLStore\TableBuilder\TemporaryTableBuilder::create  */ TEMPORARY
TABLE `t3`( id INT UNSIGNED KEY ) ENGINE=MEMORY
[DBQuery] mw-master CREATE /*
SMW\SQLStore\TableBuilder\TemporaryTableBuilder::create  */ TEMPORARY
TABLE smw_new( id INT UNSIGNED KEY ) ENGINE=MEMORY
[DBQuery] mw-master CREATE /*
SMW\SQLStore\TableBuilder\TemporaryTableBuilder::create  */ TEMPORARY
TABLE smw_res( id INT UNSIGNED KEY ) ENGINE=MEMORY
[DBQuery] mw-master INSERT /*
SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTableFor
*/ IGNORE INTO `t3` (id) VALUES ('180867')
[DBQuery] mw-master INSERT /*
SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTableFor
*/ IGNORE INTO smw_new (id) VALUES ('180867')
[DBQuery] mw-master INSERT /*
SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTableFor
*/ IGNORE INTO smw_res (id) SELECT s_id FROM `smw_fpt_subc`, smw_new
WHERE o_id=id
[DBQuery] mw-master INSERT /*
SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTableFor
*/ IGNORE INTO `t3` (id) SELECT smw_res.id FROM smw_res
[DBQuery] mw-master TRUNCATE /*
SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTableFor
*/ TABLE smw_new
[DBQuery] mw-master INSERT /*
SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTableFor
*/ IGNORE INTO smw_new (id) SELECT s_id FROM `smw_fpt_subc`, smw_res
WHERE o_id=id
[DBQuery] mw-master DROP /*
SMW\SQLStore\TableBuilder\TemporaryTableBuilder::drop  */ TEMPORARY
TABLE smw_res
[DBQuery] mw-master DROP /*
SMW\SQLStore\TableBuilder\TemporaryTableBuilder::drop  */ TEMPORARY
TABLE smw_new
[DBQuery] mw-master SELECT /*
SMW\SQLStore\QueryEngine\QuerySegmentListProcessor::resolveHierarchyForSegment
 */  s_id  FROM `smw_fpt_subp`    WHERE o_id='180864'  LIMIT 1
[DBQuery] mw-master SELECT /*
SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult  */
DISTINCT t0.smw_id AS id,t0.smw_title AS t,t0.smw_namespace AS
ns,t0.smw_iw AS iw,t0.smw_subobject AS so,t0.smw_sortkey AS
sortkey,t0.smw_sort  FROM `smw_object_ids` AS t0 INNER JOIN
`smw_fpt_inst` AS t2 ON t0.smw_id=t2.s_id INNER JOIN `t3` AS t3 ON
t2.o_id=t3.id INNER JOIN `smw_di_blob` AS t4 ON t2.s_id=t4.s_id
WHERE ((t4.p_id='180864')) AND t0.smw_iw!=':smw' AND
t0.smw_iw!=':smw-delete' AND t0.smw_iw!=':smw-redi'  ORDER BY
t0.smw_sort ASC  LIMIT 55
[DBQuery] mw-master DROP /*
SMW\SQLStore\TableBuilder\TemporaryTableBuilder::drop  */ TEMPORARY
TABLE `t3`
```

The normal query/selection process would involve:

- `QuerySegmentListProcessor::resolveHierarchyForSegment`
- `HierarchyTempTableBuilder::buildTempTableFor`
- `QueryEngine::getInstanceQueryResult`
- `TemporaryTableBuilder::drop`

A standard setup (as demonstrated above) will normally not encounter
such issue therefore I'm currently hesitant to propose a change from
`DB_SLAVE` to `DB_MASTER` and instead would ask you to investigate the
loss of temp tables (which are used to resolve hierarchies) in your
setup and why there are not available during
`QueryEngine::getInstanceQueryResult`.

I don't think `$smwgQTemporaryTablesAutoCommitMode` will change your
situation but I thought I still mention this in case `GTID` from MySQL
is used in some way.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/HierarchyTempTableBuilder.php#L114-L131

Cheers

**Comment by jamesmontalvo3** [comment]
If a temporary table is generated on DB_MASTER immediately before a SELECT query on DB_SLAVE, wouldn't you have a race condition between the table being replicated and the SELECT query running? In that case shouldn't SELECTs using temporary tables be done on DB_MASTER?

**Comment by mwjames** [comment]
> If a temporary table is generated on DB_MASTER immediately before a SELECT
> query on DB_SLAVE, wouldn't you have a race condition between the table
> being replicated and the SELECT query running?

We rely on MW's DB interface to handle such distribution to avoid any
race condition and update lag. As suggested, you should use the logs
to see when an how those temp tables are created and distributed.

>  In that case shouldn't
> SELECTs using temporary tables be done on DB_MASTER?

This hasn't been an issue with the expectation that the distribution
takes place between MASTER and SLAVE, with access to MASTER being
confined to write activities.

You may use `wfWaitForSlaves` [0] before the actual query execution in
`QueryEngine::getInstanceQueryResult` and see whether this improves
your situation or not.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/GlobalFunctions.php#L3231-L3253

**Comment by mwjames** [comment]
The following contains some notes on the general DB access approach.

- The `QueryEngine` uses the `mw.db.queryengine` connection which is
provided and registered with the `ConnectionManager` [0].
- `mw.db.queryengine` will create a connection using
`DatabaseConnectionProvider::createConnection` and is defined with
read = `DB_SLAVE` and write = `DB_MASTER`.
- You could inject a different connection provider to create a custom
connection as done so by Wikia [1, 2] where you swap the instances.
Wikia uses DB_SLAVE for read and write, see the comment in [2].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/Setup.php#L111-L118
[1] https://github.com/Wikia/SemanticMediaWiki/blob/2.4.2_Wikia/includes/Setup.php#L119-L122
[2] https://github.com/Wikia/SemanticMediaWiki/blob/2.4.2_Wikia/src/MediaWiki/QueryEngineDatabaseConnectionProvider.php

**Comment by jamesmontalvo3** [comment]
> We rely on MW's DB interface to handle such distribution to avoid any
> race condition and update lag.

[1] suggests that doing read queries against master is required when concurrency is an issue.

`wfWaitForSlaves` had no effect. I also tried putting `sleep(30)` prior to the SELECT in `getInstanceQueryResult` [2], but that had no effect. This made me think that I did in fact have an issue with replication. However, then I read [3] and this stood out to me:

> A TEMPORARY table is visible only to the current session, and is dropped automatically when the session is closed.

If the temporary table exists only for the session established with DB_MASTER, then it would make sense that it was not present on the *separate* session established on DB_SLAVE. Furthermore, [3] goes on to say:

> This means that two different sessions can use the same temporary table name without conflicting with each other...

So even if the temporary table is replicated to DB_SLAVE, the fact that the connection to DB_SLAVE is a separate session means the replicated table is invisible.

[1] https://phabricator.wikimedia.org/T35178
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/QueryEngine.php#L402
[3] https://dev.mysql.com/doc/refman/5.7/en/create-temporary-table.html

**Comment by mwjames** [comment]
> A TEMPORARY table is visible only to the current session, and is dropped automatically when the session is closed.

If that is the case for a distributed setup then it might be a good
idea to look closer at what Wikia does (see previous notes) and use
`DB_SLAVE` for both read and write by providing a dedicated connection
provider.

**Comment by jamesmontalvo3** [comment]
@mwjames Are you saying I should fork SMW like Wikia evidently has, or that I should figure out a solution similar to Wikia and submit a PR?

Adding an optional `$useDB_MASTER` argument to `Database::select()` and then using that in `QueryEngine::getInstanceQueryResult()` seems to solve the problem:

```diff
--- SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php
+++ SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php
@@ -411,7 +411,9 @@
 			"$sortfields",
 			$qobj->where,
 			__METHOD__,
-			$sql_options
+			$sql_options,
+			array(), // don't add join conditions
+			true // use DB_MASTER
 		);
 
 		$results = array();
```

```diff
--- SemanticMediaWiki/src/MediaWiki/Database.php
+++ SemanticMediaWiki/src/MediaWiki/Database.php
@@ -200,15 +200,17 @@
 	 * @return ResultWrapper
 	 * @throws UnexpectedValueException
 	 */
-	public function select( $tableName, $fields, $conditions = '', $fname, array $options = array(), $joinConditions = array() ) {
+	public function select( $tableName, $fields, $conditions = '', $fname, array $options = array(), $joinConditions = array(), $useDB_MASTER = false ) {
 
 		$tablePrefix = null;
+
+		$connection = $useDB_MASTER ? $this->writeConnection() : $this->readConnection();
 
 		// MW's SQLite implementation adds an auto prefix to the tableName but
 		// not to the conditions and since ::tableName will handle prefixing
 		// consistently ensure that the select doesn't add an extra prefix
 		if ( $this->getType() === 'sqlite' ) {
-			$tablePrefix = $this->readConnection()->tablePrefix( '' );
+			$tablePrefix = $connection->tablePrefix( '' );
 
 			if ( isset( $options['ORDER BY'] ) ) {
 				$options['ORDER BY'] = str_replace( 'RAND', 'RANDOM', $options['ORDER BY'] );
@@ -216,7 +218,7 @@
 		}
 
 		try {
-			$results = $this->readConnection()->select(
+			$results = $connection->select(
 				$tableName,
 				$fields,
 				$conditions,
@@ -232,7 +234,7 @@
 		}
 
 		if ( $tablePrefix !== null ) {
-			$this->readConnection()->tablePrefix( $tablePrefix );
+			$connection->tablePrefix( $tablePrefix );
 		}
 
 		if ( $results instanceof ResultWrapper ) {
```

**Comment by kghbln** [comment]
> @mwjames Are you saying I should fork SMW like Wikia evidently has, or that I should figure out a solution similar to Wikia and submit a PR?

I very much believe that the latter was meant since forking software should probably be avoided if possible

**Comment by mwjames** [comment]
> Adding an optional `$useDB_MASTER` argument to `Database::select()` and then
> using that in `QueryEngine::getInstanceQueryResult()` seems to solve the
> problem:

I appreciate the effort but that was __not__ what I had in mind
(certainly it is one solution) since your setup (environment) in not
easily testable or copyable, I thought you first give the solution
from Wikia a drive before we discuss a more general approach that is
clean and workable.

Changing the interface (`$useDB_MASTER = false `) and using
`DB_MASTER` is not a preferred solution since it would make it special
and a non-standard conform solution.

My suggestion was aimed at creating a new connection provider (as seen
by the Wikia example) and register the provider with the `Setup` where
`DB_SLAVE` is used for write and read as simple and clean injection
model since that works in a multi DB environment like Wikia,
apparently.

If that doesn't work for you, you could switch to `DB_MASTER`  (in the
connection provider) instead, and test its behaviour.

The approach discussed would enable use to leave everything as-is and
only change the provider at the beginning.

> @mwjames Are you saying I should fork SMW like Wikia evidently has, or that

My objective was to present some solutions that are worth an effort to
test, so that during the weekend something can be done based on
experience from past users (Wikia) combined with results from your
side and allow us to implement a solution that is workable without us
incurring too much technical debt.

> I very much believe that the latter was meant since forking software should
> probably be avoided if possible

Exactly.

**Comment by jamesmontalvo3** [comment]
Okay I'll look more closely at what Wikia has done. Looking through their history it seems like you're essentially advocating cherry-picking [1] [2] and [3].

> ...and register the provider with the `Setup` where `DB_SLAVE` is used for write and read as simple and clean injection model since that works in a multi DB environment like Wikia, apparently.

My initial thought was: Why would you choose to use DB_SLAVE to read and write versus DB_MASTER to read and write? It seems like a greater offense to write to DB_SLAVE than to read from DB_MASTER, especially considering probably 99% of SMW installations are single-database and thus most testing and experience is with reading from DB_MASTER (since DB_MASTER == DB_SLAVE in that case). That said, if you're just creating non-persistent temporary tables, then perhaps it's better to put that load on the slave(s).

> since your setup (environment) in not easily testable or copyable

It's pretty easy to set up my environment with 2 databases if you have Vagrant. On your host do:

```bash
git clone https://github.com/enterprisemediawiki/meza
cd meza
git checkout vagrant-2db
cp vagrantconf.default.yml vagrantconf.yml
$EDITOR vagrantconf.yml    # uncomment the 2db section, adjust RAM/CPUs as desired
vagrant up
```

That will setup 2 VMs primed for installation. Then `vagrant ssh` to SSH into the controlling VM and then `sudo meza deploy vagrant` to install everything. Takes about 20 minutes on my (fast) connection. If anything fails (gerrit hangs up, yum fails an install, etc) just run `sudo meza deploy vagrant` again. Then go to https://192.168.56.56 and accept the self-signed SSL cert.

[1] https://github.com/Wikia/SemanticMediaWiki/commit/3f1d9db69dbc01c550958fa685e9d637af99943c
[2] https://github.com/Wikia/SemanticMediaWiki/commit/5833f59310a8ab2d29d6ee740a576d6e2dbe29c3
[3] https://github.com/Wikia/SemanticMediaWiki/commit/87590e9eed7ddbca6eb1fb3b276e2fdf04310e70

**Comment by jamesmontalvo3** [comment]
Sorry, one other thing: can you explain to me what `#ask` query (or other SMW action) causes `QueryEngine::getInstanceQueryResult()` to be invoked? Trying to recreate it in the simplest case.

**Comment by mwjames** [comment]
> Okay I'll look more closely at what Wikia has done. Looking through their history it seems like you're essentially advocating cherry-picking [1] [2] and [3].

I guess you picked the right cherries and we will eventually create a
factory (or setting) for this but that is not really important here.
For now, I'm more keen to see that this approach is viable so that we
can confirm that it works for you, and does so for Wikia as well.

> probably 99% of SMW installations are single-database and thus most testing
> and experience is with reading from DB_MASTER (since DB_MASTER == DB_SLAVE
> in that case). That said, if you're just creating non-persistent temporary
> tables, then perhaps it's better to put that load on the slave(s).

I have no experience with those setups and trust users who have, to
come up with a solution that works for their environment.

> tables, then perhaps it's better to put that load on the slave(s).

I guess since temp tables are created in-memory that DB_SLAVE (OR
REPLICA) is a safe choice.

> Sorry, one other thing: can you explain to me what `#ask` query (or other
> SMW action) causes `QueryEngine::getInstanceQueryResult()` to be invoked?
> Trying to recreate it in the simplest case.

Any `#ask` (including `#show` as it is a `#ask`) would eventually be
resolved by `QueryEngine::getQueryResult` ->
`QueryEngine::getInstanceQueryResult` and in your case where you want
to press for an auxiliary computation (aka temp table storage)
something like:

{{#ask: [[Category:SomeCategory]] .... }} with `Category:SomeCategory`
being a subcategory of `Category:TopSomeCategory` shouldbe enough to
create a temp table during query answering.

> That will setup 2 VMs primed for installation. Then `vagrant ssh` to SSH
> into the controlling VM and then `sudo meza deploy vagrant` to install

Thanks for sharing, but here I rely on users to make the necessary
sacrifice and test and report instead of me trying to figure how to
use vagrant on my Win notebook in an attempt to navigate in an
environment I'm not familiar.

I'd be more willing to use such setup if we had a dedicated resource
[0, 1] that would allow users (like me) to adapt various scenarios
with an appropriate documentation on the "How to ..." without browsing
the realm of the Internet in a quest of finding the necessary
guidelines.

[0] https://github.com/SemanticMediaWiki/vagrant-installer
[1] https://github.com/SemanticMediaWiki/docker-installer

Cheers

**Comment by jamesmontalvo3** [comment]
Created PR #2533 which includes the above-mentioned cherry-picks plus cleanup. As said in the PR, at present I'm seeing quite a bit of lag which may or may not be related. I'll try to determine the source of that this weekend.

> my Win notebook

I'm also on a win notebook. Git Bash --> `vagrant up`. Understood you don't have the time, though. I've already taken up enough, I'm sure.

> a dedicated resource

Can you explain what you mean? I'm not sure I follow. We hope to build example wikis into meza at some point, so you can have a bunch of pre-built content/templates/forms etc which could be used for education as well as a common testing platform.

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Multi-database_environment

**Comment by mwjames** [comment]
> Can you explain what you mean?

What I'd like to see is that [0] contains all the necessary information and files required by a vagrant/role based installation so that one can simply:

- Read and follow how to install vagrant
- Pull a git from [0] with different roles with one demo role to import standard properties and templates via [1] similar to what the sandbox uses [2]
- How to start the service 
- How to extend or modify the vagrant/roles 

This goes hand in hand with #568 or #1218.

> you can have a bunch of pre-built content/templates/forms

This is what [1] is expected to help with for pre-deployed setups like those using vagrant or docker.

[0] https://github.com/SemanticMediaWiki/vagrant-installer 
[1] https://www.semantic-mediawiki.org/wiki/Help:Contents_importer
[2] https://gist.github.com/mwjames/2f83d3d775cbcc42b4ed

**Comment by mwjames** [comment]
#2534 addresses the core of the reported issue.

Of course, I would welcome someone (@jamesmontalvo3) with sufficient knowledge in vagrant/docker to look closer on the notes above so that in future we can have an easier setup of pre-deployed roles/containers.
