### ISSUE TITLE
Retrieving results causes issues

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2541]
### Setup and configuration

- MediaWiki | 1.29.0-rc.1 (929f8dc)01:59, 8 July 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.31-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (c6a8315) 01:28, 9 July 2017

### Issue

Running "rebuildData.php" produced the following warnings and errors tonight:
```
PHP Warning:  array_merge(): Argument #2 is not an array in /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php on line 299

Warning: array_merge(): Argument #2 is not an array in /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php on line 299
PHP Warning:  array_walk() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php on line 305

Warning: array_walk() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php on line 305
PHP Warning:  reset() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 275

Warning: reset() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 275
PHP Warning:  current() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 156

Warning: current() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 156
PHP Warning:  next() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 162

Warning: next() expects parameter 1 to be array, null given in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 162
PHP Catchable fatal error:  Argument 1 passed to SMW\DataValueFactory::newDataValueByItem() must be an instance of SMWDataItem, null given, called in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 218 and defined in /../w/extensions/SemanticMediaWiki/src/DataValueFactory.php on line 162

Catchable fatal error: Argument 1 passed to SMW\DataValueFactory::newDataValueByItem() must be an instance of SMWDataItem, null given, called in /../w/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php on line 218 and defined in /../w/extensions/SemanticMediaWiki/src/DataValueFactory.php on line 162
```

**Comment by kghbln** [comment]
It is this [template](https://sandbox.semantic-mediawiki.org/wiki/Mod%C3%A8le:RWProjectTemplate2) where things get ugly.
`(342/16199)     Finished processing ID 343* (Modèle:RWProjectTemplate2)`

**Comment by kghbln** [comment]
> It is this template where things get ugly. `(342/16199) Finished processing ID 343* (Modèle:RWProjectTemplate2)`

Actually it is ID 344:
```json
{
    "344": {
        "smw_id": "344",
        "smw_title": "Has_gender",
        "smw_namespace": "102",
        "smw_iw": "",
        "smw_subobject": "_MLccfa8dbd0fafe4706da7c8400ca4d27f",
        "smw_sortkey": "Has gender#The biological sex which can be different from the psychological gender or social gender.;en"
    }
}
```
```json
{
    "344": {
        "smw_di_wikipage": {
            "s_id": "343"
        },
        "smw_fpt_lcode": {
            "s_id": "344"
        },
        "smw_fpt_text": {
            "s_id": "344"
        }
    }
}
```

**Comment by mwjames** [comment]
Do you happen to have the full stack trace when this occurs?

**Comment by kghbln** [comment]
> Do you happen to have the full stack trace when this occurs?

No, the logs remain as brief as posted already.

**Comment by mwjames** [comment]
> Actually it is ID 344:

If you start the rebuild with -s 340, do you end up causing the same
issue at 344?

> [Sun Jul 09 02:06:27.110022 2017] [:error] [pid 19491] [client 106.11.156.248:56356] PHP Warning:  array_merge(): Argument #2 is not an array in /../w/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php on line 299

If you can short circuit the test time by setting the ID to cause the
same issue then go to `ResultFieldMatchFinder::doFetchPropertyValues`
before line 299 and add:

```
+			var_dump( $pv );
 			$propertyValues = array_merge( $propertyValues, $pv );
```

> > No, the logs remain as brief as posted already.

That's a bit of a shame.

If above doesn't result in some meaningful outcome, let's see whether
this is a recent regression or not by running the rebuild on some
older git (2 weeks or so) and observe if it returns with the same
issue and then work your way up to identify on which git hash it
reappears. There only two or three big changes that happen during the
last two weeks.

PS: SMW_FIELDT_CHAR_NOCASE and SMW_FIELDT_CHAR_LONG were only recently
defined, so disabling it during the test to avoid some PHP messages on
undefined constants.

Cheers

**Comment by kghbln** [comment]
> If you start the rebuild with -s 340, do you end up causing the same issue at 344?

Yes.

> If above doesn't result in some meaningful outcome

It results in lines and lines and lines of output. After minutes I stopped this.

**Comment by mwjames** [comment]
Having looked at the stack again, a simple query can reproduce the issue.

```
{{#ask: [[Has query::+]] |?-Has query |limit=3 }}
```

This is due to an inverse printout and in connection with #2495 it is
an iterator instead of a simple array.

The following should fix this:

```
@@ -294,10 +294,14 @@ class ResultFieldMatchFinder {
 				$dataItem,
 				$dataValue->getDataItem(),
 				$this->getRequestOptions()
 			);

+			if ( $pv instanceof \Iterator ) {
+				$pv = iterator_to_array( $pv );
+			}
+
```

**Comment by kghbln** [comment]
> The following should fix this: 

Affirmative! The script is now running beyond the formerly transgressing ID.

**Comment by kghbln** [comment]
> A week ago we did not have the "rebuildData.php" run since the server crashed form jobs not finishing themselves the same day. I more and more have the feeling that the crash of the server is somehow connected.

So this is not connected which is good. 

I just authored the change and made a pull request. Will merge as soon as the tests run through positively?
