### ISSUE TITLE
Format template first line handling not correct

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticMediaWiki#2544]
### Setup
SMW Sandbox site 11-07-2017:
- MW version: 1.29.0-rc.1 (929f8dc)
- DB (MySQL etc.): 10.0.31-MariaDB-1~jessie
- PHP version: 5.6.30-0+deb8u1 (apache2handler)
- SMW version: 3.0.0-alpha (c6a8315) 01:28, 9 July 2017
- SRF version: 3.0.0-alpha (c593eb2) 01:22, 9 July 2017
- Browsers and versions (if applicable): Chromium Version 59.0.3071.86 (Official Build) (64-bit)

### Issue
It seems when using ` format=template` and then show the result in a table there is an issue with the handling of the first line in `template` and in `outrotemplate`. 

In  `template` when the row in the table starts on the first line the property on that line is not shown. I tested this with and without using named arguments but the behavior is the same. 

In `outrotemplate` when the closing bracket for the table is on the fist line the table is not closed properly (of course) and this in turn breaks the headings or page.

Both can be fixed by adding an empty line on top but that should not be necessary.

When there are any questions please let me know.

**Steps to reproduce**
See example on: https://sandbox.semantic-mediawiki.org/wiki/Format_result_to_table

**Comment by kghbln** [comment]
Thanks for reporting. I have not gone through all of the examples, however if you [add the noinclude tags](https://sandbox.semantic-mediawiki.org/w/index.php?title=Mod%C3%A8le%3ANamedargno1&type=revision&diff=6959&oldid=6943) as one usually does things seem to work fine. We may already be looking at a MediaWiki peculiarity.

**Comment by s7eph4n** [comment]
Indeed, this is a MediaWiki issue. MW strips all whitespace from template before inserting it, including line feeds. This means that the first line of each template call is concatenated directly to the last line of the previous line and there is nothing SMW can do about it.

Workaround: Add something to the template so that whitespaces won't be stripped. This can be the `<includeonly>` suggested by Karsten, which is followed by a line feed. You could probably also use `<nowiki/>` followed by a line feed.

**Comment by jongfeli** [comment]
Ok, I understand. Stupid thing is that after all those years working with SMW I never noticed this before :-( 

Thanks gentlemen.

**Comment by kghbln** [comment]
No worries please. Usually one documents templates or should so so, well it is best practice I believe, so you have noincludes and includonlys or onlyincludes which do the job unnoticed. Starters will still have issues with unwanted and at first sight unexplainable breaks here and there but in general ...
