### ISSUE TITLE
Add field and delete field section not working in creating templates and form using bootstrap-mediawiki skin

### ISSUE THREAD

**Issue by Jatin1697** [SemanticMediaWiki/SemanticMediaWiki#2550]
### Setup and configuration

- SMW version: 2.5.3
- MW version: 1.28.2
- PHP version: 7.1.1
- DB (MySQL etc.): SQLite: 3.8.10.2

### Issue

Add field and delete field section not working in creating templates and form using bootstrap-MediaWiki skin.

**Comment by kghbln** [comment]
@Jatin1697 Thanks for reporting. There is an armada of bootstrap skins out in the wild so I do not know which one you are referring to. However I believe that this issue has to be addressed by the particular skin and/or the Page Forms extension.

**Comment by Jatin1697** [comment]
Thanks for telling me.
I will report this issue at pageforms extension.

**Comment by Jatin1697** [comment]
But i would like to inform yout that there is not any this type of issue in
semantic mediawiki 2.5.2. It only arised after i upgraded to SMW 2.5.3.
 It will be pleasure of you if you go through this.

**Comment by kghbln** [comment]
> But i would like to inform yout that there is not any this type of issue in SMW 2.5.2. It only arised after i upgraded to SMW 2.5.3.

When I look at the changes in 2.5.3 I ad hoc do not really see one which could have caused this. So you did not upgrade the skin and Page Forms at the same time?

What errors are issued? This question will be asked by the developer of the skin and/or Page Forms anyways.

**Comment by Jatin1697** [comment]
The skin and Page Forms are upgraded to their best level.

Till now, only one issue has arrived that  i have mentioned in the starting
"Add field and delete field section not working in creating templates and
form using bootstrap-mediawiki skin"
Thanks

**Comment by kghbln** [comment]
So you updated the skin and Page Forms at the same time?

What is the error log of you server saying?

**Comment by Jatin1697** [comment]
This is what the issue really is:
When I click on add section or delete button, nothing happens.

The template I am trying to create and error occurred are shown in the
image.
