### ISSUE TITLE
Display formats for Page properties: `link`, `nolink`, `pagename`, `fullpagename`

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#2552]
Currently (SMW <3.0) a printout for a Page property produces a link with the full page name (incl. namespace) by default. This may be modified using the `link` parameter of the `#ask` function.

To have more influence on the printout format (without resorting to the `template` format) it might be helpful to have display formats for Page type printouts, e.g.
```
|?foo #fullpagename
|?bar #pagename
|?baz #link
|?quok #nolink
```

It should be possible to combine the keywords. The full specification for the current default would then be
```
|?foo #link fullpagename
```

These printout level display formats should override whatever would be produced by default or according to the `link` parameter of the `#ask` function.

**Comment by mwjames** [comment]
* Before working on the this issue, moving all formatting related part to its own `WikiPageValuFormatter` is obligatorily using the `DataValueServiceFactory` (see existing DV examples)
* Can be combined with #2470

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
