### ISSUE TITLE
It is not possible to easily remove the groups smwcurator and smwadministrator

### ISSUE THREAD

**Issue by Seb35** [SemanticMediaWiki/SemanticMediaWiki#2565]
### Setup and configuration

- SMW version: 2.5.0
- MW version: 1.28.2
- PHP version: 7.0
- DB (MySQL etc.): 5.7

### Issue

Usually default MediaWiki groups can be removed by adding this in LocalSettings.php:
```php
unset( $wgGroupPermissions['smwadministrator'] );
```
But this instruction alone does not work for the groups smwcurator and smwadministrator. It must be added the extension function:
```php
$wgExtensionFunctions[] = function() {
        if( array_key_exists( 'smwcurator', $GLOBALS['wgGroupPermissions'] ) ) {
                unset( $GLOBALS['wgGroupPermissions']['smwcurator'] );
        }
};
```

**Comment by Seb35** [comment]
I initially thought a check could be added on the existence of the key 'smwcurator' in $wgGroupPermissions, but it the group smwcurator does not exist before the function Setup::registerPermissions(), so it cannot be detected if it is wanted or not.

A configuration parameter could be added but it is a bit overkill.

Possibly the key 'smwcurator' could be added during initial loading (Composer-autoload time), and checked if it is always here during $wgExtensionFunctions, but I’m not sure it is a good strategy.

**Comment by Seb35** [comment]
FYI a past issue slightly linked to this one : #1137

**Comment by kghbln** [comment]
Why not use `$wgAddGroups` thus not allowing to assign `smwcurator`? To prevent scary actions there is [`$smwgAdminFeatures`](https://www.semantic-mediawiki.org/wiki/Help:$smwgAdminFeatures) or set `$wgGroupPermissions['sysop']['smw-admin'] = false;`

**Comment by mwjames** [comment]
> It is not possible to easily remove the groups smwcurator and smwadministrator

Why would I want to do this? These roles are not assigned to anyone by default therefore cannot be used as attack vector.

> A configuration parameter could be added but it is a bit overkill.

Yes

> always here during $wgExtensionFunctions, but I’m not sure it is a good strategy.

The `DefaultsSettings.php` only contains SMW related default settings with `Setup` making changes to required MW GLOBALS.

If there is a valid use case and if we don't want to meddle too much with the settings system, add a hook at the end of the Setup and do whatever needs to be done in your scenario using that hook.

```
 		$this->registerFooterIcon();
 		$this->registerHooks();
+
+		\Hooks::run( 'SMW::Setup::AfterCompletion' );
 	}
```
```
\Hooks::register( 'SMW::Setup::AfterCompletion', function() {
	unset( $GLOBALS['wgGroupPermissions']['smwcurator'] );
} );
```

**Comment by mwjames** [comment]
Any feedback on this issue?

**Comment by Seb35** [comment]
Yes, I realise I didn’t explain the use case. On small (semantic) wikis, in order to simplify the user rights management, it could be desirable to reduce the number of user groups, for instance with the groups `*`, `user`, `sysop`, merging all rights from `smwadministrator` and `smwcurator` into `sysop`. Hence it is not related to any attack vector neither about removing some user rights by default, but only to user experience related to user rights management.

A hook as proposed would be very convenient; the use case is minor enough not to create complex things like a configuration parameter.

**Comment by kghbln** [comment]
This is probably similar to the "staff" user group provided by default by the Translate extension. Allowing to remove them appears to be a matter of setup beauty.

So if I understand correctly we just need to add `\Hooks::run( 'SMW::Setup::AfterCompletion' );` to "Setup.php" and then administrators will be able to disable the groups by adding 

```
\Hooks::register( 'SMW::Setup::AfterCompletion', function() {
	unset( $GLOBALS['wgGroupPermissions']['smwcurator'] );
} );
```
to "LocalSettings.php" after the `enableSemantics()` call? If so let's just add the line and continue with other issues.

**Comment by Seb35** [comment]
Thanks for fixing this issue!

**Comment by Seb35** [comment]
If someone else wants to achieve a similar behaviour: remove 'smwcurator' and/or 'smwadministrator' (preferably because you gave their rights to other user group(s)):
```php
/* For SMW < 3.0.0 */
$GLOBALS['wgExtensionFunctions'][] = function() {
	if( array_key_exists( 'smwcurator', $GLOBALS['wgGroupPermissions'] ) ) {
		unset( $GLOBALS['wgGroupPermissions']['smwcurator'] );
	}
	if( array_key_exists( 'smwadministrator', $GLOBALS['wgGroupPermissions'] ) ) {
		unset( $GLOBALS['wgGroupPermissions']['smwadministrator'] );
	}
};

/* For SMW ≥ 3.0.0 */
$GLOBALS['wgHooks']['SMW::Setup::AfterInitializationComplete'][] = function( &$vars ) {
	if( array_key_exists( 'smwcurator', $vars['wgGroupPermissions'] ) ) {
		unset( $vars['wgGroupPermissions']['smwcurator'] );
	}
	if( array_key_exists( 'smwadministrator', $vars['wgGroupPermissions'] ) ) {
		unset( $vars['wgGroupPermissions']['smwadministrator'] );
	}
};
```
Also it works both before and after the `enableSemantics` function call (because it is called at the stage "wgExtensionFunctions", hence after the whole LocalSettings.php is executed).

**Comment by kghbln** [comment]
[Documented on wiki.](https://www.semantic-mediawiki.org/wiki/Help:User_rights_and_user_groups/Remove_user_groups)
