### ISSUE TITLE
Empty css-class information in result table

### ISSUE THREAD

**Issue by DanielDIQA** [SemanticMediaWiki/SemanticMediaWiki#2586]
## Setup and configuration

- SMW version: 2.5.1
- MW version: 1.27.1
- PHP version: 5.6.30
- DB (MySQL etc.): mysql

## Issue

Inline queries, that contain empty printouts, generate html, that misses a class-name.

### Example:
Given the following inline query
```
{{#ask:
 [[Category:Ex]]
 |?Titel
 |?Dokumentart
 |?vom
 |format=table
}}
```
produces the following HTML:
```
[..]
<tr data-row-number="1" class="row-odd">
  <td class="Titel smwtype_wpg">xyz</td>
  <td></td>
  <td data-sort-value="2457959.3189815" class="vom smwtype_dat">24.07.2017</td>
</tr>
[..]
```
Notice, that the 2nd "TD" element provides no css-class-information. It would have been expected that it contains this class information: 
```
<td class="Dokumentart smwtype_wpg">xyz</td>
```
Apparently, columns that contain no value miss the css-class information.

This is unfortunate, if you want to purge columns in css-media queries, i.e. for small-size devices. In this case, a class-selector would match the table's column header, but it would miss the (empty) cells.

**Comment by kghbln** [comment]
Thanks for reporting.

**Comment by mwjames** [comment]
I suspect that the following code fixes the issue. If necessary adapt related tests and if no tests fail, please add a new test [0] that tests the new behaviour.

```
@@ -175,16 +175,18 @@ class TableResultPrinter extends ResultPrinter {

 		while ( ( $dv = $resultArray->getNextDataValue() ) !== false ) {
 			$dataValues[] = $dv;
 		}

-		$attributes = array();
+		$attributes = array(
+			'class' => $columnClass . ' smwtype' . $resultArray->getPrintRequest()->getTypeID()
+		);
+
 		$content = null;

 		if ( count( $dataValues ) > 0 ) {
 			$sortKey = $dataValues[0]->getDataItem()->getSortKey();
-			$dataValueType = $dataValues[0]->getTypeID();

 			if ( is_numeric( $sortKey ) ) {
 				$attributes['data-sort-value'] = $sortKey;
 			}

@@ -195,11 +197,10 @@ class TableResultPrinter extends ResultPrinter {
 			$alignment = trim( $resultArray->getPrintRequest()->getParameter( 'align' ) );

 			if ( in_array( $alignment, array( 'right', 'left', 'center' ) ) ) {
 				$attributes['style'] = "text-align:$alignment;";
 			}
-			$attributes['class'] = $columnClass . ( $dataValueType !== '' ? ' smwtype' . $dataValueType : '' );

 			$content = $this->getCellContent(
 				$dataValues,
 				$outputMode,
 				$resultArray->getPrintRequest()->getMode() == PrintRequest::PRINT_THIS
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/README.md#designing-an-integration-test

**Comment by mwjames** [comment]
What happen here? It has been 11 days without feedback, did we solve the issue, can this be closed?

**Comment by mwjames** [comment]
@DanielDIQA When members of the project make an effort to provide advice or suggestions, I'd somehow expect some form of feedback by the initial party that opened the inquiry.

Contributions to this repository are being made on a volunteer basis and things will not solve themselves and shouldn't be expected (especially when no feedback is provided). This time around we have been lucky that @TK-999 took on the issue and went through the trouble to provide time and effort.
