### ISSUE TITLE
Implement QueryResultDeserializer

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#2589]
FEATURE REQUEST

We have a serializer `QueryResultSerializer` but no `QueryResultDeserializer`.

Rationale: As a tester, I'd like to add tests to SRF, which uses json_encoded `SMWQueryResult` as test data. To feed the data into the SUT, e.g. getResultText( SMWQueryResult $res, $outputmode ), a deserializer is required.

**Comment by mwjames** [comment]
Relates to the discussion in https://sourceforge.net/p/semediawiki/mailman/message/35979380/.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
