### ISSUE TITLE
Goat, What?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2612]
Maybe I didn't get the memo, but what the heck is "goatification" [0]? @kghbln @JeroenDeDauw @s7eph4n 

[0] https://phabricator.wikimedia.org/tag/goatification/

**Comment by s7eph4n** [comment]
No idea. Trying to decide if this is real or you are trying to pull some elaborate joke. :P

**Comment by kghbln** [comment]
I'd rather stick with cats and bunnies and so should we. :D
