### ISSUE TITLE
Composer and the update of libraries used by extensions and MediaWiki

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2613]
Tracking ticket for [0, 1] (Provide a way to install Composer dependencies after installing an extension, without updating all unrelated libraries) in case WMF makes code changes that would affect SMW and alike.

[0] https://phabricator.wikimedia.org/T173141
[1] https://github.com/composer/composer/issues/6601

**Comment by kghbln** [comment]
This one is destined to rot since upstream fails to understand the issue.

**Comment by mwjames** [comment]
> upstream fails to understand the issue

In this case :bomb:
