### ISSUE TITLE
Gallery does not work like expected

### ISSUE THREAD

**Issue by urarku** [SemanticMediaWiki/SemanticMediaWiki#2656]
### Setup and configuration

- SMW version: 2.5
- MW version: 1.27.1
- PHP version: 5.6.31
- DB version (MySQL, Blazegraph etc.): MySQL

### Issue
I try to make a gallery-site on a private (at the moment) mediawiki-site. When I do the gallery manually with the gallery-tag then everything works fine (with gallerybox-tag).
When I do it with an ask-query it doesn't work. It shows me a standard-table. The code looks like this: _<table class="sortable wikitable smwtable">_ 

My code looks like this:

{{#ask: [[Category:Fahrradmodelle]] [[Bildname::+]] 
 |?Bildname
 |imageproperty=Bildname
 |format=gallery
 |widths=80
 |heights=90
}}

I searched the internet and GitHub for similar problems but couldn't find any solution for it. Is there a hint what the problem could be. I am still quite new to SMW but learning fast!

**Comment by kghbln** [comment]
Thanks for asking and using SMW. At first glance the query looks ok to me. However the gallery format is provided by the [Semantic Result Formats](https://github.com/SemanticMediaWiki/SemanticResultFormats) extension. Did you install this one. Apart from that there is a [mailing list](https://github.com/SemanticMediaWiki/SemanticResultFormats) and a [test wiki](https://sandbox.semantic-mediawiki.org/wiki/Main_Page)
