### ISSUE TITLE
Hierarchies, queries, and depth restriction

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2662]
http://bots.wmflabs.org/~wm-bot/logs/%23semantic-mediawiki/20170907.txt with 
> [13:30:52] <traumschule>	 ... but I am confused to select pages from a category via #ask not showing images and category contenty.
[13:34:53] <traumschule>	 {{#ask: |[[Category:fix]] |[[:+]] }} is a workaround but it shows pages in selected categories as well

The above is orthogonal to this issue but elevated the question of "How to restrict depth on a per query basis".

Generally, users do not recognize that hierarchies are resolved by default with queries yielding results that contain a larger match pool (as it includes members of the subcategories). The semantics of subcategories and subproperties are so that members are included in a set of a higher order class/property therefore resolving them is the expected behaviour.

## Issue

Semantic MediaWiki by default [0, 1] resolves subcategories and subproperties as part of a hierarchy with the levels as defined in [0, 1] and is applied to all queries where a hierarchy is detectable. It is currently not possible to restrict the depth on an individual query, forcing a user to choose between either or without providing a method to intercept or model specific use cases where hierarchy inferences are expected to be suspended temporarily.

```
Category: Foo
	|- Category: Bar
	|- Category: Foobar
		|- Category: Foobar/1
			|- Category: Foobar/1/1
		|- Category: Foobar/2
```
Given the levels in [0, 1], the query `{{#ask: [[Category: Foo]] }}` would resolve all members of the hierarchy tree without a possibility to restrict its level for this particular query.

## Proposal

To eliminate the outlined deficiency, the following syntax `[[...|+depth=...]]` is proposed to allow to define an individual level on a per query basis where [0] and [1] also function as maximum level for a possible definition within a query condition.

```
{{#ask: [[Category: Foo|+depth=0]]
 |?Category
}}
```

The query `[[Category: Foo|+depth=0]]` would only display members of the `Category: Foo` without resolving any other subcategory.

For the `SPARQLStore` we would only be able to support `|+depth=0` and `|+depth=1` achieved by modifying the path operator [2, 3] as in `*` or `?` (e.g. `rdfs:subClassOf*`, `rdfs:subClassOf?`) while any other level would require additional computation [4] and seems unnecessary for the SMW project.

[0] https://www.semantic-mediawiki.org/wiki/Help:$smwgQSubcategoryDepth
[1] https://www.semantic-mediawiki.org/wiki/Help:$smwgQSubpropertyDepth

[2] https://www.w3.org/TR/sparql11-query/#pp-language
[3] https://www.w3.org/TR/sparql11-query/#propertypath-arbitrary-length
[4] https://stackoverflow.com/questions/18126949/limit-the-sparql-query-result-to-first-level-in-hierarchy

refs: https://www.semantic-mediawiki.org/wiki/Help:Inferencing#Subcategories, https://www.semantic-mediawiki.org/wiki/Help:Inferencing#Subproperties

**Comment by kghbln** [comment]
In the past I personally have circumvented the issue by restructuring categorization if necessary. This proposal however appears like a easy going solution so I like it. So `depth` as in `max-depth` would default to [`$smwgQSubcategoryDepth`](https://www.semantic-mediawiki.org/wiki/Help:$smwgQSubcategoryDepth) +1 if not explicitly stated...?

What about subproperties? `[[Property::Foo|+depth=0]]`? I suspect that subproperties are less widely used.

**Comment by mwjames** [comment]
> So depth as in max-depth would default to $smwgQSubcategoryDepth +1 if not explicitly stated...?

For example, `+depth=0` means no depth and for the above use case would only find members of `Category: Foo` and behave as it would of no subcategory.

`+depth=1` would mean only directly associated members of `Category: Foo`, `Category: Bar`, and `Category: Foobar` are part of the match pool.

If `$smwgQSubcategoryDepth` (or for that matter `$smwgQSubpropertyDepth`) is declared as 10 and you use `+depth=1000` then it would still restrict to 10 since the setting is used as max ceiling.

> In the past I personally have circumvented the issue by restructuring categorization if necessary

I may want categories as dependency of each other but currently I'm unable to restrict a query on a particular level unless one changes `$smwgQSubcategoryDepth`/`$smwgQSubpropertyDepth`.

> What about subproperties? [[Property::Foo|+depth=0]]? I suspect that subproperties are less widely used.

Syntax would be the same as in `[[SomeProperty::SomeValue|+depth=0]]` or `[[SomeProperty::+|+depth=0]]`.

**Comment by mwjames** [comment]
I'm leaving this open (and the respective PR) for additional comments til next weeks merge window.

**Comment by kghbln** [comment]
This all sounds fair enough for me and actually meets my expectations for it. So I am cool. :)

**Comment by mwjames** [comment]
https://sandbox.semantic-mediawiki.org/wiki/Issue/2662
