### ISSUE TITLE
Mandatory properties, "empty" properties, and the search for non-existing assignments

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2669]
refs: https://sourceforge.net/p/semediawiki/mailman/message/36025265/

## Issue

As noted in an old email exchange [0], finding any non-existing assignments to a property is a herculean effort that if you use an inverted index (as those in a triple store) and a special syntax [1] in `SPARQL` is less of a problem.

For the `SQLStore` we don't have that luxury and creating an inverted index via the RDBMS layer isn't an affordable practice.

## Proposal

Hence this proposal goes into a different direction, instead of trying to prove that something does not exists by matching all existing members and compare them, we use the so called mandatory properties and a `NULL` assignment with the support of `!+` (such as `[[SomeProperty::!+]]`) to declare all `NULL`  (means no real value) matched instances as being "non-existing assignments" in context of any other value assignment.

This proposal is about an affordable (in terms of codifying the outlined requirements) practice that offers a solution for the long standing issue of finding specific properties that have no value assigned.

Under the premise that proving the existence can be easily validated using the current RDBMS, we will use `NULL` as technical identity for that purpose which by normal means cannot be assigned through any user action.

Since we cannot assume users to be a responsible in the amount [2] of properties used or declared, updating any entity with those from an arbitrary list of properties would seem to invite performance issues from the start and therefore the approach of mandatory properties is introduced with:

- Setting `$smwgMandatoryProperties`  declares a list of properties that are expected to exists on each single entity created (e.g. `$smwgMandatoryProperties = [  'Has description', 'Has keyword' ]`)
- Parser function `{{#mandatory: ... }}` can be used to override that list as in `{{#mandatory: |property=Age, AnotherValue ...}}` on each subject (it also invalidates the list declared in `smwgMandatoryProperties` for this subject)
- The definition of mandatory properties is extended to user defined subobjects that are embedded in the subject where above rules applies as well
- Any update will ensure that those listed requirements are reevaluated
- Query syntax `!+` can be used to find those entities that have not been assigned as in `{{#ask: [[AnotherValue::!+]]`

Using either `$smwgMandatoryProperties` or `{{#mandatory: ... }}` allows us to control which properties are required and mandatory during the update process.

When changing the content of `$smwgMandatoryProperties` , running the `rebuildData` script is required since each subject has to be reevaluated against the altered list of mandatory properties. Changing the content of `{{#mandatory: ... }}` does not require `rebuildData` since each subject will be reevaluated during the update itself.

Assignments with a `NULL` value will not be listed in `Special:Browse` or the `Property:...` page.

## Use case

A simple document management system with the requirement that each document (article) contains:

- Document version
- Document status
- Document description
- Keywords

Document SomeDocument

```
{{Document
 |version=123
}}
```

Template: Document
```
<includeonly>

* [[Document version::{{{version|}}}]]
* [[Document status::{{{status|}}}]]
* [[Document description::{{{description|}}}]]
* {{#set: |Has keyword={{{keyword|}}} |+sep=, |template=FormatKeywordValue}}

{{#mandatory:
 |property=Document version, Document status, Document description, Has keyword
}} [[Category:Document]]
</includeonly>
```

A query to list all entities where a `Document description` assignment is missing.
```
{{#ask: [[Category:Document]] [[Document description::!+]]
 |format=table
}}
```

## Performance

- Updates are performed on listed properties which is limited and should therefore not have any significant impact.
- Query execution is done on a `NULL` value (as `IS NULL` and `IS NOT NULL`) therefore should use the existing table indices
- Depending on the list of requested mandatory properties, table entries with `NULL` will increase but once assigned a discrete value, the `NULL` is replaced and will use the same table space

## Limitations

Categories are a somewhat difficult topic in this respect and are therefore __not__ covered here.

[0] http://wikimedia.7.x6.nabble.com/Empty-property-query-possible-td556352.html
[1] https://stackoverflow.com/questions/7097307/selecting-using-sparql-based-on-triple-does-not-exist
[2] https://wikiapiary.com/wiki/Semantic_statistics (see `The Third Turn` with `1,101,729` used properties)

**Comment by jaideraf** [comment]
@mwjames, if I understand correctly, according to this proposal, may we say that SMW "mandatory properties" is using a closed-world assumption (CWA)[0], while normal properties is using an open-world assumption (OWA)[1]? In other words, in "mandatory properties" an absence of a property value is considered a false value, while in normal properties an absence of a property value is neither a true or a false value, it is just unknown.

I understand this is tricky because OWL is OWA and SQL is CWA. So, it let me thinking about how this information would be displayed and represented/exported in Ask queries and RDF outputs.

`[[SomeProperty::!+]]` as a condition would select subjects (or subobjects) to the query. But what 
`|?SomeProperty`, as a printout statement, would exhibit? Nothing? Null? 0? False?

And in a RDF statement? I am not sure if this [2] is the right case as discussed here, but it maybe  relevant somehow.

Would datatypes have something to to with "mandatory properties"? I mean, if I have a boolean property called “`Has child`” (that expects true or false values), and I make this property “mandatory”, what an absent value would mean to this property? Absent value = false? And a number property? Absent value = 0?

I am not pro or against this feature, I am just curious about it.

[0] https://en.wikipedia.org/wiki/Closed-world_assumption
[1] https://en.wikipedia.org/wiki/Open-world_assumption
[2] https://www.w3.org/TR/2014/REC-rdf-syntax-grammar-20140225/#section-Syntax-empty-property-elements

**Comment by kghbln** [comment]
> But what |?SomeProperty, as a printout statement, would exhibit? Nothing? Null? 0? False?  

and

> Would datatypes have something to to with "mandatory properties"? I mean, if I have a boolean property called “Has child” (that expects true or false values), and I make this property “mandatory”, what an absent value would mean to this property? Absent value = false? And a number property? Absent value = 0?

I'd expect nothing to be shown since no value assignment is available. This is about selecting pages which should have a value assignment and not about displaying information i.e. a missing value assignment since it is in fact not available - regardless of the datatype.

**Comment by kghbln** [comment]
@jaideraf Did you have the chance to pull in the commit and also test for the questions. I am a bit tight in time this week so I will probably not be able to test on sandbox.

**Comment by jaideraf** [comment]
@kghbln actually I was expecting to test it on sandbox. :laughing:
Then I saw your comment above, and I tried to test it, but: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2670#issuecomment-328846956

**Comment by kghbln** [comment]
@jaideraf I tried to be somehow energetic but do not manage all the time. However testing commits is not just a matter of doing it on sandbox. There are so many instances with very different data structures out there which would help testing a lot.

**Comment by mwjames** [comment]
I modified the approach on how to define mandatory requirements (aka properties):

- Minor semantic refinement on the naming, generally we will talk about mandatory requirements instead of just mandatory properties (more on that later)
- Instead of providing a `$smwgMandatoryProperties` setting, declare global mandatory properties with  the help of the `Is mandatory` meta property as in `[[Is mandatory::true]]` (PS: `[[Is mandatory::false]]` isn't used, remove the property from the property page to remove the attribute, this is done so we avoid checking a specific Boolean value which helps to avoid DB calls to check for a a specific value)
- Removing `Is mandatory` will automatically trigger a change propagation (avoids having to run the `rebuildData` script) but of course adding a newly "global" requirement, requires to run the `rebuildData.php` script to allow for existing entities to be checked against that new requirement otherwise only successive updates will correct the requirement assumption
- Adds the `$smwgMandatoryRequirementsNamespaceList` setting to restrict the mandatory check on a namespace level, assigning `[]`/ `false` will disable the functionality entirely
- As previously noted, `{{#mandatory: ...}}` overrides the "global" mandatory requirement for an individual subject

## Expected behaviour

A short rundown of the expected behaviour.

- Create property `Property:Requirement test` with `[[Has type::Page]]`, `[[Is mandatory::true]]`
- Create an empty `NullTest` page
  - Check query `[[Requirement test::!+]]` which should list `NullTest` as member of the result
  - Usage count of `Property:Requirement test` remains 0
- Edit the `NullTest` page:
   - Add `{{#mandatory: |property=Local requirement test }}`
   - Check query `[[Requirement test::!+]]` which should NOT list `NullTest` as member of the result
   - Check query `[[Local requirement test::!+]]` which should list `NullTest` as member of the result
   - Add `[[Local requirement test::SomeValue]]` annotation to `NullTest`
     - Check query `[[Local requirement test::!+]]` which should NOT list `NullTest` as member of the result
     - Add a `{{#subobject: SomeProperty=SomeValue}}` to `NullTest`
       - Check query `[[Local requirement test::!+]]` which should ONLY list the subobject of `NullTest` as member of the result
    - Remove `{{#mandatory: |property=Local requirement test }}` from `NullTest`
       - Check query `[[Local requirement test::!+]]` which should NOT contain any `NullTest` reference
       - Check query `[[Requirement test::!+]]` which should list both `NullTest` entities as member of the result
- Add `$smwgMandatoryRequirementsNamespaceList = false`
  - Update or purge page `NullTest`
    - Check query `[[Requirement test::!+]]` which should NOT list any `NullTest` entities as member of the result
- Re-enable `$smwgMandatoryRequirementsNamespaceList` and remove `[[Is mandatory::true]]` from  `Property:Requirement test`
   - After the `SMW\ChangePropagationDispatchJob` and `SMW\ChangePropagationUpdateJob` have been completed
  - Check query `[[Requirement test::!+]]` which should NOT list any `NullTest` entities as member of the result
- Re-add `[[Is mandatory::true]]` to `Property:Requirement test`
  - Either run the `rebuildData.php` script or purge  `NullTest` manually
  - Check query `[[Requirement test::!+]]` which should list any `NullTest` entities (== 2, standard page and one subobject) as member of the result

If a requirement is violated (meaning the property is internally annotated with `NULL`) then non of the properties for which the violation occurs are listed or visible by means of the standard user interface (e.g.  `Special:Browse`).

The same behaviour applies to the RDF export, a requirement violation is not exported (more on that later). 

### Testing

The behaviour should be tested using the outlined script on alternating types of `Property:Requirement test` (`[[Has type::Page]]`) to verify that the same outcome occurs for `_txt` (Text), `_dat` (Time), `boo` (Boolean), and `_uri` (URI).

The `null_count` column from the `smw_prop_stats` table (#2680) is not directly accessible to a user but changes invoked by the test script should be reflected by count alternation in the `usage_count` and `null_count` column.
 
Running `rebuildPropertyStatistics.php` should correctly update both columns on the codified requirements.

**Comment by mwjames** [comment]
Let me try to clarify in some simple statements the premises:

- `NULL` is a transient state which is not a discrete value in terms of OWL (it is in terms of SQL)
- Boolean `false` and `true` are discrete values and are distinct from `NULL`
- Number 0 is NOT `NULL`
- `NULL` is stored as an assignment for a mandatory property where no discrete value (means any value besides `NULL` and empty) has been declared and hereby codifies that a requirement (the mandatory one) was violated
- Assignments with `NULL` will not be exported as they only declare a state "of being" in terms of SQL not OWL

As outlined earlier we will refer to the issue more broadly as mandatory requirement which currently only entails properties. 

Using either `Is mandatory` or `{{#mandatory: ... }}` has been selected for several reasons:

* First, it provides a distinct list (finite, see comments above where users create insurmountable properties [0]) of requirements the system can check against without creating a possible performance issue during the update process.
* Secondly, it creates a distinct graph for each violation by assigning a `NULL` to those statements where the requirement (meaning to be mandatory) is transgressed. Any change to the list can be verified, while having no such list would require a constant reevaluation of all entities as soon as a property is added or deleted.
* We escape the discussion and its semantic implication of incomplete information vs. non-existent information vs. emptiness on behalf of the value declaration by defining a requirement called "mandatory" which the systems records as `NULL` and is at the same time used as entailment in regards to the obligatory characteristics of those statements.

> [[SomeProperty::!+]] as a condition would select subjects (or subobjects) to the query. But what
|?SomeProperty, as a printout statement, would exhibit? Nothing? Null? 0? False?

In a loose sense, `!+` is the opposite of `+` which is defined as "show me all with any value assigned" while `!+` under the outlined framework above means "show my those that have no discrete value (== those with a NULL)".

The printout will be displayed empty because it is a transient state with no value. The `!+` is added as syntax element for just one task, namely that of translating the expression `IS NULL` into SQL.

In a strict sense, the `!+` query syntax does not translate into answering for non-existence of some value but to answer the question of which triple violates the mandatory requirement which we conveniently interpret as "Which property has no value assigned?", "Show my all entities where property X (is expected with some value) has no value assigned",

> And in a RDF statement? I am not sure if this [2] is the right case as discussed here, but it maybe relevant somehow.

If one wanted to codify the obligatory character of a statement, using the methods as suggested in the cited source maybe possible but currently I have no plans to do that since `SPARQL` has its own method to filter [1] non existing assignments.

One could also use blank nodes [2] as representation for incomplete (a "no" value) information [3], whether this creates some sort of mismatch about its established semantics [4] isn't really part of this ticket or discussion.

> In other words, in "mandatory properties" an absence of a property value is considered a false value, while in normal properties an absence of a property value is neither a true or a false value, it is just unknown.

Let me re-phrase this:

In case we have a mandatory requirement (property) declared, the absence of a property value assignment forces the `SQLStore` to store a `NULL` (not false) and hereby declares a closed-world assumption which in terms of SQL translates into "to be known as unknown or not assigned". If we declare __no__ mandatory requirement then any non-assignment to a property can only be interpreted as state of being unknown and we face the issue that we cannot query (meaning in a finite time) those as outlined in the section above.

On those properties listed as mandatory, a `NULL` is being interpret as an assignment with no discrete value on a specific entity (subject) and allows us to prove (with not much computational effort) that some properties have violated the requirement by not having any value assigned.

> Would datatypes have something to to with "mandatory properties"?

No.

> I mean, if I have a boolean property called “Has child” (that expects true or false values), and I make this property “mandatory”, what an absent value would mean to this property? Absent value = false? And a number property? Absent value = 0?

For example the subject "John Doe" has no value assignment for property "Has child" (which is an obligatory requirement) therefore the system will store a `NULL` (not a false and not a true, lets called a quantum state of "being not being") which under normal circumstances will not show up (not in Special:Browse, or a RDF export etc.). Only on the occasion that a query uses `!+` as in `[[Has child::!+]]`, the `SQLStore` will interpret `!+` as `IS NULL` and find those nodes that have an explicit `NULL` assigned.

> And a number property? Absent value = 0?

Also here it is `NULL` not 0.

[0] Whether this is a practical concern or not is not really important, alone the fact that you can invoke such scenario warrants ...
[1] https://stackoverflow.com/questions/29235840/retrieve-subjects-with-no-value-for-a-property
[2] http://ceur-ws.org/Vol-1486/paper_27.pdf (Expressing No-Value Information in RDF)
[3] P. Hayes. RDF semantics, W3C recommendation, February 2004
[4] https://www.w3.org/2009/12/rdf-ws/papers/ws23

**Comment by jaideraf** [comment]
Thank you @mwjames! the approach is very clear now. I think your text will help the documentation a lot (and for future reference, too). :+1:

**Comment by WolfgangFahl** [comment]
see https://www.semantic-mediawiki.org/wiki/Thread:Semantic-mediawiki.org:Community_portal/Querying_for_non-empty_values
and how will this influence #874?

**Comment by mwjames** [comment]
Moving this to "Enhancements and features" as it is unlikely to make the 3.0 release cut

**Comment by ankostis** [comment]
Shouldn't you mention this issue from the documentation page?
https://www.semantic-mediawiki.org/wiki/Help:Querying_for_the_absence_of_a_property

**Comment by alex-mashin** [comment]
I suppose that if `[[Default value::default]]` and `{{#defaults:property1=value1|property2=|property3=value3}}` allowing null (`[[Default value::]]`) are used instead of `[[Is mandatory::true]]`, this feature is going to be even more powerful.
