### ISSUE TITLE
Potential regression [[[[Has image::File:image.jpg]]]]

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2687]
### Setup and configuration

- SMW version: 2.5.4
- MW version: 1.27.3
- PHP version: 7.0.22-0ubuntu0.16.04.1 
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.19-0ubuntu0.16.04.1

### Issue:

 [[[[Has image::File:image.jpg]]]]
 gives an error message.
<img width="377" alt="grafik" src="https://user-images.githubusercontent.com/1336221/30687644-455dec9a-9ebc-11e7-8180-a35ca8e23403.png">

where it used to behave differently in the past by setting the Property "Has image" to "File:image.jpg" and then displaying the image (in square brackets).

### Steps to reproduce:
https://sandbox.semantic-mediawiki.org/wiki/HasImageError
has a different behavior with the same example then

see http://wiki.bitplan.com/index.php/SMWIssue2687 for the behavior described.

**Comment by mwjames** [comment]
> [[[[Has image::File:image.jpg]]]]
gives an error message.

Which is the correct behavior given that `[[ ... ]]`  contains (as per `$smwgPropertyInvalidCharacterList`) invalid characters within a property label depending from where the `InTextAnnotationParser` starts the parsing process.

You have two possibilities:

* Either remove `[` and `]` from the invalid list (#2282) or
* Set `$GLOBALS['smwgLinksInValues'] = SMW_LINV_OBFU;` (#2153) which is what can be seen in [0] as a result where the inner part is being recursively parsed and shows the same behaviour as MediaWiki without an annotation.

In any case an annotation like `[[ [[ ... ]] ]]` is semantically incorrect for creating a link (defined as `[[ .. ]]`, it is to note that using `[[Foo::[[...]] ]]` is different from the cited example `[[ [[Foo::Bar]] ]]`).

[0] https://sandbox.semantic-mediawiki.org/wiki/Issue/2687
