### ISSUE TITLE
Removing HHVM test support

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2688]
Given the announcement from Facebook [0] "... HHVM will not aim to target PHP7 ... " together with the responds from WMF [1] " ... plan is to migrate Wikimedia to PHP 7 ...", we will remove HHVM from the test matrix soon.

While SMW didn't make any specific modifications to allow it to run on HHVM, removing it from the test matrix will mean that we will no longer keep track of its compatibility or possible issues. 

SMW maybe be running on HHVM until the next HHVM 3.24 LTS release but projects should not expect any support beyond that point from SMW.

[0] http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
[1] https://phabricator.wikimedia.org/T176209#3623353

**Comment by kghbln** [comment]
Marking this with 3.1.0 since this version will probably drop support for PHP 5.6

**Comment by mwjames** [comment]
>SMW maybe be running on HHVM until the next HHVM 3.24 LTS release but projects should not expect any support beyond that point from SMW.

Facebook clarified its position in [0] with "HHVM v3.30 will be the last release series where HHVM aims to support PHP ... 2018-12-03: branch cut: expect PHP code to stop working with master and nightly builds after this date ..." therefore HHVM will be no alternative to run MediaWiki and hereby SMW.

Any user running a SMW instance on HHVM should switch to PHP 7.1 or PHP 7.2.

[0] https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html
