### ISSUE TITLE
|headers=plain breaks table head under "further results" 

### ISSUE THREAD

**Issue by stefahn** [SemanticMediaWiki/SemanticMediaWiki#2702]
## Setup
- MediaWiki | 1.29.1 (a69ecd8)18:59, 23. Aug. 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.32-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (a945401) 05:15, 24. Sep. 2017

## Issue
This is in reference to https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2000:

If |headers=plain is used in an ask query, the table head under "further results" is broken. See the 2nd example at https://sandbox.semantic-mediawiki.org/wiki/Modify_table_head. Also tested this on 2 of my own wikis.

Can this be fixed?

**Comment by kghbln** [comment]
I think `|headers=plain` is actually doing what it is supposed to do but I also see the issue. I created an [isolated page](https://sandbox.semantic-mediawiki.org/wiki/Issue/2702) for this.

**Comment by mwjames** [comment]
> Can this be fixed?

```
@@ -75,11 +75,11 @@ class TableResultPrinter extends ResultPrinter {
 				$columnClasses[] = $columnClass;
-				$text = $pr->getText( $outputMode, ( $this->mShowHeaders ==
SMW_HEADERS_PLAIN ? null : $this->mLinker ) );
+				$text = $pr->getText( SMW_OUTPUT_WIKI, ( $this->mShowHeaders ==
SMW_HEADERS_PLAIN ? null : $this->mLinker ) );
```

Above changes may correct the behaviour (I haven't tested it), if so,
please test carefully (to not introduce any regression) and send us a
PR.

In order to merge a PR, we would require another integration test that
verifies the modified behaviour.

Cheers

**Comment by mwjames** [comment]
Just to be clear, I'm not going to provide a PR for this. I have outlined a possible solution with the important part being to verify that no regression is introduced and that any PR is adding an additional integration test to cover the use case.

**Comment by kghbln** [comment]
I put this on my list.

**Comment by stefahn** [comment]
Thanks for your feedback and possible solution.
I'm not familiar with integration testing, so hopefully you can manage this Karsten.

**Comment by kghbln** [comment]
Mäh https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/issue-2702
