### ISSUE TITLE
Feature Request: syntax highlighting for ask queries

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2704]
When explaining ask queries like in http://waihekepedia.bitplan.com/index.php/Workdocumentation_2017-09-26#Example_for_a_semantic_query
it would be great to have the language "ask" work for syntax highlighting.

Did anybody already try to create something for it?

http://pygments.org/languages/
has a list of currently supported languages

http://pygments.org/docs/lexerdevelopment/
explains how to create another language

**Comment by kghbln** [comment]
I believe that this should build on top of a Wikitext lexer which we do not have yet either. I am not aware of anybody trying to create this but this has been asked for in the past.

**Comment by WolfgangFahl** [comment]
see https://www.mediawiki.org/wiki/Topic:Tyvdqm060cr42juo for the general request for mediawiki to support adding languages (again).

**Comment by TK-999** [comment]
[1] is an implementation of a wikitext syntax highlighter in JavaScript that is currently also being used at @Wikia to provide wikitext syntax highlighting in the source editor.

[1] https://www.mediawiki.org/wiki/User:Remember_the_dot/Syntax_highlighter

**Comment by kghbln** [comment]
> [1] is an implementation of a wikitext syntax highlighter in JavaScript

@TK-999 Thanks a lot for pointing to this.

**Comment by mwjames** [comment]
> it would be great to have the language "ask" work for syntax highlighting.

I can see that this might be useful to some but any code or lexer has to be placed outside of this repository (an implementation would be out of scope for this repository) therefore I'm not sure how we want to treat this and I'm more inclined to move this to https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4.

**Comment by mwjames** [comment]
As noted before this isn't really part of SMW core and doesn't contain any actionable items for the project team to act on.

Of course, interested parties can still pick the task from [0] and reopen it if new information or an external implementation is available.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4
