### ISSUE TITLE
Querying on Modification date with rebuildDate.php does not work 

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticMediaWiki#2708]
### Setup and configuration
- SMW version: **2.5.2 (84007ca)**
- MW version: **1.25.3**
- PHP version: 7.0.21 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version:  MySQL 5.6.11
- OS: Windows 7 

### Issue:
On the command line, when using special property [Modification date](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Modification_date) in the ```--query``` parameter of the [rebuildData.php](https://www.semantic-mediawiki.org/wiki/Help:Maintenance_script_%22rebuildData.php%22) script no results are shown. When running the same query on a [wiki page](https://www.semantic-mediawiki.org/wiki/User:Jongfeli#tab=Query_on_Modification_date) the correct results are shown.

### Steps to reproduce:
When creating and setting a separate property **LastEditDate** of the type date the query produces results.
```
php rebuildData.php --query='[[Category:SomeCategory]][[LastEditDate::^>28-9-2017]]'
```
When using **Modification date** the results is empty.
```
php rebuildData.php --query='[[Category:SomeCategory]][[Modification date::^>28-9-2017]]'
```

It would be nice if it where possible to use the special property **Modification date** to query for pages that have been altered to update any depending properties that would otherwise need a page purge to alter there value.

**Comment by mwjames** [comment]
> php rebuildData.php --query='[[Category:SomeCategory]][[Modification
> date::^>28-9-2017]]

Using something like ` php maintenance/rebuildData.php
--query='[[Modification date::>24-9-2017]]'` works for me.

I'm not sure what the `^>` is expected to do but `^` isn't a supported
expression.

Cheers

**Comment by kghbln** [comment]
> I'm not sure what the `^>` is expected to do but `^` isn't a supported expression.

@mwjames  I think that `^>` was meant to be `>>`

@jongfeli Does this work for you?

**Comment by jongfeli** [comment]
OK, with your input I dug a little deeper. We are using Windows Server 2008, the **.bat** file containing the commands is triggered by the Task Scheduler. It runs in **cmd**. 

When running these commands in **cmd** you need to escape certain characters. If you do not escape `>` the query will not work at all. See below from: https://ss64.com/nt/syntax-esc.html.
```
Escape Character
  ^  Escape character.
Adding the escape character before a command symbol allows it to be treated as ordinary text. 
When piping or redirecting any of these charcters you should prefix with the escape character: & \ < > ^ |

     e.g.  ^\  ^&  ^|  ^>  ^<  ^^ 
```
Now for the fun part, when I use **Windows PowerShell** to run the command there is no need for escaping `>`, it works just fine, the query returns the expected result. 

So the below code works in **PowerShell** but not in **cmd** when run on the same wiki.

```
php rebuildData.php --query='[[Category:SomeCategory]][[Modification date::>28-9-2017]]'
```
@mwjames are you using windows, if so what command line interface did you use?

**Comment by mwjames** [comment]
> @mwjames are you using windows, if so what command line interface did you use?

Using WIN8 and on both the standard cmd and git's mintty where queries are executed just fine without me trying to meddle with some character encoding.

![image](https://user-images.githubusercontent.com/1245473/31040898-e305b3f8-a5c7-11e7-8028-61e61d6efd98.png)

**Comment by jongfeli** [comment]
Ok, I will not spend any more time to try and figure out what is going on here. I wrote a **PowerShell** script that does the job.

Thanks for your time @mwjames.
