### ISSUE TITLE
smw-paramdesc-aggregation message missing

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2709]
https://wikiapiary.com/w/index.php?title=Special%3AAsk&q=+%5B%5BHas+extension%3A%3AExtension%3AMaps%5D%5D++%5B%5BHas+extension+version%3A%3A%21%7E*MLEB*%5D%5D&po=%3FHas+extension+version%3DVersion%0D%0A&eq=yes&p%5Bformat%5D=d3chart&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=-&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bdistribution%5D=1&p%5Bdistributionsort%5D=none&p%5Bdistributionlimit%5D=&p%5Baggregation%5D=property&p%5Bmin%5D=&p%5Bcharttype%5D=treemap&p%5Bheight%5D=400&p%5Bwidth%5D=100%25&p%5Bcharttitle%5D=&p%5Bcharttext%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bdatalabels%5D=&p%5Bcolorscheme%5D=&p%5Bchartcolor%5D=&eq=yes

SMW 2.4 alpha https://wikiapiary.com/wiki/Special:Version

Does not look like it is fixed on master https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=smw-paramdesc-aggregation&type=

**Comment by kghbln** [comment]
@JeroenDeDauw I have no idea which result format is affected. The linked example does not show any missing system message.

**Comment by kghbln** [comment]
Found it: [sparkline](https://www.semantic-mediawiki.org/wiki/Help:Sparkline_format)

**Comment by JeroenDeDauw** [comment]
I've updated the link. Found in the D3 format.
