### ISSUE TITLE
Make format=category responsive

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#2710]
### Setup and configuration

- SMW version: 2.5.4
- MW version: 1.30.0-alpha
- PHP version: 3.15.0 (srv)
- DB system (MySQL, Blazegraph, etc.) and version: 5.5.56-MariaDB

### Issue:

MediaWiki category listings were recently improved to be more responsive. Semantic MediaWiki categories output format does not have these improvements, and it would be nice to incorporate those.

Relevant patch: https://gerrit.wikimedia.org/r/#/c/194512/4

### Steps to reproduce:
See https://nimiarkisto.fi/wiki/Luokka:Pylk%C3%B6nm%C3%A4ki for an example.

```
{{#ask: [[{{FULLPAGENAME}}]]
 |format=category
 |columns=3
}}
```

**Comment by mwjames** [comment]
> Semantic MediaWiki categories output format does not have these
> improvements, and it would be nice to incorporate those.

If I remember correctly, using `columns=0` (#1147) should make it responsive.

Cheers

**Comment by kghbln** [comment]
@Nikerabbit Thanks for reporting. Does `columns=0` work for you? Adding "question" for the time being.

**Comment by Nikerabbit** [comment]
Oh that indeed works and it works very well, great.

Can this feature be mentioned in https://www.semantic-mediawiki.org/wiki/Help:Category_format ?

**Comment by kghbln** [comment]
> Oh that indeed works and it works very well, great.

Cool. Thanks for giving it a shot.

> Can this feature be mentioned

[Now documented!](https://www.semantic-mediawiki.org/w/index.php?title=Help:Category_format&diff=54761&oldid=54759)
