### ISSUE TITLE
PHPUnit 6.x fails

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2713]
### Setup and configuration

- SMW version: all
- PHP version: 7.1

### Issue:

Requires https://phabricator.wikimedia.org/T177132 (MediaWiki core)

#### Fatal error: Class 'PHPUnit_ ...

The first issue one encounters is that PHPUnit doesn't declare any aliases so before it starts y'd be greeted with:

* `Fatal error: Class 'PHPUnit_Framework_TestCase' not found in ...`
* `Fatal error: Class 'PHPUnit_Framework_TestResult' not found in ...`
* `Fatal error: Class 'PHPUnit_Framework_Assert' not found in ...`

Adding the following aliases removes above error messages.

```
class_alias( 'PHPUnit\Framework\TestCase', 'PHPUnit_Framework_TestCase' );
class_alias( 'PHPUnit\Framework\TestResult', 'PHPUnit_Framework_TestResult' );
class_alias( 'PHPUnit\Framework\Assert', 'PHPUnit_Framework_Assert' );
```

#### Error: Call to undefined method

The next issue is:

`Error: Call to undefined method SMW\Tests\...::setExpectedException()` [0], doing a quick `git grep -l 'setExpectedException' | xargs sed -i 's/setExpectedException/expectException/g'` solves the issue and have the tests pass as before with:

```
Using PHP 7.1.1

Semantic MediaWiki: 3.0.0-alpha (7e9a979, SMWSQLStore3, mysql)
MediaWiki:          1.30.0-alpha (38999cc, MediaWiki vendor autoloader)
Site language:      en

Execution time:     2017-09-30 09:33
Debug logs:         Disabled
Xdebug:             Disabled (or not installed)

PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.1
Configuration: D:\xampp\htdocs\mw-master-phpunit\extensions\SemanticMediaWiki\phpunit.xml.dist

.............................................................   61 / 5544 (  1%)
...
......................................................        5544 / 5544 (100%)

Tests: 5544, Assertions: 15616, Warnings: 4, Skipped: 15.

```

Unfortunately, `expectException` is unknown before PHPUnit 5.2 therefore replacing it as of now is not possible.

[0] https://github.com/sebastianbergmann/phpunit/issues/2074#issuecomment-183472385

**Comment by JeroenDeDauw** [comment]
Yeah the `expectException` thing is annoying, I've run into it many times before. Unless you can be PHP 7.x only, you're forced to stick with the older version. Once you can be 7.x only, it is easy to deal with, and the same is true for the class name.

**Comment by legoktm** [comment]
(coming from the Phabricator ticket) Is there a reason you're trying to use PHPUnit 6.x? MediaWiki core will probably upgrade once the [minimum PHP version is bumped to 7.0](https://phabricator.wikimedia.org/T172165).

**Comment by mwjames** [comment]
>  Is there a reason you're trying to use PHPUnit 6.x? 

Currently we are running PHPUnit 5.7 on PHP 7.1 and according to [0] "... PHPUnit 5.7 will receive bug fixes until February 2, 2018 ..." therefore sooner or later we have to bite the bullet of upgrading. This ticket is to track the effort and possible drawbacks when a switch becomes necessary.

As demonstrated, we can easily switch our side but MW as shown wouldn't work out of the box either way.

[0] https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.7.0

**Comment by mszabo-wikia** [comment]
@mwjames @JeroenDeDauw  I was thinking a workaround would be to provide a `setExpectedException`polyfill in the class alias for old `PHPUnit_Framework_TestCase`, kind of like this:

```php
use PHPUnit\Framework\TestCase;

class CompatibilityTestCase extends TestCase {
	protected function setExpectedException( $exception, $message = '', $code = null ) {
		$this->expectException( $exception );

		if ( $message !== null && $message !== '' ) {
			$this->expectExceptionMessage( $message );
		}

		if ( $code !== null ) {
			$this->expectExceptionCode( $code );
		}
	}
}

class_alias( 'CompatibilityTestCase', 'PHPUnit_Framework_TestCase' );
```

What do you think?

**Comment by mwjames** [comment]
@mszabo-wikia

> @mwjames @JeroenDeDauw I was thinking a workaround would be to provide a setExpectedExceptionpolyfill in the class alias for old PHPUnit_Framework_TestCase, kind of like this:

Thanks. I created a compat trait to cover the issue.
