### ISSUE TITLE
Wildcard search with blanks does not work as expected

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2731]
### Setup and configuration
current SMWmain wiki and sandbox

### Issue:
Searching for blanks with like and  wildcard operator creates unexpected results.

According to https://www.semantic-mediawiki.org/wiki/Help:Selecting_pages#Wildcards Wildcard and https://www.semantic-mediawiki.org/wiki/Help:Selecting_pages#Like.2C_not_like i
_For example, one could ask [[Address::~*Park Place*]] to select addresses containing the string "Park Place"_

When tryingto do something similar other records get matched that have only one of the words. E.g. it would be like all "Park" and all "Place" entries are selected. 
### Steps to reproduce:

Create two pages setting a text attribute to "Attendee events" to:

1. SMWCon Spring 2015
2. SMWCon Fall 2015, SMWCon Spring 2015, SMWCon Fall 2016, SMWCon Fall 2017

{{#ask: [[Attendee events::~*Fall 2015*]]|format=table}}
should return only the page 2. In fact both pages are shown. See:

Sandbox page https://sandbox.semantic-mediawiki.org/wiki/Issue/2731

Is there a workaround for this? I tried https://sandbox.semantic-mediawiki.org/wiki/Issue/2731/workaround but none of the approaches changed anything.

**Comment by mwjames** [comment]
On both systems the full-text is enabled hence the search uses the logic that comes with the full-text engine. For a more detailed introduction, see [1] or [2].

Spaces are treated as word separator hence you have to apply for a phrase matching when you are looking for a direct match of "Fall 2015".

The SQL `LIKE` operator works different in comparison to `MATCH` but to still be able to use `LIKE` in combination with an enabled full-text, #2558 was introduced.

[0] https://stackoverflow.com/questions/36437704/mysql-full-text-search-boolean-mode-with-spaces
[1] https://www.semantic-mediawiki.org/wiki/Fulltext/Searching
[2] https://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html

**Comment by WolfgangFahl** [comment]
Thanx for the comment. IMHO the documentation needs to be changed then.

**Comment by kghbln** [comment]
> IMHO the documentation needs to be changed then.

I have now [added a note pointing to the respective docu](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASelecting_pages&type=revision&diff=54907&oldid=53952) which was missing. Indeed the docu needs a general overhaul and #2558 is not even documented yet.
