### ISSUE TITLE
Checkmark output format for Boolean properties

### ISSUE THREAD

**Issue by Eventhor** [SemanticMediaWiki/SemanticMediaWiki#2733]
### Setup and configuration

- SMW version: 3.0.0
- MW version:
- PHP version:
- DB system (MySQL, Blazegraph, etc.) and version:

### Issue:
The use of a readonly checkbox with checkmark for true and no mark for false would be a format for a Boolean property value that was intelligible for all language users.

**Comment by kghbln** [comment]
Have you read though [the help page](https://www.semantic-mediawiki.org/wiki/Help:Type_Boolean). This may also be of interest for you https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1580 which is not yet documented on wiki.

**Comment by mwjames** [comment]
> The use of a readonly checkbox with checkmark for true and no mark for false would be a format for a Boolean property value that was intelligible for all language users.

I'm a bit unclear as that what is proposed here. Does this related to
an input condition (UI specific) on some kind of form (aka PageForms)
specification or does this describe a specific input characteristic of
an annotation (e.g. `[[My Boolean::x]]`)?

I think some clarification is necessary to better understand the
requirements and as noted in [0] a clear and concise use case would
further help to elevate your inquiry.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/CONTRIBUTING.md#feature-requests

**Comment by Eventhor** [comment]
I know about the output formatting option **LOCL** by which output is localised from yes or no. Still I miss the obvious (IMO) variant using a checkmark in a box (for true). I know **PageForms** uses this for input of **Boolean** values, and I think it would be cherished to have it as a formatting option for the general **SMW query output**.

**Comment by mwjames** [comment]
> uses this for input of
> **Boolean** values, and I think it would be cherished to have it as a
> formatting option for the general **SMW query output**.

Sorry, I still don't get it. As demonstrated in #1580, you already can
define the output option as in:

```
{{#ask: [[Has boolean::+]]
 |?Has boolean#x,-
 |?Has boolean#✓,✕
 |?Has boolean#○,×
}}
```

Are we talking about something else?

**Comment by Eventhor** [comment]
So sorry, I have completely missed these formatting options when reading the help pages.
And happy to see they are already there.
I close the issue immediately.

**Comment by Eventhor** [comment]
It was premature to close the issue:
The use of the square root sign, or similar, is not sufficient for me. I think a checkbox, empty or with a tic, would be clearer to the user, as generated from
<input type="checkbox" name="FirstBoolean" value="false" readonly="readonly"/>Unchecked/false
<input type="checkbox" name="SecondBoolean" value="true" readonly="readonly"
           checked="checked"/>Checked/true

**Comment by mwjames** [comment]
@kghbln Has updated the [0] with `Boolean#☑,☐` as output example.

> `<input type="checkbox" name="FirstBoolean" value="false" readonly="readonly"/>Unchecked/false
<input type="checkbox" name="SecondBoolean" value="true" readonly="readonly"
           checked="checked"/>Checked/true`

Those constructs will not be supported and will most likely be stopped by the sanitizer.

If you need a more sophisticated display method then using the template format or Lua to manipulate its output characteristics seems a better approach. You may also use `<span>` with a class to add additional attributes.

[0] https://sandbox.semantic-mediawiki.org/wiki/Issue/1580

**Comment by Eventhor** [comment]
The format
|?Boolean#☑,☐
is ok with me for the described need.

Is it possible for an administrator to make it default for boolean properties?

**Comment by kghbln** [comment]
> Is it possible for an administrator to make it default for boolean properties?

No, the display format has to be added individually to every inline query.
