### ISSUE TITLE
Provide and update documentation

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2762]
## Target release

<s>3.0</s> Ongoing task

## Issue

Making this now a hard requirement for a release. As to why, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1365#issuecomment-334902073 and I'm explicitly expect @kghbln __NOT__ to pick this task.

This is a non-developer task, so anyone can contribute and help the project in moving forward so that by the time of a release the documentation is up-to-date.

Unrelated to the task itself but as reference on the documentation issue:

- https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/33
- https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/38

## Tasks

- [x] Check the [release notes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-NOTES.md) for links to the `smw@org` wiki and provide necessary template work and place holders to avoid "This page doesn't exist" message
- [ ] Check the [wikidocu missing](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aclosed+label%3A%22wikidocu+missing%22) task and fix require documentation

PS: I'm happy to answer specific questions to an unclear wording, or extend on the description of a specific PR.

**Comment by kghbln** [comment]
I am doing a tour de force lately but I am still under the impression of loosing ground when it comes to documenting stuff.

**Comment by jaideraf** [comment]
@kghbln in your previous message, I think you mean [this page for "wikidocu missing"](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?utf8=%E2%9C%93&q=label%3A%22wikidocu+missing%22+).

**Comment by mwjames** [comment]
My recent attempts with the documentation was to make sections shorter, provide more dedicated subpages, and add visual aids, to help users quickly grasp the "What it is about" and isn't overwhelmed by the sheer amount of text that has been the standard for the wiki for years.

[0] is such typical page (no offense to the various editors) where you have to scroll back and forth to catch what this page tries to convey mixing text and examples making it fairly difficult to see what the system has to offer and "How to" transfer the knowledge.

There should be common theme visible among the recent updates to:

- https://www.semantic-mediawiki.org/wiki/Help:Missing_redirect_annotations
- https://www.semantic-mediawiki.org/wiki/Help:Property_group
- https://www.semantic-mediawiki.org/wiki/Help:Mandatory_parent_datatype_inheritance
- https://www.semantic-mediawiki.org/wiki/Help:Upgrade
- https://www.semantic-mediawiki.org/wiki/Help:Replication_monitoring
- https://www.semantic-mediawiki.org/wiki/Help:Duplicate_entities

[0] https://www.semantic-mediawiki.org/wiki/Help:Sorting#User_manual

![image](https://user-images.githubusercontent.com/1245473/53701192-7375f100-3df2-11e9-9265-c35b907b7317.png)

**Comment by kghbln** [comment]
This is a "To do" within the documentation project.
