### ISSUE TITLE
dumpRDF.php does not find LocalSettings.php

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticMediaWiki#2778]
### Setup and configuration

- SMW version: 2.5.4
- MW version: 1.29.1
- PHP version: 7.0.19-1
- DB system (MySQL, Blazegraph, etc.) and version: mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Issue:

When running `php extensions/SemanticMediaWiki/maintenance/dumpRDF.php --conf LocalSettings.php` I get this error:
```
A copy of your installation's LocalSettings.php
must exist and be readable in the source directory.
Use --conf to specify it.
```

But the file is there:
```
pierre@pierre ~/w/archi-mediawiki> file LocalSettings.php 
LocalSettings.php: PHP script, UTF-8 Unicode text
```

### Steps to reproduce:
Our setup is available here: https://github.com/Archi-Strasbourg/archi-mediawiki
The main thing is that because we use Composer to install MediaWiki, so some files are not in the default place. (However, MediaWiki's maintenance scripts work fine when using `--conf`.)

**Comment by mwjames** [comment]
> When running `php extensions/SemanticMediaWiki/maintenance/dumpRDF.php
> --conf LocalSettings.php` I get this error:
> ```
> A copy of your installation's LocalSettings.php
> must exist and be readable in the source directory.
> Use --conf to specify it.
> ```

Try to extend this class with:

```
@@ -68,10 +68,12 @@ class DumpRdf extends \Maintenance {
 	 *
 	 * @since 2.0
 	 */
 	protected function addDefaultParams() {

+		parent::addDefaultParams();
```

@kghbln If this hits the jackpot then adding it to the other scripts
should be made a follow-up.

Cheers

**Comment by kghbln** [comment]
I guess that setting the absolute path to "LocalSettings.php" for the `--conf` parameter should help as an interim solution.

**Comment by Rudloff** [comment]
It does not work either when I use the full path as workaround.
But the patch does fix the issue.

**Comment by kghbln** [comment]
> It does not work either when I use the full path as workaround.

Interesting. Anyways thanks for testing and confirming the fix!
