### ISSUE TITLE
Error: 1142 CREATE command denied to user ... for table 'smw_object_ids' (MySQL master/slave setup)

### ISSUE THREAD

**Issue by nexus511** [SemanticMediaWiki/SemanticMediaWiki#2779]
### Setup and configuration

- SMW version: 2.5.4
- MW version: 1.27.3
- PHP version: 5.6
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.6

### Issue:

After installing semantic-mediawiki via composer, maintenance/update.php cannot setup database in multi-database configuration (master/slave). Output of exception:

```
Checking table smw_object_ids ...
   Table not found, now creating...
[58c8cddef0aa3c40c8eff5a8] [no req]   DBQueryError from line 1054 of <PATH>/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: CREATE TABLE `my_wiki`.`smw_object_ids` (smw_id INT(8) UNSIGNED NOT NULL KEY AUTO_INCREMENT,smw_namespace INT(11) NOT NULL,smw_title VARBINARY(255) NOT NULL,smw_iw VARBINARY(32) NOT NULL,smw_subobject VARBINARY(255) NOT NULL,smw_sortkey VARBINARY(255) NOT NULL,smw_proptable_hash MEDIUMBLOB) ENGINE=InnoDB, DEFAULT CHARSET=binary
Function: SMW\SQLStore\TableBuilder\MySQLTableBuilder::doCreateTable
Error: 1142 CREATE command denied to user '<user>'@'<host>' for table 'smw_object_ids' (<server>)

```

### Steps to reproduce:

1. install a fresh mediawiki and setup one MySQL master and one MySQL slave via $wgDBservers in LocalSettings.php
2. install SMW using `composer require mediawiki/semantic-media-wiki "~2.5" --update-no-dev`
3. run `php maintenance/update.php --skip-external-dependencies`

**Comment by mwjames** [comment]
> cannot setup database in multi-database configuration (master/slave). Output
> of exception:

We had a fairly long discussion about a multi-database environment in
#2532, so we known there are users that make use of such
configurations successfully.

> Error: 1142 CREATE command denied to user '<user>'@'<host>' for table
> 'smw_object_ids' (<server>)

Please have a look at [0] about the required DB rights. For a historic
reference, see [1].

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation#Settings
[1] https://phabricator.wikimedia.org/T15519

**Comment by kghbln** [comment]
I am assuming that the response lead the way to resolve the issue. Thus closing. Please re-open with elaborate information in case the problem still persists.
