### ISSUE TITLE
Property page, JSON schema, and content type

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2784]
Moving discussion from #2769 to its own issue:

**Comment by mwjames** [comment]
@JeroenDeDauw Can we move related discussions this this thread?

**Comment by WolfgangFahl** [comment]
It would be great if the PlantUML extension would be installed and I could continue explaining .. as outlined in #1330

**Comment by mwjames** [comment]
> It would be great if the PlantUML extension would be installed and I could continue explaining 

You can attached picture (or graphs) to this issue, no need to divert the discussion to a wiki page.

**Comment by mwjames** [comment]
> Pierre Racine http://www.cef-cfr.ca/uploads/Membres/PierreRacine-SMWCon2013-SMW_Metaproperties.pdf had also an original idea on this ...

To be clear, the proposal will have nothing in common with PS or have a particular support for PF. It is about using a JSON schema to store declarative information in a structure and machine readable format that may or may not use its own UI interpreter to display the stored information.

**Comment by WolfgangFahl** [comment]
@mwjames - I want to show live example which are created by a generator tool. I'd have to change the generator since it depends on using PlantUML. That's why quite a few useful things have not yet made it to http://www.semantic-mediawiki.org. I think it is more an issue of priorities.

**Comment by mwjames** [comment]
Moving it to "Enhancements and features" for future deliberation as it unlikely to make the 3.0 release cut.

**Comment by JeroenDeDauw** [comment]
Hi James. I think I never saw this. If you want me to look at a PR or issue, please mail me. You are doing too much stuff for me to check all of it :)

**Comment by mwjames** [comment]
> Hi James. I think I never saw this. If you want me to look at a PR or issue, please mail me.

Thanks. Will do.
