### ISSUE TITLE
Warning: preg_replace(): Compilation failed: unmatched parentheses at offset 24

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2797]
### Setup and configuration

- MediaWiki | 1.29.1 (901313e)16:21, 20. Okt. 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (a5e9fbe) 09:24, 2. Nov. 2017

### Issue:

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
Warning: preg_replace(): Compilation failed: unmatched parentheses at offset 24 in /../w/extensions/SemanticMediaWiki/src/IntlNumberFormatter.php on line 237
```

### Steps to reproduce:
Access a page on <sandbox> and [append `?uselang=qqx`](https://sandbox.semantic-mediawiki.org/wiki/Berlin?uselang=qqx). 2.5.x appears [not to be affected](https://www.semantic-mediawiki.org/wiki/Demo:Berlin?uselang=qqx)

**Comment by mwjames** [comment]
> Access a page on and append ?uselang=qqx. 2.5.x appears not to be affected

Are you sure because the code should be the same as far as I remember since I haven't changed anything in `IntlNumberFormatter.php on line 237`.

**Comment by kghbln** [comment]
> Are you sure

The only thing I can say is that smw.o does not show this behavior and I was not able to reproduce with the same page contents.

**Comment by mwjames** [comment]
>The only thing I can say is that smw.o does not show this behavior and I was not able to reproduce with the same page contents.

Since this is a language thing, could be related to the MediaWiki version. I'm guessing (without having looked at it) that `append ?uselang=qqx.` returns an invalid string and we get some unexpected results that causes some issues in:

```
			// Make it more readable by removing ending .000 from nnn.000
			//    Assumes substr is faster than a regular expression replacement.
			$end = $decseparator . str_repeat( '0', $precision );
			$lenEnd = strlen( $end );

			if ( substr( $value, - $lenEnd ) === $end ) {
				$value = substr( $value, 0, - $lenEnd );
			} else {
				// If above replacement occurred, no need to do the next one.
				// Make it more readable by removing trailing zeroes from nn.n00.
---->				$value = preg_replace( "/(\\$decseparator\\d+?)0*$/u", '$1', $value, 1 );
			}
```

**Comment by Nikerabbit** [comment]
Invalid or not, shouldn't you always use preg_quote for all input put into `preg_replace`?

**Comment by mwjames** [comment]
> and append ?uselang=qqx

Since the language `qqx` is unknown it returns `(smw_decseparator)` as string which then causes `preg_replace` to blow.

> Invalid or not, shouldn't you always use preg_quote for all input put into preg_replace?

Doing a simple `preg_quote` breaks our tests.

```
@@ -230,10 +230,11 @@ class IntlNumberFormatter {
 			$lenEnd = strlen( $end );
 
 			if ( substr( $value, - $lenEnd ) === $end ) {
 				$value = substr( $value, 0, - $lenEnd );
 			} else {
+				$decseparator = preg_quote( $decseparator );
 				// If above replacement occurred, no need to do the next one.
 				// Make it more readable by removing trailing zeroes from nn.n00.
 				$value = preg_replace( "/(\\$decseparator\\d+?)0*$/u", '$1', $value, 1 );
 			}
 		}
```

**Comment by Nikerabbit** [comment]
It should be `preg_quote( $decseparator, '/' )` but that is not the issue. I am trying to understand the pattern, which looks weird. If you use `preg_quote`, it seems the first `\\` is unnecessary. I assume it was meant to escape the `$decseparator`, but it assumed that it was only one character long.

**Comment by mwjames** [comment]
> `preg_quote`, it seems the first `\\` is unnecessary. I assume it was meant
> to escape the `$decseparator`, but it assumed that it was only one character

Nice.

```
@@ -230,13 +230,14 @@ class IntlNumberFormatter {
 			$lenEnd = strlen( $end );

 			if ( substr( $value, - $lenEnd ) === $end ) {
 				$value = substr( $value, 0, - $lenEnd );
 			} else {
+				$decseparator = preg_quote( $decseparator, '/' );
 				// If above replacement occurred, no need to do the next one.
 				// Make it more readable by removing trailing zeroes from nn.n00.
-				$value = preg_replace( "/(\\$decseparator\\d+?)0*$/u", '$1', $value, 1 );
+				$value = preg_replace( "/($decseparator\\d+?)0*$/u", '$1', $value, 1 );
```

For some historical context, this particular code snippet exists at
least since version 1.4.1 [0] (aka 2008).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.4.1/includes/SMW_GlobalFunctions.php#L553-L564

Cheers
