### ISSUE TITLE
#nowiki should work for Properties of type External Identifier

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2808]
according to 

https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#URL

it is possible to query a Property of Type url with # nowiki

this should IMHO also work with external identifiers see:

see https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2017-11-06_WF-b

for the current different behavior.

**Comment by kghbln** [comment]
Thanks for reporting. I guess the main purpose of the external identifier is a bit different but in the end we have an URL so I labeled this as an enhancement.

**Comment by WolfgangFahl** [comment]
I think #2808 is not quite finished yet. An example for reference is missing and I think it would be good to have a "in this wiki" example link in the german and english template.
