### ISSUE TITLE
Feature request: Sort by a specific record

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticMediaWiki#2811]
Hello,

I have a record property that is set multiple times per page:
```
[[MyRecord::A; 12]]
[[MyRecord::B; 23]]
```

If I do something like this:
```
{{#ask:
[[MyRecord::B]]
|sort=MyRecord|+index=2
}}
```
I get every page with a B record but they are not sorted by that record, since the lowest number (12) is used for sorting.
It would be useful to have a way to specify a record constraint for sorting. Something like this: `|sort=MyRecord[B]|+index=2`

**Comment by mwjames** [comment]
As for the a feature request, [0] outlines certain expectations. The given example is insufficient to demonstrate the intend of the request.

[1] contains a more comprehensive example based on the information provided above.

> sort=MyRecord[B]|+index=2

This is a syntax that would be type dependent (record type) and cannot be combined with any other type therefore its implementation is unlikely to happen.

As for the sorting of a particular field component, you may use `sort=Record2811.Has number` [2] to define a specific field and hereby its order. [1] demonstrates different ordering on the specific field and its values.

#2655 maybe related on filtering a specific value component.

PS: It is very unlikely that I will have a closer look at this issue in near future especially in regards to any implementation details. It should not be counted as to make this issue invalid but to inform involved parties about the likelihood of a coding sprint.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/CONTRIBUTING.md#feature-requests
[1] https://sandbox.semantic-mediawiki.org/wiki/Issue/2811
[2] https://www.semantic-mediawiki.org/wiki/Help:Property_chains_and_paths

**Comment by Rudloff** [comment]
Thanks for your answer. Sorry for not providing a sandbox example, I wasn't sure about the best way to represent the issue.
Also my last example was just pseudo-code to try to explain what I need but of course the syntax might not be the best.

Here is more info about our use case:
We have pages describing buildings and buildings can have multiple numbers in different streets, so we use a record field with `[[Has fields::Street; Number]]` to store them.
But when listing every building in a street we want to order them by their number *in that street*.

Doing something like this:
```
{{#ask:
[[Street number::Foo]]
|sort=Street number.Number
}}
```
will sort them by any number they have in any street so we need a way to restrict the sorting to numbers in the street we are currently looking at.

**Comment by kghbln** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
