### ISSUE TITLE
Setup and the use of $wgExtensionFunctions

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2813]
Relates to [0] and the comment "... SemanticMediaWiki needs to stop registering its hooks in a $wgExtensionFunctions, which is too late... ". To avoid diluting the task with some internal SMW specific information, I will roughly sketch out the setup, required processes, and the involvement  of `$wgExtensionFunctions`.

## Overview

![image](https://user-images.githubusercontent.com/1245473/32651442-68b736b0-c644-11e7-8a1c-e06b09a16718.png)

The software relies on settings to be set and `$wgExtensionFunctions` ensures we have access to those after `LocalSettings.php` changed its default values which may or may not be used as part of a hook invocation.

###  Hook registration

Hook registration generally uses a callback and follows a similar pattern as outlined below in order to:

- be tested separately without the reliance on a static caller
- isolates configurations and GLOBALS from an instance
- use of a factory instance to access services
- shared services are build using a container builder

```

/**
 * @see https://www.mediawiki.org/wiki/Manual:Hooks/EditPage::showEditForm:initial
 */
$this->handlers['EditPage::showEditForm:initial'] = function ( $editPage, $output ) use ( $applicationFactory ) {

	$user = $output->getUser();
	$settings = $applicationFactory->getSettings();

	$editPageForm = new EditPageForm(
		$applicationFactory->getNamespaceExaminer()
	);

	$editPageForm->setOptions(
		[
			'smwgEnabledEditPageHelp' => $settings->get( 'smwgEnabledEditPageHelp' ),
			'prefs-disable-editpage' => $user->getOption( 'smw-prefs-general-options-disable-editpage-info' )
		]
	);

	return $editPageForm->process( $editPage );
};
```

[0] https://phabricator.wikimedia.org/T78018

**Comment by kghbln** [comment]
I labeled and added this to the relevant board to make sure it does not forgotten.

**Comment by legoktm** [comment]
> The software relies on settings to be set and $wgExtensionFunctions ensures we have access to those after LocalSettings.php changed its default values which may or may not be used as part of a hook invocation.

This is wrong. If you want to conditionally register special pages based on configuration, use the `SpecialPage_initList` hook. You register that hook unconditionally and in the extension entrypoint, and then read from the configuration values in the hook itself. The hook itself will never be called before LocalSettings is read, but it will be called before $wgExtensionFunctions are run, as in the ShortUrl bug. There's a similar hook for conditionally registering API modules.

**Comment by mwjames** [comment]
>  You register that hook unconditionally and in the extension entrypoint, and then read from the configuration values 

Yes, and as I outlined those should not use a static caller. Hook definition are expected to be defined as callbacks with `Namespace::initCanonicalNamespaces` remaining the only exception.

` $wgExtensionFunctions` is the endpoint to build an instance without a static reference, I cannot see how you register hooks like `SpecialPage_initList` unless you go back to the `MyStaticCaller::onDoSomething` pattern which is discouraged in this repository.

The system is simple:
```
$setup = new Setup( $GLOBALS );
$setup->run();
  |- ...
  |- ...
  |- $hookregistry = new HookRegistry(  ... );
     $hookregistry->register();

No static callers!!
```

**Comment by legoktm** [comment]
I was suggesting you make an exception for SpecialPages and API modules just like Namespaces.

For the static hooks problem, I'm not sure if you're aware of the solution the Wikidata team is using, which is a static hook class that is just a proxy to a non-static method. https://github.com/wikimedia/mediawiki-extensions-WikimediaBadges/blob/master/includes/OtherProjectsSidebarHookHandler.php#L72 is a relatively simple example.

**Comment by mwjames** [comment]
> I was suggesting you make an exception for SpecialPages and API modules just like Namespaces.

Okay, @kghbln @s7eph4n this is up for grabs  (outreach or whatever program). It should be fairly simple and straight forward I guess (haven't look at it).

> API modules

To clarify, you mean `APIAfterExecute`?

**Comment by legoktm** [comment]
`ApiMain::moduleManager` for registering action modules, and `ApiQuery::moduleManager` for query modules.

**Comment by mwjames** [comment]
> ApiMain::moduleManager for registering action modules, and ApiQuery::moduleManager for query modules.

I couldn't find them listed at https://www.mediawiki.org/wiki/Manual:Hooks.

**Comment by osnard** [comment]
Wouldn't the hook `SetupAfterCache` (fired before `$wgExtensionFunctions`) also be a suitable place to run SMW setup? There is also the on-registration-`callback` in `extension.json` that is executed directly when `wfLoadExtension` is called. This might be to early, though, but it would be similar to the old `enableSemantics` calltime.

**Comment by mwjames** [comment]
> This might be to early, though, but it would be similar to the old enableSemantics calltime.

To clarify, there will be no old `enableSemantics` even in case of a
possible supported `extension.json` in SMW due to reasons given in
#1732.

> Wouldn't the hook `SetupAfterCache` (fired before `$wgExtensionFunctions`)
> also be a suitable place to run SMW setup? There is also the

As for the use of `SetupAfterCache`, at least for the namespace issue
it can not be used [0] since it is called after the invocation of
`LocalSettings` and would cause the same problems as outlined in
#1732.

Generally, I don't think there is much difference in the execution
point which happens slightly earlier for `SetupAfterCache` [1] then
for `wgExtensionFunctions` [2] and would fail on the `SpecialPages`
and `API modules` issue for the same reason on being "too late".

I'm making an assumption that having a hook before [3] would most
likely help with the outlined issue in #1732 (and the others since the
hook would be called before [4]).

[0] https://github.com/wikimedia/mediawiki/blob/1c7c8b2540f30ba74ab00ffeb959dc9d2780ee27/includes/Setup.php
[1] https://github.com/wikimedia/mediawiki/blob/1c7c8b2540f30ba74ab00ffeb959dc9d2780ee27/includes/Setup.php#L794
[2] https://github.com/wikimedia/mediawiki/blob/1c7c8b2540f30ba74ab00ffeb959dc9d2780ee27/includes/Setup.php#L924
[3] https://github.com/wikimedia/mediawiki/blob/1c7c8b2540f30ba74ab00ffeb959dc9d2780ee27/includes/Setup.php#L88-L95
[4] https://github.com/wikimedia/mediawiki/blob/1c7c8b2540f30ba74ab00ffeb959dc9d2780ee27/includes/Setup.php#L115-L118

**Comment by mwjames** [comment]
> Okay, @kghbln @s7eph4n this is up for grabs (outreach or whatever program). It should be fairly simple and straight forward I guess (haven't look at it).

Never mind, I took care of it myself (2888).
