### ISSUE TITLE
Regression: relative urls get http:// prepended

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2825]
The following wiki markup:
```
{{#set:
has url=/w/images/2/2e/SMWConFall2017Logo.png
}}
{{#show: {{FULLPAGENAME}}|? has url}}

```
will lead to 
http://w/images/2/2e/SMWConFall2017Logo.png
be shown instead of keeping the relative URL which would work.

This is IMHO a regression to the old behavior where the relative URL would stay intact.

In my wikifarm hundreds of links are now broken so I'd appreciate a hotfix or patch advice.

See https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2017-11-12

**Comment by mwjames** [comment]
> This is IMHO a regression to the old behavior where the relative URL would stay intact.

@kghbln Is that a fact? And if so with what release?

**Comment by kghbln** [comment]
I have never done this since I always add in the full URL no matter what. So if you add an URL including the protocol then it does not get prepended. Perhaps this is the issue: Datatype URL expects a value to also contain the protocol and if it is not there it adds it automatically. There could indeed have been a change in behaviour but I am not sure.

However the most important information is missing here. The upgrade was done from SMW x to SMW y?

Anyways why not instead use the `filepath:` parser function to set the values?

PS The sandbox wiki is probably the better place to demonstrate an issue.

**Comment by WolfgangFahl** [comment]
Just tried it out on a Semantic Mediawiki 2.3.1. The relative URL is taken as is and will not be properly clickable by itself. But it is useable in scripts and templates using the baseurl of the site as the root path. We use this style to pass relative URLs to widgets.

**Comment by WolfgangFahl** [comment]
The filepath parser function is not available on my old wikis. On the new wikis I'd have to change a quite a bit to go that route if it would be feasible at all. The relative paths come from a masterwiki and the child and farm wikis might have different setups .

**Comment by kghbln** [comment]
I still think that the expected behaviour is to prepend http:// so prefious versions of SMW had an issue and not the current one. So changing to datatype "Text" should be the solution?!

**Comment by mwjames** [comment]
I took the time to find an old MediaWiki with:

![image](https://user-images.githubusercontent.com/1245473/32702718-489410d8-c82e-11e7-8408-c98341c9d497.png)

and for your example it produces the same result (aka expected result) as on 2.5+ and 3.+:

![image](https://user-images.githubusercontent.com/1245473/32702668-85e57f04-c82d-11e7-83e8-424b43a6567e.png)

![image](https://user-images.githubusercontent.com/1245473/32702664-6656308e-c82d-11e7-9f60-1ddc5e75784e.png)

![image](https://user-images.githubusercontent.com/1245473/32702678-9c67a81a-c82d-11e7-8086-54bc2fb49370.png)

We always prepend an URL type with a protocol and I cannot recall that SMW ever supported protocol relative URIs.

**Comment by WolfgangFahl** [comment]
Now that is interesting.
![grafik](https://user-images.githubusercontent.com/1336221/32713439-861b0540-c849-11e7-8e51-49f4d393a2af.png)
![grafik](https://user-images.githubusercontent.com/1336221/32713451-9527e526-c849-11e7-8ac4-9ef2b318f211.png)

![grafik](https://user-images.githubusercontent.com/1336221/32713418-6e750558-c849-11e7-8704-639f3c9decd2.png)

![grafik](https://user-images.githubusercontent.com/1336221/32713383-521a64de-c849-11e7-9d6d-ef7e93b8567d.png)

**Comment by kghbln** [comment]
You are using datatype "Page" for your property. ;)

**Comment by WolfgangFahl** [comment]
@kghbln on which of the wikis mentioned above? I don't think this should be closed.

**Comment by kghbln** [comment]
On yours

**Comment by WolfgangFahl** [comment]
I do not get it - if you talk about:

https://www.semantic-mediawiki.org/wiki/Property:Has_url has a definition of
[[Has type::URL]]

The wiki 
http://162.243.72.168/index.php/Workdocumentation_2017-11-12
is not public it has:
http://162.243.72.168/index.php/Property:Has_url
with
[has type::URL]] 

if you talk about my wiki I assume you refer to http://wiki.bitplan.com. There you'll find the issue e.g. in the property: http://wiki.bitplan.com/index.php/Property:Topic_iconUrl
with the definition.
[[Has type::URL]]

So for each Topic in the wiki the iconUrl is garbled which is the case on all my wikis in the farm for all topics.

**Comment by kghbln** [comment]
If you add `[has type::URL]]` to a property page you failed defining datatype "URL". In this case datatype "Page" is used. What I am basically saying is that the behaviour of SMW did not change. I verified on an MW 1.24 with SMW 2.4-alpha. Moreover the current behaviour is what I would expect from this datatype. I tried to indicate a workaround however so far you convened to ignore it or not reply to it.

**Comment by WolfgangFahl** [comment]
@kghbln I still do not get your point.
https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2017-11-14

sets another value for the property

https://www.semantic-mediawiki.org/wiki/Property:Has_url - this time for a page.
If the property would have the type Page the value User:WolfgangFahl/Workdocumentation 2017-11-14  would show in blue but it is in black. 

So what does _You are using datatype "Page" for your property. ;)_ refer to?

**Comment by mwjames** [comment]
Hi,

Please see my notes and I hope this clarifies the issue for once:

- If your create a type declaration (as shown in your screen dump)
with `[has type:...` then the annotation is invalid and the page type
is automatically assigned.
- The other provided example of `User:WolfgangF...` contains a `:`
with the URL parser identifying `User:` as schema protocol (loose
validation) as in `ftp:` [0]. Schemas are not validated, and the value
is being populated as-is and with `User:` not being valid protocol the
string is shown without any formatting (href etc.).
- Protocol relative URLs has not been and are not planned to be supported.

As to this point and for the provided examples, I fail to see the
validity for a regression claim and unless someone points me to a code
path where the claim can be sustained, I will no longer respond to
this issue.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/datavalues/SMW_DV_URI.php#L94

Cheers

**Comment by WolfgangFahl** [comment]
@mwjames Indeed there has been no regression on the part of SemanticMediaWiki: I am sorry to have it stated that way. The real issue was a regression on my side where the URL type that was known to be not working was spread out on my whole wikifarm. Some of these wikis had been fixed manually in the past (some 2 years ago) and I simply forgot about this. Sorry about all the fuzz.
