### ISSUE TITLE
Undesired interaction on special page "SemanticMediaWiki"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2836]
### Setup and configuration

- MediaWiki | 1.29.2 (3869ac0)08:59, 15 November 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (e48a508) 01:18, 15 November 2017
- Semantic Glossary | 2.2.0 (a1c4e74) 11:43, 4 November 2017

### Issue
I am not sure if this is an Semantic MediaWiki issue or a Semantic Glossary issue. However I am reporting it here since there is probably also something Semantic MediaWiki can do to prevent this from happening.

In case glossary term SMW is defined this terms kicks in on special page "Semantic MediaWiki" and breaks the display, i.e. instead of a hoverable tool tip the term definition is displayed directly. I think SG should not kick in on special pages at all.

### Steps to reproduce
[Access](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SemanticMediaWiki#tab-notices) the deprecation notices section on special page "SemanticMediaWiki". See  also the following screen shot:
![screenshot-2017-11-16 administrative functions - semantic mediawiki - sandbox](https://user-images.githubusercontent.com/1104078/32915232-79e823ee-cb18-11e7-9eb0-1765eb2c25af.png)

**Comment by kghbln** [comment]
@mwjames @s7eph4n FYI

**Comment by s7eph4n** [comment]
From [the docs](https://www.mediawiki.org/wiki/Extension:Semantic_Glossary#Customization):
> Semantic Glossary has inherited most of the settings available for the Lingo extension:
> ...
> * $wgexLingoUseNamespaces to specify what namespaces should or should not be used; Example: $wgexLingoUseNamespaces[NS_TALK] = false;

I don't have Admin rights on Sandbox, so cannot check quickly, but the tooltips often don't co-operate particularly well with other JS functionality that shows/hides elements of the page, e.g. HeaderTabs. Might be the same here.

**Comment by kghbln** [comment]
Thanks. I somehow overlooked this specific setting however adding the following setting did not help unless there is still some caching involved. Cleared the browser cache though.

```php
$wgexLingoUseNamespaces[NS_SPECIAL] = false;
```
So basically this is a SG and Lingo issue. Hmm, probably special pages should be disabled by default however I do not know how other users go about it.

**Comment by kghbln** [comment]
Cross referencing: Now at [Phabricator](https://phabricator.wikimedia.org/T180746).
