### ISSUE TITLE
`$wgNamespacesToBeSearchedDefault` disregarded for anonymous users

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2837]
### Setup and configuration

- MediaWiki | 1.29.2 (3869ac0)08:59, 15 November 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (e48a508) 01:18, 15 November 2017

### Issue
Even though I added the following setting after the inclusion of SMW
```php
$wgNamespacesToBeSearchedDefault = [
        NS_MAIN => true,
        ];
```
the standard search is still also enabled for namespaces "Concept" and "Property" for anonymous users. This setting is however respected for logged in users.

Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2439

Note: I have configured sandbox accordingly allowing to demonstrate the issue:

### Steps to reproduce
Use the "advanced" profile on special page "Search": [example](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Recherche&profile=advanced&search=&fulltext=1)

**Comment by mwjames** [comment]
We don't distinguish between logged and anonymous users and the only place we set the setting is in:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/88783002b5fdf11e6046bdbaa2888f747634372d/src/NamespaceManager.php#L242-L249

As of now, I don't know the cause and I can hardly see us at fault here therefore I have no immediate plans to endeavor the MW code [0] for this.

[0] https://github.com/wikimedia/mediawiki/search?utf8=%E2%9C%93&q=wgNamespacesToBeSearchedDefault&type=

**Comment by kghbln** [comment]
Thanks for the feedback. So I assume that this is an MediaWiki core issue. Thus reported on Phabricator as [T181061](https://phabricator.wikimedia.org/T181061)

**Comment by kghbln** [comment]
The solution was sitting in front of my face all the time. This works for logged in as well as anonymous users:
```php
$wgNamespacesToBeSearchedDefault = [
        NS_MAIN => true,
        SMW_NS_PROPERTY => false,
        SMW_NS_CONCEPT => false 
        ];
```
This only works for logged in users. Somewhat strange but there is a way out. See above. :)
```php
$wgNamespacesToBeSearchedDefault = [
        NS_MAIN => true,
        ];
```
