### ISSUE TITLE
how to test SM is working other than version page (apologies for simple question)

### ISSUE THREAD

**Issue by tansaku** [SemanticMediaWiki/SemanticMediaWiki#2838]
hi, I've got semantic wiki installed in our mediawiki, but I'm a little unclear about how to test it is really working, other than it appears in the versions page.

Is there some simple API that should now be enabled? some particular syntax that we can now use?

I have worked through the FAQ in the main website and searched around, but if anyone could provide some simple examples of the new functionality that is enabled and how it can quickly be manually tested I'd be very grateful

**Comment by kghbln** [comment]
A starting point is [Getting started](https://www.semantic-mediawiki.org/wiki/Help:Getting_started). Just follow the steps shown in the  [image collection](https://www.semantic-mediawiki.org/wiki/Help:Getting_started/Part_1_(Working_with_annotations)) of step 1.

**Comment by kghbln** [comment]
There is also an [introduction](https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2017/Introduction_to_Semantic_MediaWiki) but probably I should also create a more condensed version just showing an even simpler example than the one starting at page 29.

**Comment by tansaku** [comment]
thanks @kghbln  the image collection is really small in my browser and difficult to read.  I ran through your slides in the second link and gleaned that I could put into like:

```
This page is about the book called [[Has book title::The Picture of Dorian Gray]] written by [[Has book author::Oscar Wilde]]. It was last published by [[Has book publisher::Titan  Books]] in the [[Has book publishing country::UK]], [[Has book publishing year::2015]]. The ISBN is [[Has book ISBN::978­1783293650]]. My personal rating for this book is [[Has book rating::1]].

[[Category:Book]]
```

in a page, which I did: https://hlp-wiki-develop.agileventures.org/Test_Page

and then in the same or other pages I can do queries on that marked up data like so:

```
{{#ask:
 [[Category:Book]]
 [[Has book title::The Picture of Dorian Gray]]
}}
```

**Comment by tansaku** [comment]
given that that latter query is working in our wiki, I'm guessing we've installed correctly ...

so basically we can mark up any text with predicates and can then query that data and display it in other locations.

Is the search only by embedded script, or is there an API endpoint e.g. `/semantic_ask?category=book&title=The%20Picture%20of%20Dorian%20Gray` or similar?

**Comment by kghbln** [comment]
Thanks for posting back!

>  the image collection is really small in my browser and difficult to read. 

So I created https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2839

> given that that latter query is working in our wiki, I'm guessing we've installed correctly ...

Yes

>  or is there an API endpoint 

[Yes](https://www.semantic-mediawiki.org/wiki/Help:API)

**Comment by tansaku** [comment]
aha, so we can use things like:

```
/api.php?action=ask&query=[[Modification date::%2B]]|%3FModification date|sort%3DModification date|order%3Ddesc&format=jsonfm
```
great thanks! :-)

**Comment by mwjames** [comment]
... also when you edit a page you should see a note like:

![image](https://user-images.githubusercontent.com/1245473/33230130-233aa584-d221-11e7-8042-939902b3675f.png)

**Comment by mwjames** [comment]
> the image collection is really small in my browser and difficult to read. 

If you click the image then you get a slideshow and you can browse back and forth.

**Comment by kghbln** [comment]
[Added an info tooltip](https://www.semantic-mediawiki.org/w/index.php?title=Template%3ACollection&type=revision&diff=57821&oldid=57819)

**Comment by tansaku** [comment]
@mwjames ah thanks - we have the visual editor installed and so don't see that pop up in the editor I think ...

**Comment by djoris** [comment]
The easiest method I'd recommend is looking for a property that is always present: [Property:Modification_date](https://wiki.sha2017.org/w/Property:Modification_date). 
(or Special:Browse/Main_Page, but the name of the Main Page could be different depending on your localisation and settings).
