### ISSUE TITLE
Extend "Getting Started" by actual examples

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2839]
to provide a more direct help to work with SMW as asked with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2838.

**Comment by mwjames** [comment]
Just a quick note the query [0] went from ` [[Has image collection::getting started tutorial]]  [[Has keyword::editing]]  [[Has keyword::annotation]]` to `[[Has image collection::getting started tutorial]] [[Has keyword::editing||annotation]]` (AND vs OR).

[0] https://www.semantic-mediawiki.org/w/index.php?title=Help:Getting_started/Part_1_(Working_with_annotations)&diff=prev&oldid=57749

**Comment by kghbln** [comment]
Thanks for the note. At that day things had to move on fast so I accidentally changed page selection. Now at [`OR`](https://www.semantic-mediawiki.org/w/index.php?title=Template:Collection&diff=prev&oldid=57818)

**Comment by mwjames** [comment]
> Now at OR

It was a OR but should be an AND.

**Comment by kghbln** [comment]
> It was a OR but should be an AND.

[The same moment](https://www.semantic-mediawiki.org/w/index.php?title=Template:Collection&diff=prev&oldid=57819)

**Comment by kghbln** [comment]
Now a "To do" for the documentation project.
