### ISSUE TITLE
Enterprise environment and support

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2846]
I started to collect some links [0] that are mostly relevant for an enterprise environment and I'd like to ask users of the said target group the fill-in and extend the page with information that are mostly relevant for enterprise, wiki farm, and institutional users.

The objective is to create a portal page that collects information in a condensed and concise manner and should contain generalizable content independent of any professional support or package offer.

## Tasks

- [ ] SMWCon articles [1] are missing annotated keywords to select "enterprise" as selection criteria in a query

[0] https://www.semantic-mediawiki.org/wiki/Enterprise_environment
[1] https://www.semantic-mediawiki.org/w/index.php?search=Enterprise&title=Special%3ASearch&go=Go

**Comment by kghbln** [comment]
Now a "To do" for the documentation project.

In general this is a tracking issue, meaning this is endlessly ongoing.
