### ISSUE TITLE
Graph format through Special:Ask gives fatal error

### ISSUE THREAD

**Issue by djoris** [SemanticMediaWiki/SemanticMediaWiki#2848]
### Setup and configuration

Following is config of our server & the SMW sandbox (both showing the error)
- SMW version: 2.5.5 & 3.0.0-alpha (59bd015)
- MW version: 1.27.3 & 1.30.0-rc.0
- PHP version: 5.5.38 & 5.6.30-0
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 14.4 & MariaDB 10.0.33
- SRF: 2.5.4 & 3.0.0-alpha (da5e145)
- Graphviz: 2.1.0
### Issue
Creating any query that has at least one result, through Special:Ask with output format graph (graphviz) results in a 500 server error: 
```
Fatal error: Call to a member function getFulltext() on null in /../extensions/GraphViz/GraphViz_body.php on line 500
```
This issue only pertains queries through Special:Ask, not inline queries.

### Stack trace
n/a (fatal error)

### Steps to reproduce
Example data and working inline query in https://sandbox.semantic-mediawiki.org/wiki/Issue/Graphviz
1. Go to: Special:Ask
2. Create a condition that matches at least one page, such as: [[ArticleAuthor::+]]. Optionally choose a Printout selection.
3. Set Format to Graph. Optionally select or remove arguments for the format.
4. Choose Find results
The resulting page gives the fatal error: 
``` Fatal error: Call to a member function getFulltext() on null in /../w/extensions/GraphViz/GraphViz_body.php on line 500```
This can be replicated with several conditions, several properties (or none), and on multiple wikis.

**Comment by kghbln** [comment]
Thanks a lot for reporting. I think this is a GraphViz error. I actually reported the very same error at [T180376](https://phabricator.wikimedia.org/T180376) two weeks ago.

Moreover the error log gives me:
```
[Wed Nov 29 16:10:30.283412 2017] [:error] [pid 6374] [client 145.131.226.106:52869] PHP Fatal error:  Class 'OOUI\\WikimediaUITheme' not found in /../w/includes/OutputPage.php on line 3986, referer: https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/Graphviz&action=submit
```
So this may also be some broken interaction with MediaWiki core.

**Comment by kghbln** [comment]
> Moreover the error log gives me:

Sometimes... Of course there was an "issue": At the same time I upgraded from 1.29.2 to 1.30.0-rc.0 which took a minute or so. So having this is kinda expected during the upgrade. There is no related core issue.

**Comment by mwjames** [comment]
A quick note.

This relates to SRF not SMW (Graph is part of SRF not SMW).

> ```Fatal error: Call to a member function getFulltext() on null in
> /var/www/htdocs/mw/02100/w/extensions/GraphViz/GraphViz_body.php on line
> 500```

If `GraphViz_body.php` crashes for some reason then it should be no
surprise that `Special:Ask` can't handle the situation and it is not
an indicator that something is wrong with `Special:Ask`.

Someone should fix the issue of `getFulltext() on null` in `GraphViz_body.php`.

Cheers

**Comment by kghbln** [comment]
> A quick note.

Thanks for the info. So back to [T180376](https://phabricator.wikimedia.org/T180376)
