### ISSUE TITLE
Problem with '<' comparison in 'ask'

### ISSUE THREAD

**Issue by fustbariclation** [SemanticMediaWiki/SemanticMediaWiki#285]
I believe that '<' is equivalent to '<=' in an 'ask' query, and exactly less than (and not equal to) should be '<<'

I've checked and I've not got
$smwStrictComparators = true

However, it does look as though I've got a bug. I've set a test meeting as:

== Testing Meeting Setting ==
[[category:meeting]]
[[has date::{{#time: d F Y | 23 April 2014  }}]]
[[Time::Never]]
[[Venue::Nowhere]]

This ask doesn't see it (for anybody reading this later, today is the
23rd of April):

{{#ask: [[category:meeting]] [[has date::>{{#time: d F Y | now  }}]]
|?has_date=Date
|?Time
|?Venue
}}

However, this ask does:

{{#ask: [[category:meeting]] [[has date::>{{#time: d F Y | 22 April 2014  }}]]
|?has_date=Date
|?Time
|?Venue
}}

My versions are:

Installed software

ProductVersion
MediaWiki1.22.2
PHP5.3.28 (cgi-fcgi)
MySQL5.5.34-cll-lve

Installed extensions

Semantic extensions
Semantic Bundle(Version 1.8.0.5.3)A pre-packaged bundle of Semantic
MediaWiki related extensionsYaron Koren,Jeroen De Dauw and others
Semantic Compound Queries(Version 0.3.4)A parser function that
displays multiple semantic queries at the same timeYaron Koren
Semantic Drilldown (Version 1.3)A drilldown interface for navigating
through semantic dataYaron Koren and David Loomer
Semantic Forms (Version 2.6.1)Forms for adding and editing semantic
dataYaron Koren, Stephan Gambke and others
Semantic Forms Inputs(Version 0.7)Additional input types for Semantic
FormsStephan Gambke and others
Semantic Image Input(Version 0.2 alpha)Adds an image input that pulls
images from Wikipedia to Semantic FormsJeroen De Dauw
Semantic Internal Objects(Version 0.7.6)Setting of internal objects in
Semantic MediaWikiYaron Koren
Semantic Maps (Version 2.0.1.2)Provides the ability to view and edit
coordinate data stored with the Semantic MediaWiki extension (more
info...)Jeroen De Dauw
Semantic MediaWiki (Version 1.8.0.5)Making your wiki more accessible -
for machines and humans (online documentation)Markus Krötzsch, Denny
Vrandecic, Jeroen De Dauw and others
Semantic Result Formats (Version 1.8)Additional formats for Semantic
MediaWiki inline queriesJames Hong Kong, Stephan Gambke, Jeroen De
Dauw, Yaron Koren and others
SemanticTasks (Version 1.4.1)Email notifications for assigned or
updated tasksSteren Giannini and Ryan Lane

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/ByJsonScript/Fixtures/q-1002%20%5B%23285%5D%20date%20range%20for%20non%20strict%20comparators.json

and 

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/ByJsonScript/Fixtures/q-1003%20%5B%23285%5D%20date%20range%20for%20strict%20comparators.json

shows the expected behaviour in strict / non strict mode.

@kghbln FYI
