### ISSUE TITLE
Bad value for "rel" attribute in link tag

### ISSUE THREAD

**Issue by Henryfunk** [SemanticMediaWiki/SemanticMediaWiki#2852]
### Setup and configuration

- SMW version: 2.5.4
- MW version: 1.29.1
- PHP version: 7.0.22
- DB system: MySQL 5.7.20-0ubuntu0.16.04.1

### Issue
SMW causes a link tag with a bad value for the "rel" attribute to be added to HEAD:

`<link rel="ExportRDF" type="application/rdf+xml" title="Main Page" href="/wiki/index.php?title=Special:ExportRDF/Main_Page&amp;xmlmime=rdf"/>`

### Steps to reproduce
Navigate to: [Nu Html Checker](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.irhb.org)
The page concerned is at [www.irhb.org](https://www.irhb.org).

I know that the latest version of SMW is now 2.5.5, but the release notes do not say this issue has been fixed.

As always, thanks for all your efforts.

**Comment by kghbln** [comment]
Thank you for reporting the issue. So what would the [expected value](https://www.w3schools.com/tags/tag_link.asp) be? Probably "[alternate](https://www.w3.org/TR/html5/links.html#rel-alternate)" in all cases though I am not absolutely sure.

**Comment by Henryfunk** [comment]
I am afraid I can't answer your question. Does there have to be a rel attribute in this case? This document claims to be "the official rel registry": [Microformats: Existing rel Values](http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions). Is it of any use?

**Comment by kghbln** [comment]
> I am afraid I can't answer your question.

No worries. This question was directed to all parties interested in this bug. Thanks for the additional link.

**Comment by mwjames** [comment]
> `<link rel="ExportRDF" type="application/rdf+xml" title="Main Page"
> href="/wiki/index.php?title=Special:ExportRDF/Main_Page&amp;xmlmime=rdf"/>`

See [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/BeforePageDisplay.php#L81

**Comment by kghbln** [comment]
Back ported with 2db4d30a8c51dd988df1c8bc5c71a8f70e056949 to be shipped with 2.5.6
