### ISSUE TITLE
Revision::getText() now removed from Mediawiki, breaks ContentParser.php

### ISSUE THREAD

**Issue by Mewtwo-Ex** [SemanticMediaWiki/SemanticMediaWiki#2879]
### Setup and configuration

- SMW version: 2.4.6
- MW version: 1.29.2
- PHP version: 5.6.30-0+deb8u1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.5.58-0+deb8u1

### Issue
Execution of the maintenance/runJobs.php script of Mediawiki stops due to an exception in SMW tasks.

### Stack trace
PHP Fatal error:  Call to undefined method Revision::getText() in [hidden]/extensions/SemanticMediaWiki/includes/ContentParser.php on line 196

### Steps to reproduce
In command line, after a page using SMW has been edited, run: php maintenance/runJobs.php

### Possible fix
in: SemanticMediaWiki/includes/ContentParser.php
at the top of the file, add:
**use ContentHandler;**

on line 196, replace:
$this->getRevision()->getText()
by:
**ContentHandler::getContentText( $this->getRevision()->getContent() )**

**Comment by mwjames** [comment]
> SMW version: 2.4.6

2.4.x is no longer supported and as per [0] is only tested against 1.19 - 1.27 to work therefore you are advised to update.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by Mewtwo-Ex** [comment]
From what I see in the master branch and the 2.5.x branch, the getText is stil called, so the issue might still be here

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/includes/ContentParser.php
(fetchFromParser, l.191)

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/ContentParser.php
(fetchFromParser, l.191)

**Comment by mwjames** [comment]
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/includes/ContentParser.php

The mere existence of a function doesn't prove that a class fails, it
is the condition of its usage that directs the outcome.

We have tests in place that verify the behavior therefore we know that
is working with 1.29 which is the reason why the compatibility matrix
defines a lower and upper bound for supported versions.

**Comment by kghbln** [comment]
I believe upgrading to SMW 2.5.x should solve the issue. If not please report back and reopen the issue.
