### ISSUE TITLE
Provide links to uses of wanted properties

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMediaWiki#290]
Special:WantedProperties shows undefined properties and also displays "(_n_ uses)" to indicate the frequency of use. Sometimes these are actually template errors or bad data. It would be very helpful if the "_n_ uses" text were a hyperlink that would display the pages or Semantic MediaWiki objects that were using these undefined properties.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
