### ISSUE TITLE
[Tracking ticket] MW 1.31 and multi-content revisions (MCR)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2905]
Tracking ticket to monitor issues in regards the introduction of mulit-content revisions [0] (a.k.a. MCR) that started with MW 1.31.

[0] https://phabricator.wikimedia.org/tag/multi-content-revisions/

**Comment by mwjames** [comment]
@addshore I know your are busy preparing to switch to the MCR interface and in case you are looking for a wider representation of integration tests (as in creating actual content, and test against a DB master/replica), you are invited to run ` composer mediawiki/semantic-media-wiki:@dev` (and a simple `composer phpunit` from the extension base directory) as litmus test against your changes to see whether a non WMF extension passes as well.

There are about 2000 integration tests (total ~6000) expected to pass on mysql, sqlite, and postgres (unfortunately, I just uncovered #2903) as they would on Travis [0].

@cicalese FYI

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki

**Comment by addshore** [comment]
@mwjames thanks!

I'll try to remember to look at them / run them on the odd occasion.
With just a couple of basic end to end tests some of the MCR bugs could have been spotted, for example, create a page, edit it, delete it, restore it.

I'll see what I can whip up in core too

**Comment by cicalese** [comment]
@mwjames We would greatly appreciate if you could review MCR database schema at https://www.mediawiki.org/wiki/Multi-Content_Revisions/Database_Schema with respect to any potential impacts on Semantic MediaWiki. Also, if you have any input that could ensure that MCR and Semantic MediaWiki can harmoniously coexist or that would allow Semantic MediaWiki to benefit from any of the enhancements provided by MCR, that would be extremely helpful. In addition to the Phabricator tag you link above, you can find a dashboard which gives a view into the MCR tasks and related gerrit changes at [0].

[0] https://wikifarm.wmflabs.org/mcr

**Comment by mwjames** [comment]
@addshore Several integration tests fail with 1.31.0-alpha, e984121 on __PostgreSQL__ 9.3.12 because of a missing revision.

Those integration tests import data via the WikiImporter and when looking at the debug output, it reports:

```
WikiImporter::finishImportPage: Skipping article count adjustment for Category:Regression test because WikiPage::getContent() returned null
[CryptRand] 0 bytes of randomness leftover in the buffer.
[session] SessionBackend "rinm2111pi12vap81h8pdvaop6pd38j7" is unsaved, marking dirty in constructor
[session] SessionBackend "rinm2111pi12vap81h8pdvaop6pd38j7" save: dataDirty=1 metaDirty=1 forcePersist=0
[GlobalTitleFail] RequestContext::getTitle called by ImportReporter->reportPage/ContextSource->msg/RequestContext->msg/Message->setContext/RequestContext->getTitle with no title set.
IMPORT: Enter page handler.
IMPORT: Unhandled page XML tag sha1
IMPORT: Enter revision handler
[OldRevisionImporter] ImportableOldRevisionImporter::import: got invalid $pageId when importing revision of [[Category:Regression test category]], timestamp 20140131073813

WikiImporter::finishImportPage: Skipping article count adjustment for Category:Regression test category because WikiPage::getContent() returned null
[GlobalTitleFail] RequestContext::getTitle called by ImportReporter->reportPage/ContextSource->msg/RequestContext->msg/Message->setContext/RequestContext->getTitle with no title set.
IMPORT: Enter page handler.
IMPORT: Unhandled page XML tag sha1
IMPORT: Enter revision handler
[OldRevisionImporter] ImportableOldRevisionImporter::import: got invalid $pageId when importing revision of [[Category:Regression test sub category]], timestamp 20140131073741

WikiImporter::finishImportPage: Skipping article count adjustment for Category:Regression test sub category because WikiPage::getContent() returned null
[GlobalTitleFail] RequestContext::getTitle called by ImportReporter->reportPage/ContextSource->msg/RequestContext->msg/Message->setContext/RequestContext->getTitle with no title set.
IMPORT: Enter page handler.
IMPORT: Unhandled page XML tag sha1
IMPORT: Enter revision handler
[OldRevisionImporter] ImportableOldRevisionImporter::import: got invalid $pageId when importing revision of [[Category:Regression test sub sub category]], timestamp 20140131073045

WikiImporter::finishImportPage: Skipping article count adjustment for Category:Regression test sub sub category because WikiPage::getContent() returned null
[GlobalTitleFail] RequestContext::getTitle called by ImportReporter->reportPage/ContextSource->msg/RequestContext->msg/Message->setContext/RequestContext->getTitle with no title set.
IMPORT: Enter page handler.
IMPORT: Unhandled page XML tag sha1
IMPORT: Enter revision handler
[OldRevisionImporter] ImportableOldRevisionImporter::import: got invalid $pageId when importing revision of [[CategoryInstanceAndCategoryHierarchyRegressionTest/WithSubpage]], timestamp 20140131073212

WikiImporter::finishImportPage: Skipping article count adjustment for CategoryInstanceAndCategoryHierarchyRegressionTest/WithSubpage because WikiPage::getContent() returned null
[GlobalTitleFail] RequestContext::getTitle called by ImportReporter->reportPage/ContextSource->msg/RequestContext->msg/Message->setContext/RequestContext->getTitle with no title set.
IMPORT: Enter page handler.
IMPORT: Unhandled page XML tag sha1
IMPORT: Enter revision handler
[OldRevisionImporter] ImportableOldRevisionImporter::import: got invalid $pageId when importing revision of [[CategoryInstanceAndCategoryHierarchyRegressionTest/WithSubpage/WithSubSubpage]], timestamp 20140131073224

WikiImporter::finishImportPage: Skipping article count adjustment for CategoryInstanceAndCategoryHierarchyRegressionTest/WithSubpage/WithSubSubpage because WikiPage::getContent() returned null
[GlobalTitleFail] RequestContext::getTitle called by ImportReporter->reportPage/ContextSource->msg/RequestContext->msg/Message->setContext/RequestContext->getTitle with no title set.
IMPORT: Enter page handler.
IMPORT: Unhandled page XML tag sha1
IMPORT: Enter revision handler
[OldRevisionImporter] ImportableOldRevisionImporter::import: got invalid $pageId when importing revision of [[CategoryInstanceAndCategoryHierarchyRegressionTest]], timestamp 20140131073955
```

Given that ImportableOldRevisionImporter has only be introduced last month and with the import file [0] (and related tests) being untouched for the last 4 years it is conceivable that the issue was only recently introduced (== with 1.31).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/MediaWiki/Import/Fixtures/CategoryInstanceAndCategoryHierarchyTest-Mw-1-19-7.xml

**Comment by mwjames** [comment]
> @mwjames We would greatly appreciate if you could review MCR database schema at https://www.mediawiki.org/wiki/Multi-Content_Revisions/Database_Schema with respect to any potential impacts on Semantic MediaWiki. Also, if you have any input that could ensure that MCR and Semantic MediaWiki can harmoniously coexist

I will try my best by the time I no longer see any failures with 1.31 (meaning I don't have to monitor issue tagged with mediawiki during my weekend sprint) and actually make some progress towards a SMW 3.0 release.

**Comment by mwjames** [comment]
Same comments as per https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3345#issuecomment-478242311.
