### ISSUE TITLE
Printernames are being transformed into lower case letters

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2914]
### Setup and configuration

- MediaWiki | 1.30.0 (830bb58)22:58, 8. Dez. 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (09be77b) 12:14, 28. Dez. 2017

### Issue
System message "smw-ask-format-help-link" introduced with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2907 contains a placeholder $1 which is being replaced by the name of the selected result format e.g. "smw_printername_csv" as well as an link to the respective help page on s-mw.o. This system message is being transformed into lower case letters which is wrong. The casing as set with the respective result printer names, e.g. "smw_printername_csv" should be retained.

Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2907/commits/c3b620b07bb3295ee215631e12b2ab0a367eb663#diff-0711f88218e06fd4a1d5bafa0e217204R157

**Comment by kghbln** [comment]
@mwjames Probably just a matter of removing `.toLowerCase()` from https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/c3b620b07bb3295ee215631e12b2ab0a367eb663#diff-0711f88218e06fd4a1d5bafa0e217204L180

**Comment by mwjames** [comment]
> This system message is being transformed into lower case letters which is wrong. The casing as set with the respective result printer names, e.g. "smw_printername_csv" should be retained.

I don't understand the issue.

The lowercase was added to the label to make sure that the in-sentence placeholder shows with a lowercase instead of "Help with the Tagcloud format". Other messages like "smw_printername_csv" haven't been been touched where "smw-ask-format-help-link" contains a generated `href` element.

![image](https://user-images.githubusercontent.com/1245473/34440614-934c7238-ecf9-11e7-9119-2a6ef36248c0.png)

**Comment by kghbln** [comment]
I saw this usage and that's exactly why I opened the issue. In e.g. German the format names are treated as nouns so having this in lowercase is wrong. I does not matter if it is an enumeration or a sentence containing the format name.

The only other spot I can think of where the printer names are used is the drop-down menu on special page "Ask" allowing to select the printer. I guess it is acceptable for English to have this in lowercase here in contrast to uppercase which is what we have right now. I am not native English however. So a way out may be to change the printer names to lowercase instead of having them with an uppercase first letter. Thus a translator can decide if the first letter needs to be uppercase or lowercase.

**Comment by mwjames** [comment]
I removed the lower case conversion [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/2dd546e7a3ff0e7c1bc9e6400f5299740a0ac4db

**Comment by kghbln** [comment]
> I removed the lower case conversion [0].

That's the solution to fix the issue with German. However you added lowercase for reason. Probably rephrasing the message can help, e.g. with "Get help with the selected format: $1"

**Comment by mwjames** [comment]
> can help, e.g. with "Get help with the selected format: $1"

Yeah, something like that or "$1 help page", I'll leave this up to you on what fits best.
