### ISSUE TITLE
remove /extensions/ assumption

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#294]
While working on mediawiki/vagrant/composer/SMW, I found the hard-coded assumption that SMW was installed under /extensions/ caused problems.  Setup::registerFooterIcon() should be changed as follows:

```
    protected function registerFooterIcon() {
        $this->globals['wgFooterIcons']['poweredby']['semanticmediawiki'] = array(
            'src' => $this->globals['wgScriptPath']
                . end( ( explode( $this->globals['IP'],
                                              str_replace( DIRECTORY_SEPARATOR, '/',
                                                           __DIR__), 2 ) ) )
                . '/../resources/images/smw_button.png',
            'url' => 'https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki',
            'alt' => 'Powered by Semantic MediaWiki',
        );
    }
```

**Comment by mwjames** [comment]
> protected function registerFooterIcon() {

This issue mainly deals with disabling the footer icon and #233 describes a method on how to deal with that.

>  I agree, though, that SMW shouldn't have to worry about where it is installed. I'm open to better fixes.

There is no actionable task for us to work on or provide assistance, hence closing this.
