### ISSUE TITLE
Allow logging to a file for the "removeDuplicateEntities.php" maintenance script

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2946]
### Setup and configuration

- MediaWiki | 1.30.0 (d0c8f49)19:49, 5. Jan. 2018
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (388e383) 07:44, 7. Jan. 2018

### Issue
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2932 brought the new "removeDuplicateEntities.php" maintenance script.

Since the script may emit a quite large [(log)](https://gist.github.com/kghbln/e1e0ecde16f23c1ece099be1afa5d889) it will perhaps be an idea allow logging to a file similarly to what "rebuildData.php" does, i.e. getting a `--with-maintenance-log-file="/path/to/smw/logs/directory/"`file. Moreover a ` --with-maintenance-log` to allow showing the log on wiki will be nice, too.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
