### ISSUE TITLE
`#smwdoc` should show a default message in case of lacking parameters

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2950]
### Setup and configuration
- MediaWiki | 1.30.0 (d0c8f49)19:49, 5. Jan. 2018
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (388e383) 07:44, 7. Jan. 2018

### Issue
The `#smwdoc` parser function should show a default message in case the respective result format does not provide specific parameters instead of staying silent.

### Example
[smwdoc - bibtex](https://sandbox.semantic-mediawiki.org/wiki/Smwdoc_-_bibtex)

**Comment by mwjames** [comment]
> `#smwdoc` should show a default message in case the respective result format
> does not provide specific parameters instead of staying silent.

What about the following change?

```
@@ -55,11 +55,15 @@ class DocumentationParserFunction implements HookHandler {
 			}
 		}

 		$docBuilder = new ParameterListDocBuilder( $this->newMessageFunction() );

-		return $docBuilder->getParameterTable( $params );
+		if ( ( $output = $docBuilder->getParameterTable( $params ) ) === '' ) {
+			$output = wfMessage( 'smw-smwdoc-default-no-parameter-list',
$parameters['format']->getValue() )->inLanguage( $this->language
)-text();
+		}
+
+		return $output;
```

PS: It goes without saying that you need to create the message key!

**Comment by JeroenDeDauw** [comment]
They seems like a reasonable approach. Might be better to do this but whatever:

return thereAreParams() ? getParameterTable() : getNoParamsMessage();

**Comment by kghbln** [comment]
I was not able to decipher the comment from Jeroen so I ... Field test passed.
