### ISSUE TITLE
Feature request: Natural Sorting of query results 

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticMediaWiki#2951]
### Setup and configuration

- SMW version:Any/All/Current
- MW version:Any/All/Current
- PHP version:Any/All/Current
- DB system (MySQL, Blazegraph, etc.) and version: Any/All

### Feature Request ###
Hi,

> I have users entering in reference IDs as a decimal structure (WBS) as 
> follows as values to a Semantic Property of type Text:

Under the assumption (due to missing context) that an entity contains annotations like [[Has text::1.4.4.8.3.1]] ... [[Has text::1.4.4.8.3.12]] and your query looks similar to:

```
{{#ask: [[SomeProperty:WithSomeCondition]]
 |?Has text
}}
```

It produces the mentioned order using the codified procedure in [0] for how to sort "column" values to an entity. As seen in [0] it uses `SORT_LOCALE_STRING` as flag for anything that is not numeric therefore the order is as you have described it.

```
{{#ask: [[SomeProperty:WithSomeCondition]]
 |?Has text|+order=asc
}}
```

You can modify the order using [1], yet of course it will not alter the sorting behaviour in terms of the codified `SORT_LOCALE_STRING` flag.

> Is there a way (data type or otherwise) that I can sort this as 
> desired? (Attempting to pre-define it is not practical.)

I'm presume you are looking for a natural sorting (`SORT_NATURAL`) [2] with 1.4.4.8.3.1 ... 1.4.4.8.3.12. At a glance, four lines of code should be able to extend the sort behaviour (without altering the current behavior) and if you create a ticket, I'll try to comment on it.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/src/SQLStore/RequestOptionsProcessor.php#L240-L245
[1] https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/Printout_sorting_order
[2] http://php.net/manual/en/function.sort.php

Cheers

On 1/10/18, Evans, Richard K. (GRC-H000) <richard.k.evans@nasa.gov> wrote:
> I have users entering in reference IDs as a decimal structure (WBS) as 
> follows as values to a Semantic Property of type Text:
>
> 1.4.4.8.3.1
> 1.4.4.8.3.2
> 1.4.4.8.3.3
> 1.4.4.8.3.4
> 1.4.4.8.3.5
> 1.4.4.8.3.6
> 1.4.4.8.3.7
> 1.4.4.8.3.8
> 1.4.4.8.3.9
> 1.4.4.8.3.10
> 1.4.4.8.3.11
> 1.4.4.8.3.12
>
> However, queries return that data sorted like this:
>
> 1.4.4.8.3.1
> 1.4.4.8.3.10
> 1.4.4.8.3.11
> 1.4.4.8.3.12
> 1.4.4.8.3.2
> 1.4.4.8.3.3
> 1.4.4.8.3.4
> 1.4.4.8.3.5
> 1.4.4.8.3.6
> 1.4.4.8.3.7
> 1.4.4.8.3.8
> 1.4.4.8.3.9
>
> Is there a way (data type or otherwise) that I can sort this as desired?
> (Attempting to pre-define it is not practical.)
>
> -Rich (revansx)
>
>
> ----------------------------------------------------------------------
> -------- Check out the vibrant tech community on one of the world's 
> most engaging tech sites, Slashdot.org! http://sdm.link/slashdot 
> _______________________________________________
> Semediawiki-user mailing list
> Semediawiki-user@lists.sourceforge.net
> https://lists.sourceforge.net/lists/listinfo/semediawiki-user
>

**Comment by mwjames** [comment]
As for "Feature request: Natural Sorting of query results", we have to
distinguish two completely different use cases.

## Clarification

The first being related to an entity, its collation, and how the
`QueryEngine` uses the sorting information to return results that
match the condition and sorting requirements. SMW 3.0+ brings the
`smwgEntityCollation`setting (#2429) which makes it necessary to
rebuild the data since a DB column requires to be updated in order for
the SQL engine to make use of the content of this field.

The second use case which the email thread is referring to is about
sorting values within a printout (column) and the support of
`SORT_NATURAL` instead of the default `SORT_LOCALE_STRING`. I propose
to add `n-asc` and `n-desc` as printout order modifier leaving
existing representation and behaviour untouched.

## Expected behaviour

To command a natural sorting of printout values you would do something like:

```
{{#ask: [[SomeProperty::WithSomeCondition]]
 |?Has text|+order=n-asc
}}
```
It should produce the following output for the mentioned example.

```
1.4.4.8.3.1
1.4.4.8.3.2
1.4.4.8.3.3
1.4.4.8.3.4
1.4.4.8.3.5
1.4.4.8.3.6
1.4.4.8.3.7
1.4.4.8.3.8
1.4.4.8.3.9
1.4.4.8.3.10
1.4.4.8.3.11
1.4.4.8.3.12
``

## Required changes

The changes to support above extension would be minimal and something
similar to:

```
@@ -170,6 +170,12 @@ class ResultFieldMatchFinder {
 				$options->limit = trim( $limit );
 			}

+			// Expecting a natural sort behaviour (n-asc, n-desc)?
+			if ( strpos( $order, 'n-' ) !== false ) {
+				$order = str_replace( 'n-', '', $order );
+				$options->natural = true;
+			}
```

```
@@ -249,6 +249,11 @@ class RequestOptionsProc {

 		$flag = $isNumeric ? SORT_NUMERIC : SORT_LOCALE_STRING;

+		// SORT_NATURAL is selected on n-asc, n-desc
+		if ( isset( $requestOptions->natural ) ) {
+			$flag = SORT_NATURAL;
+		}
```

PS: It goes without saying, this requires additional integration tests!

Cheers

On 1/11/18, revansx <notifications@github.com> wrote:
> ### Setup and configuration
>
> - SMW version:Any/All/Current
> - MW version:Any/All/Current
> - PHP version:Any/All/Current
> - DB system (MySQL, Blazegraph, etc.) and version: Any/All
>
> ### Feature Request ###
> Hi,
>
>> I have users entering in reference IDs as a decimal structure (WBS) as
>> follows as values to a Semantic Property of type Text:
>
> Under the assumption (due to missing context) that an entity contains
> annotations like [[Has text::1.4.4.8.3.1]] ... [[Has text::1.4.4.8.3.12]]
> and your query looks similar to:
>
> ```
> {{#ask: [[SomeProperty:WithSomeCondition]]
>  |?Has text
> }}
> ```
>
> It produces the mentioned order using the codified procedure in [0] for how
> to sort "column" values to an entity. As seen in [0] it uses
> `SORT_LOCALE_STRING` as flag for anything that is not numeric therefore the
> order is as you have described it.
>
>
> ```
> {{#ask: [[SomeProperty:WithSomeCondition]]
>  |?Has text|+order=asc
> }}
> ```
>
> You can modify the order using [1], yet of course it will not alter the
> sorting behaviour in terms of the codified `SORT_LOCALE_STRING` flag.
>
>> Is there a way (data type or otherwise) that I can sort this as
>> desired? (Attempting to pre-define it is not practical.)
>
> I'm presume you are looking for a natural sorting (`SORT_NATURAL`) [2] with
> 1.4.4.8.3.1 ... 1.4.4.8.3.12. At a glance, four lines of code should be able
> to extend the sort behaviour (without altering the current behavior) and if
> you create a ticket, I'll try to comment on it.
>
> [0]
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/src/SQLStore/RequestOptionsProcessor.php#L240-L245
> [1]
> https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/Printout_sorting_order
> [2] http://php.net/manual/en/function.sort.php
>
> Cheers
>
> On 1/10/18, Evans, Richard K. (GRC-H000) <richard.k.evans@nasa.gov> wrote:
>> I have users entering in reference IDs as a decimal structure (WBS) as
>> follows as values to a Semantic Property of type Text:
>>
>> 1.4.4.8.3.1
>> 1.4.4.8.3.2
>> 1.4.4.8.3.3
>> 1.4.4.8.3.4
>> 1.4.4.8.3.5
>> 1.4.4.8.3.6
>> 1.4.4.8.3.7
>> 1.4.4.8.3.8
>> 1.4.4.8.3.9
>> 1.4.4.8.3.10
>> 1.4.4.8.3.11
>> 1.4.4.8.3.12
>>
>> However, queries return that data sorted like this:
>>
>> 1.4.4.8.3.1
>> 1.4.4.8.3.10
>> 1.4.4.8.3.11
>> 1.4.4.8.3.12
>> 1.4.4.8.3.2
>> 1.4.4.8.3.3
>> 1.4.4.8.3.4
>> 1.4.4.8.3.5
>> 1.4.4.8.3.6
>> 1.4.4.8.3.7
>> 1.4.4.8.3.8
>> 1.4.4.8.3.9
>>
>> Is there a way (data type or otherwise) that I can sort this as desired?
>> (Attempting to pre-define it is not practical.)
>>
>> -Rich (revansx)
>>
>>
>> ----------------------------------------------------------------------
>> -------- Check out the vibrant tech community on one of the world's
>> most engaging tech sites, Slashdot.org! http://sdm.link/slashdot
>> _______________________________________________
>> Semediawiki-user mailing list
>> Semediawiki-user@lists.sourceforge.net
>> https://lists.sourceforge.net/lists/listinfo/semediawiki-user
>>
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2951

**Comment by revansx** [comment]
Thanks! .. Which files and where inside them would I add these two changes in my existing installation if I was eager to help test (and use) this enhancement?

**Comment by revansx** [comment]
presumably:
./src/Query/Result/ResultFieldMatchFinder.php and
./src/SQLStore/RequestOptionsProcessor.php

ah! .. and the locations are indicated by:
$options->limit = trim( $limit ); and
$flag = $isNumeric ? SORT_NUMERIC : SORT_LOCALE_STRING;
respectively! ... stand-by...

**Comment by revansx** [comment]
hmm.. i made both changes and it didn't crash anything.. but it didn't work either.. my first thought is that I may be using php caching that is not accessing the updated src code, If I am, is there any obvious way to force it to refresh?

**Comment by mwjames** [comment]
> hmm.. i made both changes and it didn't crash anything.. but it didn't work
> either.. my first thought is that I may be using php caching that is not
> accessing the updated src code, If I am, is there any obvious way to force
> it to refresh?

No need, PHP files are under normal circumstances not cached. The
easiest way for you to verify that your changes did actually made it
to the user end is by adding extra lines after:

+ $options->natural = true;
+ var_dump( 'NATURAL SELECTED' );

and

+ $flag = SORT_NATURAL;
+ var_dump( $flag )

In case you made to correct changes and you use `n-asc` (or n-desc`)
in combination with the `+|order=` modifier, your screen should output
something like `string(16) "NATURAL SELECTED" int(6)` and if it
doesn't, it means something is missing at your end.

PS: `var_dump` is only used as immediate debugging tool and should be
removed after one has finished working with the code.

**Comment by mwjames** [comment]
> but it didn't work either

It works as outlined and the added integration tests in #2953 (which use your example) pass on the expected order.

**Comment by kghbln** [comment]
This is great! Now [documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AAsk_syntax%2FPrintout_sorting_order&type=revision&diff=58260&oldid=58257) on wiki.
