### ISSUE TITLE
Provide misssing system message "smw-change-propagation-protection"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2954]
### Setup and configuration

- MediaWiki | 1.30.0 (d0c8f49)19:49, 5. Jan. 2018
- PHP | 5.6.33-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (bf356cd) 11:43, 14. Jan. 2018

### Issue
Today I came across system message ["smw-change-propagation-protection"](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=smw-change-propagation-protection&type=) on sandbox. It is not defined and I believe it was superseded by ["smw-property-req-violation-change-propagation-locked" and "smw-property-req-violation-change-propagation-pending"](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2495/files#diff-8aed887c744b7eb6f40c0a268ae06e7b). Thus the existing occurrences of "smw-change-propagation-protection" need to be replaced by the set of new system messages.

**Edit:** Issue description is incorrect due to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2954#issuecomment-360988242

**Comment by kghbln** [comment]
@mwjames Is the issue description correct. I assume so but there is still a chance that it is just missing.

**Comment by mwjames** [comment]
>@mwjames Is the issue description correct.

"smw-change-propagation-protection" shows up in [0] (when the protection is violated) while the other messages are displayed pending the status on the property page.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=smw-change-propagation-protection&type=

**Comment by kghbln** [comment]
Ah, ok so the issue description is not correct. It is just a missing system message. I could have sworn it was in there before at some point.
