### ISSUE TITLE
Impossible to link properly to subpage

### ISSUE THREAD

**Issue by Extarys** [SemanticMediaWiki/SemanticMediaWiki#2955]
### Setup and configuration

- SMW version:  2.5.5
- MW version: 1.31.0-alpha
- PHP version:  7.0.27-0+deb9u1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.2.12-MariaDB-10.2.12+maria~stretch-log

### Issue
It is impossible to link to a subpage properly when adding a property which values equals to the name of the page.

### Steps to reproduce
Create a subpage GameTitle/Maps/Nameofthemap
Add: `[[Map Name::Nameofthemap]]`
Save.
The link refer to Nameofthemap and not GameTitle/Maps/Nameofthemap.

Maybe I didn't find the porper way of doing this though.

**Comment by kghbln** [comment]
Thanks for filing an issue.

Here Semantic MediaWiki behaves exactly as MediaWiki itself does. If you would like to change the title of the link you will have to add it, e.g. `[[Map Page::GameTitle/Maps/Nameofthemap|Nameofthemap]]`. Note the difference between the name of a map and a location.

In your case you could also work with `DISPLAYTITLE`, i.e. you add one to the page containing the map [see here](https://sandbox.semantic-mediawiki.org/wiki/GameTitle/Maps/Nameofthemap) and you would get [this](https://sandbox.semantic-mediawiki.org/wiki/GameTitle) for `[[Map Page::GameTitle/Maps/Nameofthemap]]`. Note that a configuration change is required to do this: [docu1](https://www.semantic-mediawiki.org/wiki/Help:Display_title)/[docu2](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Display_title_of).

**Comment by mwjames** [comment]
> Add: [[Map Name::Nameofthemap]]

Doing `[[Map Name::Nameofthemap]]` does exactly what it should namely to created an annotation with `Nameofthemap` as value.

If you want to use `GameTitle/Maps/Nameofthemap` then you have to create an annotation with  `[[Map Name::GameTitle/Maps/Nameofthemap]]`. There is no magic hand that would create those annotations unless `GameTitle/Maps/Nameofthemap` is redirected to `Nameofthemap`.

**Comment by Extarys** [comment]
Wow thanks @kghbln for this. I'm new to mediawiki (5 days) so I might look stupid.

On GameTitle/Maps/Nameofthemap
```
[[Map Name::Nameofthemap]]
[[Game Title::GameTitle]]
```
and on **GameTitle** main page shows (explanation purpose only): There X  maps in this game{{#if: Y < X | Y have a page. |.}}

My goal is (see also offtopic bellow) to minimize the number of "same strings" and make the digits calculate themselves not hardcoding them. If I do the following I'm repeating myself. Right now I'm starting but I imagine I'll get more and more consistency issues in the future week. 
```
[[Map Name::GameTitle/Maps/Nameofthemap]]
[[Game Title::GameTitle|]]
```

**off topic - sorry:**
Each abilities have a page with their stats detailed and on a main page I could show all stats of all abilities for example (with images and such) without needing complicated multiple embedded templates. Would that be possible with SMW?

See for stats example this section of a wiki which use many templates to store all data separately : https://deadbydaylight.gamepedia.com/Sally_Smithson#Nurse.27s_Perks

I find this to be hard for new people to edit as they have to open all templates and edit complicated wikicode to add something simple, as opposed to SMW which you only add variables in the article itself.

**Comment by kghbln** [comment]
> make the digits calculate themselves not hardcoding them

Use the count format here.

>  to minimize the number of "same strings"

I do not know your logic for page names. Use e.g. `#titleparts` or `{{ROOTPAGENAME}}`, etc.

> without needing complicated multiple embedded templates

I do not know how your abilities are annotated to these pages. In the end the user will want add just one template to a page and populate the parameters to annotate the content of the page. It may very well be that there are templates in the background that allow for this to happen with just one user facing template.

> off topic - sorry

I guess the [user mailing list](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_mailing_lists) is best for off topic since to my experience sometimes answers to one off topic leads to many further questions off topic.

**Comment by Extarys** [comment]
Haha thanks, cheers!
