### ISSUE TITLE
Incorrect call of Count () by {{#show:}} under PHP 7.2

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#2964]
### Setup and configuration

Продукт | Версия
-- | --
MediaWiki | 1.30.0 (d0c8f49)01:49, 6 января 2018
PHP | 7.2.1-1+ubuntu17.10.1+deb.sury.org+1 (fpm-fcgi)
MariaDB | 10.2.12-MariaDB-10.2.12+maria~artful-log
LuaSandbox | 2.0.13-alpha
Lua | 5.1.5

Расширение | Версия | Лицензия | Описание | Авторы
-- | -- | -- | -- | --
Semantic MediaWiki | 2.5.5 (5aa7f20) 20:16, 25 октября 2017 | GPL-2.0+ | Делает вашу вики более доступной — для машин и людей (документация в сети) | Markus Krötzsch, Jeroen De Dauw, James Hong Kong и другие
Semantic Result Formats | 2.5.4 (4ad6f2d) 21:15, 13 ноября 2017 | GPL-2.0+ | Дополнительные форматы вывода для запросов Semantic MediaWiki | James Hong Kong, Stephan Gambke, Jeroen De Dauw, Yaron Koren и другие
Semantic Scribunto | 1.1.0 (723cb7d) 03:25, 14 января 2018 | GPL-2.0-or-later | Расширение Semantic MediaWiki для встроенной поддержки расширения Scribunto | James Hong Kong и Tobias Oetterer

### Issue
The below message appears one time per `{{#show:}}` call:
```
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/var/www/wiki/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php</b> on line <b>296</b><br />
```

### Stack trace
There's no stack trace. However, below is the bebug output just before the warning:
```
[DBQuery] traditiowiki SELECT /* SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult  */  DISTINCT t0.smw_id AS id,t0.smw_title AS t,t0.smw_namespace AS ns,t0.smw_iw AS iw,t0.smw_subobject AS so,t0.smw_sortkey AS sortkey,t0.smw_sortkey  FROM `smw_object_ids` AS t0    WHERE t0.smw_id='2116' AND t0.smw_iw!=':smw' AND t0.smw_iw!=':smw-delete' AND t0.smw_iw!=':smw-redi'  ORDER BY t0.smw_sortkey ASC  LIMIT 55
[DBQuery] traditiowiki SELECT /* SMWSql3SmwIds::getDatabaseIdAndSort  */  smw_id,smw_sortkey  FROM `smw_object_ids`    WHERE smw_title = 'Правок_в_справке' AND smw_namespace = '152' AND smw_iw = '' AND smw_subobject = ''  LIMIT 1
[DBQuery] traditiowiki SELECT /* SMWSQLStore3Readers::fetchSemanticData  */  o_id AS id0,o0.smw_title AS v0,o0.smw_namespace AS v1,o0.smw_iw AS v2,o0.smw_sortkey AS v3,o0.smw_subobject AS v4  FROM `smw_fpt_redi` INNER JOIN `smw_object_ids` AS o0 ON o_id=o0.smw_id    WHERE s_title='Правок_в_справке' AND s_namespace='152'
[DBQuery] traditiowiki SELECT /* SMWSQLStore3Readers::fetchSemanticData  */  o_blob AS v0,o_serialized AS v1  FROM `smw_fpt_type`    WHERE s_id='172'
[DBQuery] traditiowiki SELECT /* SMW\SQLStore\QueryEngine\QuerySegmentListProcessor::resolveHierarchyForSegment  */  s_id  FROM `smw_fpt_subp`    WHERE o_id='172'  LIMIT 1
[DBQuery] traditiowiki SELECT /* SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult  */  DISTINCT t1.smw_id AS id,t1.smw_title AS t,t1.smw_namespace AS ns,t1.smw_iw AS iw,t1.smw_subobject AS so,t1.smw_sortkey AS sortkey,t3.o_sortkey  FROM `smw_object_ids` AS t1 INNER JOIN `smw_di_number` AS t3 ON t1.smw_id=t3.s_id    WHERE t1.smw_namespace='2' AND (t3.p_id='172') AND t1.smw_iw!=':smw' AND t1.smw_iw!=':smw-delete' AND t1.smw_iw!=':smw-redi'  ORDER BY t3.o_sortkey DESC  LIMIT 6
[error] [f8e68b30c8ac4c92e00096f5] /%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:Alex_Mashin   ErrorException from line 296 of /var/www/wiki/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php: PHP Warning: count(): Parameter must be an array or an object that implements Countable
```

### Steps to reproduce:
```{{#show:User:Alex Mashin|?Edits in templates}}```.

The property _Edits in templates_ is defined and set for _User:Alex Mashin_.

The `{{#show:}}` parser function works as expected except the warning.

**Comment by kghbln** [comment]
Thanks for reporting. Note that SMW 2.5.5 is only up to speed with PHP 7.1.x maximum. So if this is a PHP 7.2.x issue we know why it is happening. Still this may very well help making SMW 3.0.x even better.

**Comment by alex-mashin** [comment]
Yes, `count ()` gives a warning since PHP 7.2 ([count ()](http://php.net/manual/en/function.count.php)).

I think this can be corrected by replacing this:
```
(294) $parts = $showMode && $name == 0 ? $rawParam : explode( '=', $rawParam, 2 );

```
with this:
```
(294) $parts = $showMode && $name === 0 ? [$rawParam] : explode( '=', $rawParam, 2 );
```
or this:
```
(296) if ( count( $parts ) >= 2 ) {
```
with this:
```
(296) if ( is_array ($parts) && count( $parts ) >= 2 ) {
```

**Comment by mwjames** [comment]
> Yes, count () gives a warning since PHP 7.2 (count ()).

Most sane is `(296) if ( is_array ($parts) && count( $parts ) >= 2 ) {`.

> PHP | 7.2.1-1+ubuntu17.10.1+deb.sury.org+1 (fpm-fcgi)

As you can see from #2965 there is more to that than just this change.

**Comment by mwjames** [comment]
This is fixed on master, yet it is very unlikely that I will make backport since #2969 shows there is more to that than just one simple count.
