### ISSUE TITLE
Creating subobjects in a page from a hook not exposing Parser object

### ISSUE THREAD

**Issue by toniher** [SemanticMediaWiki/SemanticMediaWiki#2974]
### Setup and configuration

- SMW version: master
- MW version: 1.27
- PHP version: 7.0.x

### Issue

Hi, I'm updating an extension to perform the following feature:

Check page content in JSON content model format, if JSON is OK and page happens to be in a specific namespace that allows it, convert JSON information in different subobjects associated to that page.

I'm triggering the storage of subobjects from a PageContentSaveComplete hook, which does not expose a Parser object. I'm creating to create it here:
https://github.com/toniher/SemanticDataImport/blob/master/includes/SDImportData.php#L240

but it seems it is not liked here:
https://github.com/toniher/SemanticDataImport/blob/master/includes/SDImportData.php#L263

Should this be approached in a different way?

Thanks!

**Comment by mwjames** [comment]
Let me give you some really quick notes (I'm bit pressed with time right now) and I'll try to come back to this by next work or so.

SMW uses `NewRevisionFromEditComplete` [1] (`PageContentSaveComplete` should give the same object access) to fetch new revision data which is where you get access to the `EditInfo` and `ParserOutput` object. Once you hace access to that object you can freely access the `ParserOutput::getExtensionData( 'smwdata' )` which holds the internal `SemanticData` object that we push during a request between objects and can be manipulated before MWs `LinksUpdateConstructed` event triggers the deferred queue that includes those updates used by `Store::updateData`. Everything that happens before `LinksUpdateConstructed` is triggered and added to the `SemanticData` object will be considered during an update.

```
$content = $this->revision->getContent();

$editInfo = $this->wikiPage->prepareContentForEdit(
	$content,
	null,
	$this->user,
	$content->getContentHandler()->getDefaultFormat()
);

$parserOutput = isset( $editInfo->output ) ? $editInfo->output : null;
```

[0] https://github.com/wikimedia/mediawiki/blob/b376e4bbdad708f5beaa298a65a0628b5d5a7312/includes/page/WikiPage.php#L1843-L1849
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/LinksUpdateConstructed.php

**Comment by mwjames** [comment]
See also https://www.semantic-mediawiki.org/wiki/Developing_extensions/Access_to_in-process_data

**Comment by toniher** [comment]
From Revision object (https://doc.wikimedia.org/mediawiki-core/master/php/classRevision.html) I don't see a straight way to get a ParserOutput object. It seems possible in combination with WikiPage object (other example: https://doc.wikimedia.org/mediawiki-core/master/php/DifferenceEngine_8php_source.html#l00653 ). The only thing I wonder how the ParserOptions object should be, specifically about the context. Where should I get it. It does not seem to work from neither Title nor Revision nor WikiPage. So far I tried t his:

`      

        public static function insertInternalObjectViaJSON( $wikiPage, $revision, $object, $struct ) {

                $pageTitle = $wikiPage->getTitle();

                // $context = $pageTitle->getContext(); // FAILS
                // $context = $wikiPage->getContext(); // FAILS
                // $context = $revision->getContext(); // FAILS

                $context = new RequestContext();
                $context->setTitle( $pageTitle );                 
                $parserOptions = $wikiPage->makeParserOptions( $context );

                $parserOutput = $wikiPage->getParserOutput( $parserOptions, $revision->getId() );

                var_dump( $parserOutput );
                $semanticData = $parserOutput->getExtensionData( 'smwdata' );

                var_dump( $semanticData );

`

but  $semanticData is NULL... more context may be needed...

**Comment by toniher** [comment]
I just tried with the $editInfo above an it's not working either. I have the impression that pages with content model other than wikitext are not exposing 'smwdata' via ParserOutput. I double-checked that the custom namespace is enabled with SMW, and it seems that internal property Modification_date is actually working.

**Comment by mwjames** [comment]
> I just tried with the $editInfo above an it's not working either. I have the
> impression that pages with content model other than wikitext are not
> exposing 'smwdata' via ParserOutput. I double-checked that the custom

The sole purpose of the attached code is to demonstrate how to add a
subobject programmatically to a page object (given the namespace is
enabled) using the `PageContentSaveComplete` hook.

If you add the following code snippet at the end of your
`LocalSettings.php` (of course anywhere is fine) you would see that
using the `PageContentSaveComplete` hook and the editInfo (as outlined
before) attaches a subobject to a page you save.

It should be noted that I used SMW specific objects (because I know
they work) to fetch the ParserOutput but of course any standard MW
object will do as well.

I did not bother to work on the content itself which is where you have
to fill in dots on how to parse the content (aka JSON) and make some
sense out of the structure.

```
\Hooks::register( 'PageContentSaveComplete', function( $wikiPage,
$user, $content, $summary, $isMinor, $isWatch, $section, $flags,
$revision, $status, $baseRevId, $undidRevId ) {

	$applicationFactory = \SMW\ApplicationFactory::getInstance();

	$mwCollaboratorFactory = $applicationFactory->newMwCollaboratorFactory();

	/**
	 * Initialize the ParserOuput object
	 */
	$editInfoProvider = $mwCollaboratorFactory->newEditInfoProvider(
		$wikiPage,
		$revision,
		$user
	);

	$parserOutput = $editInfoProvider->fetchEditInfo()->getOutput();

	if ( !$parserOutput instanceof \ParserOutput ) {
		return true;
	}

	$parserData = $applicationFactory->newParserData(
		$wikiPage->getTitle(),
		$parserOutput
	);

	// Subject Foo ...
	$subject = $parserData->getSubject();

	// Contains the wikitext, JSON or whatever is stored for this content model
	$nativeData = $content->getNativeData();

	// Identify the content as unique
	$subobjectName = '_MYCUSTOMPREFIX' . md5( $nativeData );

	$subject = new \SMW\DIWikiPage(
		$subject->getDBkey(),
		$subject->getNamespace(),
		$subject->getInterwiki(),
		$subobjectName
	);

	// Build the subobject by using a separate container object
	$containerSemanticData = new \SMWContainerSemanticData(
		$subject
	);

	/**
	 * Start doing all the work required after this
	 */

	// If one knows the details you can add it directly
	$containerSemanticData->addPropertyObjectValue(
		new \SMW\DIProperty( 'PropertyIWantToUse' ),
		new \SMW\DIWikiPage( 'SomeTextItem', NS_MAIN )
	);

	// If you don't know the type, use the DataValueFactory (see available methods)
	$dataValue = \SMW\DataValueFactory::getInstance()->newDataValueByText(
	   'AnotherPropertyIWantToUse',
	   '123'
	);

	$containerSemanticData->addDataValue(
		$dataValue
	);

	/**
	 * Done
	 */

	// This part is used to add the subobject the the main subject
	// Page: Foo -> gets a _MYCUSTOMPREFIX.... attached
	$parserData->getSemanticData()->addPropertyObjectValue(
		new \SMW\DIProperty( \SMW\DIProperty::TYPE_SUBOBJECT ),
		new \SMWDIContainer( $containerSemanticData )
	);

	$parserData->pushSemanticDataToParserOutput();

	return true;

} );

```

I hope this shed some light on the topic.

**Comment by toniher** [comment]
This worked very nicely. Very useful and thanks for the patience!
