### ISSUE TITLE
simple ask Query on Concept:Datatype does not work as expected

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2981]
### Setup and configuration
see
https://www.semantic-mediawiki.org/wiki/Concept:Datatype#List_of_Datatypes

### Issue
{{#ask:[[Concept:Datatype]]
|?Has datatype ID=typeid
|format=table
}}

Does not produce any output as of today. **Why?**

**Comment by kghbln** [comment]
Seems to be working now.

**Comment by WolfgangFahl** [comment]
But why did the results not show for quite a while?
