### ISSUE TITLE
Reference Datatype displayed strangely

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2985]
### Setup and configuration

https://www.semantic-mediawiki.org/wiki/Queen_Victoria

### Issue
I tried to create an example Property with type reference as:
https://www.semantic-mediawiki.org/wiki/Property:Has_Wikidata_Reference

and tried to assign
`[[Has Wikidata Reference::https://en.wikipedia.org/wiki/Queen_Victoria;Q9439]]
`

which is displayed as
![qv](https://user-images.githubusercontent.com/1336221/35739320-812c6c18-0831-11e8-867e-24caf4746372.png)

which looks strange to me since it has visible html code elements.

**Comment by kghbln** [comment]
Aus der Lamäng: It looks to me that the field sequence is imperatively `[[Has fields::Property for the reference value;Property for the reference date;Property for the reference source]]`

**Comment by kghbln** [comment]
Indeed from the datatype docu: 

> By convention the first field of the "Has fields" declaration must describe the property holding the value to be referenced. 

So after changing from `[[Has fields::Has URL;Has Wikidata item ID]]` to `[[Has fields::Has Wikidata item ID;Has date;Has URL]]` it works as expected.

**Comment by kghbln** [comment]
Doing `[[Has fields::Has Wikidata item ID;Has URL]]` works too.

**Comment by WolfgangFahl** [comment]
I want to reference the URL - what is wrong with that?

**Comment by mwjames** [comment]
> I want to reference the URL - what is wrong with that?

Nothing. See #2986 for some details.

> Personally I think that the DataType name "Reference" is misleading.

People always have different opinions and taste and we recognize that but this in itself is not a reason or the cause for the issue you outlined above.

> So Reference is not so much difference from Record and might be used for quite a few use cases not only the classical "reference" use case. 

The reference type by its definition is used to record provenance data, any other use (knowingly or unknowingly) to its stated purpose is not in scope of the type itself.

It is obvious, the `_ref_rec` and `_rec` share some common functionality which is to make sure that a data item is unequivocally bound to the rest of the recorded data set, yet you should not draw a conclusion that while technical they share commonalities are "not so much difference".
