### ISSUE TITLE
Special:Ask UX issues

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#2989]
I noticed the cool enticements to Special:Ask coming in 3.x when reading https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1365#issuecomment-362813504

On playing with it at https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Requ%C3%AAter I found some room to make it even moar awesome from a UX perspective:

* The `Empty` link has unclear behavior. I was not sure what it would do until I clicked it. Using the word "Clear" would be more... clear. "Clear all" or "Clear page" would be even clearer.

* The cheat sheet is displayed in a box that does not clock when you click outside of it, as is convention on the web. You need to actually move the cursor to the x at the top right and click it.

* It is not that obvious how to expand the parameter list or that one can do this to begin with. Having a "show more" link underneath the shortened list would help with that.

**Comment by JeroenDeDauw** [comment]
Haha, we don't have a UX or UI tag :) Who needs UIs anyway. #JustUseTheAPI or better yet #JustWriteSomePHP --Silly Jeroen being silly, no need to take this serious

**Comment by mwjames** [comment]
> The cheat sheet is displayed in a box that does not clock when you click outside of it, as is convention on the web. You need to actually move the cursor to the x at the top right and click it.

See below.

> It is not that obvious how to expand the parameter list or that one can do this to begin with. Having a "show more" link underneath the shortened list would help with that.

See below.

![special-ask](https://user-images.githubusercontent.com/1245473/35769340-7db35652-0901-11e8-98e7-cfbdf431c3f5.gif)

**Comment by kghbln** [comment]
> The Empty link has unclear behavior. I was not sure what it would do until I clicked it. Using the word "Clear" would be more... clear. "Clear all" or "Clear page" would be even clearer.

Agreed, and I changed to "Clear all entries". I also reworded the option to remove a sorting condition to "remove" instead of "delete".

> It is not that obvious how to expand the parameter list or that one can do this to begin with. Having a "show more" link underneath the shortened list would help with that.

Indeed we could help users here buy showing "Show more" and "Show less" respectively. Here I however need assistance from the experts. I only know that "/src/MediaWiki/Specials/Ask/ParametersWidget.php" is the spot.

**Comment by kghbln** [comment]
Reopened due to the second https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2989#issuecomment-363704661

**Comment by mwjames** [comment]
> Indeed we could help users here buy showing "Show more" and "Show less" respectively. Here I however need assistance from the experts. I only know that "/src/MediaWiki/Specials/Ask/ParametersWidget.php" is the spot.

Right spot, but there is a reason I went for `[ ]` otherwise with a changing text size you get some unaesthetic element changes.

> It is not that obvious how to expand the parameter list or that one can do this to begin with. Having a "show more" link underneath the shortened list would help with that.

You might be able to add the element to the end of the line to avoid the mentioned issue but that will be a hassle and has no priority for me. If you think it is important, I'll review a PR but won't get involved.

**Comment by kghbln** [comment]
@mwjames Thanks for your comments. Thus closing for now but I will add "seeks developer" and add it to the "Enhancements and features" project to eventually be picked up.
