### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by SteveRMann** [SemanticMediaWiki/SemanticMediaWiki#2992]
I would appreciate an 'include' feature.
(Unless there is a better method)
I have a fairly complex Mediawiki on my home server, and on many pages I have a "navigation" section at the bottom of the page to make it easy to navigate to other relevant pages in the topic.  Not very unlike your "See Also" navigation.
The problem is that if I have ten sub-pages in a topic, I wind up copying the navigation lines on all ten of those pages.  If I add a new sub-page, I have to go back and edit all ten of the existing pages' navigation lines.  

An 'include' feature would be great so that I only have to edit the navigation lines once, then 
'include nav.txt'  where I want those lines inserted.

For example:
nav.txt file would contain:
```
==<p><font size="5" face="Georgia, Arial">[[Python MQTT|MQTT]]</font></p>==
;[[Python MQTT|MQTT]]
:[[mosquitto:installing|Installing Mosquitto]]
::[[mosquitto.conf|mosquitto.conf]]
::[[mosquito:persistence|persistence]]
::[[mosquitto:qos|QOS]]
:[[mqtt notes]]

```

**Comment by kghbln** [comment]
@SteveRMann Are you using Semantic MediaWiki? If yes, then have a look at the [tree format](https://www.semantic-mediawiki.org/wiki/Help:Tree_format). If you are "just" using MediaWiki put the wikitext into a template called e.g. "Navigation" and include it on the respective pages. Thus you only have to edit the template to get the updated version in on all pages using the template.

**Comment by jaideraf** [comment]
@SteveRMann you could also be interested in [SubPageList extension](https://www.mediawiki.org/wiki/Extension:SubPageList).

**Comment by kghbln** [comment]
I guess you got some ideas on how to approach your issue. Please reopen in case we misunderstood what you were trying to convey.

**Comment by SteveRMann** [comment]
Yes, the tips were very much appreciated.
