### ISSUE TITLE
ISO Date format

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2994]
https://www.semantic-mediawiki.org/wiki/Help:Type_Date

shows several ways of localizing your date formats. For my international wikis I want the opposite:
I stricly only want to use ISO dateformat no matter what. 

1. How much effort would it be to have a global setting for this? 
2. Is there such an option already?

**Comment by mwjames** [comment]
> I stricly only want to use ISO dateformat no matter what.

What exactly does this mean, The query, the special pages, the annotation itself?

> How much effort would it be to have a global setting for this?

Depends on the use case, if it is technical feasible, and whether this is something we want to support. Currently the described use case is unclear and therefore the technical effort is hard to estimate.

> Is there such an option already?

I'm not aware of one.

**Comment by kghbln** [comment]
If I interpret correctly this is about getting a configuration parameter that automatically adds [`#ISO`](https://www.semantic-mediawiki.org/wiki/Help:Type_Date#ISO) to all printout request for properties of type date without actually having to add this manually in every query.

**Comment by mwjames** [comment]
> If I interpret correctly this is about getting a configuration parameter that automatically adds #ISO to all printout request for properties of type date without actually having to add this manually in every query.

If that's the case then I'm guessing you might be able to find something in [0] but I'm not so happy about the "doing it just for #ISO" (if at all), so this needs a better approach, tests, and a PR (I can review).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/DataValues/ValueFormatters/TimeValueFormatter.php#L341-L356

**Comment by kghbln** [comment]
> I'm not so happy about the "doing it just for #ISO" 

Indeed this would not make sense. One should be able to add whatever formatter to it, e.g. `#MEDIAWIKI`, `#LOCL`, etc.

**Comment by WolfgangFahl** [comment]
As an example see https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2018-02-10

https://www.semantic-mediawiki.org/wiki/Property:Has_release_date
shows all date in english format to me since my "language" is english

Semantic Media Wiki 1.0 December 31, 2007

I'd rather like to see:

Semantic Media Wiki 1.0 2017-12-31
  I have no option to set an "ISO" language since their seems to be no differenciation of locale and language.

{{#ask: [[Has_release_date::+]]
|?Has_release_date
}}

has the same effect. This could be changed by:
{{#ask: [[Has_release_date::+]]
|?Has_release_date#ISO
}}

but I'd rather prefer:
{{#ask: [[Has_release_date::+]]
|?Has_release_date#DEFAULT
}}

and be able to set the default globally e.g. to ISO. Better even if I don't have to specify 
#DEFAULT 
but this is the normal behavior and I can change the DEFAULT to e.g. USER_SPECIFIC or ISO or any fixed locale.

The same holds true for all the other internationalization issues. I do not want to bother with true/false issues and stuff like that. I'd rather for for "x","-" to avoid the issue at all instead of going with multiple translations that make life hard when working with an API.

The current configurability of SMW is just great from a user experience point of view. From an API point of view it gives me so much trouble because I do not even know how to to know what representation of data I'll get - it's all configuration and wiki dependend.

**Comment by WolfgangFahl** [comment]
In http://wiki.bitplan.com/index.php/Bogensport#Turniere I keep having the issue with 

> {#ask: [[Concept:Bogenturnier]] [[Bogenturnier date>{{CURRENTYEAR}}-{{CURRENTMONTH}}-{{CURRENTDAY}}]]

I consider using the isodate format to be the most natural thing to do but it seems not work "out-of-the-box"

**Comment by kghbln** [comment]
Note that the syntax you are using is wrong. It should be `[[Bogenturnier date::>{{CURRENTYEAR}}-{{CURRENTMONTH}}-{{CURRENTDAY}}]]` and when things may become most natural.

**Comment by WolfgangFahl** [comment]
@kghbln Thx for helping out - i fixed the page and it now works.
