### ISSUE TITLE
JSON serialization of SMW API only available as "object"

### ISSUE THREAD

**Issue by MvGulik** [SemanticMediaWiki/SemanticMediaWiki#3038]
Any particular special reasoning why SMW opted for using a {...} JSON-object <=> Python-Dictionary structure for packing the JSON query result data, instead of the [...] Array <=> List structure ... as used by MediaWiki itself (_the expected default, if there is such a standard thing of course_).

The thing is that in Python dictionary structures (_the default one_) do not have a fixed/maintained order, and as such also don't maintain any given order of imported JSON object data.

Example, just in case.
[Some MW API call](https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=jsonfm&formatversion=2&titles=Main%20Page)

```
<snip>
    "query": {
        "pages": [  <== this part.
            {
<snip>
```
[Some SMW API call](https://www.semantic-mediawiki.org/w/api.php?action=ask&query=[[Modification%20date::%2B]]|%3FModification%20date|sort%3DModification%20date|order%3Ddesc&format=jsonfm)
```
<snip>
        ],
        "results": {  <-- that part.
            "Help:Installation/es": {
<snip>
```

**Comment by MvGulik** [comment]
https://www.semantic-mediawiki.org/wiki/Serialization_(JSON)
> **Results**
> The results array will contain: 

Think that should be "Object", not "Array".
ie: {...} versus [...] ==> https://www.json.org/

**Comment by kghbln** [comment]
Thanks for bringing up this question. Pining our experts: @mwjames @JeroenDeDauw @s7eph4n

**Comment by mwjames** [comment]
An old discussion about the very topic can be found at [0]. If I find
the time during my weekend sprint, I may add some additional comments.

It should be obvious that we cannot change the output to avoid having
users of the API retrieve broken API data but we can introduce a
`api_version` parameter that would allow those that need a list `[]`
to retrieve them in a modified format.

[0] https://phabricator.wikimedia.org/T47303

Cheers

**Comment by kghbln** [comment]
Thanks for your insight.

>  but we can introduce a `api_version` parameter that would allow those that need a list `[]` to retrieve them in a modified format.

I guess this will be awesome. Thus I reclassify this issue as an enhancement.

**Comment by MvGulik** [comment]
Thanks for the related phabricator link.
I see why. ... :( 

> we can introduce a `api_version` parameter that would allow those that need a list `[]` to retrieve them in a modified format.

Definitely to way to go in this case, in my view.
_Personally I would also think about future depreciating the {...} format for the related results part. But that's just me._

>I may add some additional comments.

More info is always appreciated on this side.

**Comment by MvGulik** [comment]
:-)
