### ISSUE TITLE
"Special:Concepts" only list a small proportion of existing concepts

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3043]
### Setup and configuration

- MediaWiki | 1.27.4 (317104c)23:34, 7 February 2018
- PHP | 7.0.25-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.21-0ubuntu0.16.04.1

### Issue
"Special:Concepts" only list a small proportion of existing concepts starting with the first concepts by name.

### Example
["Special:Concepts"](https://www.semantic-mediawiki.org/wiki/Special:Concepts) in comparison to ["Special:AllPages"](https://www.semantic-mediawiki.org/wiki/Special:AllPages?from=&to=&namespace=108)

I do not think that this is a caching issue since "LocalSetting.php" was touched and the browser cache cleared. Perhaps something related to misermode?

**Comment by mwjames** [comment]
We filter subobjects from a `[[Concept:+]]` query and may distort the limit offset which can be the reason why we only see the top of the `0 -50` range.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/specials/SpecialConcepts.php#L45-L65

**Comment by kghbln** [comment]
> We filter subobjects from a [[Concept:+]] query and may distort the limit offset which can be the reason why we only see the top of the 0 -50 range.

This sounds reasonable. Hopefully it is only a small effort to adapt.
