### ISSUE TITLE
readapidenied: You need read permission to use this module - Special:Browse in a private wiki

### ISSUE THREAD

**Issue by toniher** [SemanticMediaWiki/SemanticMediaWiki#3053]
I sent to user mailing list, but it seems it's down and I have not find this answered in another thread yet, sorry if it was answered already or in any documentation place...

I'm testing Semantic MediaWiki 2.5.6 in a 1.27.4 private wiki. Configuration in LocalSettings.php:

    $wgGroupPermissions['*']['read']              = false;
    $wgGroupPermissions['*']['edit']              = false;
    $wgGroupPermissions['user']['read']           = true;
    $wgGroupPermissions['user']['edit']           = true
    $wgGroupPermissions['*']['createaccount'] = false;

When accessing Special:Browse I'm getting this error:

    readapidenied: You need read permission to use this module

What are the approaches to follow for allowing this, and keeping wiki private for users, of course...

**Comment by mwjames** [comment]
> When accessing Special:Browse I'm getting this error:
> readapidenied: You need read permission to use this module

I suspect that logged-in users won't get the message, right? All others do because of `$wgGroupPermissions['*']['read'] = false;`

**Comment by mwjames** [comment]
https://www.mediawiki.org/wiki/API:FAQ#do_I_get_the_readapidenied_error?

**Comment by toniher** [comment]
Since it's a private wiki, the problem is with logged-in users. Non-logged-in users cannot even access wiki pages.

**Comment by kghbln** [comment]
Are you using the Lockdown extension? If yes you are currently out of luck. There is an MW core issue that prevents the API from being used. See https://gerrit.wikimedia.org/r/c/303358/. If not, I do not know.

**Comment by mwjames** [comment]
> Since it's a private wiki, the problem is with logged-in users. 

That should work as we reuse the standard API interface. If it doesn't then this needs some investigation but be warned it will have a low priority for me unless someone points me into a direction with actionable tasks.

**Comment by toniher** [comment]
@kghbln You're right! That's Lockdown extension. I close this here.

**Comment by kghbln** [comment]
@toniher Thanks for confirming my fears. Only the very first API call per user works. After that: bang. I would really appreciate if you could weight in somehow. It is pretty nasty since MW core appears to be the issue maker.

**Comment by toniher** [comment]
Thanks @kghbln Too bad I was not aware before. Let me see what I can do...
