### ISSUE TITLE
New date formats

### ISSUE THREAD

**Issue by dbobak** [SemanticMediaWiki/SemanticMediaWiki#306]
Would it be possible to add to SMW two new date formats? That is: BP and b2k. They are widely used in geology and archaeology. The "BP" is acronym to "before present" and is counted in years before 1950 (f.e., year 1900 = 50BP). The "b2k" means "years before year 2000", and is counted analogically: calendar year 1900 = 100b2k.

Of course it is possible to calculate dates from BC notation, but it makes some mess, because the BP and b2k notations are standard in earth sciences.

Thanks in advance,
Darek

**Comment by mwjames** [comment]
Has been moved to the "Enhancements and features" kanban, any implementation can make a reference to this issue.
