### ISSUE TITLE
factbox + cite conflict

### ISSUE THREAD

**Issue by alissa-huskey** [SemanticMediaWiki/SemanticMediaWiki#3081]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.30.0
- PHP version: 7.0.28 (cgi-fcgi)
- DB system: MySQL 5.6.36-82.1-log

### Issue

I seem to have encountered a conflict between the semantic mediawiki factbox and the Cite extension. Namely, when the Cite extension is enabled, the factbox does not appear. I created an example page here below, though in order to really see the behavior, I'll need to switch back and forth between enabling and disabling the cite extension. For now, Cite is enabled. There are screenshots on the page that show that the factbox does appear if the Cite extension is disabled.

http://wiki2.convergentproject.com/index.php?title=Cite_factbox_conflict

### Steps to reproduce

1. Install the Cite plugin: https://www.mediawiki.org/wiki/Extension:Cite
2. Create or load a wiki page using `__SHOWFACTBOX__` and verify that the factbox appears as expected.
3. Create a demo wiki page with the following:

```
== Summary ==

This page is intended to demonstrate the conflict between the factbox<ref>https://www.semantic-mediawiki.org/wiki/Help:Factbox</ref> feature in the semantic mediawiki extension<ref>https://www.semantic-mediawiki.org/wiki/Help:Introduction_to_Semantic_MediaWiki</ref>, and the cite extension<ref>https://www.mediawiki.org/wiki/Extension:Cite</ref>.

{{#set: foo=bar}}

__SHOWFACTBOX__
```
4. In LocalSettings.php, disable the Cite extension then reload the demo wiki page; the factbox will appear and the citation footnotes will disappear. (Expected.)
```
// wfLoadExtension( 'Cite' );
```

5. In LocalSettings.php, enable the Cite extension then reload the demo wiki page; the factbox will disappear (unexpected) and the citation footnotes will appear (expected.)
```
wfLoadExtension( 'Cite' );
```

**Comment by kghbln** [comment]
Thanks a lot for reporting! The fix https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3076 will be part of SMW 3.0.0. See also the test on https://sandbox.semantic-mediawiki.org/wiki/Issue/3081 for a now working example.

**Comment by mwjames** [comment]
> https://sandbox.semantic-mediawiki.org/wiki/Issue/3081 for a now working

Thanks for the follow-up.
