### ISSUE TITLE
XML: error parsing RDF document

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#3134]
### Setup and configuration

- SMW version: 3.0.0-alpha
- MW version: 1.30.0
- PHP version: 7.0.27
- MariaDB: 10.1.26

### Issue
XML informs error at parsing:
`<property:Datenqualität/Herkunft rdf:resource="&wiki;Der_Datensatz_wurde_basierend_auf_der_ÖK50-2C_Stand_2011_digitalisiert._Es_wurden_alle_Waldbestände_für_die_Gemeinde_Kopfing_erfasst."/>`

Should we escape "/" by `&#47;` or `&#x2F; `or `&sol;`? [0]

### Stack trace
[See sandbox](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Export_RDF/Lorem_ipsum_Export).

[0] https://en.wikipedia.org/wiki/Slash_(punctuation)#Encoding

**Comment by mwjames** [comment]
> <property:Datenqualität/Herkunft rdf:resource="&wiki;Der_Dat

As far as I can recall that should happen here [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Exporter/ExpResourceMapper.php#L239-L243

**Comment by kghbln** [comment]
Well, considering the age of the code it is at least not a regression for 3.0.0

**Comment by jaideraf** [comment]
Maybe it is not a blocker but, given sandbox is testing 3.0.0-rc.1, this issue is not over yet, [look](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Export_RDF/Lorem_ipsum_Export).

**Comment by mwjames** [comment]
>Maybe it is not a blocker but, given sandbox is testing 3.0.0-rc.1, this issue is not over yet, look.
> https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Export_RDF/Lorem_ipsum_Export

The issue here is with `[[Datenverantwortliche Stelle – E-Mailkontakt::poststelle.magistratsabteilung33@wien.gv.at]]` where the first `–` is not a normal dash but a Unicode symbol hence it is not recognized as dash in the ASCII format.

**Comment by jaideraf** [comment]
Thanks for the explanation @mwjames

**Comment by kghbln** [comment]
Added at different spots to make sure this does not get overlooked:
* [Property naming](https://www.semantic-mediawiki.org/w/index.php?title=Help:Property_naming&diff=prev&oldid=64594)
* [Special page "ExportRDF"](https://www.semantic-mediawiki.org/w/index.php?title=Help:Special:ExportRDF&diff=64595&oldid=59602)
* [Help:$smwgPropertyInvalidCharacterList](https://www.semantic-mediawiki.org/w/index.php?title=Help:$smwgPropertyInvalidCharacterList&diff=64591&oldid=63195)

**Comment by mwjames** [comment]
Maybe create a PR and add `–` to `smwgPropertyInvalidCharacterList` because a normal users cannot distinguish `Foo-Bar` from `Foo–Bar` by just looking at it (it took me some time and tools to figure out the true nature of the issue).

**Comment by kghbln** [comment]
> Maybe create a PR and add – to smwgPropertyInvalidCharacterList because a normal users cannot distinguish Foo-Bar from Foo–Bar by just looking at it (it took me some time and tools to figure out the true nature of the issue).

Doing something like this could be endless since there are many characters that are alike. However since I consider this a pretty popular pitfall at least for Germans I will to a pull tomorrow.
