### ISSUE TITLE
List format: Documentation on how to achieve multiple columns using CSS

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#3135]
### Setup and configuration

- SMW version: 3.0
- Follow-up to #2488 

The "columns" parameter was removed from the list format in SMW 3.0 (#2488) with the advice to "use CSS instead" ([0]).  There should be detailed documentation that provides details on how to use CSS to implement columns for query results.

[0] https://gist.github.com/s7eph4n/277e7804fe04954df7d1e15ae874b0d0#parameters-to-ask-and-show

**Comment by kghbln** [comment]
Documented:
- [ul](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AUl_format&type=revision&diff=66270&oldid=64867)

Missing:
- [ol]
- [list]
