### ISSUE TITLE
How to register the SMW::Store::AfterDataUpdateComplete hook?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3141]
refs [Correct way to register "SMW::Store::AfterDataUpdateComplete" hook in extension.json?](https://www.semantic-mediawiki.org/wiki/Thread:Help_talk:Hooks/Correct_way_to_register_%22SMW::Store::AfterDataUpdateComplete%22_hook_in_extension.json)

### Issue

```
I tried to register "SMW::Store::AfterDataUpdateComplete" in my extention.json but it seems not to be working.

 "Hooks": {
    "SMW::SQLStore::AfterDataUpdateComplete": [
      "SomeExtensionNs\\Hook::onAfterDataUpdateComplete"
     ]
 },

Could it be that there some typo?

It works when i register the Hook the old way like:

		global $wgHooks;
		$wgHooks['SMW::SQLStore::AfterDataUpdateComplete'][] = 'SomeExtenionNs::onAfterDataUpdateComplete'

    Reply
    More

Racoon (talk)‎14:05, 26 April 2018
```

**Comment by mwjames** [comment]
Probably I always meant to create `SMW::Store::AfterDataUpdateComplete` but I never did, only `SMW::SQLStore::AfterDataUpdateComplete` [0] exists for the `SQLStore` and for any other store it remains the `SMWStore::updateDataAfter` (2.5-).


[0] https://www.semantic-mediawiki.org/wiki/Help:Hooks

**Comment by mwjames** [comment]
## Target release

3.0

## Tasks

To follow the naming scheme:

- [ ] Create `SMW::Store::BeforeDataUpdateComplete`
- [ ] Create `SMW::Store::AfterDataUpdateComplete`

**Comment by mwjames** [comment]
> Did I get you right, that it should be possible to register "SMW::SQLStore::AfterDataUpdateComplete" via extension.json? Maybe I did something wrong with namespaces:

```
 "Hooks": {
    "SMW::SQLStore::AfterDataUpdateComplete": [
      "SomeExtensionNs\\Hook::onAfterDataUpdateComplete"
     ]
 },
```
`SMW::SQLStore::AfterDataUpdateComplete` exists as hook and the registration should work as outlined in: 

```
`$wgHooks['SMW::SQLStore::AfterDataUpdateComplete'][] = 'SomeExtenionNs::onAfterDataUpdateComplete'`
```

As for `extension.json` I never used it, best to consult the `extension.json` documentation about how to register hooks, I know that `$wgHooks` works.

**Comment by kghbln** [comment]
Re-scheduled for now to be part of 3.1.0

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/hooks/hook.store.afterdataupdatecomplete.md
