### ISSUE TITLE
Wrong info on https://www.semantic-mediawiki.org/wiki/Help:$smwgQueryResultNonEmbeddedCacheLifetime

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#3154]
The page https://www.semantic-mediawiki.org/wiki/Help:$smwgQueryResultNonEmbeddedCacheLifetime has wrong variable in section "Changing the default setting".

It is also unclear whether this is the right place to report issues about the wiki documentation.

**Comment by kghbln** [comment]
Thanks a lot for reporting. As far as I am concerned you could report either here or on wiki though the wiki appears to be the more intuitive choice. I am already happy if somebody reports at all.

I will fluff the docu and also think about how I could best convey that the wiki is probably the first choice.

**Comment by kghbln** [comment]
> The page https://www.semantic-mediawiki.org/wiki/Help:$smwgQueryResultNonEmbeddedCacheLifetime has wrong variable in section "Changing the default setting".

Now [rectified and improved](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgQueryResultNonEmbeddedCacheLifetime&type=revision&diff=62946&oldid=57642)

> It is also unclear whether this is the right place to report issues about the wiki documentation.

It took me a while to understand our mechanics but I added a [note](https://www.semantic-mediawiki.org/w/index.php?title=Template%3ADoc.info.list&type=revision&diff=62976&oldid=61099) providing information in case of uncertainty.
