### ISSUE TITLE
Allow value separator in CSV result format

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#316]
This is an enhancement request for the CSV format.

It would be nice if we could specify a separator between values of the same property.
Currently the CSV format only has the "sep" parameter to separate "fields" (values of different properties), but not values of the same property.
http://semantic-mediawiki.org/wiki/Help:CSV_format

Current behavior (only comma as a separator):
Parameter:
|sep=$

Result:
"Property1"$"Propert2"$"Property3"~...
"P1value1,P1value2"$"P2value1"$"P3value1,P3value2"

Wanted behavior (other possible separators):
Parameter:
|sep=$
|valuesep=+

Result:
"Property1"$"Propert2"$"Property3"~...
"P1value1+P1value2"$"P2value1"$"P3value1+P3value2"

[P.S.: Bug moved from https://bugzilla.wikimedia.org/show_bug.cgi?id=57330]

**Comment by mwjames** [comment]
Has been moved to the "Enhancements and features" kanban, any implementation can make a reference to this issue.

**Comment by kghbln** [comment]
Improvement will be served with SMW 3.0.0
