### ISSUE TITLE
Is MW 1.31 supported?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3163]
Per email:

> MW 1.31.0-rc.0 is out. Should I upgrade?

In general, the project uses reproducible test builds as basis for recommending or declaring compatibility with a MediaWiki release.

For users who want to use MW 1.31 we currently can only note that "Our test environment (incl. the one running on SMW 2.5+) do passes on listed MediaWiki releases [0] including 1.30 unfortunately MW 1.31 (rc.0) has shown an increased failure rate and we are unable to recommend the release for production as it contains failing tests that do pass with any other listed MediaWiki release [0] running Semantic MediaWiki.".

[1] contains a list of tracked issues in regards to MW 1.31.

PS: Issues encountered with MW 1.31 may only be of cosmetic nature but as long as the test environment fails for a particular release/DB type we are unable to pronounce a recommendation.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md#platform-compatibility
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=is%3Aissue+is%3Aopen+label%3Amediawiki

**Comment by mwjames** [comment]
@kghbln In case of any user inquiry.

**Comment by kghbln** [comment]
Thanks for the info. I will upgrade sandbox next week and we will see...

**Comment by kulusuk** [comment]
Let us know your experience. Now that 1.31 is officially releasedas an LTS version, I hope SMW will support it.

**Comment by kghbln** [comment]
I upgraded [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Main_Page) to use MW 1.31.x about six weeks ago and so far have not detected any serious issues. I believe the plan is also to support MW 1.31+

**Comment by JeroenDeDauw** [comment]
Indeed, the next release of SMW will support 1.31. The previous release likely does as well, though presumably you'll end up with some warnings in the logs.

**Comment by mwjames** [comment]
> Indeed, the next release of SMW will support 1.31.

I appreciate the enthusiasm but doubt it reflects the reality of course if you get [0] to pass I see no issue in declaring compatibility but as I earlier stated "reproducible test builds" are the key for compliance so unless effort is directed towards that goal, I'm unable to see how MW 1.31 can be officially supported.

PS: Note that the same tests pass for the MW 1.27 environment.

> ... ago and so far have not detected any serious issues. I believe the plan is also to support MW 1.31+

I do sympathize with users who are looking for a simple answer but anecdotal evidence such as above cannot replace "reproducible test builds" that in my view are required to conduct a release process in a professional manner.

The project runs ~6300 tests on different platforms and configurations helping project members to minimize support efforts before and after a release. The codified (meaning expected) behaviour allows to detect dysfunctional behaviour to a certain degree early on and relieve developers from expensive ad-hoc maintenance tasks hereby reducing the overall cost of maintenance.

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/403855632

```
Using PHP 7.2.7
Semantic MediaWiki: 3.0.0-alpha, git: 394a115, SMWSQLStore (postgres:9.2.24)
MediaWiki:          1.31.0, git: N/A, Extension vendor autoloader
Site language:      en
Execution time:     2018-07-14 10:32
Debug logs:         Disabled
Xdebug:             2.6.0
PHPUnit 6.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.2.7 with Xdebug 2.6.0

.............                                                 6357 / 6357 (100%)
Time: 6.47 minutes, Memory: 606.50MB
There were 103 errors:
```

**Comment by kghbln** [comment]
@mwjames worked on getting support for MW 1.31+ on track and it is save to say that paradise was regained. Thanks a lot!

**Comment by jamesmontalvo3** [comment]
@kghbln does that mean MW 1.31 is now supported by SMW 2.5, SMW 3.0, or both? I think the answer is:

* SMW 3.0 supports MW 1.31+ because current builds (e.g. [1]) have `MW=REL1_31` and `MW=master` jobs that pass
* SMW 2.5 does not support MW 1.31+ because current builds of that branch (e.g. [2]) do not have `MW=REL1_31` jobs and the `MW=master` job is failing

[1] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/428063753
[2] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/425712539

**Comment by kghbln** [comment]
> I think the answer is:

Affirmative, though master is MW 1.32+ in both cases.

**Comment by jamesmontalvo3** [comment]
1.32+? Why not 1.31? Are you saying:

* If you have MW 1.30 or lower, you must use SMW 2.5.x
* If you have MW 1.32 or greater, you must use SMW 3.0 (aka `master`)
* If you have MW 1.31 you may not use SMW

?

**Comment by kghbln** [comment]
> If you have MW 1.31 you may not use SMW

With master I was referring to MW master.

> SMW 3.0 supports MW 1.31+ because current builds (e.g. [1]) have MW=REL1_31 and MW=master jobs that pass

Yes, because it tests with `REL1_31` which is MW 1.31.x and `master` which is MW 1.32+

> SMW 2.5 does not support MW 1.31+ because current builds of that branch (e.g. [2]) do not have MW=REL1_31 jobs and the MW=master job is failing

Yes, because it does not test with `REL1_31` which would be MW 1.31.x and unsuccessfully tests with `master` which is MW 1.32+ and failing.

In the end you may just have a look at [COMPATIBILITY.](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md)

**Comment by jamesmontalvo3** [comment]
Thank you. I was just making sure because I saw COMPATIBILITY hadn't been updated since your comment that sounded like a change in what was supported: 

> @mwjames worked on getting support for MW 1.31+ on track and it is save to say that paradise was regained. Thanks a lot!

**Comment by kghbln** [comment]
> Thank you. I was just making sure because I saw COMPATIBILITY hadn't been updated since your comment that sounded like a change in what was supported:

No, it was not updated back then to indicate that there may be no support for MW 1.31+. Thus no ajustment was necessary.
