### ISSUE TITLE
How to fetch data from Special:Ask via cURL?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3168]
refs https://sourceforge.net/p/semediawiki/mailman/message/36312276/

> Essentially, I'd like the results of a query such as:
{{#ask: [[Category:Foo]] [[MyParam::Bar]] |format=csv }}
> How does one write a cURL statement so as to querry the wiki from a php script and save the data into a veriable?

```php
// Wiki url
$url = 'http://127.0.0.1:8080/wiki/index.php';

// Query parameters
$params = [
	'title' => 'Special:Ask',
	// Query conditions
	'q'     => '[[Has number::+]]',
	// Printouts
	'po'    => 'Has number',
	// Parameters
	'p'     => 'format=csv',
	// since 3.0+
	'request_type' => 'raw'
];

$options = array(
	CURLOPT_URL => $url,
	CURLOPT_POST => true,
	CURLOPT_POSTFIELDS => http_build_query( $params ),
	CURLOPT_RETURNTRANSFER => 1
);

// Create curl resource
$ch = curl_init();

// Set options
curl_setopt_array( $ch, $options );

// Fetch output string
$output = curl_exec( $ch );

// Close curl resource
curl_close( $ch );
```
The `$output` contains the content as string from the predefined `format`. The above example uses a similar approach as implemented by #3167.

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
[Linked from wiki](https://www.semantic-mediawiki.org/wiki/Help:Remote_request)
