### ISSUE TITLE
Querying all the subobjects included in a page requires forcing a refresh (purge) on this page

### ISSUE THREAD

**Issue by Megajoul** [SemanticMediaWiki/SemanticMediaWiki#3171]
### Setup and configuration
- SMW version: 2.5.6
- MW version: 1.30.0
- Semantic Internal Objects : 0.8.2
- PHP version: 7.0.22
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.20

Previous setup and configuration: 
- SMW version: 1.8.0.5
- MW version: 1.21.11
- Semantic Internal Objects : 0.7.5
- PHP version: 5.4.45
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.5.40

### Issue
A page includes subobjects with the syntax : `{{subobjectTemplate | property1 = ...}}`.
The template of this page includes a query on itself `{{#ask: ... {{PAGENAME}} ... }}` to display information related to the subobjects.
If we add a new subobject, it is unfortunately necessary to force a refresh (_purge_) so that the request returns this new subobject. However, when browsing the properties, before the refresh, the subobject appears recorded in the page.
This does not work with the subobject syntax embedded in SMW (`{{#subobject:`) nor with the Semantic Internal Objects extension syntax (`{{#set_internal:`).
It worked in previous versions.
Is it related to the problem of [categorization via the job queue](https://phabricator.wikimedia.org/T145206) ?

### Steps to reproduce
Do I really need to create all the stuff in a ... [sandbox](https://sandbox.semantic-mediawiki.org) to demonstrate the observed issue, otherwise provide us with a simple reproducible use case ?

**Comment by Megajoul** [comment]
Hi again,
It seems that the problem comes from the query `{{#ask:{{FULLPAGENAME}}|?someProperty}}` or `{{#show:{{FULLPAGENAME}}|?someProperty}}`. It is necessary to force a refresh (_purge_) to make the query result appear.
Thanks in advance for your help.
Megajoule

**Comment by kghbln** [comment]
Sorry for not replying to your question earlier. Indeed a lot of things changed since the versions you used before you upgraded that have to be taken into account.

I recommend to have a look at [embedded query updates](https://www.semantic-mediawiki.org/wiki/Help:Embedded_query_update). Moreover run [`rebuildData.php`](https://www.semantic-mediawiki.org/wiki/Help:Maintenance_script_%22rebuildData.php%22) on a regular basis, e.g. daily. Look at the `--shallow-update` flag to do this.

**Comment by Megajoul** [comment]
Hi Kghbln,
Thank you for replying to my question.
I solved my problem thanks to this page : https://www.semantic-mediawiki.org/wiki/FAQ#Why_doesn.27t_data_I_have_just_added_show_up_in_queries.3F
Especially thanks to this advice : 
> _Finally, if you run a small- or medium-sized wiki, you can simply disable MediaWiki page caching altogether, which probably will not have a huge impact on performance. This can be done in one easy step._ 

Besides, running a daily script doesn't allow to get SMW pages with up-to-date subobjects just after saving. Does it ?

Bye,
Megajoule

**Comment by kghbln** [comment]
Thanks for reporting back what helped you getting things going.

> Besides, running a daily script doesn't allow to get SMW pages with up-to-date subobjects just after saving. Does it ?

No, obviously it does not. It is just a thing that you should do regardless.

**Comment by mwjames** [comment]
> {{#show:{{FULLPAGENAME}}|?someProperty}}

This is using self-reference queries which has its restrictions as to when embedding page values are available in a query. I added some comments and further explanatory links in 3220.

**Comment by hexmode** [comment]
I think you meant #3230 since #3220 is about elasticsearch coverage.
