### ISSUE TITLE
delegate deprecated in current versions of jQuery

### ISSUE THREAD

**Issue by Henryfunk** [SemanticMediaWiki/SemanticMediaWiki#3174]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.30.0
- PHP version: 7.0.30-0ubuntu0.16.04.1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL, 5.7.22-0ubuntu0.16.04.1

_Note that it is **required** to provide the setup and configuration information. If you believe to have detected a regression after updating your software please also provide information about your previous setup as well. **In any case only this information will enable us to allocate appropriate review time.** Thank you for you help._

### Issue
The jQuery function "delegate" used in the file "jquery.qtip.js" is deprecated as of jQuery 3.0 ( http://api.jquery.com/delegate/ ) . I noticed it while trying to get rid of all those warning from JQMIGRATE.

**Comment by JeroenDeDauw** [comment]
I suspect this issue has already been resolved by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3085, so this warning should go away when switching to SMW 3.0 once that version has been released.

**Comment by JeroenDeDauw** [comment]
@mwjames please reopen if I am wrong

**Comment by Henryfunk** [comment]
OK, thanks.
