### ISSUE TITLE
The "json" module is deprecated

### ISSUE THREAD

**Issue by Krinkle** [SemanticMediaWiki/SemanticMediaWiki#3177]
### Issue

SemanticMediaWiki (latest master) registers a module `ext.jquery.jStorage` which depends on the `json` module from MediaWiki core which has been deprecated since MediaWiki 1.29.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/dd07f85b69fe2b58733017725982fb77bea67ec2/res/Resources.php#L65

In MediaWiki 1.29, the JavaScript run-time for Grade A was made to require native support for ES5, including `JSON.parse` and `JSON.stringify`. As such, the `json` polyfill no longer made sense.

The module was kept as an empty no-op serving only a deprecation warning.

I intend to remove the module in the current release cycle (for MW 1.32).

**Comment by kghbln** [comment]
@Krinkle Great coincidence. Just yesterday I discovered this issue on our sandbox wiki when trying to track down another issue. You were however faster reporting it. To cut it short: Thanks a lot!

**Comment by Nikerabbit** [comment]
Would it make sense to backport this patch? I cannot run Special:JavaScript test without it.

**Comment by mwjames** [comment]
> No objection from my side. If @mwjames has nothing against doing so I could
> cherry-pick to 2.5.x

No objection.

PS: I thought you just made the 2.5.7 release? Issue like that should
be marked earlier or mentioned appropriately before a release!

**Comment by kghbln** [comment]
> PS: I thought you just made the 2.5.7 release? Issue like that should
be marked earlier or mentioned appropriately before a release!

Indeed this would have been ideal however we are not living in an ideal world. Sometimes things like this are triggered by some event and one starts remembering .... Well @Nikerabbit will probably run master of 2.5.x so it appears not to be a biggest issue to me.

**Comment by kghbln** [comment]
Back-ported to 2.5.x with ad23b1637bd6f1fb7d3fc7b45a4086555df278c9
