### ISSUE TITLE
`#smwdoc`: specific parameters are shown for the "debug" and "count" formats

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3186]
### Setup and configuration

- MediaWiki | 1.31.0 (63a4e21)13:06, 20. Jun. 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-alpha (dd07f85) 08:18, 25. Jun. 2018

### Issue
`#smwdoc`: specific parameters are shown for the "debug" and "count" formats though they do not support them:
- [debug](https://sandbox.semantic-mediawiki.org/wiki/Smwdoc/debug)
- [count](https://sandbox.semantic-mediawiki.org/wiki/Smwdoc/count)

**Comment by JeroenDeDauw** [comment]
`SMWQueryProcessor::getParameters` is returning the base list of parameters no matter what format is given to it. 

These are two "exception" formats that you can easily argue are not really formats at all. They could have been `#count` and `#debugask` parser functions.

Not clear if having them supported by `#smwdoc` even makes sense. What do you think the thing should show for these "formats"?

**Comment by kghbln** [comment]
> SMWQueryProcessor::getParameters is returning the base list of parameters no matter what format is given to it.

I was not even checking on these. This one was about the format specific parameters shown via `parameters=specific`. So I expect a message like for [bibtex](https://sandbox.semantic-mediawiki.org/wiki/Smwdoc/bibtex).

When it comes to the base list of parameters shown via `parameters=base` a similar message will be nice, e.g. "This result format does not support parameters."
