### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by ralpha** [SemanticMediaWiki/SemanticMediaWiki#3193]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.31.0
- PHP version: 7.1.18
- DB system (MySQL, Blazegraph, etc.) and version: MySQL

### Issue
Inline CSS, bad practice. Skin can not overwrite this.
Background color van not be overwritten by skin.

### Stack trace
SemanticMediaWiki/src/MediaWiki/Specials/Ask/ParametersFormWidget.php
Line: 118-121
```
$resultHtml .= Html::rawElement( 'tr', array(
	'style' => 'background: ' . ( $i % 6 == 0 ? 'white' : '#eee' )
	), $rowHtml
);
Similar issue in line 128-131.
```
### Steps to reproduce
Go to file: 'Special:Ask' inspect table in 'Other options'
```
<tr> has <tr style="background: #eee">
```

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue. Looks like it has already been fixed in the development version (see link), so once 3.0 is released you'll be able to overwrite the stuff in a skin.
