### ISSUE TITLE
Parameters "intro" and "outro" ignore "link" syntax in images

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#3196]
### Setup

- MediaWiki | 1.31.0 (959e09c)18:43, 12 July 2018
- PHP | 7.0.30-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-alpha (c47b2ad) 14:15, 10 July 2018

### Issue
I just realized that the definition of a linked image does not work if put inside `intro=` or `outro=` parameters of ask queries.

### Steps to reproduce
[Image Link test](https://sandbox.semantic-mediawiki.org/wiki/Issue/3196)

**Comment by kghbln** [comment]
The issue template is there for a reason, thus it will be nice if you fill in all the data. Most importantly the setup changes in time. It may or may not be important to know at one point what exactly was going on. One never knows ...

> I just realized that the definition of a linked image does not work if put inside intro= or outro= parameters of ask queries.

Yeah, I can imagine cases where this will be nice. I have added a workaround using the template format to your example page.

**Comment by mwjames** [comment]
> The issue template is there for a reason, thus it will be nice if you fill in all the data.

Exactly, and the contribution guideline clearly states the requirement. Furthermore, if an issue is without proper annotation, I will ignore those reports whereby it doesn't matter whether it is a critical issue or not.

**Comment by krabina** [comment]
sorry I thought that if I can provide an example in sandbox I don't have to fill out what version sandbox is using for you guys. Or did you mean you want the specs of my wiki even though I have an example in sandbox?

**Comment by kghbln** [comment]
> Or did you mean you want the specs of my wiki even though I have an example in sandbox?

Preferably the specs of you wiki

> sorry I thought that if I can provide an example in sandbox I don't have to fill out what version sandbox is using for you guys.

providing specs and examples is decoupled so even if only sandbox is available these specs are required too. sandbox specs change on a daily basis.

**Comment by krabina** [comment]
ok. Will do better next time :-)
