### ISSUE TITLE
SPARQL triple-store vendors

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3199]
The following section tries to outline the current state of open source triple store vendors that are tested in connection with Semantic MediaWiki.

## Fuseki

Fuseki [f.0] is developed as part of the Jena project which is under the direction of The Apache Software Foundation and hereby available with a Apache License, Version 2.0.

## virtuoso-opensource

[v.0] notes that "Virtuoso 8.0 adds features beyond prior releases that aren't part of the Open Source Edition ...".

## 4store

In the past we had reports that users where successful in connecting with 4store [4.0] including [4.1] but no recent release has been tested against 4store. 4store is distributed under the terms of a GPL version 3 License.

## openrdf-sesame (now rdf4j)

Sesame 2.8.7 is actively used as testing platform, no active attempts have been made to migrate [s.0] to the now called rdf4j. rdf4j is licensed under the terms of the Eclipse Distribution License (EDL), v1.0 while openrdf-sesame was distributed under the terms of a BSD-style License.

## Blazegraph

As [b.0] shows, Blazegraph version 2.1.4 is supported and passes our test suite. It should be noted that the last release has been issued 30 Aug 2016 [b.1] and certain reports suggest that Blazegraph is part of Amazon [b.2,b. 3, b.4, b.5] now which may impact its availability as open source and hereby future releases and fixes.

> ... it was acquired by Amazon last year. The domain was certainly acquired by Amazon, and a number of key Blazegraph developers now work at Amazon, including Brad Bebee, CEO of Blazegraph until this year, and now giving sessions on Neptune ...

>  ... the Blazegraph triplestore may play some role in Amazon's new graph store. As Stardog CEO Kendall Clark wrote on ycombinator recently, "Amazon acquired the domains, etc. Many former Blazegraph engineers are now Amazon Neptune engineers ...

[f.0] https://jena.apache.org/documentation/fuseki2/
[v.0] https://github.com/openlink/virtuoso-opensource/issues/690
[b.0] https://www.youtube.com/edit?o=U&video_id=oi2bAWpl32w
[b.1] https://github.com/blazegraph/database/releases
[b.2] http://www.i-programmer.info/news/84-database/11358-amazon-neptune-graph-database.html
[b.3] http://www.snee.com/bobdc.blog/2017/12/sparql-and-amazon-web-services.html
[b.4] https://www.trademarkia.com/blazegraph-86498414.html
[b.5] https://www.zdnet.com/article/back-to-the-future-does-graph-database-success-hang-on-query-language/
[4.0] https://github.com/4store/4store
[4.1] https://travis-ci.org/mwjames/SemanticMediaWiki/builds/61200454
[s.0] http://docs.rdf4j.org/migration/

**Comment by kghbln** [comment]
I referenced this [here](https://www.semantic-mediawiki.org/w/index.php?title=Help:Using_SPARQL_and_RDF_stores&curid=1921&diff=63917&oldid=63278) and [there](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASPARQLStore&type=revision&diff=63918&oldid=63285) on wiki.
