### ISSUE TITLE
Special:Version RuntimeException

### ISSUE THREAD

**Issue by GrumpyGecko** [SemanticMediaWiki/SemanticMediaWiki#3224]
### Setup and configuration

- SMW version:3.0
- MW version:1.31
- PHP version:7.2
- DB system (MySQL, Blazegraph, etc.) and version:5.7.22 - MySQL Community Server (GPL) 

_Note that it is **required** to provide the setup and configuration information. If you believe to have detected a regression after updating your software please also provide information about your previous setup as well. **In any case only this information will enable us to allocate appropriate review time.** Thank you for you help._

### Issue
_Please describe the issue as best as you can and also fill in the following two sections if applicable._
The Special:Version page is not showing any more, only an error message is visible.

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:
[709a79946651aea1bc313ead] /index.php?title=Special:Version RuntimeException from line 59 of /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/src/Elastic/Connection/DummyClient.php: The DummyClient is not expected to be used outside of a test environment.

Backtrace:

#0 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/src/Elastic/Connection/ConnectionProvider.php(90): SMW\Elastic\Connection\DummyClient->__construct()
#1 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/src/Connection/ConnectionManager.php(32): SMW\Elastic\Connection\ConnectionProvider->getConnection()
#2 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/src/Store.php(575): SMW\Connection\ConnectionManager->getConnection(string)
#3 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(646): SMW\Store->getConnection(string)
#4 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(981): SMWSQLStore3->getConnection(string)
#5 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/Hooks.php(177): SMW\MediaWiki\Hooks\HookRegistry->newSoftwareInfo(array)
#6 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#7 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/specials/SpecialVersion.php(241): Hooks::run(string, array)
#8 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/specials/SpecialVersion.php(139): SpecialVersion::softwareInformation()
#9 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/specialpage/SpecialPage.php(522): SpecialVersion->execute(NULL)
#10 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#11 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#12 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/MediaWiki.php(861): MediaWiki->performRequest()
#13 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/includes/MediaWiki.php(524): MediaWiki->main()
#14 /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/index.php(42): MediaWiki->run()
#15 {main}

### Steps to reproduce
_It is recommend to use the [sandbox](https://sandbox.semantic-mediawiki.org) to demonstrate the observed issue, otherwise provide us with a simple reproducible use case._

The error can be seen: https://chatwars-wiki.de/index.php?title=Special:Version

**Comment by mwjames** [comment]
> /var/www/vhosts/hosting108982.a2f12.netcup.net/httpdocs/extensions/SemanticMediaWiki/src/Elastic/Connection/DummyClient.php:
> The DummyClient is not expected to be used outside of a test environment.

I removed the check yesterday, so this should be fixed with the latest
3.0 master.

**Comment by GrumpyGecko** [comment]
perfect timing of mine. Just updated and it works now. Thank you very much.
