### ISSUE TITLE
Headers does not show when querying for reverse properties

### ISSUE THREAD

**Issue by rotsee** [SemanticMediaWiki/SemanticMediaWiki#324]
`{{#ask:[[Lemon]]|?-Is related to=Relative}}` does not print `Relative` as expected (or anything else, for that matter) in the header. For a demonstration, see here: http://smw.referata.com/wiki/User:Rotsee/Headers_for_reverse_queries

Tested under Semantic MediaWiki 1.8.0.5 and 1.9.2

**Comment by mwjames** [comment]
Fixed with  #1270.
