### ISSUE TITLE
How to refine a map by coordinates or categories.

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#3242]
### Setup and configuration

- SMW version:  2.5.6
- MW version:  1.27.3
- PHP version: 7.0.30
- DB system (MySQL, Blazegraph, etc.) and version: mySQL 5.7.22

### Issue
I would like to show map with leaving some points out.  I only want to show the locations in scotland, but not the ones in the "GettingThere" category.

see http://ebike.bitplan.com/index.php/Category:Scotland2018

### Steps to reproduce
I tried putting the locations i do not want to show in a category and ask for not including them like this:

```
{{#ask:
[[Category:Scotland2018]][[!Category:GettingThere]]
|?Has coordinates
|format=map
}}

```

Another approach would be to ask for coordinates which are north of a certain line. I wouldn't know how to specify this in an ask query.

**Comment by mwjames** [comment]
As for:

> [[Category:Scotland2018]][[!Category:GettingThere]]

See my comment in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1084#issuecomment-385158762.

**Comment by WolfgangFahl** [comment]
Thx for the quick comment. So plan B would be to take the latitude of the coordinate and compare it to a decimal value. Is that somehow possible? Plan C would be to let the semantic template put the category into a property so that it is available for comparison.

**Comment by mwjames** [comment]
> I would like to show map with leaving some points out. I only want to show the locations in scotland, but not the ones in the "GettingThere" category.

https://sandbox.semantic-mediawiki.org/wiki/Issue/3242

**Comment by mwjames** [comment]
> ... would be to ask for coordinates which are north of a certain line. I wouldn't know how to specify this in an ask query.

@JeroenDeDauw @kghbln ?

> ... would be to take the latitude of the coordinate and compare it to a decimal value. Is that somehow possible?

@JeroenDeDauw @kghbln ?

**Comment by kghbln** [comment]
I do not think that Map permits to convert a latitude or longitude into a decimal value. Since we already have a template and category on the respective pages I'd suggest to use a boolean helper property. e.g. "Is shown on map" and add this into the pages using, e.g. [PageInCat.](https://www.mediawiki.org/wiki/Extension:PageInCat)

**Comment by JeroenDeDauw** [comment]
I don't really understand the decimal value question. Relevant docs:

https://www.semantic-mediawiki.org/wiki/Maps/Coordinates
https://www.semantic-mediawiki.org/wiki/Maps/Coordinate_formats

> would be to ask for coordinates which are north of a certain line. I wouldn't know how to specify this in an ask query.

This is not possible. Beyond the normal SMW query operations the only special thing Maps add are distance queries.

One way to support such queries would be adding new special syntax with special support and special blah. That does not appeal to me. (And is a bunch of work that I am not doing for a single use case.) On the other hand I am wondering about having locations stored as some kind of subobjects. Then such queries might be possible out of the box using normal SMW features. @mwjames @kghbln any thoughts on that? I'm quite fuzzy on how this all works, both from the user and technical perspective. Might both be useful and easy to implement.

**Comment by mwjames** [comment]
> One way to support such queries would be adding new special syntax with special support and special blah.

Not unless it is absolutely necessary.

> Then such queries might be possible out of the box using normal SMW features. @mwjames @kghbln any thoughts on that?

The range query should work, shouldn't it? Once you have the coordinates of what north entails doing a simple `>` or `<` (or query all members within a specific bounding box) should be able to answer the "ask for coordinates which are north of a certain line", anyway I see this more of a SM specific question than SMW core.

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3242#issuecomment-406862639 provides an example on how to exclude certain coordinates given available annotations are made for it, so the original question should have been answered.

Excluding categories is only supported in ES.

**Comment by WolfgangFahl** [comment]
Please do not close this - it is a question and I do not have a proper answer yet.

**Comment by JeroenDeDauw** [comment]
> The range query should work, shouldn't it? Once you have the coordinates of what north entails doing a simple > or < (or query all members within a specific bounding box) should be able to answer the "ask for coordinates which are north of a certain line", anyway I see this more of a SM specific question than SMW core.

Are you talking about the current situation, or the one where coordinates are stored as subobjects?

> Over the years I more and more get the feeling that it is not a good idea to have an "ask" query syntax. 

You can use SPARQL no? AFAIK you will run in the same problem though: coordinates being exposed as a string rather than a lat and long structure. I might be wrong about that as I've never really looked at how SMW does SPARQL stuff.

**Comment by mwjames** [comment]
> Over the years I more and more get the feeling that it is not a good idea to have an "ask" query syntax. I'd rather use some generally known query syntax and only add parameters that make sense for the special needs of SMW and the ask environment.

Does this provided the context I ask for in relation to the stated issue?

SMW and its extensions provided functionality for specific and
documented use cases, if certain use cases aren't covered you either
can see to it that it can by extending the code base or look for a
different tool that can.

#ask is an abstraction layer that let users query different backends
such as SQL, SPARQL, or Elastic without being bound to the technical
environment or its constraints. Of course, such abstraction comes at a
cost but that cost is taken into account with the intention to limit
access to SQL or SPARQL in its native form.

PS: You may express your dissatisfaction or frustration but comments
such as above are less likely to increase the willingness to listen by
those who spend their volunteer time on improving the software in
general or maintain the issue tracker.

> You can use SPARQL no?

You cannot use SPARQL in #ask (see above) directly. #1987 is an open
request for interested parties to implement (which excludes myself)
and shouldn't be too difficult to provide that functionality.

**Comment by JeroenDeDauw** [comment]
James, I think you got confused by who was asking about what. Neither of my questions where a reply to what you wrote in your previous comment. And I think you did a great job at providing support here so far, above and beyond what you can expect from a volunteer. My questions are purely to increase my understanding of the situation and see if we can easily improve things and if there is need for that in the first place.
