### ISSUE TITLE
How to sort the page title second in #ask?

### ISSUE THREAD

**Issue by icopp** [SemanticMediaWiki/SemanticMediaWiki#3323]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.30.0
- PHP version: 7.2
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.1.31

### Issue

I've been trying to figure out how to do something very simple: how to put the page title in an #ask sort, but after another property. For example:

```
{{#ask:
  [[Category:Widges]]
  |mainlabel=Widgets
  |?Has property1=Property1s
  |sort=Has property1, ???
}}
```

I have no idea what to fill in for `???`. As far as I can tell, nobody else anywhere I've looked knows how to make it work either. Is this even possible? Will I have to do some weird thing with templates and multiple #ask queries instead?

**Comment by kghbln** [comment]
> I have no idea what to fill in for ???. 

I'd say nothing. Just put a comma after the specified property name like:
```
{{#ask:
  [[Category:Widges]]
  |mainlabel=Widgets
  |?Has property1=Property1s
  |sort=Has property1,
}}
```

**Comment by kghbln** [comment]
@mwjames After looking at the referenced commit I realized that indeed "nothing" is recognized but in the end the sorting by the property provided is not done. See [sandbox example](https://sandbox.semantic-mediawiki.org/wiki/Issue/3323)

**Comment by mwjames** [comment]
> @mwjames After looking at the referenced commit I realized that indeed
> "nothing" is recognized but in the end the sorting by the property provided
> is not done. See [sandbox
> example](https://sandbox.semantic-mediawiki.org/wiki/Issue/3323)

Under the premise of sorting with `|?sort=,Is performer" where the
subject should be ordered first and `Is performer` second, the
ordering of titles takes precedence. Given that a tile is always
unique (there are no two titles that represent the same concept except
for being a redirect) a "asc" lexicographical order will put "Title/A"
before "Title/AB" no matter the value `Is performer` is assigned to.

There is one exception to the rule namely when you assign
`{{DEFAULTSORT: Title/A}}` to both titles, the sorting representation
becomes equal and the second parameter becomes the determining factor
in the ordering.

### Example

Title       DEFAULTSORT   Is performer

Title/A       Title/A               August
Title/AB    Title/A               September

* `|?sort=,Is performer |?order=asc,asc" to return Title/A, Title/AB
* `|?sort=,Is performer |?order=asc,desc" to return Title/AB, Title/A

* `|?sort=,Is performer |?order=desc,asc" to return Title/A, Title/AB
* `|?sort=,Is performer |?order=desc,desc" to return Title/AB, Title/A

### SMW 3.0+ (only relevant for the ElasticStore)

While reviewing the example, I found a little snag in the current
`ElasticStore` implementation that prevents the above to perform as
expected. We currently add the `title` as extra sort to ensure we
always have a determining order.

The following change should return the same results (for the above
example) as for the `SQLStore`.

```
@@ -94,10 +94,11 @@ class SortBuilder {

 		$isRandom = false;
 		$isConstantScore = true;
 		$sort = [];
 		$sortFields = [];
+		$count = count( $sortKeys );

 		foreach ( $sortKeys as $key => $order ) {
 			$order = strtolower( $order );
 			$isRandom = strpos( $order, 'rand' ) !== false;

@@ -106,25 +107,29 @@ class SortBuilder {
 				$this->isScoreSort = true;
 				$isConstantScore = false;
 			}

 			if ( $key === '' || $key === '#' ) {
-				$this->addDefaultField( $sort, $order );
+				$this->addDefaultField( $sort, $order, $count );
 			} else {
 				$this->addField( $sort, $sortFields, $key, $order );
 			}
 		}

 		return [ $sort, $sortFields, $isRandom, $isConstantScore ];
 	}

-	private function addDefaultField( &$sort, $order ) {
+	private function addDefaultField( &$sort, $order, $count ) {
 		$sort['subject.sortkey.sort'] = [ 'order' => $order ];

 		// Add title as extra criteria in case an entity uses the same sortkey
-		// to clarify its relative position, @see T:P0416#8
-		$sort['subject.title.sort'] = [ 'order' => $order ];
+		// to clarify its relative position (@see T:P0416#8)
+		// Only add the title as determining factor when no other sort parameter
+		// is available
+		if ( $count == 1 ) {
+			$sort['subject.title.sort'] = [ 'order' => $order ];
+		}
 	}
```

PS: After the change, we should add an integration test that covers the example.

**Comment by kghbln** [comment]
I figured that it might be related to ES as the data backend. I have just created a PR at least for the code change.
