### ISSUE TITLE
MCR, slots, and entities in SMW

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3345]
With MCR (#2905) approaching completeness in MediaWiki-core, somehow it becomes apparent that we would need to extend Semantic MediaWiki (SMW) in order to ensure that a title object (a subject in SMW, an entity) and its annotations continues to be uniquely identifiable via its `Title` representation.

#### Assumption

SMW only associates its annotations (hereby claims, facts) with the latest revision, historical data have no relevance to SMW and are not designed to be stored with SMW. Any new stored revision for a wiki page (aka `Title`) will replace any data in the SMW store with its associated entities.

### Current situation 

The current (MW 1.32-) association of content, latest revision, and `Title` provides an unambiguous method to represent data from a wiki page in SMW where a content object (which holds the raw text) identified by the `Title` can only hold one "truth" (aka the latest truth based on the latest revision) represented in SMW with a unique ID.

```
Title --------------------------> Latest revision --> Content --> Raw text 
  |
  | -> SMW entity --> ID 
```

In short, `new Title( 'Foo' )`  (implicitly assuming the latest revision) will always point to the SMW ID that represents the latest revision data in the store.

![image](https://user-images.githubusercontent.com/1245473/44616451-86a27580-a83f-11e8-814c-339c063b309b.png)

### Content and slots

As far as I understand with MCR the above (hereby the assumption about content uniqueness) will no longer produce the same results since a content object in MW is allowed to hold different "text" (blob) objects (known as slots). The association of Title → Latest revision → Content may point to different slots with each slot holding a different "truth" (or even contradictory) about the same entity (aka wiki page).

![image](https://user-images.githubusercontent.com/1245473/44616816-72ae4200-a846-11e8-85e8-f98a0aedca69.png)

### What's next?

For any future release it seems to become necessary to add a new `smw_slot` field into the `smw_object_ids` table to be able to distinguish and produce IDs for when an entity (e.g. `Foo`) has more than one slot assigned (meaning to have different text representations hereby containing different annotations).

#### Preliminary notes

* SMW 4.0+
* Querying should match all known IDs (including entities with different slots), so for example `{{#ask: [[knows::bar]] ...` should list `Foo|Slot 1` and `Foo|Slot 2` even though the "real" entity is `Foo`
* Find a method to represent an entity (aka subject) with a slot identifier (similar that what is used representing a subobject see `#....`) so that a query can list them as distinguishable such as:
  - Foo | ....
  - Foo#Slot:1 | ....
  - Foo#_Subobject_1 | ...
  - Foo#Slot:1#_Subobject_1 | ...
* Avoid any active reference to a Revision or RevisionStore object unless it is provided by the WikiPage/Content object or related hook (it is anticipated that it would introduce technical depth and will most likely break in future)

**Comment by mwjames** [comment]
@hexmode @gesinn-it @s7eph4n @kghbln 

Unless I'm mistaken on the assumptions I made above, it may prove to require substantial effort therefore you might want to take the chance on the upcoming SMWCon to discuss the impact, requirements, and resolutions.

I haven't seen MCR in action nor do I have the time to review the code related to it but my first impression is that refactoring would require some significant effort and testing.

**Comment by hexmode** [comment]
@cicalese you'll be at SMWCon, I think, right?  And MCR is under your purview, IIRC, so this seems like the perfect opportunity.

**Comment by cicalese** [comment]
Thank you for your insights, @mwjames. Discussing this at SMWCon is an excellent idea. As I mentioned in #2905, your input with respect to MCR is appreciated.

**Comment by gesinn-it** [comment]
@cicalese feel free to block a slot in upcoming SMWCon agenda [1]. Maybe during 2nd day (SMW News) or 3rd day (Tutorial/Hackathon).

[1] https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2018#Agenda

**Comment by cicalese** [comment]
Unfortunately, I have a schedule conflict and will not be able to be at SMWCon in December. Maybe somebody else would be willing to lead this discussion there? Or we could add it to the agenda for the next EMWCon?

**Comment by mwjames** [comment]
If in future someone provides a clear and concise introduction and resources like [0, 1] that lets third party developers easily participate on changes in regards to MCR the issue can be reopened but as per repository policy currently it provides no actionable task or information to elaborate further on this issue.

As per comments above, my requirement for a meaningful example would be to see a full cycle of how data entered in at least two different edit fields (for the same title) create different slots and interact with each other to make a judgement about adjustments or the impact to our datamodel.

[0] https://github.com/wikimedia/mediawiki-extensions-examples/blob/master/includes/XmlContent.php
[1] https://github.com/wikimedia/mediawiki-extensions-examples/blob/master/includes/XmlContentHandler.php
