### ISSUE TITLE
Installation, composer, and the download via git

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3346]
Only for the purpose of documentation!

### Fetching master

```
$ cd extensions

$ git clone -b master https://github.com/SemanticMediaWiki/SemanticMediaWiki.git

Cloning into 'SemanticMediaWiki'...
remote: Counting objects: 91929, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 91929 (delta 44), reused 33 (delta 13), pack-reused 91797
Receiving objects: 100% (91929/91929), 34.21 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (72255/72255), done.
Checking out files: 100% (2412/2412), done.
```

### Fetching a specific branch (aka version)

```
$ cd extensions

$ git clone -b 2.5.x https://github.com/SemanticMediaWiki/SemanticMediaWiki.git

Cloning into 'SemanticMediaWiki'...
remote: Counting objects: 91929, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 91929 (delta 44), reused 33 (delta 13), pack-reused 91797
Receiving objects: 100% (91929/91929), 34.21 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (72255/72255), done.
Checking out files: 100% (2412/2412), done.
```

Make sure the folder you just downloaded is called SemanticMediaWiki and located in extensions/

### Download archive

Instead of using Git you can alternatively download an archive with the latest version of SemanticMediaWiki or choose to download a specific version of SemanticMediaWiki.
Make sure you extract the archive into a new folder called SemanticMediaWiki inside the extensions folder of your MediaWiki installation.

## Using the composer-merge-plugin

Include the following into composer.local.json at the root of your mediawiki installation:

```
{
  "extra": {
    "merge-plugin": {
      "include": [
        "extensions/SemanticMediaWiki/composer.json"
      ]
    }
  }
}
```
and run from the root of your mediawiki installation:

```
composer install --no-dev
```
or

```
php composer.phar install --no-dev
```

**Comment by mwjames** [comment]
@kghbln I'd like us to stop producing tarball downloads as it binds volunteer time and is tedious to make for any minor release. So, instead maybe above can provide a installation method for those that have issues with a pure Composer approach and is similar to what the wikibase extension promotes [0].

[0] https://www.mediawiki.org/wiki/Wikibase/Installation

**Comment by kghbln** [comment]
Well, starting with SMW 3.0.0 I will no longer do it anyways, also due to the fact that it no longer works with extension registration anyways. Moreover I think that it does no longer make sense to run SMW on a machine without command line access.

**Comment by mwjames** [comment]
> Well, starting with SMW 3.0.0 I will no longer do it anyways, also due to the fact that it no longer works with extension registration.

We should add a note to the release notes about it.

**Comment by kghbln** [comment]
> We should add a note to the release notes about it.
