### ISSUE TITLE
Discontinue tarball releases

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3347]
Refs:
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3346#issuecomment-415963111
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1732#issuecomment-385165181

**Comment by kghbln** [comment]
I figured that I could be a great smart ass today but realized that trying to build a MW-SMW bundle both from file archives does not work since the "composer.local.json" file is being ignored, i.e. dependencies of SMW are not being fetched. Now trying the Git method.

**Comment by kghbln** [comment]
I have now created a shell script that clones MW and SMW, pulls in the depedencies and drops the tared file to sandbox. See [here](https://sandbox.semantic-mediawiki.org/wiki/MediaWiki-SemanticMediaWiki-bundle). I hope that this can serve as an individual file release.

**Comment by mwjames** [comment]
> I have now created a shell script that clones MW and SMW

If you think it has production quality why not create a repo (clone-mw-smw, or something similar) drop the script and a README so it can be used as reference or to create a local copy.

**Comment by kghbln** [comment]
> If  you think it has production quality why not create a repo  (clone-mw-smw, or something similar) drop the script and a README so it  can be used as reference or to create a local copy.

Not quite. Currently it is specific to my server and restricted to MW + SMW. What I still need to figure out:
- how to specify not just one extension to be included
- how to create a "composer.local.json" file via the script

**Comment by kghbln** [comment]
> If you think it has production quality why not create a repo

Done.

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AUsing_Composer%2FCopying_and_transferring_files_to_a_server&type=revision&diff=64274&oldid=64263)

**Comment by mwjames** [comment]
>Done. The script probably appears a bit crude in general, however it does its job which I verified by doing a field test.

Did a field test as well, so [0] provides sufficient convenience for all those that need a bundle, yet without us getting too involved in the file release process.

Security wise, the script uses the official sources (github, gerrit) which absolves us from being a possible attack vector on when we bundle files ourselves to make them accessible or downloadable.

[0] https://github.com/SemanticMediaWiki/IndividualFileRelease

**Comment by kghbln** [comment]
I just wonder why we did not do this before. ;)
