### ISSUE TITLE
Add compatibility with DataValues 2.x and dependants

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3371]
### Setup and configuration

- MediaWiki | 1.31.0 (c6f0a38)05:03, 15. Aug. 2018
- PHP | 7.0.30-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-alpha (95c5331) 07:50, 27. Aug. 2018

### Issue
After updating sandbox via Composer I the following software was update:
- "data-values/data-values" was updated from version 1.1.1 to 2.1.1
- "data-values/validators" was updated from version 0.1.2 to 0.1.3

This resulted into:
```
PHP Warning:  require(/../w/vendor/composer/../data-values/validators/Validators.php): failed to open stream: No such file or directory in /../w/vendor/composer/autoload_real.php on line 70
PHP Fatal error:  require(): Failed opening required '/../w/vendor/composer/../data-values/validators/Validators.php' (include_path='/../w/vendor/pear/console_getopt:/../w/vendor/pear/mail:/../w/vendor/pear/mail_mime:/../w/vendor/pear/mail_mime-decode:/../w/vendor/pear/pear-core-minimal/src:/../w/vendor/pear/pear_exception:.:/usr/share/php') in /../w/vendor/composer/autoload_real.php on line 70
```
After explicitly adding `"data-values/validators": "0.1.2",` to the "composer.local.json" file and thus downgrading the wiki is up and running again.

```
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 2 updates, 0 removals
  - Downgrading data-values/data-values (2.1.1 => 1.1.1): Loading from cache
  - Downgrading data-values/validators (0.1.3 => 0.1.2): Loading from cache
Writing lock file
Generating optimized autoload files
> ComposerVendorHtaccessCreator::onEvent
```

**Comment by kghbln** [comment]
@JeroenDeDauw @mwjames For your info and action. I am not sure if 2.5.x should upgrade however I guess that this branch also needs changes to make sure that DV 1.x continues to be used.

**Comment by JeroenDeDauw** [comment]
I am a bit confoosed. Running into a compatibility issue if SMW uses this component but does not specify which versions it works with it not surprising. But looking at the error... it seems like something is loading the Validators.php file, which no longer exists. It'd be quite weird for SMW to load this.

**Comment by kghbln** [comment]
I believe SMW was solely counting on [this](https://github.com/DataValues/Validators/pull/19/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L38) to be present.

**Comment by kghbln** [comment]
> I believe SMW was solely counting on this to be present.

No, this does not make sense. Somewhere it still tries to additionally load this file.

**Comment by JeroenDeDauw** [comment]
Yeah... the question is how and why it is doing that.

You sure you don't have an old composer genereted autoloader included somewhere?

**Comment by kghbln** [comment]
> You sure you don't have an old composer genereted autoloader included somewhere?

You mean the "composer.lock" file? I can get you both for current sandbox and for a regular install.

**Comment by kghbln** [comment]
> You sure you don't have an old composer genereted autoloader included somewhere?

A, I get it. Something in vendor or so.

**Comment by kghbln** [comment]
No all autoload files in `w/vendor/composer` were generated tonight. No artifacts around.

**Comment by JeroenDeDauw** [comment]
Yes, something in vendor/. That directory should have been updated though. Perhaps it exists more than once for this MW install? For instance once in the MW root and once in the SMW dir?

**Comment by kghbln** [comment]
Nope, I only have a vendor directory in MediaWiki root. SemanticMediaWiki is clean.

**Comment by kghbln** [comment]
Oh man, this is painful. Yeah, I had an old file in SRF. After updating SRF I am now on "data-values/data-values" 2.1.1. I guess this is what happens when you run an test instance.

**Comment by kghbln** [comment]
Ouch ;)
