### ISSUE TITLE
PageUpdater/rebuildData.php with missing index select causes performance issue

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#3413]
### Setup and configuration

- SMW version: 2.5.7
- MW version: 1.31.0-alpha
- PHP version: 7.1.20
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.35-MariaDB

### Issue

I am running `php maintenance/rebuildData.php --v --skip-properties` in batches and because it was going slowly I looked at mytop and saw queries like these taking ~4s each:

```sql
SELECT /* SMW\MediaWiki\PageUpdater::doPoolPurge nlaxstro@sanat2... */
page_id FROM `page` WHERE page_title = 'Q5289680' AND (page_touched < '20180907153500')
```

Running explain on it:
```sql
explain SELECT page_id FROM `page` WHERE page_title = 'Q5289680' AND (page_touched < '20180907153500')\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: page
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 6484010
        Extra: Using where
1 row in set (0.01 sec)
```
It is not using any index and scanning ~7 million rows. It is not clear whether the omission of namespace condition is on purpose, but it definitely hurts.

### Stack trace
...

### Steps to reproduce
See the command above.

**Comment by Nikerabbit** [comment]
I am currently testing the following modification (code mostly taken form Translate extension) to the query to use an index.

```patch
index e0f06e8..fa702f0 100644
--- a/src/MediaWiki/PageUpdater.php
+++ b/src/MediaWiki/PageUpdater.php
@@ -283,6 +283,24 @@ class PageUpdater implements LoggerAwareInterface, DeferrableUpdate {
 
                Timer::start( __METHOD__ );
 
+               $byNamespace = [];
+               foreach ( $this->titles as $title ) {
+                       $namespace = $title->getNamespace();
+                       $pagename = $title->getDBkey();
+                       $byNamespace[$namespace][] = $pagename;
+               }
+
+               $conds = [];
+               foreach ( $byNamespace as $namespaces => $pagenames ) {
+                       $cond = [
+                               'page_namespace' => $namespaces,
+                               'page_title' => $pagenames,
+                       ];
+
+                       $conds[] = $this->connection->makeList( $cond, LIST_AND );
+               }
+
+               $titleConds = $this->connection->makeList( $conds, LIST_OR );
                // Required due to postgres and "Error: 22007 ERROR:  invalid input
                // syntax for type timestamp with time zone: "20170408113703""
                $now = $this->connection->timestamp();
@@ -290,7 +308,7 @@ class PageUpdater implements LoggerAwareInterface, DeferrableUpdate {
                        'page',
                        'page_id',
                        [
-                               'page_title' => array_keys( $this->titles ),
+                               $titleConds,
                                'page_touched < ' . $this->connection->addQuotes( $now )
                        ],
                        __METHOD__
```

**Comment by mwjames** [comment]
>It is not using any index and scanning ~7 million rows. It is not clear whether the omission of namespace condition is on purpose, but it definitely hurts.

Nice find.

>I am currently testing the following modification (code mostly taken form Translate extension) to the query to use an index.

Did the applied change had an impact?

**Comment by Nikerabbit** [comment]
Yes it sped up the script a lot. It's now taking less than a week instead of an eternity :)

**Comment by mwjames** [comment]
> It's now taking less than a week instead of an eternity :)

Just so we have a perspective and a context, go I correctly in my assumption that wiki in question has: 

- Content pages | 1,023,217
- Property values (total) | 35,458,214
- Outdated entities (marked for removal) | 1,542,289
- Queries | 1,657,340

**Comment by Nikerabbit** [comment]
I am not sure where you got those numbers and when, but https://nimiarkisto.fi/wiki/Toiminnot:Tilastot shows me:
* Conteng pages | 2 229 654
* Property values (total) | 27 639 972
* Outdated entities (marked for removal) | 0
* Queries | 0

I should also add that I'm running the script on four simultaneous processes and the database is probably under a non-trivial load.

**Comment by mwjames** [comment]
> I am not sure where you got those numbers and when, but https://nimiarkisto.fi/wiki/Toiminnot:Tilastot shows me:

My bad, I looked at with https://wikiapiary.com/wiki/Sanat!.

**Comment by mwjames** [comment]
refs #3424
