### ISSUE TITLE
plain(list) vs. list as default format

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3472]
### Setup and configuration

- SMW version: 3.0
- refs #2488 

### Issue

Extension of the https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3470#issuecomment-423766165 discussion before the 3.0 release to avoid major interruptions of existing users that expect a non-class "list" output.

**Comment by s7eph4n** [comment]
When I used `list` as default I had the standard query in running text in mind (e.g. https://www.semantic-mediawiki.org/wiki/Help:Inline_queries), everything else being special cases (e.g. the SFS input). 
But I am not quite sure anymore how many people actually use the `#ask` function that way. As opposed to e.g. using queries in templates, so that it doesn't matter as much if the `#ask` call is a bit longer and more complex.
In the end I don't mind either as the default. `plainlist` might cause less trouble.

**Comment by kghbln** [comment]
I just upgraded my internal working wiki and the first thing that struck my vision was the change of behavior for the list format in comparison to the "plainlist" format. Thus I had to adapt several templates to specify the "plainlist" format.

So it appears that we should go for "plain(list)" as default to allow for wider backwards compatibility. This is what we had the past 10+ years as "list" format. People liking to apply further styling will naturally adopt "list" I believe.

+1 for "plainlist" as default.

**Comment by toniher** [comment]
Yeah, I have the impression that ```plain(list)``` by default might mean less problems in the end.

**Comment by kghbln** [comment]
@darenwelsh @jamesmontalvo3 @JeroenDeDauw Perhaps you would like to comment too.

**Comment by jamesmontalvo3** [comment]
I don't see a difference between `list` and `plainlist`.

https://www.semantic-mediawiki.org/wiki/User:Jamesmontalvo3/list_v._plainlist

**Comment by kghbln** [comment]
> I don't see a difference between list and plainlist.

Look at the HTML source code. :)

**Comment by jamesmontalvo3** [comment]
Thanks...so SMW 2.5.x has a `<p>` with a bunch of `<a>` tags for both `list` and `plainlist`. SMW 3.0.x has a `<p>`  with a bunch of `<span>` for `list`, and still `<p>` with a bunch of `<a>` for `plainlist`. So `plainlist` appears to maintain the functionality, and seems like the best option for default.

**Comment by JeroenDeDauw** [comment]
+1 for plainlist

**Comment by darenwelsh** [comment]
+1 for plainlist due to backward compatibility. Thanks for noticing my test page and identifying what was causing the issue.

**Comment by s7eph4n** [comment]
> Thanks...so SMW 2.5.x has a `<p>` with a bunch of `<a>` tags for both `list` and `plainlist`. SMW 3.0.x has a `<p>` with a bunch of `<span>` for `list`, and still `<p>` with a bunch of `<a>` for `plainlist`. So `plainlist` appears to maintain the functionality, and seems like the best option for default.

@jamesmontalvo3 The `<p>` tags are MW core's doing, the `<a>` tags should be SMW returning Page type properties. The `list` format should add `<span>` tags on top. See https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/ListResultPrinter/ListResultBuilder.php#L20-L60 for the actual tags used.
(The mechanism is to take the `'*'` configuration and adjust it with the specific configuration.)

Anyway, before I just flip it around, can anyone think of any negative side effects?

**Comment by kghbln** [comment]
> Anyway, before I just flip it around, can anyone think of any negative side effects?

Currently none come to my mind for people who did not specify a result format for their query. The people who explicitly specified "list" will be getting a different format but this would have happened anyways even without setting one or the other as default. Moreover we are doing a major version so changing behavior is acceptable to some extent.

**Comment by mwjames** [comment]
> (The mechanism is to take the `'*'` configuration and adjust it with the
> specific configuration.)
>
> Anyway, before I just flip it around, can anyone think of any negative side
> effects?

I was thinking that `ListResultBuilder` remains untouched with the
only change happen to [0] where instead of `list` you'll return
`plainlist` as default printer. This should resolve the issue we've
seen in #3470 where no format was mentioned, it switched to `list`,
and suddenly the result contained extra HTML elements compared to 2.5.
Of course, if you choose `list` as format then by no means you'll get
the `span` elements.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/params/SMW_ParamFormat.php#L120-L125

**Comment by mwjames** [comment]
> Of course, if you choose `list` as format then by no means you'll get
the `span` elements.

It was meant to be "by all means".

**Comment by jamesmontalvo3** [comment]
Any reason not to do this? And lines 120-122 below can be removed if 124 returns `plainlist`, right? You're not suggesting we flip those around? I'm not sure what `showMode` does.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/67ac7d59f670ad6b70f9f2653d8bd2bbc054ed8b/includes/params/SMW_ParamFormat.php#L120-L124
