### ISSUE TITLE
Named args not evaluating

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticMediaWiki#3488]
### Setup and configuration

Happening on current semantic-mediawiki.org setup.

- SMW version: 3.0.0-rc.1
- MW version: 1.31.1
- PHP version: 7.0.32
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.23

### Issue
Use of `named args` is not causing args to be evaluated. Instead they are just outputting `{{{?The name of the arg}}}`.

### Stack trace
N/A

### Steps to reproduce

With page content of [User:Jamesmontalvo3/Named args](https://www.semantic-mediawiki.org/wiki/User:Jamesmontalvo3/Named_args) as:

```
{{#ask: [[Category:API]]
|?=pagename
|?Has description=Has description
|format=template
|named args=yes
|template=User:Jamesmontalvo3/Named args template
}}
```

And template of [User:Jamesmontalvo3/Named args template](https://www.semantic-mediawiki.org/wiki/User:Jamesmontalvo3/Named_args_template) as:

```
* {{{?pagename}}}: {{{?Has description}}}
```

The page output should look like:

* API module "ask": Allows to do ask queries
* API module "askargs": Allows to do ask queries with as little ask query specific syntax as possible
* API module "browsebyproperty": Allows to fetch information about a property or a list of properties
* ...several more pages...

Instead it's displaying

* {{{?pagename}}}: {{{?Has description}}}
* {{{?pagename}}}: {{{?Has description}}}
* {{{?pagename}}}: {{{?Has description}}}
* ...several more pages...

**Comment by mwjames** [comment]
This relates to #2488 which if I recall correctly states `Removed ? as
prefix for template arguments` [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/migration-guide-3.0.md

**Comment by darenwelsh** [comment]
Subscribing since this has impacts to https://github.com/darenwelsh/SummaryTimeline (and potentially other stuff)

**Comment by jamesmontalvo3** [comment]
I updated [0] the template above to remove the ? and it doesn't appear to have fixed it. Or am I misunderstanding?

[0] https://www.semantic-mediawiki.org/w/index.php?title=User%3AJamesmontalvo3%2FNamed_args_template&type=revision&diff=64637&oldid=64635

**Comment by jamesmontalvo3** [comment]
Must have been a cache thing... Works now. Thanks.

**Comment by kghbln** [comment]
I guess this is sorted out. Indeed there are some syntax changes to congest. However I believe the syntax is now more consistent now which will make things easier in the future.

**Comment by jamesmontalvo3** [comment]
Concur, fixed with a syntax change. And concur, the new syntax is better. 

Should there be a page on smw.o like `[[Upgrading from SMW 2.5.x to 3.0]]`? It'd be good to have a list of considerations like "fix named args" and "change list to plainlist" that points to the relevant documentation pages.

**Comment by mwjames** [comment]
> guide](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/migration-guide-3.0.md)
> for this which when compete may also be embedded in the wiki.

Which has already be added with [0].

If you want to highlight some other requirements or changes, amend the
file in the repo, send a PR and then it should appear on-wiki without
having to maintain two resources.

PS: For larger code blocks use `<pre> ... </pre>` because "```"
doesn't work with the selected markdown parser of the Github
extension.

[0] https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_3.0.0/Migration_guide

**Comment by kghbln** [comment]
> Which has already be added with [0].

Oh, I did this?! :)

> If you want to highlight some other requirements or changes, amend the file in the repo, send a PR and then it should appear on-wiki without having to maintain two resources.

Indeed.

> PS: For larger code blocks use `<pre> ... </pre>` because "```"

Now I also remember. Fixed.
