### ISSUE TITLE
tree input in query forms can not be rendered when another tree input has been selected and submitted before

### ISSUE THREAD

**Issue by frank-fzi** [SemanticMediaWiki/SemanticMediaWiki#3492]
### Setup and configuration

reproducible with:
- SMW version: 3.0.0-rc.1 (and 2.5.6)
- MW version: 1.31.1 (and 1.31.0)
- PHP version: 7.0.30-0+deb9u1 (and 7.2.10)
- Page Forms version: 4.3.1 (and 4.4-alpha)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.1.26-MariaDB-0+deb9u1 (and MySQL 5.5.61)

hint: versions from sandbox.semantic-mediawiki.org (and my configuration in brackets)

### Issue
If multiple tree inputs exist for a query form and the first tree input has been selected and submitted, the other tree input will not be rendered any more and can therefore not be selected.

### Stack trace

https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:RunQuery/MultidimensionalQuery&pfRunQueryFormName=MultidimensionalQuery&MultidimensionalQuery%5B%3FComputerHardware%5D=Central+processing+unit&pf_free_text=&wpRunQuery=Run+query

### Steps to reproduce

* open https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:RunQuery/MultidimensionalQuery
* select any entry in "ComputerHardware"
* hit "Run query"
* result: tree input "Oranism" will not be rendered any more and can therefore not be selected

**Comment by mwjames** [comment]
> If multiple tree inputs exist for a query form and the first tree input has
> been selected and submitted, the other tree input will not be rendered any
> more and can therefore not be selected.

> Page Forms version: 4.3.1 (and 4.4-alpha)
> Special:RunQuery

`Special:RunQuery` is not part of SMW-core hence this issue should be
reported to where  `Special:RunQuery` is part of.

**Comment by kghbln** [comment]
Indeed, this looks very much like it should be reported at Page Forms which moreover also provides the tree input.
