### ISSUE TITLE
Make it possible to link to Special:Ask queries, in the wikilink style

### ISSUE THREAD

**Issue by agharbeia** [SemanticMediaWiki/SemanticMediaWiki#3503]
This is a feature request:

Currently, the page ```Special:Ask``` avails a URI to the query designed through it. However that link is standard HTTP link, i.e external link in Mediawiki terms.

I propose that it would be useful to be able to link to queries using Mediawiki's internal link syntax, with some additions probably. Perhaps something a la:
```[[Special:Ask/encoded_query_parameters]]```

Perhaps with forward-slash/sub-page notation used for passing individual parameters.

It's understandable that the strings of a link to query would still be fairly complex and will have to be created using ```Special:Ask```, rather than manually.

See also the related: #3504

**Comment by agharbeia** [comment]
The ability to pass parameters to some pages of special nature, such as pages in the "Special:" namespace and the "Concept:" space would be greatly useful.

Currently, although some parameters can be passed to some "Special:" pages, this is still not uniform, even for pages that allows it, such as ```Special:PrefixIndex```. And indeed the functionality of passing parameters to Meduiawiki in general is contested, being not a programming platform, etc.

**Comment by kghbln** [comment]
Thanks for suggesting. SMW 3.0.0 comes with compact link support (see https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3017) which in turn allows to do this. See the [example](https://sandbox.semantic-mediawiki.org/wiki/Issue/3507).
