### ISSUE TITLE
Get results of inline query more 10000 rows

### ISSUE THREAD

**Issue by dfhdfhdf** [SemanticMediaWiki/SemanticMediaWiki#3508]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.28.0
- PHP version: 7.0.27-0
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.1.26

I have more than 300000 pages in category Plant species.
I want get the list of this pages by inline query:

`{{#ask: [[Category:Plant species]]
 |format=list
 |limit=500000
 |link=all
 |headers=show
}}`

But I get max 10000 results.

In LocalSettings.php:
```
$smwgQMaxInlineLimit = 1000000;
$smwgQMaxLimit = 1000000;
```
How I get **all** results?

**Comment by kghbln** [comment]
Try changing the [`$smwgQUpperbound`](https://www.semantic-mediawiki.org/wiki/Help:$smwgQUpperbound) configuration parameter.

**Comment by dfhdfhdf** [comment]
Tnx, this help for me!

**Comment by kghbln** [comment]
> Tnx, this help for me!

Great!
