### ISSUE TITLE
Error on page causes "rebuildData.php" to not update startidfile

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticMediaWiki#3509]
### Setup and configuration

- SMW version: 3.0.0-rc.2
- MW version: 1.31.1
- PHP version: 7.0.32 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 5.5.60-MariaDB

### Issue
Looped partial refreshing with `rebuildData.php` is not updating `startidfile` after error

### Stack trace
N/A

### Steps to reproduce

I'm running `rebuildData.php` in chunks with a script like the following (I've left out the top and bottom of the script and focused on the important parts).

```bash
dependent_option="-f"

while [ "$start_id" != "-1" ]; do

	php "/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php" \
	-d 5 -v $dependent_option --ignore-exceptions \
	--debug \
	--report-runtime \
	--startidfile "$start_id_file" -n 1000 \
	--exception-log="$exception_log" \
	>> "$out_log" 2>&1

	# after first run, don't rebuild structure, but do skip rebuilding properties
	dependent_option="--skip-properties"

	start_id=$(cat "$start_id_file")

	echo "next pass start id = $start_id"

done
```

This has always worked fine, but I started getting this problem when running SMW 3.0.0-rc.2. I'm not sure if it's related to upgrading from 2.5.x-->3.0, or if it's just that someone started doing something bad on one of the pages. The output below is from the `rebuildData.php` script running above. It's updating pages, then dies with an error message, but restarts the `rebuildData.php` script without updating `startidfile`. Thus, it loops through this endlessly. I inserted a note into the output below to indicate what appears to be happening.

```
   ... updating 660       [Some_page#0#_QUERYc2e5078bf826510d4a348ae2fdcafb81]
   ... updating 661*      [File:Some_file.png]
   ... updating 661       [Some_page#0#_QUERY5fca2459ecc1adcd4e00262693422648]
   ... updating 662*      [Some_device_page]
   ... updating 662       [Some_page#0#_QUERYcc82f577ded24f541f8c67b8d9cd0782]
   ... updating 663*      [Template:Hardware]
   ... updating 663       [Some_page#0#_QUERY654ac7adc8f11a793dc7d15f61e80c93]
   ... updating 664*      [Form:Hardware]
   ... updating 664       [Some_page#0#_QUERY1532511adc19a87b06920917c1af53c2]
Error: first argument to #set_internal cannot be blank.

Note: while loop restarts here. You're not seeing the "next pass start id = $start_id"
      in this log, but it is happening within another log.

Long-running scripts may cause memory leaks, if a deteriorating
rebuild process is detected (after many pages, typically more
than 10000), please abort with CTRL-C and resume this script
at the last processed ID using the parameter -s. Continue this
until all pages have been refreshed.

...rebuildData.php loops forever...
```

Fixing the issue with `#set_internal`[1] on that page allows `rebuildData.php` to complete. However, I think `rebuildData.php` should fail more gracefully, perhaps incrementing the `startidfile` before each page in case there's an issue. Also nothing appears to have been reported in the `exception-log`.

[1] I realize `#set_internal` is not required anymore for SMW, but we still have it for legacy issues. We discourage people from making new things with it, but as long as it's still present people will use it.

**Comment by kghbln** [comment]
Thanks a lot for reporting. More graceful failures are always preferable.

I think that `#suboject`fails more gracefully in such a situation. Moreover it offers more protection against wrong content being added and in the meantime more features as well. So yes, migrating to it is recommended basically since SMW 1.9.0. I added an info on the extension's page on s-mw.o informing about this recommendation.

**Comment by jamesmontalvo3** [comment]
I'm getting the same infinite loop problem on another page with no parser functions. So it's not limited to #set_internal. It has about 60 characters of simple content. No idea what the failure is yet. Will report when I have more info.

**Comment by jamesmontalvo3** [comment]
I believe SemanticMediaWiki/SemanticResultFormats#438 means that SRF just started requiring `wfLoadExtnsion` recently. The following observation assumes that is the case.

I reported this issue because some errors were causing `rebuildData.php` to fail in an infinite loop. That was on an earlier version of SRF that did not require `wfLoadExtension`. SRF then started to require `wfLoadExtension`, and `rebuildData.php` started to work. I thought that some issue had been fixed in SMW. When I realized SRF was not showing up in Special:Version, I started using `wfLoadExtension`. Now `rebuildData.php` fails with the infinite loop on certain pages. Unfortunately these pages are not showing obvious errors, so they're hard to resolve.

**Comment by Nikerabbit** [comment]
Just noting that 128M is not much RAM for MediaWiki these days, especially for long running maintenance scripts it is actually very little.

**Comment by kghbln** [comment]
@jamesmontalvo3 Thanks for digging into this further.

Indeed 128M is rather tight though I must admit that I have rarely seen this script using as much. Anyways a loop safeguard of some kind for vulnerable result formats will be cool. Running the script verbosely already tells about the transgressing object. Moreover we have the query lookup letting us have a peep too.

**Comment by jamesmontalvo3** [comment]
Sure, 128MB as defined in the limit on the 500 error may be tight. I'll consider bumping that up. However, I was talking about the usages mentioned in `dmesg`:

```
[262790.805146] Killed process 13556 (php) total-vm:11577404kB, anon-rss:7111332kB, file-rss:696kB, shmem-rss:56048kB
```

I'm not incredibly familiar with what this means, beyond just having googled what to do when you get a mysterious "killed" message with no other explanation after a script terminates, but those values are 11.6  GB (more than system RAM, less then RAM+swap), 7.1 GB (system ram 8 GB), 696kb (clearly this isn't the limit), 56 MB (less than the 128MB limit). Perhaps I read this wrong and the GB values are not the offending ones, but it certainly seemed like it was eating the entire system memory when running.

> Running the script verbosely already tells about the transgressing object. 

I was running it verbosely. It tells you about the transgressing object after it's done, which never happens in this case.

**Comment by mwjames** [comment]
>When going to the page, I got a 500 error:
> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /opt/htdocs/mediawiki/extensions/SemanticResultFormats/formats/tree/TreeNodeVisitor.php on line 52

```
{{#ask: [[Category:Lesson Plan]][[Prerequisite::+]]
| format=tree
| parent=Prerequisite
| limit=5000
}}
```

Given the involvement of `TreeNodeVisitor` and `format=tree`, @s7eph4n would mind you helping with dissecting the issue and answer the question in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3509#issuecomment-431343165.
