### ISSUE TITLE
RFE: allow [Alst+Shift+S] shortcut to launch semantic-search form at Special:Ask  with keyboard only

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3513]
- SMW version: 2.5.8

## Problem
I don't know of a way to launch searches only with keyboard.  Having to use the mouse when building queries just for clicking the submit button is not user friendly for advanced users.

## Suggested enhancement
Bind `accesskey="s"` to the "Find results" submit button, so **[Alt+Shift+S]** runs the query (tested in Chrome only).

Note: "S" may mean "search", and is the same as the "Save" shortcut on mediawiki edit boxes.

## Workaround:
I have put this in my `mediaWiki:Common.js`:
```javascript
$(function () {
	// Allow to semantic-search with [Alt+Shift+S] in Special:Ask form.
	//
	$('input.smw-ask-action-btn.smw-ask-action-btn-dblue').each(function() {
		$(this).attr('accesskey', 's');
	});
});
```

**Comment by kghbln** [comment]
Thanks a lot for suggesting this enhancement and also showing a way to do this. Indeed "s" is [already taken](https://www.mediawiki.org/wiki/Manual:Interface/Access_keys) by MW core. However we are talking about a special page here were this key should not be available.

**Comment by ankostis** [comment]
After having experimented for a week with **[Alt+Shift+S]**,
i can tell that finger-RAM jupms to **[Alt+Shift+P]** (preview) because running queries feels like revieing a page while editing, a much less intrusive action than **S** (for saving), which you press only rarely.

So eventually i've changed `accesskey` it to **P**. 
(from "perform search"?)

**Comment by ankostis** [comment]
Fallback to **[Ctrl+S]**; firefox open private browsing.

**Comment by ankostis** [comment]
Closed by mistake.
