### ISSUE TITLE
`#info` not producing tooltips in RTL MW UIs

### ISSUE THREAD

**Issue by agharbeia** [SemanticMediaWiki/SemanticMediaWiki#3514]
### Setup and configuration

- SMW version: 2.5.5
- MW version: 1.30.0
- PHP version: 5.6.38-0+deb8u1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 10.0.36-MariaDB-0+deb8u1

### Issue
The parser function #info produces an icon, but no tool-tip appears, neither when hovering nor when clicking on the info icon.

The produced HTML as per Special:ExpandTemplates:
```
<span class="smw-highlighter" data-type="5" data-state="persistent" data-title="معلومات" title="This is tooltip text. It should be in Arabic but I&#39;m reproducing an issue for a bug report."><span class="smwtticon info"></span><div class="smwttcontent">This is tooltip text. It should be in Arabic but I'm reproducing an issue for a bug report.</div></span>
```

However, what is actually in the page, as per Firefox inspector:
```
<span class="smw-highlighter smwttpersist" data-type="5" data-state="persistent" data-title="معلومات" data-hasqtip="0" aria-describedby="qtip-0"><span class="smwtticon info"></span></span>
```

The text gets sanitized somewhere!

**Comment by kghbln** [comment]
Thanks for reporting the issue. Any chance to get this on https://sandbox.semantic-mediawiki.org/ since I admittedly do not handle Arabic interfaces well? Moreover for 3.0.0 some work was done on this parser function.

**Comment by agharbeia** [comment]
Thanks, Karsten, for your reply.

I did some more testing and found out that either in [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Judith_Butler) or my wiki, when the wiki language is one written in non-Latin script, such as Arabic, Farsi, or Hebrew, the tooltip doesn't appear. But when the language is written in another script, it behaves as expected.

Note that the issue may in fact be related to RTL scripts, since Syriac didn't work while Amharic worked. But I haven't tested that extensively.

Another note which I think is relevant, is that while the page is still loading but haven't finished loading yet, the tip layer appears when the mouse hovers on the icon. However at that time the layer appears in black, i.e. unstyled in the style that is applied later on after the page has finished loading. (Merits of a slower internet connection, you get to say page genesis)
I hope this helps.

**Comment by kghbln** [comment]
Thanks a lot of recreating the issue on sandbox and elaborate on your findings. I had hoped that it might work on SMW 3.0.0 but not absolutely unexpected this version has issues with RTL, too. I do not think that it ever worked in earlier versions of SMW either.

**Comment by Nikerabbit** [comment]
Another thing that caught my eye is that you have a `div` inside a `span`. This will get mangled in some way by Tidy or Remex (depending on MediaWiki configuration and version).

**Comment by agharbeia** [comment]
The issue still manifests in the example you created, Karsten, when I
switch the Sandbox wiki UI language to one that is RTL.

To clarify, this is what I meant with my description of the tests I did
with the different languages, not the language of the string of #info
itself. Sorry, I wasn't clear enough.

**Comment by agharbeia** [comment]
Thanks, Niklas!
I need to take a look at the HTML markup generated by the template
indeed. Mixing HTML and MediaWiki can be problematic, for this reason.

**Comment by kghbln** [comment]
> The issue still manifests in the example you created, Karsten, when I switch the Sandbox wiki UI language to one that is RTL.

Affirmative, there is an issue. Admittedly I do not deal with RTL languages at all in my personal life. Using respective wikis is hardly to not possible too and I am not even talking about trying to edit. I guess this explains my ignorance here. Anyhow I added a comment to the page making it clear over there what needs to be done to recreate the issue. We standardly test against Japanese but this is obviously not an RTL. :|

**Comment by agharbeia** [comment]
You might want to take a look at this some time, @maysara

**Comment by kghbln** [comment]
> This isn't bug in or by SMW and can ultimately only be resolved by relying on a more modern tooltip facilitator such as tippyjs [1] which would require some effort which makes it an enhancement.

I had hoped that there will be an easier way to get this going for RTL users but reality is often even more complex than expected.
