### ISSUE TITLE
Special:Ask fails with Records field-properties having `Coresponds to::` units on them

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3517]
### Setup
- Core & extensions download & install date: Sept 2018
- MW version: 1.3.10
- DB (MySQL etc.): mysql
- PHP version: 7.2.10
- SMW version: 2.5.8
- SRF version: 2.5.6
- Browsers and versions (if applicable): Chrome latest

### Issue
When: 
- semantically-searching pages that contain a `[[Has type:: Record || Reference]]` property (e.g `Ref prop`), AND 
- that `Ref prop` has as the 1st  `[[Has fields::]]` property one with `[[Has type::Quantity]]` (e.g. `Field prop`), WHICH
- has at least one unit `[[Corresponds to::]]`, AND
- the query-display results specify that field with the construct `?Ref prop.Field prop`

THEN the search http-request fails, and you get this this stack printed (e.g. inside the `Semantic:Ask` page):

```
[2adc3b5803483af8961ddae0] /wiki/index.php?title=Special%3AAsk&q=%5B%5BCategory%3AEntities%5D%5D%5B%5BFD009%5D%5D&po=%3FRef prop.Field prop%3DLLL%0D%0A&eq=yes&p%5Bformat%5D=datatables&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Btheme%5D=bootstrap&eq=yes 
TypeError from line 162 of /var/lib/wiki/extensions/SemanticMediaWiki/src/DataValueFactory.php: 
Argument 2 passed to SMW\DataValueFactory::newDataValueByItem() must be an instance of SMW\DIProperty or null, 
instance of SMWDIBlob given, called in /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php on line 119

Backtrace:

#0 /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(119): SMW\DataValueFactory->newDataValueByItem(SMWDINumber, SMWDIBlob)
#1 /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(185): SMW\Serializers\QueryResultSerializer::getSerialization(SMWDINumber, SMW\Query\PrintRequest)
#2 /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(45): SMW\Serializers\QueryResultSerializer::getSerializedQueryResult(SMWQueryResult)
#3 /var/lib/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_QueryResult.php(319): SMW\Serializers\QueryResultSerializer->serialize(SMWQueryResult)
#4 /var/lib/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_QueryResult.php(346): SMWQueryResult->serializeToArray()
#5 /var/lib/wiki/extensions/SemanticMediaWiki/includes/queryprinters/RawResultPrinter.php(123): SMWQueryResult->toArray()
#6 /var/lib/wiki/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php(261): SMW\RawResultPrinter->getResultText(SMWQueryResult, integer)
#7 /var/lib/wiki/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php(226): SMW\ResultPrinter->buildResult(SMWQueryResult)
#8 /var/lib/wiki/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(372): SMW\ResultPrinter->getResult(SMWQueryResult, array, integer)
#9 /var/lib/wiki/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(103): SMWAskPage->makeHTMLResult()
#10 /var/lib/wiki/includes/specialpage/SpecialPage.php(522): SMWAskPage->execute(NULL)
#11 /var/lib/wiki/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#12 /var/lib/wiki/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#13 /var/lib/wiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#14 /var/lib/wiki/includes/MediaWiki.php(524): MediaWiki->main()
#15 /var/lib/wiki/index.php(42): MediaWiki->run()
#16 {main}
```
### Notes: 
- When the reference property does not have [[corresponds to]] "units", search works without crashes.
- The manual refers to a known limitation about [`[[Property:Display units]]` special property](https://www.semantic-mediawiki.org/wiki/Help:Type_Record#Limitations).  But the presence of his annotation on the filed-property does not cause any such problem.  So maybe for the time being, add also the `[[Property:Corresponds to]]` property into the "limitations"?

#### `Property:Ref prop`:
```mediawiki
* [[Has type::Reference]]
* [[Has fields::Field prop;other prop]]
```
#### `Property:Field prop`:
```mediawiki
[[Has type::Quantity]]
[[Corresponds to::1 km]]
```
#### `Foo page`:
```mediawiki
[[Good prop::ok]]
[[Ref prop::123;unsearchable in datatable]]
```
#### #Ask queries
(edit: Had forgotten to compete the queries)
```wikitext
{{#ask: [[Ref2 prop::;~B*]]
 |?Ref prop
 |?Ref prop.field prop=Field prop
 |format=DataTables
 |link=all
 |headers=show
 |searchlabel=... further results
 |class=sortable wikitable smwtable
}}

{{#ask: [[Base1 prop::;~B*]]
 |?Ref2 prop
 |?Ref2 prop.field prop=Field prop
 |?Ref2 prop.other prop=Other prop
 |format=DataTables
 |link=all
 |headers=show
 |searchlabel=... further results
 |class=sortable wikitable smwtable
}}

```
---
Note: the error is also described in detail in SemanticMediaWiki/SemanticResultFormats#437.

**Comment by kghbln** [comment]
Thanks for digging into this issue. I will close the corresponding issue at SRF since it appears to originate in SMW.

**Comment by kghbln** [comment]
You are obviously the first one trying to implement the described setup since the datatype reference was introduced in March 2017. Thus I do not see this issue as a blocker for the 3.0.0 release of SMW.

**Comment by ankostis** [comment]
The issue happens also with Record datatype.

**Comment by kghbln** [comment]
> The issue happens also with Record datatype.

Yeah, were are very similar in concept.

**Comment by ankostis** [comment]
Ola kala then :+1: :

**Comment by mwjames** [comment]
> Content of the issue should be recreated on the sandbox.

Once created, the ticket can be closed.

**Comment by ankostis** [comment]
Is there something here for me to do?

**Comment by kghbln** [comment]
> Is there something here for me to do?

Yeah, recreating the issue on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Main_Page) will be great.

**Comment by kghbln** [comment]
> Yeah, recreating the issue on sandbox will be great.

I ended up doing it myself. Anyways the field test shows that special page "Ask" no longer errors out.
