### ISSUE TITLE
sanitization of `Homepage` url strips away the colon, forming incorrect url

### ISSUE THREAD

**Issue by ghost** [SemanticMediaWiki/SemanticMediaWiki#352]
Hi.

This is best seen here: http://semanticweb.org/wiki/Fluent_Editor
on the right side, the shown url is correct as 
`http://www.cognitum.eu/semantics/FluentEditor2/` 
but clicking(or hovering mouse above) it shows the actual url to be:
`http//www.cognitum.eu/semantics/FluentEditor2/` 
(note the missing colon `:`) 
and thus, in firefox, loads this page: 
`http://www.http.com//www.cognitum.eu/semantics/FluentEditor2/`

Editing that page and viewing its source shows the url is correct:
```wiki
{{Tool
|Name=Fluent Editor 2
|Homepage=http://www.cognitum.eu/semantics/FluentEditor2/
|Status=mature
|Logo=FE2_Logo.png
|Version=2.2.2
|Release=2013/03/20
|License=Free for non-commercial usage, Paid commercial license
|Language=.NET
|Affiliation=Cognitum
|Download=http://www.cognitum.eu/Semantics/FluentEditor2/Download.aspx
}}
```

All the other urls(in this group) seem to be unaffected.
Editing the page and looking at it in Preview is a good way to confirm this bug is still present. But I don't know which(possibly outdated) version of SMW they are using.

It seems that some pages ie. http://semanticweb.org/wiki/Bigdata
are using the workaround of not including the `http://` part and this way completely avoid this bug.

Hope I reported this in the right place, semanticweb.org site seem to be outdated, following the old instructions to report bugs(on bugzilla) was a dead end.

Thanks for your time.

**Comment by mwjames** [comment]
The issue could not be confirmed with the current 2.3-alpha. Feel free to re-open this issue once it can be reproduced with a supported release.
