### ISSUE TITLE
RFE: add property validation for records/references to forbid multiple [[Has fields::]] assignments

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3522]
## Setup and configuration
- Core & extensions download & install date: Sept 2018
- MW version: 1.3.10
- DB (MySQL etc.): mysql
- SMW version: 2.5.8

## Issue
Having descriptive error messages when violating property definitions significantly improve the usability of this extension.  For instance, a record/reference property without field declarations present an error-bar with _`smw-property-req-violation-missing-fields:` Some ref prop" is missing declaration details..._

It would be nice to have a similar message if there are multiple field annotations on a _Record/Reference_ property, like:
```wikitext
[[Has fields:Field 1]]
[[Has fields:Field 2]]
```
instead of this, which is the correct:
```wikitext
[[Has fields:Field 1;Field 2]]
```

In my case the error was buried in some mistaken template, and after fixing it, i could only tell the difference from the property's factbox, where in the bad case there i a final "and" in the list of csv-values for the `[[Has field]]`.

### Side-effects
The "bad" record-property continued to behave like a regular one, receiving only the 1st field value, while `#ask` didn't work at all on that reference, but also generic searches on pages using the bad-property were also "broken" (e.g. {{#ask: `[[<pagename>]]}}` didn't work!).

### Suggest for Enhancement
Since the whole wiki is suffering because of this "silent" user-mistake, if possible, provide a validation in `src/PropertySpecificationReqExaminer.php`  to warn the user of `[[Has field]]` abuse.

**Comment by kghbln** [comment]
Thanks a lot for suggesting this enhancement.

**Comment by ankostis** [comment]
My deepest gratitude for the new release !

**Comment by mwjames** [comment]
>for records/references to forbid multiple [[Has fields::]] assignments

We won't "forbid" or ban those multiple assignments (because we don't know which one is the correct one) but we'll inform the user about it (see #3735).
