### ISSUE TITLE
Using the "further results" link when the query contains `headers=plain` with a piped link in a header breaks the output

### ISSUE THREAD

**Issue by Dinoguy1000** [SemanticMediaWiki/SemanticMediaWiki#3523]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.30.0
- PHP version: 7.1.22-1+ubuntu16.04.1+deb.sury.org+1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.1.31-MariaDB-1~xenial

(see also [Special:Version](https://yugipedia.com/wiki/Special:Version))

### Issue
After upgraing from SMW 2.5.6 to SMW 3.0.0, we noticed that viewing a "further results" link on some queries started producing `The part "..." of the query was not understood.` notices. After a bit of investigation, I narrowed the cause to the use of piped links in table headers with the `headers=plain` option set: the header content starting from the pipe is truncated from the header, and the content after the pipe is appended to the end of the query. See [sandbox](https://yugipedia.com/index.php?title=User:Dinoguy1000/sandbox/SMW&oldid=3962993) and [resulting Special:Ask page](https://yugipedia.com/wiki/Special:Ask/cl:YzplUttuwjAM_R14CGFANalSH7g-7KKhwQ-krUsjkhQ56RB_P7s3BpOqxD7n-BZXRCsRrdZGeS9m05c4_ioKnWllRLThbzYVjWKJWekBNfg43gMWFVp1-afao7YKb-SH2wVY6fLa1JaAz8r5ANgGSDHfbd3JaF8S5ZQFukZGuzPkYybfKLkDDx3L0GNuRg6QVS5_xJYhoE7rAEnXd-_fCx9J2rFs3olDUMiv4CnEnTrJB_zAMOZOzNcp8rhsblvFt3Lne5I_Ix8yZfpKz7B4Xbf3ELg8vj_XZmjgN9vdM89Qy1ulnVEpmKRpbiONtjqwE8mqKDyEJJLN0kISVGpAlqByQM-Si6Fo6UHRjockk8mEzqLGUAJPjOBrE_h5RosFnbZCGMuMfxyW-wqbvGRe9Vn3trfX3swU5tQZ7Tz8Ag).

#### Inline
```
{{#ask:
 [[Archseries::Performapal]]
 [[Primary type::Pendulum Monster]]
 [[Class 1::Official]]
 |?Pendulum Scale=[[Pendulum Scale|Scale]] <!--transgressing syntax -->
 |headers=plain
 |limit=5
}}
```
#### Special page
```
{{#ask: [[Archseries::Performapal]] [[Primary type::Pendulum Monster]] [[Class 1::Official]]Scale]]
 |?Pendulum Scale=[[Pendulum Scale
 |format=table
 |limit=5
 |offset=5
 |sort=
 |order=asc
 |headers=plain
 |mainlabel=
}}
```

**Comment by kghbln** [comment]
Thanks a lot for reporting. Isn't this something where you would rather use the "plainlist" format formerly known as "template" format?

**Comment by Dinoguy1000** [comment]
`format=plainlist` appears to suffer from this issue as well; see [sandbox](https://yugipedia.com/index.php?title=User:Dinoguy1000/sandbox/SMW&oldid=3963121) and [Special:Ask](https://yugipedia.com/wiki/Special:Ask/cl:Yzpdjt0KgzAMhZ-odD-UgdCL6djdmLAnyDTFQKqS1AvfflY3GEIgOYfvJDGuNK68StMpCqEWRY0SBokwAht3y3U6mJWqhSLIvOg0j5jJvp14iovxGHpNKLtAxaC6qGNRPEOghn4rrTnf_9KvBhj998jONpdq61swAvUMb2RvmSIl7-wQgmIe1reTHzkzpMl2CC2Kbs4H) (of course, if you meant something different with your suggestion, please correct me =) ).

We completed the update to 3.0.0 literally just a few hours ago, so we haven't had much time to start making use of new features or to change functionality/behavior where breakages didn't occur (though I do intend to convert our uses of `format=template` to `format=plainlist`).

**Comment by kghbln** [comment]
No, this will indeed not work either. I was thinking of [this](https://www.semantic-mediawiki.org/wiki/Help:Use_the_template_format_to_create_tabular_output) which lets you define arbitrary headers.

> We completed the update to 3.0.0 literally just a few hours ago

Take your time. Rome was not build in a day either. :)

**Comment by Dinoguy1000** [comment]
Aah, right, building a table by using `template`. We do that in places, though (as you might expect) with `format=template` instead of other result formats (and without use of `introtemplate`/`outrotemplate`, by just having the query surrounded with the desired table header/footer). This will be something I'll be playing with in the future, to be sure.

**Comment by kghbln** [comment]
> furthermore an example should be created on the sandbox to confirm that #3584 resolves the issue

https://sandbox.semantic-mediawiki.org/wiki/Issue/3523
