### ISSUE TITLE
Issues when installing SMW 3.0.0

### ISSUE THREAD

**Issue by sochin67** [SemanticMediaWiki/SemanticMediaWiki#3525]
Hello everyone,
when I tried to install SMW 3.0.0 via Composer I receive the following error message:
 
++++++++++++++++++++++++++++++++++++++++++++++++++++
php composer.phar require mediawiki/semantic-media-wiki:~3.0.0 --update-with-dependencies

 

./composer.json has been updated

> ComposerHookHandler::onPreUpdate

Dependency "psr/log" is also a root requirement, but is not explicitly whitelisted. Ignoring.

Dependency "psr/log" is also a root requirement, but is not explicitly whitelisted. Ignoring.

Dependency "wikimedia/cdb" is also a root requirement, but is not explicitly whitelisted. Ignoring.

Loading composer repositories with package information Updating dependencies (including require-dev) Your requirements could not be resolved to an installable set of packages.

 

  Problem 1

    - mediawiki/semantic-result-formats 2.5.6 requires mediawiki/semantic-media-wiki ~2.1 -> satisfiable by mediawiki/semantic-media-wiki[2.1.0, 2.1.0-RC1, 2.1.1, 2.1.2, 2.1.3, 2.1.x-dev, 2.2.0, 2.2.0-RC1, 2.2.1, 2.2.2, 2.2.3, 2.2.x-dev, 2.3.0, 2.3.0-RC1, 2.3.1, 2.3.x-dev, 2.4.0, 2.4.0-RC1, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.x-dev, 2.5.0, 2.5.0-rc.1, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.x-dev] but these conflict with your requirements or minimum-stability.

    - mediawiki/semantic-result-formats 2.5.6 requires mediawiki/semantic-media-wiki ~2.1 -> satisfiable by mediawiki/semantic-media-wiki[2.1.0, 2.1.0-RC1, 2.1.1, 2.1.2, 2.1.3, 2.1.x-dev, 2.2.0, 2.2.0-RC1, 2.2.1, 2.2.2, 2.2.3, 2.2.x-dev, 2.3.0, 2.3.0-RC1, 2.3.1, 2.3.x-dev, 2.4.0, 2.4.0-RC1, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.x-dev, 2.5.0, 2.5.0-rc.1, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.x-dev] but these conflict with your requirements or minimum-stability.

    - mediawiki/semantic-result-formats 2.5.6 requires mediawiki/semantic-media-wiki ~2.1 -> satisfiable by mediawiki/semantic-media-wiki[2.1.0, 2.1.0-RC1, 2.1.1, 2.1.2, 2.1.3, 2.1.x-dev, 2.2.0, 2.2.0-RC1, 2.2.1, 2.2.2, 2.2.3, 2.2.x-dev, 2.3.0, 2.3.0-RC1, 2.3.1, 2.3.x-dev, 2.4.0, 2.4.0-RC1, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.x-dev, 2.5.0, 2.5.0-rc.1, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.x-dev] but these conflict with your requirements or minimum-stability.

    - Installation request for mediawiki/semantic-result-formats (locked at 2.5.6, required as 2.*) -> satisfiable by mediawiki/semantic-result-formats[2.5.6].

 

Installation failed, reverting ./composer.json to its original content.

++++++++++++++++++++++++++++++++++++++++++++++++++++
 
My version info is as follows:
 
MediaWiki: 1.31.0
PHP: 7.1.19-nmm1 (fpm-fcgi)
MySQL: 5.7.21-nmm1-log
ICU: 55.1
 
Semantic Compound Queries: 1.2.0
Semantic MediaWiki: 2.5.8
Semantic Result Formats: 2.5.6
 
I'm struggling to see any "requirements or minimum-stability" problems with my installation.
Is anybody able to help?
 
Many thanks!
Regards,
Tom

**Comment by jamesmontalvo3** [comment]
Looks like you're specifying a `2.x` version of SemanticResultFormats. You need to specify `3.x`. Your composer.json should look something like:

```json
{
  "require": {
    "mediawiki/semantic-compound-queries": "1.2.0",
    "mediawiki/semantic-media-wiki": "3.0.0",
    "mediawiki/semantic-result-formats": "3.0.0"
  }
}
```

**Comment by kghbln** [comment]
Try to directly change your "composer.local.json" file to something like shown on [this page](https://www.semantic-mediawiki.org/wiki/Help:Installation/Example_%22composer.local.json%22_file). Then do the `composer update`.

**Comment by sochin67** [comment]
Hi,
After fixing some „Your composer.lock file is not up to date“ issues I managed to do the update with the help of your instructions above.
Many thanks for this!!

**Comment by kghbln** [comment]
Great to read that it worked out now.
