### ISSUE TITLE
SEP issue with SMW query results in a parser function

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticMediaWiki#3526]
### Setup and configuration
- SMW version: 2.5.6
- MW version: 1.30.0 (830bb58)
- PHP version: 5.6.37 (apache2handler)
- DB system and version: 5.5.60-MariaDB

### Issue
I'm trying to use SMW SRF to return the results of a ASK statement as lines of unprocessed text within some other parser call (say Mermaid [1])

Here is an example of the parser function result I'm trying to emulate:

```
{{#mermaid:gantt
  Event1: myevent1, 2018/10/18, 1d
  Event2: myevent2, 2018/10/20, 1d
}}
```

Here is the way I am coding it:

```
{{#mermaid:gantt
  {{#ask:  [[Category:Foo]]  |?has name  |?has date |link=none
     |format=template
     |template=Foo-item
     |import-annotation=true
     |sep=\n
  }}
}}
```

It works for a single result but not for multiple results. 

Here is what the html source looks like:

`<div id="ext-mermaid-57345bc89a90cf8bf" class="ext-mermaid" data-mermaid="&#123;&quot;content&quot;:&quot;gantt\n Event1: myevent1, 2018\/10\/18, 1d\\n Event2: myevent2, 2018\/10\/20, 1d&quot;,&quot;config&quot;:&#123;&quot;theme&quot;:&quot;forest&quot;&#125;&#125;"><div class="mermaid-dots"></div></div>`

By inspecting the html source of the rendered page, I can see that the problem is that the "`\`" in the SEP of the results is ultimately getting printed as "`\\n`" in the final HTML. 

Does anyone know a way that I can avoid having the output writer add the extra "`\`" to the "`\n`"?

Ref: https://www.mediawiki.org/wiki/Topic:Umu0cct3j3thj1nu 

Thank you!
-Rich

### Stack trace
```
n/a
```

### Steps to reproduce
provided as deemed neccessary

**Comment by kghbln** [comment]
I believe we have several dupes of this issue. I guess this is the main issue to track mermaids. :) https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/364
