### ISSUE TITLE
Annotations do not get updated

### ISSUE THREAD

**Issue by naramoksu** [SemanticMediaWiki/SemanticMediaWiki#3527]
### Setup and configuration

- SMW version: 3.0 
- Semantic Compound Queries:	1.2.0
- Semantic Result Formats:	2.5.0
- MW version: 1.31.0
- PHP version: 7.0.30 (fpm-fcgi)
- DB system (MySQL) and version: 5.7.22

### Issue
I followed the upgrade procedure. update SMW 3.0 with composer --> ran update.php
The mediawiki special:version showed me it have smw 3.0 and my mediawiki seems working well. 

I edited a document, made a internal link and added properties, but the the property of document is not updated. 

I found Special:Ask does not work. It was a problem caused wrong Semantic result format version. It was fixed. 

I thought it is fixed and closed this issue. but the property is not updated yet. 

Please advice me if there is a variable to check. 

Thanks in advance.

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
Placeholder for the stack trace or code!

```

### Steps to reproduce
_It is recommend to use the [sandbox](https://sandbox.semantic-mediawiki.org) to demonstrate the observed issue, otherwise provide us with a simple reproducible use case._

**Comment by naramoksu** [comment]
I missed semantic result format should be updated 3.0

**Comment by kghbln** [comment]
Glad it worked out for you. :)

**Comment by naramoksu** [comment]
I fixed special:ask problem. Property update is not working. Please help me to find a reason.

**Comment by kghbln** [comment]
> Property update is not working. Please help me to find a reason.

I am not sure what you mean here. You have a set of property values stored to a page and when adding more of them they do not get stored? With document you a referring to a wiki page? Did you rebuild your data with "rebuildData.php"?

**Comment by naramoksu** [comment]
Thanks your comments.
 
I already rebuildData.php.

For example, Before I updated smw 3.0, if I insert a property([[have something with::B]]) to a page A then I can find page B have incomming property from page A. I'm checked this with a "browse properties"

After SMW 3.0 these kind of page modification is not updated.

**Comment by naramoksu** [comment]
I found smw 3.0 does not updated if there is extension cargo. After I disable cargo, smw properties updated well.

**Comment by jamesmontalvo3** [comment]
I'm running MW 1.31.1, SMW 3.0.0, and Cargo 1.7 (3be7c40) and have not experienced issues with SMW properties updating.

**Comment by naramoksu** [comment]
I tested again and confirmed that smw does not updated with Cargo. I used Cargo 1.7. Maybe it depend on some other extensions.

**Comment by kghbln** [comment]
I was away recently. First I figured that it might have something to do with the job queue but now it appears to me that you have not set `$smwgEnabledCompatibilityMode = true;` after installing Cargo.
