### ISSUE TITLE
Subproperty not inheriting parent property type

### ISSUE THREAD

**Issue by brettz9** [SemanticMediaWiki/SemanticMediaWiki#3528]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.0.32-0ubuntu0.16.04.1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.24-0ubuntu0.16.04.1

### Issue

When adding `[[Subproperty of::...]]` to a property page and based on another page with `[[Has type::Number]]`, I would have expected the child property to inherit the type info from the parent. However, in order to get the property to avoid showing up as a link, as well as to be available in queries, I needed to add `[[Has type::Number]]` to the subproperty page as well.

If this is not a bug, I'd like to request it as a feature.

Thanks for the really awesome tool!

**Comment by kghbln** [comment]
> If this is not a bug, I'd like to request it as a feature.

I do not think this is a bug but indeed an enhancement which makes sense to me, too. Thanks for suggesting.

**Comment by mwjames** [comment]
> If this is not a bug, I'd like to request it as a feature.

It as a feature. See #3733

> "invalid" message when an inherited child property has incompatible type with regards to its parent

See #3733

>  case when the parent is Page, and the child has no Type annotation at all; one would expect SMW to behave as if the child is Page, but that is not the case

A property (independent of being parent or sub) without a type annotation will automatically be of a `Page` (`wpg`) type according to the `smwgPDefaultType` setting [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L850-L858
