### ISSUE TITLE
Subcategory of

### ISSUE THREAD

**Issue by brettz9** [SemanticMediaWiki/SemanticMediaWiki#3529]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.0.32-0ubuntu0.16.04.1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.24-0ubuntu0.16.04.1

### Issue

Given how powerful subproperties can be with being able to search nested properties
I'd like to request a "Subcategory of" feature which behaved in a similar manner. While I know this would appear to be more the provenance of Mediawiki proper, I'd expect that for full searching capabilities, this implementation would be useful as a part of SemanticMediaWiki and not force users to reimplement all categories as properties in order to get the searching benefits.

**Comment by brettz9** [comment]
Apologies, I see now that is actually how SMW behaves in category searches...

**Comment by kghbln** [comment]
Great that you found it. :)
