### ISSUE TITLE
Searching parent property without subproperties

### ISSUE THREAD

**Issue by brettz9** [SemanticMediaWiki/SemanticMediaWiki#3530]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.0.32-0ubuntu0.16.04.1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.24-0ubuntu0.16.04.1

### Issue

As powerful as searching a property with its subproperties can be, I'd also like a way to search the parent property alone.

If #3529 is implemented, I'd also like to see such a capability of searching only the parent with that.

**Comment by brettz9** [comment]
I see this too (per https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/Hierarchy_depth_restriction ) has been implemented already as well, my apologies...

**Comment by kghbln** [comment]
Indeed. This is a SMW 3.0 feature.
