### ISSUE TITLE
Date interpretation fails for  "2018-10-11 18:23:59 +0200" 

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#3532]
## Setup and configuration
see 
- https://sandbox.semantic-mediawiki.org/wiki/Issue3532
- https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2018-10-26

### Issue
see 
- https://sandbox.semantic-mediawiki.org/wiki/Issue3532
- https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2018-10-26
![grafik](https://user-images.githubusercontent.com/1336221/47567359-9e28d800-d92e-11e8-9c0f-8593ea744d92.png)

_Unable to interpret the "2018-10-11 18:23:59 +0200" input value as valid date or time component with "Part of the date is out of bounds." being reported_

### Steps to reproduce

```
[[Has date::2018-10-11 18:23:59 +0200]]

{{#ask: [[{{FULLPAGENAME}}]]
|?Has_date
}}
```
similar iso dates do not have this issue e.g.
2018-10-11 18:03:20 +0200
works.

**Comment by kghbln** [comment]
This is indeed a known limitation as [documented](https://www.semantic-mediawiki.org/wiki/Help:Type_Date#Input_examples). Please use a formatter like `ISO` or `F` to get the result in shape.

**Comment by WolfgangFahl** [comment]
I do not understand why this is closed? Is this not a candidate for an enhancement?

**Comment by kghbln** [comment]
> Is this not a candidate for an enhancement?

No.

**Comment by WolfgangFahl** [comment]
We are talking input not output. Your comment is not a work around for the problem ...
