### ISSUE TITLE
Add "git" as valid URI schema

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#3533]
### Setup and configuration

Sandbox as of 2018-10-26

### Issue
https://sandbox.semantic-mediawiki.org/wiki/Issue3533

### Steps to reproduce
`[[Has url::git:git.server.com/srv/git]]`

```
{{#ask:
 [[{{FULLPAGENAME}}]]
 |?Has_url
}}
```

leads to error message "git ist nicht sls zulässiges URI-schema gelisted"

**Comment by kghbln** [comment]
> Sandbox as of 2018-10-26

This is a non information.

Please use [`$smwgURITypeSchemeList`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1979) to add "git". However I believe it should be in here by default.

**Comment by kghbln** [comment]
We also should have "sftp" and "ssh" by default. All the others used by [default](https://sandbox.semantic-mediawiki.org/w/index.php?target=http%3A%2F%2Fexamlple.org%2F%25E3%2582%2588%25E3%2581%2586%25E3%2581%2593%25E3%2581%259D&title=Sp%C3%A9cial%3ARecherche_de_lien) by MediaWiki are either already in here or not really widely used.
