### ISSUE TITLE
Improve sanitization of the `Display title of` content to support `< ... >`

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#3534]
### Setup and configuration

Product | Version
-- | --
MediaWiki | 1.31.1 (921e265)01:19, 25 October 2018
PHP | 7.0.30-0+deb9u1 (apache2handler)
MariaDB | 10.1.26-MariaDB-0+deb9u1
ICU | 57.1
LuaSandbox | 3.0.3
Lua | 5.1.5
Elasticsearch | 6.4.2

Semantic MediaWiki | 3.1.0-alpha (c7deedd) 10:12, 12 October 2018 | GPL-2.0-or-later | Making your wiki more accessible - for machines and humans (online documentation) | Markus Krötzsch, Jeroen De Dauw, James Hong Kong and others
-- | -- | -- | -- | --

### Issue
The wikitext `{{DISPLAYTITLE:&lt;tag&gt;}}` changes the displayed title of wiki page to `<tag>` as expected.

However, the special property Property:Has display title of is set to an empty string. The HTML entity `&lt;` is stripped from the property value as if it were the plain `<` sign.

I think this is wrong. 

Example: https://sandbox.semantic-mediawiki.org/wiki/Display_Title_test.

**Comment by kghbln** [comment]
Thanks for reporting this. I think this needs to be looked into. At least the part of having an empty annotation.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
