### ISSUE TITLE
Further results link not working if outro parameter contains another ask query

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#3535]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.1.23 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.36-MariaDB

### Issue
"Further results" link is shown as external link and does not work if outro parameter is more complex. I am using outro parameter to show download as CSV link only if there are results to show.

### Steps to reproduce
1. Go to https://nimiarkisto.fi/wiki/Special:ExpandTemplates and paste the following query
2. Click the more results link

```
{{#ask:

[[Keruunimi::~Vuos*]]

 |?Paikanlaji
 |?Nimenlaji
 |?Pitäjä
 |?Kerääjä
 |default=Ei tuloksia!
 |format=table
 |link=all
 |headers=plain
 |searchlabel=more results
 |showtitle=1
 |limit=10
 |outro=
{{#ask:

[[Keruunimi::~Vuos*]]

 |?Keruunimi
 |?Paikanlaji
 |?Nimenlaji
 |?Pitäjä
 |?Kerääjä
 |?Keruuvuosi
 |format=csv
 |limit=2500
 |offset=0
 |default=
 |searchlabel=<span class="mw-ui-button">Lataa tulokset (enintään 2500) CSV-muodossa</span>
}}

}}
```

**Comment by Nikerabbit** [comment]
It would be helpful csv/json output format did not ignore the default parameter when there are no search results. Then I would not need to place this in an outro.

**Comment by kghbln** [comment]
Thanks a lot for reporting this!

> It would be helpful csv/json output format did not ignore the default parameter 

I agree here. There are a couple of other result formats that also ignore the `default`parameter. I think it should always be possible to specify a default. I am not sure if "csv" etc. already consider possible results when being added to the page rather when being triggered to create the file. Another possibility is to make "intro" and "outro" behave like "default".

**Comment by mwjames** [comment]
> "Further results" link is shown as external link and does not work if outro parameter is more complex. I am using outro parameter to show download as CSV link only if there are results to show.

I'm fairly certain this relates to #3855 hence we reverted the settings default.

> It would be helpful csv/json output format did not ignore the default parameter when there are no search results. Then I would not need to place this in an outro.

I'm guessing this to be a feature request which should be tracked somewhere else (please don't count on me to have a look at it anytime soon) but ...

> I think it should always be possible to specify a default. I am not sure if "csv" etc. already consider possible results 

... export formats are special since they don't have a pre-output processing, only during the actual click on the link will the `QueryEngine` engage with the format and know whether it can provide results or not with the `default` only becoming visible when there are no results.
