### ISSUE TITLE
RFE: Property link labels (@@@) do not work with record/reference field property chains

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3539]
### Setup and configuration

- SMW version: 2.5.8
- MW version: 1.31.0
- PHP version:  7.2.10
- DB system: MySQL

## Problem
When using `#ask` queries on record/reference properties, the labels on the results get special treatment 
(the field properties link back to their parent record/reference).
Unfortunately, you cannot replicate this output when using [property links](https://www.semantic-mediawiki.org/wiki/Help:Property_links), like: `[[record prop.field prop::@@@@]]` when using the [property chain printout method](https://www.semantic-mediawiki.org/wiki/Help:Type_Record#Semantic_search).

**Comment by kghbln** [comment]
Thanks a lot for suggesting. You really like records. :)

**Comment by kghbln** [comment]
We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
