### ISSUE TITLE
`#set_recurring_event` creates only 26 subobjects

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3541]
### Setup and configuration

- MediaWiki | 1.31.1 (8e4e0d8)19:00, 15. Nov. 2018
- PHP | 7.0.30-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.1.0-alpha (a3460c1) 08:20, 15. Nov. 2018

### Issue
`#set_recurring_event` creates only 26 subobjects. Configuration parameter `$smwgDefaultNumRecurringEvents` is thus being ignored even in default install.

Note that this is not an SMW 3.0.0 regression but was originally detected on SMW 2.5.8

### Steps to reproduce
[Birthday events template](https://sandbox.semantic-mediawiki.org/wiki/Mod%C3%A8le:TestBirthdays) with the following content:
```
{{#set_recurring_event:
 Is birthday
 |property=Has date
 |start={{{birth|}}}
 |end={{{death|}}}
 |unit=year
 |period=1
 |event=birthday
 |eventcolour=ff8000
 |eventname={{{name|}}}
}}
```
[Data setting and query](https://sandbox.semantic-mediawiki.org/wiki/Issue/3541). The result only returns 26 events though 100 are expected.

**Comment by kghbln** [comment]
p-0112.json

```json
{
	"description": "Test #set_recurring_event parser (#3541, en)",
	"setup": [
		{
			"page": "John Doe's Birthdays",
			"contents": "{{#set_recurring_event: Is birthday |property=Has date |start=1948-11-03 |end=2019-01-06 |unit=year |period=1 }}"
		},
		{
			"page": "John Doe's Number of Birthdays",
			"contents": "{{#ask: [[John Doe's Birthdays]] [[Is birthday::+]] |format=count }}"
		},
		{
			"page": "Jane Doe's Birthdays",
			"contents": "{{#set_recurring_event: Is birthday |property=Has date |start=1953-05-06 |unit=year |period=1 }}"
		},
		{
			"page": "Jane Doe's Number of Birthdays",
			"contents": "{{#ask: [[Jane Doe's Birthdays]] [[Is birthday::+]] |format=count }}"
		},
	],
	"tests": [
		{
			"type": "parser",
			"about": "#0 #set_recurring_event parser with end date",
			"subject": "John Doe's Number of Birthdays",
			"assert-output": {
				"to-contain": [
					"70"
				]
			}
		},
		{
			"type": "parser",
			"about": "#1 #set_recurring_event parser without end date",
			"subject": "Jane Doe's Number of Birthdays",
			"assert-output": {
				"to-contain": [
					"110"
				]
			}
		}
	],
	"settings": {
		"wgContLang": "en",
		"wgLang": "en",
		"smwgDefaultNumRecurringEvents": "110"
	},
	"meta": {
		"version": "2",
		"is-incomplete": false,
		"debug": false
	}
}
```

**Comment by kghbln** [comment]
I am not sure how easy it is to hijack a pull request. Since I can only do the test I posted here for easy copy and past. I could also create a pull just for the test - which should fail in both case as of now.

**Comment by mwjames** [comment]
I has a quick look at it and the issue is with `$maxNumRecurringEvents = 25;` in `RecurringEvents` which isn't set correctly after the class is initiated.

**Comment by kghbln** [comment]
So this refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1925. I am amazed that nobody detected this earlier.

**Comment by mwjames** [comment]
>  Since I can only do the test I posted here for easy copy and past. I could also create a pull just for the test

I used your test as input (https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/issue-3541), please see the diff on how to make the test really work.

PS: If you create a test as above you can simply put it in the JSONScript folder (where all the others tests are) and run `composer test -- --filter p-0112` from the SMW root. `--filter` allows you to run each integration test individually by replacing `p-0112` with the name of the test file.

```
--- untitled 
+++ (clipboard) 
@@ -1,13 +1,18 @@
 {
 	"description": "Test #set_recurring_event parser (#3541, en)",
 	"setup": [
+		{
+			"namespace": "SMW_NS_PROPERTY",
+			"page": "Has date",
+			"contents": "[[Has type::Date]]"
+		},
 		{
 			"page": "John Doe's Birthdays",
 			"contents": "{{#set_recurring_event: Is birthday |property=Has date |start=1948-11-03 |end=2019-01-06 |unit=year |period=1 }}"
 		},
 		{
 			"page": "John Doe's Number of Birthdays",
-			"contents": "{{#ask: [[John Doe's Birthdays]] [[Is birthday::+]] |format=count }}"
+			"contents": "{{#ask: [[Is birthday::John Doe's Birthdays]] |format=count }}"
 		},
 		{
 			"page": "Jane Doe's Birthdays",
@@ -15,8 +20,8 @@
 		},
 		{
 			"page": "Jane Doe's Number of Birthdays",
-			"contents": "{{#ask: [[Jane Doe's Birthdays]] [[Is birthday::+]] |format=count }}"
-		},
+			"contents": "{{#ask: [[Is birthday::Jane Doe's Birthdays]] |format=count }}"
+		}
 	],
 	"tests": [
 		{
@@ -25,7 +30,7 @@
 			"subject": "John Doe's Number of Birthdays",
 			"assert-output": {
 				"to-contain": [
-					"70"
+					"71"
 				]
 			}
 		},
@@ -35,7 +40,7 @@
 			"subject": "Jane Doe's Number of Birthdays",
 			"assert-output": {
 				"to-contain": [
-					"110"
+					"111"
 				]
 			}
 		}
```

**Comment by kghbln** [comment]
First of all, thanks for the fluff

> please see the diff on how to make the test really work

Ah, yes, we need to tell the datatype which I should have thought of and counting in the initial subobject should have been on my mind, too. :| The queries I added were just plain stupid. :(

**Comment by kghbln** [comment]
@mwjames What puzzles me is that the [example on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/3541) is still only emitting 26 subobjects instead of the expected 101

**Comment by mwjames** [comment]
> @mwjames What puzzles me is that the example on sandbox is still only emitting 26 subobjects instead of the expected 101

See my comments in the other thread about the outdated Composer ref.

**Comment by kghbln** [comment]
> See my comments in the other thread about the outdated Composer ref.

Sorry for the noise. I expected to be on master after `composer update --no-dev --prefer-source` did not move in any new code.

> What puzzles me is that the example on sandbox is still only emitting 26 subobjects instead of the expected 101

Affirmative, after the update, we are back in business.
