### ISSUE TITLE
'Format not found exception' in further results when using a SPACE between format= and the format in inline queries

### ISSUE THREAD

**Issue by carchaias** [SemanticMediaWiki/SemanticMediaWiki#3542]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.1.23
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 5.5.50

This occurs after update from MW 1.23.15, SMW 2.5.4

### Issue
When there is a SPACE in the format statement of #ask: queries an exception occurs when clicking on further results link.
  
Example:
```
|format= table 
```
instead of 
```
|format=table
```
this is independent from the format selected. 

### Stack trace
```
[W-JmIM-0xIdZK26Wq8BEngAAABE] /aquanautwebwiki11205/index.php/Spezial:Semantische_Suche/cl:YzotTltqAzEMPE6_jJddlkLAH82Lhi3tR8kB5ES7deO1izwpbc7Tm_RilZvAII00M0KmX5p-ORB4yhJ48eLf-QTTrxXWdNt9wbO4fQJLASHkVLdDJAF_ofJrAt8fddgVmLbZmHa9euPDSbtw5E9KsDOFFMlzdA_Dq41hDnBt0zQ2y5HFHbkcbMkCdzlHxqXemfj3J6kIm8ex8M0_ZpkJTnWQj2xDgmQd7xV3plv5MJlu8xQKWD0a1_pIEyd_rh9t_5WkRuVX7y37Bw SMW\Query\Exception\ResultFormatNotFoundException from line 441 of /home/www/sites/IP/mediawiki-1.31.1/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php: There is no result format for ' table'.
```

### Backtrace:
```
#0 /home/www/sites/IP/mediawiki-1.31.1/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(302): SMWQueryProcessor::getResultPrinter(string, integer)
#1 /home/www/sites/IP/mediawiki-1.31.1/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(169): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#2 /home/www/sites/IP/mediawiki-1.31.1/includes/specialpage/SpecialPage.php(522): SMW\MediaWiki\Specials\SpecialAsk->execute(string)
#3 /home/www/sites/IP/mediawiki-1.31.1/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(string)
#4 /home/www/sites/IP/mediawiki-1.31.1/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#5 /home/www/sites/IP/mediawiki-1.31.1/includes/MediaWiki.php(861): MediaWiki->performRequest()
#6 /home/www/sites/IP/mediawiki-1.31.1/includes/MediaWiki.php(524): MediaWiki->main()
#7 /home/www/sites/IP/mediawiki-1.31.1/index.php(42): MediaWiki->run()
#8 {main}
```

### Steps to reproduce
Make an inline ask-query with a number of results that break the limit. Use the format string with a space ( |format= table). Click on further results.

**Comment by kghbln** [comment]
Thanks a lot for reporting. I think it will be good if this still works even with a space.

**Comment by carchaias** [comment]
Yes, becaus this struggles existing wikis. And on new ones you see it first time when a limit is exausted.

**Comment by kghbln** [comment]
As a quick fix I recommend doing a search and replace operation using the ["ReplaceText" extension](https://www.mediawiki.org/wiki/Extension:Replace_Text). This does not solve the issue but I avoids it for the time being.

**Comment by carchaias** [comment]
I did so , but that's really no fix..
