### ISSUE TITLE
Sorting in record datatype query

### ISSUE THREAD

**Issue by dfhdfhdf** [SemanticMediaWiki/SemanticMediaWiki#3544]
Can I sorting results by one of the field (Has fields in Record type)?

I have page. On this page:
```
[[ACounterListKeyWords::pollination;5]]
[[ACounterListKeyWords::flowering;10]]
```

Property page ACounterListKeyWords contain:
```
[[Has type::Record]]
[[Has fields::CounterListTitle;CounterListNumber]]
```

And on first page, i query:
```
{{#ask:
 [[{{PAGENAME}}]]
 |?ACounterListKeyWords
 |?ACounterListKeyWords#title|+index=1
 |?ACounterListKeyWords#number|+index=2
}}
```

The question - Can I sort result by ACounterListKeyWords#number?

**Comment by kghbln** [comment]
Have a look a the docu [here](https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/Printout_sorting_order) and see if this works.

@ankostis I believe you have intensely dug into Records lately. Most probably you are even more proficient answering this question. I personally never used Records yet. :|

**Comment by mwjames** [comment]
> The question - Can I sort result by ACounterListKeyWords#number?

There is no such thing as `...#number` but you can use the index or chain notation and [0] should provide all the answers to your question.

[0] https://sandbox.semantic-mediawiki.org/wiki/Issue/3544

**Comment by ankostis** [comment]
I confirm that the chain notation works also with Reference types.

Thanks @mwjames, i didn't the the `|+order+` notation.  Is it somewhere written in wiki?
