### ISSUE TITLE
`Has uniqueness constraint` in a Record field reports collisions on every 2nd refresh

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3547]
### Setup and configuration

- SMW version: 2.6.8
- MW version: 1.31.0
- PHP version: 7.2.10
- DB system (MySQL, Blazegraph, etc.) and version: mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper

### Issue
When annotating a page with a "Record" property that has a "unique' field, it produces false positive collision _with the same page_, usually every 2nd rebuild of the page (but not always - sometime the collision is stuck for all the time).  

### Steps to reproduce
See also [sandbox (Category:Unique Record sample)](https://sandbox.semantic-mediawiki.org/wiki/Unique_record_test) where smw-v3.1.0alpha has still this bug.

Create 2 props + 1 test-page:
* [[Property:Unique record]]: 
  ```
  * type: [[Has type::Record]]
  * fields: [[Has fields::Unique field;other prop]]
  ```
* [[Property:Unique field]]: 
  ```
  * type: [[Has type::Text]]
  * unique: [[Has uniqueness constraint::true]]
  ```
* [[Test page]]:
  ```
  * Annotate with <nowiki>[[Unique record::abc;123]]</nowiki>: [[Unique record::abc;123]]
  ```

And then click `refresh` from the top-bar menu until you get the error message:
```
Property "Unique field" only permits unique value assignments and abc was already annotated in subject "Unique record test".
```
 Refresh once more, and the error disappears, and the annotation passes through.

**Comment by kghbln** [comment]
Thank you for reporting.
