### ISSUE TITLE
Property-labels are used as the parameters passed in templated #ask queries with "named ags"

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3548]
## Setup and configuration
- SMW version: 2.5.8
- MW version: 1.31.0

## Context
When a property that has been re-labelled with [`Has preferred property label`](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Has_preferred_property_label) is used 
* in a printout of an `#ask` query that uses the [`|format=template`](https://www.semantic-mediawiki.org/wiki/Help:Template_format) (or [`|format=plainlist`](https://www.semantic-mediawiki.org/wiki/Help:Plainlist_format) in `smw-v3+`) , and 
* its ask-template parameters use [`|named args=1`](https://www.semantic-mediawiki.org/wiki/Help:Template_format#Usage_for_template_arguments.3D.5Bnamed.7Clegacy.5D_.28named_args.29) (`|template arguments=named`, and
* if the property has been re-labelled with [`Has preferred property label`](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Has_preferred_property_label), 

then, the original property is masked by the label, and the parameter-name has to be that of the label.

### Problems
The problem manifests more promptly as a bug when someone adds a label on a property that is used by many templated-queries; so a i18n-content change breaks the structure of the site.

Also, when the property has many labels, for different languages, it is not clear which parameter-name to use in the ask-template.

As a discussion point, to use the parameter names derived from overridden printouts in the #ask queries makes sense, since the same person developing the query is usually in direct control of both the override-label, and the template params.  But that's not the case with the `Has preferred property label`.

### Steps to reproduce
See https://sandbox.semantic-mediawiki.org/wiki/Relabel_ask_templates_test.

**Comment by kghbln** [comment]
Thanks for reporting!

**Comment by jamesmontalvo3** [comment]
Just to clarify: you show steps to reproduce on Sandbox which is running SMW 3.x and MW 1.32, but you list at the top that the issue presents itself on SMW 2.5.x and MW 1.31.

**Comment by jamesmontalvo3** [comment]
Oh...and the reason that's important is SMW 2.5.x only supports up to MW 1.30

**Comment by ankostis** [comment]
>  SMW 2.5.x only supports up to MW 1.30

Oh, i didn't know that - downgraded my wiki, thanks.

Just to be clear, my installation's versions were exactly as listed above.
The sandbox manifested the same behavior, although it runs different version.

**Comment by ankostis** [comment]
> Anyways a fix should go ideally into SMW 3.0.x

I can always backport the fix as a PR, if you don't mind.
