### ISSUE TITLE
Columns parameter not working in "ul" format for queries

### ISSUE THREAD

**Issue by V-Brooks** [SemanticMediaWiki/SemanticMediaWiki#3549]
### Setup

- MW version: 1.31.1
- DB (MySQL etc.):
- PHP version: 7.1.23 (apache2handler)
- SMW version: 3.0.0
- SRF version:
- Browsers and versions (if applicable): Chrome 70.0.3538.110 (Official Build) (32-bit)

### Issue

When using #ask and using the format "ul", the "columns" parameter doesn't work. This used to work but I'm not sure when it stopped working.

**Steps to reproduce**
Create a query, set the format to "ul", and add the "columns=2" parameter.

```
{{#ask: [[Category:City]] [[located in::Germany]] 
| format=ul
| columns=2
}}
```

**Expected result:** 
• Berlin&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Cologne
• Frankfurt&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Munich
• Stuttgart&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Würzburg

**Observed result:** 
- Berlin
- Cologne
- Frankfurt
- Munich
- Stuttgart
- Würzburg

**Comment by kghbln** [comment]
@V-Brooks Thanks for reporting. The "ul" format actually ships with Semantic MediaWiki but this is a side note. The `columns` parameter is no longer provided as of SMW 3.0.0. Instead CSS should be used. So far I have not gotten around poking at issue https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3135 and see how it is done now. 

@s7eph4n Probably you will be faster in providing a solution.

**Comment by kghbln** [comment]
Ah, this [page](https://www.w3schools.com/css/css3_multiple_columns.asp) will help here. Use the "column-count" property of CSS to achieve this like e.g. for two columns:

```css
ul.smw-format.ul-format {
    column-count: 2;
}
```

**Comment by kghbln** [comment]
Now [documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AUl_format&type=revision&diff=66270&oldid=64867)

**Comment by V-Brooks** [comment]
Thanks for the help!

**Comment by kghbln** [comment]
You are welcome. It was long overdue to document this.
