### ISSUE TITLE
smw_di_time.o_serialized has strange format in SMW 3.0?

### ISSUE THREAD

**Issue by yaronkoren** [SemanticMediaWiki/SemanticMediaWiki#3552]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.1.24
- DB system (MySQL, Blazegraph, etc.) and version: 5.5.60-MariaDB

### Issue
The column smw_di_time.o_serialized seems to be storing data in the format "1/YYYY/MM/DD", instead of just "YYYY/MM/DD" - which breaks Semantic Drilldown's date queries. Is this a deliberate new format?

**Comment by kghbln** [comment]
Thanks for asking. I myself cannot answer but I have the feeling that there must be a purpose for doing so. If not this can still be relabeled to bug.

**Comment by yaronkoren** [comment]
Actually, it looks like the "1/" was added before SMW 3.0 was released - it happened maybe two years ago, or more. It would be good to know when exactly this happened (and why).

**Comment by s7eph4n** [comment]
Unless I am looking at the wrong file this seems to have been in since forever:
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blame/419e7926ee62efb087fb936e905f195d483bc936/includes/dataitems/SMW_DI_Time.php#L349

**Comment by yaronkoren** [comment]
Oh... that's odd. Maybe it's just an SMWSQLStore vs. SMWSQLStore3 thing. I'll assume that's the case; closing this bug. Thanks!
