### ISSUE TITLE
Special:Ask is missing 'count' result format

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3557]
### Setup and configuration

- SMW version: 2.5.8
- MW version: 1.31.0
- PHP version: 7.2.10-0ubuntu0.18.04.1 (apache2handler)
- MySQL: 5.7.23-0ubuntu0.18.04.1
- ICU: 60.2
### Issue
The dropdown list in the "Semantic search" special page is missing the `count` result format, it does contain other aggragation results (mean, median, max, etc)/.

Could that be due to my, kind of, invalid installation>
(SMW-v2.5.8 + MW > 1.30)

**Comment by kghbln** [comment]
Thanks for reporting. It does not work on 2.5.x and 3.0.x as e.g. [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Requ%C3%AAter) shows.

**Comment by ankostis** [comment]
Now that i'm sure it is a "blessed" format, i added `[[Has category::math]]` to [its page](https://www.semantic-mediawiki.org/wiki/Help:Count_format).

**Comment by s7eph4n** [comment]
`mean`, `median`, etc. are provided by SRF, while `count` is provided by SMW directly.

The `count` format is a special case format that does not have (and as far as I know never had) its own result format handler and therefore does not appear in the dropdown on Special:Ask.

Fixing this might be a bigger task.

**Comment by mwjames** [comment]
> The dropdown list in the "Semantic search" special page is missing the count result format, it does contain 
> The count format is a special case format that does not have (and as far as I know never had) its own result format handler and therefore does not appear in the dropdown on Special:Ask.

Exactly, `count` requires a different SQL execution plan and has a simple numerical representation which doesn't require a `ResultPrinter`. The `Special:Ask` drop-down generates its list from `smwgResultFormats` (among others) hence it doesn't appear in the list.

This is not bug (see [0]), you might provide a PR or find a sponsor to add required functionality that will allow `count` to become a dropdown entry but current project members have no immediate plans to provide such support therefore closing this ticket.

Feel free to re-open this ticket once an actual implementation is planned or sponsored.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/CONTRIBUTING.md#report-bugs

**Comment by ankostis** [comment]
But we won't be able to find pending issues like this in the future.
Could there be some "label", like `wont' fix`, to mark them?

**Comment by kghbln** [comment]
> But we won't be able to find pending issues like this in the future.

We use a project for this. I labelled it "enhancement" and "seeks developer" and added it to the [ [Enhancements and features](https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4) to prevent it from getting lost.
