### ISSUE TITLE
Statement Based Replication (SBR) not working

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3558]
### Setup and configuration

- MediaWiki | 1.31.1 (141cb48)22:39, 5 December 2018
- PHP | 7.0.32-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.24-0ubuntu0.16.04.1
- Semantic MediaWiki | 3.0.0 (abdec88) 22:29, 11 October 2018

### Issue
In contrast to Row Based Replication (RBR) which is supposedly working, at least for Wikia, Statement Based Replication (SBR) does not since `TRUNCATE TABLE` for temporary statements does not work for Percona MySQL and Aurora MySQL (temporary tables are not being replicated). The suggestion was to replace `TRUNCATE` with `DELETE` per https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/master...HydraWiki:3.0.x-hydra (includes a configuration parameter change)

**Comment by jamesmontalvo3** [comment]
Can you provide an example of something that doesn't work? A particular type of query or something? I don't have replication running in a production environment at the moment, but I just spun up a couple of VMs and basic things work with both `binlog_format=STATEMENT` and `binlog_format=ROW`. Note that per [1] you have to add to LocalSettings.php:

```php
$smwgLocalConnectionConf['mw.db.queryengine'] = array(
	'read' => DB_SLAVE,
	'write' => DB_SLAVE
);
```

See my default config [2] which has some additional rationale in comments. See also [3] and [4].


[1] https://www.semantic-mediawiki.org/wiki/Help:$smwgLocalConnectionConf
[2] https://github.com/enterprisemediawiki/meza/blob/eea7891cac300501891098c5999690b8da0438e3/config/core/MezaCoreExtensions.yml#L19-L26
[3] #2532
[4] #2534

**Comment by kghbln** [comment]
> Can you provide an example of something that doesn't work?

Actually I cannot. I was just at the end of a chain of statements of people telling people that people have supposedly an issue. So  figured it may be worth documenting what the issue is about.

**Comment by jamesmontalvo3** [comment]
Okay. I'm as long as you set `$smwgLocalConnectionConf` appropriately in LocalSettings I think it works well with STATEMENT and ROW. If you don't set that properly I don't believe even ROW will work. I'm very curious to hear from anyone who can provide more info.

**Comment by brightbyte** [comment]
Running rebuildData.php on a system with GTID enabled, I get:

```
Wikimedia\Rdbms\DBQueryError from line 1457 of /var/www/events.ccc.de/congress/2018/wiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: DELETE FROM `smw_ft_search` WHERE s_id = '501'
Function: SMW\SQLStore\PropertyTableIdReferenceDisposer::cleanUpSecondaryReferencesById
Error: 1785 Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables. (192.168.236.1)
```

Full trace:
```
#0 /var/www/events.ccc.de/congress/2018/wiki/includes/libs/rdbms/database/Database.php(1184): Wikimedia\Rdbms\Database->makeQueryExce
ption('Statement viola...', 1785, 'DELETE FROM `sm...', 'SMW\\SQLStore\\Pr...')
#1 /var/www/events.ccc.de/congress/2018/wiki/includes/libs/rdbms/database/Database.php(2845): Wikimedia\Rdbms\Database->query('DELETE
 FROM `sm...', 'SMW\\SQLStore\\Pr...')
#2 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(673): Wikimedia\Rdbms
\Database->delete('`smw_ft_search`', 's_id = '501'', 'SMW\\SQLStore\\Pr...')
#3 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(248): SMW
\MediaWiki\Connection\Database->delete('smw_ft_search', Array, 'SMW\\SQLStore\\Pr...')
#4 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(204): SMW
\SQLStore\PropertyTableIdReferenceDisposer->cleanUpSecondaryReferencesById('501', false)
#5 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(150): SMW
\SQLStore\PropertyTableIdReferenceDisposer->cleanUpReferencesById('501')
#6 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(132): SMW
\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesById('501')
#7 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/EntityIdDisposerJob.php(58): SMW\SQLStor
e\PropertyTableIdReferenceDisposer->cleanUpTableEntriesByRow(Object(stdClass))
#8 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(486): SMW\MediaWiki\Jobs\
EntityIdDisposerJob->dispose(Object(stdClass))
#9 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(264): SMW\Maintenance\DataRebuilder->dispose_outdated()
#10 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(182): SMW\Maintenance\DataRebuilder->rebuild_all()
#11 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(167): SMW\Maintenance\DataRebuilder->rebuild()
#12 /var/www/events.ccc.de/congress/2018/wiki/maintenance/doMaintenance.php(95): SMW\Maintenance\RebuildData->execute()
#13 /var/www/events.ccc.de/congress/2018/wiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(225): require_once('/var/www/events...')
#14 {main}
```

**Comment by brightbyte** [comment]
Somewhat off topic: With regards to $smwgLocalConnectionConf['mw.db.queryengine'], what's the intention here? The idea behind having replicated databases (typically more than one replica) is to distribute read operations among them. In theory, that should Just Work if write operations happen with DB_MASTER, and read operations with DB_REPLICA. This configuration seems to imply that the query engine only uses one database, instead of spreading queries across the replicas, and limiting writes to the master. Am I misunderstanding this? Is there a way to actually make use of replicated databases with the SMW query engine?

**Comment by kghbln** [comment]
> Error: 1785 Statement violates GTID consistency

Did you try changing the setting to configuration parameter [`$smwgQTemporaryTablesAutoCommitMode`](https://www.semantic-mediawiki.org/wiki/Help:$smwgQTemporaryTablesAutoCommitMode)?

**Comment by kghbln** [comment]
> Somewhat off topic: ...

I guess this is best discussed here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2534

**Comment by jamesmontalvo3** [comment]
Regarding the seemingly contradictory `'write' => DB_REPLICA`, see [this comment](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2532#issuecomment-312365395) and the following two comments from #2532. My understanding is that writes using `mw.db.queryengine` aren't persistent, but only in-memory temporary table creation. @mwjames would have to confirm.

**Comment by brightbyte** [comment]
> > Error: 1785 Statement violates GTID consistency
> 
> Did you try changing the setting to configuration parameter [`$smwgQTemporaryTablesAutoCommitMode`](https://www.semantic-mediawiki.org/wiki/Help:$smwgQTemporaryTablesAutoCommitMode)?

Yes. From LocalSettings.php:
```
$smwgQTemporaryTablesAutoCommitMode = true;
```

Same difference.

**Comment by brightbyte** [comment]
From the relevant MySQL documentation:

>  CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE statements are not supported inside transactions, procedures, functions, and triggers when using GTIDs (that is, when the enforce_gtid_consistency system variable is set to ON). It is possible to use these statements with GTIDs enabled, but only outside of any transaction, and only with autocommit=1. 

https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-restrictions.html

The problem is apparently that rebuildData causes temporary tables to be used inside a transaction.

**Comment by jamesmontalvo3** [comment]
From [1] it seems that generating the temporary tables on replicas is not preferred, so perhaps our documentation should change the recommendation to DB_MASTER. Also, the use of temporary tables at all in a replicated environment may not be ideal. I'm not sure what the impacts of not using temporary tables would be, if that's at all feasible for SMW.

@brightbyte someone mentioned that `binlog_format=ROW` may have resolved your issue. Is that correct? If so, then I think this issue should be separated into two issues:

1. `binlog_format=STATEMENT` does not work with GTID-based replication
2. `TRUNCATE TABLE` does not work for temporary tables in Percona MySQL and Aurora MySQL 

For (1) I'm not sure what the solution is. I'd have to dig into the error @brightbyte added above. 

For (2) the solution to change `TRUNCATE` to `DELETE` seems pretty straightforward [2]. I'm certainly not an expert, but I think the only thing we'd have to look out for is a performance hit. I think (2) needs to be confirmed as a real issue first, though, since right now I think @kghbln is just passing on someone else's words.

Thoughts?

[1] https://phabricator.wikimedia.org/T202245
[2] From @kghbln first comment on this issue, https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/master...HydraWiki:3.0.x-hydra

**Comment by kghbln** [comment]
It appears that discussion on this cooled down lately. Since there is not detectable progress however referenced documentation I am closing this for now. Feel free to re-open or better create a fresh issue for this if there are still worries.

**Comment by mwjames** [comment]
> It appears that discussion on this cooled down lately. Since there is not
> detectable progress however referenced documentation I am closing this for
> now. Feel free to re-open or better create a fresh issue for this if there
> are still worries.

Well, the discussion went of rails making the initial intent unclear,
and worse, I have been unable to decipher of what "Statement Based
Replication" would require or what would be expected from SMW.

So, yes, the next time some similar issues appears, keep it clean and
clear, and create a specific problem statement that allows someone to
respond without being sidetracked by other discussions.
