### ISSUE TITLE
Query for strings with substring '-3D'

### ISSUE THREAD

**Issue by tschijv** [SemanticMediaWiki/SemanticMediaWiki#3560]
### Setup and configuration

- SMW version: 3.0.0 (abdec88) to 3.1.0-alpha (c0f2982) 
- MW version: 1.27 to 1.32.0-rc.1 (49b7c17)
- PHP version: 7.0.33-0 + deb9u1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL  5.7.24-0ubuntu0.16.04.1

### Issue
Queries searching for strings which contain the substring '-3D' don't have any results. The reason is that SMW encodes this substring to '=' and thereby changes the value to search for.

### Stack trace
no stack trace

### Steps to reproduce
- Go to https://sandbox.semantic-mediawiki.org/wiki/special:ask
- Enter in the search this query [[Id::-3D]]. 
- Click on 'Find results'
- The value in de search condition box will transformed to [[Id::=]]
- without any results

**Comment by kghbln** [comment]
Thanks a lot for reporting.

**Comment by mwjames** [comment]
> Queries searching for strings which contain the substring '-3D' don't have any results. The reason is that SMW encodes this substring to '=' and thereby changes the value to search for.

Yes, internally we used `-3D` to temporarily encode `=` in `[[ ... ]]` to distinguish it from other parts that include `=`.

It appears that `-3D` can be part of a value declaration, #3632 will use `0x003D` for the encoding instead with the likelihood that a user selects the direct UTF-8 equivalent of `=` is rather diminishable.
