### ISSUE TITLE
Docu of "import-annotation" option is missing from `#smwdoc` for "template" and "plainlist" format

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3564]
### Setup and configuration
- MediaWiki | 1.31.1 (836f10d) 22:05, 27 December 2018
- PHP | 7.0.32-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.24-0ubuntu0.16.04.1
- Semantic MediaWiki | 3.0.0 (abdec88) 22:29, 11 October 2018

### Issue
The documentation of "import-annotation" option is missing from `#smwdoc` for "template" and "plainlist" format. This is a 3.0.0 regression since 2.5.8 still shows this option.

### Steps to reproduce
See [plainlist](https://www.semantic-mediawiki.org/wiki/Help:Plainlist_format) and [template](https://www.semantic-mediawiki.org/wiki/Help:Template_format) docu.

**Comment by krabina** [comment]
related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1257

**Comment by krabina** [comment]
This is probably where it goes wrong:
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2735/files#diff-7ce2559cc43953d96821b11403762474L547
@s7eph4n

**Comment by kghbln** [comment]
@JeroenDeDauw I really would like to see this issue fixed. Is this just a matter of adding the info [to this file](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/ListResultPrinter.php#L142)

**Comment by kghbln** [comment]
The template format is now history past. I archived the docu. Moreover after looking at the docu page for plainlist for about 100 times I realized that the `import-annotation` parameter is listed in the general section and not in the format specific section. Not sure if this is the correct spot, however this is good enough for me.
