### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3568]
### Setup and configuration

- MediaWiki | 1.32.0-rc.1 (92ea1ec)22:07, 27 December 2018
- PHP | 7.0.33-0+deb9u1 (apache2handler)
- MariaDB | 10.1.37-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.1.0-alpha (038ae2f) 01:02, 4 January 2019

### Issue
Then doing a remote query using the "RemoteRequest" feature the following warning is shown:

Warning: Cannot modify header information - headers already sent by (output started at /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php:449) in /.../w/includes/WebResponse.php on line 154

### Steps to reproduce
See the [example](https://sandbox.semantic-mediawiki.org/wiki/My_second_external_query) including the configuration used.

**Comment by kghbln** [comment]
Interestingly enough this only happens with user language set to "en" or "fr". If I set it to German the error does not appear.

**Comment by mwjames** [comment]
I've seen this as well (on the sandbox) but I'm unable to reproduce it locally so unless someone guides me to a locally reproducible case, I'm afraid that this will be a low-priority for me.

**Comment by mwjames** [comment]
I'm guessing MW complains about `print` but it is unclear why because we do a `$this->getOutput()->disable();` before.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/038ae2f684c2c943a0e39fab28ac28131aa3e759/src/MediaWiki/Specials/SpecialAsk.php#L442-L449

**Comment by mwjames** [comment]
You could try replacing `return print $query_result;` with `echo $query_result;` (see above line 449) on the REMOTE site and disable the cache on sandbox (for the test) and see of this shows a better result.

**Comment by kghbln** [comment]
This did not change a thing. The warnings are the same and the logs remain empty. :(

**Comment by mwjames** [comment]
> Affirmative, 02310 is s-mw.o while 02100 is sb.s-mw.o So basically I reported the wrong wiki's bio data in my initial report.

It just confirms that we see the source in the embedded output as a simple string from smw.org. It is unclear why smw.org/Special:Ask produces those messages but a "brutal" hack could be to just filter them (since there are only strings from the source) on the target (i.e the receiving end).
