### ISSUE TITLE
Sortable Special:Properties and other features

### ISSUE THREAD

**Issue by nischayn22** [SemanticMediaWiki/SemanticMediaWiki#357]
Sortable Special:Properties might be of use to some people. 

This should be easy to implement and could be a good task for a new developer.
Can also reuse some code from my failed attempt https://gerrit.wikimedia.org/r/#/c/69306/

**Comment by mwjames** [comment]
Has been moved to the "Enhancements and features" kanban, any implementation can make a reference to this issue.

**Comment by kghbln** [comment]
Let's continue on #4489 since it provides more rationale.
