### ISSUE TITLE
Question: is SMW 2.x serie subject to future updates

### ISSUE THREAD

**Issue by MvGulik** [SemanticMediaWiki/SemanticMediaWiki#3575]

**Comment by mwjames** [comment]
No (see also [0] which clearly states " SMW 2.5.x | Obsolete release | 2017-03-14 ..." )

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by mwjames** [comment]
Further information can be found in #2212 which describes the process with "... a previous stable release automatically becomes an unmaintained release and will no longer receive any patches or maintenance activities ...".

**Comment by MvGulik** [comment]
(_WTF ... I like to write my text before being presented with an already opened issue report_)

(_Wow ... getting an answer while  still writing my issue text ... no point in wasting more time one that part. And its also also closed for me. O well ...._)

On provided Answer.
Bummer, no point then in reporting any 2.x bugs. Besides, I have no way to confirm them against the last 2.x version anyway. (_tried it with online 3.x test version, but that one was so alien, I gave up_)

**Comment by mwjames** [comment]
> Bummer, no point then in reporting any 2.x bugs. Besides, I have no way to confirm them against the last 2.x version anyway. 

You can report them if your observation can be replicate on the sandbox [0] in regards to the 3.x release but no core developer will make an attempt to verify issues against 2.x or provide backports to it.

> And its also also closed for me.

The question was answered "Question: is SMW 2.x serie subject to future updates", wasn't it? 

PS: "WTF ..." isn't really an appropriate expression for an emotional disposition especially towards project members.

[0] https://sandbox.semantic-mediawiki.org/

**Comment by mwjames** [comment]
>tried it with online 3.x test version, but that one was so alien, I gave up

Unless there is clear expression of what is meant by "alien" it is fairly unlikely to solicit a reponse!

**Comment by MvGulik** [comment]
>The question was answered "Question: is SMW 2.x serie subject to future updates", wasn't it?

Not sure how "No"(_first reply_) can contain any potential ambiguity on the question:
>is SMW 2.x serie subject to future updates 

But, as I see a question mark (_kinda rarely used character these days_), the answer on your question is "Yes".
