### ISSUE TITLE
Update GitHub.com interaction with Packagist.org

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3600]
It appears that changes on the side of GitHub.com force us to update interaction with Packagist.org by January 31, 2019.

Quoting comment https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3595#issuecomment-453753212 here to avoid further mixups with other issues:

"No updates could be related to Github's webhook changes "Note: GitHub Services are being deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps" [1, 2], I tried to add it but have insufficient rights [0, 3]. Maybe @JeroenDeDauw could give it a go?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/settings/hooks
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/settings/installations
[2] https://developer.github.com/changes/2018-04-25-github-services-deprecation/
[3] https://packagist.org/about "

**Comment by kghbln** [comment]
@JeroenDeDauw FYI and preferably action. :)

**Comment by mwjames** [comment]
> I tried to add it but have insufficient rights [0, 3]. 

Apparently the registered user does work and [0] now contains expected auto updates.

[0] https://packagist.org/packages/mediawiki/semantic-media-wiki

**Comment by kghbln** [comment]
Since we are part the 31st and the workflow set up still works I am closing this.
