### ISSUE TITLE
Equivalent URI is not working in subject pages

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#3601]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.0
- PHP version: 7.1.25
- MySQL version: 5.6.41-84.1

### Issue
`[[Equivalent URI::$someURI]]` used to allow to declare identical things in the world that is being described. [0] In subject pages, it used to be exported as `owl:sameAs`. In property pages, it is exported as `owl:equivalentProperty` and in category pages it is exported as `owl:equivalentClass`.
Now I noticed that subject pages is not allowed anymore to use this property, and it causes a lot of `Has improper value for` in my wiki. [1] Why Equivalent URI is not permited anymore in subject pages?

### Steps to reproduce
[See the warning at the end of the sentence](https://www.semantic-mediawiki.org/wiki/User:Frank_Dengler). 

[0] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Equivalent_URI
[1] http://wikincat.org/wiki/Especial:Navegar/cl:OkZvdW5kYXRpb25zLTIwb2YtMjBTZW1hbnRpYy0yMFdlYi0yMHRlY2hub2xvZ2llcy0yMCgyMDEwKS0yMy01RkVSUjVhOWI1NmIxZWNkODZiYzRiYTIzZGRmODYxNWEwMTlm?uselang=en

**Comment by mwjames** [comment]
> Why Equivalent URI is not permited anymore in subject pages?

No idea.

If you can make a bisect (see git bisect) and find the related change I may be able to comment on it but right now I'm fairly occupied and unless I have enough information at hand it can take a while before I will review this ticket.

**Comment by mwjames** [comment]
>If you can make a bisect (see git bisect) and find the related change I may be able to comment

Likely (PS: I haven't tested my assumption! )related to #2820 where it adds `'_URI'   => array( '__spu', true, true, true ), // "equivalent URI"` with the last `true` defining it as `isDeclarative`.

Making it non declarative (== false) should restore the previous behaviour. Since we didn't detect the issue before we need a test for this.

**Comment by jaideraf** [comment]
@mwjames that was fast! Thanks for investigating it. :+1:

**Comment by mwjames** [comment]
@jaideraf and @kghbln if both of you could cooperate and send a PR with a suggested change and test that would be much appreciated.
