### ISSUE TITLE
extension.json and names with language context

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3618]
### Setup and configuration

- SMW version: all

### Issue

It seems some extensions that use `extension.json` show the extension name in a language context while it should display the canonical name like for SESP.

https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version

![image](https://user-images.githubusercontent.com/1245473/51089962-e953c980-176c-11e9-9be5-2285c84e7561.png)

**Comment by kghbln** [comment]
Indeed. In case extension registration is used only e. g. "SemanticExtraSpecialProperties" is possible as a displayable name via the "name" parameter. To make "Semantic Extra Special Properties" possible the "namemsg" is added. Though I add the info to the message documentation that this message should not be translated there are translator communities which are exercising language domination to the limit ignoring this note. On the other hand I may have forgotten to add the note to the message docu. I believe we are looking at a lost cause here. I can only make sure that this does not happen for German, which I actually do.

**Comment by kghbln** [comment]
I must note that the "namemsg" parameter was also present for extension credits however rarely used. I guess this came with MW 1.17 but I may be wrong.

**Comment by Nikerabbit** [comment]
You can submit patches against https://gerrit.wikimedia.org/g/translatewiki/+/85f132e6e60d03500492faf0488d0aee6c53ea60/groups/MediaWiki/mwgithub.yaml#144 (preferred) or file tasks in Phabricator with translatewiki.net project.

New messages often sync into translatewiki.net without review, so I don't really catch these other than by accident.

**Comment by kghbln** [comment]
> You can submit patches against https://gerrit.wikimedia.org/g/translatewiki/+/85f132e6e60d03500492faf0488d0aee6c53ea60/groups/MediaWiki/mwgithub.yaml#144 (preferred) or file tasks in Phabricator with translatewiki.net project.

Thanks for the pointer. Will do a pull these days. 

> New messages often sync into translatewiki.net without review, so I don't really catch these other than by accident.

No worries.

**Comment by kghbln** [comment]
I have just authored a change: https://gerrit.wikimedia.org/r/#/c/translatewiki/+/486730/

**Comment by kghbln** [comment]
"smw-title" now got removed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/b9958aac0586c224b0046b00506d75db11d23b91#diff-36a1249b16a7a82f5ee9b57034fa0a39 as a result of https://gerrit.wikimedia.org/r/#/c/translatewiki/+/486730/ being merged. Cool.
