### ISSUE TITLE
CSV result format ignores omitting of units with #-n

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#3620]
### Setup

- MW version: 1.31.1 (899f475)18:58, 12 January 2019
- DB (MySQL etc.): 5.7.24-0ubuntu0.16.04.1
- PHP version: 7.0.32-0ubuntu0.16.04.1 (apache2handler)
- SMW version:  3.0.0 (abdec88) 22:29, 11 October 2018
- SRF version: 3.0.0 (36ced8d) 09:15, 12 October 2018
- Browsers and versions (if applicable):

### Issue
[Custom units](https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#Custom_units) can be conveniently omitted in printouts using
`?Area #-n`
e. g. if the property Area is using the custom unit "km²", the resulting query would only deliver the value without the custom unit.

This is especially useful in export formats like CSV, because they are used to deliver exports the will be reused in spreadsheet programs. Hovever, currently the notation is being ignored in CSV output.

**Steps to reproduce**
* https://www.semantic-mediawiki.org/w/index.php?title=Special:Ask&cl=Yzo1jcEKgzAQRL8orli8FHKpUvobq26aYMzC7or4900rhTk8mOFNYNnQ_CSMi-GUCXLakvm-rVBWX7gQRMKFRL1GPkAJZY4ZJ8q-aRrXtWEXiySVhHTPpjBn1Dpn-SlrcaQ1_Vm343r69h5YqtujzsAhKJlvYcNUrgNw_aNmQKM3y3kfkp2uH2vA3Z4v1OpDIXTdzXVj-QA
* If you click on "CSV", the resulting file has "km²" displayed after the value.

**Expected result:** 
the CSV file should only have the value of the property "has Area" without the "km²"

**Observed result:** 
the CSV file includes the value with "km²"

**Comment by mwjames** [comment]
This is a feature request (no regression to 3.0 or 2.5) [0].

> the CSV file should only have the value of the property "has Area" without the "km²"

Without having tested it but changing the following line should help with the request.

```
@@ -155,11 +155,11 @@ class CsvFileExportPrinter extends FileExportPrinter {
 
 			foreach ( $row as /* SMWResultArray */ $field ) {
 				$growing = [];
 
 				while ( ( $object = $field->getNextDataValue() ) !== false ) {
-					$growing[] = Sanitizer::decodeCharReferences( $object->getWikiValue() );
+					$growing[] = Sanitizer::decodeCharReferences( $object->getShortWikiText() );
 				}
```

## Tasks

- Confirm the suggestion
- Confirm other outputs (number, quantity, text etc.) are not negatively influenced
- Write an integration test (as example see [1])
- Send a PR

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8.0.5/includes/queryprinters/SMW_QP_CSV.php#L92-L100
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/s-0022.json

**Comment by krabina** [comment]
suggestion works as expected. Faster than the speed of light. Amazing, thank you.

regarding the next tasks: 
* Confirm other outputs: this will take a while since I am building up a wiki with this change in the next couple of weeks
* Write an integration test: I have never done that and will probably not be able to learn this in the next weeks. However there is documentation on this if someone else wants to step in: https://www.semantic-mediawiki.org/wiki/Help:Integration_tests

**Comment by kghbln** [comment]
> regarding the next tasks:

@krabina I guess we can split the effort here:

> Confirm other outputs:

No need to wait. Little examples as on [this page](https://sandbox.semantic-mediawiki.org/wiki/Issue/3620/quantity) are sufficient. I created a list of prospective datatype which are likely to be affected. [Just create the missing pages.](https://sandbox.semantic-mediawiki.org/wiki/Issue/3620)

> Write an integration test:

Once the little examples are available I will try to create the integration tests and submit a pull.

**Comment by krabina** [comment]
I created the missing pages. As soon as we have the fix in sandbox we can test the results.

Datatype temperature has the same behaviour as quantity.

**Comment by kghbln** [comment]
> I created the missing pages. As soon as we have the fix in sandbox we can test the results.

I am up not. This [example](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2826/files) should help doing it.

**Comment by krabina** [comment]
> Write an integration test: I have never done that and will probably not be able to learn this in the next weeks.

In the near future I must say :-/  
This is an idea for the tutorial day of the next SMWCon. So please don't wait for me to do this...
