### ISSUE TITLE
"plainol" and "plainul" formats for rendering without HTML needed

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3623]
### Setup and configuration

- MediaWiki | 1.31.1 (632c3b6)16:10, 16 January 2019
- PHP | 7.0.32-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.24-0ubuntu0.16.04.1
- Semantic MediaWiki | 3.0.0 (abdec88) 22:29, 11 October 2018
- Semantic Result Formats | 3.0.0 (36ced8d) 09:15, 12 October 2018

### Issue
As a result of the list formats rework (#2488) the "ol" and "ul" format provide HTML with class attributes allowing for easier manipulation with CSS etc. However some result formats depending on the output of ordered and unordered lists of results may require an output without HTML class attributes to work, e.g. the "listwidget" format perhaps another format, too. See https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/449 for detailed information.

Thus the "plainol" and "plainul" formats rendering without HTML class attributes etc. are needed analogous to the "plainlist" format.

### Steps to reproduce
See [this page](https://www.semantic-mediawiki.org/wiki/Demo:Listwidget_paginated_list) as a result of "listwidget" gone wild.

**Comment by s7eph4n** [comment]
I am not fundamentally against "plainol" and "plainul", but I have two points that I think should be investigated before creating them.

First, we should understand what the problem with the ListWidget is. I am not convinced that simply removing html classes will do the trick. After a first quick glance it seems that the ListWidget format is using an internal interface that does not exist anymore: It sets `$this->format` (which is _protected_) to "ol" or "ul" and expects that the ListFormat is using this setting. Which it does not.

Second, it might be better to not use ListFormat directly, but a [ListResultBuilder](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/ListResultPrinter/ListResultBuilder.php).

**Comment by kghbln** [comment]
Thanks for your comment. It appears that the code change proposed for the listwidget format indeed without creating "plainol" or "plainul".

Still cases may perhaps arise where these two formats would serve goodness. Thus closing but adding this feature request to the "Enhancements and features" project.
