### ISSUE TITLE
Allow querying of page_props

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3625]
### Setup and configuration

- SMW version: 3.0.0

### Issue

It would be useful if you could query the [page_props table](https://www.mediawiki.org/wiki/Manual:Page_props_table).

For [behavior switches](https://www.mediawiki.org/wiki/Help:Magic_words#Behavior_switches): `[[Has switch::__DISAMBIG__]]`

or page properties in general: `[[Has pageprop::propname]]`, `[[Has pageprop::propname;propvalue]]`

**Comment by kghbln** [comment]
Thanks for proposing this feature. I personally see this as a feature to be implemented via special properties hence via the [Semantic Extra Special Properties](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties) extension. Anyways @mwjames could assess much better here.

**Comment by s7eph4n** [comment]
I do not think that this should be a core SMW feature. Might be added to [SemanticExtraSpecialProperties](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties) or even better put into it's own extension. "SemanticPageProps" or something like that.

**Comment by mwjames** [comment]
> even better put into it's own extension. "SemanticPageProps" or something like that.

Most likely (see below).

> Allow querying of page_props

### Questions

- What is the user case for querying `[[Has switch::__DISAMBIG__]]` and what do I do with those results?
- Why do we need access to the `page_props` and for what purpose when retrieved values have no direct reference to any other SMW entity (expect maybe for the Title -> Subject)?
- What page properties require access that can't be stored directly in SMW?

### General notes

The `page_props` table is not owned by SMW and the `QueryEngine` has currently no adapter to query "foreign" (meaning not owned by SMW) tables.

Furthermore, given that this an internal MediaWiki table, no support can be given (unless replication is implemented) for the `SPARQLStore` and `ElasticStore`, yet we generally try to achieve parity which makes this request rather special.

### Technical notes

You would need to write an `ValueDescription` adapter (similar to what was done on the full-text support)  and match those special properties and value interpretation to retrieve results via the standard `QueryResult` interface.

PS: As noted in 3629, if the ticket cannot find a sponsor within the next 90 days then it will be closed and moved to the `Enhancements and features` project.

**Comment by Larivact** [comment]
Thanks for your thorough response, you raise good questions. I was mainly envisioning this as a way to let SMW query data, set from extensions unaware of SMW, but I can see that this is not really what SMW is intended for.
