### ISSUE TITLE
Attachment links

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3640]
### Setup and configuration

- SMW version: all

### Feature

The "Media" in MediaWiki always gets a bit neglected with MW-core file upload and metadata retrieval to be rudimentary at best but nothing we can do about besides making sure users annotate files and images accordingly and have something like SESP to annotate the EXIF data (if available).

What SMW can do to improve the interaction with attachments (files, images) on a per page basis is to have:
- Automatically annotate embedded files and images (`_ATTCH_LINK`)
- Use the existing infrastructure of the `Factbox` to show an additional tab that lists those attachment links as a compact list of links

This will allow a user to uncover attachments easily without having to sift through the raw text.

### Example

![image](https://user-images.githubusercontent.com/1245473/51431412-442f6a00-1c20-11e9-90fe-331e466fda1c.png)

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/wiki/Help:Attachment_links)
