### ISSUE TITLE
#HashTag annotation support

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3651]
### Setup and configuration

- SMW version: all

### Feature 

Semantic MediaWiki serves different user groups, some of them may seek a `#hashTag` [0] support to simplify the annotation process such as adding keywords (see #3020) to a text without having to remember a specific property, yet want be able to query those tags using the standard SMW infrastructure and query interface.

It is proposed to use `$smwgHashTagProperty` as setting (by default disabled) that defines the global property to be used whenever a `#...` annotation appears and is turned into a SMW annotate value. Given that the `Keyword` type normalizes any upper/lower casing it provides best type and allows for additional match agility without requiring users to manually transform those tags (e.g. #FOO == #foo == #FoO).

### Example

![image](https://user-images.githubusercontent.com/1245473/51443896-0bf35e80-1ce8-11e9-8565-3faead9fe576.png)

### Notes

"...# (also known as the hash character) in front of a string of alphanumeric characters, usually a word or unspaced phrase, in or at the end of a message. The hashtag may contain letters, digits, and underscores. " [0]

[0] https://en.wikipedia.org/wiki/Hashtag

**Comment by kghbln** [comment]
This is a good idea and will be a cool feature. However using the pound here may confuse users since wiki links within a page are also using the pound and render identically. Thus SMW needs somehow to adapt the user facing display to make sure that both cannot be confused.

**Comment by mwjames** [comment]
> the pound here may confuse users since wiki 

`#` is the recognized character for a hash tag, not sure about using a different identifier since that would no longer be hash tag.

> SMW needs somehow to adapt the user facing display to make sure that both cannot be confused.

I'm not sure I understand what you mean by "adapt the user facing display".

**Comment by kghbln** [comment]
> .. is the recognized character for a hash tag, not sure about using a different identifier since that would no longer be hash tag.

Indeed. That's why I figure that the "user facing display" of the link should be adapted.

> I'm not sure I understand what you mean by "adapt the user facing display".

If you just see something like `#Notes` you will not be able to see if it is a hash-tag annotation or an intra-page link. Currently I have no decisive idea how it could look like, perhaps `#::Note` for the annotation.

**Comment by mwjames** [comment]
> it links to a query for the respective pages with that keyword the pound does not need to be rendered either.

We store the tag without the hash symbol, so any query will look like `[[Has keyword::test]]` for a `#test` tag.

**Comment by s7eph4n** [comment]
I like the feature. I wonder though if it should be part of core SMW.

**Comment by mwjames** [comment]
> I like the feature. I wonder though if it should be part of core SMW.

Well, the code itself (without tests) is roughly as seen and would be part of the `InTextAnnotationParser`.

```
+		// Process `#...` tags
+		if ( $this->hashTagProperty && $this->hashTagProperty !== '' ) {
+			// Twitter regex (include underscore and not start with a number):
+			// (?<=^|\P{L})(#\b\p{L}[\p{L}\d_]+)
+
+			// Allow to start with a number
+			$text = preg_replace_callback(
+				'/(?<!&|\S)#(\w+)/u',
+				function( $matches ) {
+					return $this->addPropertyValue(
+						[ $this->hashTagProperty ],
+						$matches[1],
+						$matches[0]
+					);
+				},
+				$text
+			);
+		}
```

If you wanted to move this to an extension then we would need to add a hook to `InTextAnnotationParser` and make the `addPropertyValue` public (otherwise you have to rewrite that part for the extension).

**Comment by s7eph4n** [comment]
It just seems to me that from a high-level perspective this feature would be a candidate for a separate extension. I don't know enough about that class to have an opinion on whether it is worth the effort to break it out or not, so whatever you decide is fine with me.

(Having this hook would also open up the possibility of similar extensions where an attribute is set by annotations other than the classic [[foo::bar]]. Will that ever be used, though?)

**Comment by jaideraf** [comment]
This feature used with [`tagcloud` format](https://www.semantic-mediawiki.org/wiki/Demo:Tagcloud/Tagcloud_using_the_sphere_widget) from SRF is going to be awsome!

**Comment by jaideraf** [comment]
I am sorry, I have just read about the [Formatter rule](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3020#issue-169846837) now. The text answers my questions above: it links to special pages Ask or SearchByProperty.

**Comment by mwjames** [comment]
> It just seems to me that from a high-level perspective this feature would be a candidate for a separate extension. 

Okay, I decided that we will go with a hook (#4169) that can be registered and contain a `HashTagPasrer` as demonstrated in [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/examples/hook.parser.afterlinksprocessingcomplete.md

**Comment by JeroenDeDauw** [comment]
Just reading this now and was going to suggest to only create an extension mechanism if there is an additional use case. I'm great at timing right?

I don't see an issue with having the hook though recommend not spending time on putting this in an extension since there is likely many better things to do with ones time.

**Comment by kghbln** [comment]
> Okay, I decided that we will go with a hook (#4169) that can be registered and contain a HashTagPasrer as demonstrated in [0].

Ok, so this will be a dedicated extension when implemented.

> I don't see an issue with having the hook though recommend not spending time on putting this in an extension since there is likely many better things to do with ones time.

This appears to be something for starters to implement.

**Comment by mwjames** [comment]
>
> This appears to be something for starters to implement.

For some inspiration, see [0].

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/examples/hook.parser.afterlinksprocessingcomplete.md
