### ISSUE TITLE
Content of frames of multiple-instance form termplates

### ISSUE THREAD

**Issue by agharbeia** [SemanticMediaWiki/SemanticMediaWiki#3692]
reference: [https://sourceforge.net/p/semediawiki/mailman/message/36439738/](https://sourceforge.net/p/semediawiki/mailman/message/36439738/)

Make it possible to have content such as a descriptive paragraph appear within the labelled frame of a multi-instance form template (created by `|label=` on the definition of the sub-form template) but not have that text repeated with every added instance of the form.

Currently, if text is added within the embedded template definition it is repeated with every instance.

Alternatively, if text is added in the parent form then it is out of the boundary of the frame of the sub-form.

**Comment by kghbln** [comment]
Isn' t this about Page Forms handling multi-instance templates?

**Comment by mwjames** [comment]
> reference: https://sourceforge.net/p/semediawiki/mailman/message/36439738/

This is unrelated to SMW. Please direct such requests to the correct channel (PageForm extension).

**Comment by agharbeia** [comment]
Correct. My fault.
