### ISSUE TITLE
Allow subobject nesting (subsubobjects)

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3702]
### Setup and configuration

- SMW version: 3.0.0

### Issue

The [#subobject](https://www.semantic-mediawiki.org/wiki/Help:Adding_subobjects) parser function apparently cannot be nested, which can be desirable.

Syntax suggestion:

```
{{#subobject:
|Has property 1=value
|Has property 2=values
|{{#subobject:
 |Has property 1=value
 |Has property 2=values
}}
}}
```

**Comment by mwjames** [comment]
```
{{#subobject:
|Has property 1=value
|Has property 2=values
|{{#subobject:
 |Has property 1=value
 |Has property 2=values
}}
}}
```

This won't work as each entity (meaning a subobject) needs a context of the embedding instance but you run into the same problems as described in (#3654) about how parser functions work in MW. The second `#subobject` is unable to determine that its context object is the first `#subobject` and not the embedding subject (== wiki page).

There are other issues but (without having delved into it) I would guess above is a general show stopper for the proposed syntax .

**Comment by Larivact** [comment]
I guess a good alternative would be a `return identifier = yes` parameter for `#subobject`, which would allow for:

```
{{#subobject:
|Has property 1=value
|Has property 2=values
|Has subthing={{#subobject:
 |Has property 1=value
 |Has property 2=values
 |return identifier=yes
}}
}}
```

**Comment by mwjames** [comment]
> I guess a good alternative would be a return identifier = yes parameter for

It doesn't work like this, the second `#subobject` needs the reference of the first. In your example the first gets the reference of the second while semantics for the subtree are subject -> `#subobject` (first) -> `#subobject` (second), so the second has to "know" that it belongs to the first (which it cannot as outlined above).

**Comment by Larivact** [comment]
Note that I wrote `Has subthing` not `Has subobject`. While these two subobjects would be siblings, `return identifier = yes` would still allow to construct a hierarchy outside of the subtree.

**Comment by mwjames** [comment]
Besides the technical aspect, what is the use case here? What sort of data would require such construct?

**Comment by Larivact** [comment]
Articles that mention books with multiple editions.

**Comment by mwjames** [comment]
The following is a quick hack (untested == contains caveats yet to be found, no guarantees) but it should provide an idea of what is required to make the semi tree structure available (for example the change fails for SG [0]).

For those who want (it ain't me) to implement this:

- Test the code path (I mean it!! and improve it, it is just a rough sketch)
- Make field tests with existing store implementations
- Write appropriate integration tests
- Test with other extensions (see [0])
- Limit the hierarchy depth, and so on ...

Whether this is a functionality we want to support or not (maintenance cost, hidden technical debt, errors that may arise due to hierarchy dependencies etc.) is a different discussion.

### Changes

```diff
@@ -46,10 +46,12 @@ class SubobjectParserFunction {
 	 * Fixed identifier that describes a property that can auto-linked the
 	 * embeddedding subject
 	 */
 	const PARAM_LINKWITH = '@linkWith';
 
+	const PARAM_EMBEDDED = '@embedded';
+
 	/**
 	 * @var ParserData
 	 */
 	protected $parserData;
 
@@ -81,10 +83,12 @@ class SubobjectParserFunction {
 	/**
 	 * @var boolean
 	 */
 	private $isComparableContent = false;
 
+	private $embedded = false;
+
 	/**
 	 * @since 1.9
 	 *
 	 * @param ParserData $parserData
 	 * @param Subobject $subobject
@@ -167,11 +171,11 @@ class SubobjectParserFunction {
 		// An empty output in MW forces an extra <br> element.
 		//if ( $html == '' ) {
 		//	$html = '<p></p>';
 		//}
 
-		return $html;
+		return $html . $this->embedded;
 	}
 
 	protected function addDataValuesToSubobject( ParserParameterProcessor $parserParameterProcessor ) {
 
 		// Named subobjects containing a "." in the first five characters are
@@ -190,10 +194,11 @@ class SubobjectParserFunction {
 
 		$this->subobject->setEmptyContainerForId(
 			$id
 		);
 
+		$this->embedded = $this->embedded ? $id : '';
 		$subject = $this->subobject->getSubject();
 
 		foreach ( $parameters as $property => $values ) {
 
 			if ( $property === self::PARAM_SORTKEY ) {
@@ -202,10 +207,19 @@ class SubobjectParserFunction {
 
 			if ( $property === self::PARAM_CATEGORY ) {
 				$property = DIProperty::TYPE_CATEGORY;
 			}
 
+			if ( $property === 'Has subobject' ) {
+				$subSemanticData = $this->parserData->getSemanticData()->findSubSemanticData( end( $values ) );
+				$this->subobject->getSemanticData()->addPropertyObjectValue(
+					new DIProperty( '_SOBJ' ),
+					new \SMWDIContainer( $subSemanticData )
+				);
+				continue;
+			}
+
 			foreach ( $values as $value ) {
 
 				$dataValue = DataValueFactory::getInstance()->newDataValueByText(
 						$property,
 						$value,
@@ -251,10 +265,15 @@ class SubobjectParserFunction {
 		return [ $parameters, $id ];
 	}
 
 	private function preprocess( ParserParameterProcessor $parserParameterProcessor, $useFirst ) {
 
+		if ( $parserParameterProcessor->hasParameter( self::PARAM_EMBEDDED ) ) {
+			$this->embedded = true;
+			$parserParameterProcessor->removeParameterByKey( self::PARAM_EMBEDDED );
+		}
```

### Usage

```
{{#subobject:
 |Has text=test
 |Has subobject={{#subobject:
  |Has page=123
  |@embedded=true
  |Has subobject={{#subobject:
   |Has page=123,1234|+sep=,
   |@embedded=true
  }}
 }}
}}
```
```
{{#ask: [[Has text::test]]
 |?Has text
 |?Has subobject
 |?Has subobject.Has page
 |?Has subobject.Has subobject.Has page
}}

{{#ask: [[Has page::123]]
 |?Has page
 |?Has subobject
 |?-Has subobject.Has text
 |?-Has subobject.Has subobject.Has text
}}
```

![image](https://user-images.githubusercontent.com/1245473/52537174-69188800-2d5b-11e9-8695-9dc7ef03d2f7.png)

### Notes

[0] `  as it returns "[39e98b4cffe23e9ab6c97a72] /mw-master-pg2/index.php?title=Subsubobject&action=submit TypeError from line 81 of ...\extensions\SemanticGlossary\src\Cache\CacheInvalidator.php: Argument 2 passed to SG\Cache\CacheInvalidator::invalidateCacheOnStoreUpdate() must be an instance of SMW\SemanticData, null given, called in ...\extensions\SemanticGlossary\src\Cache\CacheInvalidator.php on line 135")`

**Comment by kghbln** [comment]
We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
