### ISSUE TITLE
IndexerRecoveryJob to cause "RuntimeException Indexer.php: Missing ID: ..."

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3705]
### Setup and configuration

- MediaWiki | 1.32.0 (8a2f437)00:17, 10. Feb. 2019
- PHP | 7.0.33-0+deb9u1 (apache2handler)
- MariaDB | 10.1.37-MariaDB-0+deb9u1
- Elasticsearch | 6.6.0

### Issue

```
2019-02-11 09:46:03 phalaris 0210020150926-02100_: [f054efd5e3da05653c32c203] [no req]   RuntimeException from line 310 of /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Indexer.php: Missing ID: Noob.jpg#6##_FILE6b9354efb486ca22e72283c02684f1a0
```
### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/IndexerRecoveryJob.php(122): SMW\Elastic\Indexer\Indexer->create(SMW\DIWikiPage)
#1 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/IndexerRecoveryJob.php(80): SMW\Elastic\Indexer\IndexerRecoveryJob->create(string)
#2 /../w/includes/jobqueue/JobRunner.php(290): SMW\Elastic\Indexer\IndexerRecoveryJob->run()
#3 /../w/includes/jobqueue/JobRunner.php(192): JobRunner->executeJob(SMW\Elastic\Indexer\IndexerRecoveryJob, Wikimedia\Rdbms\LBFactorySimple, BufferingStatsdDataFactory, integer)
#4 /../w/maintenance/runJobs.php(89): JobRunner->run(array)
#5 /../w/maintenance/doMaintenance.php(94): RunJobs->execute()
#6 /../w/maintenance/runJobs.php(122): require_once(string)
#7 {main}
```

### Steps to reproduce
I basically get this for every file uploaded to the wiki. I am not sure if connected but I ran ["rebuildData.php"](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Journal?type=smw&user=&page=&wpdate=2019-02-11&tagfilter=) followed by "rebuildElasticIndex.php" around that time.

**Comment by mwjames** [comment]
> 2019-02-11 09:46:03 phalaris 0210020150926-02100_:
> [f054efd5e3da05653c32c203] [no req]   RuntimeException from line 310 of
> /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Indexer.php: Missing
> ID: Noob.jpg#6##_FILE6b9354efb486ca22e72283c02684f1a0

The `RuntimeException` exception is there on purpose to find cases
where we missed something.

Please try adding the following lines before the exception is thrown
in the `Indexer::create` method.

```
@@ -304,10 +304,14 @@ class Indexer {

 		if ( $this->isSafe() === false ) {
 			return $this->pushRecoveryJob( $title, $params );
 		}

+		if ( $dataItem->getId() == 0 ) {
+			$dataItem->setId( $this->getId( $dataItem ) );
+		}
+
 		if ( $dataItem->getId() == 0 ) {
 			throw new RuntimeException( "Missing ID: " . $dataItem );
 		}
```
