### ISSUE TITLE
Storing HTML entities

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#3707]
### Setup and configuration

- SMW version: 3.0.1
- MediaWiki version: 1.31.1 
- PHP version: 7.1.26
- MySQL version: 5.6.43-84.3

### Issue
SMW 2.5.8 seems to store `{{#set:Has text=&nbsp;}}` as `{{#set:Has text= }}` (with just one space character).

SMW 3.0.1 seems to store `{{#set:Has text=&nbsp;}}` as `{{#set:Has text=&nbsp;}}` (with 6 characters, the HTML entity as is)

I am not talking about displaying it, but storing it. How did I discover this? I used to analyze strings with `{{#sub:string|start|length}}` from [StringFunctions extension](https://www.mediawiki.org/wiki/Extension:StringFunctions##sub:) in SMW 2.5.8. When I upgraded SMW to 3.0.1 some of my templates [0] broke because of this change.

Does this makes sense to you? Maybe the parsing have changed. It's hard to explain... Is there a configuration to bring the behaviour back?

[0] http://wiki.fabricioassumpcao.com/w/index.php?title=Template:Field_string&action=edit

**Comment by kghbln** [comment]
Let's make this is general issue about storing html entities. I personally think that the storage observed with SMW 3.0.0 is preferable. Once stored the software can decide how to render them. If it is already stored in a rendered form when we do not have this choice any longer.

If I am not mistaken the change in behaviour came with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2435

**Comment by mwjames** [comment]
> SMW 3.0.1 seems to store `{{#set:Text=&nbsp;}}` as `{{#set:Text=&nbsp;}}`

The storage of such entities has been as-is, meaning that what the
user has entered is stored and the output as far as I can see is the
same (== `&nbsp;`) for 2.5+ and 3.0+.

Running the test on either 2.5+ or 3.0+ will yield the same result and
passes the test (Note: `&nbsp;` is converted by MW to `&#160;`), so
there is no regression in regards to storage and output.

```
{
	"description": "Test `format=plainlist` and `&nbsp;`",
	"setup": [
		{
			"namespace": "SMW_NS_PROPERTY",
			"page": "Has text",
			"contents": "[[Has type::Text]]"
		},
		{
			"page": "Test:F0212/1",
			"contents": "{{#set:Has text=&nbsp;}}"
		},
		{
			"page": "Test:F2012/Q.1",
			"contents": "{{#show: Test:F0212/1|?Has text}}"
		}
	],
	"tests": [
		{
			"type": "format",
			"about": "#0 (#show with default format `plainlist`)",
			"subject": "Test:F2012/Q.1",
			"assert-output": {
				"to-contain": [
					"<p>&#160;"
				]
			}
		}
	],
	"settings": {
		"wgContLang": "en",
		"wgLang": "en",
		"smwgNamespacesWithSemanticLinks": {
			"NS_MAIN": true,
			"SMW_NS_PROPERTY": true
		}
	},
	"meta": {
		"version": "2",
		"is-incomplete": false,
		"debug": false
	}
}
```

> [StringFunctions
> extension](https://www.mediawiki.org/wiki/Extension:StringFunctions##sub:)

Of course, I cannot account for anything this extension does or maybe
how MW changed the interpretation of such entities between releases.

Cheers

**Comment by kghbln** [comment]
> If I am not mistaken the change in behaviour came with #2435

Well it did not after looking at it again. ;)

**Comment by mwjames** [comment]
> If I am not mistaken the change in behaviour came with
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2435

No, #2435 only deals with "invisible chars" (Right-to-left_mark,
Left-to-right_mark) as it was noted in the ticket.

**Comment by kghbln** [comment]
There is however a slight difference in display: On MW 1.32.0 and SMW 3.1.0-alpha the query result displays as [`Has text:`](https://sandbox.semantic-mediawiki.org/wiki/Issue/3707) whereas on MW 1.27.5 and SMW 2.5.8 it displays as `Has text`. So there is a difference here too. Perhaps remex?

**Comment by mwjames** [comment]
When you use the browser you'll see that `&nbsp;` as output.

MW 1.29, SMW 2.5.8

![image](https://user-images.githubusercontent.com/1245473/52676809-4cc74780-2f23-11e9-9342-6f576f8422d3.png)

MW 1.30, SMW 3.0+

![image](https://user-images.githubusercontent.com/1245473/52676784-315c3c80-2f23-11e9-8d19-d851f2d8096a.png)

> MW 1.27.5 and SMW 2.5.8 it displays as `Has text`. So there is a difference
> here too. Perhaps remex?

As I said, we don't account for MW changes.

**Comment by mwjames** [comment]
> > MW 1.27.5 and SMW 2.5.8 it displays as `Has text`. So there is a difference

... and here your `smw_di_blob` table should have a line that says
`&nbsp;` in the `o_hash` column.

**Comment by jaideraf** [comment]
Well, that is a puzzle then... because I only upgraded SMW and I am preatty sure that this worked before. I know that because that template is a "core" template in that wiki, since november 23, 2017‎ and hugely used.

And yes, I know MW have been changing the parser recently, but, as I said, I only upgraded SMW. And I am not against SMW storing that [new] way, I am just trying to understand what happened. That behaviour was kind of vital for that wiki... Anyway, we are all in good faith here, and the mistery goes on.

**Comment by jaideraf** [comment]
Huuum, maybe [StringFunctions extension](https://www.mediawiki.org/wiki/Extension:StringFunctions##sub:) have changed... I will have a look at it.

**Comment by jaideraf** [comment]
Eureka! Sorry guys, my fault. The problem is that, when upgrading, I did not notice that: 

> → Now you have to use wfLoadExtension( 'SemanticResultFormats' ); in the "LocalSettings.php" file to invoke the extension

So, my template uses ` |format=array` and I did not realise that SRF was not loaded at all.

**Comment by jaideraf** [comment]
When I said 
> I only upgraded SMW

I forgot to mention SRF as well. 
I really sorry for wasting your time. :pensive:

**Comment by jaideraf** [comment]
Guys, just to demonstrate why I had such a problem, please see: https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Jaideraf/3707

I need to use the `array format` because my template needs to count like 4, not like 14 as `list format` does. I am not reopening this issue, I am just better explaining what happened, in case of misunderstanding.

**Comment by mwjames** [comment]
> I need to use the `array format` because my template needs to count like 4,
> not like 14 as `list format` does. I am not reopening this issue, I am just
> better explaining what happened, in case of misunderstanding.

I'm guessing that because of [0]
(`Sanitizer::decodeCharReferences...`) HTML entities are decoded
before an output hereby making `&nbsp;` to be displayed as ` ` which
in total accounts for 4 instead of 14.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/array/SRF_Array.php#L177-L181

**Comment by kghbln** [comment]
I personally think that counting `&nbsp;` as 6 is the more intuitive count. In the end we are storing 6 characters. Rendering is a different pair of shoes I guess.

**Comment by jaideraf** [comment]
> I personally think that counting `&nbsp;` as 6 is the more intuitive count. In the end we are storing 6 characters. Rendering is a different pair of shoes I guess.

I am not so sure... We can say we are _entering_ (and storing) 6 characters, but we can not say we are _displaying_ 6 characters. I guess it is a matter of point of view.

Fortunately, there are these two wonder formats to play with, and I am happy to choose one of them when necessary. :relieved:
