### ISSUE TITLE
Allow filtering on page non-existence

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3709]
### Setup and configuration

- SMW version: 3.0.1

### Issue

While the [page datatype](https://www.semantic-mediawiki.org/wiki/Help:Type_Page) can contain non-existent  pages, there apparently is no proper way to filter on page existence. If you want to only return pages whose property `X` points to an existing page you can do something like `[[X.Modification date::+]]`, however this does not work in reverse because you cannot check for the absence of a property.

I propose the introduction of an `Exists` special property so that you can do `[[X.Exists::1]]` and `[[X.Exists::0]]` in queries.

**Comment by mwjames** [comment]
> While [page
> datatype](https://www.semantic-mediawiki.org/wiki/Help:Type_Page) can
> contain non-existent  pages, there apparently is no property to filter on

Yes, a page type property is allowed to represent entities that are
not matchable to a MediaWiki page (see [0], aka red links) and the
link between a MW page and that of a SMW entity is to be a special use
case.

Of course, it is not helpful that the name of the type (== page)
suggests a direct correlation between SMW and MW where in fact it
represents a resource that is linkable (meaning it is assigned a URI)
and by that, it is most natural to connect this type to a page
representation or link in MediaWiki.

> I propose the introduction of an `Exists` special property so that you can
> do `[[X.Exists::1]]` and `[[X.Exists::0]]`.

By default, an instance of a MW page is to contain a `Modification
date` and to filter those entities that are "real" in a sense of
representing a page you just would add `[[Modification date::+]]` as
condition (see [1]). Adding `[[Modification date::+]]` also removes
subobject entities as those are not represented as a page in the
MediaWiki universe and its instance does not contain a `Modification
date`.

Unless, I missed a use case (or edge case) adding `[[Modification
date::+]]` should be sufficient to assert that only "real" pages are
part of the result set.

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=Yzo1jk0KgzAQhQ9UwkiKXQizERe9xqhjExyNzEQ8U8_RizVWCm_xweP9TEkXythrojFTLwwSl5jR11WhdUYSgcA0shpaSAcYkw5BqGdB5x-BReLm7q3zFe1Z2Qro5227ZMoGg5CVZNJfe_GOOMc_23Jco6ePkLTMINkAaZqMM1bg6vaU7550Fm_04qa5uborgoXieh35Ag

[1] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=YzpFjkEKg0AMRQ9UhpEpdiHMRlx000PEMXaC0ZFJxDP1HL1Yx0op_MUjP_k_Y8ozqO9zgkGhZ7RMM6l3dVVomTww24gwYBYvMe1WEHKIDD2yN-4WkZlWc22Nq2DTjFIgv1-ysYKKDQxSLlP-phdvp4l-LPN-lh6-tymXGg8SbBpHQfWVNXV7yHV3OIJXeGLTXEzdHXLVaT_SQCMFUEpLGQ6g_yU7Ay3ntx8

Cheers

**Comment by Larivact** [comment]
I already mentioned `[[Modification date::+]]`. I am looking for a way to query broken page properties.

**Comment by mwjames** [comment]
> I already mentioned `[[Modification date::+]]`. I am looking for a way to
> query broken page properties.

The mail I received was about "Allow filtering on page existence (#3709)".

> check for the absence of a property.

Well, that is not supported. It could be any combination of ! and
hereby introduces pathological queries that may require extensive
computational power (given any combination of conditions and
hierarchies involved) to prove that something doesn't exists. In SQL,
you may rely on something LEFT JOIN + IS NULL check but you would you
have make those implementable in all stores and is a similar to the
discussion about `NOT in` categories (#1084).

In the past, I made a proposal about mandatory properties to allow for
checking against the "expected" existence but I abandon it as I don't
have the time to finish the implementation for it.

**Comment by Larivact** [comment]
This is not about querying the absence of properties but about querying the absence of pages. While for the former there is [a workaround](https://www.semantic-mediawiki.org/wiki/Help:Querying_for_the_absence_of_a_property) for the latter there is not.

I would also argue that `[[X.Modification date::+]]` is bad semantic-wise because it hides the intention behind a technicality, whereas `[[X.Exists::1]]` directly expresses the intention.

**Comment by kghbln** [comment]
We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
