### ISSUE TITLE
Special pages (list) with subsection support

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3711]
While trying to consolidate our special pages into one coherent section it became clear that collecting all pages into one section creates some inconsistencies where users cannot clearly distinguish pages (by topic, or interest) on a subsection level (as shown below). We would require a tiny change to `SpecialSpecialpages` in MW-core to allow us to define a subsection using `/` as separator in the group name.

### Special page group to indicate a subsection

`/` indicates a subsection and uses a different header element (`h3`) than the main group.

```php
/**
 * @see SpecialPage::getGroupName
 */
protected function getGroupName() {
	return 'smw_group/props';
}
```

### MW-core

The change impact for MW-core should be minimal but it would allows us to create a better experience for users.

```diff
@@ -97,14 +97,22 @@ class SpecialSpecialpages extends UnlistedSpecialPage {

 		$includesRestrictedPages = false;
 		$includesCachedPages = false;

 		foreach ( $groups as $group => $sortedPages ) {
-			$out->wrapWikiMsg(
-				"<h2 class=\"mw-specialpagesgroup\" id=\"mw-specialpagesgroup-$group\">$1</h2>\n",
-				"specialpages-group-$group"
-			);
+			if ( strpos( $group, '/' ) !== false ) {
+				list( $group, $subGroup ) = explode( '/', $group, 2 );
+				$out->wrapWikiMsg(
+					"<h3 class=\"mw-specialpagessubgroup\">$1</h3>\n",
+					"specialpages-group-$group-$subGroup"
+				);
+			} else {
+				$out->wrapWikiMsg(
+					"<h2 class=\"mw-specialpagesgroup\" id=\"mw-specialpagesgroup-$group\">$1</h2>\n",
+					"specialpages-group-$group"
+				);
+			}
```

## Output example

![image](https://user-images.githubusercontent.com/1245473/52633321-e3601e00-2ebb-11e9-93f3-76ac2e6e78c4.png)

**Comment by mwjames** [comment]
@kghbln @hexmode @s7eph4n Would be nice if someone could champion on behalf of SMW for this small change in MW-core.

**Comment by hexmode** [comment]
See [T216467](https://phabricator.wikimedia.org/T216467).

**Comment by mwjames** [comment]
> See T216467.

Thanks

**Comment by kghbln** [comment]
Utterly cool! Thanks a lot. The change was merged in master and will be delivered with MW 1.33 and later in case the back-ports to MW 1.31.x and MW 1.32.x do not make it.

**Comment by kghbln** [comment]
> The change was merged in master and will be delivered with MW 1.33 and later in case the back-ports to MW 1.31.x and MW 1.32.x do not make it though it will be nice in the end.

Ok, so no. Fair enough but worth a try. ;)

**Comment by mwjames** [comment]
Thanks to everyone who got involved to get this deployed quickly without much noise and discussions.
