### ISSUE TITLE
Prefetch lookup

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3722]
When Semantic MediaWiki is resolving a query request (i.e. resolving the parser function `{{#ask ... }}` or `{{#show: ... }}`) it has two distinct tasks to accomplish:
- First, build a query condition in a corresponding language (SQL, ES-DSL, SPARQL) that is understood by the assigned `QueryEngine` where it returns a list of subjects that match the condition (similar to finding rows in a table that match a `WHERE` condition)
- Secondly, build a `QueryResult` object that contains the matched subjects and provide information on the requested printouts (equivalent of columns displayed in a table)

## Issue

The performance of the first task (i.e. retrieving and sorting results that match the condition) mostly depends on the selected `QueryEngine` (and can vary to quite a degree especially when complex disjunctive queries or negation conditions return a large pool of possible results and need to be sorted) where any optimizations is more or less independent of how Semantic MediaWiki is functioning or the `SQLStore` is used as primary data store.

The second task of retrieving printouts for each column and each matched subject is currently designed in a way that each such request creates a dedicated SQL SELECT statement in the `SQLStore` to only fetch those items that are required for the display and means that a result set of 200 subjects with a request for three different properties (e.g `{{#ask: [[__condition__]] |?Foo |?Bar |?Foobar }}`) requires 200 x 3 SELECT requests to fetch all relevant data.

The approach to be able to selectively retrieve data for a single subject does make sense when viewing a page or compare the data during the pre/post storage process but for a bulk (or list) operation it is a fairly sub-optimal solution.

## Solution

To significantly reduce the amount of DB queries required when resolving printrequests yet produce the same result output a refactoring of `SemanticDataLookup` (and `PropertySubjectsLookup` for inverse lookups) is necessary to introduce a so-called prefetch mode (or lookup) to be able to “bulk” load all values at once for a list of subjects (using the `WHERE IN` construct).

Some preliminary tests showed:

Current select method
```
Queries (424)
MediaWiki: 1.31.0
PHP: 7.1.1
Time: 3.40497
Memory: 26.71 MB (Peak: 26.75 MB)
```

Prefetch lookup
```
Queries (30)
MediaWiki: 1.31.0
PHP: 7.1.1
Time: 2.93601
Memory: 26.54 MB (Peak: 26.58 MB)
```

## Notes

![image](https://user-images.githubusercontent.com/1245473/52910686-12e3a180-3293-11e9-9fc9-84b4c0d0c234.png)

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/wiki/Help:$smwgExperimentalFeatures)
