### ISSUE TITLE
Introduce Property:External formatter interwiki

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3728]
### Setup and configuration

- SMW version: 3.0.1

### Issue

It would be handy if you could use existing interwiki prefixes with [Datatype "External identifier"](https://www.semantic-mediawiki.org/wiki/Help:Type_External_identifier), so that you don't have to duplicate the URL with [Property:External formatter URI](https://www.semantic-mediawiki.org/wiki/Help:Special_property_External_formatter_URI), which could be achieved with a new `External formatter interwiki` special property.

Example: `[[External formatter interwiki::bug]]`

**Comment by kghbln** [comment]
Thanks for suggesting.

**Comment by mwjames** [comment]
>It would be handy if you could use existing interwiki prefixes with Datatype "External identifier", so that you don't have to duplicate the URL with Property:External formatter URI, which could be achieved with a new External formatter interwiki special property.

I understand the proposal, I'm unsure whether it is worth the effort
or not in creating an additional formatter just to avoid maintaining
an URL with a place holder.

In case someone wants to work on it:

- Avert any performance issues with the interwiki table lookup (cache
the lookup etc.)
- The interwiki table lookup needs to be isolated from the rest of SMW
by adding a new class (e.g. `InterwikiLookup`) to the `SMW\MediaWiki`
namespace to avoid SMW objects "talking" directly to a MediaWiki table
- Add necessary unit and integration tests

PS: I will review any code (given above points have been followed)
that tries to tackle the request but I won't implement it myself.

**Comment by Larivact** [comment]
I just had a brilliant idea how this can be solved without any code changes:

    [[External formatter uri::{{fullurl:bug:$1}}]]

If you confirm my account request, I can add it as a tip to the wiki.

**Comment by kghbln** [comment]
> I just had a brilliant idea how this can be solved without any code changes:

That's even better.

> If you confirm my account request, I can add it as a tip to the wiki.

Done. :)

**Comment by Larivact** [comment]
Thanks, [added it to the wiki](https://www.semantic-mediawiki.org/wiki/Help:Special_property_External_formatter_URI#Reusing_interwiki_prefixes). Closing this.
