### ISSUE TITLE
Duplicate Entity lookup has plural problem

### ISSUE THREAD

**Issue by kuality** [SemanticMediaWiki/SemanticMediaWiki#3736]
### Setup and configuration

- SMW version: 3.0.1
- MW version: 1.32.0
- PHP version: 7.1.22
- DB system (MySQL, Blazegraph, etc.) and version: MySQL | 5.6.34-log

### Issue
Page Special:SemanticMediaWiki&action=duplookup contains a line 
: <pre>The list contains 3 {{PLURAL:3|entry|entries}} and was retrieved from cache (UTC: Sat, 23 Feb 2019 19:35:54 GMT). </pre>
That {{PLURAL should probably resolve to something, but it just shows up as I posted it here. 

### Steps to reproduce
I have no idea how to make the sandbox throw an error so that this page will be displayed... sorry...

**Comment by mwjames** [comment]
>  The list contains 3 {{PLURAL:3|entry|entries}} a

I have seen this before and the reason is that JS `mw.msg` cannot parse those template replacement messages. I changed the approach and display in SMW 3.1 to avoid the issue in the `Duplicate Entity lookup`.

## Example output

![image](https://user-images.githubusercontent.com/1245473/53291318-274eff00-37a9-11e9-92c8-216e5321525d.png)

**Comment by mwjames** [comment]
@kghbln Simplest fix would be to nuke the `{{PLURAL:3|entry|entries}}`  from the message and use something like `entire(s)` in case you wanted to make a 3.0.2 release.

**Comment by kghbln** [comment]
I guess we talk about "smw-list-count" and "smw-list-count-from-cache" here. These two still appear to be in the code for 3.1.0 and active

**Comment by mwjames** [comment]
> "smw-list-count"

In JS I changed it to:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/c71278767d7294ac82fc7da7818cfef5de9c5aa3/res/smw/special/ext.smw.special.admin.js#L75

>"smw-list-count-from-cache"

In PHP the only reference is in [0] (which can be nuked as well), JS no longer uses it.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?l=PHP&q=smw-list-count-from-cache

**Comment by kghbln** [comment]
Ah, ok, thanks for the info.

> In PHP the only reference is in [0] (which can be nuked as well), JS no longer uses it.

This however should not be back-ported since we would be missing it in 3.0.x, so two pull needed here.

**Comment by kghbln** [comment]
> smw-list-count-plural

I guess this one is missing from master?

**Comment by Nikerabbit** [comment]
> JS component cannot resolve messages with {{PLURAL...

It can if `mediawiki.jqueryMsg` is loaded.

**Comment by kghbln** [comment]
> It can if mediawiki.jqueryMsg is loaded.

Thanks for the info. Worth considering in the future!

**Comment by mwjames** [comment]
> It can if mediawiki.jqueryMsg is loaded.

I didn't know that, wasn't even aware that there is special package for it. Thanks
