### ISSUE TITLE
Support parser extension tags in text annotations

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3753]
### Setup and configuration

- SMW version: 3.0.1

### Issue

SMW currently does not support [parser extension tags](https://www.mediawiki.org/wiki/Parser_extension_tags) in [text](https://www.semantic-mediawiki.org/wiki/Help:Type_Text) annotations. [Extension:Cite](https://www.mediawiki.org/wiki/Extension:Cite) and [Extension:Math](https://www.mediawiki.org/wiki/Extension:Math) are quite popular and it would be nice if their respective tags `<ref>` and `<math>` were usable in text annotations.

When you annotate `[[Has text::<ref>test</ref>]]` you expect the value to become `<ref>test</ref>`.  Currently you however get a [strip marker](https://www.mediawiki.org/wiki/Strip_marker): ([demo](https://www.semantic-mediawiki.org/wiki/User:Larivact/Parser_extension_tag_in_text))

    '"`UNIQ--ref-00000003-QINU`"'

While the [SMW_PARSER_UNSTRIP](https://www.semantic-mediawiki.org/wiki/Help:$smwgParserFeatures#Available_options) option, introduced in #794, sounds helpful, setting it undesirably renders the tags to HTML:

    <nowiki><sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup></nowiki>

Since we do not want to convert extension-specific HTML back to wikicode, a general extension-independent way to support parser extension tags in text annotations is to be found.

**Comment by mwjames** [comment]
If any, this is a feature request.

> Set $smwgParserFeatures = $smwgParserFeatures | SMW_PARSER_UNSTRIP;.
> `<nowiki><img class="mwe-math-fallback-image-inline tex" alt="foo" src="/images/math/a/c/b/acbd18db4cc2f85aedef654fccc4a4d8.png" /></nowiki>`

This is the expected outcome, if you don't want to have those tags unstripped then don't set `SMW_PARSER_UNSTRIP`. SMW_PARSER_UNSTRIP does what it suppose to do, unstrip those parser tags. More information is available with #794.

> Install Extension:Math.

Maybe you can find a sponsor to look at it, I will not able to do so.

**Comment by Larivact** [comment]
>if you don't want to have those tags unstripped then don't set SMW_PARSER_UNSTRIP

Well if I don't set it, the value becomes just a [strip marker](https://www.mediawiki.org/wiki/Strip_marker).

**Comment by mwjames** [comment]
> Well if I don't set it, the value becomes just a strip marker.

I know, but trying to reverse from an unstrip `<img class="mwe-math-fallback-image-inline tex"...` to the canonical representation `<math>` will be difficult and it is one of the reasons why `<ref>` isn't supported (as noted in #794). Maybe there is way around it but that requires effort.

What happens when you annotate `[[Has text::<nowiki><math>foo</math></nowiki>]]`?

**Comment by Larivact** [comment]
I was not proposing extension-specific HTML to be converted back to wikicode. There has got to be an extension-independent way. I widened the scope of this issue and updated its title and description accordingly.

>What happens when you annotate `[[Has text::<nowiki><math>foo</math></nowiki>]]`?

Sets the value to `<nowiki><math>foo</math></nowiki>`, which also isn't desirable.

**Comment by mwjames** [comment]
> I was not proposing extension-specific HTML to be converted back to wikicode. There has got to be an
> extension-independent way.

I wouldn't know one.

### How it works?

Any text (before it reaches SMW) is run through the `Parser` where all `<tag>` tags (including `#set`, `#ask` etc.) get a `UNIQ...` strip maker and will be recursively parsed through the preprocessor/processor (see the `Parser` class for more details) after which the preprocessed (before tidy) text is available to SMW (through the hook system). At this point you only have the HTML available and be able to unstrip (given that you have access to `StripState`) those `UNIQ` marker so that the annotated text can contain an unstriped representation.

**Comment by mwjames** [comment]
@gesinn-it Maybe something for you to have a look at it.

**Comment by Larivact** [comment]
To store extension tags in property values, we need to access them before they are parsed. The only way to do this is with another [extension tag](https://www.mediawiki.org/wiki/Manual:Tag_extensions). The following would work:

```mediawiki
<set prop="Has text">
<math>foo</math>
</set>
```
This comes with the limitation that the `<set>` tag needs to be used directly in the page source code, because as soon as you pass an extension tag to a parser function or template, they are reduced to a strip marker.

This would make using the tag with templates quite akward, e.g:
```
{{Excercise|due=2019-05-01|
<set prop="Has text">
What is <math>1 + 4</math>?
</set>
}}
```

However I have an idea how this could be resolved. We could introduce a new rule  (`Rule:Set tag types` or whatever) that contains an object mapping arbitrary "types" to a property and a template, e.g:
```
{
    "exercise": {
        "property": "Has text",
        "template": "Template:Exercise"
    }
}
```
The above example could then become:
```
<set type=exercise due=2019-05-01>
What is <math>1 + 4</math>?
</set>
```
Note that the type corresponds to a key in the rule object. The tag would do the following:
1. Add a new DataValue with
   * the property corresponding to the type argument and
   * the passed input.
2. Call the template corresponding to the type argument, passing the tag arguments and the tag input as argument `1`.

**Comment by ankostis** [comment]
Wouldn't be too confusing for the developer of a smw-site to decide between the two typical annotation methods (simple `[[prop::value]]` wikilink or `{{#set:prop=value}}` parser-func) or to resort to the new rule pattern?

Btw, wanted to add the following documentation section that lists the pros & cons of the existing 2 choices, but didn't know where to append it?
```wiki
* There are, roughly, 4 ways to build a semantic-template: 
*; 1. simple-annotations (e.g. {{code|[[foo prop::value]]}}):
*: values displayed ''formatted'' (as links / with units, aliased page-titles, etc) 
*: '''BUT''' cannot use values with wiki-syntax (e.g. {{code|[[Description::See [[Help:FAQ]]]]}}) does not parse) ''even if'' [[mw:Help:$smwgEnabledInTextAnnotationParserStrictMode|parser strict mode]] is disabled (note: default is enabled).
*; 2. {{code|#set}} annotations + accompanied by respective {{code|#show}} query
*: Can set any value,  displayed formatted automatically,
*: '''BUT''' it is ''expensive'' (if there many annotations + {{code|#show}}-queries on a page).
*; 3. {{code|#set}} annotation using [[smw:Help:Setting_values/Working_with_the_template_parameter|the {{code|template}} parameter]].
*: Can set any value, fast,
*: '''BUT''' needs manual templating work to format the displayed values (and not always working).
*; 4. Massive {{code|#set}} annotations, and a ''single'' {{code|#ask}} query
*: Can set any value, automatically formatted, fast
*: '''BUT''' {{code|#ask}} needs templating work for the whole results (i.e. may require elaborate use of result-formatting templates).
* Properties "imported" from external vocabularies: {{fullurl:Special:PrefixIndex|prefix=smw+import&namespace=8}}
* Remember to inspect [[Special:ProcessingErrorList]] for '''SMW problems''', included in the [[Velawiki:Data issues]] "gardening" page.
```

**Comment by kghbln** [comment]
This https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3753#issuecomment-469058803 sounds more like it should be part of an extra specialized extension.

**Comment by kghbln** [comment]
> Btw, wanted to add the following documentation section that lists the pros & cons of the existing 2 choices, but didn't know where to append it?

I'd add it to a dedicated page like https://www.semantic-mediawiki.org/wiki/Help:Which_annotation_syntax_to_choose or something similar which can be linked to from various other pages. This is however off topic to this issue so we should continue on wiki if there is need to talk further.

**Comment by Larivact** [comment]
So supporting parser extension tags is not deemed necessary enough to be part of core SMW? I would be willing to work on this, if it was accepted.
