### ISSUE TITLE
Remove `template arguments` and add `named args` to `templatefile` result printer

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3760]
### Setup and configuration

- SMW version: 3.+

### Issue

For the `templatefile` format (#3024), remove `template arguments` and add `named args` to have the same parameters/behaviour as the other formats using a template.

refs https://www.semantic-mediawiki.org/wiki/Thread:Help_talk:Templatefile_format/beacon_export_not_working/reply

**Comment by adarshPatel509** [comment]
Hi @mwjames , I would like to work on this issue. Thanks!

**Comment by adarshPatel509** [comment]
I am new contributor on WikiMedia , can u guide me from where to get started to work on this issue?.
Thanks!

**Comment by mwjames** [comment]
>I am new contributor on WikiMedia , can u guide me from where to get started to work on this issue?.
Thanks!

Welcome.

First, so you should have a look at https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/architecture/README.md to get a frist impression about Semantic MediaWiki.

As for this task and once you have familiarized yourself, have a look at:

- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/TemplateFileExportPrinter.php (this the class where we want to remove `template arguments` and add `named args`)
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/CategoryResultPrinter.php shows how to use `$this->params['named args']`
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/s-0025.json the integration test for `format=templatefile`

The task isn't just about changing some lines of PHP but to ensure that those changes are tested and actually return the expected results.

**Comment by adarshPatel509** [comment]
Thanks @mwjames , I will go through what you have suggested.
