### ISSUE TITLE
Duplicate properties due to consecutive spaces in Record field-names joined only partially

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3764]
### Setup and configuration

- MW version: 2.5.8
- SMW version: 1.31
- DB system: MariaDB | 10.1.34-MariaDB-0ubuntu0.18.04.1
- ICU: 60.2
- LuaSandbox: 3.0.1
- Lua: 5.1.5

### Issue
When defining the fields of a `Record` (or `Reference`) property, if a name of a field contains (by mistake?) more than one space, like `[[Has fields::Two_spaced__field;other field]]` (notice there are 2-spaces between `spaced` & `field` words), then the spaces are "joined" internally by MW, but SMW does not follow:
* the link on the record-property's page points to a sub-field property-page with all spaces joined, 
* BUT any values assigned to that record end-up to the original 2-spaced field-property (which is non existent).

Eventually, the wiki ends up with 2 properties listed in `[[Special:Properties]]`, and of course the type of the single-spaced property is ignored for record-values.

Since there is a discrepancy in what you view in the rendered record-property page and its _sources_ (which might originate from templates), this bug is very hard to detect.

### Steps to reproduce
See [`Category:Spaces-in-records` sample](https://sandbox.semantic-mediawiki.org/wiki/Category:Spaces-in-records)

**Comment by kghbln** [comment]
Thanks for reporting. I believe you should avoid naming properties with two consecutive spaces since at this point MediaWiki kicks in and joins because two spaces are no longer permissive with recent versions. I think the names should be joined consistently in all spots.

**Comment by ankostis** [comment]
Yes sure.  The 2-spaces were a mistake of mine, that was hard to debug, so i wrote this report.

**Comment by ankostis** [comment]
For anyone else afflicted, i had to use `?action=raw&templates=expand`  on the record-property to discover the error.
