### ISSUE TITLE
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3765]
### Setup and configuration
- MediaWiki | 1.31.1 (9ea0a46)17:34, 18. Feb. 2019
- PHP | 7.0.33-0+deb9u1 (apache2handler)
- MariaDB | 10.1.37-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.1

### Issue
```
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /../extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php on line 225
```

### Steps to reproduce
This rarely happens and not every time I perform a similar action. However the actions triggering this are edit actions.

referer: https://www.example.org/index.php?title=190017&action=edit
referer: https://www.example.org/index.php?title=190031&action=edit

Pages 190018 to 190030 did not trigger the warning though their content is similar.

**Comment by mwjames** [comment]
Hi,

> PHP Warning:  call_user_func() expects parameter 1 to be a valid callback,
> no array or string given in
> /../extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php
> on line 225

Haven't seen this once.

> This rarely happens and not every time I perform a similar action. However
> the actions triggering this are edit actions.

The only thing that comes to my mind is that [0] sets the null here,
so to mitigate the issue let's try the following:

- Go to [1] and change `private function emptyCallback` to `protected
function emptyCallback`
- Go to [0] and change `$this->callback = null;` to `$this->callback =
[ $this, 'emptyCallback' ];`

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.0.x/src/MediaWiki/Deferred/TransactionalCallableUpdate.php#L174
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.0.x/src/MediaWiki/Deferred/CallableUpdate.php#L326

Cheers
