### ISSUE TITLE
Add display format to show namespaces in links

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3766]
### Setup and configuration

- SMW version: 3.0.1

### Issue

There appears to be neither an [#ask option](https://www.semantic-mediawiki.org/wiki/Help:Inline_queries#Parser_function_.23ask) nor a [display format](https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#Display_format) to show namespaces of links. This is such a basic use case that you should not need to use a plain format with a template.

**Comment by mwjames** [comment]
Hi,

> to show namespaces of links. This is such a basic use case that you should
> not need to use a plain format with a template.

The request is unclear. Do you mean the subject list or the printouts?
In case of a printout you can introduce something like `#-ns` as
output formatter but for the subject list each individual result
printer decides whether to use the short or the long form (i.e. a
subject prefixed with a namespace).

In case you always want to see the long form then you may add a flag
(see `smwgDVFeatures`) and modify the behaviour of [0] accordingly.

Anyway, this is a feature request and if someone wants to work on this:

- [ ] Clarify the intent and scope
- [ ] Send a PR where the current behaviour remains the default
- [ ] The PR will cover both unit (testing the newly introduce
behaviour) and integration tests (to compare before and after, parsing
of results and output validation, existing tests shouldn't be changed)

This task isn't particularly difficult but requires some diligence to
avoid introducing some hidden behaviour changes on part of the `_wpg`
datavalue.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/datavalues/SMW_DV_WikiPage.php

Cheers

**Comment by krabina** [comment]
I am also in favour of this feature request. I was about to write the same thing.

For printouts I think the following options  make sense in accordance to the printouts of custom units:
```
|?My value # - gives "City:Berlin" (full page name = namespace and page name)
|?My value # -p gives "Berlin" (just the page name)
|?My value # -ns gives "City:" (just the namespace part of the full page name)
```
For a subject list, I could imagine actually the same behaviour if you use the "?" as printout for the mainlabel
```
|mainlabel=-
|? #
```

**Comment by krabina** [comment]
another variant is of course to make use of the already existing parameter "link="
So we could have
```
|link=all# - gives all links including namespaces
|link=subjectl# - gives links only in subjects including namespaces
|link=nonel# - gives the page names including namespaces, but without links
```

**Comment by mwjames** [comment]
> |?My value # - gives "City:Berlin" (full page name = namespace and page
> name)
> |?My value # -p gives "Berlin" (just the page name)
> |?My value # -ns gives "City:" (just the namespace part of the full page
> name)

I'm guessing this to be similar to [0].

PS: If someone makes an effort  then I will review any PR that uses a
clean approach (#2552 has a note about it) to format the output based
on a printout.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2552

**Comment by mwjames** [comment]
> So we could have
> ```
> |link=all# - gives all links including namespaces
> |link=subjectl# - gives links only in subjects including namespaces
> |link=nonel# - gives the page names including namespaces, but without links
> ```

The `link` parameter is only available to the `ResultPrinter` which
means you would have to implement those options for each individual
printer where you'd like to see support for it therefore the printout
`#` parameter seems a better choice where each individual `DataValue`
can be formatted without having to care for the printer used.

Cheers

**Comment by kghbln** [comment]
We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
