### ISSUE TITLE
Unremovable SMW properties

### ISSUE THREAD

**Issue by FO-nTTaX** [SemanticMediaWiki/SemanticMediaWiki#3849]
### Setup and configuration

- SMW version: 3.0.1
- MW version: 1.31.1
- PHP version: 7.0.33-0+deb9u3
- DB system (MySQL, Blazegraph, etc.) and version: 10.2.21-MariaDB-10.2.21+maria~stretch

### Issue
When I go to this page [1], it does not show certain properties that shouldn't be defined, however searching for a certain property nets me a result from that page [2]. The property does not seem to have a value for the page, but it still has one. 

I've tried both using the button "Outdated entities disposal" and a full data rebuild to no avail. Even blanking the page this is observed on [3] entirely does not remove the property value. The same issue is true for all similar pages we have though, not necessarily related to this specific page.

The SMW `{{#set:}}` in the template [4] that usually sets this property is inside an `{{#if:}}` of Extension:ParserFunctions, in case that makes any difference.

At this point I'm out of ideas what to try to remove this property value, any suggestions are welcome.

[1] https://liquipedia.net/dota2/Special:Browse/:User:BlueOceanz-2FBlueOceanz
[2] https://liquipedia.net/dota2/index.php?title=Property%3AHas+nationality&limit=100&offset=0&filter=BlueOceanz
[3] https://liquipedia.net/dota2/User:BlueOceanz/BlueOceanz
[4] https://liquipedia.net/dota2/Template:Infobox_player

### Steps to reproduce
I have included links to the relevant pages above.

**Comment by mwjames** [comment]
> When I go to this page [1], it does not show certain properties that
> shouldn't be defined,

I don't understand the issue, looking at [0] I see the following
properties, so which of them are unremovable?

```
Has birth day
November 8, 2002  +
Has query
bLink +  and bLink +
Display title of
bLink  +
Modification date
16:08:30, 26 March 2019  +
```

[0] https://liquipedia.net/dota2/Special:Browse/:User:BlueOceanz-2FBlueOceanz

**Comment by trevize23** [comment]
> I don't understand the issue, looking at [0] I see the following properties, so which of them are unremovable?

The issue is not with [0] (or OP's [1]), but the property value will still show up in [2].

**Comment by kghbln** [comment]
It appears to me that the current example properly sets  the property values. So we cannot see what is going on in the described situation. What about changing the page to a state where you believe not to set any values but still have a value in [2]?

**Comment by FO-nTTaX** [comment]
Isn't that exactly what my example up there is? It should not set Property:Has_nationatily, yet there is a value in [2].

**Comment by mwjames** [comment]
> Isn't that exactly what my example up there is? It should not set
> Property:Has_nationatily, yet there is a value in [2].

Well, then this belongs into the problem statement to clearly state
what, when, how. Taken aside the semantics of how to construct a bug
report.

I looked at it and I'm currently unable to determine why `[[Has
nationality::BlueOceanz]]` shows up for the
`User:BlueOceanz/BlueOceanz` subject given that [1] has no assignments
for it.

The only hypothesis I have at the moment is that we have more than one
`User:BlueOceanz/BlueOceanz` representations.

## Questions

- Can you confirm that in table `wikidota_smw_object_ids` there is
only one object that matches the `User:BlueOceanz/BlueOceanz`
representation.
- Does the `Duplicate entities lookup` contain any entries for
`User:BlueOceanz/BlueOceanz`

### Note

From the debug output [2], we know `20091` represents the property
`Has nationality`.

```
SELECT DISTINCT
  t0.smw_id AS id,
  t0.smw_title AS t,
  t0.smw_namespace AS ns,
  t0.smw_iw AS iw,
  t0.smw_subobject AS so,
  t0.smw_sortkey AS sortkey, t0.smw_sort
FROM
  `wikidota_smw_object_ids` AS t0
INNER JOIN
  `wikidota_smw_di_blob` AS t1 ON t0.smw_id=t1.s_id
WHERE
  (
   (t1.o_hash='BlueOceanz') AND t1.p_id='20091')
  AND t0.smw_iw!=':smw'
  AND t0.smw_iw!=':smw-delete'
  AND t0.smw_iw!=':smw-redi'
ORDER BY
  t0.smw_sort ASC
LIMIT
  55
OFFSET
  0
```

The ask query `[[Has nationality::BlueOceanz]]` and the `BlueOceanz`
filter on the property page `Has nationality` use the same query.

[0] https://liquipedia.net/dota2/User:BlueOceanz/BlueOceanz
[1] https://liquipedia.net/dota2/api.php?action=browsebysubject&subject=User:BlueOceanz/BlueOceanz
[2] https://liquipedia.net/dota2/index.php?title=Special:Ask&q=%5B%5BHas+nationality%3A%3ABlueOceanz%5D%5D&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FHas+nationality%0A&sort=&order=asc&eq=yes&offset=0&limit=50&debug=true#search

**Comment by FO-nTTaX** [comment]
> Well, then this belongs into the problem statement to clearly state what, when, how. Taken aside the semantics of how to construct a bug report.

That's what I tried to say with

> The property does not seem to have a value for the page, but it still has one.

I'll try to use better English next time, it's not my native language, sorry about that.

As for the Questions: 

> - Can you confirm that in table `wikidota_smw_object_ids` there is only one object that matches the `User:BlueOceanz/BlueOceanz` representation.

For `select * from wikidota_smw_object_ids where smw_title = 'BlueOceanz/BlueOceanz' and smw_namespace = 2;` I get 5 rows:

```
+---------+---------------+-----------------------+-------------+----------------------------------------+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+---------+
| smw_id  | smw_namespace | smw_title             | smw_iw      | smw_subobject                          | smw_sortkey                                                                         | smw_sort                                                                            | smw_proptable_hash                                                                                                                                                                                                                                         | smw_hash                                 | smw_rev |
+---------+---------------+-----------------------+-------------+----------------------------------------+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+---------+
| 1633279 |             2 | BlueOceanz/BlueOceanz |             |                                        | bLink                                                                               | bLink                                                                               | a:4:{s:11:"smw_di_time";s:32:"3faf432da79e7478d6f834a426c8e105";s:11:"smw_fpt_ask";s:32:"82290df43e28e3fab94a4e72c05af2d6";s:14:"smw_fpt_dtitle";s:32:"c948e17b0237167acaab69d49bcf7218";s:12:"smw_fpt_mdat";s:32:"9e71a50e9b2a1c275c896816a9aaaf30";}     | ba3cf643d93dcbeebc54763e382a8c5b99ca06b8 |  737610 |
| 3835688 |             2 | BlueOceanz/BlueOceanz |             | _QUERY021984bfa8925ce7f22f6e6abbea91ae | bLink# QUERY021984bfa8925ce7f22f6e6abbea91ae                                        | bLink# QUERY021984bfa8925ce7f22f6e6abbea91ae                                        | a:4:{s:13:"smw_fpt_askde";s:32:"b812d1b17c3eea815abc148728234f34";s:13:"smw_fpt_asksi";s:32:"bf0736027ea55d7e95ce5d8253a20d88";s:13:"smw_fpt_askfo";s:32:"c169eaec7c2f7b4ff62910274106c08d";s:13:"smw_fpt_askst";s:32:"008c16fdbe68e513284afe1b29f44ed7";} | ac6b6e3847b8ee0759e80893a6b58ca459f15211 |    NULL |
| 3835689 |             2 | BlueOceanz/BlueOceanz |             | _QUERY6eae3dd76c7b50e3b58684ada481be42 | bLink# QUERY6eae3dd76c7b50e3b58684ada481be42                                        | bLink# QUERY6eae3dd76c7b50e3b58684ada481be42                                        | a:4:{s:13:"smw_fpt_askde";s:32:"47a819acdf5d1443691c42d32305806a";s:13:"smw_fpt_asksi";s:32:"3fd9a1061c4604bd7038d9defc4050b8";s:13:"smw_fpt_askfo";s:32:"e67f121ead3a7148ccde7163be3510a8";s:13:"smw_fpt_askst";s:32:"c7910c82d3dd92c35d033cd6ab3cf0c4";} | 5e87a4809817fc12f838616cc4d82410d6b12abf |    NULL |
| 3825610 |             2 | BlueOceanz/BlueOceanz | :smw-delete | _QUERY021984bfa8925ce7f22f6e6abbea91ae | bLink# QUERY021984bfa8925ce7f22f6e6abbea91ae# QUERY021984bfa8925ce7f22f6e6abbea91ae | bLink# QUERY021984bfa8925ce7f22f6e6abbea91ae# QUERY021984bfa8925ce7f22f6e6abbea91ae | a:0:{}                                                                                                                                                                                                                                                     | 44757d23b399ba8d545d93020ff41669e395efca |    NULL |
| 3825611 |             2 | BlueOceanz/BlueOceanz | :smw-delete | _QUERY6eae3dd76c7b50e3b58684ada481be42 | bLink# QUERY6eae3dd76c7b50e3b58684ada481be42# QUERY6eae3dd76c7b50e3b58684ada481be42 | bLink# QUERY6eae3dd76c7b50e3b58684ada481be42# QUERY6eae3dd76c7b50e3b58684ada481be42 | a:0:{}                                                                                                                                                                                                                                                     | 479869f9c1434b592a254762543b0c260b978ab6 |    NULL |
+---------+---------------+-----------------------+-------------+----------------------------------------+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+---------+
```

> - Does the `Duplicate entities lookup` contain any entries for `User:BlueOceanz/BlueOceanz`

Duplicate entities lookup does not contain this page, it has a dozen or so other pages though.

Thank you for your effort in helping me with this one.

**Comment by mwjames** [comment]
> > | 1633279 |             2 | BlueOceanz/BlueOceanz |             |
>                             | bLink
>                                      | bLink
>                                               |
> a:4:{s:11:"smw_di_time";s:32:"3faf432da79e7478d6f834a426c8e105";s:11:"smw_fpt_ask";s:32:"82290df43e28e3fab94a4e72c05af2d6";s:14:"smw_fpt_dtitle";s:32:"c948e17b0237167acaab69d49bcf7218";s:12:"smw_fpt_mdat";s:32:"9e71a50e9b2a1c275c896816a9aaaf30";}

So, yes, there is only one representation for
`User:BlueOceanz/BlueOceanz` namely 1633279, the others represent
queries (having a subobject name starting with _QUERY...) embedded in
the page.

> {s:11:"smw_di_time";s:32:"3faf432da79e7478d6f834a426c8e105";s:11:"smw_fpt_ask";s:32:"82290df43e28e3fab94a4e72c05af2d6";s:14:"smw_fpt_dtitle";s:32:"c948e17b0237167acaab69d49bcf7218";s:12:"smw_fpt_mdat";s:32:"9e71a50e9b2a1c275c896816a9aaaf30";}

This shows me that we have non (meaning no blob value annotations) and
should have no entities associated with the `smw_di_blob` table, ergo
we should have no association in the `wikidota_smw_di_blob`.

I know this is fuzzy work but I'm currently a bit out of ideas.

- Can you confirm that table `wikidota_smw_di_blob` has a matching
entry for s_id=1633279 and p_id=20091 before purging
- Can you confirm that after purging the page those entries are still
available in the `wikidota_smw_di_blob`

**Comment by FO-nTTaX** [comment]
> - Can you confirm that table `wikidota_smw_di_blob` has a matching entry for s_id=1633279 and p_id=20091 before purging

`select * from wikidota_smw_di_blob where s_id = 1633279  and p_id = 20091 ;`
```
+---------+-------+--------+------------+
| s_id    | p_id  | o_blob | o_hash     |
+---------+-------+--------+------------+
| 1633279 | 20091 | NULL   | BlueOceanz |
+---------+-------+--------+------------+
```
> - Can you confirm that after purging the page those entries are still available in the `wikidota_smw_di_blob`

After a blank edit and a `action=purge` purge, the values are still there exactly like that.

**Comment by mwjames** [comment]
> +---------+-------+--------+------------+
> | s_id    | p_id  | o_blob | o_hash     |
> +---------+-------+--------+------------+
> | 1633279 | 20091 | NULL   | BlueOceanz |
> +---------+-------+--------+------------+
> ```
>> - Can you confirm that after purging the page those entries are still
>> available in the `wikidota_smw_di_blob`
>
> After a blank edit and a `action=purge` purge, the values are still there
> exactly like that.

Yes, this is what I thought.

## What

>> a:4:{s:11:"smw_di_time";s:32:"3faf432da79e7478d6f834a426c8e105";s:11:"smw_fpt_ask";s:32:"82290df43e28e3fab94a4e72c05af2d6";s:14:"smw_fpt_dtitle";s:32:"c948e17b0237167acaab69d49bcf7218";s:12:"smw_fpt_mdat";s:32:"9e71a50e9b2a1c275c896816a9aaaf30";}

The `smw_proptable_hash` field (above contents) contains the
collective hash of those values that the tables (hereby annotations)
currently suppose to have assignments for and with that mechanism the
updater has an efficient diffing method during the update to decided
which tables require an insert/delete without reading each single
table and compare its values.

## Why

I don't know why the `wikidota_smw_di_blob` has a leftover (maybe an
update gone bad, a rollback gone haywire etc.). As for the `Has
nationality` and `User:BlueOceanz/BlueOceanz` issue, the easiest way
to restore the `smw_proptable_hash` content hash balance is by adding
a simple `Has nationality` assignment, save it, and removed it which
should ensure that all leftovers for that property are removed as
well.

Leftovers should rarely happen given that the SMW update process is
isolated in an transaction which means if something happens during the
processing or update all related data (tables stacked updates) are
expected to see a rollback and avoid a state as observed above.

Having said that, we have seen leftovers before and there should be
some sort of maintenance script to recompute the `smw_proptable_hash`
field as we rely on its consistency.

## Tasks

- Script to report leftovers
- Script to recompute the `smw_proptable_hash` (can be expensive since
you have to go through all tables and compare values with each other)
- Heuristic check during an update for leftovers on all tables that
are not part of the `smw_proptable_hash` tables with something like
`SELECT ... WHERE s_id=... LIMIT 1`

I have absolutely no idea as to when I will be able to attend those
listed tasks but I can help those who think this is urgent in order
for them to provide a PR.

Cheers

**Comment by FO-nTTaX** [comment]
That workaround with setting the property worked just fine, thank you for the hint there. Maybe we should just do a rebuildData.php with the maintenance script if we see issues like this in the future, that might avoid me stealing your time. 

Thank you so much for taking the time to help us with our issue here though, it is much appreciated!

**Comment by mwjames** [comment]
> the hint there. Maybe we should just do a rebuildData.php with the

The rebuildData.php runs through the same differ/updater (there is
only one) hence faces the same limitations as outlined.

> - Heuristic check during an update for leftovers on all tables that are not part of the `smw_proptable_hash` tables with something like `SELECT ... WHERE s_id=... LIMIT 1`

I'll post a PR on the upcoming weekend which will contain a change to
the `PropertyTableRowDiffer` but will be disabled by default as it
incurs additional overhead as it is evident by:

- DISABLED: 2019-03-28 11:26:47 127.0.0.1 mw-31-00: Store: ["Update
completed: Lorem_ipsum#0##","rev: 804","procTime: 0.23181"]
- ENABLED: 2019-03-28 11:27:16 127.0.0.1 mw-31-00: Store: ["Update
completed: Lorem_ipsum#0##","rev: 804","procTime: 0.36112"]

If a user assumes that the incurred overhead is negligible compared to
a hardening of consistency then s(he) will be able to use a setting
and make that change permanent.

```
@@ -169,10 +184,32 @@ class PropertyTableRowDiffer {
 				$tablesInsertRows[$tableName] = [];
 				$tablesDeleteRows[$tableName] =
$this->fetchCurrentContentsForPropertyTable(
 					$sid,
 					$propertyTable
 				);
+			} elseif ( $this->removeGhostEntities ) {
+
+				// #3849
+				// Check the table that wasn't part of the old and new hash
+				$row = $connection->selectRow(
+					$propertyTable->getName(),
+					's_id',
+					[
+						's_id' => $sid
+					],
+					__METHOD__
+				);
+
+				// Find and remove any leftovers (ghosts) from possible failed updates
+				// that weren't rollback correctly
+				if ( $row !== false ) {
+					$tablesInsertRows[$tableName] = [];
+					$tablesDeleteRows[$tableName] =
$this->fetchCurrentContentsForPropertyTable(
+						$sid,
+						$propertyTable
+					);
+				}
 			}
```

**Comment by mwjames** [comment]
For future reference, the appearance of so called ghosts or remnant entities is now described in [0] with #3866 providing an active counter measure to avoid the manual intervention of "... the easiest way to restore the `smw_proptable_hash` content hash balance is by adding a simple `Has nationality` assignment, save it, and removed it which should ensure that all leftovers  ...".

[0] https://www.semantic-mediawiki.org/wiki/Help:Remnant_entities
