### ISSUE TITLE
Ask page not available after upgrade to 3.0.1

### ISSUE THREAD

**Issue by foxpluto** [SemanticMediaWiki/SemanticMediaWiki#3850]
### Setup and configuration

- SMW version: 3.0.1
- MW version: 1.32
- PHP version: 7.1.19 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.17-MariaDB

My previous version was with:

- SMW version: 2.5.6
- MW version: 1.31
- PHP version: 7.1.19 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.17-MariaDB

### Issue
After the upgrade I am no more able to access the Ask Special page

### Stack trace
```
[XJpRmS2QvTwvdmtKW8ARXAAAAAo] /index.php?title=Special:Ask Error from line 131 of /var/www/html/mediawiki-1.32.0/extensions/Operations/TemplateRenderer.php: Call to undefined method TemplateRenderer::getContext()

Backtrace:

#0 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/FormatListWidget.php(105): TemplateRenderer->getName()
#1 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/FormatListWidget.php(69): SMW\MediaWiki\Specials\Ask\FormatListWidget::formatList(string, string, string, string, string)
#2 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/ParametersWidget.php(121): SMW\MediaWiki\Specials\Ask\FormatListWidget::selectList(Title, array)
#3 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(372): SMW\MediaWiki\Specials\Ask\ParametersWidget::fieldset(Title, array)
#4 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(194): SMW\MediaWiki\Specials\Ask\HtmlForm->editElements(SMW\MediaWiki\Specials\Ask\UrlArgs)
#5 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(143): SMW\MediaWiki\Specials\Ask\HtmlForm->buildHTML(SMW\MediaWiki\Specials\Ask\UrlArgs, NULL, string)
#6 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(388): SMW\MediaWiki\Specials\Ask\HtmlForm->getForm(SMW\MediaWiki\Specials\Ask\UrlArgs, NULL, string)
#7 /var/www/html/mediawiki-1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(169): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#8 /var/www/html/mediawiki-1.32.0/includes/specialpage/SpecialPage.php(569): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#9 /var/www/html/mediawiki-1.32.0/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#10 /var/www/html/mediawiki-1.32.0/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#11 /var/www/html/mediawiki-1.32.0/includes/MediaWiki.php(860): MediaWiki->performRequest()
#12 /var/www/html/mediawiki-1.32.0/includes/MediaWiki.php(517): MediaWiki->main()
#13 /var/www/html/mediawiki-1.32.0/index.php(42): MediaWiki->run()
#14 {main}
```

### Steps to reproduce
Just click on the page anche the stack trace appear.

Thanks,
S.

**Comment by mwjames** [comment]
> Stack trace
[XJpRmS2QvTwvdmtKW8ARXAAAAAo] /index.php?title=Special:Ask Error from
line 131 of /var/www/html/mediawiki-1.32.0/extensions/Operations/TemplateRenderer.php:
Call to undefined method TemplateRenderer::getContext()

It should be clear from the stack trace that your custom printer
`Operations/TemplateRenderer.php` tries to access a method we no
longer provide.

This relates to #2748.

Cheers

**Comment by foxpluto** [comment]
Thanks for the super speedy reply.

Sorry but I am not good in coding, what I have to do to fix the problem?

Regards,
S.

**Comment by foxpluto** [comment]
Sorry..... 

I got the point, Operation is a piece of code written by us (not actually me).

We will fix this.

Thanks,
S.

**Comment by mwjames** [comment]
> Thanks for the super speedy reply.
>
> Sorry but I am not good in coding, what I have to do to fix the problem?

We are not really providing support for software the project hasn't
deployed but if for some reason you need access to the
`RequestContext` in your printer, you should be able to use
`RequestContext::getMain()` to get a context instance.

Cheers

**Comment by foxpluto** [comment]
Thanks for the suggestion! 

Regards,
S.
