### ISSUE TITLE
Display title not utilized in nested result template (and link=none)

### ISSUE THREAD

**Issue by WSViktorS** [SemanticMediaWiki/SemanticMediaWiki#3853]
### Setup and configuration
- SMW version: 3.0.1
- MW version: 1.31.1
- PHP version: 7.0.32
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.25

Issue tested and NOT present on stack with SMW 2.5.5/MW 1.30.0/PHP 7.0.31/MySQL 5.7.25

### Issue
Nested SMW result templates converting a plain page string (`{{{1|}}}`) to a link (`[[{{{1|}}}]]`) (so using `link=none`) does not utilize display title. A non-nested result template displays it correctly. 

### Stack trace
N/a

### Steps to reproduce
I've set up a page displaying the problem here:
https://i.wikibase.nl/index.php/Wikibase_Solutions_problem_demo

**Comment by mwjames** [comment]
> Nested SMW result templates converting a plain page string (`{{{1|}}}`) to a
> link (`[[{{{1|}}}]]`) (so using `link=none`) does not utilize display title.
> A non-nested result template displays it correctly.

`template` belongs to the `SMW\Query\ResultPrinters\ListResultPrinter`
so it relates to the  #2488 ticket whether the change was deliberate
or not I cannot say.

The output is generated by [0] where `getLinkerForColumn` returns null
and forces the `natural` title (unaltered title).

To clarify, a no `linker` (aka null) means [1] will return the
`getWikiValue` (unaltered) and has the same behaviour as in 2.5 [2].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/ListResultPrinter/ValueTextsBuilder.php#L68
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/datavalues/SMW_DV_WikiPage.php#L269-L311
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/includes/datavalues/SMW_DV_WikiPage.php#L244-L249

Cheers

**Comment by mwjames** [comment]
> Issue tested and NOT present on stack with SMW 2.5.5/MW 1.30.0/PHP
> 7.0.31/MySQL 5.7.25

Actually, no I have tested your example on 2.5.8 and both 2.5.8 and
3.0 return the same results for the the query:

```
{{#ask: [[Issue::3853]]
|format=template
|template=Parse 1
|link=none
}}

```

Where the subject `Issue/3853` contains:

```
[[Issue::3853]]

{{DISPLAYTITLE:SMW 3.0/link=none/Displaytitle problem}}
```

And the templates being defined as in the link provided.

**Comment by kghbln** [comment]
I labelled this as "question" for now. Perhaps @s7eph4n has some info on this too.

**Comment by mwjames** [comment]
Given the primarily findings, I will recuse myself from this issue
until the attached integration test [0] shows a difference in
behaviour (2.5.x/3.x) as of now it doesn't.

```
> php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist "--filter" "p-0712"

Using PHP 7.1.1

Semantic MediaWiki: 2.5.8 (SMWSQLStore3, mysql)
MediaWiki:          1.29.1 (MediaWiki vendor autoloader)
Site language:      en-gb

Execution time:     2019-03-27 11:52
Debug logs:         Disabled
Xdebug:             Disabled (or not installed)

PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

Runtime:        PHP 7.1.1
Configuration:  ...\extensions\SemanticMediaWiki\phpunit.xml.dist

.

Time: 37.43 seconds, Memory: 68.00MB

OK (1 test, 4 assertions)
```

```
> php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist "--filter" "p-0712"
Using PHP 7.1.1

Semantic MediaWiki: 3.1.0-alpha, git: 426a780, SMWElasticStore
(mysql:10.1.21-MariaDB, es:6.2.4)
MediaWiki:          1.31.0, git: n/a, MediaWiki vendor autoloader
Site language:      en

Execution time:     2019-03-27 11:53
Debug logs:         Disabled
Xdebug:             Disabled (or not installed)

PHPUnit 6.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.1
Configuration: ...\extensions\SemanticMediaWiki\phpunit.xml.dist

.                                                                   1 / 1 (100%)

Time: 36.77 seconds, Memory: 152.00MB

OK (1 test, 4 assertions)
```

## Test

```
{
	"description": "Test `#ask` on
`format=template`/`link=none`/DISPLAYTITLE with nested template",
	"setup": [
		{
			"namespace": "NS_TEMPLATE",
			"page": "Example/P0712/Parse 1",
			"contents": "<includeonly>'''Parse 1 result:'''<br>Modify to link:
[[{{{1|}}}]]<br>As-is output: {{{1|}}} '''Parse 2
result:'''<br>{{Example/P0712/Parse 2|{{{1|}}} }}</includeonly>"
		},
		{
			"namespace": "NS_TEMPLATE",
			"page": "Example/P0712/Parse 2",
			"contents": "<includeonly>Modify to link: [[{{{1|}}}]]<br>As-is
output: {{{1|}}}</includeonly>"
		},
		{
			"page": "Test:P0712/1",
			"contents": "[[Issue::3853]] {{DISPLAYTITLE:Displaytitle P0712}}"
		},
		{
			"page": "Test:P0712/Q.1",
			"contents": "{{#ask: [[Issue::3853]] |link=none
|template=Example/P0712/Parse 1 |format=template }}"
		},
		{
			"page": "Test:P0712/Q.2",
			"contents": "{{#ask: [[Issue::3853]] |template=Example/P0712/Parse
1 |format=template }}"
		}
	],
	"tests": [
		{
			"type": "parser",
			"about": "#0 `link=none`",
			"subject": "Test:P0712/Q.1",
			"assert-output": {
				"to-contain": [
					"<b>Parse 1 result:</b><br />Modify to link: <a
href=\".*Test:P0712/1\" title=\"Test:P0712/1\">Test:P0712/1</a>",
					"<b>Parse 2 result:</b><br />Modify to link: <a
href=\".*Test:P0712/1\" title=\"Test:P0712/1\">Test:P0712/1 </a><br
/>As-is output: Test:P0712/1"
				]
			}
		},
		{
			"type": "parser",
			"about": "#1 ",
			"subject": "Test:P0712/Q.2",
			"assert-output": {
				"to-contain": [
					"<b>Parse 1 result:</b><br />Modify to link: [[<a
href=\".*Test:P0712/1\" title=\"Test:P0712/1\">Displaytitle
P0712</a>]]<br />",
					"<b>Parse 2 result:</b><br />Modify to link: [[<a
href=\".*/Test:P0712/1\" title=\"Test:P0712/1\">Displaytitle P0712</a>
]]"
				]
			}
		}
	],
	"settings": {
		"wgContLang": "en",
		"wgLang": "en",
		"wgRestrictDisplayTitle": false,
		"smwgPageSpecialProperties": [
			"_MDAT"
		]
	},
	"meta": {
		"version": "2",
		"is-incomplete": false,
		"debug": false
	}
}
```

**Comment by mwjames** [comment]
You failed to mention that you have `DisplayTitle` installed which
messes with how links appear. Now, given the extra test passes for
both releases. This issue can be closed unless you demonstrate
(without `DisplayTitle` enabled) that tests behave differently.

[0] https://i.wikibase.nl/index.php/Special:Version

**Comment by kghbln** [comment]
Well, I guess this happened in the heat of the action. Admittedly I use the "DisplayTitle" extension very often as part of my setups too. If O interpret your info correctly this is a report that should go to the "DisplayTitle" bug tracker.

**Comment by mwjames** [comment]
>  If O interpret
> your info correctly this is a report that should go to the "DisplayTitle"
> bug tracker.

Not necessarily, I'll I'm saying is that there is no difference in
behavior for the described test case and what you see on the cited
demo page is distorted by the fact the `DisplayTitle` manipulates
certain links which is beyond the scope of SMW. The generated template
output is the same for 2.5.8 and 3.x (this is what test proves) which
means there is no regression from the SMW perspective.

**Comment by WSViktorS** [comment]
Hi James,

I should have mentioned it explicitely, apologies for that. I figured including the Special:Version page was enough. Thank you for the time spent looking into this already.

However, I do -as many others I'm assuming- would like to be able to use the extension DisplayTitle together with Semantic MediaWiki. DisplayTitle is, as far as I know, working well on its own but not in the case I described in this issue. However, I would like to double check this tomorrow morning when I'm able to.

**Comment by mwjames** [comment]
> However, I do -as many others I'm assuming- would like to be able to use the
> extension DisplayTitle together with Semantic MediaWiki. DisplayTitle is, as
> far as I know, working well on its own but not in the case I described in
> this issue. However, I would like to double check this tomorrow morning when
> I'm able to.

You can (as Karsten has mentioned).

All I'm concerned is whether there was a regression or not in SMW and
as far as the evidence shows there isn't one. How this ties in with
the interaction of `DisplayTitle` is out of scope of this ticket or
the project.

If you can demonstrate that the test above (feel free to amend without
enabled `DisplayTitle`) behaves differently on 2.5.8 and 3.x then we
have a platform that allows us to verify the differences excluding any
third party extension interference.

Cheers

**Comment by WSViktorS** [comment]
Hi James,

It appears you are right and this is a DisplayTitle problem rather than an SMW problem. Calling the `Parse 1` and `Parse 2` templates (as seen on the demo page) without being a result format of SMW presented the exact same wrong result. I will submit a bug report to the authors of DisplayTitle. 

Thanks for looking into this.
