### ISSUE TITLE
`$smwgCompactLinkSupport = true;` may cause links to break 

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3855]
### Setup and configuration

- MediaWiki | 1.31.1 (9ea0a46)17:34, 18. Feb. 2019
- PHP | 7.0.33-0+deb9u3 (apache2handler)
- MariaDB | 10.1.37-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.1

### Issue
Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3017

### Causes
Described in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3017#issuecomment-470106840 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3017#issuecomment-477217343. Both need to be investigated and describe more to find the exact cause.

**Comment by kghbln** [comment]
@krabina FYI

**Comment by mwjames** [comment]
I'm pretty sure #3535 as the same cause, so once the PR is merged the
issue can be closed as well.

**Comment by kghbln** [comment]
> I'm pretty sure #3535 as the same cause, so once the PR is merged the issue can be closed as well.

There is a difference however. The query I used does not use and explicitely set `|searchlabel=`

#### not working
linking to an empty "Special:Ask"
```
{{#ask:
 [[Konzept:Kontakte]]
 [[Postanschrift::Briefanschrift (f)]]
 [[Status::!3 - gesperrt]]
 |?=Kennung
 |?Status=Status
 |?Firmenkennung=Firmenkennung
 |?Firma=Firma
 |?Rechtsform=Rechtsform
 |?Position=Position
 |?Anrede=Anrede
 |?Akad Grad=Titel
 |?Briefanrede=Briefanrede
 |?Alternativanrede=Alternativanrede
 |?Vorname 1=Vorname
 |?Familienname=Familienname
 |?Postanschrift=Postanschrift
 |?Postfach Arbeit=Postfach
 |?PLZ Postfach Arbeit=Postleitzahl
 |?Ort Postfach Arbeit=Ort
 |?Land Postfach Arbeit=Staat
 |?Land Postfach DE Arbeit=Land
 |?EMail privat 1=E-Mail (p)
 |?EMail alternativ 1=E-Mail (a)
 |?EMail Arbeit 1=E-Mail (A)
 |?Zuordnung=Zuordnung
 |?Merkmal=Merkmal(e)
 |?Bemerkung=Bemerkung Person
 |?Bemerkung Sonstiges
 |mainlabel=-
 |limit=2000
 |format=csv
}}
```

#### not working 
linking to a page telling me that the page title is longer than 512 byte. Note that I changed the lable for the email printouts.

"Der angeforderte Seitentitel ist zu lang. Er darf nicht länger als 512 Bytes in UTF-8-Kodierung sein."

```
{{#ask:
 [[Konzept:Kontakte]]
 [[Postanschrift::Briefanschrift (f)]]
 [[Status::!3 - gesperrt]]
 |?=Kennung
 |?Status=Status
 |?Firmenkennung=Firmenkennung
 |?Firma=Firma
 |?Rechtsform=Rechtsform
 |?Position=Position
 |?Anrede=Anrede
 |?Akad Grad=Titel
 |?Briefanrede=Briefanrede
 |?Alternativanrede=Alternativanrede
 |?Vorname 1=Vorname
 |?Familienname=Familienname
 |?Postanschrift=Postanschrift
 |?Postfach Arbeit=Postfach
 |?PLZ Postfach Arbeit=Postleitzahl
 |?Ort Postfach Arbeit=Ort
 |?Land Postfach Arbeit=Staat
 |?Land Postfach DE Arbeit=Land
 |?EMail privat 1=E-Mail
 |?EMail alternativ 1=E-Mail
 |?EMail Arbeit 1=E-Mail
 |?Zuordnung=Zuordnung
 |?Merkmal=Merkmal(e)
 |?Bemerkung=Bemerkung Person
 |?Bemerkung Sonstiges
 |mainlabel=-
 |limit=2000
 |format=csv
}}
```

#### working
```
{{#ask:
 [[Konzept:Kontakte]]
 [[Postanschrift::Briefanschrift (f)]]
 [[Status::!3 - gesperrt]]
 |?=Kennung
 |?Status=Status
 |?Firmenkennung=Firmenkennung
 |?Firma=Firma
 |?Rechtsform=Rechtsform
 |?Position=Position
 |?Anrede=Anrede
 |?Akad Grad=Titel
 |?Briefanrede=Briefanrede
 |?Alternativanrede=Alternativanrede
 |?Vorname 1=Vorname
 |?Familienname=Familienname
 |?Postanschrift=Postanschrift
 |?Postfach Arbeit=Postfach
 |?PLZ Postfach Arbeit=Postleitzahl
 |?Ort Postfach Arbeit=Ort
 |?Land Postfach Arbeit=Staat
 |?Land Postfach DE Arbeit=Land
 |?Zuordnung=Zuordnung
 |?Merkmal=Merkmal(e)
 |?Bemerkung=Bemerkung Person
 |?Bemerkung Sonstiges
 |mainlabel=-
 |limit=2000
 |format=csv
}}
```
Exporting stuff. Note that I removed the email printouts.

**Comment by mwjames** [comment]
>> I'm pretty sure #3535 as the same cause, so once the PR is merged the
>> issue can be closed as well.

For enabled compact links, the MW parser eats some bytes which is why
the further result link is being empty.

> linking to a page telling me that the page title is longer than 512 byte.
> Note that I changed the lable for the email printouts.

I'm guessing this to be similar to [0] which is a limit set by the
browser and has nothing to do with SMW.

[0] https://core.trac.wordpress.org/ticket/8942

**Comment by kghbln** [comment]
> For enabled compact links, the MW parser eats some bytes which is why
the further result link is being empty.

Indeed, this was your first assessment anyways.

> I'm guessing this to be similar to [0] which is a limit set by the browser and has nothing to do with SMW.

Ten years passed and nothing happened. ;)

**Comment by krabina** [comment]
I guess this is relevant: URL shortener for the Wikimedia projects will be available on April 11th
https://phabricator.wikimedia.org/T44085
