### ISSUE TITLE
 translation issue Typo 'Compilied constraint schema'  arrived in translatewiki.net 

### ISSUE THREAD

**Issue by ChristianWia** [SemanticMediaWiki/SemanticMediaWiki#3860]
Hi all, I noticed following message arrived in translatewiki.net with typo Compilied->Compiled. Request for correction of the original EN string. Thank you.

Compilied constraint schema

should be :

Compiled constraint schema

Link: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=8%3ASmw-property-tab-constraint-schema-title&group=mwgithub-semanticmediawiki

**Comment by kghbln** [comment]
@ChristianWia Thanks a lot for reporting. Just merged in the fix!

**Comment by ChristianWia** [comment]
Thanks
