### ISSUE TITLE
Special:JavaScriptTest breaks when SMW is installed

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#3861]
### Setup and configuration

- SMW version: 3.0.1
- MW version: 1.33.0-alpha (0336e2b)
- PHP version: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.0.38-MariaDB-0ubuntu0.16.04.1

### Issue
Special:JavaScriptTest doesn't work if SMW installed. I believe the cause is https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/1fad17a07ca0a4c2c0fa2fba9710e2e647768bea#r32968076

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
MWException from line 870 of /www/dev.translatewiki.net/docroot/w/includes/resourceloader/ResourceLoaderFileModule.php: ResourceLoaderFileModule::readScriptFiles: script file not found: "/www/dev.translatewiki.net/docroot/w/tests/qunit/smw/ext.smw.test.js"
```

### Steps to reproduce
Enable JavaScript testing with `$wgEnableJavaScriptTest = true;` and go to Special:JavaScriptTest.

**Comment by kghbln** [comment]
Thanks for reporting.
