### ISSUE TITLE
[[MediaWiki:Smw-property-predefined-constraint-schema/fr]] translation issue Typo "predefined property tat defines"

### ISSUE THREAD

**Issue by ChristianWia** [SemanticMediaWiki/SemanticMediaWiki#3878]
Hi all, this EN text was received in translatewiki.net for translation and requires correction. Thank you.

"$1" is a predefined property tat defines a constraint schema and is provided by [https://www.semantic-mediawiki.org/wiki/Help:Special_properties Semantic MediaWiki].

Should be :

"$1" is a predefined property that defines a constraint schema and is provided by [https://www.semantic-mediawiki.org/wiki/Help:Special_properties Semantic MediaWiki].

Link: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=8%3ASmw-property-predefined-constraint-schema&group=mwgithub-semanticmediawiki

**Comment by kghbln** [comment]
@ChristianWia Thanks a ton for reporting. Just merged in the fix!

**Comment by ChristianWia** [comment]
ok
