### ISSUE TITLE
Month(-date) without year

### ISSUE THREAD

**Issue by brettz9** [SemanticMediaWiki/SemanticMediaWiki#3881]
Just a feature request as it appears this is not supported per https://www.semantic-mediawiki.org/wiki/Help:Type_Date#Input_examples ...

Would it be difficult to add support for just "Month" or "Month Date" only (without a year)? We have "This day in history" types of page, so it would be nice to be able to search a range of these dates (e.g., for text content within say a given month or month/day range).

I know `Has date::Feb 11` would be ambiguous with year 11, but I figure some syntax might be possible?

**Comment by mwjames** [comment]
> Would it be difficult to add support for just "Month" or "Month Date" only

The `Date` type is per definition calendar type and year bound.

> be nice to be able to search a range of these dates (e.g., for text content
> within say a given month or month/day range).

What you can do (based on #1178) is to use the `in` operator (or ~
which is semantically equivalent in the date context) to define a
range such as:

- `[[Has date::in:2009]]` find all entities with in the range of Year 2009
- `[[Has date::in:Jan 2010]]` find all entities with in the rage of Jan 2010
- `[[Has date::in:1 Feb 2011]]` find all entities with in the rage of 1 Feb 2011

Internally we store a date value as JD representation (simple integer
value) which allows for range queries to be constructed efficiently
but those need a Year (at least).

For example, something like `[[Modification date::in:2019]]` will
internally be interpret as
`[[Modification date:: [[≥2019]] [[<<1 January 2020 00:00:00]] ]]` and
is transformed as (SQL):

```
INNER JOIN
  `smw_fpt_mdat` AS t1 ON t0.smw_id=t1.s_id
WHERE
  (
   ((t1.o_sortkey>='2458484.5')
   AND (t1.o_sortkey<'2458849.5')
  ))
```

Cheers

**Comment by brettz9** [comment]
A few issues:

1. Some items don't even have a year connected at all--they just refer to recurring events. So if one wished to search for info one recalled reading about for an activity in January, one couldn't find info about it.
2. As these deal with history, there could be a great many years involved, but if one knew the month, they could narrow it down quickly.
3. The existing content was added as pages with "Month date" and the individual dates that exist within haven't been marked up. If we could just add "Month date" to these pages' templates, we could allow queries with less effort.

This is not a huge need on our end for this though, but just thought I'd check. Thanks!

**Comment by mwjames** [comment]
Again, the `Date` type is defined to have a year so that we can
represent the values as JD [0] not as a mere string.

> 1. Some items don't even have a year connected at all--they just refer to
> recurring events. So if one wished to search for info one recalled reading
> about for an activity in January, one couldn't find info about it.

Yes, and in those cases the `Date` type is the wrong type. You may as
well store them using a simple text type or a number depending how you
want to format those values and make them queryable.

For example, you can describe an event by something like `[[Event
month::12]] [[Event day::3]]` hereby make them queryable the way you
like and combine them with other conditions. You can add some
constraints on those properties such as `[[Allows value::1...12]]` the
help avoid collecting bogus data.

[0] https://en.wikipedia.org/wiki/Julian_day

**Comment by brettz9** [comment]
Ah, cool idea!  Takes some getting used to all the possibilities...  Thanks!
