### ISSUE TITLE
Create CI job to run with some extra extensions enabled

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3896]
### Setup and configuration

- SMW version: 3.1+
- MW version: LTS

refs https://github.com/SemanticMediaWiki/SemanticNotifications/issues/27

### Tasks

Create an additional CI job to run tests on the current SMW master with some extension (maintained by the project) to immediately check on each merge whether some incompatibilities were introduced or not.

- List of potential extensions ...

When working on this task only one extension at a time should be added to verify that tests don't interfere with each other.

The CI job should:

- Use SMW master
- Use MW LTS version
- Use the `@dev` of an extension 

Firs make the CI job non voting, after all listed extensions have been added and showed no issues on running SMW master make the job voting.

**Comment by kghbln** [comment]
@JeroenDeDauw In light of a possible new semantic bundle this will be a great thing to implement at the same time.

**Comment by kghbln** [comment]
In any case we need a developer for this. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
