### ISSUE TITLE
Displaying highlighted terms within excerpts for unstructured queries

### ISSUE THREAD

**Issue by brettz9** [SemanticMediaWiki/SemanticMediaWiki#3910]
### Issue

As discussed in #3880, I would be very interested in the ability to not only make queries against unstructured text, but also for queries to display excerpts out of unstructured text with highlighted terms (along the lines of https://www.semantic-mediawiki.org/wiki/Help:Full-text_search/Searching#Search_highlighting , but for unstructured text).

Unlike the built-in search features of Mediawiki which show such excerpts already, this idea is to get highlighted excerpts out of the content based on unstructured term or terms—*along with structured queries (e.g., property/category)* .

**Comment by brettz9** [comment]
While this is somewhat off topic, I'm curious whether the structured text queries can in any way be made to accept line breaks and full markup (albeit with necessary escaping), since that is one of the deterrents for using the structured text format.

**Comment by kghbln** [comment]
I am not sure if this is really an SMW issue. However there may be a way. Anyways, we need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
