### ISSUE TITLE
Avoid either or situation for `$wgSearchType`

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3937]
### Setup and configuration

- MediaWiki | 1.32.1 (3efaceb)17:46, 11. Apr. 2019
- PHP | 7.2.15-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.1
- Elasticsearch | 6.5.4
- Semantic MediaWiki | 3.1.0-alpha (a795e69) 17:50, 15. Apr. 2019

### Issue
If one would like to use CirrusSearch for searching with unstructured content I have to add the following configuration:
```php
$wgSearchType = 'CirrusSearch';
```
However in this case I cannot set:
```php
$wgSearchType = 'SMWSearch';
```
Thus I am loosing the option to use the query syntax withing the search field as well as all other features for special page "Search" provided by SMW.

FYI @s7eph4n since you originally implemented the feature.

**Comment by s7eph4n** [comment]
See https://www.semantic-mediawiki.org/wiki/Help:$smwgFallbackSearchType
:wink:

**Comment by kghbln** [comment]
> See https://www.semantic-mediawiki.org/wiki/Help:$smwgFallbackSearchType

Aaaaaaaaaaaarrrrrrgggh. I guess I lost my spannkraft for today. I know this setting but for some reason did not consider this as the solution. Senior moments .... and thanks for the hint.
