### ISSUE TITLE
Next-Previous: Minor localisation issue with Greek

### ISSUE THREAD

**Issue by Protonotarios** [SemanticMediaWiki/SemanticMediaWiki#3952]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.32.0
- PHP version: 7.2.12 (cgi-fcgi)
- DB system and version: MySQL 5.6.36-82.0

### Issue
MediaWiki messages MediaWiki:Prevn and MediaWiki:Nextn are meant to be used in phrases such as  "Show next 20" but SMW uses them in Property pages without the verb "Show" (and maybe elsewhere, I don't know). This is an issue with Greek because "Show next 20" ( _Εμφάνιση 20 **επόμενων**_) translates different from plain "next 20" (_20 **επόμενα**_).
So, SMW must either employ two new MediaWiki messages instead of MediaWiki:Prevn and MediaWiki:Nextn, or keep existing messages and add the verb "Show".

**Comment by mwjames** [comment]
> know). This is an issue with Greek because "Show next 20" ( Εμφάνιση 20 επόμενων) translates different from plain "next 20" (20 επόμενα).

I'm not sure I fully understand the subtleties of the issue but in any event [0] produces the HTML output in relation to `prevn` and `nextn`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Utils/Pager.php

**Comment by Protonotarios** [comment]
Translatewiki.net gives the following info for [prevn](https://translatewiki.net/w/i.php?title=MediaWiki:Prevn/el&action=edit) and [nextn](https://translatewiki.net/w/i.php?title=MediaWiki:Nextn/el&action=edit):

> This is part of the navigation message on the top and bottom of Special pages (lists of things in alphabetical order, i.e. the 'Special:Categories' page), where it is used as the first argument of [Viewprevnext](https://translatewiki.net/w/i.php?title=MediaWiki:Viewprevnext/el&action=edit) ("Show ($1 | $2) ($3).").

The issue with Greek is that it translates differently if there is a verb ("Show") and differently if there in no verb. `prevn` and `nextn` as they are now, they are translated to Greek assuming there is a verb. But in SMW property pages they are used without a verb so the Greek translation becomes wrong.

So the solution is either to add a string like `Viewprevnext` to the existing code or to just create two new message strings instead of `prevn` and `nextn`.

**Comment by kghbln** [comment]
@Protonotarios To me it appears to be the easiest and most pragmatic solution to translate "next 20" also as "show next 20" since the latter does also make sense including the word show. At least this is what I do in similar situations when it comes to translating to German.

**Comment by Protonotarios** [comment]
@kghbln If I translate it as "show next 20" then in all other MediaWiki pages will appear as "Show show next 20"!
The problem is that SMW uses a message shared with other resources (but it doesn't use it exactly as it supposed to be used). So if I translate it to suit SMW then I will break the other translations, and vice versa.

**Comment by mwjames** [comment]
Karsten added #3980 as suggested, please test this before merging (and on all screens where it supposed to be displayed) to avoid disruption of the existing functionality.

**Comment by kghbln** [comment]
I have just checked pages I can think of using these new system messages doing a field test to see if it works out:
- [property page](https://sandbox.semantic-mediawiki.org/wiki/Attribut:Has_parent_page)
- [concept page](https://sandbox.semantic-mediawiki.org/wiki/Concept:Books_in_German)
- [Special:Concepts](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Concepts)
- [Special:Ask](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&q=%5B%5BHas+processing+error+text%3A%3A%2B%5D%5D&po=%3FHas+improper+value+for%7C%3FHas+processing+error+text&p=class%3Dsortable-20wikitable-20smwtable-2Dstriped&eq=no&limit=20&bTitle=processingerrorlist&bMsg=smw-processingerrorlist-intro)

Obviously translations are not yet available but the English source text shows as expected in all examples.
