### ISSUE TITLE
Query / QueryResultPrinter / sep arg for format=template

### ISSUE THREAD

**Issue by hypergrove** [SemanticMediaWiki/SemanticMediaWiki#396]
Seems that format=template processor does not pay attention to the 'sep' arg, per both experience and site dox. Could this be added please for values that contain commas?
thanks/john

**Comment by mwjames** [comment]
@kghbln Totally forgot about this. Solved with 2.2 (a7b09f5857)

```
[[TemplateListOutput-1::test 1]] [[TemplateListOutput-1::test 1-2]] [[TemplateListOutput-2::test 2]]

{{#ask: [[TemplateListOutput-1::+]]
 |?TemplateListOutput-1
 |?TemplateListOutput-2
 |template=TemplateListOutput
 |format=template
 |named args=yes
 |sep=;
}}
```
Values that belong to the same property are divided by `;`.
