### ISSUE TITLE
Remove support for the "type" namespace entirely

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#399]
This namespace was depreciated and its usage discouraged with SMW 1.6.0 three years ago at end of July 2011. Perhaps SMW 2.0 is an opportunity to remove the support entirely together with the `$smwgHistoricTypeNamespace` setting.

**Comment by JeroenDeDauw** [comment]
@mwjames might be a fun thing to kill :)

**Comment by kghbln** [comment]
We also need to add a depreciation notice for this [setting](https://www.semantic-mediawiki.org/wiki/Help:$smwgHistoricTypeNamespace)

**Comment by kghbln** [comment]
> @mwjames might be a fun thing to kill :)

Since this seems to be a namespace day today: Perhaps this is a good chance to get namespace related stuff for 3.0.0 out of the way for good. :)
