### ISSUE TITLE
Support categories in property chains

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3990]
### Setup and configuration

- SMW version: 3.0.1

### Issue

I would like to query for [subobjects](https://www.semantic-mediawiki.org/wiki/Help:Adding_subobjects) whose parent page has a specific category.

Suggested syntax: `-Has subobject.Category::Foo`

(Yes I am aware that categories aren't properties.)

**Comment by mwjames** [comment]
> I would like to query for subobjects whose parent page has a specific category.

The following query `[[-Has subobject::<q>[[Category:Foo]]</q>]]` should suffice to retrieve matches for the above request.

> Suggested syntax: -Has subobject.Category::Foo
> (Yes I am aware that categories aren't properties.)

So, yes, categories and properties are two distinct concepts and while technically there could be a method to interpret the syntax and mix them, semantically there are different and cannot be mixed.

The property path syntax is to declare a path of properties  (as the name suggests using `.` as syntax expression over properties, not characters) and what seems convenient doesn't always necessarily equate to be reinterpretable or reusable for something seemingly indifferent in terms of character representations.
