### ISSUE TITLE
SQL / DB / Error due to missing o_id field in smw_di_blob

### ISSUE THREAD

**Issue by ghost** [SemanticMediaWiki/SemanticMediaWiki#400]
I am encountering a SQL error with at least one page (and probably more) on my dev wiki environment after upgrading MW from 1.20.8 to 1.23.1 and SMW from 1.8.0.5 to 1.9.2 (with all of my other extensions being updated appropriately as well) and running both the update.php and SMW_refreshData.php scripts:

Unexpected non-MediaWiki exception encountered, of type "RuntimeException"
[189900ee] /wiki/Special:Browse/Silk_Scrap Exception from line 162 of /var/www/sites/gw2w.en/extensions/SemanticMediaWiki/includes/src/MediaWiki/Database.php: A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT DISTINCT smw_title, smw_namespace, smw_iw, smw_sortkey, smw_subobject FROM `smw_object_ids` INNER JOIN `smw_di_blob` AS t1 ON t1.s_id=smw_id WHERE t1.p_id='136206' AND t1.o_id='75104' ORDER BY smw_sortkey LIMIT 21
Function: SMWSQLStore3Readers::getPropertySubjects
Error: 1054 Unknown column 't1.o_id' in 'where clause' 

There was a similar issue previously that one of our community SMW experts resolved by editing an item template to add an #if wrapper around #show queries since MW no longer likes such queries with null arguments. However, that does not resolve this particular issue, neither did deleting and recreating the specified item.

**Comment by mwjames** [comment]
#1222 describes a test case that sufficiently and repeatedly allows to re-create the issue. #1224 (2.3) is expected to fix this issue.
