### ISSUE TITLE
[ES] Show `&action=elastic` unconditionally on "Special:SemanticMediaWiki" if ES backend is configured

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4019]
### Setup and configuration
```json
{
    "SMWElasticStore": {
        "mysql": "10.1.38-MariaDB-0ubuntu0.18.04.2",
        "es": "6.5.4"
    },
    "smw": "3.1.0-alpha",
    "mediawiki": "1.32.1",
    "php": "7.2.17-0ubuntu0.18.04.1"
}
```

### Issue
For some reason ES went into a failed state yesterday. As soon as ES fails the section on special page "Semantic MediaWiki" holding the link to `&action=elastic` is no longer shown. I think it should still show since ES is configured as a backend, however informing about the failed state.

**Comment by mwjames** [comment]
> For some reason ES went into a failed state yesterday. As soon as ES fails the section

In those cases "normal" users should see #4018.

> I think it should still show since ES is configured as a backend, however informing about the failed state.

#4023

**Comment by kghbln** [comment]
> In those cases "normal" users should see #4018.

Indeed and this is how I got to know. :)

> #4023

This is a good improvement, however one has to know that this page exists since the "Elasticsearch section" as shown below on the screen shot does not shown when Elasticsearch is in a failed state.

![image](https://user-images.githubusercontent.com/1104078/57970373-d2262200-7980-11e9-99d6-544016631e30.png)

**Comment by mwjames** [comment]
> This is a good improvement, however one has to know that this page exists since the "Elasticsearch section" as shown below on the screen shot below does not shown when Elasticsearch is in a failed state.

It should show up now with this PR, doesn't it?

**Comment by kghbln** [comment]
> It should show up now with this PR, doesn't it?

Affirmative. Just killed ES an it works perfectly. Thank you!
