### ISSUE TITLE
Query based on revisions prior to a specific date

### ISSUE THREAD

**Issue by EvenThorbergsen** [SemanticMediaWiki/SemanticMediaWiki#4021]
### Setup and configuration

No setup or configuration is needed.

### Issue
It would be highly useful to be able to recreate the results of a query that was or could have been created at some previous date (or rather, previous point in time) based on revisions of the articles valid at that date. The syntax might be as follows:

```
{{#ask: [[Category:Persons]] [[Role::+]][[MediaWiki:Date::2001-09-11]]
| mainlabel=Name
| ?Role
| ?Phone
| ?E-mail
}}
```
This would present the members of a board valid at 9/11.

**Comment by kghbln** [comment]
This would require being able to query an outdated revision of a page which is currently not possible. I think this feature was already discussed here in an issue following SMWCon in Frankfurt as well as in connection to Multi Content Revisions (MCR). I am afraid your only shot is to adapt your data model in a way that it also stores historical data in the current revision of the page.

**Comment by mwjames** [comment]
> This would require being able to query an outdated revision of a page which
> is currently not possible. I think this feature was already discussed here

Exactly, SMW only knows the latest available truth (meaning that of
the latest available revision) or that of an approved revision (in
combination of [0]). There is concept in the datamodel that would
support different revision for the same entity.

> in an issue following SMWCon in Frankfurt as well as in connection to Multi
> Content Revisions (MCR). I am afraid your only shot is to adapt your data

MCR wouldn't change anything on the SMW side in terms of the latest
available truth as data from different slots would have to be merged
into one coherent representation for an entity. How that should be
done or how the whole slot mechanism works remains a mystery (at least
for me) as the documentation is rather ambiguous and no usable
extension exists (to my knowledge) that demonstrates the use of MCR
with different slots.

[0] https://github.com/SemanticMediaWiki/SemanticApprovedRevs

Cheers

**Comment by kghbln** [comment]
A related issue: #3345 (MCR) and with more info for historical data #2850
