### ISSUE TITLE
Constraints, value restrictions, and object classifications

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4032]
#3746 and #3830 introduced a new framework [0] for how constraint requirements and restrictions can be defined and attached (#3829) to a property. The new framework allows for a formalized and systematic approach to define and create atomic constraint definitions with the possibility to combine them into a coherent schema for a specific property that requires extended value validation and a stricter control over value assignments.

Creating constraint schemata with the `PROPERTY_CONSTRAINT_SCHEMA`  (#3746) type allows to define requirements for values assigned to a property but that type doesn't allow to define a broader group of constraints when properties belong to a class (aka category) to describe the characteristics of a claim.

To broaden the definition horizon for constraints and their validation, a new `CLASS_CONSTRAINT_SCHEMA` type is required to define a class schema that describes constraint conditions for members of a class to extend the validation and reevaluation of boundaries for values and properties of those members.

### Property vs. category

To help clarify the difference between the `PROPERTY_CONSTRAINT_SCHEMA` and `CLASS_CONSTRAINT_SCHEMA` type, it should be remembered that a category [1] is to "... divide content into groups that share similar characteristics ..." while a property is to "... describe individual characteristics of a class member ...".

![image](https://user-images.githubusercontent.com/1245473/58382238-6a428d80-7fb7-11e9-817b-a8518e8a37ad.png)

### Event
Let's take a simple example for a class that expects to be a collection of events with any entity that is assigned to the event class (e.g. `[[Category:Event]]`) to require a consistency checks in order to be interpretable as "event". To express of what is required for such an event, one could define:

- To have at least an "Event start" and "Event end" property present hereby making them mandatory (`mandatory_properties`) in the context of the assigned class
- The properties are expected to have a certain "shape" (`shape_constraint`) such as:
  - Appear only once (`max_cardinality`)
  - Be of the `Date` type
  - While "Has description" isn't mandatory, if present it is at least expected to contain a text with 100 characters (`min_textlength`) to be meaningful for the audience 

Semantic MediaWiki will provide base validators to define requirements and schemata but it will abstain from providing specialized checks for things that depend on a usage context like that where an "Event start" has to start before "Event end". A user can choose to implement a `custom_constraint` [2] such as `start_end_constraint` that checks for `greater_than`.

```
{
    "type": "CLASS_CONSTRAINT_SCHEMA",
    "constraints": {
        "mandatory_properties": [
            "Event start",
            "Event end"
        ],
        "shape_constraint": [
            {
                "property": "Event start",
                "property_type": "Date",
                "max_cardinality": 1
            },
            {
                "property": "Event end",
                "property_type": "Date",
                "max_cardinality": 1
            },
            {
                "property": "Has description",
                "property_type": "Text",
                "min_textlength": 100
            }
        ],
        "custom_constraint": {
            "start_end_constraint": {
                "greater_than": [
                    "Event end",
                    "Event start"
                ]
            }
        }
    },
    "tags": [
        "class constraint",
        "custom constraint"
    ]
}
```

### Person

```
{
    "type": "CLASS_CONSTRAINT_SCHEMA",
    "description": "Constraint that describes a person or human being",
    "constraints": {
        "mandatory_properties": [
            "Gender",
            "Name",
            "Birthdate",
            "Birthplace"
        ],
        "shape_constraint": [
            {
                "property": "Gender",
                "max_cardinality": 1
            }
        ]
    },
    "tags": [
        "class constraint"
    ]
}
```

## Notes 

Despite the fact that SHACL (Shapes Constraint Language) [3] exists to describe constraints and conditions using the RDF syntax, Semantic MediaWiki uses a simplified JSON syntax [4] to allow novice as well as expert users to define constraints without having to learn SHACL or RDF hereby making its administration and management more likely to be adopted by different user groups that have only a loose affiliation with semantic web technologies.

[0] https://www.semantic-mediawiki.org/wiki/Constraint_schema
[1] https://www.semantic-mediawiki.org/wiki/Help:Classification
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/examples/register.custom.constraint.md
[3] https://www.w3.org/TR/shacl/
[4] https://www.semantic-mediawiki.org/wiki/Help:Schema/Type/PROPERTY_CONSTRAINT_SCHEMA

**Comment by krabina** [comment]
Note: With [ShapeExpressions](https://en.wikipedia.org/wiki/ShEx) (ShEx) there is a somewhat comparable standard that could fit better into the constraint schema approach thatn SHACL.
See
- https://shex.io/
- https://book.validatingrdf.com/bookHtml013.html
