### ISSUE TITLE
Use @@@ syntax for property links without actually linking.

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#4037]
### Feature request
The [@@@ syntax to generate a property link](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1855) feature is great, but there are several use cases where in your wiki you don't want users to visit property pages.

Therefore it would be great to be able to use the feature of having the preferred property label and property description showing up in a tooltip, but without the possibility to actually click on it an got to the property page. 

This could be achieved by the syntax
`[[Foo::@@@|@@@]]` (where `|@@@]]` indicates a no link)

A workaround is to use something like
`{{#show:Property:Foo|?has preferred property label|+lang={{USERLANGUAGECODE}}}}`
to display the correct name of the poperty and then also do the tooltip in a similar way which is a lot of coding and querying in templates...

This is what it can look like when done manually:
![grafik](https://user-images.githubusercontent.com/4318745/58171769-05292800-7c97-11e9-959d-1fcd4f81de45.png)

As there is no link present, users don't know that they can hover over the property names. Therefore it might be better to have it undlined as with the Semantic Glossary extension.
![grafik](https://user-images.githubusercontent.com/4318745/58171871-415c8880-7c97-11e9-991c-0e0b4deaaf29.png)

**Comment by krabina** [comment]
Ideally, this would go together with a new value for the "headers" parameter value for aks queries:
`|headers=tooltip` to be used e. g in result format table.

This would be the same as `|headers=plain`, but show the tooltips for the properties instead of just the names.

**Comment by mwjames** [comment]
> As there is no link present, users don't know that they can hover over the
> property names. Therefore it might be better to have it undlined as with the
> Semantic Glossary extension.

That won't be part of the change but we can provide a CSS class such
as `smw-property` (those with a link) and `smw-property.nolink (for
those with no link) that users can facilitate on if they deemed to see
it necessary.

**Comment by mwjames** [comment]
> Ideally, this would go together with a new value for the "headers" parameter
> value for aks queries:
> `|headers=tooltip` to be used e. g in result format table.
>
> This would be the same as `|headers=plain`, but show the tooltips for the
> properties instead of just the names.

The use of `@@@` and the display of a property via a result printer
are two distinct components that don't share any coding path (just
because they appear similar in the output doesn't mean the have the
same origin) therefore adding something like `|headers=tooltip` would
be a different request.

It should be noted that adding `|headers=tooltip` would require
additional effort and testing which is beyond the scope and cannot be
part of this request.

**Comment by jaideraf** [comment]
> [[Foo::@@@|@@@]]

I wonder if the sintaxis `[[Foo::@@@=#]]`, `[[Foo::@@@#]]`, `[[Foo::@@@|#]]`, wouldn't be more appropriate, considering we normally use "#" to tell SMW to print plain (unformatted) text. [0]

[0] https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#Plain_.28unformatted.29_printouts

**Comment by krabina** [comment]
Great idea, [[Foo::@@@#]] looks most intuitive for me, since this could be used in conjunction with [[Foo::@@@#|Bar]]

**Comment by mwjames** [comment]
It can be either `[[Foo::@@@|@@@]]` or `[[Foo:@@@|#]]` anything else
would require extra parsing and coding since we expect to support
`[[Foo::@@@en]]` where `@en` indicates the forced language. The only
place for a formatting directive is to misuse the caption `|...]]`.

**Comment by krabina** [comment]
Then I guess this makes most sense: [[Foo::@@@|#]]

`[[Foo::@@@]]` - Regular display for property links: link with name and description of property in language of user
`[[Foo::@@@en] `- Regular display: link with name and description of property in English
`[[Foo::@@@|Bar]]` - Regular display: forcing display of "Bar" including link to property and description in  language of user
`[[Foo::@@@en|Bar]]` - Regular display: forcing display of "Bar" including link to property and description in english
`[[Foo::@@@|#]] `- New display of property name without link, but usual hover with description in language of user
`[[Foo::@@@en|#]] `- New display of property name without link, but usual hover with description in English
`[[Foo::@@@|Bar#]] `- New display: forcing display of "Bar" without link, but usual hover with description in language of user
`[[Foo::@@@en|Bar#]] `- New display: forcing display of "Bar" without link, but usual hover with description in English
In case you don't want a hover at all, simply don't define preferred labels/descriptions on the property page.

**Comment by mwjames** [comment]
> `[[Foo::@@@]]` - Regular display for property links: link with name and
> description of property in language of user
> `[[Foo::@@@en] `- Regular display: link with name and description of
> property in English
> `[[Foo::@@@|Bar]]` - Regular display: forcing display of "Bar" including
> link to property and description in  language of user
> `[[Foo::@@@en|Bar]]` - Regular display: forcing display of "Bar" including
> link to property and description in english

Should be covered by p-0212 (integration test).

> `[[Foo::@@@|#]] `- New display of property name without link, but usual
> hover with description in language of user
> `[[Foo::@@@en|#]] `- New display of property name without link, but usual
> hover with description in English

Expected to be supported.

> `[[Foo::@@@|Bar#]] `- New display: forcing display of "Bar" without link,
> but usual hover with description in language of user
> `[[Foo::@@@en|Bar#]] `- New display: forcing display of "Bar" without link,
> but usual hover with description in English

Not going to be supported.

**Comment by mwjames** [comment]
> In case you don't want a hover at all, simply don't define preferred
> labels/descriptions on the property page.

I would suggest (so does the documentation) that a property has always
a description so users have less interpretive freedom on what the
property is expected to represent hereby making hopefully less input
errors when assigning values to it.

Don't use `@@@` if you don't want a property to display a preferred
label or description tooltip.
