### ISSUE TITLE
Inline query (ask) doesn't find page with accented characters

### ISSUE THREAD

**Issue by otisyves** [SemanticMediaWiki/SemanticMediaWiki#4052]
### Setup and configuration

- SMW version: 3.02
- MW version: 1.31.1
- PHP version: 7.0.32
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.6.36
- Main language : Fr
- $wgShellLocale = "C.UTF-8";

### Issue

When asking (inline query) with a property containing one or more accented chars, no result appears, even if the requested page exists.

The same query with the like operator (~) gets the same result.

Removing the first accented char of the string and using the wildcard makes it work.

The length of the string doesn't seem to be a factor.

Detailed example here 
- https://wiki.lineaire-ecoconstruction.com/wiki/Test_ask

**Comment by mwjames** [comment]
> The length of the string doesn't seem to be a factor.
>
> Detailed example here
> - https://wiki.lineaire-ecoconstruction.com/wiki/Test_ask

We test for special characters in queries, furthermore creating an
annotating with something like `[[Has description::Plans 3D de la
charpente aprè abc]]` (`Has description` being a Text type) allows a
query `[[Has description::~Plans 3D de la charpente aprè*]]` to return
the expected results.

For now, I assume that some database specific settings are responsible
why a SQL query like below doesn't return any results.

The debug output (using `format=debug`) should be similar to:

```
SELECT DISTINCT
  t0.smw_id AS id,
  t0.smw_title AS t,
  t0.smw_namespace AS ns,
  t0.smw_iw AS iw,
  t0.smw_subobject AS so,
  t0.smw_sortkey AS sortkey, t0.smw_sort
FROM
  `smw_object_ids` AS t0
INNER JOIN
  (`smw_di_blob` AS t1
INNER JOIN
  `t2` AS t2 ON t1.p_id=t2.id) ON t0.smw_id=t1.s_id
WHERE
  (
   (t1.o_hash LIKE 'Plans 3D de la charpente aprè%')
  )
  AND t0.smw_iw!=':smw'
  AND t0.smw_iw!=':smw-delete'
  AND t0.smw_iw!=':smw-redi'
ORDER BY
  t0.smw_sort ASC
LIMIT
  25
OFFSET
  0
```

**Comment by mwjames** [comment]
@kghbln maybe the example from [0] can be submitted as integration
test (in JSON format) including `Page` and `URI` type for accented
chars using a wildcard search pattern.

PS: There should be some tests in [1] but I cannot find them right now.

[0] https://wiki.lineaire-ecoconstruction.com/wiki/Test_ask
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/README.md

Cheers

**Comment by otisyves** [comment]
Will check for our MySQL setup but we have the same configs for all our wikis. This is the only one on SMW 3.0.2 though (in dev.)
I put the debug code on the example page.

**Comment by mwjames** [comment]
> > I put the debug code on the example page.

This doesn't help much.

You should add a query with the mentioned condition and use
`format=debug`. Also you find the table `smw_di_blob` and compare the
`o_hash` field on whether it contains accented characters or not.

**Comment by mwjames** [comment]
Some notes on accented characters and MySQL:

- https://stackoverflow.com/questions/14083847/accented-characters-in-mysql-table
(table collation set to utf8_general_ci)
- https://superuser.com/questions/978203/issues-sending-latin-accented-characters-%C3%A3-%C3%B5-%C3%A1-%C3%A9-%C3%AD-to-a-database-table-in-ph
- https://xaviesteve.com/1223/issues-with-accents-and-strange-characters-in-php-mysql-solved/

**Comment by otisyves** [comment]
Found that the DB  was created a while ago was and set to ISO-Latin-Swedish. 

Thx for the help.

**Comment by kghbln** [comment]
> ISO-Latin-Swedish

Thanks for reporting back. Indeed, this is ouch but can occur on old instances. Only do binary for database for best experience.

**Comment by mwjames** [comment]
>> ISO-Latin-Swedish
>
> Thanks for reporting back. Indeed, this is ouch but can occur on old
> instances. Only do binary for database for best experience.

Maybe the installation instruction could have a checklist and include
things like:

- [ ] Temporary tables are enabled
- [ ] UTF-8 is enabled (including mb* functions)
- [ ] Cache is enabled
- [ ] DB table collation is set to binary or UTF-8 safe etc.
- and so on ...

The next time similar questions arise, you may ask people to submit
the checklist as well.
