### ISSUE TITLE
Query / #ask query with large number of fields gives 404

### ISSUE THREAD

**Issue by Spudley** [SemanticMediaWiki/SemanticMediaWiki#406]
Hi.

I'm trying to generate a CSV file from data on an SMW-based site.

The site's main category is called Case Studies: I need to generate a CSV file of all case studies, with all the properties stored against each one. There are 109 fields to query.

I have been successful in writing queries that can give me some of the properties, but not all of them. For example, I can query the first 60 properties, and get results. But if I attempt to add another property after them, all I get is a 404 error.

Likewise, I can query another group of 40 properties before running into the same issue adding one more property.

All of the properties can be queried successfully as long as they're in a short query; the problem only occurs when writing a query with large numbers of properties.

When the error occurs, it happens immediately; successful queries take time to run and produce results, but if it is going to give a 404, it will do so without waiting. This tells me that it isn't a memory issue.

The issue is the same whether I am generating a CSV or a Broad table, and also consistent between both the semantic search page (Special:Ask) and {{ask}} queries embedded in a page.

The error is definitely a 404 (confirmed in Firebug et al), although "not found" is clearly not a good description of what is actually happening.

Can anyone explain what is happening here, and more importantly suggest how to resolve it (or work around it)?

Thank you.

For ref:

_Special:Version_

```
MediaWiki   1.21.1
PHP     5.4.10 (cgi-fcgi)
MySQL   5.5.20-log
```

_Installed extensions_

```
Semantic extensions
Semantic Compound Queries (Version 0.3.4)   A parser function that displays multiple semantic queries at the same time  Yaron Koren
Semantic Forms (Version 2.4.2)  Forms for adding and editing semantic data  Yaron Koren, Stephan Gambke and others
Semantic Forms Inputs (Version 0.6) Additional input types for Semantic Forms   Stephan Gambke and others
Semantic Maps (Version 2.0.1.2) Provides the ability to view and edit coordinate data stored with the Semantic MediaWiki extension (more info...)   Jeroen De Dauw
Semantic MediaWiki (Version 1.8.0.5)    Making your wiki more accessible - for machines and humans (online documentation)   Markus Krötzsch, Denny Vrandecic, Jeroen De Dauw and others
Special pages
Data Transfer (Version 0.4.1)   Allows for importing and exporting data contained in template calls     Yaron Koren
Delete Batch (Version 1.4)  Delete a batch of pages     Bartek Łapiński
Nuke (Version 1.1.7)    Gives administrators the ability to mass delete pages   Brion Vibber and Jeroen De Dauw
Parser hooks
Maps (Version 2.0.1)    Enables embedding of dynamic maps into wiki pages, geocoding of addresses and other geographical operations. (more info...)     Jeroen De Dauw
ParserFunctions (Version 1.5.1) Enhance parser with logical functions   Tim Starling, Robert Rohde, Ross McClure and Juraj Simlovic
Vote (Version 2.5.1)    JavaScript-based voting with the <vote> tag     Aaron Wright, David Pean and Jack Phoenix
Spam prevention
ConfirmEdit (Version 1.2)   Provides CAPTCHA techniques to protect against spam and password-guessing   Brion Vibber and others
Other
AddThis (Version 1.0.1) Adds AddThis widget to the sidebar and displays a toolbar on page headers which can be reproduced anywhere by inserting the <addthis /> tag     Gregory Varnum (Contributions by John Du Hart)
Google Analytics Integration (Version 2.0.2)    Inserts Google Analytics script (ga.js) in to MediaWiki pages for tracking  Tim Laqua
Google Maps Extension (Version 0.9.42)  <gm-descs>  Evan Miller
Google Translator (Version 0.1) Adds Google Translator to the sidebar   Joachim De Schrijver
NewUserMessage (Version 3.2, 2011-07-14)    Adds a message to newly created user's talk pages   Nad and Siebrand Mazeland
Personal Homepage (Version r671)    an extension to allow users to customise the Main Page  Mark Clements
UserPageEditProtection (Version 2.0)    Restricts editing on user pages to user and allowed editors     Lisa Ridley and Eric Gingell
Validator (Version 0.5.1)   Provides generic parameter handling support for other extensions    Jeroen De Dauw
```

**Comment by mwjames** [comment]
Quoting from https://stackoverflow.com/.../what-is-the-maximum-possible-length-of-a-query-string:

"RFC 3986 also states there is no limit, but indicates the hostname is limited to 255 characters because of DNS limitations (section 2.3.3). Microsoft states that the maximum length of a URL in Internet Explorer is 2,083 characters, with no more than 2,048 characters in the path portion of the URL.May 1, 2009"

For a working example, see https://sandbox.semantic-mediawiki.org/wiki/Issue/406.
