### ISSUE TITLE
MW1.33+: Maintenance logging no longer works due to missing user

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4077]
### Setup and configuration

- MediaWiki | 1.33.0-rc.0 (c733c85)19:29, 7. Jun. 2019
- PHP | 7.2.19-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.40-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.0-alpha (371c70a) 18:09, 6. Jun. 2019

### Issue
Since the upgrade to MediaWiki 1.33.0-rc.0 the maintenance logging for the maintenance scripts by SMW no longer shown. Moreover it is no longer possible to create new entries using the `--with-maintenance-log` flag.

```
[1d697fb2d43da21358449d21] [no req]   CannotCreateActorException from line 2516 of /../w/includes/user/User.php: Cannot create an actor for a usable name that is not an existing user
```
### Stacktrace
```
#0 /../w/includes/ActorMigration.php(220): User->getActorId(Wikimedia\Rdbms\DatabaseMysqli)
#1 /../w/includes/logging/LogEntry.php(718): ActorMigration->getInsertValues(Wikimedia\Rdbms\DatabaseMysqli, string, User)
#2 /../w/extensions/SemanticMediaWiki/src/MediaWiki/ManualEntryLogger.php(73): ManualLogEntry->insert()
#3 /../w/extensions/SemanticMediaWiki/src/Maintenance/MaintenanceLogger.php(69): SMW\MediaWiki\ManualEntryLogger->log(string, User, string, string)
#4 /../w/extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php(158): SMW\Maintenance\MaintenanceLogger->log(string)
#5 /../w/maintenance/doMaintenance.php(96): SMW\Maintenance\RebuildConceptCache->execute()
#6 /../w/extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php(188): require_once(string)
#7 {main}
```

### Steps to reproduce
```
php w/extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php --create --with-maintenance-log
```
Produces the following output followed by the stacktrace.
```
Creating/updating concept caches. Use CTRL-C to abort.

(0) Creating cache for "Concept:Issue/1157/1" ...
(1) Creating cache for "Concept:Issue/1157/2" ...
(2) Creating cache for "Concept:InversePageCreatorLastEditorIs" ...
(3) Creating cache for "Concept:Can be referenced in accordance with" ...
(4) Creating cache for "Concept:Books in German" ...
(5) Creating cache for "Concept:Books in English" ...
(6) Creating cache for "Concept:Books" ...
(7) Creating cache for "Concept:Tracks" ...
(8) Creating cache for "Concept:NFL:Data" ...

Done.
```

## Notes

When applying the schema changes with `update.php` the following notes were issued when doing 

```
Beginning migration of logging.log_user and logging.log_user_text to logging.log_actor

..

... log_id=1700
User name "RebuildPropertyStatisticsLogger" is usable, cannot create an anonymous actor for it. Run maintenance/cleanupUsersWithNoId.php to fix this situation.

User name "RebuildConceptCacheLogger" is usable, cannot create an anonymous actor for it. Run maintenance/cleanupUsersWithNoId.php to fix this situation.

User name "RebuildDataLogger" is usable, cannot create an anonymous actor for it. Run maintenance/cleanupUsersWithNoId.php to fix this situation.

... log_id=1800

..
```

When running `maintenance/cleanupUsersWithNoId.php --prefix=sbxsmw` as instructed the result was:

```
Beginning cleanup of logging
... log_timestamp=20160803040402 log_id=2044
... log_timestamp=20160919010104 log_id=2644
... log_timestamp=20161103040402 log_id=3167
... log_timestamp=20161205010105 log_id=3653
... log_timestamp=20170106020205 log_id=4171
... log_timestamp=20170205010104 log_id=4560
... log_timestamp=20170308040402 log_id=4755
... log_timestamp=20170409040402 log_id=5141
... log_timestamp=20170511020205 log_id=5552
... log_timestamp=20170612010104 log_id=5840
... log_timestamp=20170715020206 log_id=6277
... log_timestamp=20170816010106 log_id=6562
... log_timestamp=20170917010110 log_id=6831
... log_timestamp=20171020020206 log_id=7317
... log_timestamp=20171120040402 log_id=7736
... log_timestamp=20171223010108 log_id=8062
... log_timestamp=20180123040402 log_id=8349
... log_timestamp=20180225040402 log_id=8658
... log_timestamp=20180328020205 log_id=8942
... log_timestamp=20180428040403 log_id=9328
... log_timestamp=20180531020211 log_id=9697
... log_timestamp=20180703040406 log_id=9834
... log_timestamp=20180804092147 log_id=10077
... log_timestamp=20180906010104 log_id=10218
... log_timestamp=20181010040405 log_id=10358
... log_timestamp=20181111040407 log_id=10485
... log_timestamp=20181213010111 log_id=10672
... log_timestamp=20190114005109 log_id=10922
... log_timestamp=20190213160732 log_id=11251
... log_timestamp=20190316040403 log_id=11428
... log_timestamp=20190422020401 log_id=11592
... log_timestamp=20190608020402 log_id=21066
Completed cleanup, assigned 0 and prefixed 3195 row(s)
```

**Comment by mwjames** [comment]
> [1d697fb2d43da21358449d21] [no req]   CannotCreateActorException from line 2516 of /../w/includes/user/User.php: Cannot create an actor for a usable name that is not an existing user

Seriously!?!

I'd say that worked before and it should work on 1.33+. I'm not going to invest any time into digging of what has changed, so please contact the responsible WMF developer and ask for support of how to remedy this regression.

**Comment by kghbln** [comment]
> so please contact the responsible WMF developer and ask for support of how to remedy this regression.

Reported with [T225361](https://phabricator.wikimedia.org/T225361). I guess in the end we need a sane way of automatically creating the respective users when installing SMW.

**Comment by kghbln** [comment]
After manually creating an account called "RebuildConceptCacheLogger" the logging [works again](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Journal?type=smw&user=&page=&wpdate=&tagfilter=). I know that MediaWiki automatically creates new users. Thus it should be possible to do so for Semantic MediaWiki too. Dunno how painful this is though.

**Comment by mwjames** [comment]
The following code used to work, raising an exception in MW 1.33+ because of some internal changes is a BC break and should go through a proper deprecation. Furthermore, I expect a migration path so that established functionality can be retained without breaking this in the next release again.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/5b80143ec548336a2eb1a63f1b21156625fecf20/src/MediaWiki/ManualEntryLogger.php#L56-L74

> Thus it should be possible to do so for Semantic MediaWiki too. Dunno how painful this is though.

I don't want to deal with any user/bot/session management as it pulls in MW dependencies as increases the likelihood of a breakage (evidence is this issue itself).

**Comment by kghbln** [comment]
The extend of my question on phabricator was not fully understood when it comes to the impact on other  extensions but we got an answer.

**Comment by mwjames** [comment]
> extensions but we got an answer.

If I interpret the answer from the cited phab ticket correctly then
the following change should restore known behaviour:


```
@@ -61,11 +61,11 @@ class ManualEntryLogger {

 		$logEntry = $this->newManualLogEntryForType( $type );
 		$logEntry->setTarget( Title::newFromText( $target ) );

 		if ( is_string( $performer) ) {
-			$performer = User::newFromName( $performer );
+			$performer = User::newSystemUser( $performer, [ 'steal' => true ] );
 		}
```

**Comment by kghbln** [comment]
> If I interpret the answer from the cited phab ticket correctly then the following change should restore known behaviour:

Let's see what happens. I can test with "rebuildFulltextSearchTable.php"
