### ISSUE TITLE
MW 1.34+, use DB_REPLICA

### ISSUE THREAD

**Issue by legoktm** [SemanticMediaWiki/SemanticMediaWiki#4093]
I merged https://github.com/wikimedia/mediawiki/commit/0653e575fc641ee828a949b2e06a11a7500ab3cd earlier today, which removed the long-deprecated `DB_SLAVE`. Its replacement, `DB_REPLICA` was introduced in 1.28.0, and backported in 1.27.4, so SMW should be able to transition with no problem, AIUI (let me know if I assumed wrongly).

**Comment by kghbln** [comment]
Thanks for notifying!
