### ISSUE TITLE
Not able to escape characters inside property value

### ISSUE THREAD

**Issue by jups23** [SemanticMediaWiki/SemanticMediaWiki#4095]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.32.2
- PHP version: 7.2.3 (cgi-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.6.19-67.0-log

### Issue
When setting the value for the “Has text” attribute I would have expected to be able to escape characters using <nowiki>.

#### Input:
**Expected solution**
a) [[Has text::Here comes my text <nowiki>|</nowiki> This is another text]]

**Alternative attempts**
b) [[Has text::Here comes my text {{!}} This is another text]]
c) 
```
{{#set:
Has text=Here comes my text {{!}} This is another text
}}

{{#ask: [[Has text::~"comes"]]
 |?Has text
}}
```

#### Expected output
I would have expected in all three cases a, b, c:

Here comes my text | This is another text

### Stack trace
a)
```
Here comes my text '"`UNIQ--nowiki-00000003-QINU`"' This is another text
```
b)
```
This is another text
```

c) Warning:
![Screen Shot 2019-06-15 at 22 43 53](https://user-images.githubusercontent.com/217980/59556222-20016a80-8fbf-11e9-806c-bcd6ce0918c9.png)

### Steps to reproduce
https://sandbox.semantic-mediawiki.org/wiki/Issue/4095_(Not_able_to_escape_characters_inside_property_value)

**Comment by kghbln** [comment]
Thanks for reporting. Did you add `SMW_PARSER_UNSTRIP` to the [`$smwgParserFeatures`](https://www.semantic-mediawiki.org/wiki/Help:$smwgParserFeatures) configuration parameter?

**Comment by jups23** [comment]
Thank you for the quick reply! I've just tried adding it but I still get the same processing error.

```
Property "Has text" (as page type) with input value "Here comes my text | This is another text" contains invalid characters or is incomplete and therefore can cause unexpected results during a query or annotation process. 
```
The markup I've added is: `[[Has text::Here comes my text <nowiki>|</nowiki> This is another text]]`.

I've gotten the same error with both versions in my LocalConfig.php, at the bottom of the file after the call to `enableSemantics`.

1)  `$smwgParserFeatures = SMW_PARSER_UNSTRIP;`
2) `$smwgParserFeatures = $smwgParserFeatures | SMW_PARSER_UNSTRIP;`

Could you guess what's going on?

**Comment by kghbln** [comment]
> Could you guess what's going on?

Do not do 1 since you remove all other parser features. 2 should do the trick. Did you edit the page after changing the configuration to clear the parser cache for that page. Apart from that I am not sure why it is not working for you. Anyways I'd say you should probably avoid pipes within property values.

**Comment by jups23** [comment]
Yes, I've tried (1) only to be really sure.
I've edited the page multiple times and also hit in the menu More->Refresh a couple of times.

It is not only with pipes that I keep getting this error but also with other tags, e.g.

[[Has text::<pre>Here comes my text. This is another text</pre>]]

I am still wondering if it is either a regression or some setting or plugin is missing to have text like that.

**Comment by jups23** [comment]
See http://grantha-test.jiva.org/index.php?title=%C5%9Ar%C4%ABdhara%E1%B8%A5_Bhagavad-g%C4%ABt%C4%81_2.1

**Comment by jups23** [comment]
Thank you very much for your help, I'm very excited about using Semantic MediaWiki as a basis for a Sanskrit text library with semantic links and semantic search (which authors have commented on a certain passage etc.)!

**Comment by kghbln** [comment]
I have no idea as to why you still cannot annotate in a way that you get the same results as on sandbox. Anyways I still think it is an utterly bad idea wanting to store pipes with in data values.

**Comment by kghbln** [comment]
This may very well be a feature request. In this case a developer for this will be needed. Thus I added this enhancement to the "Enhancements and features" project as "open. Closing here.
