### ISSUE TITLE
ReplicationWiki page suddenly displayed empty

### ISSUE THREAD

**Issue by jhoeffler** [SemanticMediaWiki/SemanticMediaWiki#4096]
### Setup and configuration

- SMW version:  
- MW version: Generator:MediaWiki 1.19.8 (1.19.8)
- PHP version: 5.4.45-0+deb7u14 (5.4) 
- DB system (MySQL, Blazegraph, etc.) and version: MySQL

_Note that it is **required** to provide the setup and configuration information. If you believe to have detected a regression after updating your software please also provide information about your previous setup as well. **In any case only this information will enable us to allocate appropriate review time.** Thank you for you help._

### Issue
_Please describe the issue as best as you can and also fill in the following two sections if applicable._
The page http://replication.uni-goettingen.de/wiki/index.php/ReplicationWiki:Help/FAQ that previously worked fine, after a harmless addition of external links is suddenly displayed completely empty, also in older versions or when trying to display something that works on other pages.

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
Placeholder for the stack trace or code!
```

### Steps to reproduce
_It is recommend to use the [sandbox](https://sandbox.semantic-mediawiki.org) to demonstrate the observed issue, otherwise provide us with a simple reproducible use case._

**Comment by jaideraf** [comment]
> MediaWiki: 1.19.8
> Semantic MediaWiki: 1.8.0.5

We do not support these old versions. Please update [0] your wiki environment. [1]

[0]https://www.semantic-mediawiki.org/wiki/Help:Upgrade
[1]https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md#platform-compatibility-and-release-status

**Comment by jhoeffler** [comment]
Thanks for the quick reply. Apparently the problem was caused by an update of the PHP version from 5.4 to 5.6, which has now been temporarily undone. We do not currently have the resources to update but it seems we have to find them. Thank you very much again.

**Comment by kghbln** [comment]
Indeed, ante antediluvian versions of PHP and MW and SMW are no longer supported. I strongly recommend to upgrade all of this.
