### ISSUE TITLE
Maintenance script setupStore.php fails for 'it' localization

### ISSUE THREAD

**Issue by carlo66** [SemanticMediaWiki/SemanticMediaWiki#4097]
### Setup and configuration

- SMW version:3.1.0-alpha (1876d13) 2019-06-12T11:05:43
- MW version:1.32.0
- PHP version:7.0.33-0ubuntu0.16.04.1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version:5.7.21-0ubuntu0.16.04.1

### Issue
After installing SemanticMediaWiki with composer,  execution of setupStore.php fails. Line 104 of includes/title/TitleValue.php (see line  #0 in Stack trace below) shows that the problem is the trailing underscore in parameter $dbKey. The value is the localized name of property "Corresponds to".

The problem is solved by removing the trailing space in the property name (line 53 in SemanticMediaWiki/i18n/extra/it.json).

### Stack trace
setupStore.php output:

```
  Import of smw.vocab.json ...
     ... creating MediaWiki:Smw import skos ...
     ... creating MediaWiki:Smw import foaf ...
     ... creating MediaWiki:Smw import owl ...
     ... creating Proprietà:Foaf:knows ...
  [bfcf86f36e17437042343171] [no req]   Wikimedia\Assert\ParameterAssertionException from line 63 of /var/www/html/wiki_1.32.0_SMW_3.1.0/vendor/wikimedia/assert/src/Assert.php: Bad value for parameter $dbkey: invalid DB key 'Corrisponde_a_'
  Backtrace:
  #0 /var/www/html/wiki_1.32.0_SMW_3.1.0/includes/title/TitleValue.php(105): Wikimedia\Assert\Assert::parameter(boolean, string, string)
  #1 /var/www/html/wiki_1.32.0_SMW_3.1.0/includes/cache/LinkBatch.php(179): TitleValue->__construct(integer, string)
  #2 /var/www/html/wiki_1.32.0_SMW_3.1.0/includes/cache/LinkBatch.php(143): LinkBatch->addResultToCache(LinkCache, Wikimedia\Rdbms\ResultWrapper)
```

**Comment by kghbln** [comment]
Thanks a lot for reporting and also providing info about how to resolve. This is apparently a pretty old bug. @mwjames Perhaps some test can be added to make sure that trailing spaces are detected?
