### ISSUE TITLE
AR SESP values don't update until next edit

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticMediaWiki#4102]
### Setup and configuration
- MW version: 1.31.1 (a4c8065)
- PHP version: 7.1.30
- SMW version: 3.0.0
- SESP version: 2.0.0
- AR Version: 1.0 (b2f77fb)

I'm observing an issue in the combined use of SMW, SESP, and ApprovedRevs. 

The desired behavior is to have the "approval status" of the page available to the wiki as a semantic property of the page via SESP after an AR state change. AR works well but the SESP AR values don't update until the page is edited. 

It's not clear to me which of the 3 extension (SMW, AR, SESP) is not addressing this scenario properly, but as a quick fix, I altered AR to perform a auto-edit in the background after each time the page is either 'approved' or 'unapproved'.  This solved the problem perfectly but 
1) this is probably not the right way to fix this
2) my fix is not merged in the AR extension
3) it forces users to accepted an edit with each approval/disapproval.

Hexmode said this was supposed to be fixed in SMW in issue 3230, but I'm observing that it is not. 

NOTE this is not a simple matter of waiting for the job queue to run. My job queue is clear and the SESP values do not update with my auto-edit hack in AR.

ref: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3230

**Comment by revansx** [comment]
Here's how I fixed this issue by hacking AR to produce an edit to announce the approval state change

```
	// Seems to be needed when the latest version is approved -
	// at least when the Cargo extension is being used.
	$this->page->doPurge();
       	#$this->page->view();
    
    	global $egApprovedRevsAppendArticleWithMsg;
    	if($egApprovedRevsAppendArticleWithMsg) {
	    	$zPage = WikiPage::newFromID( $this->page->getTitle()->getArticleId() );
			if ( $zPage ) { 
			  $zContent = $zPage->getContent( Revision::RAW );
			  $zText = ContentHandler::getContentText( $zContent )."\n\n{{Approval Log|Approved|".date("Y/m/d h:i:s",time())."|".$user."}}";
			  $zPage->doEditContent( ContentHandler::makeContent( $zText, $zPage->getTitle() ), "[Auto-append] Approved." ); 
			  $zPage->doPurge(); 
			}
        }
    
		// Show the revision.
		$this->page->view();
	}
```

This works if you don't mind an automatic edit made by AR after the approval/disapproval to announce the change to the page .. *shrugs* .. I'm ok with it, so if no one wants to fix this properly, I'll just keep my own version of AR on hand until this issue is truly fixed and the combined extensions are verified to work as expected.

**Comment by mwjames** [comment]
I think I tried to explain the issue in #3230 on what is required which is why I also responded to https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/108 explaining the details of the issue and for that matter [0] exist to address the issue.

You can test SemanticApprovedRevs in the sandbox using the `Extra` namespace as demonstrated here [1].

[0] https://github.com/SemanticMediaWiki/SemanticApprovedRevs
[1] https://sandbox.semantic-mediawiki.org/wiki/Extra:ApprovedRevs

PS: SemanticApprovedRevs requires SMW 3.1+, and no, you cannot use with SMW 3.0 (see https://github.com/SemanticMediaWiki/SemanticApprovedRevs/issues/3#issuecomment-471176366).

**Comment by revansx** [comment]
SMW 3.1... ah.. ok.. thank you!

**Comment by mwjames** [comment]
> SMW 3.1... ah.. ok.. thank you!

Yes, but only in combination with `SemanticApprovedRevs` and SESP will loose any special handling of AR related properties [0].

[0] https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/111

**Comment by revansx** [comment]
ok. I'm confused about which is expected to be used.. AR or SAR? Currently
I'm using is AR. Is this an issue?

**Comment by mwjames** [comment]
> ok. I'm confused about which is expected to be used.. AR or SAR? Currently

How so, the description of `SemanticApprovedRevs` "Complementary extension to Semantic MediaWiki and Approved Revs to control the storage of approved revision content" should make it clear that the extension is about Semantic MediaWiki __and__ Approved Revs.

**Comment by mwjames** [comment]
Furthermore, the requirements section [0] should not allow much room for interpretation.

[0] https://github.com/SemanticMediaWiki/SemanticApprovedRevs#requirements

**Comment by revansx** [comment]
Thank you for being patient with me. I'm clearly having trouble processing
something basic. Are you saying that both ApprovedRevisions AND Semantic
Approved Revisions are BOTH necessary for SESP to work with SMW?

**Comment by mwjames** [comment]
> Are you saying that both ApprovedRevisions AND Semantic Approved Revisions are BOTH necessary for SESP to work with SMW?

No.

As I tried to explain earlier, any reference to AR in SESP will be removed and instead `SemanticApprovedRevs` has been created to deal with subtleties of the integration (i.e. how approved revision are managed by AR) between AR and SMW including the setting of Approved* properties which made it necessary to isolate related code paths and put them into a separate extension where AR is a requirement to `SemanticApprovedRevs` but not to SESP.

SESP will be independent of `SemanticApprovedRevs` and after [0] has been merged will no longer have any relation to AR, any code related to AR processing should be handled by `SemanticApprovedRevs` hence the name `Semantic` + `ApprovedRev`.

[0] SemanticMediaWiki/SemanticExtraSpecialProperties#111

**Comment by revansx** [comment]
Let me see if I have this right. When one uses SAR, then SESP is not needed
at all for AR related properties, but SESP is still needed for the non-AR
related properties that SESP already does so well.. in other words,
assuming I want the other non-AR related SESP properties like Creation
Date, etc.. I can load all 3 (AR, SAR, SESP) and everything should work. Is
this correct?

continued thanks,
/Rich

**Comment by revansx** [comment]
MWJames.. can you please tell me what combination of MW, SMW, AR, SAR
versions currently all work together?

I've removed SESP and can't get MW (1.31.1), SMW (3.0.2), AR (1.0), and SAR
(master from github) to work. Please .. What am I missing?

**Comment by kghbln** [comment]
SMW 3.1, SAR 1.0, SESP 3.0 and AR 1.0

**Comment by revansx** [comment]
Ok. So what I'm trying to do is not possible yet. Is that the case?
