### ISSUE TITLE
Setting "Extended" as the default search tab?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4115]
### Setup and configuration

- SMW version: 3.0+

### Issue
https://www.semantic-mediawiki.org/wiki/Help_talk:SMWSearch#Setting_.22Extended.22_as_the_default_search_tab_2774

> I have successfully implemented the SMWSearch configuration, but I cannot figure out how to set the 'Extended' tab as the default result view for searches. Is this a SMW configuration? or a MediaWiki configurations? thanks.

**Comment by mwjames** [comment]
For logged-on user, you may rely on the "Remember selection for future searches" checkbox which sets a cookie (this a MW functionality) and set the extended tab as default for this user. Unfortunately, [0] doesn't provide any hook to explicitly set a certain profile as default.

@kghbln @hexmode Having some method (e.g. hook) in [0] to set a default profile would made things easier for users and administrators.

## Notes

![image](https://user-images.githubusercontent.com/1245473/60384313-9f854400-9a6b-11e9-8992-cc35676b9582.png)

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/specials/SpecialSearch.php#L206-L257

**Comment by kghbln** [comment]
> For logged-on user, you may rely on the "Remember selection for future searches" checkbox 

Ah, I know about this but I was not aware that this also saves the selection of the search section and not just the namespaces to be searched which in turn may be predefined with `$wgNamespacesToBeSearchedDefault`

**Comment by mwjames** [comment]
>  to be searched which in turn may be predefined with $wgNamespacesToBeSearchedDefault

I'm not sure about this, anyhow the way this is suppose to work is not self-explanatory and MW should provide a proper way for extensions to define a default profile for users.

**Comment by kghbln** [comment]
> I'm not sure about this

It does work and I am actively using the configuration parameter on many wikis.

Feature request filed upstream with [T226896.](https://phabricator.wikimedia.org/T226896)

**Comment by mwjames** [comment]
> It does work and I am actively using the configuration parameter on many wikis.

Yes, but this setting has nothing to do with how the profile is determined in Special:Search, or? As far as I can see there is no "real" code path that allows you define a default profile from either a setting or hook.

**Comment by kghbln** [comment]
I do not believe that MediaWiki will make progress on the issue in the foreseeable future. Thus I added this enhancement to the "Enhancements and features" project as "open. Closing here.
