### ISSUE TITLE
Storing identical values to the same property within on subject?

### ISSUE THREAD

**Issue by 4L8** [SemanticMediaWiki/SemanticMediaWiki#4127]
### Setup and configuration

- SMW version: 3.0.2
- Semantic Result Formats: 3.0.1
- MW version: 1.32.2
- PHP version: 7.3.6-nmm1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL | 5.6.44-nmm1-log

### Issue
sum and count of attribute values only for different values (same values are ignored)

### example Wiki Page "Test"
```
{| class="wikitable"
|-
! Monat !! Tage (max) !! Tage ist
|-
| Januar || [[Tmax::31]] || [[Tist::1]]
|-
| Februar || [[Tmax::28]] || [[Tist::2]]
|-
| März || [[Tmax::31]] || [[Tist::3]]
|-
| April || [[Tmax::30]] || [[Tist::4]]
|-
| Mai || [[Tmax::31]] || [[Tist::5]]
|-
| Juni || [[Tmax::30]] || [[Tist::6]]
|-
| Juli || [[Tmax::31]] || [[Tist::7]]
|-
| August || [[Tmax::31]] || [[Tist::8]]
|-
| September || [[Tmax::30]] || [[Tist::9]]
|-
| Oktober || [[Tmax::31]] || [[Tist::10]]
|-
| November || [[Tmax::30]] || [[Tist::11]]
|-
| Dezember || [[Tmax::31]] || [[Tist::12]]
|-
! Summe !! "expected 365" != {{#ask: [[Test]]
| ?Tmax
| format=sum
}} !! "expected 78" = {{#ask: [[Test]]
| ?Tist
| format=sum
}}
|}
count Tmax "expected 12": {{#ask: [[Test]]
| ?Tmax
| format=count
}} count Tist "expected 12": {{#ask: [[Test]]
| ?Tist
| format=count
}}
```
the attributes are type number

### Steps to reproduce
*https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/MathSum

**Comment by 4L8** [comment]
added issue (initial)

**Comment by mwjames** [comment]
> | März || [[Tmax::31]] || [[Tist::3]]

> |-

> | April || [[Tmax::30]] || [[Tist::4]]

> |-

> | Mai || [[Tmax::31]] || [[Tist::5]]

This works as expected, the entity (MathSum in your example) has
one(!!) value [[Tmax:: 30]] and [[Tmax::31]] not as you might have
indicted several with the same value.

If you wanted to assign the same value pattern you would need
different entities (subjects or subobjects) to hold the values.

Again, assigning something like [[Foo::Bar]], [[Foo::Bar]],
[[Foo::Bar]] (aka more than once) to a single entity will only result
in one single assignment of [[Foo::Bar]].

If you browse the subject then you will see of what has been assigned
to the subject which builds the basis for any calculation a result
printer might execute.

Cheers

**Comment by kghbln** [comment]
[Values stored](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Issue-2FMathSum)

Something like this per month:
```
{{#subobject: |Has pagename={{PAGENAME}} |Is month=January |Tmax=31 |Tist=1 }}
```
Think of a subobject like an invisible page. However creating several visible pages is fine too as MWJames noted.
