### ISSUE TITLE
Deferred query not working for anons on whitelisted pages

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#4165]
**Setup**
MW 1.31.1, SMW 3.0.2

**Configuration**
The way I've set up read permissions is straightforward. First, the 'read' right has been revoked for anonymous visitors (that have not logged in). And then I set `$wgWhitelistReadRegexp` and `$wgWhitelistRead` to whitelist entire namespaces and specific pages. Unlike Toni Hermoso Pulido in #3053, I'm not using the Lockdown extension. 

**The problem**
When an anonymous visitor views one of the whitelisted pages, the deferred #ask query returns "You need read permission to use this module."

**Comment by kghbln** [comment]
I guess this is an enhancement request and the issue is that the API requires read permission in this kind of setup.

**Comment by mwjames** [comment]
> The way I've set up read permissions is straightforward. First, the 'read'
> right has been revoked for anonymous visitors (that have not logged in). And
> then I set $wgWhitelistReadRegexp and $wgWhitelistRead to whitelist entire

I think the error message "You need read permission to use this
module." describes the necessary requirement. If you have revoked the
read permission than this won't work  where it is generally assumed
that users have read permissions to use the feature.

The answer maybe unsatisfactory but if users want to support that kind
of use case I expect someone from the community to step-up and send a
PR that can address this issue.

PS: I have no plans (nor time) to look into this and investigate the
API for how to make it work.

> I guess this is an enhancement request and the issue is that the API requires read permission in

Yes (and after 90 days it is going to be closed and moved to the
enhancement request). I urge anyone how wants to see enhancements to
become a reality to promote such requests to a wider audience by
either notifying the mailing list or take the discussion to a venue
like the upcoming SMWCon.

**Comment by D-Groenewegen** [comment]
Thank to you both for giving a clear answer and managing expectations. 

What I half-assumed at first is that whitelisting a page so that it becomes viewable again is achieved by lifting restrictions to read permissions, but evidently, as I understand now, that's not how MediaWiki's method of whitelisting works. Could be a bypass, for all I know. 

I'll consider other options first and will see then if the issue is important enough to take further steps.

**Comment by kghbln** [comment]
The whole system of restricting view access is different and much more complicated in comparision to just restricting write access. This would require refactoring in MediaWiki core already. Last year I was told that this is a week or so just there, if I am not mistaken.

**Comment by kghbln** [comment]
> I'll consider other options first and will see then if the issue is important enough to take further steps.

Feel free to reopen this issue. For now I will close and add it to the "Enhancements and features" project to be picked up eventually.
