### ISSUE TITLE
SMWCon Fall 2019 notes

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4173]
Issue to collect things to mention and materials for the SMWCon Fall 2019 yearly SMW overview talk.

**Comment by kghbln** [comment]
* SWM 3.1.0 release and features
* New SAR extension

**Comment by krabina** [comment]
Updated [Semantic Tasks](https://github.com/SemanticMediaWiki/SemanticTasks) extension.

**Comment by JeroenDeDauw** [comment]
@mwjames any input?

**Comment by mwjames** [comment]
> @mwjames any input?

A couple of quick notes:

- Q/A: I'd like to see that a lightning talk is taking place to highlight the difference between SQLStore, SPARQLStore, and ElasticStore including its limitations, target user group, and installation easiness and a reason why we provide three different kinds of stores
- Q/A: I'd like to see more active (means vivid) reports and responses from institutional and enterprise users especially those where there is an installed base of more than 5Mio triples 
- Q/A: I'd like to see some discussions around how to use/install Semantic MediaWiki and Wikibase together in one instance as it is the case for https://nimiarkisto.fi/
- Q/A: Why is the installed base dropping (see https://sandbox.semantic-mediawiki.org/wiki/Semantic_MediaWiki_Usage)? Is it due some missing or insufficient data, other reasons?
- Federation queries (external query sources) and how it is done or can be done, or what is expected (see ...), use cases
- The "snapshot" discussion from the mailing-l sparked my interest, so gathering some feedback on that, as from a technical side we may be able to "take" a snapshot be freezing the output of the `QueryResult` as serialized JSON object and revive the result from the snapshot serialization format to show a specific version of a result output independent of any selected result printer, format, or HTML output
- The "prefetch mode" for fetching a `QueryResult` in bulk should save a couple of (~100++++ ) SELECT statements (depending on the size/limit and the total of requested printouts) per query and execution

Surely there is more but I'm a bit preoccupied right now, so as soon as additional questions/comments arise, I'll extend the list.

**Comment by kghbln** [comment]
> Q/A: Why is the installed base dropping (see https://sandbox.semantic-mediawiki.org/wiki/Semantic_MediaWiki_Usage)? Is it due some missing or insufficient data, other reasons?

Not really an issue to be discussed intensely I believe: See https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/65

**Comment by kghbln** [comment]
Link to [presentation](https://www.semantic-mediawiki.org/wiki/File:20190922_SMWConFall2019_SemanticMediaWiki_CurrentStatus.pdf)
