### ISSUE TITLE
Introducing the concept of `sequence map` for annotation values

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4226]
In general, stored values are idempotent and have no particular retrieval order (i.e. meaning the order of values retrieved from a back-end is not guaranteed to be in the order as to the point there were stored) unless a particular order attribute is declared and even then it would retrieve values in a lexicographical order (or if given in a random order).

## Issue

Sometimes we want to retrieve values of a property (e.g. `Has author` etc.) in the order they appeared during the input, yet as outlined above, a DB back-end doesn't guarantees such order when stored as list of values.

## Solution

SMW 3.1 will introduce the concept of an "sequence map" where a new auxiliary table with a blob field holds information about the encoded position or sequence (i.e. input order) of annotated values for properties that enabled this option.

The "sequence map" will follow FIFO meaning that the first appearance of the value in a list will define its position even though the same value has been annotated in different positions.

To recall, duplicate values are not stored in SMW therefore declaring something like  `[[Has number::42]] [[Has number::1]] [[Has number::42]]` only leads to `[[Has number::42]]` and `[[Has number::1]]` as representation with duplicate values being discarded.

With that in mind, an input with something like:
- `[[Has number::42]] [[Has number::1]] [[Has number::42]] [[Has number::1001]]` will produce a map that matches to
- `[[Has number::42]] [[Has number::1]] [[Has number::1001]]`

### Example

![image](https://user-images.githubusercontent.com/1245473/62829286-c3e74b00-bbe9-11e9-9514-ba5df35f45c1.png)

## Use case(s)

- `Has authors` containing a list of authors and reflect its position as that of the source ("If there is more than one author, arrange them in the same order as found in the source." see https://library.shsu.edu/research/guides/handouts/APA_Citation_Basics.pdf)

## Technical notes

- A new table `smw_object_aux` is introduced to hold auxiliary information about a subject
- The field `smw_seqmap` will contain the sequence mapping for all properties of a particular subject that have the `sequence_map` option enabled for a property
- The sequence map consists of md5 hash values of the annotation values together with its associated position in a list (aka. array)
- By default, no sequence map is stored for any property unless there is a profile schema assigned to it
- Any property that wants to make use of the sequence mapping has to assign a `[[Profile schema::...]]` to its declaration with a schema being defined as something like:

```
{
    "type": "PROPERTY_PROFILE_SCHEMA",
    "profile": {
        "sequence_map": true
    },
    "tags": [
        "property profile"
    ]
}
```

**Comment by jaideraf** [comment]
Awesome! :1st_place_medal: 
As you pointed out, in bibliographic description (e.g. traditional library cataloguing rules) the rule "_If there is more than one _value_, record them in the same order as found in the source_" is very important, so this feature is very nice.

Just an addendum: In RDF, this is expressed as `rdf:Seq` container. [0][1]
(this is not a request, it is just for future reference)

[0] https://www.w3.org/TR/rdf-schema/#ch_seq
[1] https://www.w3schools.com/xml/xml_rdf.asp (RDF Containers section)

**Comment by kghbln** [comment]
To be documented [here](https://www.semantic-mediawiki.org/w/index.php?title=Help:Sequence_map&action=edit&redlink=1)

**Comment by mwjames** [comment]
- https://sandbox.semantic-mediawiki.org/wiki/smw/schema:Profile:Sequence
- https://sandbox.semantic-mediawiki.org/wiki/Attribut:Has_author

**Comment by mwjames** [comment]
> To be documented here

Added some preliminary notes to [0].

[0] https://www.semantic-mediawiki.org/wiki/Help:Sequence_map
