### ISSUE TITLE
Ask output with table format has missing <tr> for header row

### ISSUE THREAD

**Issue by nischayn22** [SemanticMediaWiki/SemanticMediaWiki#4232]
### Setup and configuration

- SMW version: 2.5.8
- MW version: 1.29
- PHP version: NA
- DB system (MySQL, Blazegraph, etc.) and version: NA

### Issue
When trying to pro-grammatically generate HTML for a wiki page containing a smw ask query with table format the resulting HTML for the table has th elements without a surrounding tr element.

### Steps to reproduce
Sample code I used to generate the HTML:

```
$titleObj = Title::newFromText( $wikipage );
$pageObj = new WikiPage( $titleObj );
$content = $pageObj->getContent( Revision::RAW );
$wikitext = $content->getNativeData()
$content = new WikitextContent( $wikitext );
$parser_output = $content->getParserOutput( $titleObj, null, $popts );

```

On further debugging I found that the function doConcatenatedHeader() in HtmlTableRenderer doesn't add tr elements before returning the header. Here's the exact line:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/cb928a5b475e0fe7943ddb7789eb3f6947ed8f0e/src/MediaWiki/Renderer/HtmlTableRenderer.php#L224

**Comment by JeroenDeDauw** [comment]
Thanks for the report. Added the tag in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4233

**Comment by mwjames** [comment]
> $wikitext = $content->getNativeData()
$content = new WikitextContent( $wikitext );
$parser_output = $content->getParserOutput( $titleObj, null, $popts );

Accessing content without a parser my result in some inconsistency but given that the output is tidied as seen in [0] and [1] doesn't show any violations or contractions in particular of a missing tr element, I'm seeing this as a rather low hanging fruit (== meaning I won't get involved). Fixing should happen in two places and tests should be adapted including unit and integration tests.

[0] https://sandbox.semantic-mediawiki.org/wiki/Main_Page  
[1] https://validator.w3.org/nu/?doc=https%3A%2F%2Fsandbox.semantic-mediawiki.org%2Fwiki%2FMain_Page

![image](https://user-images.githubusercontent.com/1245473/63206048-4a45d600-c09d-11e9-99e0-1f9d9f529715.png)
