### ISSUE TITLE
Why caching matters?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4245]
Recently, I came across a page where an extension suggests to disable the parser cache [0] which is not the first time but it strengthen my position to reiterate that disabling the parser cache for a production environment is not recommended and should be avoided at any cost. There are plenty of reasons why disabling is a bad idea with the most important one being the cost of re-parsing a page on every view for a disabled cache.

Aside the MW parser cache, Semantic MediaWiki comes with a couple of internal caching [1] to ensure that data requests can make use of that cache to avoid unnecessary DB queries.

Without question, the biggest consumer of query time will be by far the SQLStore `QueryEngine` and we provide two different strategies to minimize the impact on a production environment.
- The first being to define queries as `Concepts` and run the static caching script [2] to prefetch the results that match the concept query.
- The other approach is to enable the "dynamic" `QueryCache` [3] to cache each embedded query. It is recommended to use the `QueryCache` in tandem with the `QueryDependencyLinksStore` [4] to detect changes to queries (and dependent results) that are part of other pages (including their annotations) to dynamically disable the parser cache for a specific request so that new results can be fetched (by allowing MW to re-parse the page hereby executing embedded #ask queries) and evict any previous query cache items associate with the executed query. Furthermore, the `QueryCache` is a shared cache meaning that a query and its results is being reused in another pages if the query signature is the same hereby providing additional savings on computational requirements.

### Example of an enabled query cache

The statistics only represent a ~ 20h time window [5] but it should be obvious that retrieving data from cache `"cached": 0.0003483271019992302,` is surely faster than without `  "uncached": 0.013891713631560814` and besides the fact that those cached queries aren't making a SELECT for the 16228 #ask requests.

```json
{
    "misses": {
        "embedded": {
            "AskParserFunction": 805
        },
        "nonEmbedded": {
            "SpecialAsk": 301,
            "Undefined": 1737,
            "AskParserFunction": 43,
            "API": 14,
            "SCI": {
                "CitationResourceMatchFinder": 16,
                "ReferenceBacklinksLookup": 1
            }
        }
    },
    "hits": {
        "embedded": {
            "AskParserFunction": 16228
        },
        "nonEmbedded": {
            "SpecialAsk": 451,
            "Undefined": 551,
            "AskParserFunction": 104,
            "API": 1
        },
        "tempCache": {
            "embedded": 158,
            "nonEmbedded": 8
        }
    },
    "deletes": [],
    "noCache": {
        "byLimit": {
            "AskParserFunction": 1144
        },
        "byOption": {
            "0": 4,
            "SIL": {
                "InterlanguageLinksLookup": 4
            }
        }
    },
    "medianRetrievalResponseTime": {
        "cached": 0.0003483271019992302,
        "uncached": 0.013891713631560814
    },
    "ratio": {
        "hit": 0.8571,
        "miss": 0.1429
    },
    "meta": {
        "version": "1",
        "cacheLifetime": {
            "embedded": 604800,
            "nonEmbedded": 600
        },
        "collectionDate": {
            "start": "2019-08-16 21:28:23",
            "update": "2019-08-17 16:53:25"
        }
    }
}
```

[0] https://semorg.oteloegen.at/wiki/Installation
[1] https://www.semantic-mediawiki.org/wiki/Help:$smwgMainCacheType
[2] https://www.semantic-mediawiki.org/wiki/Help:Concepts#Caching_concepts
[3] https://www.semantic-mediawiki.org/wiki/Help:Query_cache
[4] https://www.semantic-mediawiki.org/wiki/Help:Embedded_query_update
[5] https://www.semantic-mediawiki.org/w/index.php?title=Special:SemanticMediaWiki&action=stats%2Fcache
[1] https://www.semantic-mediawiki.org/wiki/Speeding_up_Semantic_MediaWiki

**Comment by krabina** [comment]
I usually disable any caching on my wikis, because many of them are very small. My strategy is to care about caching only when performance problems arise. So I need to rethink this, I guess...

**Comment by mwjames** [comment]
> My strategy is to care about caching only when performance problems arise. So I need to rethink this, I guess...

In the end the user has to decide what s(he) can manage and weigh the cost of performance against a cache vs. non-cache strategy.

As I said, generally it is recommended to enable caching and if you unsure you always can go with `CACHE_ANTHING` [0]  or `CACHE_DB` which provides the simplest of all solutions. `CACHE_DB` uses the same DB backend meaning it has a diminishing effect on performance when it needs to store and retrieve cache items from a blob table that is coupled to the same DB but it still let you enjoy caching without no apparent administrative overhead.

The recommendation is to use `redis` as a cache backend [0] as it provides performance, is simple to install and manage where it allows to store large cache items without a specific size limit (as far as I remember memcached on the other hand has a limit) and is separate from the actual DB cluster hereby avoiding SELECT requests to/from the DB you would otherwise need in case you choose `CACHE_DB`.

As for statistics, the `QueryCache` statistics was added to provide more insights to help argue for or against an active caching since it is hard to make any argument without some facts at hand.

So, if you think, your wikis are too small while the administrative overhead would be unjustifiable then of course you as a user are in the best position to judge and weigh in on what is required and what not.

[0] https://www.mediawiki.org/wiki/Manual:$wgMainCacheType
[1] https://www.semantic-mediawiki.org/wiki/Help:Caching

**Comment by kghbln** [comment]
Form my point of view "Redis" provides two important features "Memcached" does not:
- Increased security due to password protection
- Less load on the main data store since it allows to hold job queue items

Redis as such is slightly more difficult or time consuming to set up because:
- You actually have to configure Redis and set a maximum cache to prevent it from hitting the servers maximum cache which may result in server failure
- You  need to configure it as a caching provider for MediaWiki

I believe there are still a couple of MediaWiki features that depend on Memcached for best performance. However in the end I now very much prefer Redis over Memcached due to the two advantages noted above.

**Comment by kghbln** [comment]
Linked form [this page](https://www.semantic-mediawiki.org/wiki/Help:Caching) which a lot of references from other pages. Thus closing.
