### ISSUE TITLE
Record Datatype in 3.0.2 doesn't work with 'allows value'

### ISSUE THREAD

**Issue by heinrich-k** [SemanticMediaWiki/SemanticMediaWiki#4255]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.33.0
- PHP version: 7.3.8
- DB system (MySQL, Blazegraph, etc.) and version: mysql 5.7.27-0ubuntu0.16.04.1-log

Former setup:
- SMW version: 2.5.5
- MW version: 1.29.2
- PHP version : 7.0.33-0ubuntu0.16.04.6
- DB system (MySQL, Blazegraph, etc.) and version: mysql 5.7.27-0ubuntu0.16.04.1-log

### Issue
I use thee properties. One is type page, one is type number and one is a record, consisting of the former too.
All three properties have 'allows value' set, to limit the possible entried.
This worked fine in SMW 2.5.5
In SMW 3.0.2 every page that want's to set the Record property produces an error, stating that the value wasn't allowed via 'allows value', despite it being allowed.

The error message in question also showes a space between the ; that seperates the values and the 2nd value, despite there being none in the article.

### Stack trace
Not relevant, I guess.

### Steps to reproduce
The page 'Example Rang Record' on https://sandbox.semantic-mediawiki.org showed the behavior too, until I checked again today. So maybe the error is fixed there already...

**Comment by kghbln** [comment]
Thanks a lot for reporting. Luckily this was already fixed this weekend with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4242.
