### ISSUE TITLE
FormsBuilder.php producing a PHP Warning

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#4283]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.31.0
- PHP version: 7.1.31
- MySQL version: 5.6.44-86.0

### Issue
Using this [search profile form definition](https://wikincat.org/wiki/smw/schema:Search-profile-form-definition) the following appears on [Special:Search](https://wikincat.org/w/index.php?title=Especial:Busca&profile=smw&search=&fulltext=1):

**Warning**:  is_array() expects exactly 1 parameter, 0 given in **/w/extensions/SemanticMediaWiki/src/MediaWiki/Search/Form/FormsBuilder.php** on line **249**

(I am still learning search profiles, I don't know what is wrong).

**Comment by mwjames** [comment]
> Warning: is_array() expects exactly 1 parameter, 0 given in /w/extensions/SemanticMediaWiki/src/MediaWiki/Search/Form/FormsBuilder.php on line 249

Okay, if look at the code above we'll see something like:

```
		if ( isset( $data['namespaces']['hidden'] ) && is_array(  ) ) {
			$this->hidden_namespaces( $data['namespaces']['hidden'] );
		}
```

Now, `&& is_array(  )` should actually be `&& is_array( $data['namespaces']['hidden'] )`, so during some copy and pasting the inner part went missing and is the reason for the " is_array() expects exactly 1 parameter" message.

**Comment by mwjames** [comment]
> (I am still learning search profiles, I don't know what is wrong).

As for the "don't know what is wrong", the code is wrong not your schema. On the matter of "I am still learning", if something is unclear on the provide wiki page or [0] docu then just create a new ticket or make suggestions on how to improve the documentation (and examples) and make it more user friendly.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/src/MediaWiki/Search

**Comment by jaideraf** [comment]
Thanks @mwjames. Shoud I make a PR with this change or are you going to make it?

**Comment by kghbln** [comment]
> Shoud I make a PR with this change or are you going to make it?

You could have been bold here. ;) Just made #4285 Anyways it will indeed be much appreciated if you could have a peep at the docu.

**Comment by jaideraf** [comment]
> Anyways it will indeed be much appreciated if you could have a peep at the docu.

[Ok, here it is](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASchema%2FType%2FSEARCH_FORM_SCHEMA&type=revision&diff=71293&oldid=68735).

**Comment by kghbln** [comment]
> Ok, here it is.

Thanks a lot! Did some minor fluff and published.
