### ISSUE TITLE
Changes made to $wgCanonicalNamespaceNames in MediaWiki 1.34

### ISSUE THREAD

**Issue by dominic998** [SemanticMediaWiki/SemanticMediaWiki#4290]
### Setup and configuration
N/A

### Issue
A change has been made to `$wgCanonicalNamespaceNames` in MediaWiki core (see [T232004]( https://phabricator.wikimedia.org/T232004)).

We now explicitly set `$wgCanonicalNamespaceNames[NS_MAIN]`.

I believe this might affect [the union done here](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/NamespaceManager.php#L188), if the code assumes `$wgCanonicalNamespaceNames[NS_MAIN]` is not already set. Any value of the main namespace returned by `$instance->getCanonicalNames()` will be ignored.

This change will be in [1.34.wmf.22](https://www.mediawiki.org/wiki/MediaWiki_1.34/wmf.22)

Raising this bug here just so you are aware and can take the necessary actions.

### Stack trace
N/A

### Steps to reproduce
N/A

**Comment by kghbln** [comment]
Thanks for notifying.

**Comment by JeroenDeDauw** [comment]
Code now at https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/NamespaceManager.php#L206

**Comment by akuckartz** [comment]
What is left to be done here?

**Comment by JeroenDeDauw** [comment]
Figuring out if there actually is an issue and potentially fixing it

**Comment by jaideraf** [comment]
> Figuring out if there actually is an issue and potentially fixing it

Since we are working now on MW 1.39+ and no one else have noticed any issue relating to this one, I am closing this now.
