### ISSUE TITLE
Errors after change language

### ISSUE THREAD

**Issue by askurashev** [SemanticMediaWiki/SemanticMediaWiki#4292]
### Setup and configuration

MediaWiki 1.31.3
PHP 7.0.33-0+deb9u3 (apache2handler)
MariaDB 10.1.41-MariaDB-0+deb9u1
Semantic MediaWiki  3.0.2

I run mediawiki a site in Russian and all my code expressions work correctly. When I change the language to another (from Russian to English, for example), an error appears: Expression error: unidentified punctuation character “,”.

For example, an error in place of the code:
```
{{#expr: 100 - (100 * {{#ask: [[Категория:Авторы]] [[APublicationsCount::>{{#show: {{PAGENAME}} |?APublicationsCount}}]] |format=count}} / {{#show:Константы|?CAuthorsCount}}) round 2}}
```
```
{{#set:APublicationsCount={{#ask: [[Категория:Публикации]] [[PAuthors::{{PAGENAME}}]] |format=count }}}}
```

**Comment by JeroenDeDauw** [comment]
Why closed?

**Comment by askurashev** [comment]
I figured out what the problem was.
It arises due to the fact that in English and Russian, a different separator is used for decimal numbers (dot and comma).
But another question arose, on which I am still looking for an answer. What numbers can the Number property take? If you use a Russian number with a dot, then it takes it, and if a number with a comma, then it gives an error.
This error occurs only with me, or I don’t know something about which numbers can be assigned to the Number property.

**Comment by jaideraf** [comment]
@askurashev have a look at the following pages, one of those may help you.

https://www.semantic-mediawiki.org/wiki/Help:Type_Number#In_other_languages
https://www.semantic-mediawiki.org/wiki/Help:Display_precision
https://www.semantic-mediawiki.org/wiki/Localization_and_multilingual_content#Multilingual_content
https://www.mediawiki.org/wiki/Extension:NumberFormat

**Comment by askurashev** [comment]
Dark forest with numbers.
Wikipedia does not have the ability to bring any number to a single form. You can change using magic words, but only on condition that you know the format of the original number. And when you change the language, this format of original number changes!!!
A lot of problems arise when changing the interface language.
Is it possible to completely prohibit the separator of digits in numbers? That it was not in English, nor in Russian.

**Comment by jaideraf** [comment]
@askurashev In calculations, try to use the plain (unformatted) printouts [0]

> For numerical properties like the population number, the plain format is a simple number string without commas to separate digits.

That means, add `#` after your property, in the printout area of your queries. 

`?YourNumberProperty#`

After the calculation is done, if you want so, you aplly the formating with other parser functions/extensions/templates.

[0] https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#Plain_.28unformatted.29_printouts

**Comment by askurashev** [comment]
`{{#show: {{PAGENAME}} |?AFirstPubYear}} // 2005, for example`

Results in Russian language: 2005
Result in English language: 2,005

`{{#show: {{PAGENAME}} |?AFirstPubYear#}} // 2005, for example`

I get the same results.
