### ISSUE TITLE
Uniqueness constraint is confused by redirects

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4314]
Can be seen on https://www.semantic-mediawiki.org/wiki/Demo:Berlin

![image](https://user-images.githubusercontent.com/146040/65646872-d7653e80-dffc-11e9-8e28-cc7ac5cdd21a.png)

Redirecting page: https://www.semantic-mediawiki.org/w/index.php?title=Berlin&redirect=no

**Comment by kghbln** [comment]
This page contains a duplicate annotation to demo uniqueness constraints. The message tells me that it already contains an assigned value which is correct and it tells me that the second assigned value is violation uniqueness, since it is the number for London.

```
* NDL ID: [[NDL ID::00629494]] <code>00629494</code> is not possible because it is assigned to [[Demo:London|London]] → [[NDL ID::00629194]] is the correct identifier
```

**Comment by JeroenDeDauw** [comment]
A I got confused by the display of the error message. Reading it again now it is so hard to understand that I feel I still don't.

**Comment by kghbln** [comment]
The main issue may be the error note and the two explanatory items are displayed as one bulleted item.
