### ISSUE TITLE
Numbers separators error

### ISSUE THREAD

**Issue by askurashev** [SemanticMediaWiki/SemanticMediaWiki#4321]
MediaWiki 1.31.3
PHP 7.2 (apache2handler)
MariaDB 10.1.41-MariaDB-0+deb9u1
Semantic MediaWiki 3.0.2

Hello.
Steps:
1. I change in MessagesEn.php `$separatorTransformTable = null;` to `$separatorTransformTable = [ ',' => "\u{00A0}", '.' => ',' ];`. Now MessagesRu.php and MessagesEn.php by this parameter is equal.
2. I run update.php and purge the cache.
3. Now, `{{#expr: 2000 - 1}}` i get 1999, both in russian and english language.
4. But, if I get same number from property, I get 1,999  (with comma thousands separator) in english language and 1999 in russian language.

Does the SMW take the decimal separator settings and thousands separators not from Mediawiki parameters?

P.S. I know about `#LOCL@ru`, but is more code, and all should work good without this construction.

**Comment by JeroenDeDauw** [comment]
See https://www.semantic-mediawiki.org/wiki/Help:Type_Number#In_other_languages

**Comment by JeroenDeDauw** [comment]
There have been many changes since 3.0.2, so you can always try upgrading to 3.1 if you think you ran into some kind of bug.

**Comment by askurashev** [comment]
> See https://www.semantic-mediawiki.org/wiki/Help:Type_Number#In_other_languages

> In recent versions of SMW, both the decimal separator and the thousands separators are determined by the wiki language using MediaWikis i18n system. So you cannot change the symbols used yourself.

If I determine separator in Mediawiki, why smw shows not as prescribed in the configuration of Mediawiki?

**Comment by askurashev** [comment]
> There have been many changes since 3.0.2, so you can always try upgrading to 3.1 if you think you ran into some kind of bug.

I have very big semantic data in my wiki, upgrade version is very slow.

**Comment by askurashev** [comment]
I know how resolve this problem - double use formatnum or #LOCL, but I want use very trouth decision.

**Comment by JeroenDeDauw** [comment]
Unfortunately I do not know what changes where made to the number formatting in recent history. Ping @mwjames @kghbln

**Comment by jaideraf** [comment]
I don't think this issue will get further responses, so I am closing it now. If anyone is interested in the subject, fell free to reopen.
