### ISSUE TITLE
`SMWSearch` breaks namespace search previews

### ISSUE THREAD

**Issue by MPThLee** [SemanticMediaWiki/SemanticMediaWiki#4342]
### Setup and configuration

- SMW version: 3.1.0
- MW version: 1.33.1
- PHP version: 7.3.11
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB v15.1, ElasticSearch v6.8.4, Redis v5.0.6

### Issue
I'm just trying to search on wiki-project page. 
but after sets 'SMWSearch', It doesn't show up in previews(don't know actual name. see Step to reproduce) until add a character of page after namespace. (eg. `Mediawiki:G`)
I don't know if this is intended, but it seems to be a bug.

### Steps to reproduce
Typing `Mediawiki:` on searchbox.

Default and CirrussSearch Setting:
![normal_and_cirrussearch](https://user-images.githubusercontent.com/26970092/67617535-8c913f00-f7d3-11e9-9903-12a9600c85eb.png)

Set to `SMWSearch`:
![smwsearch](https://user-images.githubusercontent.com/26970092/67617518-68cdf900-f7d3-11e9-967d-eba96d91d898.png)

**Comment by kghbln** [comment]
@mwjames This could probably be back-ported?

**Comment by mwjames** [comment]
> @mwjames This could probably be back-ported?

Should be fine given that there are only minimal changes to the class signature.
