### ISSUE TITLE
Erroneous test failures based on equality support setting from LocalSettings.php

### ISSUE THREAD

**Issue by larsjuergenson** [SemanticMediaWiki/SemanticMediaWiki#4343]
### Setup and configuration

- SMW version: 3.2.0-alpha (e5b8377)
- MW version: 1.33.1
- PHP version: 7.1.23
- DB system and version: MySQL 8.0.17

### Issue
If the `LocalSettings.php` of the MW installation used to run the tests specifies `$smwgQEqualitySupport = SMW_EQ_NONE;`, several tests fail erroneously.

### Output
Below is the (pared down) list of test failures.
- Failure 3 should be ignored, it is an independent issue.
- Failure 6 Is a php integration test.
- The other four failures are JSONScript tests pertaining to redirects.

```
There were 6 failures:

1) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "p-0405.json"
Failed asserting count for incoming `propertyKeys` on #0 verify redirect for unknown target"
Failed asserting that actual size 0 matches expected size 1.

2) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "p-0407.json" 
Unmatched values in #0 check annotation for a deleted redirected target subject for:
{
    "@unresolved": [
        "Example/0407/2"
    ],
    "@valueHint": [
        "Example/0407/1",
        "2019-10-27T08:00:29",
        "Example/0407/3"
    ],
    "HasPropertyForUse": "Example/0407/1#0##",
    "_MDAT": "1/2019/10/27/8/0/29/0",
    "_SKEY": "Example/0407/3"
}
Failed asserting that an array is empty.

3) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "p-1006.json" 
Failed "#0 (verify item list order)" for StringContains:
==== (actual) ====
...
==== (expected) ====
[ <div class="smw-table-cell smwpropname" data-list-index="5"><a href=.*Example/P1006/4" title="Example/P1006/4">CC</a> ]

Failed asserting that 9 matches expected 10.

4) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "q-0402.json" 
Failed asserting query result count on #4 distinct value for Has author / redirected value / subproperty level zero
Failed asserting that 0 matches expected 1.

5) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "q-0604.json" 
Failed on on #0 any value query for redirected property to match datavalues [ PageRedirectTarget#0## ] against the expected results.
Failed asserting that an array is empty.

6) SMW\Tests\Integration\MediaWiki\RedirectTargetFinderIntegrationTest::testDeepRedirectTargetResolverToFindTarget
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'DeepRedirectTargetResolverToFindTarget/3'
+'DeepRedirectTargetResolverToFindTarget/1'
```

### Possible fixes

For the JSONScript tests, there are two ways to fix this (probably BOTH should be implemented):

1. Make sure the testing environment for the JSONScript-Tests sets `$smwgQEqualitySupport` to its default value.
2. Make sure that tests that rely on a particular setting of `$smwgQEqualitySupport` specify this as a `setting`. (For this, the variable must be made `settable` first.)

I tried to see if there is a simple way to do (1.) by adding to the array in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/LightweightJsonTestCaseScriptRunner.php#L75 , but that fixed only some of the failures. I am afraid someone with more knowledge of the JSONScript test runners needs to take a look at this.

**Comment by JeroenDeDauw** [comment]
Thanks for the detailed issue report @larsjuergenson!

**Comment by mwjames** [comment]
> $smwgQEqualitySupport = SMW_EQ_NONE;, several tests fail erroneously.

Access to `smwgQEqualitySupport` has been isolated in #4556 to avoid interference with tests and possible different settings added in `LocalSettings.php`.
