### ISSUE TITLE
refreshLinks.php RuntimeExcception in TransactionHandler.php: Trying to begin a new section transaction while SMW\SQLStore\SQLStoreUpdater::doDataUpdate is still active

### ISSUE THREAD

**Issue by Wikinaut** [SemanticMediaWiki/SemanticMediaWiki#4350]
RuntimeException from line 123 of extensions/SemanticMediaWiki/src/MediaWiki/Connection/TransactionHandler.php:

Trying to begin a new section transaction while SMW\SQLStore\SQLStoreUpdater::doDataUpdate is still active!

### Setup and configuration

- SMW version: 3.1.0
- MW version: 1.31.3
- PHP version: 7.2.23
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.27-log

### Issue

see title

### Stack trace

http://dpaste.com/2S1FXNP.txt

**Comment by JeroenDeDauw** [comment]
Thanks for reporting. This was fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4333, though we have yet to release this. Keep an eye out for SMW 3.1.1, which will hopefully be released soon.

**Comment by Wikinaut** [comment]
Cool! Very important for the CCC Congresswiki. How can I quicly fix it?

**Comment by JeroenDeDauw** [comment]
Quickest way to fix is to run master. We've not made many changes since 3.1.0 besides fixes. One thing to watch out for is that we dropped support for PHP 7.0.x, though presumably you are running something more recent anyway.

**Comment by JeroenDeDauw** [comment]
Yeah [you're running PHP 7.2](https://events.ccc.de/congress/2019/wiki/index.php/Special:Version), so master should be fine.

I created an issue to get SMW 3.1.1 going: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4351

**Comment by Wikinaut** [comment]
Nice & bedankt for your swift response. I will follow your recommendation and report back here. 


> Quickest way to fix is to run master. We've not made many changes since 3.1.0 besides fixes. One thing to watch out for is that we dropped support for PHP 7.0.x, though presumably you are running something more recent anyway.

I am a little bit reluctant (because I am not experienced) with respect to changing our current
composer.local.json file (see below).

What are the exact steps to go away from the current release SM versions to github master? I think this could break something.

```
{
	"require": {
		  "mediawiki/maps": "^6.3",
                  "mediawiki/semantic-media-wiki": "~3.0",
		  "mediawiki/parser-hooks": "*",
		  "zordius/lightncandy": "*",
		  "mediawiki/semantic-result-formats": "^3.1",
		  "mediawiki/page-forms": "^4.6"
        }
}
```

**Comment by kghbln** [comment]
Since the fix was already back-ported last week in preparation you can do this to get master of the 3.1.0 branch: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4323#issuecomment-549836527

**Comment by JeroenDeDauw** [comment]
You can put

    "mediawiki/semantic-media-wiki": "dev-master",

to get master.

Putting `3.1.x@dev` as per Karstens comment probably gets you the 3.1.x branch... though I'm not 100% sure since the MediaWiki composer setup is doing some special things. `3.1.x-dev` is a safer bet. You can just try and see what happens or run Composer with the `--dry-run` flag.

You do not need `mediawiki/parser-hooks` in your composer.local.json. This thing does not provide functionality on its own and is automatically pulled in by extensions that need it. (Having it in there does not cause real harm either)

You have the Maps extension installed but not loaded. Is that on purpose? Clearly you want people to be able to add maps (I might be slightly biased here).

**Comment by kghbln** [comment]
> probably gets you the 3.1.x branch the 3.1.x branch

I guess this is what he wants to do since SMW 3.1.0 is running on their machine. Anyhow there are many ways to move forward here.

**Comment by Wikinaut** [comment]
Problem solved! Thanks.
After having changed the composer.local.json as indicated by @JeroenDeDauw and running ```sudo -u www composer update```, I had to run php update.php. 100% okay now.
