### ISSUE TITLE
"show" parser function has stopped following redirects

### ISSUE THREAD

**Issue by FO-nTTaX** [SemanticMediaWiki/SemanticMediaWiki#4370]
### Setup and configuration

- SMW version: 3.2.0-alpha (6314502)
- MW version: 1.34.0-rc.1 (0a6ce0b)
- PHP version: 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.43-MariaDB-0ubuntu0.18.04.1

### Issue
When using the `{{#show:}}` Parser Function, the function used to follow redirects when gathering data up to at least version 3.0.1, in the more recent versions (tested on at least 3.1.1 and 3.2.0-alpha) it seems to not follow redirects anymore though

### Steps to reproduce
I have recreated the bug in its most simple way on the Sandbox wiki, I hope this helps:
https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:FOnTTaX/Bug1/SMW_Show_With_Default

**Comment by mwjames** [comment]
> When using the `{{#show:}}` Parser Function, the function used to follow
> redirects when gathering data up to at least version 3.0.1, in the more
> recent versions (tested on at least 3.1.1 and 3.2.0-alpha) it seems to not
> follow redirects anymore though

I know what causes the issue but cannot commit to any time before the
holidays, so this has to wait until next year.

**Comment by FO-nTTaX** [comment]
No problem, have a nice holiday season :)
