### ISSUE TITLE
Special:ExpandTemplates with Internal error when #ask is present

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#4374]
### Setup and configuration

- SMW version: 3.1.1
- MW version: 1.31.5 
- PHP version: 7.2.24
- MariaDB version: 10.1.43

### Issue
When running a query like this one in the [ExpandTemplates](https://www.semantic-mediawiki.org/wiki/Special:ExpandTemplates) special page an issue appears.
```
{{#ask:
 [[Category:City]]
 |?Located in=Country
 |?Average rainy days
 |sort=Located in,Average rainy days
 |order=asc,desc
}}
```
I remembered [this setting](https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledSpecialPage) and tried, but it did not solve the problem (not sure if it is related to the problem or if it is the correct value):

```php
$smwgEnabledSpecialPage = array(
        'Ask',
        'RunQuery',
        'ExpandTemplates'
);
```

### Stack trace
```
[2289a0d6c07dd281bb93aa1e] /wiki/Special:ExpandTemplates TypeError from line 46 of /var/www/html/wwwsmw/w/extensions/SemanticMediaWiki/includes/formatters/MessageFormatter.php: Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance of Language, instance of StubUserLang given, called in /var/www/html/wwwsmw/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php on line 133

Backtrace:

#0 /var/www/html/wwwsmw/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(133): SMW\MessageFormatter->__construct(StubUserLang)
#1 /var/www/html/wwwsmw/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(395): SMW\ParserFunctionFactory->newAskParserFunction(Parser)
#2 /var/www/html/wwwsmw/w/includes/parser/Parser.php(3426): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string)
#3 /var/www/html/wwwsmw/w/includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#4 /var/www/html/wwwsmw/w/includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#5 /var/www/html/wwwsmw/w/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#6 /var/www/html/wwwsmw/w/includes/parser/Parser.php(701): Parser->replaceVariables(string, PPFrame_DOM)
#7 /var/www/html/wwwsmw/w/includes/StubObject.php(112): Parser->preprocess(string, Title, ParserOptions)
#8 /var/www/html/wwwsmw/w/includes/StubObject.php(138): StubObject->_call(string, array)
#9 /var/www/html/wwwsmw/w/includes/specials/SpecialExpandTemplates.php(91): StubObject->__call(string, array)
#10 /var/www/html/wwwsmw/w/includes/specialpage/SpecialPage.php(565): SpecialExpandTemplates->execute(NULL)
#11 /var/www/html/wwwsmw/w/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#12 /var/www/html/wwwsmw/w/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#13 /var/www/html/wwwsmw/w/includes/MediaWiki.php(861): MediaWiki->performRequest()
#14 /var/www/html/wwwsmw/w/includes/MediaWiki.php(524): MediaWiki->main()
#15 /var/www/html/wwwsmw/w/index.php(42): MediaWiki->run()
#16 {main}
```

### Steps to reproduce
Query something like the above query in the [Special:ExpandTemplates](https://www.semantic-mediawiki.org/wiki/Special:ExpandTemplates) page.

**Comment by mwjames** [comment]
> /var/www/html/wwwsmw/w/extensions/SemanticMediaWiki/includes/formatters/MessageFormatter.php:
> Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance
> of Language, instance of StubUserLang given, called in

[0] provides a history on "Language, instance of StubUserLang given"
so maybe some of those listed in [0] show a solution for the issue.

This isn't a particular SMW issue as evident by [0] and while a
solution needs to be implemented in SMW it is not caused by SMW.

[0] https://phabricator.wikimedia.org/search/query/UZmgTD34KcPI/#R

**Comment by kghbln** [comment]
> This isn't a particular SMW issue as evident by [0] and while a solution needs to be implemented in SMW it is not caused by SMW.

Reclassified to enhancement.

**Comment by mwjames** [comment]
>> This isn't a particular SMW issue as evident by [0] and while a solution
>> needs to be implemented in SMW it is not caused by SMW.
>
> Reclassified to enhancement.

I have a couple of changes I plan to do in 2020 but be advised that it
is unlikely for me to look at this issue any time soon.
