### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by acnetj** [SemanticMediaWiki/SemanticMediaWiki#4382]
### Setup and configuration

MediaWiki | 1.34.0
PHP | 7.4.1 (fpm-fcgi)
MySQL | 5.7.25-0ubuntu0.16.04.2
Semantic MediaWiki | 3.1.1

After upgrade I have to save the page twice in order for the edits to show up on query results. If I just save once after edit the query output is still old. Wasn't that way before upgrade.

**Comment by mwjames** [comment]
> MediaWiki | 1.34.0
> PHP | 7.4.1 (fpm-fcgi)

I don't remember that the compatibility matrix mentions anything about
supporting either MW 1.34+ or PHP 7.4+ which means users that deploy
the software on systems that aren't tested (meaning working outside of
the compatibility range) will unlikely be satisfied

There is a reason why there is a compatibility matrix and users should
not expect any support assistance for unsupported environments.

That said, adding MW 1.34 to the CI should be the next step, yet I'm
confident that it will break the SMW test suite and is likely hinting
to an issue that has been introduced with MW 1.34 given that no
fundamental changes have been merged to SMW in the last 4/5 months.

> After upgrade I have to save the page twice in order for the edits to show
> up on query results. If I just save once after edit the query output is
> still old. Wasn't that way before upgrade.

This description is too ambiguous (at least for me) which means I
cannot (and will not) respond to any such issues that don't provide a
clear explanation of how to replicate such issue especially now that
my volunteer time will become more restricted starting with 2020.

Cheers

**Comment by kghbln** [comment]
I have mixed experience and the result is probably dependent on the result format used. On [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Kghbln/Unknown_count) I have to add the subobject and purge twice to get it to show in the graph (MW 1.34, SMW 3.1, PHP 7.2). On another wiki (MW 1.31, SMW 3.1 and PHP 7.0) the results show immediately for the table format.

**Comment by kghbln** [comment]
Ok, I created some examples on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/4382) and the behavior is identical for both formats. 1. Add subobject to add data, 2. Purge once to get the results. For me this is kinda expected and I think the [`@deferred` query marker](https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/Deferred_query_marker) is meant at the way out here.

When it comes to my previous https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4382#issuecomment-571173550 the difference in the setup is MediaWiki and PHP however not SMW.

**Comment by kghbln** [comment]
Just saw that the `@deferred` query marker is probably only interacting with certain result printers.

**Comment by mwjames** [comment]
I suspect this to be fixed by #4470.
