### ISSUE TITLE
NameTableAccessException.php: Failed to access name from content_models using id = 2

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4386]
### Setup and configuration

- MediaWiki | 1.33.1 (39f8f34)20:51, 5 December 2019
- PHP | 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.43-MariaDB-0ubuntu0.18.04.1
- VisualEditor | 0.1.1 (6f1fd3d) 23:13, 30 November 2019
- Semantic MediaWiki | 3.1.1 (143488d) 10:11, 17 November 2019

### Issue
When running "update.php" or "setupStore.php" I get a failure if not using the `--skip-import` flag. I am not sure why this happens. 

### Stack trace
```
Importing from smw.groups.json ...
   ... replacing smw/schema:Group:Schema properties
       importer was last editor ...
[f4fc8747b73543c93b00e612] [no req]   MediaWiki\Storage\NameTableAccessException from line 42 of /../w/includes/Storage/NameTableAccessException.php: Failed to access name from content_models using id = 2
Backtrace:
#0 /../w/includes/Storage/NameTableStore.php(308): MediaWiki\Storage\NameTableAccessException::newFromDetails(string, string, integer)
#1 /../w/includes/Revision/RevisionStore.php(1633): MediaWiki\Storage\NameTableStore->getName(integer)
#2 /../w/includes/Revision/RevisionStore.php(1680): MediaWiki\Revision\RevisionStore->loadSlotRecords(string, integer)
#3 [internal function]: MediaWiki\Revision\RevisionStore->MediaWiki\Revision\{closure}()
#4 /../w/includes/Revision/RevisionSlots.php(165): call_user_func(Closure)
#5 /../w/includes/Revision/RevisionSlots.php(136): MediaWiki\Revision\RevisionSlots->getSlots()
#6 /../w/includes/Revision/RevisionRecord.php(219): MediaWiki\Revision\RevisionSlots->getSlotRoles()
#7 /../w/includes/Revision/MutableRevisionRecord.php(57): MediaWiki\Revision\RevisionRecord->getSlotRoles()
#8 /../w/includes/Storage/DerivedPageDataUpdater.php(773): MediaWiki\Revision\MutableRevisionRecord::newFromParentRevision(MediaWiki\Revision\RevisionStoreCacheRecord)
#9 /../w/includes/Storage/PageUpdater.php(694): MediaWiki\Storage\DerivedPageDataUpdater->prepareContent(User, MediaWiki\Storage\RevisionSlotsUpdate, boolean)
#10 /../w/includes/page/WikiPage.php(1915): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#11 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(124): WikiPage->doEditContent(SMW\MediaWiki\Content\SchemaContent, CommentStoreComment, integer)
#12 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(110): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent(WikiPage, Title, SMW\Importer\ImportContents)
#13 [internal function]: SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}(integer, Wikimedia\Rdbms\DatabaseMysqli)
#14 /../w/includes/libs/rdbms/database/Database.php(3588): call_user_func(Closure, integer, Wikimedia\Rdbms\DatabaseMysqli)
#15 /../w/includes/libs/rdbms/database/Database.php(3436): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks(integer)
#16 /../w/includes/libs/rdbms/database/DBConnRef.php(53): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle(Closure)
#17 /../w/includes/libs/rdbms/database/DBConnRef.php(572): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#18 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(764): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle(Closure)
#19 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(111): SMW\MediaWiki\Connection\Database->onTransactionIdle(Closure)
#20 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create(SMW\Importer\ImportContents)
#21 /../w/extensions/SemanticMediaWiki/src/Importer/Importer.php(133): SMW\Importer\ContentCreators\DispatchingContentCreator->create(SMW\Importer\ImportContents)
#22 /../w/extensions/SemanticMediaWiki/src/Importer/Importer.php(109): SMW\Importer\Importer->doImportContents(SMW\Importer\ImportContents)
#23 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1352): SMW\Importer\Importer->doImport()
#24 /../w/includes/Hooks.php(174): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete(SMW\SQLStore\TableBuilder\MySQLTableBuilder, Onoi\MessageReporter\ObservableMessageReporter, SMW\Options)
#25 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#26 /../w/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(191): Hooks::run(string, array)
#27 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(437): SMW\SQLStore\Installer->install(SMW\Options)
#28 /../w/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(326): SMW\SQLStore\SQLStore->setup(SMW\Options)
#29 /../w/extensions/SemanticMediaWiki/src/Store.php(506): SMW\Elastic\ElasticStore->setup(SMW\Options)
#30 /../w/includes/installer/DatabaseUpdater.php(489): SMW\Store::setupStore(boolean, SMW\Options)
#31 /../w/includes/installer/DatabaseUpdater.php(457): DatabaseUpdater->runUpdates(array, boolean)
#32 /../w/maintenance/update.php(203): DatabaseUpdater->doUpdates(array)
#33 /../w/maintenance/doMaintenance.php(96): UpdateMediaWiki->execute()
#34 /../w/maintenance/update.php(275): require_once(string)
#35 {main}
```

**Comment by mwjames** [comment]
> /../w/includes/Storage/NameTableAccessException.php: Failed to access name
> from content_

This isn't an issue with SMW but with MediaWiki and the
MultiContentRevision they have introduced.

Please search WMF phab [0] for similar reports, all I can say is that
this cannot be fixed by trying to hack something into SMW to mitigate
this due to shortcomings on the MCR handling.

PS: I have encountered to issue before on a test system of mine but
since I no longer have the luxury to review MW specific issues, I
scraped the test system all at once. I don't what is causing the issue
or how to fix it, all I know is that it appeared with MCR.

[0] https://phabricator.wikimedia.org/search/query/awFINaNdGBzC/#R

Cheers

**Comment by kghbln** [comment]
Thanks for the info. I had a feeling that MCR may be involved. Reported as [T241977](https://phabricator.wikimedia.org/T241977)

**Comment by jamesmontalvo3** [comment]
@kghbln are you saying `--skip-import` should work on `update.php`? I get `Unexpected option skip-import!`. `--skip-optimize` does work on `update.php`, and `--skip-import` does work on `setupStore.php`.

Without `--skip-import` for `update.php` I think I'm blocked from using `update.php` with newer versions of MW with SMW installed, right?

- MediaWiki | 1.34.1 (48c3e32)
- PHP | 7.2.31 (apache2handler)
- MariaDB | 5.5.65-MariaDB
- VisualEditor | 0.1.1 (74116a7)
- Semantic MediaWiki | 3.1.6

**Comment by kghbln** [comment]
I cannot remember any longer what I did. Since I also get the unexpected option note for "update.php" it is obviously only available to "setupStore.php". Thus I must obviously have moved forward via "setupStore.php".

Currently I am more worried about the MCR feature. My issue report was not even touched during the past half year. Either they abandoned development, have not clue how to go about it or whatever. WMF appears to be even more erratic as ever before. :(

**Comment by jamesmontalvo3** [comment]
I was able to get this working by running `setupStore.php` on new 1.34 wikis before running `update.php` (I generate new wikis by sourcing MW's `tables.sql` and running `update.php` rather than running the installer). Without doing `setupStore.php` first I got the error you have above. On preexisting wikis coming from MW 1.32 I just ran `update.php` as normal. 

So, perhaps me running into this issue was only due to the way I manage installs (with Meza). If that's the case then there doesn't seem to be an issue with MW or SMW, right?

**Comment by kghbln** [comment]
> I was able to get this working by running setupStore.php on new 1.34 wikis before running update.php

Probably this is how I did it too. Still cannot remember.

> So, perhaps me running into this issue was only due to the way I manage installs (with Meza). If that's the case then there doesn't seem to be an issue with MW or SMW, right?

Since I also ran into this issue there must be something in the water...

**Comment by jamesmontalvo3** [comment]
> Since I also ran into this issue there must be something in the water...

Fair point. If running setupStore.php at the correct time resolves the issue, is there not something within SMW that could be altered to prevent the error?
