### ISSUE TITLE
Datatype "Reference" not considering field specifications

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4424]
### Setup and configuration

- MediaWiki | 1.34.0 (ae6e0c0)15:53, 27 December 2019
- PHP | 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.43-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (7037afa) 03:14, 14 January 2020

### Issue
Datatype "Reference" is no longer considering field specifications. Since this is working on [mw.o](https://www.semantic-mediawiki.org/wiki/Property:Has_Wikidata_reference) and not on [sbx.mw.o](https://sandbox.semantic-mediawiki.org/wiki/Attribut:Has_population) I believe this is yet another MW 1.34 fatality.

**Comment by mwjames** [comment]
> Datatype "Reference" is no longer considering field specifications. Since this is working on mw.o and not on sbx.mw.o I believe this is yet another MW 1.34 fatality.

This shows the same symptoms as mentioned in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4394#issuecomment-573349345 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4382#issuecomment-570825763 where an "old" revision is used as base for the data assignment.

As per [0] the revision ID (in MediaWiki) is 46116 for the content displayed but my guess is that when you lookup the `smw_object_ids` table for the associated revision (see `smw_rev` field, [1]), the `Has population` entity would contain a different ID.

![image](https://user-images.githubusercontent.com/1245473/72667613-ada1ae80-3a15-11ea-9408-bc6e044b4f3c.png)

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=Attribut:Has_population&oldid=46116
[1] https://www.semantic-mediawiki.org/wiki/Help:Associated_revision

**Comment by mwjames** [comment]
I suspect this to be fixed by #4470.
