### ISSUE TITLE
Why is importing a vocabulary restricted to only property and category pages?

### ISSUE THREAD

**Issue by hannesmiller** [SemanticMediaWiki/SemanticMediaWiki#4426]
### Setup and configuration

- SMW version: 3.2.0-alpha
- MW version: 1.33.1
- PHP version: 7.2.24-0ubuntu0.18.04.1
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.28-0ubuntu0.18.04.4

### Issue
I think this is more of an enhancement request... Currently for `MediaWiki` properties and categories we import from a vocabulary like so:

```
[[Imported from::prefix:prop_or_category]]
```

- Why is importing restricted to only `property` and `category` pages?

- It would be very useful and save a lot of time if we could do this for an individual `MW` page?

**Comment by jaideraf** [comment]
Hi, you may be interested in the `Equivalent URI`[0] special property. It allows you to declare an `owl:sameAs` statement wich, in semantic terms, says that your URI represents the same external entity.

[0] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Equivalent_URI

**Comment by mwjames** [comment]
> Why is importing restricted to only property and category pages?

Because "importing" (or better declaring) is clearly defined for a property (or category) with a limit set of statements.

> It would be very useful and save a lot of time if we could do this for an individual MW page?

I'm guessing the functionality you are referring to is importing of RDF statements, yes? Otherwise you have to clarify of what you expect to happen here.

That requires considerable effort to parse the content as RDF and create equivalent statements. In the past there was a rudimentary support for this [0] but the maintenance cost clearly outweighs the benefits in SMW core itself. One alternative is to use RDFIO [1] as it supports "... the RDF import and export functionality in Semantic MediaWiki by providing import of arbitrary RDF triples ...".

[0] https://www.semantic-mediawiki.org/wiki/Help:Ontology_import
[1] https://github.com/rdfio/RDFIO

**Comment by hannesmiller** [comment]
> Hi, you may be interested in the `Equivalent URI`[0] special property. It allows you to declare an `owl:sameAs` statement wich, in semantic terms, says that your internal IRI represents the same entity as an external IRI.
> 
> [0] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Equivalent_URI

Yes thanks ... we are making extensive use of `Equivalent URI` in fact what we do for aesthetic reasons is import our content via  `SMW REST API` into a volatile graph using Python `RDFLib`, manipulate it, i.e.  flip `owl:sameAs` with the `wiki IRI`.

**Comment by hannesmiller** [comment]
> > Why is importing restricted to only property and category pages?
> 
> Because "importing" (or better declaring) is clearly defined for a property (or category) with a limit set of statements.
> 
> > It would be very useful and save a lot of time if we could do this for an individual MW page?
> 
> I'm guessing the functionality you are referring to is importing of RDF statements, yes? Otherwise you have to clarify of what you expect to happen here.
> 
In essence yes ... we tried creating some  [SMW Subobjects](https://www.semantic-mediawiki.org/wiki/Subobject) with some localized properties for a few pages ...

It wasn't clear in the documentation as what to expect on the RDF output - we were hoping for an  [RDF Blank Node](https://en.wikipedia.org/wiki/Blank_node) with some internal properties.

But found the  `properties` themselves must be defined in the `MW ` as they were showing as `redlinks` and hence I created some non-imported properties.

It's not a show stopper for us as we ended up extending our `vocabulary` and `ontology` which is not always convenient for all situations.

> That requires considerable effort to parse the content as RDF and create equivalent statements. In the past there was a rudimentary support for this [0] but the maintenance cost clearly outweighs the benefits in SMW core itself. One alternative is to use RDFIO [1] as it supports "... the RDF import and export functionality in Semantic MediaWiki by providing import of arbitrary RDF triples ...".
> 
> [0] https://www.semantic-mediawiki.org/wiki/Help:Ontology_import
> [1] https://github.com/rdfio/RDFIO

Yes we initially looked at `RDFIO` extension about 6 months ago - there were some nice features but in the decided to stick with the SMW Core.

Thank you for filling me in on the background.
