### ISSUE TITLE
Make dev example docs executable and add basic CI support

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#445]
After reading [a question on SMW wiki](https://semantic-mediawiki.org/wiki/User_talk:Yury_Katkov/programming_examples#Examples_not_working_1402) I started thinking that it is probably good if we migrated our code examples in such a way that they become executable and testable. If they each are in a `.php` file in `docs/technical/examples`, the CI could execute them, and catch errors. This would ensure the examples stay up to date with the version of SMW they are bundled with. We have such examples both on SMW wiki and in `.md` files in `docs/technical`.

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Code_snippets

**Comment by mwjames** [comment]
Moving this to [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/3
