### ISSUE TITLE
Templatefile format is not receiving intro and outro parameters

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#4467]
### Setup and configuration

- SMW version: 3.2.0-alpha
- MW version: 1.33.2
- PHP version: 7.3.12
- MySQL version: 5.6.46-86.2

### Issue
The `templatefile` format is not sending `intro` and `outro` parameter values to the output file. 

### Steps to reproduce
See here: https://sandbox.semantic-mediawiki.org/wiki/Issue/4467

**Comment by mwjames** [comment]
> The templatefile format is not sending intro and outro parameter values to the output file.

I'm not sure (without having looked at it) but I don't think export formats in general will produce an intro/outro text.

**Comment by mwjames** [comment]
> I'm not sure (without having looked at it) but I don't think export formats in general

... and the reason is that it checks for `$results->getCount() > 0` [0] which in case of export formats is always "0" since we only produce a link when embedded.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/ResultPrinters/ResultPrinter.php#L382-L398

**Comment by jaideraf** [comment]
The docs says we can use them [0] and they also appear at `Special:Ask` (when selecting the templatefile format) [1]

[0] https://www.semantic-mediawiki.org/wiki/Help:Templatefile_format
[1] https://www.semantic-mediawiki.org/wiki/Special:Ask

**Comment by mwjames** [comment]
> The docs says we can use them [0] and they also appear at Special:Ask

I said when "... when embedded ...".

**Comment by jaideraf** [comment]
I think I need to clarify before any misunderstanding: I think intro and outro should be placed **inside** the contents of the file, not before and after the link to the file.

But thinking right now, they would be exacly like introtemplate and introtemplate if they do... Now I am confused of what shoud they behave.  :thinking:

**Comment by mwjames** [comment]
> I think I need to clarify before any misunderstanding: I think intro and outro should be placed inside the contents of the file, not before and after the link to the file.

The `intro`/`outro` parameters are to encapsulate the result as in <intro> <actual results> <outro> while `introtemplate`/`outrotemplate` should be used to add something to the top (or bottom) before (or after) the actual template has generated the result output.

**Comment by jaideraf** [comment]
Thanks for clarifying @mwjames. I have had understood like `intro/outro` for just (simple) texts to be added and `introtemplate/outrotemplate` as "complex" (templates) texts.

**Comment by kghbln** [comment]
I guess this is clarified now and can be closed?

**Comment by jaideraf** [comment]
@kghbln I think the documentation should mention that `intro/outro` parameters will not produce anything when specified. So I added this note:
https://www.semantic-mediawiki.org/w/index.php?title=Help%3ATemplatefile_format&type=revision&diff=73874&oldid=66414

**Comment by kghbln** [comment]
Thanks a lot. I think that the `#smwdoc` parser function could use some improvement. There are quite some other exceptions this one does not take into account. On the other hand it might be to much effort to make it accommodate for it. Definitively not a front burner improvment.
