### ISSUE TITLE
Fatal error: Class 'SMW\MediaWiki\Hooks\HookHandler' not found

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4480]
### Setup and configuration

- MediaWiki | 1.34.0 (ae6e0c0)15:53, 27 December 2019
- PHP | 7.2.24-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.43-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (73f3016) 23:59, 23 January 2020
- Admin Links | 0.4 (647fc41) 21:48, 13 January 2020

### Issue
```
 Fatal error: Class 'SMW\MediaWiki\Hooks\HookHandler' not found in /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/AdminLinks.php on line 16
```
I am a pretty heavy user of the Admin Links extension, so a fix will be utterly cool.

### Steps to reproduce
Happens when accessing [Special:Adminlinks](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:AdminLinks)

**Comment by mwjames** [comment]
> Fatal error: Class 'SMW\MediaWiki\Hooks\HookHandler' not found

Wasn't tested because nothing we can test (oversight from #4456) unless you have it installed.

**Comment by kghbln** [comment]
> Wasn't tested because nothing we can test (oversight from #4456) unless you have it installed.

No worries. Thanks for the fix!
