### ISSUE TITLE
Deprecation in implode()

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#4501]
PHP 7.4, MW 1.34.0. SMW 3.1.3:
```ErrorException from line 402 of /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php: PHP Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters```

**Comment by JeroenDeDauw** [comment]
Thanks for reporting. Fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4502
