### ISSUE TITLE
TypeError from line 42 "IndexerRecoveryJob.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4522]
### Setup and configuration

- MediaWiki | 1.34.0 (df260af)16:26, 28 January 2020
- PHP | 7.2.24-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.44-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (93b0a24) 15:00, 6 February 2020

### Issue
Then trying to run "rebuildElasticIndex.php" on sandbox I get the following error:
```
   ... updating document ...                          22566 / 242498 (  9%)
[33b7306eb37214473b24d014] [no req]   TypeError from line 42 of /../w/extensions/SemanticMediaWiki/src/Elastic/Jobs/IndexerRecoveryJob.php: Argument 1 passed to SMW\Elastic\Jobs\IndexerRecoveryJob::__construct() must be an instance of Title, null given, called in /../w/extensions/SemanticMediaWiki/src/Elastic/Jobs/IndexerRecoveryJob.php on line 81
```
### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/Elastic/Jobs/IndexerRecoveryJob.php(81): SMW\Elastic\Jobs\IndexerRecoveryJob->__construct(NULL, array)
#1 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Indexer.php(320): SMW\Elastic\Jobs\IndexerRecoveryJob::pushFromDocument(SMW\Elastic\Indexer\Document)
#2 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder/Rebuilder.php(317): SMW\Elastic\Indexer\Indexer->indexDocument(SMW\Elastic\Indexer\Document)
#3 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(474): SMW\Elastic\Indexer\Rebuilder\Rebuilder->rebuild(string, SMW\SQLStore\EntityStore\StubSemanticData)
#4 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(421): SMW\Maintenance\RebuildElasticIndex->rebuildByRow(string, stdClass, string, boolean)
#5 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(186): SMW\Maintenance\RebuildElasticIndex->rebuild()
#6 /../w/maintenance/doMaintenance.php(99): SMW\Maintenance\RebuildElasticIndex->execute()
#7 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(534): require_once(string)
#8 {main}
```

**Comment by mwjames** [comment]
Relates to #4498.

**Comment by kghbln** [comment]
@mwjames Thank you for the fix! One thing with the script output:

```
Rebuilding indices ...
   ... creating required indices and aliases ...                          ✓
   ... selected entities ...                                    9449 (rows)
   ... updating document ...                         185454 / 242509 ( 76%)
   ... done.
```
The script completed successfully, however only 76% of documents were updated. I know this is not exact science with the progress information but this discrepancy appears to be a bit big. If I remember correctly I always had a 100% in the end.

**Comment by mwjames** [comment]
>  If I remember correctly I always had a 100% in the end.

Before #4498 each single entity was read from the DB and replicated but with #4498 and the `Document` it only uses the "parent" and produces the graph (including subobjects) from the `SemanticData` object.

I'll look into those numbers, for now this shouldn't raise any concerns.

**Comment by kghbln** [comment]
Thanks for the insight.

> I'll look into those numbers, for now this shouldn't raise any concerns.

Yeah, this will be great since people will intuitively be concerned if only 76% of documents were dealt with.
