### ISSUE TITLE
Elasticsearch, file ingestion, and the "Content keyword" property

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4528]
As outlined in [0] we are able to fetch certain information from Elasticsearch/Tika as part of the file ingestion and make them available in the `File attachment` container.

Now, one of the properties is the `Content keyword` property but the documentation [1] isn't really forthcoming on how the data are expected to be stored in the Elasticsearch `keywords` field whether with `,`, `;`, or just separated by a space. [2] shows what is possible and based on these examples we have to conclude that it is "just" a long text field without a predetermined method (for example always uses `,` or `;` etc.) to split those terms into individual representations in SMW.

refs #4488 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Elastic/docs/replication.md#file-attachment
[1] https://www.elastic.co/guide/en/elasticsearch/plugins/master/using-ingest-attachment.html
[2] https://sandbox.semantic-mediawiki.org/wiki/Attribut:Content_keyword

**Comment by kghbln** [comment]
Thanks. Also [referenced from the wiki.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AElasticStore%2FFile_ingestion&type=revision&diff=74203&oldid=74034)
