### ISSUE TITLE
"Examination Panel" or a better name?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4530]
Semantic MediaWiki 3.1 introduced several examinations (integrity checks) during its release cycle and made those results visible to users by relying on the so called page status indicator.

The problem to provide more checks hereby add more of those individual status indicators will quickly diminish the objective of helping users to identify and understand issues with an entity (aka. wikipage) by being confronted with too many visual cues that need to be deciphered while viewing a page.

So, for the last couple of weeks I reworked how those checks interact and integrated them into one coherent panel which is extensible for future checks (if needed). The panel is expected (see the screen shots) to provide guidance for failed checks.

The implementation and interfaces will be placed in the `SMW\Indicator\EntityExaminerIndicators` NS while the panel is tentatively named "Examination Panel".

The question is, are they any suggestions for a better name?

## Examples
![image](https://user-images.githubusercontent.com/1245473/74103496-41155d80-4b44-11ea-885f-dfc88a6a593f.png)

![image](https://user-images.githubusercontent.com/1245473/74103502-4d011f80-4b44-11ea-9d34-3a7e9a8fe54f.png)

![image](https://user-images.githubusercontent.com/1245473/74103512-59857800-4b44-11ea-801c-3011a3858d92.png)

**Comment by akuckartz** [comment]
"Data Quality Panel" or "Quality Panel". Maybe without "Panel".

**Comment by kghbln** [comment]
"Data Status Monitor", "Page Data Monitor" or "Page Data Panel" though I prefer the first.

> "Data Quality Panel" or "Quality Panel". Maybe without "Panel".

Quality goes a bit too far I guess since it is a formal check in the end. Not saying that this formal check is to be undervalued.

**Comment by jaideraf** [comment]
"Data analysis $1", "Data status $1", "Data notice $1", "Data information $1",  "Data diagnosis $1"

$1 = indicator, monitor, panel, tool, board

I like [SMW] Data status indicator (to contrast with, and at the same time, to resemble MW page status indicator).

**Comment by mwjames** [comment]
I appreciated the feedback but somehow it didn't make "click" which is why I will most like go with "Entity issue panel" because the examiner is about the `Entity` (aka. wikipage) not some "Data" and "Quality" would imply an broader approach including various examinations of an entity while in fact there are only dedicated checks that are run to identify potential inconsistencies upfront.

**Comment by akuckartz** [comment]
"Page issues" or "Page inconsistencies"

**Comment by mwjames** [comment]
> "Page issues" or "Page inconsistencies"

We are not concerned about something like a "Page" (we don't know that MediaWiki concept) the only thing we know of is an Entity [0] and that is what we are examine here. To elaborate on the difference, the "Page" concept would imply knowledge about a revision or a history of a content representation which we clearly don't have and it is why we normally don't refer in SMW to a "Page" as representation for concept or idea. On the other hand, adding a "page" type is legitimate as it refers to a specific representation.

[0] https://www.semantic-mediawiki.org/wiki/Entity

**Comment by kghbln** [comment]
> "Entity issue panel"

Yeah, this on is good.

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Entity_issue_panel
