### ISSUE TITLE
Travis / Postgres sometimes stops with connections on Unix domain socket

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#458]
Sometimes our postgres runs are stale and Travis-CI returns with:

```
psql -c 'create database its_a_mw;' -U postgres
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

After restarting the run (as in [0]), the installation normally goes smooth and unit tests do what they suppose to be doing.

**Comment by mwjames** [comment]
> +'[' postgres == postgres ']'
+sudo /etc/init.d/postgresql stop
 * Stopping PostgreSQL 9.1 database server        * Stopping
PostgreSQL 9.2 database server        * Stopping PostgreSQL 9.3
database server
+sudo /etc/init.d/postgresql start
 * Starting PostgreSQL 9.1 database server       +psql -c 'create
database its_a_mw;' -U postgres
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Travis@support

> I think what might be happening is that the `psql` command is run before Postgres has finished starting up, we see this issue with some other databases from time to time. Could you try adding a sleep of a few seconds between starting PostgreSQL and the first command that accesses PostgreSQL? Since this usually works I don't think you need a very long sleep time.

Added with 9de2388218

**Comment by gavinwahl** [comment]
I recently started seeing this error <https://travis-ci.org/fusionbox/django-widgy/jobs/53861004>. This just started (I've been using this same .travis.yml for years). I assume that the before_script is getting run before the environment is fully initialized.

If I can wager a guess, did the worker environment recently switch from sysv init to systemd? Seems like systemd's lazy behavior could cause the init process to return before it's completely finished.

I wouldn't call putting a sleep in your before_script a real solution. Shouldn't you want until the environment is ready before even starting the before_script?
