### ISSUE TITLE
Using `SemanticData::addPropertyObjectValue`

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4581]
In reference to https://github.com/JeroenDeDauw/Maps/pull/603#commitcomment-37307413

If you are a developer and you want to extend the `SemanticData` with your own data as outlined in [0] then using `SemanticData::addPropertyObjectValue` requires you to be particular vigilant in how and what data you are trying to add via the `SemanticData::addPropertyObjectValue` method.

```php
$semanticData->addPropertyObjectValue(
	new \SMW\DIProperty( 'HasDescription' ),
	new \SMWDIBlob( 'blah' )
);
```

For the above example, any storage attempt will fail when using a `SMWDIBlob` instance in connection with a property that isn't a `_txt` type and as visible in the log with:

```
from line 1506 of ...\includes\libs\rdbms\database\Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: INSERT  INTO `smw_di_wikipage` (s_id,p_id,o_blob,o_hash) VALUES ('165027','165037',NULL,'blah')
Function: SMW\SQLStore\PropertyTableUpdater::insert-smw_di_wikipage
Error: 1054 Unknown column 'o_blob' in 'field list' (localhost)

#0 ...\includes\libs\rdbms\database\Database.php(1476): Wikimedia\Rdbms\Database->makeQueryException(string, integer, string, string)
#1 ...\includes\libs\rdbms\database\Database.php(1236): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#2 ...\includes\libs\rdbms\database\Database.php(2078): Wikimedia\Rdbms\Database->query(string, string)
```

Now, that the a particular storage has failed the entire update failed as well (open transactions are rolled backed) and as a consequence no data is available for the entity (aka. wikipage).

`SemanticData::addPropertyObjectValue` is used without checking the type between `Property` and `DataItem` because methods that use this method have verified the data before and is not necessary to make `addPropertyObjectValue` to verify the type again. Raising any exception wouldn't help at this stage because it is removed from any user interaction and hereby is only visible in the log given that the storage and related activities are executed as part of the `DeferredUpdate`.

## Type safety

As noted in [0], if you are not sure about the data and types (because of some user input or unknown variable) then relying on the `DataValueFactory`  is the appropriate choice to build the correct value representation from the available data (see for supported method signatures).

```php
$dataValue = DataValueFactory::getInstance()->newDataValueByText(
	'AnotherPropertyIWantToUse',
	'123'
);
$semanticData->addDataValue(
	$dataValue
);
```
[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/examples/hook.pagecontentsavecomplete.md

**Comment by JeroenDeDauw** [comment]
Well ok, all the more reason for SMW to get a new interface more suitable for storing structured data from extensions, which is what https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4583 is about.

**Comment by mwjames** [comment]
> Well ok, all the more reason for SMW to get a new interface more suitable for storing structured data from extensions, which is what #4583 is about.

I'm not sure about this, all what is need is already in place, the `SemanticData::addPropertyObjectValue` is used for cases where data have been validated before and in all other cases the `DataValueFactory` should be used to create a `DataValue` object because it is at this level where input data gets validated against the type. For example, it means if you post a string on a `_num` type then this will be recognized and reported as `Processing error` (which is queryable and visible to the end-user) or if you post a non-URL conform input on a `_url` type then this will be reported as well.

Again, validation of (input)data happens through a `DataValue` instance.

**Comment by mwjames** [comment]
Also, just because some data "says" (in form of some XML or JSON import definition) that is of a valid type doesn't mean it will pass value validation for those types in SMW and is the reason why validation of any data has to happen before it reaches the DB presentation level (in form of a `DataItem`) independent of whether the source is trustworthy or not.
