### ISSUE TITLE
Let SESP to be grouped in Special:Browse via smw/schema:Group:Predefined properties

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#4597]
### Setup and configuration

- SMW version: 3.2.0-alpha
- MW version: 1.33.2
- PHP version: 7.3.14
- MySQL version: 5.6.46-86.2
- SESP version: 2.1.0

### Enhancement
When aplying "`_CUSER`" (key for `Page creator` special property from SESP - "Criador da página" in Portuguese) in "`adminstrative_group`" section from `smw/schema:Group:Predefined properties` the property does not "move" to `Adminstrative properties` group in Special:Browse.

### Steps to reproduce
See: 
* https://novo.wikincat.org/wiki/Especial:Navegar/:B000001?uselang=en
* https://novo.wikincat.org/w/index.php?title=smw/schema:Group:Predefined_properties&action=edit

**Comment by mwjames** [comment]
> When aplying "_CUSER" (key for Page creator special property from SESP

The actual (internal) key is `___CUSER` as see in [0] which should be used here.

[0] https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/data/definitions.json#L32-L37

**Comment by kghbln** [comment]
> The actual (internal) key is ___CUSER as seen in [0] which should be used here.

I knew this was already possible but I would not have come up with the internal id. Thanks for you help. Now [documented.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASchema%2FType%2FPROPERTY_GROUP_SCHEMA&type=revision&diff=74635&oldid=72777)

**Comment by jaideraf** [comment]
Indeed. Thanks @mwjames for your help, and thanks @kghbln for the ever astonishing SMW docs.
(I was on vacation, that is why did not respond earlier). :heart:
