### ISSUE TITLE
Removal of deprecated SpecialPageFactory

### ISSUE THREAD

**Issue by DannyS712** [SemanticMediaWiki/SemanticMediaWiki#4623]
Please note that the old SpecialPageFactory, deprecated in mediawiki 1.32, will likely be removed in 1.36. Its methods still have calls from this extension.

The replacement is to use MediaWikiServices::getInstance()->getSpecialPageFactory(), and use the new factory's methods. However, since this extension supports versions of MediaWiki that predate the addition of the new factory in 1.32, you will likely need to add conditional logic based on if the `MediaWiki\SpecialPage\SpecialPageFactory` class exists.

See https://phabricator.wikimedia.org/T246142 for more.

**Comment by kghbln** [comment]
Thanks a lot for notifying. I believe that the first version of SMW supporting MW 1.36 will at the same time drop support for MW 1.31. Thus some extra logic will not be necessary.

**Comment by kghbln** [comment]
@mwjames I believe #4602 and #4603 are the direct results of this removal

**Comment by kghbln** [comment]
I cross referenced the existing issues with this one. Thus closing here since we have dedicated issues.
