### ISSUE TITLE
Tokens with #ask with smw > 3.0.2 

### ISSUE THREAD

**Issue by circa138** [SemanticMediaWiki/SemanticMediaWiki#4624]
### Setup and configuration

- SMW version: 3.1.5
- MW version: 1.3.3
- PHP version: 7.3.11-1~deb10u1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.17-MariaDB-0+deb10u1

### Issue
When im using the "edit with form" option or i am trying to create an entity with a form im getting an error in the PF_ValuesUtils.php (PageForms). I was able to identify the error. I am using tokens for the input (which are replacing 'two listboxes') and localized the problems in the 'values' part:
{{{field|fieldName|input type=tokens|default=X|**values from query={{#ask:[[Category:XCat]]}}** }}}
When im removing the line it works well. After downgrading SMW from 3.1.5 to 3.0.2 the error is gone. 

### Stack trace
```
[fe42c27fc7e153154b6b1a45] [no req] Error from line 782 of /var/www/html/wikiname/extensions/PageForms/includes/PF_ValuesUtils.php: Call to undefined method SMWQueryProcessor::processFunctionParams()

Backtrace:

#0 /var/www/html/wikiname/extensions/PageForms/includes/PF_ValuesUtils.php(574): PFValuesUtils::getAllPagesForQuery(string, integer)
#1 /var/www/html/wikiname/extensions/PageForms/includes/PF_FormField.php(336): PFValuesUtils::getAutocompleteValues(string, string)
#2 /var/www/html/wikiname/extensions/PageForms/includes/PF_FormPrinter.php(1058): PFFormField::newFromFormFieldTag(array, PFTemplate, PFTemplateInForm, boolean)
#3 /var/www/html/wikiname/extensions/PageForms/includes/PF_AutoeditAPI.php(901): PFFormPrinter->formHTML(string, boolean, boolean, integer, string, string, NULL)
#4 /var/www/html/wikiname/extensions/PageForms/includes/PF_AutoeditAPI.php(115): PFAutoeditAPI->doAction()
#5 /var/www/html/wikiname/extensions/PageForms/specials/PF_FormEdit.php(104): PFAutoeditAPI->execute()
#6 /var/www/html/wikiname/extensions/PageForms/includes/PF_FormEditAction.php(310): PFFormEdit->printForm(string, string)
#7 /var/www/html/wikiname/extensions/PageForms/includes/PF_FormEditAction.php(32): PFFormEditAction::displayForm(PFFormEditAction, Article)
#8 /var/www/html/wikiname/includes/MediaWiki.php(511): PFFormEditAction->show()
#9 /var/www/html/wikiname/includes/MediaWiki.php(302): MediaWiki->performAction(Article, Title)
#10 /var/www/html/wikiname/includes/MediaWiki.php(900): MediaWiki->performRequest()
#11 /var/www/html/wikiname/includes/MediaWiki.php(527): MediaWiki->main()
#12 /var/www/html/wikiname/index.php(44): MediaWiki->run()
#13 {main}
``` 

### Steps to reproduce
try to set **values from query={{#ask:[[Category:XCat]]}}** in input=tokens

**Comment by kghbln** [comment]
Thank you  for your elaborate report. I am afraid this is an issue for the Page Forms extension. Thus I have created [Task T247056](https://phabricator.wikimedia.org/T247056) for you to address this issue.

**Comment by mwjames** [comment]
> [fe42c27fc7e153154b6b1a45] [no req] Error from line 782 of /var/www/html/wikiname/extensions/PageForms/includes/PF_ValuesUtils.php: Call to undefined method SMWQueryProcessor::processFunctionParams()

In regards to `SMWQueryProcessor::processFunctionParams`, see #3402 (and #2737).
