### ISSUE TITLE
Owl / Import vocabulary / Use of `Imported from` property

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#464]
I tried to create a `Property:Homepage` with `[[imported from::foaf:homepage]]` just to encounter that fundamental settings are missing. After looking at `SMW_DV_Import.php`:

- The `smw_unknown_importns` is missing from i18n
- Individual namespace definition such as `smw_import_foaf` is missing as well

Adding `"smw_import_foaf": "http://xmlns.com/foaf/0.1/|[http://www.foaf-project.org/ Friend Of A Friend] \n name|Type:String\n homepage|Type:URL\n mbox|Type:Email\n mbox_sha1sum|Type:String\n depiction|Type:URL\n phone|Type:String\n Person|Category\n Organization|Category\n knows|Type:Page\n member|Type:Page"
` to the en.json, copied from http://semanticweb.org/index.php?title=MediaWiki:Smw_import_foaf,  I was finally able to use `[[imported from::foaf:homepage]]`

### i18n
- [X] Add `smw-pa-property-predefined_impo` explain the property and point to http://semantic-mediawiki.org/wiki/Help:Import_vocabulary
- [x] Add `smw-datavalue-import-unknownns` for better help when a namespace definition such as `foaf` is missing and needs a message key such as `smw_import_foaf`

**Comment by mwjames** [comment]
@kghbln Maybe in 2.2 we could sort things a bit. I found another site (smw.coopaxis.fr) that relies on import vocab. @tfrancart would be great if you could share your experience and suggestions how to improve the documentation or feature in general. 

> I just never understood (but I never asked) why the types declared in MediaWiki:smw_import_... don't work.
Because of that, I have to declare them on every page property anyway.
So, to me, I could never obey this part of the documentation: "If you import a property, remove its "has type" statement."

@jaideraf A more detailed analysis on this issue would help as well.

**Comment by tfrancart** [comment]
Actually, smw.coopaxis.fr and the blog post on blog.sparna.fr all comes from me.
I second jaideraf by saying this vocabulary import feature is important for me too.
I also wasn't able to make this part of the documentation work : "If you import a property, remove its "has type" statement."

I don't really have enough experience for now to make suggestions on how to improve, our SMW+RDF project is just starting, but be sure that I will let you know if I have !

**Comment by jaideraf** [comment]
@mwjames, just to explain some things:
* Despite my concern about vocabularies/ontologies in the SMW RDF export, I don't currently use the RDF exported in a triplestore. I am just "ready to use" but not actually using it yet. So, I can not run tests or whatever in triplestores.
* As a Semantic Web researcher (like Markus and Denny), I think [semantic interoperability](https://en.wikipedia.org/wiki/Semantic_interoperability) is a key issue on the Web (and, by extension, on the SMW). That's why I try to use vocabularies/ontologies well known (dc, foaf, skos, schema, geo, etc.). But, I have to admit, just a few people that use SMW care about these "old Semantic Web visions". And I can not blame them. Even the SMW “[SWIVT Ontology Specification](http://semantic-mediawiki.org/swivt/)” [1] is very outdated.
* More about [SMW vocabulary import feature on Google](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22MediaWiki:smw_import_%22&safe=off&start=0).

I second tfrancart by saying I don't really have enough experience for now to make suggestions or how to improve the vocabulary import feature, but be sure that I will let you know if I have!
(only this bug about declaring the datatype in the MediaWiki:Smw_import_... that doesn't work).

1. http://semantic-mediawiki.org/swivt/1.0

**Comment by jaideraf** [comment]
Just one more thing: 
> However I believe the output of "knows" is wrong since it uses "Special:URIResolver" which should not happen if I understand correctly. The same thing on semanticweb.org provides the URL to the referenced page of the person.

The use of the “Special:URIResolver” is exactly the right URI to be there. The result of the  semanticweb.org is different because they use $smwgNamespace = 'http://semanticweb.org/id/'; [1]

“Special:URIResolver” is the URI to represent the entity (the actual person, for example), not the (wiki or web) page about it. 

In other words, the person (Special:URIResolver/$Person) can have a (dc:)creator. And the page about the person (wiki/$Person) can have another (dc:)creator.

1. http://semantic-mediawiki.org/wiki/Help:Configuration#smwgNamespace

**Comment by mwjames** [comment]
Here is another thought on how to improve the practical application without having to "Deploy smw_import_foaf as example with SMW".

By borrowing the power of the standard `Special:Import`, `Special:Export` it should be possible to host downloadable XML files on github/smw.org that contain owl vocabs to be readily reusable in SMW.

For example, if you go to https://semantic-mediawiki.org/wiki/Special:Export and export the following, you get an XML that can be imported across wikis without the need to edit or create the property manually.
```
MediaWiki:Smw import foaf
Property:Foaf:name
Property:Foaf:knows
Property:Foaf:homepage
```
With a more comprehensive and complete definition base the usage can be hosted as downloadable (either on smw.org or github) file.

In order to avoid issues with existing property names, the naming schema should follow `Namespace`:`Identifier` (`Property:Foaf:name` or `Property:Dc:publisher` etc.) and annotations can be made with `[[Foaf:name::Foo]]` or `[[Dc:publisher::Bar]]`.

If after the import someone wants to use other names then s(he) has to only redirect to the imported definition as in `Property:Homepage` to `#REDIRECT [[Property:Foaf:name]]`.

@kghbln @jaideraf All we need is to provide a well maintained vocab base (foaf,dc etc.), so that a XML can be generated.

The outlined approach should make it possible to revive the smw.org@`Help:Ontology import` page by focusing solely on the `Special:Import`, `Special:Export` approach.

**Comment by jaideraf** [comment]
@mwjames Great idea!
Right now, I have no time to maintain those pages (vocabularies) on smw.org.
But, my following pages may help to start such a thing:

* dc: http://wikincat.org/wiki/MediaWiki:Smw_import_dc?action=edit
* dcterms: http://wikincat.org/wiki/MediaWiki:Smw_import_dcterms?action=edit
* foaf: http://wikincat.org/wiki/MediaWiki:Smw_import_foaf?action=edit
* owl*: http://wikincat.org/wiki/MediaWiki:Smw_import_owl?action=edit
* rdfs*: http://wikincat.org/wiki/MediaWiki:Smw_import_rdfs?action=edit
* skos: http://wikincat.org/wiki/MediaWiki:Smw_import_skos?action=edit

\* CAUTION: this can explode semantics.
Unfortunately, I currently don't have all the pages of these properties on my wiki. But, it's a start.

**Comment by mwjames** [comment]
#884 now tests `imported from` property with described test cases using `foaf:name`, `foaf:knows` annotation.

**Comment by mwjames** [comment]
#884 also fixes the issue that if you created a `MediaWiki:Smw_import_*` in one particular language while switching to another content language it would render the import content (it is still their but not in the content language expected) empty. This is now corrected and handled by [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/ControlledVocabularyImportFetcher.php

**Comment by mwjames** [comment]
Could some help to follow up on the import properties discussion here [0] because I'm occupied with some other issues to give this a thorough read through?

[0] https://semantic-mediawiki.org/w/index.php?title=semantic-mediawiki.org:Community_portal&offset=20150319125758&lqt_mustshow=1673#Some_questions_about_SMW_1673

**Comment by kghbln** [comment]
I am not the best of breed not when it comes to this. Wonder why [the tip](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/464#issuecomment-70341109) did not work out since it looks very reasonable to me. Perhaps  @jaideraf has another idea...

**Comment by jaideraf** [comment]
I think the user just forgot to declare `[[imported from::$vocabPrefix:$propertyOrClass]]` on the property or category page.

**Comment by kghbln** [comment]
Just added the /qqq

**Comment by kghbln** [comment]
@jaideraf Thank you!

**Comment by mwjames** [comment]
SMW 2.2 generally improves the handling of imported vocab* while providing additional integration tests [0, 1] therefore from the premise of "Use of `Imported from` property" this issue is resolved.

Of course, it would be neat if the smw.org documentation could be improved over time to make this topic more accessible to new comers.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Rdf/rdf-003-import-foaf.json

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/Fixtures/query-03-01-import-foaf.json

**Comment by kghbln** [comment]
@jaideraf I'd rather call me a newcomer on this too to be frank. To me it appears that you have much more insight and use cases or better used is for some cases. Will you do the honors of documenting, please?

**Comment by jaideraf** [comment]
@kghbln, I'm sorry. I appreciate your comment, but I am on vacation right now. I cannot test the RC nor revise the documentation about the vocabulary import on the next weeks. Cheers.

**Comment by kghbln** [comment]
@jaideraf No worries. Enjoy your vacation! Since this is more or less about documenting, we will cheerfully wait until you are back for action.

**Comment by jaideraf** [comment]
@kghbln @mwjames The page "Import vocabulary" on smw.org, now, seems updated to me.
http://semantic-mediawiki.org/w/index.php?title=Help%3AImport_vocabulary&diff=38830&oldid=34697
