### ISSUE TITLE
Typo in release page: SMW 3.1.5 not SWM 3.1.5

### ISSUE THREAD

**Issue by jqnatividad** [SemanticMediaWiki/SemanticMediaWiki#4643]
### Setup and configuration

- SMW version: 3.1.5
- MW version: 1.34
- PHP version: 7.2.24
- DB system (MySQL, Blazegraph, etc.) and version: PostgreSQL 11.7

### Issue
Just a typo :) https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases

**Comment by kghbln** [comment]
@jqnatividad Good catch, Joel. Thanks a lot. Amended now.
