### ISSUE TITLE
rebuildData.php script always stops at the same page ID

### ISSUE THREAD

**Issue by NicolasNallet** [SemanticMediaWiki/SemanticMediaWiki#4652]
### Setup and configuration

- SMW version: 3.1.5 seen on 3.1.4 too
- MW version: 1.34.0 seen on 1.33+ too
- PHP version: 7.2.24
- DB system (MySQL, Blazegraph, etc.) and version:MySQL 5.7.29

more info on https://wikivalley-publictest.wiki-valley.com/Special:Version

### Steps to reproduce
the page that block the rebuildData is on time out : https://wikivalley-publictest.wiki-valley.com/Template:Th%C3%A8me

**Comment by kghbln** [comment]
I have no clue what I should do with this. As you mention the template times out so no way to have a look at it. What kind of stuff did you add to this template?

**Comment by NicolasNallet** [comment]
I cannot get the wikitext either... I will have a look at the database

**Comment by kghbln** [comment]
Oh man, even with an account one cannot see the wikitext: https://wikivalley-publictest.wiki-valley.com/index.php?title=Themplate:Th%C3%A8me&action=edit: locked down. You are even more crazy than me when it comes to editing and viewing of unattended wikis. :)

**Comment by kghbln** [comment]
Anyhow I guess the database appears to be the only way to get the wikitext right now.

**Comment by mwjames** [comment]
> the page that block the rebuildData is on time out : https://wikivalley-publictest.wiki-valley.com/Template:Th%C3%A8me

Unless there is a stacktrace that hints towards some SMW function, I don't think this issue is related to SMW given the "... I cannot get the wikitext either..." which seems to have a more fundamental MW issue.

**Comment by kghbln** [comment]
I guess this is no longer an issue. Thus closing. However in the light of new findings this one can obviously be re-opened again.
