### ISSUE TITLE
SPARQLStore / Property value redirects in queries (bug 40084)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#467]
Just encountered [bug 40084](https://bugzilla.wikimedia.org/show_bug.cgi?id=40084) (from 2012) which is still not solved with the current implementation.

**Comment by lloonngg** [comment]
Hi,

I am trying to use 4store 1.1.5 or virtuoso 7.1 as RDF backends for our SMW 2.1 instance.  All of our subobject queries do not work and I assume that it is related to lack of SPARQL 1.1 support (I assume from the RDF backend?).  The subobject queries works on jena-fuseki; however, we have noticed poor performance after migrating over 100K+ pages.  Therefore we prefer to use 4store or virtuoso.  Is there any quick fix to support subobject queries or will this have to wait until SMW 2.2 is released?  Is this something that can be fixed only from the SMW side or SPARQL 1.1 is absolutely required on the RDF backend?

Thanks,

Long

**Comment by mwjames** [comment]
> I am trying to use 4store 1.1.5 or virtuoso 7.1 as RDF backends for our SMW 2.1 instance. All of our subobject queries do not work and I assume that it is related to lack of SPARQL 1.1 support (I assume from the RDF backend?)

No, SPARQL 1.1 has nothing do to with subobject support. SPARQL 1.1 is only relevant to some query features (as mentioned above for example in case of property paths etc.)

> The subobject queries works on jena-fuseki;

There is no discrimination between Fuseki, Sesame, 4store, or Virtuoso when it comes to replicating the data from SMW to the TDB instance because the RDF export (or better the Turtle serialization) is the same for all official listed TDB's that are supported and tested.

Normal annotations (`[[ ... :: ... ]]`) and subobject annotations are tested against [tr.0] involving different use cases [t.1, t.2, t.3] that include subobjects as well. This is to ensure that those objects behave in the same way and are independent from the back-end (`SQLStore` or `SPARQLStore`).

> we have noticed poor performance after migrating over 100K+ pages.

Interesting, can you quantify your findings?

> Therefore we prefer to use 4store or virtuoso. Is there any quick fix to support subobject queries or will this have to wait until SMW 2.2 is released?

The way subobjects are constructed/exported as TurtleTriple have not changed since 2.0 (where it was first supported).

Earlier today, I run __4store 1.1.4__ against the 2.2-RC build  [tr.1] which did not pass :-1:  all our tests especially [tr.1.1, tr.1.2] which are expected to pass as for any other tested TDB (Sesame, Fuseki, Virtuoso) therefore I can't really say whether 4store is supporting all use cases or not. Furthermore, it took the 4store instance ~ 31.6 minutes to complete our test suite which normally only takes ~2.5/3.5 min for any other vendor.

__Virtuoso 7.1__ passed :+1: all our tests against SMW 2.3 alpha/2.2-RC1 [tr.2] including those with subobjects but as you can see it took about 20 min to build Virtuoso 7.1 from ground up (because there is no official debian Virtuoso 7 package [v.1]) before the test could run hence we cannot effort to run 7.1 on a regular basis (building 7.1 from scratch is not what we want to test) therefore we rely on Virtuoso 6.1 via debian apt-get.

> Is this something that can be fixed only from the SMW side or SPARQL 1.1 is absolutely required on the RDF backend?

vide supra (SPARQL 1.1 is not required for the storage/replication)

> Is there any quick fix to support subobject queries

The information provided are somewhat short therefore no recommendation can be made but I urge you to run our test suite via `composer phpunit` [c.1] from your SMW root directory against your installation and see whether they pass or not. If they pass it means those tests that include subobjects return expected results and is an indication that `#subobject` parser/RDF export does work within your wiki (especially after running the integration tests).

You should create a new issue (#467 is solely addressing the redirects/property paths issue) with sufficient background information and use cases in order to analyse the root cause.

### Notes

[tr.0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki
[tr.1] https://travis-ci.org/mwjames/SemanticMediaWiki/builds/61200454
[tr.1.1] `SMW\Tests\Integration\Query\ByJsonQueryTestCaseRunnerTest::executeTestCasesFor with data set "query-01-02-blob.json" `
[tr.1.2] `SMW\Tests\Integration\Query\ByJsonQueryTestCaseRunnerTest::executeTestCasesFor with data set "query-01-04-blob-disjunction.json"`
[tr.2] https://travis-ci.org/mwjames/SemanticMediaWiki/builds/61203319
[t.1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Rdf/rdf-001.json#L17-L37
[t.2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/Fixtures/query-06-02-page-subobject-intext-parser.json#L9-L13
[t.3] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/SPARQLStore/QueryResultLookupWithoutBaseStoreIntegrationTest.php#L171
[v.1] https://github.com/openlink/virtuoso-opensource/issues/350#issuecomment-77861910
[b.1] http://sourceforge.net/p/bigdata/mailman/message/34073026/
[c.1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#running-tests

**Comment by mwjames** [comment]
Implemented with 05c38f2
