### ISSUE TITLE
Disabling SMW notice in editor

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4673]
![image](https://user-images.githubusercontent.com/146040/77826064-8221fb00-710d-11ea-8ee0-ca175721f822.png)

Is there a way to disable this notice via configuration?

I suspect disabling this would be the better default. Getting this in front of me on every edit, even when I am not using SMW, is annoying. It comes over to me as SMW screaming for attention like a little kid and makes me think bloatware.

I can also easily see people not wanting to install SMW because of this message for multiple reasons. I'm serious here. Want to start using SMW on part of your wiki? Well, too bad, all your editors now get this message. Even if it is not relevant to them. Even if it confuses them. Even if you do not want them to use SMW, or not use it via in-text annotations.

**Comment by mwjames** [comment]
Yes, either via the [0] global setting or in your preference section.

> I'm serious here. Want to start using SMW on part of your wiki? Well, too bad, all your editors now get this message. Even if it is not relevant to them. Even if it confuses them. Even if you do not want them to use SMW, or not use it via in-text annotations.

I don't understand the reasoning here, what has the message with installing of SMW in common?

[0] https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledEditPageHelp

**Comment by JeroenDeDauw** [comment]
Lets keep the issue open while we talk about this topic.

**Comment by JeroenDeDauw** [comment]
I'm honestly at a loss what part you do not understand. I used simple clear language. Not 4 line long sentences loaded with big words. So you'll have to help me and point to what needs more explanation.

**Comment by kghbln** [comment]
In general I disable this for the wikis I control for the simple reason that I am there in case help is needed.

If I remember correctly the reason for this is that people new to SMW usually cannot tell if a namespace is enabled for semantic annotations or not, especially if it is a custom namespace. And if they believe a namespace was enabled but is apparently is not working for annotations the situation does not get better.

To improve here I suggest to do two things:

1. Disable this parameter by default.

2. Add a warning to namespaces that do not allow for semantic annotations which are not by default part of `smwgNamespacesWithSemanticLinks` which can be disabled by a parameter.

**Comment by kghbln** [comment]
Triggered by a comment in another issue I remember that we have an [UPO for this](https://www.semantic-mediawiki.org/wiki/Help:Edit_help). So in your preferences it says: "[ ] Disable the introductory text on the edit page". So the easiest solution for 1. is to tick this by default and let users fiddle with the option.

**Comment by jaideraf** [comment]
For the record, I am not opposed to let it disabled by default. In fact, I do, too, disable it for the wikis I control. 

However, I think this message also serves to SMW be 'noticible' by an avergage user who will never automatically understand and learn the sintaxes `[[some text::another text]]`, `{{#set:}}` or `{{#subobject:}}`, etc.  I mean, how they could learn about SMW if SMW is almost invisible to them (except the result formats)? I do understand that maybe this message is not appropriate in this place or in this moment (every editing), but we have to think about it.

What I am trying to say is that, for example, Wikibase has a noticible interface where users know they are not in a "normal" MediaWiki. SMW lacks this kind of visibility (as any other invisible  extension), and we always have heard that SMW, besides being awesome, lacks some marketing to   it (it needs to be noticible).

**Comment by jaideraf** [comment]
That is why user interfaces like Special:Browse, the Fact box, Special:Ask, Special:FacetedSearch (hopefully) and others are important to make SMW gain public.

**Comment by JeroenDeDauw** [comment]
"edit with form" is probably more significant than all those combined. There definitely is room for more UIs. If you look at "competitors" like sharepoint and confluence, there is a lot more handholding. Visual flows with decent user experience and standard widgets. No need to learn templates and parser functions for something basic. SMW wins in power but loses overall due to immensely terrible UX for the most common usecases. Much potential here IMO.

**Comment by jaideraf** [comment]
> "edit with form" is probably more significant than all those combined. 

Yes, but, we know... it is not SMW. 

That is why I believe the power of SMW is in the MediaWiki template system. I mean, with the Parser Unification (Parsoid/PHP replacing the original parser) [0], VisualEditor may become the default editing interface in content namespaces. **New** users will probably interact with templates only in those interfaces (with the help TemplateData [1], similar to PageForms). 

I think wikitext will be used only in Template namespace and few others. So, SMW will have to choose at least one of the three options: 

* create a new way (visually) to make "annotations" on a page (without VisualEditor);
* use VisualEditor, adding buttons, windows, etc. to make "annotations" (probably using OOUI); 
* use VisualEditor/TemplateData for entenring templates (with SMW code only inside the template namespace, like PageForms) (no need to do anything new).

[0] https://phabricator.wikimedia.org/phame/post/view/189/parsoid_in_php_or_there_and_back_again/
[1] https://www.mediawiki.org/wiki/Extension:TemplateData
[2] https://www.mediawiki.org/wiki/OOUI

**Comment by gesinn-it** [comment]
Check out @osnard talk about TemplateData @SMWCon2019: https://www.semantic-mediawiki.org/wiki/CC1756624532

**Comment by JeroenDeDauw** [comment]
https://twitter.com/SemanticMW/status/1302013836992696321

**Comment by kghbln** [comment]
Hmm, since we have an UPO for this "Disable the introductory text on the edit page" I'd rather add a note to the system message making aware of this UPO. Setting to "false" basically removes the purpose.

**Comment by akuckartz** [comment]
> I'd rather add a note to the system message making aware of this UPO.

Was that done before closing this issue?

**Comment by JeroenDeDauw** [comment]
No. Please create a dedicated issue if you want to improve the notice in the editor
