### ISSUE TITLE
What happened to `SMW::LinksUpdate::ApprovedUpdate` hook and `docs/technical/code-snippets`?

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticMediaWiki#4739]
Hi!

I saw some documentation about a hook called `SMW::LinksUpdate::ApprovedUpdate` in version 3.0. But now in 3.1 and `master` I can not find it anymore. Has it been removed? I can not see any hint in the changelogs.

- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/code-snippets/README.md
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?q=ApprovedUpdate&unscoped_q=ApprovedUpdate

**Comment by kghbln** [comment]
> and `docs/technical/code-snippets`?

It was moved to another location: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3953 Now in [`/docs/examples/`.](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/docs/examples)

> I saw some documentation about a hook called SMW::LinksUpdate::ApprovedUpdate in version 3.0.

I believe [all of this is gone at SMW](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/examples/approve.update.md) and is now handled via the SAR extension.

**Comment by kghbln** [comment]
@osnard Thanks for asking. I guess I have answered correctly and fixed the broken links. If there is still something to ask ...

**Comment by mwjames** [comment]
> I saw some documentation about a hook called SMW::LinksUpdate::ApprovedUpdate in version 3.0. But now in 3.1 and master I can not find it anymore. 

Please see #3897 for the an explanation and relevant changes.
