### ISSUE TITLE
QuerySourceFactory: Cannot instantiate abstract class 

### ISSUE THREAD

**Issue by YOUR1** [SemanticMediaWiki/SemanticMediaWiki#4756]
Environment:
**mysql:** 10.2.31-MariaDB-1:10.2.31+maria~bionic
**smw:** 3.1.6
**mediawiki:** 1.31.3
**php:** 7.3.17-1+ubuntu18.04.1+deb.sury.org+1

We've encountered a fatal error since SMW tries to instantiate a new class which is a abstract class.

I think there should be an additional check in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/QuerySourceFactory.php#L82 to see if the source class is abstract yes or no. Otherwise it will fail at https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/QuerySourceFactory.php#L87.

The solution is what I think quite easy to achieve;
```php
$refClass = new \ReflectionClass( $source );
if ( $source === null || !class_exists( $source ) || !$refClass->isAbstract() ) {
...
```

**Comment by kghbln** [comment]
Thanks for reporting and suggesting a way out!

**Comment by mwjames** [comment]
> We've encountered a fatal error since SMW tries to instantiate a new class which is a abstract class.

I don't think that is possible with a standard setup which means you made some modifications and unless you explain the context of your modification, this isn't issue for SMW in general.

What did you do? How did it appear? Where is the stack trace?

> $refClass = new \ReflectionClass( $source );

This is not recommended for a "hot" code path given the performance impact [0] "... ReflectionClass construction is now a bit less than 3x slower than the object construction ..." (in PHP 8) of `ReflectionClass`.

[0] https://bugs.php.net/bug.php?id=72224

**Comment by YOUR1** [comment]
> > We've encountered a fatal error since SMW tries to instantiate a new class which is a abstract class.
> 
> I don't think that is possible with a standard setup which means you made some modifications and unless you explain the context of your modification, this isn't issue for SMW in general.
> 
> What did you do? How did it appear? Where is the stack trace?
> 
> > $refClass = new \ReflectionClass( $source );
> 
> This is not recommended for a "hot" code path given the performance impact [0] "... ReflectionClass construction is now a bit less than 3x slower than the object construction ..." (in PHP 8) of `ReflectionClass`.
> 
> [0] https://bugs.php.net/bug.php?id=72224

Hi James,

We don't do any modifications in SMW core itself, only in custom made extensions (which implement SMW ofcourse). The extension adds the 'ArchiMateStore' class to the $smwgQuerySources[] list. 

The ArchiMateStore exists of three files, extending a SMW class (and nothing more)
```class ArchiMateStore extends SQLStore {```
```class ArchiMateQueryResult extends SMWQueryResult {```
```class ArchiMateResultArray extends SMWResultArray {```

I've also found out that the problem occurs while there are still job's pending in the jobqueue. The wiki was migrated from a SMW2.5.x (MW 1.27) to the versions above. 

I think the solution I've pointed out should head you in the correct direction, but I don't know a more efficient way to see if the class is not a abstract class. And I really think it's not really that nice that the class throw's fatal errors, thus checking for abstract's isn't a bad thing to do really (imo).

**Stacktrace**
```php
[6a1b07d1b1c2f695b75b2a6a] /index.php?title=Bedrijfsobjecten_sturing Error from line 88 of /var/platform/wikifarm-2.0.x/hora2/20200430-153557/extensions/SemanticMediaWiki/src/Query/QuerySourceFactory.php: Cannot instantiate abstract class ArchiMate

Backtrace:

#0 /var/platform/wikifarm-2.0.x/hora2/20200430-153557/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(335): SMW\Query\QuerySourceFactory->get(string)
#1 /var/platform/wikifarm-2.0.x/hora2/20200430-153557/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(361): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#2 /var/platform/wikifarm-2.0.x/hora2/20200430-153557/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(196): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#3 /var/platform/wikifarm-2.0.x/hora2/20200430-153557/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#4 /var/platform/cores/1_31/20200506-011200/includes/parser/Parser.php(3426): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string)
#5 /var/platform/cores/1_31/20200506-011200/includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#6 /var/platform/cores/1_31/20200506-011200/includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#7 /var/platform/cores/1_31/20200506-011200/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#8 /var/platform/cores/1_31/20200506-011200/includes/parser/Parser.php(1293): Parser->replaceVariables(string)
#9 /var/platform/cores/1_31/20200506-011200/includes/parser/Parser.php(443): Parser->internalParse(string)
#10 /var/platform/cores/1_31/20200506-011200/includes/content/WikitextContent.php(323): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#11 /var/platform/cores/1_31/20200506-011200/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#12 /var/platform/cores/1_31/20200506-011200/includes/poolcounter/PoolWorkArticleView.php(144): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#13 /var/platform/cores/1_31/20200506-011200/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#14 /var/platform/cores/1_31/20200506-011200/includes/page/Article.php(604): PoolCounterWork->execute()
#15 /var/platform/cores/1_31/20200506-011200/includes/actions/ViewAction.php(68): Article->view()
#16 /var/platform/cores/1_31/20200506-011200/includes/MediaWiki.php(500): ViewAction->show()
#17 /var/platform/cores/1_31/20200506-011200/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#18 /var/platform/cores/1_31/20200506-011200/includes/MediaWiki.php(861): MediaWiki->performRequest()
#19 /var/platform/cores/1_31/20200506-011200/includes/MediaWiki.php(524): MediaWiki->main()
#20 /var/platform/cores/1_31/20200506-011200/index.php(42): MediaWiki->run()
#21 {main}
```

The weird thing is that there's absolutely no reference to the ArchiMate class our ArchiMateStore class, so I don't know how the QuerySourceFactory comes up with initing that class.. 

Last but not least; the problem only exists while (update/upgrade) jobs are pending, but I really think this class shouldn't try to init abstract classes..

**Comment by YOUR1** [comment]
Additional debug information;

As said the extension adds the custom store as following:
```php
$wgAutoloadClasses['ArchiMateStore'] = $dir . 'query/ArchiMateStore.php';
$wgAutoloadClasses['ArchiMateQueryResult'] = $dir . 'query/ArchiMateQueryResult.php';
$wgAutoloadClasses['ArchiMateResultArray'] = $dir . 'query/ArchiMateResultArray.php';
$GLOBALS['smwgQuerySources'] = array(
    'archimate' => 'ArchiMateStore',
);```

We have a class named ArchiMate (that is abstract), perhaps the QuerySourceFactory also looks for the array key 'archimate' as defined above.

I can post the ArchiMateStore classes if needed.

**Comment by YOUR1** [comment]
After further debugging and testing, the problem was because we used a old way to inject extensions (`include <extension>/<extension>.php` instead `wfLoadExtension`). The extension wasn't injected properly, what caused smwgQuerySources not being set, thus SMW tried to automatically guess the class (ArchiMate) that should be used. 

I'm not sure that's the best way to go, since the problem above is one test case (automatically initing abstract classes..)

**Comment by jaideraf** [comment]
> the problem was because we used a old way to inject extensions (include <extension>/<extension>.php instead wfLoadExtension).

It seems the problem was solved and no one will probably get involved on the subject. I am closing this now, fell free to reopen if this still matters.
