### ISSUE TITLE
Database versions not outlined in compat matrix

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#478]
[doc/COMPATIBILITY.md](../blob/master/docs/COMPATIBILITY.md) currently does not provide info on which versions of MySQL, SQLSite and Postgres are supported.

**Comment by mwjames** [comment]
I think the latest compat doc does contain version numbers or?

**Comment by JeroenDeDauw** [comment]
Yes
