### ISSUE TITLE
Error with long texts

### ISSUE THREAD

**Issue by JaviRoch** [SemanticMediaWiki/SemanticMediaWiki#4784]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.31
- Pageforms: 4.4.1
- PHP version: 7.0.33
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.3

### Issue
Using pageforms and Semantic with a textarea input field, when filling the content in the form and exceeding 2727 characters, the page is left blank.

Code in form
`{{{field|Historia|input type=textarea|class=form-textarea}}}`

Code in template
`<p>[[Historia::{{{Historia|}}}]]</p>`

### Stack trace

Deprecated: Use of QuickTemplate::setRef was deprecated in MediaWiki 1.31. [Called from SkinChameleon::setupTemplateForOutput in /home/javier/www/culturacomunitaria/skins/chameleon/src/SkinChameleon.php at line 77] in /home/javier/www/culturacomunitaria/includes/debug/MWDebug.php on line 309

Notice: Did not find alias for special page 'UserBoardAdvanced'. Perhaps no aliases are defined for it? [Called from SpecialPageFactory::getLocalNameFor in /home/javier/www/culturacomunitaria/includes/specialpage/SpecialPageFactory.php at line 683] in /home/javier/www/culturacomunitaria/includes/debug/MWDebug.php on line 309

Deprecated: Use of MediaWikiI18N::translate was deprecated in MediaWiki 1.31. [Called from Skins\Chameleon\Components\SearchBar::getSearchButton in /home/javier/www/culturacomunitaria/skins/chameleon/src/Components/SearchBar.php at line 92] in /home/javier/www/culturacomunitaria/includes/debug/MWDebug.php on line 309

Thank you very much.

**Comment by akuckartz** [comment]
SMW 2.5 and MW 1.31 are not compatible:
https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.5.0

**Comment by mwjames** [comment]
> SMW version: 2.5.6

This Version is no longer supported. For details, see [0].

As for:

> Using pageforms and Semantic with a textarea input field, when filling the content in the form and exceeding 2727 characters, th

Using SMW without any intermediary as demonstrated by [1] will have no length issue you apparently observed which leads to the conclusion that extension `pageforms` is the reason for your troubles and you should report the issue with their ticket system.

As for:

> Deprecated: Use of MediaWikiI18N::translate was deprecated in MediaWiki 1.31. [Called from Skins\Chameleon\Components\SearchBar::getSearchButton

Those are unrelated to SMW.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md
[1] https://sandbox.semantic-mediawiki.org/wiki/Issue/4784

**Comment by kghbln** [comment]
@JaviRoch Thanks for reaching out to us. Actually you are not just having one issue but a potpourri of issues with multiple extension.

When it comes to storing more than 3000 characters to a property of type text, this works with compatible version. See [the example](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:20200516) so it come down to Page Forms and its "textarea" input type. I believe this should work with recent and compatible versions of MediaWiki, Semantic MediaWiki and Page Forms.

**Comment by kghbln** [comment]
Closing as invalid.
