### ISSUE TITLE
Property:Creation_date and other special properties not created

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#4787]
### Setup and configuration

- SMW version: 3.1.6
- MW version: 1.31.7
- PHP version:  7.3.14-1~deb10u1
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.22-MariaDB-0+deb10u1

### Issue
LocalSettings.php has:
```
# add support for special properties
# see https://www.semantic-mediawiki.org/wiki/Help:$smwgPageSpecialProperties
# Modification date
$smwgPageSpecialProperties[] = '_MDAT';
# Creation date
$smwgPageSpecialProperties[] = '_CDAT';
# Is a new page
$smwgPageSpecialProperties[] = '_NEWP';
# Last editor is
$smwgPageSpecialProperties[] = '_LEDT';
# Media type
$smwgPageSpecialProperties[] = '_MEDIA';
# MIME type
$smwgPageSpecialProperties[] = '_MIME';
```

### Steps to reproduce
MediaWiki's maintenance script "update.php" (MediaWiki.org) followed by the maintenance script "rebuildData.php" have been run after changing the setting of this configuration parameter. 

The properties were not created. E.g. Property:Creation_date is not available.

How can this be debugged?

**Comment by kghbln** [comment]
You ran "rebuildData.php" after changing "LocalSettings.php" and running "update.php"?

**Comment by WolfgangFahl** [comment]
@kghbln  - thx for looking into this I did and it did not have the desired effect. How could i debug why that is so?

**Comment by kghbln** [comment]
I have no clue why this is not working for you. I personally use the array_merge approach when setting these but I do not see a difference doing so.

**Comment by WolfgangFahl** [comment]
I was referencing the properties with Property:_CDAT which was possible in the past. Now only the long form e.g. "Creation Date" is available.
