### ISSUE TITLE
Invalid argument ... FieldList.php on line 86

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4790]
Warning: Invalid argument supplied for foreach() in /var/www/html/w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/FieldList.php on line 86

SMW master, MW 1.34.1

**Comment by bertrandgorge** [comment]
Also reproduced on SMW 3.2.0.

Same as issue #4865

**Comment by kghbln** [comment]
Oops, this one is older than the duplicate issue. :(
