### ISSUE TITLE
undefined function during install

### ISSUE THREAD

**Issue by seth2740** [SemanticMediaWiki/SemanticMediaWiki#4794]
Built a Fedora 32 system and installed apache (2.4.43) /php (7.4.6) /mediawiki (1.33.3) from the regular repo.  Went through the MediaWiki install selecting all features.  At the finalization page, told it to install and then it threw up.  Posted this in the MediaWiki forum and was told to notify SemanticMediaWiki maintainers.

```
[XukdTH7z706fDeNemJRv-QAAABU] /wiki/mw-config/index.php?page=Install Error from line 464 of /usr/share/mediawiki/extensions/SemanticMediaWiki/includes/SMW_Setup.php: Call to undefined function wfProfileIn()

Backtrace:

#0 /usr/share/mediawiki/extensions/SemanticMediaWiki/includes/SMW_Setup.php(426): smwfInitContentLanguage()
#1 /usr/share/mediawiki/extensions/SemanticMediaWiki/SMW_Settings.php(95): smwfInitNamespaces()
#2 /usr/share/mediawiki/extensions/SemanticMediaWiki/SemanticMediaWiki.php(74): require_once(string)
#3 /usr/share/mediawiki/includes/installer/Installer.php(1497): require_once(string)
#4 /usr/share/mediawiki/includes/installer/Installer.php(1597): Installer->includeExtensions()
#5 /usr/share/mediawiki/includes/installer/WebInstallerInstall.php(44): Installer->performInstallation()
#6 /usr/share/mediawiki/includes/installer/WebInstaller.php(264): WebInstallerInstall->execute()
#7 /var/www/wiki/mw-config/index.php(80): WebInstaller->execute()
#8 /var/www/wiki/mw-config/index.php(38): wfInstallerMain()
#9 {main}
```

**Comment by kghbln** [comment]
@seth2740 Thanks for reporting. Which version of SMW are you trying to intall? Moreover please note that Semantic MediaWiki cannot be installed via the web installer provided by MediaWiki.

**Comment by seth2740** [comment]
It was installed from the Fedora repo.

```
[root@oloroso share]# rpm -qa | grep -i semantic
mediawiki-semantic-1.8.0.4-13.fc32.noarch
```

**Comment by kghbln** [comment]
> It was installed from the Fedora repo.

This version was released 8 years ago and abandoned 6 years ago, i.e. Fedora provides an heavily outdated version of Semantic MediaWiki which will not work under any circumstances. Since you are using PHP 7.4 you also need to use master since SMW 3.1 does not fully support PHP 7.4. You can do so using these [installation instructions](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md)
