### ISSUE TITLE
SQLStore / rebuildData + refreshData memory leaks

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#480]
[Email](http://wikimedia.7.x6.nabble.com/Using-Fuseki-tp5033271.html) from Stephan where he wrote:

> Well, apart from that pesky memory leak issue [1] causing rebuildData.php to bail out every few thousand pages.

**Comment by kghbln** [comment]
My No. 1 from January 2015: 440163 IDs (1141680 values), Memory: 667858080, 33455,35 sec with PHP 5.4

**Comment by mwjames** [comment]
Nothing new here, you can try to use `--shallow-update` but aside from that not much actionable on this as long as the `Parser` can not household its memory usage.
