### ISSUE TITLE
TypeError from line 144 of /var/www/html/includes/parser/ParserCache.php

### ISSUE THREAD

**Issue by diablo6006** [SemanticMediaWiki/SemanticMediaWiki#4822]
### Setup and configuration

- SMW version:3.1
- MW version:1.35
- PHP version:7.4
- DB system (MySQL, Blazegraph, etc.) and version: mariadb 10

_Note that it is **required** to provide the setup and configuration information. If you believe to have detected a regression after updating your software please also provide information about your previous setup as well. **In any case only this information will enable us to allocate appropriate review time.** Thank you for you help._

### Issue
`_Please describe the issue as best as you can and also fill in the following two sections if applicable._
`
### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
TypeError from line 144 of /var/www/html/includes/parser/ParserCache.php: Argument 1 passed to ParserCache::getETag() must be an instance of WikiPage, instance of Article given, called in /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php on line 646

Backtrace:

#0 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(646): ParserCache->getETag()
#1 /var/www/html/includes/HookContainer/HookContainer.php(319): SMW\MediaWiki\Hooks->onArticleViewHeader()
#2 /var/www/html/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#3 /var/www/html/includes/HookContainer/HookRunner.php(887): MediaWiki\HookContainer\HookContainer->run()
#4 /var/www/html/includes/page/Article.php(715): MediaWiki\HookContainer\HookRunner->onArticleViewHeader()
#5 /var/www/html/includes/actions/ViewAction.php(74): Article->view()
#6 /var/www/html/includes/MediaWiki.php(527): ViewAction->show()
#7 /var/www/html/includes/MediaWiki.php(313): MediaWiki->performAction()
#8 /var/www/html/includes/MediaWiki.php(986): MediaWiki->performRequest()
#9 /var/www/html/includes/MediaWiki.php(543): MediaWiki->main()
#10 /var/www/html/index.php(47): MediaWiki->run()
#11 {main}```

### Steps to reproduce
_It is recommend to use the [sandbox](https://sandbox.semantic-mediawiki.org) to demonstrate the observed issue, otherwise provide us with a simple reproducible use case._

**Comment by jaideraf** [comment]
SWM 3.1 is not compatible with PHP 7.4, see: [Compatibility](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4822)

**Comment by diablo6006** [comment]
I've tried that using the user guide here:
`https://www.semantic-mediawiki.org/wiki/Help:Installation/Quick_guide`
by adding this line to composer.json
`                  "mediawiki/semantic-media-wiki": "~3.0"
`
then with i changed it to: "~3.1"
then wiki pages are working fine, but when i tried to do some changes in template, module, category, then this error comes.

by the the way, i did all the steps, including the maintenance script of semantic mediawiki, because it's not a fresh installation.

how to get version 3.2 using composer, when i tried to change to "mediawiki/semantic-media-wiki": "~3.2", it didn't works,
`Problem 1
    - The requested package mediawiki/semantic-media-wiki ~3.2 is satisfiable by mediawiki/semantic-media-wiki[3.2.x-dev] but these conflict with your requirements or minimum-stability.`

thank you

**Comment by akuckartz** [comment]
SMW 3.1 is not compatible with MediaWiki 1.35 and MW 1.35 is not yet released. SMW 3.2 also has not been released.

**Comment by diablo6006** [comment]
thank you for clarifying this.
