### ISSUE TITLE
Pass tests for MW 1.35

### ISSUE THREAD

**Issue by akuckartz** [SemanticMediaWiki/SemanticMediaWiki#4824]
See https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki for MW=master

**Comment by akuckartz** [comment]
See #4549

**Comment by kghbln** [comment]
Did you have time yet to do the matching?

**Comment by akuckartz** [comment]
@kghbln I will try to do that this weekend. The failures seem to be caused by deprecations.

**Comment by kghbln** [comment]
Really cool. since I am short in time.

**Comment by kghbln** [comment]
Split into @gesinn-it with separate issues
