### ISSUE TITLE
What to do with closed issues tagged "seeks developer"

### ISSUE THREAD

**Issue by akuckartz** [SemanticMediaWiki/SemanticMediaWiki#4840]
There are currently 63 of such issues. I propose to either reopen them or removing the "seeks developer" tag.

**Comment by jaideraf** [comment]
I don't see a benefit of doing that. The feature requests of those closed bugs will not magically "inspire" a developer. If a developer wants to introduce a new feature, she/he will propose it and, ideally, develop the new feature. If there is no developer interested in develop that feature, it is not going to happen. A lot of open bug reports only make it difficult to manage the really bugs in the code. 

Also, MWJames and Karsten works hard to make SMW bug reports "clean" and towards an objective. I think it's a little disrespectful (not you, but this idea) to propose a change that will disturb such state.

If I see a GitHub repository with ~500 open bug reports, I think something like: "the software must be a crap, look at how much open bug reports they have", or "there must be crazy people opening so much bugs... no way one or two developers can deal with that amount of bugs".

**Comment by akuckartz** [comment]
@jaideraf
> A lot of open bug reports only make it difficult to manage the really bugs in the code. ...  Also, MWJames and Karsten work hard to make SMW bug reports "clean" and towards an objective.

Issues about bugs are tagged as "bug".

> If I see a GitHub repository with ~500 open bug reports ...

This issue is about currently 63 issues which are (at least mostly) not bugs. Combined with 77 currently open issues the sum is 140.

**Comment by JeroenDeDauw** [comment]
There is some benefit in having a more curated list of issues, rather than a big pile with mostly random ideas someone once had that _might_ be useful for _some_ use case. There are actually people that recommend throwing away product backlogs every so often, since important issues will come back anyway. This approach avoids spending a lot of time on grooming the backlog. Sure, the issues here are not a backlog of a product team, but it is similar enough.

**Comment by JeroenDeDauw** [comment]
I'd be real nice to somehow get a prioritized list of issues based on what people actually want/need. This https://twitter.com/SemanticMW/status/1302036673568665601 gives only _some_ indication.

Then again, like with the linked Twitter poll, we'll likely get mostly super advanced users participating, warping the prioritization away from what most users actually need and from what would make the software more successful.

**Comment by jaideraf** [comment]
This issue can be closed.
