### ISSUE TITLE
Why was the SMW::DataUpdater::ContentProcessor documentation removed?

### ISSUE THREAD

**Issue by Absotively** [SemanticMediaWiki/SemanticMediaWiki#4846]
The documentation for the SMW::DataUpdater::ContentProcessor hook was removed from docs/technical/hooks.md in commit 3bf4165. I can't find any information about why it was removed.

Was the documentation removed accidentally? Or is this hook no longer supported?

**Comment by JeroenDeDauw** [comment]
I have no idea and it might be quite some time before James replies.

Are you using this hook?

**Comment by Absotively** [comment]
Not at the moment, but I'm considering using it.

**Comment by kghbln** [comment]
It appears to be an interesting hooks since we go the same question again. Perhaps the revision that removed the docu will tell.

**Comment by kghbln** [comment]
This one was added with 3.0 so it is a fairly new one.

**Comment by jaideraf** [comment]
I think no one will answer that question. So closing it by now.
