### ISSUE TITLE
Negative Timezone leads to warning: contains more than three components required for a date interpretation.

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#4848]
### Setup

- SMW version: 2.5.8
- MW version: 1.27.3
- PHP version: 7.2.24
- DB system: MySQL 5.7.31

### Issue
Trying to set a data type property with the value: 2020-09-15 03:42:20 -0500

Gives the warning:
![grafik](https://user-images.githubusercontent.com/1336221/93739349-5bd6a700-fbe8-11ea-81a1-5b9750f127e9.png)
"2020-09-15 03:42:20 -0500" contains more than three components required for a date interpretation.

The data comes from a script I am using to document git log entries
```
git --no-pager log --reverse --pretty=format:{{commit'|'host=$host'|'path=${path}'|'project=${project}'|'subject=%s'|'name=%cn'|'date=%ci'|'hash=%h'|'storemode=subobject'|'viewmode=line}}
```

So it would be great not to have to modify the script to work around the negative timezone not being handled.

**Comment by akuckartz** [comment]
The MW and SMW versions are somewhat old. What happens using more current versions?

**Comment by WolfgangFahl** [comment]
MW 1.35.0 + SMW 3.2.0 does not have the problem

**Comment by kghbln** [comment]
Let's put it like this: Appears to work on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/4848)
