### ISSUE TITLE
Did anybody test a clean installation of SMW 3.2 with MW 1.35?

### ISSUE THREAD

**Issue by fandjelo** [SemanticMediaWiki/SemanticMediaWiki#4854]
Hi I'm new to SMW and currently evaluating it for a big hardware database project with around 20k parts. May be I'm doing something wrong, but I just can't setup SMW for testing. I'm trying to setup latest MW 1.35 and SMW 3.2. The installation is made step by step, as described in the SMW howto and seems to work flawlessly.

However after the installation weird things happen. First of all there is no "Special:Browse" link in the toolbox (ok, I found this bug report already #4831). There is no "create property" in the special pages. If I add a property by hand, as described in the documentation, it is not recognized properly. SMW shows it as property, but for example Number is not treated as Number in the usage, I mean, I can click on it and MW wants me to create a page for it.

This are just two examples, there are a lot of strange issues, Page Forms crashes, many things behave not in the same way as described in the documentation. SMW is very complicated to use when all the "special" links are missing. Is there something in the installation howto, what has to be updated and I missed during my installation? Did something change with version 3.2 of SMW? Did something heavy change in MW 1.35?

Any help is highly appreciated.

**Comment by JeroenDeDauw** [comment]
SMW has not been well tested with MediaWiki 1.35 yet. So while most things should work, you might indeed run into some issues that have not been fixed or documented yet.

A good amount of things changed between SMW 3.1 and 3.2, though unfortunately this was not documented well. If things no longer work, my suspicion and hope is that this is due to compatibility issues with MediaWiki 1.35.

If you want to use MW 1.35, then SMW 3.2 is definitely the way to go. Or a development version of SMW. Using 3.1 will get you a lot more compatibility problems.

What is the Page Forms issue?

**Comment by fandjelo** [comment]
Well, unfortunately, either I do something really wrong, or SMW 3.2 seems not to be usable with MW 1.35. I can't create properties, the visualization seem not to be right. On some places the SMW properties are not recognized as is and MW want's me to create pages for it. The Page Forms gives me strange error here and there. You can see it for example, if you click on Special:CreateProperty in "Page Forms" special block. I currently don't even know, what it means, but the error seems to come constantly there:
[a116715ca301656347f7bc0d] 2020-10-05 07:07:20: Fatal exception of type "Error"

**Comment by fandjelo** [comment]
Here, I got the backtrace of the error:
[ecdaf359aaefcd245ced9f7f] /necroware/uh19wiki/index.php?title=Special:CreateProperty Error from line 99 of /srv/http/public/necroware/uh19wiki/extensions/PageForms/specials/PF_CreateProperty.php: Call to a member function getDatatypeLabels() on null

Backtrace:

#0 /srv/http/public/necroware/uh19wiki/extensions/PageForms/specials/PF_CreateProperty.php(22): PFCreateProperty->printCreatePropertyForm()
#1 /srv/http/public/necroware/uh19wiki/includes/specialpage/SpecialPage.php(600): PFCreateProperty->execute()
#2 /srv/http/public/necroware/uh19wiki/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#3 /srv/http/public/necroware/uh19wiki/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#4 /srv/http/public/necroware/uh19wiki/includes/MediaWiki.php(940): MediaWiki->performRequest()
#5 /srv/http/public/necroware/uh19wiki/includes/MediaWiki.php(543): MediaWiki->main()
#6 /srv/http/public/necroware/uh19wiki/index.php(53): MediaWiki->run()
#7 /srv/http/public/necroware/uh19wiki/index.php(46): wfIndexMain()
#8 {main}

**Comment by Nikerabbit** [comment]
That page forms issue has been fixed in latest (currently unreleased) version of Page Forms: https://phabricator.wikimedia.org/T249172

**Comment by fandjelo** [comment]
Ok, I'll try to use unreleased version and see how far I'll come. I guess, the other problems will not suddenly disappear in SMW whatsoever.... but may be I can then get a better overview.....

**Comment by fandjelo** [comment]
Ok, with the fixed version of PageForms most of the things seem to work. Only annoying thing is the missing Special:Browse in the toolbox, but everything seem to be reachable at least with a workaround now. Thank you for the help. At least it is sufficient to evaluate SMW now.

**Comment by JeroenDeDauw** [comment]
Hah, guess you did not get a stellar first impression.
