### ISSUE TITLE
`Browse Properties` Button is not showing on MW 1.35 Vector Skin

### ISSUE THREAD

**Issue by MPThLee** [SemanticMediaWiki/SemanticMediaWiki#4866]
### Setup

- SMW version: 3.2.0
- MW version: 1.35.0
- PHP version: PHP 7.4.11
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.5.6

### Issue
`Browse Properties` Button on Toolbox Sidebar is now showing up after upgrade mediawiki to 1.35

This is on 1.31.10/3.2.0 (semantic-mediawiki.org)
![image](https://user-images.githubusercontent.com/26970092/96730251-f5b09000-13f0-11eb-856f-056356b92d86.png)

This is on 1.35.0-rc.2/3.2.0 (sandbox.semantic-mediawiki.org)
![image](https://user-images.githubusercontent.com/26970092/96730429-1aa50300-13f1-11eb-8cb6-8415ad6531cc.png)

I don't know this is intended or not. Please close this issue if it's not error.

There's no stacktrace about this. or somewhere that not logged on my side.

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Install semantic mediawiki to MediaWiki 1.35 and done.

**Comment by jaideraf** [comment]
It was a bug (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4831), and it was fixed thanks to @StarHeartHunt (https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4856). Thanks for reporting it.

**Comment by kghbln** [comment]
Thanks for reporting. Indeed this was rather annoying.
