### ISSUE TITLE
Do not write objects into ExtensionData

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/SemanticMediaWiki#4868]
As part of [ParserCache / RESTBase / Parsoid integration](https://phabricator.wikimedia.org/T250500), the ParserCache serialization format is being changed to JSON. This requires that an objects that are being written to ExtensionData currently be converted to JSON serialization.  It appears that there are places in [ParserData.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/ParserData.php) and perhaps elsewhere where this must be fixed.

We plan to submit a patch to address this.

**Comment by cscott** [comment]
There have been some fixes/improvements to JSON serialization since this was filed; though see T313452.

**Comment by JeroenDeDauw** [comment]
https://phabricator.wikimedia.org/T313452

**Comment by hexmode** [comment]
Looks like this was superseded with #5285.  Also, discussed this with Cindy and she said she probably wouldn't use this.

**Comment by hexmode** [comment]
Should have closed as resolved since #5285 has apparently fixed it.
