### ISSUE TITLE
SMW 4.0

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4870]
Miletone: https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestone/41

Release notes: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-4.0.0.md#semantic-mediawiki-400

**Comment by JeroenDeDauw** [comment]
@kghbln my current thinking is that it probably makes sense to drop support for MW older than 1.35 on master / for SMW 4.0. Given limited volunteer time to deal with MW 1.35 issues (*), 1.35 being an LTS and little in the way of feature development happening in SMW at the moment, this seems like a good deal. It is what I am doing for Maps.

(*) Dealing with those issues is easier if you do not need to stay compatible with older versions

**Comment by kghbln** [comment]
We just have to make sure that both releases overlap for the support of the latest LTS of MW, i.e. 1.35. Since both 3.2 and 4.0 will support 1.35 I have no objections. Probably we should still do MW 1.34 since this is currently supported though this depends on when we do the 4.0 release.

**Comment by JeroenDeDauw** [comment]
> Probably we should still do MW 1.34 since this is currently supported though this depends on when we do the 4.0 release.

The way I look at things this actually does not make sense. If we release in a year and don't support 1.34, or release now and don't support it, either way, people using 1.34 are not affected. What is different is that people using 1.35 get a new release sooner. Having a release optimized for 1.35 soon is additive. It does not take away from the recent 3.2 release. You could think of it as a 1.35 optimized version of SMW 3.2.

**Comment by JeroenDeDauw** [comment]
We have a whole bunch of compat fixes on master. [200 commits](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.2.x...master). So I think it makes sense to get the 4.0.0 release out soon. It is much better for users using MW 35 or later than 3.2.3.

At the moment it is not clear to me to what degree SMW is compatible with MW 36 and 37, or with PHP 8 and 8.1. The tests are all run with MW 35. Would be fantastic to get the tests to run on GitHub Actions with all versions: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5089

**Comment by kghbln** [comment]
> We have a whole bunch of compat fixes on master. 200 commits. So I think it makes sense to get the 4.0.0 release out soon. It is much better for users using MW 35 or later than 3.2.3.

Indeed, I agree here.

> At the moment it is not clear to me to what degree SMW is compatible with MW 36 and 37, or with PHP 8 and 8.1. The tests are all run with MW 35. Would be fantastic to get the tests to run on GitHub Actions with all versions: #5089

This is true though I suspect that it will not be worse for 1.36 than what 3.2.3 is for 1.35.

**Comment by Nikerabbit** [comment]
Translatewiki.net is currently running 1.36 with SMW from the master branch. Patches for last two deprecation warnings we found have been merged. We're planning to upgrade to 1.37 this week and see if we find anything new.

**Comment by kghbln** [comment]
Thanks for your feedback. This at least assures that fatal errors and such will not be encountered. You are however not a heavy user of SMW when it comes to the features provided.  Hopefully this will not be a sad story for users.

**Comment by JeroenDeDauw** [comment]
Tagged

**Comment by kghbln** [comment]
Wiki updated
