### ISSUE TITLE
smw-category-invalid-redirect-target ?

### ISSUE THREAD

**Issue by MvGulik** [SemanticMediaWiki/SemanticMediaWiki#4875]
I'm seeing this ...
> "smw-category-invalid-redirect-target": "Category \"$1\" contains an invalid redirect target to a non-category namespace."

... error at the SMW "Processing error list" page.

I know what it is that I'm doing, that is triggering this error.

What I don't get is:
- Why is SMW seeing this as a problem ?
and
- What SMW problem's might I encounter by doing this.

`MW 1.31.0 with SMW 3.1.5` just in case it might matter.

**Comment by MvGulik** [comment]
Mmm ...

After running into the [Help:Inferencing](https://www.semantic-mediawiki.org/wiki/Help:Inferencing#Equality_of_pages:_redirects) page.
And reading the next part.
>Redirects between two different namespaces, such as redirects from normal pages to properties, properties to categories, etc. are not supported in a special semantic way. They still create normal MediaWiki redirect pages but nothing else.

It feels to me its more a warning than a error. in that:
* SMW seems to assume it must have been a none intended redirect usage on the user.
and
* The related redirect target will be ignored as such by SMW. Or, there will be no unexpected SMW side effects.

Seems I might have just answered my own question.
(_presuming I answered it correctly. Time will tell, or not of course._)

**Comment by kghbln** [comment]
> Seems I might have just answered my own question.

I believe you did. It is a warning preventing you from having false expectations.

**Comment by MvGulik** [comment]
Like to add to this that I think that "warnings" should not be presented under a "error" header.
And that it would be nice is there was some way to make SMW bypass/ignore them (_if there is I have not fount it yet of course_). (_in my case I got a lot of those warnings, and there effectively bloating the error list so that other real(kinda) errors are overshadowed_)

**Comment by MvGulik** [comment]
Seems I was a bit premature on the "no unexpected SMW side effects".

Seems I somehow managed to trow SMW of balance. (_while adding such a non-category redirect from a category_)

Some related #ask: call first went from 80+ items to zero.
And although, after some debug edits, it started to showing some items again (_those included in some other related category_).
It still refused to pick up the rest of those 80+ items.

Seems I have to hit refresh on those other 70+ pages. :-(

**Comment by MvGulik** [comment]
Confirming: A SMW category-ask will not return any data if that category has a non-category redirect from a category.

:-(
