### ISSUE TITLE
Missing redirect annotations ?

### ISSUE THREAD

**Issue by MvGulik** [SemanticMediaWiki/SemanticMediaWiki#4876]
I got a redirect-page that's showing up in the special "_Missing redirect annotations_" SMW page.
The page has the following content (`<relative>`):
```
#REDIRECT [[<other page name, also in main-space>]]

<br>...some text... {{<template-call>|option|other anonymous option}}.
```
Why would this page show up as a "_Missing redirect annotations_" case ?
(_There are plenty of other plain/bare-redirect pages that do not show up as "Missing redirect annotations" cases._)
(_Actually, that particular page is the only page that is showing up in the "Missing redirect annotations" page._)

What might be the reason why manual purging is not helping to change this situation ?
(_as advised on the "Missing redirect annotations" page itself._)
(_Manual purged both the source and target page (no effect)._)

`MW 1.31.0 with SMW 3.1.5` just in case it might matter.
(_I'm just a wiki admin, ie: not system owner or bureaucrat._) 

+That template call makes some SMW #ask: calls (_although those are unrelated to the page in question_).

**Comment by MvGulik** [comment]
Guess nobody knows, or don't like to tell.

Considering this is the second case where SMW is generating problems on (_otherwise completely valid MW_) \#Redirect usage, I do wondering why SMW made the decision to piggyback on the MW \#Redirect feature.
In my view its a bit more than just piggy-bagging at this point, if one starts to put limitation on otherwise completely valid basic MW feature usage (_with the inevitable SMW generated issues and problems_) it becomes more a case of hijacking a basic MW feature (_without providing a way around SMW demands in this matter_).

Closing

**Comment by akuckartz** [comment]
Why was this issue closed?

**Comment by MvGulik** [comment]
> Why was this issue closed?

I don't like to keep a question open (_that I posted/initiated_), when I have lost interest in getting a potential answer from the other side. Ergo: I close it, and move on. (_varies per person/site/etc of course_)

Figure its one step away from not caring to close it either, and just forgetting about it.
Needles to say that that would be indistinguishable from the general default. ... 

(_Anyone that has the same question can re-open/use this one if they like, or open a new-topic for it (the latter probably works better!_).
