### ISSUE TITLE
BaseTemplateToolbox deprecated in 1.35 with planned 1.36 removal

### ISSUE THREAD

**Issue by jdlrobson** [SemanticMediaWiki/SemanticMediaWiki#4877]
### Issue

This BaseTemplateToolbox hook has been deprecated and I've detected it as being present in the SemanticMediaWiki codebase. It should be a straightforward migration,  as it can be substituted safely with the SidebarBeforeOutput hook.

This is tracked on Phabricator in https://phabricator.wikimedia.org/T256509 
Please let me know if you have any further questions.

**Comment by Seb35** [comment]
See issue #4831 and PR #4856 to be released in SMW 3.2.1.

If the old hook is kept for older MW versions then this issue could be considered fixed.

**Comment by akuckartz** [comment]
> See issue #4831 and PR #4856 to be released in SMW 3.2.1.

Both are closed now.

> If the old hook is kept for older MW versions then this issue could be considered fixed.

Can this issue be closed?

**Comment by kghbln** [comment]
`BaseTemplateToolbox` is still in the current codebase, if I understand correctly for backwards compatibility with older versions of MW, i.e. 1.34 and earlier. Thus we still need to remove it for the 4.0.0 release.

**Comment by Abijeet** [comment]
This was fixed in #5067. I think it can be closed now.
