### ISSUE TITLE
Message "This message will disappear after all relevant tasks have been resolved." is not disappearing though all tasks have been completed.

### ISSUE THREAD

**Issue by jkpubsrc** [SemanticMediaWiki/SemanticMediaWiki#4884]
The situation:

* I installed a new MW extension
* I uninstalled the extension
* problem: the MW then complained that there would be no SMW upgrade key
* I run MW maintenance scripts to rebuild the database
* now I get MW pages again, but now there is the following message on top of every page and it is not going away:

```
Semantic MediaWiki
This message will disappear after all relevant tasks have been resolved.
The installation or update of Semantic MediaWiki has not yet been fully completed. An administrator or another person with administrator rights must therefore perform the following tasks in order to avoid data inconsistencies before users of the wiki change existing content or create additional content:
```

(This message has been translated into English.)

And that's it. No additional information beyond the colon at the end of the message.

What is wrong here? How can I make this message disappear?

Versions:

* MW 1.33.0
* SMW 3.2.0

**Comment by jaideraf** [comment]
In my case, sometimes, following this message comes a message asking to run "`updateEntityCollation.php`" which is under "`...extensions/SemanticMediaWiki/maintenance`". You could try to run it.

**Comment by saerdnaer** [comment]
Run into the same problem, with the german locale it is even worse:

![image](https://user-images.githubusercontent.com/40266/99547239-9a55cb80-29b7-11eb-889c-c61a6c44c1ec.png)

**Comment by jaideraf** [comment]
Good. The message in your print also asks you to run `updateEntityCountMap.php`.

**Comment by saerdnaer** [comment]
@jaideraf Sure, but it should not be necessary to switch the locale to english, right?

**Comment by kghbln** [comment]
Admittedly I never had this issue. So you need to run "updateEntityCountMap.php" or "updateEntityCollation.php"? I would have guessed the first but ....

**Comment by jaideraf** [comment]
@saerdnaer Yes, sorry, I thought you were the same person that opened this issue. Maybe some translations is lacking in your languages:
https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&language=pt-br&group=mwgithub-semanticmediawiki#sortable:3=desc

**Comment by saerdnaer** [comment]
@jaideraf See update above. Thanks!

**Comment by jkpubsrc** [comment]
Data bases get corrupted, messages are not shown, and you're labeling that as a "question"??? Sorry, but that sounds a bit as joke.

**Comment by jkpubsrc** [comment]
> Running `php extensions/SemanticMediaWiki/maintenance/updateEntityCollation.php` fixed the issue for me.

Thanks for you mentioning this.

Running `updateEntityCollation.php` did not resolve the issue. No change at all.

After switching to `en` I was still seeing an error message. But now it referred to a different page listing pending tasks. Here I was told to run `updateEntityCountMap.php` (which seem to not be pending as I have to run this script manually). But now after running `updateEntityCountMap.php` everything seems to be fine again.

Thank you all very very much for providing me with the crucial hint to resolve this!
