### ISSUE TITLE
No display of the link to Special:Browse in the toolbox

### ISSUE THREAD

**Issue by Megajoul** [SemanticMediaWiki/SemanticMediaWiki#4895]
The toolbox of the content pages doesn't show the link to the special page "Browse" although `$smwgBrowseFeatures` is set to `SMW_BROWSE_TLINK | SMW_BROWSE_SHOW_INCOMING | SMW_BROWSE_SHOW_GROUP | SMW_BROWSE_USE_API;`

MW : 1.35.0
SMW : 3.2.0

**Comment by kghbln** [comment]
Please upgrade to SMW 3.2.2 which ships the fix!
