### ISSUE TITLE
Special property Page creator

### ISSUE THREAD

**Issue by Megajoul** [SemanticMediaWiki/SemanticMediaWiki#4896]
The `Page creator` special property does not seem to be predefined although the reference page states the contrary :  https://www.semantic-mediawiki.org/wiki/Property:Page_creator

Moreover, it is not listed in https://www.semantic-mediawiki.org/wiki/Help:Special_properties

It's a pity! This property would be very useful...

**Comment by JeroenDeDauw** [comment]
Do you have Semantic Extra Special Properties installed?

**Comment by Megajoul** [comment]
Hello Jeroen,
Thanks for your reply. I've just installed the Semantic Extra Special Properties extension and followed the installation instructions. However I get the following notice : 
`Notice: Undefined index: wgDisableCounters in /var/www/mediawiki/extensions/SemanticExtraSpecialProperties/SemanticExtraSpecialProperties.php on line 124`
Moreover every page with javascript (VisualEditor, autocompletion...) doesn't seem to work anymore so that I can't check with Special:Browse if the SEPS _CUSER is recorded.
Oh I've forgotten to specify that my MW version is 1.35...

**Comment by kghbln** [comment]
Do you have the HitCounters extension installed?

**Comment by Megajoul** [comment]
No.

**Comment by kghbln** [comment]
Could you post the config for SESP?

**Comment by kghbln** [comment]
Turns out that https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4896#issuecomment-744698761 is a bug caused by MW 1.35 which requires SESP to be adapted. See https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/147

**Comment by Megajoul** [comment]
Thank you Karsten. The workaround seems to work for me.

**Comment by kghbln** [comment]
> Thank you Karsten. The workaround seems to work for me.

Great to read!
