### ISSUE TITLE
Examiner doesn't finish on pages that have a " (double quote) in the name 

### ISSUE THREAD

**Issue by kuality** [SemanticMediaWiki/SemanticMediaWiki#4899]
I have a [wiki page](https://ccmdb.kuality.ca/index.php?title=Change_of_GRA_location_names_from_%22our%22_names_to_EPR/Cognos_names) on which the entity examination does not seem to complete, i.e. the three pulsing bars just keep pulsing even if the page has been rendered for half an hour: 

I copied the content of the page to a new page, no problem. Then I renamed the new page to have " in the name and the examiner again doesn't finish.

See also [discussion page] (https://www.semantic-mediawiki.org/wiki/Thread:Help_talk:Entity_examinations/Entity_examination_seems_to_not_complete_on_a_page)

MW 1.35.0 SMW 3.2.0

**Comment by Nikerabbit** [comment]
Since you mention `"` I believe #4849 is another symptom of the same issue, cause being invalid handling of quotes in page names.

**Comment by kghbln** [comment]
@kuality Thanks for reporting and @Nikerabbit for providing a reference to an issue that appear to be same!

**Comment by kghbln** [comment]
Indeed. I just did a field test. Fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4901 to be shipped with SMW 3.2.3

**Comment by kghbln** [comment]
[sandbox test page](https://sandbox.semantic-mediawiki.org/wiki/Issue/4899_%22test%22_page)
