### ISSUE TITLE
"Creating a BEACON file with GND numbers" example is invalid

### ISSUE THREAD

**Issue by dranitski** [SemanticMediaWiki/SemanticMediaWiki#4900]
Here in wiki https://www.semantic-mediawiki.org/wiki/Help:Templatefile_format **Creating a BEACON file with GND numbers** section example is broken - it doest really return any data in _Result: beacon export__

[beacon (1).txt](https://github.com/SemanticMediaWiki/SemanticMediaWiki/files/5702624/beacon.1.txt)

result is

```
 #FORMAT: BEACON
 #PREFIX: http://d-nb.info/gnd/
 #TARGET: https://www.semantic-mediawiki.org/w/index.php?title=
 #VERSION: 0.1
 #HOMEPAGE: https://www.semantic-mediawiki.org/w/index.php?title=Help:BEACON
 #FEED: https://www.semantic-mediawiki.org/w/index.php?title=BEACON&action=render
 #LINK: http://www.w3.org/2000/01/rdf-schema#seeAlso
 #INSTITUTION: Semantic MediaWiki
 #MESSAGE: Person test data in Semantic MediaWiki
 #TIMESTAMP: 20201216121752
 #UPDATE: always

 ||
 ||
 ```

**Comment by kghbln** [comment]
Thanks for reporting.

@krabina I believe you are a heavy user of the templatefile format. Does it work you and if it does it will be cool if you could have a peep at the docu and see what goes wrong with the exampes?

**Comment by krabina** [comment]
Not yet. I was the reason why it was created, because I used [somewhat of a hack](https://www.semantic-mediawiki.org/wiki/Help:BEACON#Implementation_prior_to_SMW_3.x) in order to provide a BEACON file before templatefile format was there.

But I am planning to make use of the format soon and will report how it goes here.

**Comment by jaideraf** [comment]
Hi, I fixed the example by altering named arguments to numbered arguments. See the differences:
https://www.semantic-mediawiki.org/w/index.php?title=Help%3ATemplatefile_format&type=revision&diff=80165&oldid=76177
The template page:
https://www.semantic-mediawiki.org/w/index.php?title=Template%3ABEACON&type=revision&diff=80164&oldid=66352

I don't know the reason why it is not worinking with named arguments anymore.

**Comment by kghbln** [comment]
@jaideraf Thanks for looking at this and fixing the example. Did not have time to look at it at all so you were the white knight here. `template arguments` was removed with the list format overhaul which obviously came after the page was created but before 3.0 was released. `named args` is our new friend here.

@krabina Thanks for the feedback. I really figured you were happily using it already.
 
> But I am planning to make use of the format soon and will report how it goes here.

Go for it. :)

@dranitski I believe you can finally move forward now.

**Comment by kghbln** [comment]
> `named args` is our new friend here.

https://www.semantic-mediawiki.org/wiki/Help:Templatefile_format/parameter_named_args
