### ISSUE TITLE
Avoid using xdebug_is_enabled

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4904]
XDebug 3.x removed `xdebug_is_enabled()` with the following comment: ["Has been removed, but was never originally documented or supported."](https://xdebug.org/docs/upgrade_guide#Changes-to-Functions).

Usages:
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/f8beb3ce01c7dcca680e774e1a9ea5af47325d51/tests/phpUnitEnvironment.php#L49

**Comment by gesinn-it** [comment]
idea: change to something like `(extension_loaded( 'xdebug' ) && (function_exists('xdebug_is_enabled') || function_exists('xdebug_info'))`

**Comment by gesinn-it** [comment]
@kghbln can you please backport to 3.2.x? I don't want to mess up something.

**Comment by kghbln** [comment]
229e1661b4332fdf37c4d58af488c1cc9c5259bc
