### ISSUE TITLE
Abandoned guzzlehttp packages

### ISSUE THREAD

**Issue by justinclloyd** [SemanticMediaWiki/SemanticMediaWiki#4919]
### Setup

- SMW version: 3.2.x
- MW version: 1.35.1 (current REL1_35 branch from GitHub)
- PHP version: 7.4.3

### Issue

Running `php composer.phar update --no-dev` with an empty composer.local.json against MediaWiki REL1_35 branch from GitHub has no issues. After adding `"mediawiki/semantic-media-wiki": "~3.2.0"` to composer.local.json, there are two warnings about abandoned guzzlehttp packages:

```
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies
Package operations: 25 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.10.0): Loading from cache
  - Installing justinrainbow/json-schema (5.2.10): Loading from cache
  - Installing seld/jsonlint (1.8.3): Loading from cache
  - Installing react/promise (v2.8.0): Loading from cache
  - Installing guzzlehttp/streams (3.0.0): Loading from cache
  - Installing guzzlehttp/ringphp (1.1.1): Loading from cache
  - Installing elasticsearch/elasticsearch (v6.7.2): Loading from cache
  - Installing symfony/css-selector (v3.4.47): Loading from cache
  - Installing onoi/shared-resources (0.4.3): Loading from cache
  - Installing wikimedia/textcat (1.3.0): Loading from cache
  - Installing onoi/tesa (0.1.0): Loading from cache
  - Installing onoi/callback-container (2.0.0): Loading from cache
  - Installing onoi/cache (1.2.0): Loading from cache
  - Installing onoi/http-request (1.3.1): Loading from cache
  - Installing onoi/blob-store (1.2.1): Loading from cache
  - Installing onoi/event-dispatcher (1.1.0): Loading from cache
  - Installing onoi/message-reporter (1.4.2): Loading from cache
  - Installing serialization/serialization (4.0.0): Loading from cache
  - Installing data-values/interfaces (0.2.5): Loading from cache
  - Installing data-values/data-values (2.3.0): Loading from cache
  - Installing data-values/validators (0.1.3): Loading from cache
  - Installing data-values/common (0.4.3): Loading from cache
  - Installing param-processor/param-processor (1.10.0): Loading from cache
  - Installing mediawiki/parser-hooks (1.6.1): Loading from cache
  - Installing mediawiki/semantic-media-wiki (3.2.2): Loading from cache
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
9 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> ComposerVendorHtaccessCreator::onEvent
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by JeroenDeDauw** [comment]
Cause:

SMW depends on `elasticsearch/elasticsearch: ^5.3|^6.0` which depends on those abandoned packages

Fix:

Allow installation with https://packagist.org/packages/elasticsearch/elasticsearch 7.x (or later)

**Comment by kghbln** [comment]
I'd not touch this until CirrusSearch moves on to newer versions of Elasticserach.

**Comment by justinclloyd** [comment]
Working on an upgrade to MW 1.36 and getting a couple more messages about abandoned packages in addition to the two originally reported:

```
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.
```

FWIW, regarding Jeroen's reply above, I'm actually using (AWS) Elasticsearch now in my 1.35 wikis, with `elasticsearch/elasticsearch: '6.7.*'` in my composer.local.json file in order to resolve the version requirements of CirrusSearch and SMW.

**Comment by JeroenDeDauw** [comment]
Those are development packages coming from MediaWiki itself. Unless you wish to run unit tests or something similar, you typically want to run composer with `--no-dev`, as per most installation instructions. In that case you'll not get these warnings.

**Comment by justinclloyd** [comment]
My script does run it with `--no-dev`. You can see that in my build script on [line 378](https://gist.github.com/justinclloyd/cff4a6886a593c0a7e99c36c5f4a8918#file-build_wiki_sites_directory-sh-L378). Could something else be causing unnecessary libraries to get loaded?

**Comment by JeroenDeDauw** [comment]
Dunno but perhaps this https://gist.github.com/justinclloyd/cff4a6886a593c0a7e99c36c5f4a8918#file-build_wiki_sites_directory-sh-L169

**Comment by justinclloyd** [comment]
Ah good eye, that was basically a cut and paste as I was fixing the script to get SMW and CirrusSearch working together. I'll test without that, thanks!

**Comment by krabina** [comment]
Closing this. Feel free to reopen if it is still valid.
