### ISSUE TITLE
Create central repo for Travis install bash scripts

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4922]
Many repos under github.com/SemanticMediaWiki make use of Travis CI. Many of them require MW or SMW installed. [This is done via bash scripts](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/build/travis/install-mediawiki.sh).

I was thinking about creating a dedicated central repo (SemanticMediaWiki/TravisScripts?) that could hold reusable scripts. These scripts could be pulled during Travis runs from Github. This would reduce effort to maintain those scripts, reduce errors and help making sure, CI is working.

@JeroenDeDauw @kghbln if you like the idea, feel free to create such a repo (I don't have sufficient rights I think)

**Comment by JeroenDeDauw** [comment]
I'm migrating all my stuff away from Travis to GitHub Actions.

If you want a new repo please provide the repo name and description

**Comment by gesinn-it** [comment]
@JeroenDeDauw should we consider switching to GitHub Actions for the SMW related stuff, too?

**Comment by gesinn-it** [comment]
@JeroenDeDauw to keep it neutral, can you please create
* Repo: SemanticMediaWiki/CIScripts
* Desc: Continuous Integration (CI) helper scripts for Semantic MediaWiki and related extensions.

**Comment by JeroenDeDauw** [comment]
I'd not put effort into TravisCI at this point. Looks like I started working on SMW on GitHub actions in Maps but didn't finish it https://github.com/JeroenDeDauw/Maps/tree/master/.github/workflows

https://github.com/SemanticMediaWiki/CIScripts
