### ISSUE TITLE
translatewiki commit 3feef71 breaks integration tests

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4924]
Since https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/3feef71c0e7569b5fba515b2c24384c6d9000497, we get

```
SMW\Tests\Structure\I18nMsgKeyIntegrityTest::testDecKiloSeparatorHasDifferentValue with data set "ne (22fab)" ('/home/travis/build/SemanticMe...e.json')

Failed on ne.json where smw_decseparator/smw_kiloseparator have the same set of values.
```
https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/757518023#L1922

**Comment by Nikerabbit** [comment]
I've deleted the translations per https://unicode-org.github.io/cldr-staging/charts/latest/summary/ne.html#4ec3d1b99830ad07.

Will fix itself in next export on Monday.

For context, we started updating languages that have fallen under the export threshold.
