### ISSUE TITLE
SPAN tags inside H1 tag

### ISSUE THREAD

**Issue by askurashev** [SemanticMediaWiki/SemanticMediaWiki#4929]
Hello.
I form the text on the page using a template. In the template I am using the code:
`<h1 class="PulicationProfileTitle">{{#show: {{PAGENAME}} | ?PTitle}}</h1>`

This code gives the following code on the page
`<h1 class="PulicationProfileTitle"><span id="Антэкология_энтомофильных_альпийских_растений_северо-западного_Кавказа._I._Морфология_генеративных_органов"></span><span class="mw-headline" id=".D0.90.D0.BD.D1.82.D1.8D.D0.BA.D0.BE.D0.BB.D0.BE.D0.B3.D0.B8.D1.8F_.D1.8D.D0.BD.D1.82.D0.BE.D0.BC.D0.BE.D1.84.D0.B8.D0.BB.D1.8C.D0.BD.D1.8B.D1.85_.D0.B0.D0.BB.D1.8C.D0.BF.D0.B8.D0.B9.D1.81.D0.BA.D0.B8.D1.85_.D1.80.D0.B0.D1.81.D1.82.D0.B5.D0.BD.D0.B8.D0.B9_.D1.81.D0.B5.D0.B2.D0.B5.D1.80.D0.BE-.D0.B7.D0.B0.D0.BF.D0.B0.D0.B4.D0.BD.D0.BE.D0.B3.D0.BE_.D0.9A.D0.B0.D0.B2.D0.BA.D0.B0.D0.B7.D0.B0._I._.D0.9C.D0.BE.D1.80.D1.84.D0.BE.D0.BB.D0.BE.D0.B3.D0.B8.D1.8F_.D0.B3.D0.B5.D0.BD.D0.B5.D1.80.D0.B0.D1.82.D0.B8.D0.B2.D0.BD.D1.8B.D1.85_.D0.BE.D1.80.D0.B3.D0.B0.D0.BD.D0.BE.D0.B2">Антэкология энтомофильных альпийских растений северо-западного Кавказа. I. Морфология генеративных органов</span></h1>`

Where do these two `span ` elements come from? SMW or MW? Is it necessary for some purpose? Can I remove and get text only? How do you do it?

**Comment by kghbln** [comment]
Have you tried the ["plainlist" format](https://www.semantic-mediawiki.org/wiki/Help:Plainlist_format)?

**Comment by askurashev** [comment]
Now remains only span inside h1
```
<h1 class="PulicationProfileTitle"><span class="mw-headline" id="The_transmission_of_genes_via_pollen_and_ovules_in_gynodioecious_angiosperms">The transmission of genes via pollen and ovules in gynodioecious angiosperms</span></h1>
```

**Comment by kghbln** [comment]
I believe this on comes from MediaWiki.

**Comment by akuckartz** [comment]
Maybe someone can ensure that this is raised as a MW issue.
