### ISSUE TITLE
Escaping blanks in identifiers 

### ISSUE THREAD

**Issue by tholzheim** [SemanticMediaWiki/SemanticMediaWiki#4933]
I get different query results on the wiki [OPENRESEARCH](https://www.openresearch.org/wiki/Issue:Query_Underscore) (v1.31.1)  for the following two queries:
```
{{#ask:[[isA::Event series]]}}
{{#ask:[[isA::Event_series]]}}
```
but the queries 
```
{{#ask:[[Category:Event series]]}}
{{#ask:[[Category:Event_series]]}}
```
return the same result. So the blank in the identifier can be replaced with an underscore in some cases.
On my test wiki [orth](https://confident.dbis.rwth-aachen.de/orth/index.php?title=Issue:Query_Underscore) (v1.35.1), which is a complete copy of OPENRESEARCH, this issue does not occur. Meaning that the blank can always be replaced with an underscore without altering the query result.

Is this issue related to the version or the configuration of the wiki?

| wiki| orth | OPENRESEARCH |
| --- | --- | --- |
|Mediawiki version| 1.35.1 | 1.31.1 |
|Semantic Mediawiki| 3.2.2 | 2.5.8|
|Semantic Result Formats | 3.2.0 | 2.5.6 | 
|Issue occurs| No | Yes |
| Issue Page | [link](https://confident.dbis.rwth-aachen.de/orth/index.php?title=Issue:Query_Underscore)|[link](https://www.openresearch.org/wiki/Issue:Query_Underscore)

**Comment by WolfgangFahl** [comment]
Which Semantic MediaWiki versions are installed on the different setups?

**Comment by tholzheim** [comment]
It issue occurs on OPENRESEARCH which runs on Semantic MediaWiki v.2.5.8

**Comment by WolfgangFahl** [comment]
So https://github.com/SmartDataAnalytics/OpenResearch/issues/83 is needed
