### ISSUE TITLE
MW 1.35: CsvFileExportPrinterTest::testLink - Use of $wgParser was deprecated in MediaWiki 1.32.

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4940]
1) SMW\Tests\Query\ResultPrinters\CsvFileExportPrinterTest::testLink

Use of $wgParser was deprecated in MediaWiki 1.32. [Called from SMW\Query\ResultPrinters\ResultPrinter::handleNonFileResult in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php at line 379]

https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/760157304#L1973

**Comment by Seb35** [comment]
Fixed by e56edac5e, this issue can be closed.

**Comment by kghbln** [comment]
Thank you!
