### ISSUE TITLE
MW 1.35: p-0901.json - Use of TitleMoveComplete hook was deprecated in MediaWiki 1.35.

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4942]
3) SMW\Tests\Integration\JSONScript\JSONScriptTestCaseRunnerTest::testCaseFile with data set "p-0901.json" ('/home/travis/build/SemanticMe...1.json')

Use of TitleMoveComplete hook (used in onTitleMoveComplete) was deprecated in MediaWiki 1.35. [Called from MediaWiki\HookContainer\HookContainer::run in /home/travis/build/SemanticMediaWiki/mw/includes/HookContainer/HookContainer.php at line 132]

https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/760157304#L2007

**Comment by Abijeet** [comment]
This was fixed in bb7adbccb223804c2c13a681f2fa74a839150a55 and then further improved in #5050
