### ISSUE TITLE
MW 1.35: s-0001.json - Use of SpecialPageFactory::getPage was deprecated in MediaWiki 1.32.

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4943]
4) SMW\Tests\Integration\JSONScript\JSONScriptTestCaseRunnerTest::testCaseFile with data set "s-0001.json" ('/home/travis/build/SemanticMe...1.json')

Use of SpecialPageFactory::getPage was deprecated in MediaWiki 1.32. [Called from SMW\Tests\Utils\JSONScript\SpecialPageTestCaseProcessor::process in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/SpecialPageTestCaseProcessor.php at line 88]

https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/760157304#L2040

**Comment by Seb35** [comment]
See also #4623 and linked issues for previous replacements of this deprecated static method.
