### ISSUE TITLE
MW 1.35: Use of Revision::newFromId was deprecated in MediaWiki 1.31.

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4944]
5) SMW\Tests\Integration\MediaWiki\LinksUpdateSQLStoreDBIntegrationTest::testPageCreationAndRevisionHandlingBeforeLinksUpdate

Use of Revision::newFromId was deprecated in MediaWiki 1.31. [Called from SMW\Tests\Integration\MediaWiki\LinksUpdateSQLStoreDBIntegrationTest::retrieveAndLoadData in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/MediaWiki/LinksUpdateSQLStoreDBIntegrationTest.php at line 190]

https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/760157304#L2056

**Comment by Abijeet** [comment]
This was fixed in https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/4e0aed2f8084b71442e94c05598c8f71cfb922f0#diff-e522ca6c381e561f70b7c582a2fabea47d77e1b867ead2440bfa90d2045d85d3R191
