### ISSUE TITLE
MW 1.35: Use of Parser::__construct was deprecated in MediaWiki 1.34.

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4945]
6) SMW\Tests\Integration\Parser\InTextAnnotationParserTemplateTransclusionTest::testPreprocessTemplateAndParse with data set #0 (0, array(array(true), false, 8, 'hash'), '[[Foo::{{Bam}}]]', '?bar', array('[[:?bar|?bar]]', 1, array('Foo'), array('?bar')))

Use of Parser::__construct was deprecated in MediaWiki 1.34. [Called from SMW\Tests\Integration\Parser\InTextAnnotationParserTemplateTransclusionTest::runTemplateTransclusion in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/Parser/InTextAnnotationParserTemplateTransclusionTest.php at line 58]

https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/760157304#L2071

**Comment by Seb35** [comment]
Fixed by e56edac5e, this issue can be closed.

**Comment by Nikerabbit** [comment]
Thanks!
