### ISSUE TITLE
Regex/Wildcard support in property chains

### ISSUE THREAD

**Issue by simontaurus** [SemanticMediaWiki/SemanticMediaWiki#4948]
Dealing with ontology concepts like the relation "has part" often leads to deeply nested structures in a SMW.

Example data structure: 
```
Car-(has part)->Steering wheel-(has shape)->round
Car-(has part)->Chassis-(has part)->Axle-(has part)->Wheel-(has shape)->round
```

Property chaining helps to query those structures, but the path has to be explicit.

Example query: All round shaped object of a car
```
{{#ask: [[has shape::round]] [[-has part::Car]] 
OR [[has shape::round]] [[-has part.-has part.-has part::Car]] }}
```

Since the exact nesting depth is not known, it is costly to write down all possible nesting depths.
It would be much easier to use a (regex) wildcard (*/+) to write this query

`{{#ask: [[has shape::round]] [[-has part+::Car]] }} = {{#ask: [[has shape::round]] [[-has part.-has part*::Car]] }}`

or alternatively 

`{{#ask: [[has shape::round]] [[-has part{1,5}::Car]] }}`

to query for a nesting depth of min 1 and max 5.

SPARQL-Equivalent: [https://www.w3.org/TR/sparql11-property-paths/]()

**Comment by alex-mashin** [comment]
It will be difficult to implement it with SQL backend.

**Comment by jaideraf** [comment]
> It will be difficult to implement it with SQL backend.

Exactly. As noted in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4951#issuecomment-791417100.

Closing this for now.
