### ISSUE TITLE
Selecting pages with regular expressions

### ISSUE THREAD

**Issue by maxnth** [SemanticMediaWiki/SemanticMediaWiki#4951]
Is it possible to select pages (in e.g. inline queries) via regular expressions?
I'm currently only aware of the search operators `~` and `!~` (and `like:` and `nlike:` since SMW 3.0) and while these certainly help to cover a lot of use cases, they're still somewhat limited compared to regular expressions.

In case this isn't possible at the moment, are there any plans to integrate this into future versions of SMW or is it unlikely that we'll see an implementation because of e.g. security concerns like ReDoS?

**Comment by gesinn-it** [comment]
I'm not aware of any plans for implementing this at the moment. @kghbln ?

**Comment by jaideraf** [comment]
There is no plan for implementing regular expressions in queries. SMW always aim to make ASK queries features equivalent among backends (SQL, Triplestores, Elastic), so I think implementing regular expressions would not be an easy task.

**Comment by jaideraf** [comment]
Not an ASK query, but you can search with regular expressions with[ Replace text extension](https://www.mediawiki.org/wiki/Extension:Replace_Text).

**Comment by WolfgangFahl** [comment]
You might use the the workaround https://www.semantic-mediawiki.org/wiki/Architecture_Tradeoffs and use a mySQL query using requlare expressions. I also intend to make multiple query options available in https://github.com/BITPlan/pyWikiCMS and https://github.com/WolfgangFahl/py-3rdparty-mediawiki - feel free to add an issue with a feature request there.

**Comment by jaideraf** [comment]
> Not an ASK query, but you can search with regular expressions with [Replace text extension](https://www.mediawiki.org/wiki/Extension:Replace_Text).

Not an ASK query, but you can search with regular expressions with [CirrusSearch](https://www.mediawiki.org/wiki/Help:CirrusSearch#Regular_expression_searches), also. It requires Elasticsearch, though. 

I think this issue can be closed.
