### ISSUE TITLE
TypeError from line 75 of TaskHandlerFactory.php

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4964]
### Setup

- SMW version: 3.2.3
- MW version: 1.35.1 (6f5d70b) 17:17, 31. Mär. 2021
- PHP version: 7.4.3 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.25-MariaDB-0ubuntu0.20.04.1

### Issue

When trying to access special page "Semantic MediaWiki" I get:

```
[b7480215912aedf28154e089] /wiki/Spezial:SemanticMediaWiki TypeError from line 75 of /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Admin/TaskHandlerFactory.php: Argument 2 passed to SMW\MediaWiki\Specials\Admin\TaskHandlerFactory::newTaskHandlerRegistry() must be of the type int, string given, called in /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAdmin.php on line 106
```
<s>This is probably an issue introduced with one of the recent commits to REL1_35 of MediaWiki since this only happens after updating MediaWiki: "Updating 2a1a1b6b5b..6f5d70b6c7".</s> Sandbox is using a release candidate of MW 1.35 and does not show the issue. Nope, 1.35.1 shows the same issue.

### Backtrace
```
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAdmin.php(106): SMW\MediaWiki\Specials\Admin\TaskHandlerFactory->newTaskHandlerRegistry()
#1 /../w/includes/specialpage/SpecialPage.php(600): SMW\MediaWiki\Specials\SpecialAdmin->execute()
#2 /../w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#3 /../w/includes/MediaWiki.php(311): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#4 /../w/includes/MediaWiki.php(943): MediaWiki->performRequest()
#5 /../w/includes/MediaWiki.php(547): MediaWiki->main()
#6 /../w/index.php(53): MediaWiki->run()
#7 /../w/index.php(46): wfIndexMain()
#8 {main}
```

**Comment by kghbln** [comment]
@gesinn-it Looks like a similar issue as in https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/88

**Comment by kghbln** [comment]
Also happening on:
- MediaWiki | 1.31.12 (4a1e3f7)00:30, 5. Apr. 2021
- PHP | 7.3.27-1~deb10u1 (apache2handler)

**Comment by kghbln** [comment]
I wonder wtbh this does not happen with sandbox. The only difference is the PHP version which is 7.2 over there.

**Comment by JeroenDeDauw** [comment]
Newer versions of PHP are more strict about types

**Comment by kghbln** [comment]
Obviously.

**Comment by JeroenDeDauw** [comment]
I don't see anything wrong with the code. Maybe someone fucked up the `smwgAdminFeatures` setting by putting `'SMW_ADM_REFRESH'` (or similar) instead of `SMW_ADM_REFRESH`
