### ISSUE TITLE
SMW does not set rdfs:subClassOf for subcategories any more

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#4970]
### Setup

- SMW version: 3.2.3, 3.2.2
- MW version:  1.35.1, 1.31.x
- PHP version: 7.3.27
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.28-MariaDB

### Issue

According to the [documentation](https://www.semantic-mediawiki.org/wiki/Help:RDF_export#Categories), SMW should set set rdfs:subClassOf in the RDF representatiof of a page if the page is in a category which is a subcategory of another category.

However, this does not work anymore.
The page [Issue/2662/1](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Issue-2F2662-2F1) is in category [C0615/1](https://sandbox.semantic-mediawiki.org/wiki/Cat%C3%A9gorie:C0615/1) which a subcategory of [C0615](https://sandbox.semantic-mediawiki.org/wiki/Cat%C3%A9gorie:C0615).

However, in the [RDF representation](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Export_RDF/Issue/2662/1&syntax=rdf) there is no rdfs:subClassOf statement...

**Comment by krabina** [comment]
However, it can be found here: https://www.semantic-mediawiki.org/w/index.php?title=Special:ExportRDF/Category:AspectCode&syntax=rdf

**Comment by jaideraf** [comment]
Hi @krabina. I did not see a bug here. 

Article1 that is in a Category1:
`Article1 > rdf:type > Category1`
Category1 that is in a Category2:
`Category1 > rdfs:subClassOf > Category2`

That is right for me.

**Comment by krabina** [comment]
oh. I see. Indeed. 
I was expecting that the rdfs:subClassOf must be in the RDF of an instance. However, it is present in the category page RDF, which seems to be enough...
Thank you.
