### ISSUE TITLE
Is SMW ready for PHP 8?

### ISSUE THREAD

**Issue by MPThLee** [SemanticMediaWiki/SemanticMediaWiki#4972]
Hi, Since Mediawiki upstream is almost done for php8 support, I want to know that SemanticMediaWiki and related projects are PHP 8 ready.

Make MediaWiki compatible with PHP 8: https://phabricator.wikimedia.org/T248925
Make PHP 8.0 voting on MW 1.35: https://phabricator.wikimedia.org/T274965
PHP 8.0 Support workboard on Wikimedia Phabricator: https://phabricator.wikimedia.org/project/view/4652/

**Comment by JeroenDeDauw** [comment]
Probably not. We've not been able to test with PHP 8 since MediaWiki itself would error out.

**Comment by jaideraf** [comment]
Answering the question: yes, by now. The CI is testing against PHP 8.1. So, this issue can be closed.
