### ISSUE TITLE
composer shows errors and won't update dependencies

### ISSUE THREAD

**Issue by tim1mike** [SemanticMediaWiki/SemanticMediaWiki#4977]
### Setup

- SMW version: 3.2.2
- MW version: 1.35.1
- PHP version: 7.4.13
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.5.8

### Issue

I've installed SMW with only one problem - version conflict with External Data 2.3 which required `"symfony/css-selector": "~5.1"` I just downgrade requirements to `"^3.3"`
Now it's working fine but I want to install more smw extensions so I add 3 new extensions into my composer.local.json
```
{
	"require": {
		"mediawiki/semantic-media-wiki": "~3.2",
		"mediawiki/semantic-result-formats": "~3.2",
		"mediawiki/semantic-breadcrumb-links": "~2.0",
		"mediawiki/semantic-meta-tags": "~3.0"
	},
	"extra": {
		"merge-plugin": {
			"include": [
				"extensions/*/composer.json",
				"skins/*/composer.json"
			]
		}
	}
}
```
I ran `composer update --prefer-source` and then it showed some errors:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mediawiki/core No version set (parsed as 1.0.0) -> satisfiable by mediawiki/core[No version set (parsed as 1.0.0)].
    - mediawiki/semantic-result-formats 3.2.0 requires mediawiki/semantic-media-wiki ~3.0 -> satisfiable by mediawiki/semantic-media-wiki[3.2.2, 3.2.0, 3.2.1, 3.2.3].
    - remove mediawiki/core No version set (parsed as 1.0.0)|remove mediawiki/semantic-media-wiki 3.2.2
    - don't install mediawiki/semantic-media-wiki 3.2.0|remove mediawiki/core No version set (parsed as 1.0.0)
    - don't install mediawiki/semantic-media-wiki 3.2.1|remove mediawiki/core No version set (parsed as 1.0.0)
    - don't install mediawiki/semantic-media-wiki 3.2.2|remove mediawiki/core No version set (parsed as 1.0.0)
    - don't install mediawiki/semantic-media-wiki 3.2.3|remove mediawiki/core No version set (parsed as 1.0.0)
    - Installation request for mediawiki/semantic-result-formats ~3.2 -> satisfiable by mediawiki/semantic-result-formats[3.2.0].
```
I don't know why this is happening and can't install another extensions which required composer installation, I tried to find if I have `mediawiki/core` line somewhere but there's nothing found.
If I just remove `"mediawiki/semantic-media-wiki": "~3.2",` from composer.local.json it will remove SMW after `composer update` command.

I have many other extensions but seems they cause no problems with composer update at all

**Comment by JeroenDeDauw** [comment]
`mediawiki/core`? huh. I wonder where that is coming from

**Comment by kghbln** [comment]
Dunno either. Perhaps try to remove the `extra` section and see what is happening after that.

**Comment by tim1mike** [comment]
> Dunno either. Perhaps try to remove the `extra` section and see what is happening after that.

Whoa it works, thanks!
Now I got some errors after maintenance/update.php but It's a solution!
I deleted `"extensions/*/composer.json",` and instead I added all the extensions one by one like this:
```
	"extra": {
		"merge-plugin": {
			"include": [
				"extensions/AWS/composer.json",
				"extensions/BetaFeatures/composer.json",
				"extensions/CategoryTree/composer.json",
				"extensions/Cite/composer.json",
				"extensions/CiteThisPage/composer.json"
```

**Comment by kghbln** [comment]
Thanks for confirming my somehow educated guess. Note that you only have to include the "composer.json" files of extensions that fetch dependencies. All the rest is superfluous.
