### ISSUE TITLE
Named subobjects

### ISSUE THREAD

**Issue by octfx** [SemanticMediaWiki/SemanticMediaWiki#4978]
I have a clarifying question regarding named subobjects.

Both the main [documentation](https://www.semantic-mediawiki.org/wiki/Help:Adding_subobjects#Specifying_an_identifier) and the Semantic Scribunto [documentation](https://github.com/SemanticMediaWiki/SemanticScribunto/blob/master/docs/mw.smw.subobject.md) state, that anonymous subobjects are prefered or  that `[...] manually setting a subobject id. [...] is not recommended`.

Are there any performance implications using named subobjects?

**Comment by JeroenDeDauw** [comment]
> Are there any performance implications using named subobjects?

I'm not sure but suspect not

**Comment by kghbln** [comment]
I believe the reason behind this is that you can do much more when you use unnamed subobjects. Cannot remember the last time I used this variant if ever.

**Comment by jaideraf** [comment]
> Cannot remember the last time I used this variant if ever.

By the contrary, my default is using named subobjects. :joy: By using named subobjects I can atribute properties/values in more than one call to the object. Using unnamed subobjects that is not possible (each call creates a new subobject). Also, an ID to the object (the named part) allows me to query by the same ID.

**Comment by kghbln** [comment]
Fair enough. Admittedly I usually pass the object name to the subobject as an annotation to the subobject to establish a direct connection.

**Comment by octfx** [comment]
It seems that naming objects is a valid approach.
The reason for my question is that I'm adding objects from an external API as subobjects. Some objects are missing data which should be set manually by adding supplemental subobjects to the wikipage (which only works if they get an ID so they are merged).

Thanks all for the help! 😃
