### ISSUE TITLE
SQLStore support a way to clean up the `smw_object_ids` table

### ISSUE THREAD

**Issue by nischayn22** [SemanticMediaWiki/SemanticMediaWiki#498]
There are a lot of ways one can introduce invalid entries in SMW. 

Example: Assign a property-value for a property with no user-defined type. The default type is Page, this will lead to the values assigned being put into the smw_object_ids table. Now change the type to Text. The ids will still be there. 

I think even deleteSubject also currently doesn't support this. The comment in the code says
TODO: Possibly delete ID here...

I am also not sure if doing a database clean + rebuild will fix these issues, otherwise that is a good workaround.

**Comment by mwjames** [comment]
Fixed with #1216
