### ISSUE TITLE
ParserCache::getETag was deprecated in MediaWiki 1.36. [Called from SMW\MediaWiki\Hooks::onArticleViewHeader

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#4982]
### Setup

- SMW version: 4.0.0-alpha (6b0280b)
- MW version: 1.37.0-alpha (f005492)
- PHP version: 7.3.27-1~deb10u1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.27-MariaDB-0+deb10u1

### Issue

Suggested replacement: "instead build suitable etag explicitly."

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Not possible since hard deprecation is in 1.3[67].

**Comment by Abijeet** [comment]
Should be fixed by #5019

**Comment by JeroenDeDauw** [comment]
Please close this if it is fixed

**Comment by bertrandgorge** [comment]
Hello all, I see that the fix from @Abijeet has not made its way to the latest release of SMW (3.2.3), thus rendering SMW not compatible with REL_1.37... I'd be happy to help testing if that's what is missing...?

**Comment by JeroenDeDauw** [comment]
You can run SMW master on MW 37 and tell us if it worked well, or report issues. That will help us get SMW 4.0 out.

**Comment by bertrandgorge** [comment]
Ok !

**Comment by bertrandgorge** [comment]
Hello @JeroenDeDauw - is there any documentation about the upgrade ? I've changed the version in composer and got the master version for SMW but it doesn't seem to do any good. I end up with `[29-Nov-2021 12:00:36 UTC] PHP Parse error:  syntax error, unexpected 'SmwJsonRepo' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/extensions/SemanticMediaWiki/src/SetupFile.php on line 66` when I try to `update.php` the wiki... (sorry if this is not the right place to discuss this - would be happy to do so anywhere else)

**Comment by jaideraf** [comment]
@bertrandgorge Maybe you have to adjust the way SMW is loading, see:  

https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5148#issuecomment-980507917

**Comment by bertrandgorge** [comment]
Thanks @jaideraf - I just added that but it didn't change the error I get...

**Comment by bertrandgorge** [comment]
In fact I think I will have unresolved conflicts in my composer : 

```
{
    "require": {
        "mediawiki/chameleon-skin": "^3.4",
        "mediawiki/semantic-media-wiki": "master",
        "mediawiki/maps": "^8.0",
        "mediawiki/semantic-result-formats": "^3.2",
        "mediawiki/semantic-forms-select": "^3.0",
        "mediawiki/semantic-scribunto": "^2.1",
        "mediawiki/semantic-extra-special-properties": "^2.1",
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

Some of those packages are locked with version 3 of SMW....

**Comment by Abijeet** [comment]
Try using `dev-master`
```
"mediawiki/semantic-media-wiki": "dev-master",
```

**Comment by jaideraf** [comment]
My composer.local.json (but I have MW 1.35): 

```json
{
	"require": {
		"mediawiki/semantic-media-wiki": "dev-master",
		"mediawiki/semantic-result-formats": "~3.1",
		"mediawiki/semantic-extra-special-properties": "~2.0",
		"mediawiki/semantic-meta-tags": "~2.0",
		"mediawiki/semantic-scribunto": "~2.1",
		"professional-wiki/id-generator": "~1.0",
		"elasticsearch/elasticsearch": "6.7.x"
	}
}
```

**Comment by bertrandgorge** [comment]
Still no luck...:

```
root@9734bd2e30a2:/var/www/html# php maintenance/update.php
[18657b7e5bc096af518e502e] [no req]   ParseError: syntax error, unexpected 'SmwJsonRepo' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
Backtrace:
from /var/www/html/extensions/SemanticMediaWiki/src/SetupFile.php(66)
#0 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile(string)
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass(string)
#2 /var/www/html/extensions/SemanticMediaWiki/src/Setup.php(116): spl_autoload_call(string)
#3 /var/www/html/extensions/SemanticMediaWiki/SemanticMediaWiki.php(76): SMW\Setup->init(array, string)
#4 /var/www/html/includes/Setup.php(856): SemanticMediaWiki::onExtensionFunction()
#5 /var/www/html/maintenance/doMaintenance.php(90): require_once(string)
#6 /var/www/html/maintenance/update.php(264): require_once(string)
#7 {main}
root@9734bd2e30a2:/var/www/html#
```

@JeroenDeDauw is it something that comes from https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/534ccf3c358bf03e9bb206e29bf37e2dd663d4d1 ?

**Comment by JeroenDeDauw** [comment]
What PHP version and which commit of SMW are you using?

**Comment by bertrandgorge** [comment]
Ahhh.... That did it... I was on 7.3.33 indeed. Moving to 7.4.26 fixes it. Starting tests now - will keep you updated (I'll open new issues)

**Comment by jaideraf** [comment]
@JeroenDeDauw should we change PHP 7.3.0 to PHP 7.4.0 [here](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md)?: 

<table class="compatibility">
	<tr>
		<th>SMW</th>
		<th>PHP</th>
		<th>MediaWiki</th>
		<th>Released</th>
		<th>Status</th>
	</tr>
	<tr>
		<th>4.0.x</th>
		<td><strong>7.3.0</strong> - 7.4.x</td>
		<td><strong>1.35.0</strong> - 1.36.x</td>
		<td>-</td>
		<td>In development</td>
	</tr>
	</table>

**Comment by JeroenDeDauw** [comment]
There is this strange local blurring effect on my screen. But I can just make out that you both are saying we should require PHP 8.1 for SMW 4.0. Consider it done.

**Comment by gesinn-it-gea** [comment]
no, I think we should drop support for PHP 8.x for SMW 4 and make future PHP 9.x mandatory :upside_down_face:
