### ISSUE TITLE
Error with set property contain #widget

### ISSUE THREAD

**Issue by askurashev** [SemanticMediaWiki/SemanticMediaWiki#4986]
Hello.

With Widgets extension I get some URL. 
In page I want set property contains results of work this widget:
`{{#set:PPreview={{#widget:PublicationPreview|title={{{Title}}}|abstract={{{Abstract}}}|authors={{{Authors}}}|year={{{Year}}}|aid={{PAGENAME}}|type={{{Type}}}}}}}`
But I get error, my property:
START_WIDGETdb78d22704ab88d5-124END_WIDGET.

Please, help me undestand this error.

**Comment by kghbln** [comment]
I am really not sure what you are trying to do here. Please post the output of just the widget. Also you could try to add `SMW_PARSER_UNSTRIP` to [`$smwgParserFeatures`](https://www.semantic-mediawiki.org/wiki/Help:$smwgParserFeatures]
