### ISSUE TITLE
How to disable thousand separators in datatype 'Number'

### ISSUE THREAD

**Issue by Mikumikuer** [SemanticMediaWiki/SemanticMediaWiki#4992]
I need ask a property and use in template as a filename, this property contains only numbers.
Since I need filter it with comparators, i must add '[[Has type:Number]]', but it comes with thousand separators that I don't except in filename.
Is there any method to disable it?

**Comment by Mikumikuer** [comment]
Solved, Adding '#' after properties you need ( eg:{{#ask|[[condition]]|?prop#}} ), it will disable thousand separators.

**Comment by gesinn-it** [comment]
see https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#Plain_.28unformatted.29_printouts
