### ISSUE TITLE
Error when adding external links

### ISSUE THREAD

**Issue by JaviRoch** [SemanticMediaWiki/SemanticMediaWiki#5000]
### Setup

- SMW version: 3.0.2
- MW version: 1.31.3
- PHP version: 7.2.34
- DB system MySQL: 5.7.33
- Page Forms: 4.4.1

### Issue

I use Page Forms to enter text in templates, when I enter an external URL when saving it switches to the wikitext editor and does not allow me to save.

If the user is a mediawiki administrator there is no error.

Text of the entry in wikitext:

```
{{Info-iniciativa
|Main_Picture=Edi3_cierta-luz-31012019-920.jpg
|Objetivos=Social
|IniciaTipo=Asociación
|Gestion=Pública
|CA=Madrid
|Nacimiento=1234/01/01
|Organizacion=[https://prueba.es Prueba]
}}
```

Semantic Mediawiki configuration:

```
require_once "$IP/extensions/SemanticMediaWiki/SemanticMediaWiki.php";
enableSemantics( $wgServer );
$smwgParserFeatures  = SMW_PARSER_LINV;
```

**Comment by jaideraf** [comment]
I think the problem is connected to a spam prevention extension (ConfirmEdit, SpamBlacklist or TitleBlacklist - I don't remember which one). One of these extension is preventing a URL to be saved if the user has not the appropriate priviledges.

**Comment by jaideraf** [comment]
Also, I recommend you to update your Page Forms extension.

**Comment by jaideraf** [comment]
Also, not related but 
`enableSemantics( $wgServer );`
seems not appropriate. Maybe 
`enableSemantics( $wgServer, true );`
See https://www.semantic-mediawiki.org/wiki/Help:EnableSemantics#Parameters

**Comment by JaviRoch** [comment]
Thank you very much for the indications, it was a configuration error in ConfirmEdit

**Comment by kghbln** [comment]
> Also, not related but
> `enableSemantics( $wgServer );`
> seems not appropriate. Maybe
> `enableSemantics( $wgServer, true );`
> See https://www.semantic-mediawiki.org/wiki/Help:EnableSemantics#Parameters

I would not use `$wgServer` but rather hard code for reasons noted on that very help page. A change to this parameter would result into a change of source identifier in the linked data world which is something you would like to avoid.
