### ISSUE TITLE
Drop SMW_NS_RULE namespace

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#5004]
`SMW_NS_RULE` namespace [seems to be unused](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?q=SMW_NS_RULE), I think it was replaced by the awesome `SMW_NS_SCHEMA` in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3431. So, as @mwjames is not actively developing it right now, it shoud be droped in a SMW 4.0. It is currently just an empty namespace displayed in the Special:Search.

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/w/index.php?title=Help:Namespaces&oldid=90217)
