### ISSUE TITLE
code shouldn't be using $wgContLang any longer?

### ISSUE THREAD

**Issue by MvanKoll** [SemanticMediaWiki/SemanticMediaWiki#5010]
According to a developer of the page schemas extension, SWM "shouldn't be using $wgContLang any longer since it was removed in MW 1.36". See this issue: 
https://www.mediawiki.org/wiki/Extension_talk:Page_Schemas#Error_when_creating_a_schema. I'm not a developer myself so I have no idea about this.

**Comment by kghbln** [comment]
Thanks for reporting. Unfortunately SMW currently does not officially support MW 1.36.x

**Comment by hexmode** [comment]
This was done in e56edac5e17e0474c50682944302e4fa6698ae94
