### ISSUE TITLE
Template with Named Arguments not working with #show

### ISSUE THREAD

**Issue by r0estir0bbe** [SemanticMediaWiki/SemanticMediaWiki#502]
I'm using templates with named arguments to query lists of data. Usually, I use #ask to query that data. But to show some examples (e.g. how the template looks like), I occasionally use #show.
However, it seems that #show doesn't support named arguments at all. When using `named args=yes`, no more parameters are passed and no variables are set (numbered as well as the named arguments).
I created an example on the Referata scratchpad:
http://scratchpad.referata.com/wiki/NamedArgumentPage

**Comment by mwjames** [comment]
> No, scratchpad and my public test wiki are still on 1.8

@kghbln Again, sorry for requesting your assistance but it is a similar request as in #481.

**Comment by kghbln** [comment]
The behaviour is unchanged: https://sandbox.semantic-mediawiki.org/wiki/Issue/502
