### ISSUE TITLE
Tests on master are broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#5058]
https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/builds/237102047

**Comment by JeroenDeDauw** [comment]
@Abijeet I was afraid this would happen

**Comment by Abijeet** [comment]
@JeroenDeDauw - I'll check it out tomorrow.

**Comment by Abijeet** [comment]
@JeroenDeDauw - I've submitted some fixes in #5059 but I'm not sure what's causing the failures in the latest CI - https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/3542775804

The CI here (Just 2 commits previous) had more test cases pass: https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/536006098 

Anything obvious that stands out to you?

**Comment by Abijeet** [comment]
> @Abijeet I was afraid this would happen. Not sure which change this is coming from

The tests on master should be fixed by #5065.
I've submitted further improvements in #5066 and #5067.
