### ISSUE TITLE
Missing semicolons in ext.smw.special.ask.js: The special page "Semantic search" is grayed out. Safari reports the JS SyntaxError: "Unexpected identifier 'change'"

### ISSUE THREAD

**Issue by oboehlk** [SemanticMediaWiki/SemanticMediaWiki#5060]
Setup

- SMW version: 3.2.3
- MW version: 1.36.0
- PHP version: 7.4.19 (fpm-fcgi)
- DB system: MariaDB	10.5.11-MariaDB-1:10.5.11+maria~focal-log

[Url of the Version-Special-Page ](https://bernburg-memorial.ksb-anhalt.de/index.php?title=Spezial:Version)

 Issue

Unfortunately the special page "Semantic search" ([Link](https://bernburg-memorial.ksb-anhalt.de/index.php?title=Spezial:Semantische_Suche)) is grayed out.
Safari reports the JS SyntaxError: "Unexpected identifier 'change'" (load.php:21).  Firefox: "Uncaught SyntaxError: Unexpected token: identifier" (load.php:116:27).
It is referred to the following code snippet:

delete this.messages[key];}change.prototype.informAbout=function(key){var informAbout='';if(this.messages.hasOwnProperty(key)){informAbout=key;}else{for(var prop in this.messages){if(prop!==key&&this.messages.hasOwnProperty(prop)){informAbout=prop}}}if(informAbout!==''){this.show(informAbout);}else{this.hide();}}change.prototype.show=function(key){var msg=this.messages[key];var html=this.html.element('div',{id:'status-format-change',class:'smw-callout smw-callout-'+msg[1]},mw.msg(msg[0],this.name));$(this.hideList).hide();$('#status-format-change').remove();$('#ask-change-info').append(html);}change.prototype.hide=function(){$(this.hideList).show();$('#status-format-change').remove();$('#inlinequeryembed, #embed_hide').hide();$('#embed_show').show();}var tooltip=smw.Factory.newTooltip();var _init={tooltip:function(){$('.smw-ask-info').each(function(){tooltip.show({context:$(this),content:$(this).data('info'),title:mw.msg('smw-ui-tooltip-title-parameter'),button:!1});});$(

 
It comes from the file /extensions/SemanticMediaWiki/res/smw/special/ext.smw.special.ask.js

**Comment by oboehlk** [comment]
Ok. https://jshint.com provides the following warnings for /mediawiki/extensions/SemanticMediaWiki/res/smw/special/ext.smw.special.ask.jsext.smw.special.ask.js

64	Missing semicolon
74	Missing semicolon
92	Missing semicolon
102	Missing semicolon
127	Missing semicolon
140	Missing semicolon
350	Missing semicolon

The addition of these semicolons solved the problem. The special page for semantic search works now.

**Comment by kghbln** [comment]
@oboehlk Great finding! Would you like to create a pull request?

**Comment by oboehlk** [comment]
@kghbln Unfortunately I am a complete beginner on "github". It would certainly be important to solve the problem. Could you please tell me what I need to do to create a "pull request"?

**Comment by oboehlk** [comment]
The semicolons in lines 64,74,102,127 and 140 already exists in the code of "i/extensions/SemanticMediaWiki/res/smw/special/ext.smw.special.ask.js". I added the semicolons in lines 92 and 350 and started a "pull request". I hope it is ok..

**Comment by jaideraf** [comment]
Hi @oboehlk, I think you almost have done it right, you have made the modifications on your copy of Semantic MediaWiki ([oboehlk / SemanticMediaWiki](https://github.com/oboehlk/SemanticMediaWiki/pull/1/commits/ff778883ed773b5fb58de002ec99c6f6e93661e9)). Over there you may have a button to submmit your modifications to this main repository (SemanticMediaWiki/SemanticMediaWiki).

**Comment by oboehlk** [comment]
@jaideraf Thank you for pointing this out. I had overlooked that. I have now created the pull request.

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5064
