### ISSUE TITLE
Call to undefined function SMW\SPARQLStore\curl_init()

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5061]
### Setup

Product | Version
-- | --
MediaWiki | 1.35.1
PHP | 7.3.29-1~deb10u1 (apache2handler)
MariaDB | 10.3.27-MariaDB-0+deb10u1
ICU | 63.1
Semantic MediaWiki | 3.2.3 (5619c2d) 22:40, 29 March 2021

### Issue

When tryinig to setup SMW to a SPARQL store, I get the following message when running setupStore.php
```
Semantic MediaWiki:                                                   3.2.3
MediaWiki:                                                           1.35.1
[1d9e78d7105349d6c692c12e] [no req]   Error from line 177 of /var/www/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryConnectionProvider.php: Call to undefined function SMW\SPARQLStore\curl_init()
Backtrace:
#0 /var/www/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryConnectionProvider.php(159): SMW\SPARQLStore\RepositoryConnectionProvider->connectTo(string)
#1 /var/www/mediawiki/extensions/SemanticMediaWiki/src/Connection/ConnectionManager.php(46): SMW\SPARQLStore\RepositoryConnectionProvider->getConnection()
#2 /var/www/mediawiki/extensions/SemanticMediaWiki/src/Store.php(581): SMW\Connection\ConnectionManager->getConnection(string)
#3 /var/www/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(512): SMW\Store->getConnection(string)
#4 /var/www/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(387): SMW\SPARQLStore\SPARQLStore->getConnection(string)
#5 /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php(166): SMW\SPARQLStore\SPARQLStore->setup(SMW\Options)
#6 /var/www/mediawiki/maintenance/doMaintenance.php(107): SMW\Maintenance\setupStore->execute()
#7 /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php(277): require_once(string)
#8 {main}

```

I tried bothVirtuoso (Virtuoso version 06.01.3127 on Linux (x86_64-pc-linux-gnu), Single Server Edition and Fuseki (version 4.1.0 in tomcat 9)

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/b3ac27fe09705a5d9c7bf6c49f0d78c291459ace/src/SPARQLStore/RepositoryConnectionProvider.php#L177

**Comment by JeroenDeDauw** [comment]
Perhaps you do not have the curl PHP extension installed

**Comment by krabina** [comment]
indeed. thank you.

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ATroubleshooting&type=revision&diff=81050&oldid=80544)

**Comment by krabina** [comment]
Well nothing escapes you! I wanted to hide my stupid mistake. It is already stated in the [requirements](https://www.semantic-mediawiki.org/wiki/Help:Installation#Environment). But the more places, the better :-)
