### ISSUE TITLE
OutputPageParserOutput->process() should check if $title is null

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#5077]

**Comment by hexmode** [comment]
@cicalese @JeroenDeDauw thoughts on this?  I don't have a backtrace for when this has happened, but I have seen it.

**Comment by cicalese** [comment]
That seems like a reasonable check and a reasonable fix to me.

**Comment by JeroenDeDauw** [comment]
This seems reasonable to me yes https://github.com/hexmode/SemanticMediaWiki/commit/268534b507c87c918b4f4e3c3566012cd88a76ee

**Comment by hexmode** [comment]
Thanks, y'all!
