### ISSUE TITLE
State of undocumented hook `SMW::DataUpdater::ContentProcessor`

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticMediaWiki#5078]
The hook `SMW::DataUpdater::ContentProcessor` has been added four years ago (#3122). Back then it was also documented in the `docs/technical/hooks.md`. This documentation apparently has been removed in the meantime, but the hook is still in the code.

Is is safe to bind code to this hook, or must it be seen as deprecated?

**Comment by kghbln** [comment]
Duplicate of #4846
