### ISSUE TITLE
Special property "Is a new page" no longer works

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#5082]
### Setup

- MediaWiki | 1.31.15 (d2a85fb)01:36, 6 September 2021
- PHP | 7.2.24-0ubuntu0.18.04.8 (apache2handler)
- MariaDB | 10.1.48-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.3 (5619c2d) 00:40, 30 March 2021

Also happens on more recent software combinations. 

### Issue

Refs: https://sourceforge.net/p/semediawiki/mailman/semediawiki-user/thread/AM8PR08MB5714446185A48609629C54F2E1A29%40AM8PR08MB5714.eurprd08.prod.outlook.com/#msg37354831

Even though the page was newly created and has only one revision `false` is assigned as a property value.

![grafik](https://user-images.githubusercontent.com/1104078/134531664-a3f6e6cf-2e73-4784-a249-3ff36b960c76.png)

**Comment by krabina** [comment]
I can confirm this also in MW 1.35. 
A test on smw.org can be seen here:
https://www.semantic-mediawiki.org/wiki/Special:Browse/:User:Krabina-5FBernhard-2FIs-5Fnew-5Fpage-5Ftest
I just created this page and hit browse properties and is new page is false, though it should be true
