### ISSUE TITLE
PageForm not working in MW 1.35.3

### ISSUE THREAD

**Issue by er-pooja** [SemanticMediaWiki/SemanticMediaWiki#5085]
### Setup
<html>
<body>

Product | Version
-- | --
MediaWiki | 1.35.3
PHP | 7.1.30 (apache2handler)
MySQL | 5.6.40
ICU | 50.1.2

</body>
</html>
- SMW version: 3.0.2
- Page Forms	5.2.1

<br>

### Issue
if we are trying to include the from   **{{Special:RunQuery/XXXXXXXXXXX }}**
 it shows below error .
**Error: No form was found on page**
```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by er-pooja** [comment]
even when we are changing the values namespace { id's  206 to 106 and 207 to 107 } in  extensions.json .
Then Page form works but Maps will not work.

**Comment by kghbln** [comment]
I'd ask [over there](https://www.mediawiki.org/wiki/Extension_talk:Page_Forms). I also [failed](https://sandbox.semantic-mediawiki.org/wiki/Query_form) to get it working with `{{Special:RunQuery/BooksQuery}}`: "You must specify a form name in the URL; the URL should look like "Special:RunQuery/<form name>". " The `#queryformlink:` parser function works though.
`
