### ISSUE TITLE
SMWInfolink::getText / Deprecated: Use of Linker::link with parameter $query as string ...

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#511]
```
Deprecated: Use of Linker::link with parameter $query as string (should be array) was deprecated in MediaWiki 1.20.
```

```
$link = $this->getLinker( $linker )->link(
    $title,
    $this->mCaption,
    array(),
    SMWInfolink::encodeParameters( $this->mParams, false )
);
```

`SMWInfolink::encodeParameters` returns a string while an array is expected.

SMWInfolink is missing a test which is why the deprecation notice has been caught yet.

refs #1590

**Comment by kghbln** [comment]
@nemobis Adding you here as the reporter of #2014 and adding cross-reference https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2014#issuecomment-261686027

**Comment by mwjames** [comment]
For the record on a private email I said to @nemobis that "... My support window for this week (== Saturday) has already been planned, so maybe next week I may have look at it (without a promise).".

**Comment by kghbln** [comment]
Thanks for the note! It will be great and much appreciated if this issue eventually vanishes.

**Comment by mwjames** [comment]
> so maybe next week I may have a look at it

Done.

**Comment by kghbln** [comment]
> Done.

Great, thanks a lot.
