### ISSUE TITLE
Version of elasticsearch that comes with semantic mediawiki is too recent for Elastica...

### ISSUE THREAD

**Issue by bertrandgorge** [SemanticMediaWiki/SemanticMediaWiki#5114]
### Setup

- SMW version: 3.2.3
- MW version: 1.35.2
- PHP version: 7.3.29
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.32

### Issue
Apparently SMW comes with version 6.8.2 of elasticsearch/elasticsearch, which is incompatible with elasticsearch-php version 6.7.2 that comes with the Elastica extension.

This can be fixed by keeping elasticsearch/elasticsearch at version 6.7.* in composer.local.json, but the best would be to change smw's own composer.json...?

See : https://phabricator.wikimedia.org/T267106#7451675

**Comment by jaideraf** [comment]
I confirm the findings: installing `"elasticsearch/elasticsearch": "6.7.x"` in composer.local.json fixes the `SMWElasticStore` feature that was broken. Changing [this line](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/bba13e801d6b774c7fb0781b0aead6638c737c86/composer.json#L55) to use "6.7.x" could be made?

**Comment by gesinn-it** [comment]
@bertrandgorge @jaideraf please feel free to try out PR #5115. @JeroenDeDauw CI reports same result after change.

**Comment by jaideraf** [comment]
Thanks @gesinn-it. Unfortunately I can't handle the git and composer thing to test appropriately the change. I can only say with certainty that after composer says:
```
- Downgrading elasticsearch/elasticsearch (v6.8.2 => v6.7.2): Extracting archive
```
I can use `SMWElasticStore` again. Maybe @bertrandgorge could make a better test.

**Comment by bertrandgorge** [comment]
Yes, perfect! With the dev-master branch on packagist it works perfectly. Once again thanks a lot all of you, I'm amazed by the reactivity of the team!

**Comment by JeroenDeDauw** [comment]
Looks like this needs to be reverted or changed. It makes SMW uninstallable with PHP 8

**Comment by JeroenDeDauw** [comment]
Why does SMW have a dependency on `elasticsearch/elasticsearch` anyway? I'm guessing and hoping this is not used unless you actually have MW configured to use elastic for search, or perhaps even only if you configure SMW to use it?

**Comment by jaideraf** [comment]
I don't know the answer, but maybe the intention was to make a built-in `elasticsearch` feature, I mean, without much effort for users to use it.

**Comment by gesinn-it** [comment]
MW itstelf seems to be not yet fully compatible with PHP 8: https://phabricator.wikimedia.org/T248925.

**Comment by bertrandgorge** [comment]
I don't know if elasticsearch is really required in SMW as it is embedded in elastica in any case (unless I'm missing something). The point was to keep elastica's version sync'ed with SMW's one. If elasticsearch can be removed from SMW without harming the integration that would be best of course.

**Comment by freephile** [comment]
SMW supports having [an Elasticstore backend](https://www.semantic-mediawiki.org/wiki/Help:$smwgDefaultStore) so I assume that's why it's in composer.json

**Comment by bertrandgorge** [comment]
> SMW supports having [an Elasticstore backend](https://www.semantic-mediawiki.org/wiki/Help:$smwgDefaultStore) so I assume that's why it's in composer.json

Sure - but would that make sense setting up when CirrusSearch is not set up on the instance ? I don't know that feature enough to tell.

**Comment by jaideraf** [comment]
> Sure - but would that make sense setting up when CirrusSearch is not set up on the instance ? I don't know that feature enough to tell.

@bertrandgorge The idea was not make CirrusSearch a dependency.

**Comment by JeroenDeDauw** [comment]
You can still install the package directly via Composer and it is listed as a required on https://www.semantic-mediawiki.org/wiki/Help:ElasticStore.
