### ISSUE TITLE
[CI] test failure: f-0801.json > Unmatched values in #2 (manual embedded)

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5116]
### Setup

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:66

**Comment by gesinn-it** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/f-0801.json

**Comment by jaideraf** [comment]
I am not a developer so I don't understand exactly what is going on here, but maybe [this change](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5111) could have altered the output of some tests, right? Not sure if it is the case here. I am just letting this note for some people who can interpret the test and the change.

**Comment by gesinn-it-gea** [comment]
@jaideraf good catch. This is really related. Now we need to understand, if the change breaks something or if it's sufficient to update the tests. ping @alex-mashin

**Comment by jaideraf** [comment]
@gesinn-it-gea it seems to me the that the other failures are also related to categories output: #5117 #5118 #5119 #5122 #5123 so all those tests have the same root cause.

**Comment by alex-mashin** [comment]
There is one failure left; and I am not sure that it is connected to #5111:
```
1) SMW\Tests\Integration\JSONScript\JSONScriptTestCaseRunnerTest::testCaseFile with data set "p-1110.json" ('/var/www/html/extensions/Sema...0.json')
#4 (violation of `mandatory_properties`, missing two properties, subobject) Counted properties include: []
Failed asserting that actual size 0 matches expected size 3.

/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:118
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:221
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/ParserTestCaseProcessor.php:147
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/ParserTestCaseProcessor.php:105
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/JSONScriptServicesTestCaseRunner.php:353
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/JSONScriptServicesTestCaseRunner.php:143
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/JSONScriptTestCaseRunner.php:235
/var/www/html/extensions/SemanticMediaWiki/tests/phpunit/DatabaseTestCase.php:173
/var/www/html/maintenance/doMaintenance.php:107
```

**Comment by jaideraf** [comment]
@alex-mashin following your steps, would'nt be change "P1110" to "Category:P1110" to resolve it?

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-1110.json#L116

**Comment by alex-mashin** [comment]
> @alex-mashin following your steps, wouldn't be change "P1110" to "Category:P1110" to resolve it?
> 
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-1110.json#L116

Already done in #5140.

**Comment by alex-mashin** [comment]
I suspect that the remaining test failure for MW 1.35 is due to the different _Has processing error_ subobject ID generated by SMW. In [my commit](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140/commits/5f669857134aa68d07cd0f3cc397e709b4239823) I have tried to replace it with the ID that my wiki had generated for this subobject, after I reproduced the test case, but this did not help.

**Comment by alex-mashin** [comment]
Can anyone approve #5140, if it's technically possible? After that there will be only one test failure for MW 1.35.
