### ISSUE TITLE
[CI] test failure: p-0301.json > Unmatched values in #0 #subobject with category annotation

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5117]
### Setup

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:96

**Comment by jaideraf** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0301.json#L17

**Comment by jaideraf** [comment]
This issue should be closed, fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140
