### ISSUE TITLE
[CI] test failure: p-0404.json > Unmatched values in #0 : vs. :: for:

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5119]
### Setup

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:150

**Comment by jaideraf** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0404.json#L24

**Comment by jaideraf** [comment]
This issue should be closed, fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140
