### ISSUE TITLE
[CI] test failure: p-1110.json > Unmatched values in #2 (violation of `mandatory_properties`, missing two properties)

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5120]
### Setup

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:178

**Comment by jaideraf** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-1110.json#L66

**Comment by jaideraf** [comment]
This issue should be closed, fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140
