### ISSUE TITLE
[CI] test failure: p-1111.json > Unmatched values in #1.2 (violation of `shape_constraint`, `max_cardinality` violation)

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5121]
### Setup

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:206

**Comment by jaideraf** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-1111.json#L102

**Comment by jaideraf** [comment]
This issue should be closed, fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140
