### ISSUE TITLE
[CI] test failure: Added Category And Changed Defaultsort Without Predefined Properties For New Page

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5122]
Failed asserting that 'SortForFoo SingleCategory' contains "Category:SingleCategory".

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:234

**Comment by jaideraf** [comment]
This issue should be closed, fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140
