### ISSUE TITLE
[CI] test failure: Import Of Record Values

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5123]
Failed asserting that 'Regression test Data type regression test Record type regression test' contains "Category:Regression test".

https://github.com/SemanticMediaWiki/SemanticMediaWiki/runs/4094543026?check_suite_focus=true#step:10:245

**Comment by jaideraf** [comment]
This issue should be closed, fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5140
