### ISSUE TITLE
Move Content::fillParserOutput method that don't belong in Content to ContentHandler

### ISSUE THREAD

**Issue by roman-stolar** [SemanticMediaWiki/SemanticMediaWiki#5129]
### Issue

Detailed description of the issue and a [stack trace](https://phabricator.wikimedia.org/T295110) if applicable:

Since starting with version 1.38 we move Content::getParserOutput and Content::fillParserOutput to ContentHandler we should also move it in SemanticMediaWiki (SchemaContent -> SchemaContentHandler). But as SemanticMediaWiki used in older version, we should leave the old SchemaContent::fillParserOutput and reuse it for the new one SchemaContentHandler::fillParserOutput.

More details in ticket description: https://phabricator.wikimedia.org/T287158

**Comment by roman-stolar** [comment]
PR: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5130

**Comment by JeroenDeDauw** [comment]
I believe this issue also effects the Maps extension. I had to disable MW 38 deprecation warnings yesterday: https://github.com/ProfessionalWiki/Maps/commit/e7a42674e66ef5b6e0b163130b804532c3143dc4 due to these failures https://github.com/ProfessionalWiki/Maps/runs/4145028908?check_suite_focus=true
