### ISSUE TITLE
Benchmark HHVM 3.3 vs. Zend PHP 5.6

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#513]
Relates to #512 and is using the [`semantic-mediawiki-benchmark`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Benchmark) tests.

Comparison between benchmarks run on HHVM 3.3 and Zend (PHP 5.6) shows that HHVM has a clear advantage over Zend when running Semantic MediaWiki related benchmarks.

The influence of hardware during both tests are not negligible but the overall trend shows that HHVM is leading for all benchmark tests.

The benchmark test suite (`--group semantic-mediawiki-benchmark`) recreates content from scratch (using `benchmarkPageCopyThreshold`) but unfortunately running Zend for more than "3K page" exceeds the current timeout limit on Travis (10 min) making it only feasible to have HHVM to return benchmarks for the "5K", "10K" page load scenario.
### QueryEngine (using MySQL)
- (C)ount queries on HHVM are slightly slower compared to the same queries executed on Zend
- (I)nstance queries are faster on HHVM than on Zend
- (S)erialization of query results is faster on HHVM than on Zend
## Using Travis

| Scenario* | Benchmarks | Logs | Comments |
| --- | --- | --- | --- |
| 1K | [1K page HHVM/Zend comparison](https://gist.github.com/mwjames/cc1a694338d58846238f/revisions)** | [HHVM Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33354006/log.txt), [Zend Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33354005/log.txt) | (*\* red marked lines are benchmarks created during the HHVM run) |
| 3K | [3K page HHVM/Zend comparison](https://gist.github.com/mwjames/fca7d2806d8195bc382f/revisions)** | [HHVM Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33417577/log.txt), [Zend Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33417576/log.txt) | (*\* red marked lines are benchmarks created during the HHVM run) |
| 5K | [5K page HHVM only](https://gist.github.com/mwjames/623be99f835a056e5381/revisions) | [HHVM Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33355202/log.txt), [HHVM Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33422853/log.txt), Zend N/A | "5K page" scenario, 10K `smw_objects_id`'s will be available during the benchmark test |
| 10K | [10K page HHVM only](https://gist.github.com/mwjames/27ccebab76e5298f3642/revisions) | [HHVM Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/33421623/log.txt), Zend N/A |  |
| HHVM 1K vs 5K | [1K vs 5K comparison](https://gist.github.com/mwjames/d0c538b73be40a243d0b/revisions) |  |  |
| HHVM 5K vs 10K | [5K vs 10K comparison](https://gist.github.com/mwjames/3364132946d2cb273a49/revisions) |  |  |

A scenario\* is set by using `benchmarkPageCopyThreshold`.

**Comment by nemobis** [comment]
If I see correctly, most of the time save came from the serialize and RebuildData phase, right?
