### ISSUE TITLE
Issue 5141

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#5141]
### Setup

- MediaWiki | 1.35.0-rc.2 (5f6c9d1)16:32, 21 August 2020
- PHP | 7.2.24-0ubuntu0.18.04.10 (apache2handler)
- MariaDB | 10.1.48-MariaDB-0ubuntu0.18.04.1
- ICU | 60.2
- Semantic MediaWiki | 3.2.3 (5619c2d) 23:40, 29 March 2021

### Issue

To be filled.

**Comment by kghbln** [comment]
@hexmode @gesinn-it-gea @JeroenDeDauw FYI

**Comment by JeroenDeDauw** [comment]
Just double checked that it is not April 1st. It isn't. So I am confus

**Comment by JeroenDeDauw** [comment]
What is this about? Please close or put a clear title and description.

**Comment by kghbln** [comment]
Well yeah. I leave this to you folks. I am out of this one. No worries.
