### ISSUE TITLE
SemanticMediaWiki: "Call to undefined method ParserCache::getETag()"

### ISSUE THREAD

**Issue by nypolitics** [SemanticMediaWiki/SemanticMediaWiki#5145]
I installed Mediawiki 1.37.0 via cpanel. After installing SMW 3.2.3, I get this error (via $wgShowExceptionDetails = true;):

[YZ8I7OuCFOLcDEB6lTWd8gAAAB0] /index.php?title=Main_Page Error: Call to undefined method ParserCache::getETag()

Backtrace:

from /home4/jeo4yxva/mysite.com/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(710)
#0 /home4/jeo4yxva/insidenypolitics.com/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onArticleViewHeader(Article, NULL, boolean)
#1 /home4/jeo4yxva/insidenypolitics.com/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#2 /home4/jeo4yxva/insidenypolitics.com/includes/HookContainer/HookRunner.php(856): MediaWiki\HookContainer\HookContainer->run(string, array)
#3 /home4/jeo4yxva/insidenypolitics.com/includes/page/Article.php(568): MediaWiki\HookContainer\HookRunner->onArticleViewHeader(Article, NULL, boolean)
#4 /home4/jeo4yxva/insidenypolitics.com/includes/page/Article.php(506): Article->generateContentOutput(User, ParserOptions, integer, OutputPage, array)
#5 /home4/jeo4yxva/insidenypolitics.com/includes/actions/ViewAction.php(74): Article->view()
#6 /home4/jeo4yxva/insidenypolitics.com/includes/MediaWiki.php(538): ViewAction->show()
#7 /home4/jeo4yxva/insidenypolitics.com/includes/MediaWiki.php(320): MediaWiki->performAction(Article, Title)
#8 /home4/jeo4yxva/insidenypolitics.com/includes/MediaWiki.php(925): MediaWiki->performRequest()
#9 /home4/jeo4yxva/insidenypolitics.com/includes/MediaWiki.php(559): MediaWiki->main()
#10 /home4/jeo4yxva/insidenypolitics.com/index.php(53): MediaWiki->run()
#11 /home4/jeo4yxva/insidenypolitics.com/index.php(46): wfIndexMain()
#12 {main}

This error appears when I try to access MAIN_PAGE, as well as every page but Special:. If I disable SMW, MediaWiki 1.37.0 works fine. Previous MediaWiki versions had worked fine with SMW.

**Comment by JeroenDeDauw** [comment]
SMW 3.2.3 does not run on MW 1.37. See https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md.

If you want to run SMW on MW 1.37 you will need to use the master branch for now.

**Comment by Seb35** [comment]
And this specific issue was fixed by #5019, so it can be closed.
