### ISSUE TITLE
After 'composer update --no-dev', semantic no longer loads

### ISSUE THREAD

**Issue by yombo** [SemanticMediaWiki/SemanticMediaWiki#5148]
Updated semantic mediawiki, here's the console output:
```
composer update --no-dev
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 7 updates, 0 removals

  - Upgrading mediawiki/semantic-extra-special-properties (dev-master 122f48f => dev-master 2250a16)
  - Upgrading mediawiki/semantic-media-wiki (dev-master 21b4a5a => dev-master c96656f)
  - Upgrading sebastian/exporter (3.1.3 => 3.1.4)
  - Upgrading symfony/console (v5.3.10 => v5.3.11)
  - Upgrading symfony/deprecation-contracts (v2.4.0 => v2.5.0)
  - Upgrading symfony/var-dumper (v5.3.10 => v5.3.11)
  - Upgrading symfony/yaml (v5.3.6 => v5.3.11)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading mediawiki/semantic-media-wiki (dev-master c96656f)
  - Downloading mediawiki/semantic-extra-special-properties (dev-master 2250a16)
  - Upgrading mediawiki/semantic-media-wiki (dev-master 21b4a5a => dev-master c96656f): Extracting archive
  - Upgrading mediawiki/semantic-extra-special-properties (dev-master 122f48f => dev-master 2250a16): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
```

Now, semantic mediawiki won't load. Nothing in the versions page. If I add a print statement to the GlobalFunctions.php::enableSemantics function, it gets displayed on the webpage. So, the function is being called.

I've ran the update.php script, nothing. If I run the semantic mediawiki rebuild all, I get:
`You need to have SMW enabled in order to run the maintenance script!`

I've really no clue what to do. I've even tried to downgrade to the previous version (using composer), and still nothing.

If I have multiple enableSemantics() calls to LocalSettings, no error is displayed.
MediaWiki Version: 1.36.2
PHP 7.4.25

Semantic MediaWiki: dev-master, currently on: c96656fcf56928eecf2f29938e812a8a6a282862:
```
           "name": "mediawiki/semantic-media-wiki",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/SemanticMediaWiki/SemanticMediaWiki.git",
                "reference": "c96656fcf56928eecf2f29938e812a8a6a282862"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/SemanticMediaWiki/SemanticMediaWiki/zipball/c96656fcf56928eecf2f29938e812a8a6a282862",
                "reference": "c96656fcf56928eecf2f29938e812a8a6a282862",
                "shasum": ""
            },
```

**Comment by malberts** [comment]
After #5144, if you run master you need to add this to your LocalSettings:
   
    wfLoadExtension( 'SemanticMediaWiki' );

The documentation will probably only start referring to this once it is tested more.

**Comment by yombo** [comment]
A million thank you's!!  I've been reviewing commit code trying to find the cause. :-) Doing this, then running update.php fixed it all up. :-)

**Comment by kghbln** [comment]
> wfLoadExtension

We somehow need to add this to the install documents. Created https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5149 for this.
