### ISSUE TITLE
Issue with rendering strings with special characters, undocumented bug 

### ISSUE THREAD

**Issue by renoirb** [SemanticMediaWiki/SemanticMediaWiki#515]
Stumbled upon an edge-case that shows an error message in the page render. 

After looking at the code we see a TODO note in [`SMWWikiPageValue::parseUserValue`, line 111](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/be3cd27f74597165bdb7c0346692455cd790745d/includes/datavalues/SMW_DV_WikiPage.php#L111)

    // TODO: Escape the text so users can see punctuation problems (bug 11666).

The bug is not documented anywhere else, creating it here.

## Context

This issue arose when trying to upgrade WebPlatform.org installation from 

Software    | From        | To
--------------|--------------|----------------
MediaWiki  | 1.22wmf5 | 1.24wmf16
SMW          | 1.8.0.5      |  2.0

## The affected code
 
When we have pages with special characters in them, e.g. (`&#58;active`), the page 

## Observations

1. When we `var_dump($value)`, we get the string inserted in the class method only in one specific situation: when we clear the cache (memcache, redis)
2. Called from `SMW_DataValue::setUserValue($value)`, $value has something only on first render after clearing memcached/redis.
3. Echoing from both `SMW_DataValue::setUserValue($value)` and `SMWWikiPageValue::parseUserValue($value)`  shows in output only on first load
4. Hard to figure out where the method gets called. Is it by reflexion, or magic setter/getter? Maybe at `DataValueFactory::newTypeIdValue()` but not sure.

It seems clear that the call to the method is called only on first render, but not subsequent ones. But for some reason, maybe due to class property visibility, it gets non reachable. 

I suspect its caused by caching and whether or not its just giving the page already rendered from cache or not. But the strange behavior is that even though I set  in parent  `SMW_DataValue::setUserValue($value)`  a `if(empty($value)){/*...subsequent loads, return void ...*/}` the error message is shown anyway. 

## Temporary ~~fix~~ way to silence the error

Commented full `SMWWikiPageValue::parseUserValue()` method body.

**Comment by mwjames** [comment]
We have various tests in order to verify that special characters are handled correctly. Unless there is evidence on [0] about a potential conflict or mistreatment of certain characters we are unable to follow up on this issue and closing it as invalid.

[0] http://sandbox.semantic-mediawiki.org
