### ISSUE TITLE
Link to join team of contributers on github doesnt work 404 not found

### ISSUE THREAD

**Issue by mshartdreams** [SemanticMediaWiki/SemanticMediaWiki#5158]

**Comment by JeroenDeDauw** [comment]
Where is this link?

**Comment by morganfletcher** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Pre-release_testing

**Comment by hexmode** [comment]
This one? https://www.semantic-mediawiki.org/wiki/Help:Pre-release_testing

Link on that page points to https://github.com/orgs/SemanticMediaWiki/teams/testers which works for me.

The other link on that page is a nabble email archive link which doesn't work.  We should update the nabble links (@kghbln ?) with other ones.  The wayback machine has a [copy](https://web.archive.org/web/20201031200245/http://wikimedia.7.x6.nabble.com/Call-for-testers-td5022160.html).

**Comment by morganfletcher** [comment]
@hexmode https://github.com/orgs/SemanticMediaWiki/teams/testers returns a 404 for me.

**Comment by JeroenDeDauw** [comment]
Guess that page is only for organization members and that Karsten did not realize this when writing the docs. You could remove the link from the docs.

**Comment by hexmodenew** [comment]
I've updated the [pre-release testing page](https://www.semantic-mediawiki.org/wiki/Help:Pre-release_testing) with instructions and added an issue template to help with this process,
