### ISSUE TITLE
SMW master vanished after MW update to 1.36.3

### ISSUE THREAD

**Issue by stefahn** [SemanticMediaWiki/SemanticMediaWiki#5163]
I updated my wikis to the latest MW version. One of my installs uses MW 1.36.3 now **and** the SMW master version. After updating MW via "git pull" and SMW via "composer update --no-dev" SMW functionality no longer works. SMW is not listed in Special:Version either.

I ran maintenance/update.php which worked. If I run /SemanticMediaWiki/maintenance/rebuildData.php it says "You need to have SMW enabled in order to run the maintenance script!".

I do have the "enableSemantics" call in LocalSettings.php and it all used to work until yesterday...

Anyone knows what's going on here?

### Setup

- SMW version: dev-master (d17a319)
- MW version: 1.36.3 (00393d6)
- PHP version: PHP | 7.4.13 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL | 8.0.25-15

**Comment by jaideraf** [comment]
See https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-4.0.0.md#upgrading

**Comment by stefahn** [comment]
Thanks, that fixed it. I think this is a change that needs to be highlighted if 4.0 is released publicly.
