### ISSUE TITLE
RDF 1.1 support especially IRI support

### ISSUE THREAD

**Issue by galaxyeye** [SemanticMediaWiki/SemanticMediaWiki#517]
Since RDF 1.1 is out which supports IRI instead of URI to identify resources, i think it's time to add RDF 1.1 support now.
(see : http://www.w3.org/TR/2014/REC-rdf-schema-20140225/#PER-changes)

It's frankly to deal with unicode properties when exporting a page, for example:

http://www.qiwur.com/wiki/Special:%E5%AF%BC%E5%87%BARDF/%E4%B8%89%E6%98%9F_NP532U3X-KK2CN_13.3%E8%8B%B1%E5%AF%B8%E7%AC%94%E8%AE%B0%E6%9C%AC%E7%94%B5%E8%84%91_(I5_2537M_4G_500G_%E6%A0%B8%E8%8A%AF%E6%98%BE%E5%8D%A1_DOS_%E8%93%9D%E7%89%994.0)_%E6%9B%9C%E6%9C%88%E9%BB%91

Terrible URL:(

**Comment by mwjames** [comment]
Expected to be fixed by #2207.
