### ISSUE TITLE
Properties not updating on page save

### ISSUE THREAD

**Issue by mitchelln** [SemanticMediaWiki/SemanticMediaWiki#518]
I have what is essentially a couple of knowledge base sites that use a 
number of forms and templates to capture and query information.

Since upgrading to SMW 2.0 on MW 1.23.2 I'm seeing the problem that I 
haven't seen for a very long time.

When a page is edited via a form and a property value changed then saved, queries 
on other pages do not pick up the new value. The job queue is empty. I 
even have a cron job that kicks off runJobs.php every 15 minutes. I've 
also tried adjusting the documented cache and queue related settings, 
but nothing seems to help. I've even tried disabling all caching altogether.

This used to be a problem years ago with SMW, but was solved in 1.7/1.8. 
In fact, if I downgrade the site to 1.8.0.5 the problem goes away. My 
other sites running sub 1.9.2 SMW versions are fine as well (and have 
been for a couple of years now), which is why this became so noticeable 
when I upgraded these particular two instances.

Is this expected behaviour with 2.0, or am I missing a setting?

Thanks.

**Comment by mwjames** [comment]
Cannot be observed at [0].

[0] http://sandbox.semantic-mediawiki.org
