### ISSUE TITLE
Fatal error: Uncaught Error: SMW\Setup::initExtension()

### ISSUE THREAD

**Issue by bldevuid798** [SemanticMediaWiki/SemanticMediaWiki#5202]
### Setup

- SMW version: dev-master
- MW version: 1.37.1
- PHP version: 8.1.1
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.4.22

### Issue

On enabling the SMW extension using `wfLoadExtension( 'SemanticMediaWiki' );` and `enableSemantics();` I get the following error

> `Fatal error: Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in ..\extensions\SemanticMediaWiki\includes\SemanticMediaWiki.php:46`

**Comment by hexmode** [comment]
I think this depends on [ensuring MediaWiki itself is compatible with PHP 8](https://phabricator.wikimedia.org/T248925) first.

**Comment by hexmode** [comment]
[More info](https://php.watch/versions/8.1/GLOBALS-restrictions) on this change in PHP 8.1.

**Comment by hexmode** [comment]
> It's actually complaining about passing a **string** by reference. You can't do that in any version of PHP.

That is what php 7 is complaining about.  And php 8.0.  But php 8.1 only prints out one "here" and complains about line that has the `$GLOBALS`.

**Comment by freephile** [comment]
I see. The change in behavior for PHP 8+ is definitely one to be aware of. I just didn't want you to be misled by the string test.

**Comment by bldevuid798** [comment]
> As a work-around, try php8.0. It appears to be complaining about passing `$GLOBALS` by reference.
> 
> For example, see this test script:
> 
> ```
> <?php
> 
> class checkPass {
> 	static function method( &$arg ) {
> 		echo "here\n";
> 	}
> }
> 
> $var = "value";
> checkPass::method( $var );
> checkPass::method( $GLOBALS );
> checkPass::method( "string" );
> ```
> 
> When I run with php8.0, I get:
> 
> ```
> $ php8.0 tmp.php
> here
> here
> PHP Fatal error:  Uncaught Error: checkPass::method(): Argument #1 ($arg) cannot be passed by reference in tmp.php:12
> Stack trace:
> #0 {main}
>   thrown in tmp.php on line 12
> ```
> 
> With php 8.1, I get:
> 
> ```
> $ php8.1 tmp.php
> here
> PHP Fatal error:  Uncaught Error: checkPass::method(): Argument #1 ($arg) cannot be passed by reference in tmp.php:11
> Stack trace:
> #0 {main}
>   thrown in tmp.php on line 11
> ```
> 
> Interestingly, PHP 7.4, 7.3 and 7.2 all refuse to run:
> 
> ```
> $ php tmp.php
> PHP Fatal error:  Only variables can be passed by reference in tmp.php on line 12
> ```

Are you suggesting that PHP 8.0 also results in an error? I ran the same setup a few months back using PHP 8.1.1 and it worked fine. BTW, if I disable (not uninstall) the extension, MW works just fine.

**Comment by bldevuid798** [comment]
I have been able to test and can confirm that things are now working with PHP8.0 - The SMW ext is enabled, the Wiki loads fine, the ext is being picked up on `Special:Version` and there is no longer any error being reported. Thanks @hexmode and @freephile. Closing.
