### ISSUE TITLE
rebuildData: You need to have SMW enabled in order to run the maintenance script!

### ISSUE THREAD

**Issue by Martien** [SemanticMediaWiki/SemanticMediaWiki#5213]
### Setup

See http://pearllanguage.org/Special:Version

- SMW version: 4.0.0
- MW version: 1.35.5
- PHP version: 7.4.27 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 8.0.11

### Issue

1. Upgrading from MW 1.30.0 to 1.35.5 (preferably even to 1.37.1).
2. Followed `https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md`
3. Fails on step 5: `php extensions/SemanticMediaWiki/maintenance/rebuildData.php -v`
   - You need to have SMW enabled in order to run the maintenance script!

LocalSettings.php does have `enableSemantics( 'pearllanguage.org' );`

What am I missing? How to fix?

BTW - Did get MW 1.30.0 to 1.31.1 and SMW working: see http://pareltaal.nl/Speciaal:Softwareversie

**Comment by malberts** [comment]
Do you also have `wfLoadExtension( 'SemanticMediaWiki' );`?

This is new in SMW 4:
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md#step-3

**Comment by Martien** [comment]
Aargh. This does the trick. Replaces the `enableSemantics()` with `wfLoadExtension`.

Thanks. I new there ware changes in this area. I only found it (very) hard to find.

update.php and rebuildData now terminate successfully.

**Thank you!** @malberts

**Comment by malberts** [comment]
You should have both `wfLoadExtension()` and `enableSemantics()`. Not sure what happens if you replace it.

**Comment by Martien** [comment]
BTW, I see that both lines are needed. Fixed that as well.

**Comment by Martien** [comment]
@JeroenDeDauw Question that has been burning on my lips for years (since I started using SMW): Your name sounds so Ducth (like mine as well). Are you Dutch? Still live in NL? (Curiosity killed the cat)

**Comment by JeroenDeDauw** [comment]
I'm Belgian, have lived just over the Dutch boarder (Hulst) for 10 years and now live in Berlin :)

**Comment by Martien** [comment]
👍
