### ISSUE TITLE
Article::$mTitle is deprecated since MediaWiki 1.35

### ISSUE THREAD

**Issue by Martien** [SemanticMediaWiki/SemanticMediaWiki#5214]
### Setup
Latest stable version to date.
Please see: http://aardnoot.nl/Speciaal:Softwareversie for details.

### Issue
Deprecated: Accessing Article::$mTitle is deprecated since MediaWiki 1.35 [Called from SMW\MediaWiki\Page\ConceptPage::getHtml in /www/aardnoot.nl/mediawiki-1.37.1/extensions/SemanticMediaWiki/src/MediaWiki/Page/ConceptPage.php at line 90] in /www/aardnoot.nl/mediawiki-1.37.1/includes/debug/MWDebug.php on line 375

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
- visit any concept listed on http://aardnoot.nl/Speciaal:Concepten

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/153445457-753bb1a5-6b94-4c75-a3eb-bc0d78753df4.png)
