### ISSUE TITLE
Error page gives HTTP 200 where HTTP 500 is expected

### ISSUE THREAD

**Issue by djoris** [SemanticMediaWiki/SemanticMediaWiki#5228]
### Setup

- SMW version: 3.1.6 (smw:2019-09-23)
- MW version: 1.31.16
- PHP version: 7.3
- DB system (MySQL, Blazegraph, etc.) and version: MySQL

### Issue

When a wiki breaks, an error page is shown at any URL instead of the.
This error page is given with the HTTP status 200 (OK), while a status 500 is expected (Internal Server Error). The latter would trigger monitoring software.

This occurst at least with the error "`[Semantic MediaWiki](https://www.semantic-mediawiki.org/) was installed and enabled but is missing an appropriate [upgrade key](https://www.semantic-mediawiki.org/wiki/Help:Upgrade).`")
TBH not sure if this is a SMW of MW error page and thus issue.
![image](https://user-images.githubusercontent.com/790925/162443240-e7aebf3e-6bf9-4035-88c5-68b95e1cd8a9.png)

**Comment by kghbln** [comment]
I do not think if 500 is expected however 200 is definitively not the correct status. Anyhow a very valid issue.

**Comment by djoris** [comment]
> I do not think if 500 is expected however 200 is definitively not the correct status. Anyhow a very valid issue.
Curious, what status code do you expect?

**Comment by kghbln** [comment]
At least nothing in the 5xx range since the server is working properly and delivering a website as the software provisions. Some 2xx other than 200 could match reality better or even a custom 9xx. Not sure what monitoring software does with such codes.

**Comment by YOUR1** [comment]
> At least nothing in the 5xx range since the server is working properly and delivering a website as the software provisions. Some 2xx other than 200 could match reality better or even a custom 9xx. Not sure what monitoring software does with such codes.

I don't fully agree - A 503 should be fine for this:
The server cannot handle the request (because it is overloaded or **down for maintenance**). Generally, this is a temporary state. [[65]](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#cite_note-66)

**Comment by YOUR1** [comment]
Also; this issue seems already to be fixed in the master repo: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SetupCheck.php#L342; just not in 3.2.x.
