### ISSUE TITLE
Semantic Bundle 4.0 installs OK, 6.0 does not

### ISSUE THREAD

**Issue by jslagle** [SemanticMediaWiki/SemanticMediaWiki#5229]
Steps which work when I install Semantic Bundle 4.0 fail when I change "~4.0" to "~6.0" in the Composer require command.
Here are the steps I follow:

1. Run these commands to make sure the machine is up to date, and Composer is installed: `sudo apt update && sudo apt upgrade -y && sudo apt install composer -y && echo "OK: All Commands Successful" || echo "ERROR: Something Went Wrong"`
2. Add these two lines at the end of /etc/mediawiki/LocalSettings.php:
 **enableSemantics( '**_MyHostName_**' );**
 **require_once '/var/lib/mediawiki/extensions/SemanticBundle/SemanticBundle.php';**
(NOTE: instructions at https://github.com/ProfessionalWiki/SemanticBundle are different, saying to use "**require_once \_\_DIR\_\_ . '/extensions/SemanticBundle/SemanticBundle.php';**", apparently assuming NOT ONLY that the \_\_DIR\_\_ will change to the location of LocalSettings.php, BUT ALSO that LocalSettings.php resides where the extensions folder is; but on my system, LocalSettings.php is a symbolic link to **/etc/mediawiki/LocalSettings.php**...so \_\_DIR\_\_ was changing to **/etc/mediawiki** not **/var/lib/mediawiki**, which of course was breaking my install; that's why I ditched "\_\_DIR\_\_ ."and added **/var/lib/mediawiki** in the **require_once**)
3. So that Composer can have access it needs without having to run as root, transfer ownership of all root:root files to my user account (which is not www-data) using: `sudo chown -R $USER:$USER /usr/share/mediawiki /var/lib/mediawiki/config /var/lib/mediawiki/extensions`
4. Last but not least, run the following commands to actually install Semantic Bundle 4.0:
`cd /usr/share/mediawiki/ &&
COMPOSER=composer.local.json composer require --no-update mediawiki/semantic-bundle:~4.0 &&
composer update --no-dev &&
composer update mediawiki/semantic-bundle --no-dev -o &&
php maintenance/update.php &&
echo "OK: All Commands Successful" || echo "ERROR: Something Went Wrong"`

The commands in that script on step 4 are an adaptation of what was posted at https://github.com/ProfessionalWiki/SemanticBundle. I arrived at those commands as the result of trial-and-error fiddling around trying to make the install work on my system (this is the same approach which let me to hard-code **/var/lib/mediawiki** in LocalSettings.php, as mentioned above...in short, none of the installation instructions I found at https://github.com/ProfessionalWiki/SemanticBundle worked "out of the box" for me).

At any rate, this procedure seems to install Semantic Bundle 4.0 just fine; and it is repeatable (meaning I can run the script in step 4 multiple times, and it always works for me).

PROBLEM: When I change "~4.0" to "~6.0" in step 4 above, I would expect to get the newer Semantic Bundle installed. What actually happens (even if I just restored the machine from a backup, and had to start on step 1) is that update.php fails with a message which implausibly, if not comically, seems to suggest SemanticMediaWiki is not installed:

> PHP Fatal error:  Uncaught ExtensionDependencyError: SemanticResultFormats requires SemanticMediaWiki to be installed.
> ModernTimeline requires SemanticMediaWiki to be installed.
> SemanticExtraSpecialProperties requires SemanticMediaWiki to be installed.
> SemanticCompoundQueries requires SemanticMediaWiki to be installed.
>  in /usr/share/mediawiki/includes/registration/ExtensionRegistry.php:407
> Stack trace:
> #0 /usr/share/mediawiki/includes/registration/ExtensionRegistry.php(231): ExtensionRegistry->readFromQueue()
> #1 /usr/share/mediawiki/includes/Setup.php(161): ExtensionRegistry->loadFromQueue()
> #2 /usr/share/mediawiki/maintenance/doMaintenance.php(91): require_once('/usr/share/medi...')
> #3 /usr/share/mediawiki/maintenance/update.php(253): require_once('/usr/share/medi...')
> #4 {main}
>   thrown in /usr/share/mediawiki/includes/registration/ExtensionRegistry.php on line 407

OBSERVATION: Having received the above failure, I can re-run the script with "~4.0" instead of "~6.0", and it seems to install Semantic Bundle 4.0 perfectly fine.

VERSIONS OF SOFTWARE I AM USING: On my system, running _5.10.0-12-amd64 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux_, and having installed with `sudo apt install mediawiki` I am running MediaWiki 1:1.35.4-1+deb11u2.

**Comment by JeroenDeDauw** [comment]
There is a bug in the 6.0.0 release causing the issue you ran into. It should be fixed in the just released 6.0.1. So if you re-run with `~6.0` it should work now.

**Comment by jslagle** [comment]
Good news/bad news. The bad news is that, when I tried re-running with `~6.0`, Composer was still downloading SemanticBundle.php 6.0.0; I also tried re-running with `~6.0.1` and got this complaint:"
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires mediawiki/semantic-bundle ~6.0.1, found mediawiki/semantic-bundle[dev-dependabot/composer/mediawiki/mermaid-tw-3.0.1, dev-master, 1.0.0, 2.0.0, 3.0.0, ..., 3.2.0, 4.0.0, 5.0.0, 6.0.0] but it does not match the constraint.
The good news is that manually editing my copy of **/var/lib/mediawiki/extensions/SemanticBundle/SemanticBundle.php** and pasting a copy of the 6.0.1 content from GitHub solved the problem very nicely indeed.

So I am definitely able to run version 6.0.1 now, albeit with a little manual override.
