### ISSUE TITLE
LinksUpdateConstructed hook deperecated in 1.38

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#5231]
### Issue

Starting in 1.38 the [LinksUpdateConstructed](https://www.mediawiki.org/wiki/Manual:Hooks/LinksUpdateConstructed) is deprecated and emits warnings

```
PHP Deprecated:  Use of LinksUpdateConstructed hook was deprecated in MediaWiki 1.38. [Called from SMW\MediaWiki\Hooks::register in /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /var/www/html/w/includes/debug/MWDebug.php on line 377
```

**Comment by saturnalium** [comment]
Having the same issue:

`Use of LinksUpdateConstructed hook was deprecated in MediaWiki 1.38. [Called from SMW\\MediaWiki\\Hooks::register in /var/www/.../extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /var/www/.../includes/debug/MWDebug.php on line 377`

**Comment by Nikerabbit** [comment]
> This issue is impeding editing globally.

Deprecation warnings are just log messages and do not impede anything.

Also, this was fixed in https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/47669b91a4bb9d0ed95f40a143a2b56f70f2aa6e but there hasn't been a new release which includes this fix.
