### ISSUE TITLE
Querying for "last editor is" retrieves wrong value

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5235]
### Setup

- SMW version: 3.2.3 (5619c2d)
- MW version: 1.35.5
- PHP version: 7.3.33 (litespeed)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.34-MariaDB

### Issue

Querying for the built-in property "last editor is" retrieves a wrong value, different from {{REVISIONUSER}} (which holds the correct value). The wrong value is shown with the #show parser function as well as in the browse properties interface. Thus, it seems that the values is not set correctly.

I have never seen this before, but the above installation is the one where this is critical, so this but might be around without anybody noticing. 

Maybe someone can look into their installations and see if they can reproduce it?

**Comment by krabina** [comment]
running rebuildData.php did not help

**Comment by gesinn-it-gea** [comment]
... is it showing the previous editor (one step behind so to say)?

**Comment by krabina** [comment]
Can someone please edit this page:
https://www.semantic-mediawiki.org/wiki/Semantic_Annotations
(you can see a test for this at the bottom)

**Comment by jaideraf** [comment]
@krabina done

**Comment by krabina** [comment]
Hmm. Is working correctly in smw.org

**Comment by gesinn-it-gea** [comment]
try to examine the user IDs. Maybe you see a pattern, like (<expected user id> - 1).

**Comment by krabina** [comment]
Indeed it happens only with 3 specific users. With 2 other uses, the info is correct. So I am closing this. Maybe a messed up user-table.

**Comment by gesinn-it-gea** [comment]
tip: check if there are duplicate entries / names in the user table
