### ISSUE TITLE
Sorting 

### ISSUE THREAD

**Issue by metro3** [SemanticMediaWiki/SemanticMediaWiki#5240]
Hi I need your help when it come to a certain wiki before the fandom design change the Property:Unit type of gundam.fandom the units were in alphabetical order by the name of the units not the unit type here's a link(https://gundam.fandom.com/wiki/Property:Unit_Type) now the admins didn't edit the order or the code I believe that the design change caused a bug to rearranged the order which starts with numbers to z and I think it might be a bug that caused it

**Comment by jaideraf** [comment]
If I understand correctly, it seems there is not an issue anymore. So I am closing this now.
