### ISSUE TITLE
Possible Reflected XSS vulnerability in Special:Ask

### ISSUE THREAD

**Issue by justinclloyd** [SemanticMediaWiki/SemanticMediaWiki#5262]
### Setup

- SMW version: 3.2.3
- MW version: 1.36.4
- PHP version: 7.4.28 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.12

### Issue

There is a possible "reflected XSS" vulnerability in Special:Ask. Given that it's a potential security risk to, let me know if there is a way I can submit the details privately. I can send a link that clearly demonstrates the issue.

**Comment by JeroenDeDauw** [comment]
Mail me at jeroendedauw@gmail.com

**Comment by justinclloyd** [comment]
> Mail me at [jeroendedauw@gmail.com](mailto:jeroendedauw@gmail.com)

Sent, thanks!

**Comment by JeroenDeDauw** [comment]
Confirmed on SMW 3.2.3

**Comment by kghbln** [comment]
Probably high time to deal with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5248
