### ISSUE TITLE
errors on update script

### ISSUE THREAD

**Issue by grantiago** [SemanticMediaWiki/SemanticMediaWiki#5265]
`/public_html$ php maintenance/update.php`

`PHP Fatal error:  Uncaught Error: SMW\Setup::registerExtensionCheck(): Argument #1 ($vars) cannot be passed by reference in /var/public_html/extensions/SemanticMediaWiki/SemanticMediaWiki.php:72
Stack trace:
#0 /var/public_html/extensions/SemanticMediaWiki/SemanticMediaWiki.php(18): SemanticMediaWiki::load()
#1 /var/public_html/vendor/composer/autoload_real.php(73): require('...')
#2 /var/public_html/vendor/composer/autoload_real.php(63): composerRequire_mediawiki_vendor()
#3 /var/public_html/vendor/autoload.php(7): ComposerAutoloaderInit_mediawiki_vendor::getLoader()
#4 /var/public_html/includes/Setup.php(107): require_once('...')
#5 /var/public_html/maintenance/doMaintenance.php(91): require_once('...')
#6 /var/public_html/maintenance/update.php(253): require_once('...')
#7 {main}
  thrown in /var/public_html/extensions/SemanticMediaWiki/SemanticMediaWiki.php on line 72` 

    [MediaWiki](https://www.mediawiki.org/)	1.35.0
    [PHP](https://php.net/)	7.4.30 (apache2handler)
    [MySQL](https://www.mysql.com/)	5.7.38-0ubuntu0.18.04.1-log
    Semantic MediaWiki | 3.2.0

`composer install` completly breaks it. 

blank page

apache error log:
`PHP Fatal error:  Uncaught Error: Class 'Wikimedia\\AtEase\\AtEase' not found in /var//public_html/includes/registration/ExtensionRegistry.php:171\nStack trace:\n#0 /var/public_html/includes/GlobalFunctions.php(88): ExtensionRegistry->queue()\n#1 /var/public_html/LocalSettings.php(174): wfLoadSkin()\n#2 /var/public_html/includes/Setup.php(143): require_once('/var/www/wiki/p...')\n#3 /var/public_html/includes/WebStart.php(89): require_once('/var/p...')\n#4 /var/public_html/index.php(44): require('/var/www/wiki/p...')\n#5 {main}\n  thrown in /var/public_html/includes/registration/ExtensionRegistry.php on line 171
[Sun Jun 19 11:30:54.866526 2022] [php7:error] [pid 22988] [client 154.54.249.198:16080] PHP Fatal error:  Uncaught Error: Class 'WebRequest' not found in /var/public_html/includes/HeaderCallback.php:63\nStack trace:\n#0 [internal function]: MediaWiki\\HeaderCallback::callback()\n#1 {main}\n  thrown in /var/public_html/includes/HeaderCallback.php on line 63
`

Thanks for having a look.

**Comment by YOUR1** [comment]
Something is wrong with your setup; WebRequest should always be loaded.

**Comment by JeroenDeDauw** [comment]
Tracked by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5300
