### ISSUE TITLE
Undefined variable: last_letter in CategoryResultPrinter

### ISSUE THREAD

**Issue by rcdeboer** [SemanticMediaWiki/SemanticMediaWiki#5270]
### Setup

- SMW version: 3.2.3
- MW version: 1.35

### Issue

I see a lot of log entries where line 232 in CategoryResultPrinter.php throws a PHP Notice 'Undefined variable: last_letter'.  It seems that $last_letter is only set when $first_letter is not set (line 199). 

I'm not entirely sure about the intended use of 'last letter' on line 232, but shouldn't it be something like this 
```
// Make label for finding further results
if ( $this->linkFurtherResults( $res ) ) {
	$index = isset( $last_letter ) ? $last_letter : $first_letter; 
	$contents[$index][] = $this->getFurtherResultsLink( $res, $outputMode )->getText( SMW_OUTPUT_WIKI, $this->mLinker );
}
```

instead of the current code:
```
// Make label for finding further results
if ( $this->linkFurtherResults( $res ) ) {
	$contents[$last_letter][] = $this->getFurtherResultsLink( $res, $outputMode )->getText( SMW_OUTPUT_WIKI, $this->mLinker );
}
```

**Comment by kghbln** [comment]
Thanks for reporting. I guess the easiest will be to provide a pull and go via the review process.
