### ISSUE TITLE
SemanticMediaWiki 

### ISSUE THREAD

**Issue by Dein-Anwalt** [SemanticMediaWiki/SemanticMediaWiki#5272]
### Setup

- SMW version: 4.0.1
- MW version: 1.38.2
- PHP version: 8.1.6
- i am using the actual version of Xampp 

### Issue
Hello all, 
I followed the following installation instructions: https://www.semantic-mediawiki.org/wiki/Help:Installation/Quick_guide 

and got the following error after entering 
 $ php maintenance/update.php

PHP Fatal error:  Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in C:\xam
pp\htdocs\extensions\SemanticMediaWiki\includes\SemanticMediaWiki.php:46
Stack trace:
#0 C:\xampp\htdocs\includes\registration\ExtensionRegistry.php(574): SemanticMediaWiki::initExtension(Array)
#1 C:\xampp\htdocs\includes\registration\ExtensionRegistry.php(258): ExtensionRegistry->exportExtractedData(Array)
#2 C:\xampp\htdocs\includes\Setup.php(252): ExtensionRegistry->loadFromQueue()
#3 C:\xampp\htdocs\maintenance\doMaintenance.php(96): require_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\maintenance\update.php(264): require_once('C:\\xampp\\htdocs...')
#5 {main}
  thrown in C:\xampp\htdocs\extensions\SemanticMediaWiki\includes\SemanticMediaWiki.php on line 46
Fatal error: Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in C:\xampp\ht
docs\extensions\SemanticMediaWiki\includes\SemanticMediaWiki.php:46
Stack trace:
#0 C:\xampp\htdocs\includes\registration\ExtensionRegistry.php(574): SemanticMediaWiki::initExtension(Array)
#1 C:\xampp\htdocs\includes\registration\ExtensionRegistry.php(258): ExtensionRegistry->exportExtractedData(Array)
#2 C:\xampp\htdocs\includes\Setup.php(252): ExtensionRegistry->loadFromQueue()
#3 C:\xampp\htdocs\maintenance\doMaintenance.php(96): require_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\maintenance\update.php(264): require_once('C:\\xampp\\htdocs...')
#5 {main}
  thrown in C:\xampp\htdocs\extensions\SemanticMediaWiki\includes\SemanticMediaWiki.php on line 46

iam using git on a windows PC.

**Comment by JeroenDeDauw** [comment]
PHP 8.1 is not supported, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by formwandler** [comment]
Is there a good chance, that this problem is fixed with SMW 4.1, even though compatibility matrix for 4.1 says "PHP 8.0.x"?

**Comment by JeroenDeDauw** [comment]
Yeah. You ran into a known issue and fixing it is high up the prio list

**Comment by JeroenDeDauw** [comment]
Tracked by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5300
