### ISSUE TITLE
Semantic Mediawiki and wikibase

### ISSUE THREAD

**Issue by zampaleu** [SemanticMediaWiki/SemanticMediaWiki#5283]
I installed both SMW and Wikibase 
But WikibaseProperty and SMWProperty  not work at the same time.

Error in creating  WikibaseProperty if SMW is enabled.
[83c16611e727778c934f8129] /mediawiki/index.php/Special:NewProperty MediaWiki\Page\PageAssertionException: The given PageIdentity Special:Badtitle/NS122:NewProperty does not represent a proper page

Backtrace:

from /var/www/mediawiki/includes/page/WikiPageFactory.php(59)

any idea where it comes from?

Regards  s

**Comment by krabina** [comment]
You might want to look into https://github.com/ProfessionalWiki/SemanticWikibase#semantic-wikibase for this.

**Comment by kghbln** [comment]
And this is the direct spot describing how to rename the namespaces so they do not clash: https://github.com/ProfessionalWiki/SemanticWikibase#property-namespaces

**Comment by kghbln** [comment]
[Additionally documented here](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ANamespaces&type=revision&diff=82886&oldid=76854)

**Comment by zampaleu** [comment]
OK Thanks
FYI:
I renamed the  SemanticProperty namespaces  but the problem remains.
Added in LocalSettings.php
$wgExtensionFunctions[] = function() {
    $GLOBALS['wgExtraNamespaces'][SMW_NS_PROPERTY] = 'SemanticProperty';
    $GLOBALS['wgExtraNamespaces'][SMW_NS_PROPERTY_TALK] = 'SemanticProperty_talk';
};
Is the third extension  SemanticWikibase necessary/mandatory?
I will try

**Comment by kghbln** [comment]
>  I renamed the SemanticProperty namespaces but the problem remains.

In this case I have no idea what is going on at your end.

>  Is the third extension SemanticWikibase necessary/mandatory?

No and it is only compatible with MW 1.35

Did you check if you are using a setup with is [compatible?](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md)

**Comment by zampaleu** [comment]
Q: Did you check if you are using a setup with is [compatible?]
R. It could be that this is the reason. I am using [MediaWiki]: 1.38.2 and SMW 4.1.x
I have to downgrade and check.

**Comment by zampaleu** [comment]
FYI: There is no way to make it work properly on my maschine.
MW 1.37.4 + SMW 4.0.2 + wikibase 1.37 does not work on my maschine. 
update.php failure wikibase problem Error: Class 'Diff\Differ\MapDiffer' not found

MV 1.38.2 + SMW 4.0.1 + wikibase 1.38 works except for creating wikbase-property Special:NewProperty.
Tried renaming all namespaces. different combinations 
I will try again in the future
