### ISSUE TITLE
4.0 PHP Compatibility

### ISSUE THREAD

**Issue by aeon-rain** [SemanticMediaWiki/SemanticMediaWiki#5284]
Hi!

For SMW 4.x [COMPATIBILITY.md](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md) says PHP 7.3.0 - 7.4.x but [SMW 4.x release notes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-4.0.0.md) say "Dropped support for PHP older than 7.4". So the question is does it support PHP 7.3 or doesn't it? :)

Thanks!

**Comment by JeroenDeDauw** [comment]
The release notes were incorrect. SMW 4.0.x supports PHP 7.3
