### ISSUE TITLE
Fix PHP 8.1 compatibility

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#5300]
Issue: SMW passes $GLOBALS by reference in its setup code. https://php.watch/versions/8.1/GLOBALS-restrictions

Also reported in
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5272
*  https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5265
*  https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5302

**Comment by osnard** [comment]
I have browsed the code and it looks like most places where this issue occurs are related to things that are usually done by `extension.json` (like hook wiring).

I can think of three ways do fix this:
1. Quickfix by directly accessing `$GLOBALS` where it is actually used
2. Quickfix by making the methods return an array and then merging it into `$GLOBALS`
3. Refactor to use `extension.json` mechanisms

There are also some usages that require a different approach (e.g. unsetting a hook handler).

Do you have any preference or do you have a different way in mind?

**Comment by JeroenDeDauw** [comment]
Approach 2 is likely best for testing

**Comment by osnard** [comment]
I have tried approach 1 to identify the places: https://github.com/hallowelt/mediawiki-extensions-SemanticMediaWiki/commit/c90f870d2c93b8f455820c557474eb0511689061

With this change it doesn't break at regular runtime. I have not touched the tests.
With approach 2 I could adapt unit tests better. Approach 3 is probably too heavy.

**Comment by saerdnaer** [comment]
@osnard @JeroenDeDauw Any plans to bring this to master via an PR?

**Comment by osnard** [comment]
Unfortunately I had to stop work on this due to my personal work load. But I think I could move on and provide a PR.

@JeroenDeDauw You said option 2 was preferred. Before I continue with the work, may I ask for your opinion on this again?

As an example, let's use a current implementation like
```php
Setup::initExtension( $GLOBALS ); // $GLOBALS passed by reference
```

Given the information on https://php.watch/versions/8.1/GLOBALS-restrictions, I can probably neither do something like
```php
$GLOBALS = array_merge_recursive( $GLOBALS, Setup::initExtension() ); // `Setup::initExtension` just returning an array
```
nor
```php
$GLOBALS = Setup::initExtension( $GLOBALS ); // $GLOBALS as reference passed by value
```

So I will need to add some "helper logic", that does the "per-key-merging". E.g.
```php
SMW\Utils\SetupHelper::mergeIntoGlobals( Setup::initExtension() ); // `Setup::initExtension` just returning an array, `mergeToGlobals` iterating the input and merging it key-by-key into `$GLOBALS`
```

What do you think about this? Do you have any suggestions/preferences?

**Comment by malberts** [comment]
> So I will need to add some "helper logic", that does the "per-key-merging". E.g.

We recently did something similar to get around the $GLOBALS issue. Where we previously passed in $GLOBALS by reference, we now have to return the modified keys instead.

The other two approaches won't work, because both involve modifying the entire array which is not allowed.

**Comment by osnard** [comment]
Looking at https://github.com/hallowelt/mediawiki-extensions-SemanticMediaWiki/commit/c90f870d2c93b8f455820c557474eb0511689061 again, I fear that just "merging" stuff will not be sufficient at all, as there are other operations too, like `isset`, `unset`, `array_replace` and `===` checks.

**Comment by malberts** [comment]
You're right about the difficulties involved in "merging". In our case we ended up replacing keys in GLOBALS. The "merging" happens in the function generating the variables. The rough idea is you pass a readonly $GLOBALS to the function, the function copies the entire variable (e.g. 'wgGroupPermissions'), makes changes and returns the full value. The helper logic then simply replaces it in GLOBALS.

My specific exampe is in a private repo, but here's the gist of it:

Helper class:
```php
class Globals {

	public static function replace( array $variables ): void {
		foreach ( $variables as $key => $value ) {
			$GLOBALS[$key] = $value;
		}
	}

}
```

Then if we had something like this where $GLOBALS was passed by reference:
```php
FooBar::changeGlobals( $GLOBALS );
```

It now becomes this where $GLOBALS is passed by value:
```php
Globals::replace( FooBar::getGlobals( $GLOBALS ) );
```

Inside `FooBar` we previously had:
```php
public function changeGlobals( array &$mwGlobals ): void {
	...
	$mwGlobals['wgGroupPermissions']['*']['createaccount'] = false;
	...
}
```

Which now becomes:
```php
public function getGlobals( array $mwGlobals ): void {
	$newGlobals = [];
	...
	$newGlobals['wgGroupPermissions'] = $mwGlobals['wgGroupPermissions'] ?? [];
	$newGlobals['wgGroupPermissions']['*']['createaccount'] = false;
	...
	return $newGlobals;
}
```

Any time we need to change something inside an array in $GLOBALS we need to copy the whole array. This avoid the complications of guessing any merge logic.

**Comment by osnard** [comment]
Thanks for sharing. Looks like a good solution. @JeroenDeDauw Do you agree? Can I go for it?

**Comment by JeroenDeDauw** [comment]
@osnard :+1:

**Comment by osnard** [comment]
FYI: This is still in progress. I will prioritize it due to the recent release of MediaWiki 1.39 which is actually compatible to PHP 8.1.

**Comment by osnard** [comment]
Here are some more results from running `phpcs -p mediawiki-extensions-SemanticMediaWiki --standard=PHPCompatibility --runtime-set testVersion 8.1`

```
FILE: /src/Query/Processor/ParamListProcessor.php
---------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------
 123 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x003D'
 193 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x003D'
 264 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x003D'
---------------------------------------------------------------------------------------------------------------------------------------------------


FILE: /src/MediaWiki/Specials/Ask/ParametersProcessor.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------
 228 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x7C'
 236 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x7C'
 237 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x7C'
-------------------------------------------------------------------------------------------------------------------------------------------------


FILE: /src/ParserFunctionFactory.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 6 WARNINGS AFFECTING 6 LINES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 402 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$parser" was used, and possibly changed (by reference), on line 395.
 428 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$parser" was used, and possibly changed (by reference), on line 421.
 448 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$parser" was used, and possibly changed (by reference), on line 444.
 469 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$parser" was used, and possibly changed (by reference), on line 465.
 490 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$parser" was used, and possibly changed (by reference), on line 486.
 510 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$parser" was used, and possibly changed (by reference), on line 507.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by justinclloyd** [comment]
Just found this issue, adding my +1. It prevents upgrading to web servers from Ubuntu 20.04 to 22.04.

**Comment by lucamauri** [comment]
Question: [Semantic MediaWiki 4.1.1 announcement](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_4.1.1) states 

> This release improves compatibility with MediaWiki 1.39 and PHP 8.1.

meaning this issue is solved?
It is unclear to me the extent of the term "_improves_".

**Comment by JeroenDeDauw** [comment]
Most features should work at the moment, though you might experience some logspam.

**Comment by lucamauri** [comment]
> Most features should work at the moment, though you might experience some logspam.

Thanks, I performed a few tests and everything looks fine, but I have a question. Do you think this release is ready for production already in a MW 1.39 and PHP 8.1 environment?
Or shall we wait for some future `.2` ?

**Comment by JeroenDeDauw** [comment]
The latest release should be good

**Comment by rkevk** [comment]
I gather from this issue being closed that the hint in the [table on the doc page](https://www.semantic-mediawiki.org/wiki/Help:Compatibility) is outdated?

**Comment by JeroenDeDauw** [comment]
Yes. Docs fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5487
