### ISSUE TITLE
Issues with installation, against latest MediaWiki stable, and PHP 8.1.2

### ISSUE THREAD

**Issue by vmlemon** [SemanticMediaWiki/SemanticMediaWiki#5302]
### Setup

- SMW version: 4.0.2
- MW version: 1.37.4
- PHP version: PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)
- DB system (MySQL, Blazegraph, etc.) and version: mysql  Ver 8.0.30-0ubuntu0.22.04.1 for Linux on aarch64 ((Ubuntu))

### Issue

After several hours of metaphorical head-bashing (mostly fighting with seemingly-missing dependencies (e.g. "at-ease"), thanks to "Composer"), I seem to have arrived at the conclusion where I can "install" Semantic MediaWiki, with the aforementioned configuration, but if I attempt to use it, with just the ```enableSemantics( 'localhost' );``` stanza, in my LocalSettings.php file (as recommended, although it doesn't seem to be obvious, if it's the only thing necessary, given how much the documentation seems to be in flux), it doesn't appear in Special:Versions, and trying to tag elements of wiki entries doesn't seem to result in the expected behaviour (I see ```Something::Attribute```, in the _Network_ graph, instead of just "Attribute"). 

If I add the ```wfLoadExtension( 'SemanticMediaWiki' );``` stanza (I don't know if it's actually required, or not, with the latest versions of MediaWiki), I receive the following:

```
ubuntu@wiki:/var/www/html/mediawiki-1.37.4$ php maintenance/update.php 
PHP Fatal error:  Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in /var/www/html/mediawiki-1.37.4/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php:46
Stack trace:
#0 /var/www/html/mediawiki-1.37.4/includes/registration/ExtensionRegistry.php(574): SemanticMediaWiki::initExtension()
#1 /var/www/html/mediawiki-1.37.4/includes/registration/ExtensionRegistry.php(258): ExtensionRegistry->exportExtractedData()
#2 /var/www/html/mediawiki-1.37.4/includes/Setup.php(168): ExtensionRegistry->loadFromQueue()
#3 /var/www/html/mediawiki-1.37.4/maintenance/doMaintenance.php(90): require_once('...')
#4 /var/www/html/mediawiki-1.37.4/maintenance/update.php(264): require_once('...')
#5 {main}
  thrown in /var/www/html/mediawiki-1.37.4/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php on line 46

```

I assume there's some incompatibility, between my version of PHP, or MediaWiki, and this version of Semantic MediaWiki? (I also tried MediaWiki 1.38.2, initially, and decided to downgrade, in the end, with much the same result). 

Thanks in advance, and apologies for a bug report, that's probably as vague as the errors I've been seeing, for the past few hours. :(

**Comment by JeroenDeDauw** [comment]
The issue is PHP 8.1. Tracked by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5300

You can fix it by downgrading to PHP 8.0.x
