### ISSUE TITLE
Add formatter that allows partial ISO dates

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5309]
This issue is a follow-up on #4373 to allow an ISO formatted date for both, complete and partial dates.

Rationale:

- Sometimes, only a year or a year and month are specified for a date, e.g. during planning of events
- At a later point in time, the date is completed with a month and day

Currently, a date with only a year specified will be rendered completed with January first which is wrong for the reader.

2022 should become 2022 instead of 2022-01-01.

A new formatter `ISO-P` (P for "partial") should render partial dates in ISO formatting:

- 2022 → 2022
- April 2022 → 2022-04
- 1 April 2022 → 2022-04-01

**Comment by JeroenDeDauw** [comment]
Updated milestone as per https://semver.org/
