### ISSUE TITLE
Replace deprecated WikiPage::factory with WikiPageFactory::newFromTitle

### ISSUE THREAD

**Issue by umherirrender** [SemanticMediaWiki/SemanticMediaWiki#5324]
### Setup

- SMW version: master
- MW version: master

### Issue

According to codesearch SMW is using the deprecated `WikiPage::factory`, please replace with the service `WikiPageFactory::newFromTitle`. The class exists since 1.36 and needs compat code to work with 1.35, see the search result for examples.

https://codesearch.wmcloud.org/search/?q=%5CbWiki(Category%7CFile)%3FPage%5Cs*%3A%3A%5Cs*(factory%7CnewFromID%7CnewFromRow)%5Cb&i=nope&files=&excludeFiles=&repos=

The function is going to be hard deprecated and would emit deprecation warning, which can result in massive log spam.

https://phabricator.wikimedia.org/T297688

**Comment by JeroenDeDauw** [comment]
Deprecated in what version? 1.40?

**Comment by kghbln** [comment]
I suspect either 1.38 since the Phabricator issue was created in December 2021.

**Comment by umherirrender** [comment]
The deprecation was done in 1.36 with commit wikimedia/mediawiki@f871f7b

**Comment by Seb35** [comment]
This is now solved, only one occurence remains in `src/MediaWiki/PageCreator.php` for compatibility reasons (see below). It was fixed (perhaps amongst others) by @Abijeet in d4d5137ee8c3b816c9cf6c446a34163137569906.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/e1e0d3e4c2bc0f06f5db2fb88c75c2acd0aa6de0/src/MediaWiki/PageCreator.php#L27-L32
