### ISSUE TITLE
Error : Semantic MediaWiki:4.0.2 and MediaWiki: 1.38.4 on POSTGRES

### ISSUE THREAD

**Issue by zampaleu** [SemanticMediaWiki/SemanticMediaWiki#5326]
Trying to install BACKEND is Postrges
Semantic MediaWiki:                                                   4.0.2
MediaWiki:                                                           1.38.4

Checking `smw_id` sequence consistency ...
[00ecb5e305854f7eab6fb865] [no req]   Error: Call to undefined method Wikimedia\Rdbms\DatabasePostgres::onTransactionIdle()
Backtrace:
from /var/www/solab/includes/libs/rdbms/database/DBConnRef.php(69)
#0 /var/www/solab/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Sequence.php(86): Wikimedia\Rdbms\DBConnRef->__call()
#1 /var/www/solab/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(488): SMW\MediaWiki\Connection\Sequence->restart()
#2 /var/www/solab/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(474): SMW\SQLStore\TableBuilder\PostgresTableBuilder->doCheckOnPostCreation()
#3 /var/www/solab/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuildExaminer.php(171): SMW\SQLStore\TableBuilder\PostgresTableBuilder->checkOn()
#4 /var/www/solab/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(239): SMW\SQLStore\TableBuilder\TableBuildExaminer->checkOnPostCreation()
#5 /var/www/solab/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(451): SMW\SQLStore\Installer->install()
#6 /var/www/solab/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(419): SMW\SQLStore\SQLStore->setup()
#7 /var/www/solab/extensions/SemanticMediaWiki/maintenance/setupStore.php(166): SMW\SPARQLStore\SPARQLStore->setup()
#8 /var/www/solab/maintenance/doMaintenance.php(114): SMW\Maintenance\setupStore->execute()
#9 /var/www/solab/extensions/SemanticMediaWiki/maintenance/setupStore.php(277): require_once(string)
#10 {main}

**Comment by someone-somenet-org** [comment]
Seems to be the same issue as #5287 :(
