### ISSUE TITLE
Use of PersonalUrls hook was deprecated in MediaWiki 1.39

### ISSUE THREAD

**Issue by MPThLee** [SemanticMediaWiki/SemanticMediaWiki#5329]
### Setup

- SMW version: 4.0.2
- MW version: 1.39.0-rc.1
- PHP version: 8.0.25
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.8

### Issue
Just in case, for new update.

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
PHP Deprecated:  Use of PersonalUrls hook was deprecated in MediaWiki 1.39. [Called from SMW\MediaWiki\Hooks::register in /srv/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /srv/wiki/w/includes/debug/MWDebug.php on line 381
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
run update.php with semantic on 1.39.

**Comment by MPThLee** [comment]
Just found that #5310 fixed this issue. So should we wait 4.0.3 and close this issue?

**Comment by kghbln** [comment]
Thanks for your comment. Added it to the 4.0.3 milestone for memory lane.
