### ISSUE TITLE
Class "SMW\DataValues\PropertyValue" not found

### ISSUE THREAD

**Issue by Justman10000** [SemanticMediaWiki/SemanticMediaWiki#5330]
### Setup

- SMW version: master (cloned from GitHub)
- MW version: 1.38.4
- PHP version: 8.2.0RC3
- DB system (MySQL, Blazegraph, etc.) and version:  Ver 15.1 Distrib 10.11.0-preview-MariaDB

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
PHP Warning:  Class "SMW\DataValues\PropertyValue" not found in /home/web/mediawiki/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php on line 205
PHP Fatal error:  Uncaught Error: Class "SMWDataValue" not found in /home/web/mediawiki/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php:45
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Install and run:

```
php <media_wiki_dir>/maintenance/update.php --quick
```

**Comment by JeroenDeDauw** [comment]
SMW is not compatible with PHP 8.1 and later. The error you are running into makes me think you did not install SMW properly, which needs to be done with Composer.

**Comment by Justman10000** [comment]
> SMW is not compatible with PHP 8.1 and later. The error you are running into makes me think you did not install SMW properly, which needs to be done with Composer.

After `composer install` and with PHP 8.1.12:

> PHP Fatal error:  Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in /home/web/mediawiki/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php:46

**Comment by Justman10000** [comment]
@JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
Yeah I told you that it won't work with PHP 8.1

**Comment by z0rgster** [comment]
I use the official MW 1.39 docker image which happens to run on php 8.1. I built a custom image based on the official one in order to integrate composer and install SMW. Is there a possibility to downgrade php in my "personal" Dockerfile after 8.1 was installed?

```Dockerfile
FROM mediawiki:1.39

# install missung stuff and php extensions
RUN apt-get update && apt-get install -y \
    #   vim \
      unzip \
      libzip-dev \
    && docker-php-ext-install zip

# install composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer
    
# update mediawiki extensions via composer
COPY composer.local.json .
RUN composer update --no-dev
```

**Comment by JeroenDeDauw** [comment]
Easiest is to copy the official Dockerfile and modify the version in there. I've never seen someone do such a downgrade. 

Btw, we are working on getting SMW to work with PHP 8.1. Master will work a lot better with 8.1 than it did in November already.

**Comment by gesinn-it-gea** [comment]
see this: https://github.com/gesinn-it/docker-mediawiki-base/ as an example

**Comment by JeroenDeDauw** [comment]
@Justman10000 Go ahead and upgrade it. It's an open-source project. And apparently, it is not that much effort.

:roll_eyes:

**Comment by Justman10000** [comment]
> @Justman10000 Go ahead and upgrade it. It's an open-source project. And apparently, it is not that much effort.
> 
> 🙄

Well, I don't know PHP... So... Not really... So...
