### ISSUE TITLE
Replace use of core global function wfShowingResults

### ISSUE THREAD

**Issue by umherirrender** [SemanticMediaWiki/SemanticMediaWiki#5335]
The global function `wfShowingResults` is going to be removed.

Please inline the usage in `includes/querypages/QueryPage.php` or use your `HtmlFormRenderer::addPaging`, which seems to also provide the html string.

Upstream:
https://phabricator.wikimedia.org/T264980

**Comment by Krinkle** [comment]
@octfx I'd recommend avoiding the re-use of the core localisation message and instead copy that as well, as per https://phabricator.wikimedia.org/T264980#8482286 and <https://www.mediawiki.org/wiki/Help:System_message#Avoid_message_re-use>.

With core no longer using this message, it is likely to be removed as messsages themselves do not constitute a Stable interface (stable interfaces can sometimes include messages via a function or class, as this function was doing previously).

**Comment by octfx** [comment]
Thanks for pointing this out! I’ll update my PR accordingly 👍
