### ISSUE TITLE
Property links don't work in de-formal language

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5342]
### Setup

Software | Version
-- | --
MediaWiki | 1.35.8
PHP | 7.4.3 (fpm-fcgi)
MariaDB | 10.3.37-MariaDB-0ubuntu0.20.04.1
ICU | 66.1
Elasticsearch | 6.8.23
Semantic MediaWiki | 4.0.2

### Issue

The [@@@-Syntax to create property links](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1855) does work when the property _Has property description_ is set so some description:
` [[Has property description::Testdescription@de]]` 

It is working if the user has "de" as their language set. However, If a user sets "de-formal" the mouse-over-effect is not working. 

Trying to set ` [[Has property description::Testdescription@de-formal]]` fails with the massage that is not a valid language code.

So I guess this must be some kind of bug. If I cannot set de-formal as language value in monolinual text properties than somehow _de-formal_ (and _de-AT_, _de-CH_) should fallback to _de_.

See also https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1865 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3562

**Comment by krabina** [comment]
Thank you, it is working for me!

**Comment by krabina** [comment]
Unfortunately, this does not solve the issue for me. You can see it here:
https://test.knowledge.wiki/Adolf_Loos
the "Objektbezug" property should be called "Siehe auch": https://test.knowledge.wiki/Attribut:Objektbezug
![grafik](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/4318745/ff34166a-9c85-4c8b-be08-736b1319effa)
When I switch from de-forma. to de (as user), the correct name is shown:
![grafik](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/4318745/63f90b9a-ae32-43f2-9c97-ea39df3e96d4)
This happens only for non-logged-in users, btw.

**Comment by thomas-topway-it** [comment]
@JeroenDeDauw I'm waiting for some feedback, here https://test.knowledge.wiki/index.php?title=Attribut:Objektbezug&action=edit  I don't see de-format specified

**Comment by krabina** [comment]
That is right. I was not expecting having to set a property description to de-formal, I was expecting it to fall back to de if the wiki is set to de-formal.
So the PR is working, and this is an improvement. However, I don't think it is very likely that a property name or description will have language where formal or informal tone is required. You would usually never address the user in a property description.

**Comment by krabina** [comment]
@thomas-topway-it would it be easy to implement a fallback to "de" if the wiki is set to a subset of de (like de-formal) and there are no annotations with de-formal, but only with de?

**Comment by thomas-topway-it** [comment]
@krabina I've checked. In the MW files there isn't a fallback from de-formal to de, so they are considered two different languages. However there is a fallback in the file `jquery.i18n.fallbacks.js` , so we can translate it to PHP

```
	$.extend( $.i18n.fallbacks, {
		ab: [ 'ru' ],
		ace: [ 'id' ],
		aln: [ 'sq' ],
		// Not so standard - als is supposed to be Tosk Albanian,
		// but in Wikipedia it's used for a Germanic language.
		als: [ 'gsw', 'de' ],
		an: [ 'es' ],
		anp: [ 'hi' ],
		arn: [ 'es' ],
		arz: [ 'ar' ],
		av: [ 'ru' ],
		ay: [ 'es' ],
		ba: [ 'ru' ],
		bar: [ 'de' ],
		'bat-smg': [ 'sgs', 'lt' ],
		bcc: [ 'fa' ],
		'be-x-old': [ 'be-tarask' ],
		bh: [ 'bho' ],
		bjn: [ 'id' ],
		bm: [ 'fr' ],
		bpy: [ 'bn' ],
		bqi: [ 'fa' ],
		bug: [ 'id' ],
		'cbk-zam': [ 'es' ],
		ce: [ 'ru' ],
		crh: [ 'crh-latn' ],
		'crh-cyrl': [ 'ru' ],
		csb: [ 'pl' ],
		cv: [ 'ru' ],
		'de-at': [ 'de' ],
		'de-ch': [ 'de' ],
		'de-formal': [ 'de' ],
		dsb: [ 'de' ],
		dtp: [ 'ms' ],
		egl: [ 'it' ],
		eml: [ 'it' ],
		ff: [ 'fr' ],
		fit: [ 'fi' ],
		'fiu-vro': [ 'vro', 'et' ],
		frc: [ 'fr' ],
		frp: [ 'fr' ],
		frr: [ 'de' ],
		fur: [ 'it' ],
		gag: [ 'tr' ],
		gan: [ 'gan-hant', 'zh-hant', 'zh-hans' ],
		'gan-hans': [ 'zh-hans' ],
		'gan-hant': [ 'zh-hant', 'zh-hans' ],
		gl: [ 'pt' ],
		glk: [ 'fa' ],
		gn: [ 'es' ],
		gsw: [ 'de' ],
		hif: [ 'hif-latn' ],
		hsb: [ 'de' ],
		ht: [ 'fr' ],
		ii: [ 'zh-cn', 'zh-hans' ],
		inh: [ 'ru' ],
		iu: [ 'ike-cans' ],
		jut: [ 'da' ],
		jv: [ 'id' ],
		kaa: [ 'kk-latn', 'kk-cyrl' ],
		kbd: [ 'kbd-cyrl' ],
		khw: [ 'ur' ],
		kiu: [ 'tr' ],
		kk: [ 'kk-cyrl' ],
		'kk-arab': [ 'kk-cyrl' ],
		'kk-latn': [ 'kk-cyrl' ],
		'kk-cn': [ 'kk-arab', 'kk-cyrl' ],
		'kk-kz': [ 'kk-cyrl' ],
		'kk-tr': [ 'kk-latn', 'kk-cyrl' ],
		kl: [ 'da' ],
		'ko-kp': [ 'ko' ],
		koi: [ 'ru' ],
		krc: [ 'ru' ],
		ks: [ 'ks-arab' ],
		ksh: [ 'de' ],
		ku: [ 'ku-latn' ],
		'ku-arab': [ 'ckb' ],
		kv: [ 'ru' ],
		lad: [ 'es' ],
		lb: [ 'de' ],
		lbe: [ 'ru' ],
		lez: [ 'ru' ],
		li: [ 'nl' ],
		lij: [ 'it' ],
		liv: [ 'et' ],
		lmo: [ 'it' ],
		ln: [ 'fr' ],
		ltg: [ 'lv' ],
		lzz: [ 'tr' ],
		mai: [ 'hi' ],
		'map-bms': [ 'jv', 'id' ],
		mg: [ 'fr' ],
		mhr: [ 'ru' ],
		min: [ 'id' ],
		mo: [ 'ro' ],
		mrj: [ 'ru' ],
		mwl: [ 'pt' ],
		myv: [ 'ru' ],
		mzn: [ 'fa' ],
		nah: [ 'es' ],
		nap: [ 'it' ],
		nds: [ 'de' ],
		'nds-nl': [ 'nl' ],
		'nl-informal': [ 'nl' ],
		no: [ 'nb' ],
		os: [ 'ru' ],
		pcd: [ 'fr' ],
		pdc: [ 'de' ],
		pdt: [ 'de' ],
		pfl: [ 'de' ],
		pms: [ 'it' ],
		pt: [ 'pt-br' ],
		'pt-br': [ 'pt' ],
		qu: [ 'es' ],
		qug: [ 'qu', 'es' ],
		rgn: [ 'it' ],
		rmy: [ 'ro' ],
		'roa-rup': [ 'rup' ],
		rue: [ 'uk', 'ru' ],
		ruq: [ 'ruq-latn', 'ro' ],
		'ruq-cyrl': [ 'mk' ],
		'ruq-latn': [ 'ro' ],
		sa: [ 'hi' ],
		sah: [ 'ru' ],
		scn: [ 'it' ],
		sg: [ 'fr' ],
		sgs: [ 'lt' ],
		sli: [ 'de' ],
		sr: [ 'sr-ec', 'sr-cyrl' ],
		srn: [ 'nl' ],
		stq: [ 'de' ],
		su: [ 'id' ],
		szl: [ 'pl' ],
		tcy: [ 'kn' ],
		tg: [ 'tg-cyrl' ],
		tt: [ 'tt-cyrl', 'ru' ],
		'tt-cyrl': [ 'ru' ],
		ty: [ 'fr' ],
		udm: [ 'ru' ],
		ug: [ 'ug-arab' ],
		uk: [ 'ru' ],
		vec: [ 'it' ],
		vep: [ 'et' ],
		vls: [ 'nl' ],
		vmf: [ 'de' ],
		vot: [ 'fi' ],
		vro: [ 'et' ],
		wa: [ 'fr' ],
		wo: [ 'fr' ],
		wuu: [ 'zh-hans' ],
		xal: [ 'ru' ],
		xmf: [ 'ka' ],
		yi: [ 'he' ],
		za: [ 'zh-hans' ],
		zea: [ 'nl' ],
		zh: [ 'zh-hans' ],
		'zh-classical': [ 'lzh' ],
		'zh-cn': [ 'zh-hans' ],
		'zh-hant': [ 'zh-hans' ],
		'zh-hk': [ 'zh-hant', 'zh-hans' ],
		'zh-min-nan': [ 'nan' ],
		'zh-mo': [ 'zh-hk', 'zh-hant', 'zh-hans' ],
		'zh-my': [ 'zh-sg', 'zh-hans' ],
		'zh-sg': [ 'zh-hans' ],
		'zh-tw': [ 'zh-hant', 'zh-hans' ],
		'zh-yue': [ 'yue' ]
	} );

```

**Comment by thomas-topway-it** [comment]
My comment wasn't correct. There is a fallback specified in the file `MessagesDe_formal.php`. 
However within the frame of the current issue, I'm not sure it is a problem of fallback but rather the inverse operation. (the language code is expressed as 'de' in the property page but the expected result should reflect the language of the wiki set as de-formal)
This seems legitimate considering that 

> I don't think it is very likely that a property name or description will have language where formal or informal tone is required. You would usually never address the user in a property description

however for this to work in our case we have to use an inverse map (not a fallback) from de to de-formal specifically for the `Has preferred property label` property, that takes into account the language of the wiki

**Comment by krabina** [comment]
I am not sure I completely understand this. But from a user perspective, I would see it this way.

* if there is a preferred property defined, display it for the language the user is currently using (independent of the wikis language). This is working
* if there is no preferred property defined in the user language, use the wikis language. This is working and is used for anonymous users.
* if there is a definition in de-xxx and one in de, use the one the user specified. For anonymous users use the one in the wiki setting. This is working since this PR

Edge-Cases (only if the definition does not match)
* If there is a definition in de-xxx and the wiki is in de, use the de-xxx
* if there is a definition in de and the wiki is in de-xxx, use de
