### ISSUE TITLE
Fix MW 35 test failure on GitHub Actions

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#5346]
This started happening a few days ago without the SMW code being changed

![image](https://user-images.githubusercontent.com/146040/206587488-cf2fdc48-cbc6-47ec-a0b9-f234623e35ac.png)

**Comment by malberts** [comment]
This started happening because the tests are now somehow running (and failing) on PHP 8 first.

The underlying issue is here: https://github.com/onoi/http-request/pull/13

**Comment by malberts** [comment]
It's using PHP 8 because the underlying Docker image was updated:
https://github.com/wikimedia/mediawiki-docker/pull/117
https://phabricator.wikimedia.org/T324427#8441788

**Comment by Seb35** [comment]
This issue should be closed as fixed by #5351 (at least I guess: the CI history is now lost but the PR provided PHP 8 support and it is said above that the PHP version on Docker images was 8) and anyway the last commit with 1.35 tests (3d362487719d0354855b05a7d63b4cce7a57da28) was successful.
