### ISSUE TITLE
Subobject property processing issue

### ISSUE THREAD

**Issue by darenwelsh** [SemanticMediaWiki/SemanticMediaWiki#535]
It seems that there is a bug in how SMW processes revisions to properties in subobjects. Specifically the issue is when subobjects are created using values outputted from the show parser function with data from the same page (e.g. {{#show: {{PAGENAME}} |? Some property }} ).

To test this issue, open the following two pages:
- http://semantic-mediawiki.org/wiki/User:Darenwelsh/Subobject_Test_Data
- http://semantic-mediawiki.org/wiki/User:Darenwelsh/Subobject_Test_Query

Then run the following process:
1. Edit the Data page
2. Modify one of the values for property "Is from" (has type Page)
3. Save the Data page
4. Refresh the Query page

Notice how the values for the data page "Is from" has been updated to reflect your modification, but the "Has attendee" value in each object has not been updated.

Repeat the modification process above. You'll notice that the previous modification now displays in the objects' properties. So it seems they are one step behind. My theory is that SMW is processing the definition of "Is from" on the data page upon page save, but the process of passing that value along to the subobject is not happening until the page is revised one more time. Does SMW process the subobject properties before the page properties?

We're pretty sure we have used this method before with no issues in SMW 1.8, but we have recently upgraded to 2.0. Though we can't say for certain if this behavior is linked to the SMW upgrade.

**Comment by mwjames** [comment]
> Not a bug, IMO.
> self-referencing you get what you ask for

As a self-reference issue the topic has been addressed and explained in #1696, #1478, and #2375.
