### ISSUE TITLE
Inconsistent behaviour when using #set_internal in a #loop

### ISSUE THREAD

**Issue by josch** [SemanticMediaWiki/SemanticMediaWiki#536]
Hi,

to reproduce my problem, try pasting the following into a new referata scratchpad wiki page and save the page:

```wiki
{{#set_internal:Part of model | Has qty=1 | Has id=3004 | Has color=red }}
{{#set_internal:Part of model | Has qty=2 | Has id=3004 | Has color=red }}
{{#set_internal:Part of model | Has qty=1 | Has id=3004 | Has color=black }}
{{#set_internal:Part of model | Has qty=2 | Has id=3006 | Has color=red }}

Unique color values in order:

{{#arraydefine: colors
 | {{#ask:[[Part of model::{{PAGENAME}}]]|mainlabel=-| headers = hide|?Has color}}
 | , | print=list, sort=asc, unique
}}

{{#loop: i
  | 0
  | {{#arraysize:colors}}
  | <nowiki/>
{{#set_internal:Color of model
  | Has Color Name={{#arrayindex:colors | {{#var:i}} }}
  | Has qty={{#ask:[[Part of model::{{PAGENAME}}]][[Has color::{{#arrayindex:colors | {{#var:i}} }}]] |? Has qty |format=sum }}
}}
}}

= Parts list =

{{#ask:[[Part of model::{{PAGENAME}}]]
|mainlabel=-
|? Has qty
|? Has id
|? Has color
}}

= Colors by quantity (irrespective of part) =

{{#ask:[[Color of model::{{PAGENAME}}]]
|mainlabel=-
|? Has qty
|? Has Color Name
}}
```

You will see that there is no table in the "Colors by quantity" section. Calling the pagename with `?action=purge` does not solve the issue. I thought this could be because I did something wrong above, but surprisingly after adding a single more entry like:

```
{{#set_internal:Part of model | Has qty=2 | Has id=3006 | Has color=green }}
```

and then saving the page, the table will show up (the "Has qty" column will be empty but only because we didnt create a page for the "Has qty" type to set it to "number" and this is not the problem of this bugreport). It will not include the new "Has color" value "green" but "red" and "black" will show up. Again, doing `?action=purge` does not change this. On the other hand, if I now delete the new entry I created above, the table will change again and now include the "Has color" "green" value.

**Comment by mwjames** [comment]
Since `#set_internal`  and `#loop` are not part of SMW core, I'm afraid that this question can not be answered in full.
