### ISSUE TITLE
Remote Requests do not work with PHP 8.0

### ISSUE THREAD

**Issue by EriqJB** [SemanticMediaWiki/SemanticMediaWiki#5394]
SMW version: 4.0.2
MW version: 1.35.9
PHP version: 8.0.27

After an update to PHP 8.0, my wikipages that contain queries with remote requests throw this fatal error:

> TypeError from line 32 of /var/www/html/vendor/onoi/http-request/src/CurlRequest.php: get_resource_type(): Argument #1 ($resource) must be of type resource, CurlHandle given
> 
> Backtrace:
> #0 /var/www/html/vendor/onoi/http-request/src/CurlRequest.php(32): get_resource_type(CurlHandle)
> #1 /var/www/html/vendor/onoi/http-request/src/CachedCurlRequest.php(40): Onoi\HttpRequest\CurlRequest->__construct(CurlHandle)
> #2 /var/www/html/extensions/SemanticMediaWiki/src/Query/RemoteRequest.php(255): Onoi\HttpRequest\CachedCurlRequest->__construct(CurlHandle, Onoi\Cache\CompositeCache)
> #3 /var/www/html/extensions/SemanticMediaWiki/src/Query/RemoteRequest.php(107): SMW\Query\RemoteRequest->init()
> #4 /var/www/html/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SMW\Query\RemoteRequest->getQueryResult(SMWQuery)
> #5 /var/www/html/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(361): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
> #6 /var/www/html/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(196): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
> #7 /var/www/html/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
> #8 /var/www/html/includes/parser/Parser.php(3341): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string, string)
> #9 /var/www/html/includes/parser/Parser.php(3048): Parser->callParserFunction(PPTemplateFrame_Hash, string, array)
> #10 /var/www/html/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPTemplateFrame_Hash)
> #11 /var/www/html/includes/parser/Parser.php(3226): PPFrame_Hash->expand(PPNode_Hash_Tree)
> #12 /var/www/html/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPTemplateFrame_Hash)
> #13 /var/www/html/includes/parser/Parser.php(3226): PPFrame_Hash->expand(PPNode_Hash_Tree)
> #14 /var/www/html/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPTemplateFrame_Hash)
> #15 /var/www/html/includes/parser/Parser.php(3226): PPFrame_Hash->expand(PPNode_Hash_Tree)
> #16 /var/www/html/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPFrame_Hash)
> #17 /var/www/html/includes/parser/Parser.php(2888): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
> #18 /var/www/html/includes/parser/Parser.php(1557): Parser->replaceVariables(string)
> #19 /var/www/html/includes/parser/Parser.php(652): Parser->internalParse(string)
> #20 /var/www/html/includes/content/WikitextContent.php(374): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
> #21 /var/www/html/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
> #22 /var/www/html/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
> #23 /var/www/html/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
> #24 /var/www/html/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
> #25 /var/www/html/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
> #26 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
> #27 /var/www/html/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
> #28 /var/www/html/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
> #29 /var/www/html/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
> #30 /var/www/html/includes/page/Article.php(810): PoolCounterWork->execute()
> #31 /var/www/html/includes/actions/ViewAction.php(80): Article->view()
> #32 /var/www/html/includes/MediaWiki.php(531): ViewAction->show()
> #33 /var/www/html/includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
> #34 /var/www/html/includes/MediaWiki.php(947): MediaWiki->performRequest()
> #35 /var/www/html/includes/MediaWiki.php(547): MediaWiki->main()
> #36 /var/www/html/index.php(53): MediaWiki->run()
> #37 /var/www/html/index.php(46): wfIndexMain()
> #38 {main}

This is probably related to the `curl_init` function of PHP, which [returns `CurlHandle` instead of `resource` since PHP 8.0](https://www.php.net/manual/en/function.curl-init.php), and which is called in [`RemoteRequest.php:270`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Query/RemoteRequest.php#L270).

**Comment by malberts** [comment]
Can you try using the latest master branch of SMW? We recently replaced the old http-requests library with an updated one that supports PHP 8 (#5351). That came up specifically because of test failures, but your error looks the same, so I believe it should be fixed by that change.

**Comment by EriqJB** [comment]
Thanks @malberts, this seems to work for now! Looking forward to release 4.0.3 🙂
