### ISSUE TITLE
CI against SQLite?

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5422]
Is there a reason, why CI is currently only running against MySQL?

**Comment by gesinn-it-gea** [comment]
see also #5384 with an issue that should imho be discovered by SMW CI itself

**Comment by JeroenDeDauw** [comment]
The old CI ran against multiple DB types. The current one does not even vary the PHP version beyond what comes shipped in the MW images.

**Comment by jaideraf** [comment]
The current CI is testing against MW 1.39, PHP 8.1, SQLite. So this can be closed, I think.
