### ISSUE TITLE
PersonalUrls hook depreciated

### ISSUE THREAD

**Issue by dafogary** [SemanticMediaWiki/SemanticMediaWiki#5429]
When running:

maintenance/populateContentTables.php 

It throws an error:

PHP Deprecated:  Use of PersonalUrls hook was deprecated in MediaWiki 1.39. [Called from SMW\MediaWiki\Hooks::register in /var/www/html/farm/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /var/www/html/farm/includes/debug/MWDebug.php on line 381

**Comment by dafogary** [comment]
Config

<html>
<body>
<h2 id="mw-version-software" style="box-sizing: border-box; color: rgb(0, 0, 0); margin: 1rem 0px 0.5rem; padding-top: 0.5em; padding-bottom: 0.17em; overflow: hidden; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.7rem; font-weight: 500; line-height: 1.2; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="mw-headline" id="Installed_software" style="box-sizing: border-box;">Installed software</span></h2>

Product | Version
-- | --
MediaWiki | 1.39.1
PHP | 7.4.3-4ubuntu2.17 (apache2handler)
MariaDB | 10.3.37-MariaDB-0ubuntu0.20.04.1
ICU | 66.1
Lua | 5.1.5
Pygments | 2.11.2

<br class="Apple-interchange-newline">
</body>
</html>Installed software
Product	Version
[MediaWiki](https://www.mediawiki.org/)	1.39.1
[PHP](https://php.net/)	7.4.3-4ubuntu2.17 (apache2handler)
[MariaDB](https://mariadb.org/)	10.3.37-MariaDB-0ubuntu0.20.04.1
[ICU](https://icu.unicode.org/)	66.1
[Lua](http://www.lua.org/)	5.1.5
[Pygments](https://pygments.org/)	2.11.2
Entry point URLs
Entry point	URL
[Article path](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:$wgArticlePath)	[/waas/index.php/$1](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/$1)
[Script path](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:$wgScriptPath)	[/waas](https://waas.dd.mcn.ice.mod.gov.uk/waas)
[index.php](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:index.php)	[/waas/index.php](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php)
[api.php](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:api.php)	[/waas/api.php](https://waas.dd.mcn.ice.mod.gov.uk/waas/api.php)
[rest.php](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:rest.php)	[/waas/rest.php](https://waas.dd.mcn.ice.mod.gov.uk/waas/rest.php)
Installed skins
Skin	Version	Licence	Description	Authors
[Chameleon](https://www.mediawiki.org/wiki/Skin:Chameleon)	4.1.0	[GPL-3.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/chameleon)	A highly flexible responsive skin using Bootstrap 4	[Stephan Gambke](https://www.mediawiki.org/wiki/User:F.trott), [Professional.Wiki](https://professional.wiki/), Morne Alberts and [Jeroen De Dauw](https://www.entropywins.wtf/mediawiki)
[SimpleFooterLink](https://www.mediawiki.org/wiki/Extension:SimpleFooterLink)	0.1.1	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SimpleFooterLink)	This extension provides a simple way to add any link that system administrators want to footer link area.	AnnAngela
[Vector](https://www.mediawiki.org/wiki/Skin:Vector)	1.0.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Vector)	
Provides 2 Vector skins:

2011 - The Modern version of MonoBook with fresh look and many usability improvements.
2022 - The Vector built as part of the WMF [mw:Desktop Improvements](https://www.mediawiki.org/wiki/Desktop_Improvements) project.
[Readers Web Team](https://www.mediawiki.org/wiki/Readers/Web/Team), Trevor Parscal, Roan Kattouw, Alex Hollender, Bernard Wang, Clare Ming, Jan Drewniak, Jon Robson, Nick Ray, Sam Smith, Stephen Niedzielski and Volker E.
Installed extensions
Semantic extensions
Extension	Version	Licence	Description	Authors
[Modern Timeline](https://github.com/ProfessionalWiki/ModernTimeline#modern-timeline)	1.2.1	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/ModernTimeline)	Provides a modern timeline visualization for Semantic MediaWiki	[Professional.Wiki](https://professional.wiki/) and [Jeroen De Dauw](https://www.entropywins.wtf/mediawiki)
[Semantic Compound Queries](https://www.semantic-mediawiki.org/wiki/Extension:Semantic_Compound_Queries)	2.2.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SemanticCompoundQueries)	A parser function that displays multiple semantic queries at the same time	James Hong Kong, Yaron Koren and others
[Semantic Extra Special Properties](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/)	3.0.1	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SemanticExtraSpecialProperties)	Adds some extra special properties to all pages	James Hong Kong, Leo Wallentin and others
[Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.0.2	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SemanticMediaWiki)	Making your wiki more accessible - for machines and humans ([online documentation](https://www.semantic-mediawiki.org/wiki/Help:User_manual))	[Markus Krötzsch](https://korrekt.org/), [Jeroen De Dauw](https://entropywins.wtf/mediawiki), James Hong Kong, [Professional.Wiki](https://professional.wiki/) and [others](https://www.semantic-mediawiki.org/wiki/Contributors)
Special pages
Extension	Version	Licence	Description	Authors
[Admin Links](https://www.mediawiki.org/wiki/Extension:Admin_Links)	0.5 (2f0c5c0) 07:50, 6 December 2022	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Admin_Links)	Adds a [special page](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:AdminLinks) that holds helpful links for administrators	Yaron Koren
[CiteThisPage](https://www.mediawiki.org/wiki/Extension:CiteThisPage)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/CiteThisPage)	Adds a [citation](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:CiteThisPage) special page and toolbox link	Ævar Arnfjörð Bjarmason and James D. Forrester
[Echo](https://www.mediawiki.org/wiki/Extension:Echo)	– (14f34aa) 06:43, 10 January 2023	[MIT](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Echo)	System for notifying users about events and messages	Andrew Garrett, Ryan Kaldari, Benny Situ, Luke Welling, Kunal Mehta, Moriel Schottlender, Jon Robson and Roan Kattouw
[EditAccount](https://www.mediawiki.org/wiki/Extension:EditAccount)	1.3.5	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/EditAccount)	Enables privileged users members to [manage user account information](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:EditAccount)	Łukasz Garczewski, Jack Phoenix and WikiTeq
[Flex Diagrams](https://www.mediawiki.org/wiki/Extension:Flex_Diagrams)	0.4	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Flex_Diagrams)	Editing and creation of diagrams	Yaron Koren and Sahaj Khandelwal
[Interwiki](https://www.mediawiki.org/wiki/Extension:Interwiki)	3.2	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Interwiki)	Adds a [special page](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Interwiki) to view and edit the interwiki table	Stephanie Amanda Stevens, Alexandre Emsenhuber, Robin Pepermans, Siebrand Mazeland, Platonides, Raimond Spekking, Sam Reed, Jack Phoenix, Calimonius the Estrange and others
[LastUserLogin](https://www.mediawiki.org/wiki/Extension:LastUserLogin)	1.6 (6729f3f) 09:37, 4 December 2022	[GPL-3.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/LastUserLogin)	Displays the last time a user logged in	Justin G. Cramer, Danila Ulyanov, Thomas Klein and [Sophivorus](https://www.mediawiki.org/wiki/User:Sophivorus)
[Nuke](https://www.mediawiki.org/wiki/Extension:Nuke)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Nuke)	Gives administrators the ability to [mass delete](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Nuke) pages	Brion Vibber and Jeroen De Dauw
[Page Forms](https://www.mediawiki.org/wiki/Extension:Page_Forms)	5.5.1	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/PageForms)	Forms for creating and editing wiki pages	Yaron Koren, Stephan Gambke and others
[Renameuser](https://www.mediawiki.org/wiki/Extension:Renameuser)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Renameuser)	Adds a [special page](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:RenameUser) to rename a user (need renameuser right)	Ævar Arnfjörð Bjarmason and Aaron Schulz
[Replace Text](https://www.mediawiki.org/wiki/Extension:Replace_Text)	1.7	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Replace_Text)	Provides a [special page](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:ReplaceText) to allow administrators to do a global string find-and-replace on all the content pages of a wiki	Yaron Koren, Niklas Laxström and others
[RottenLinks](https://github.com/miraheze/RottenLinks)	1.0.20	[GPL-3.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/RottenLinks)	Shows the [state of all external links](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:RottenLinks) on the wiki	John Lewis and Universal Omega
[UserMerge](https://www.mediawiki.org/wiki/Extension:UserMerge)	1.10.1 (a0508d6) 06:47, 3 January 2023	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/UserMerge)	[Merges references from one user to another user](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:UserMerge) in the wiki database - will also delete old users following merge. Requires usermerge privileges	Tim Laqua, Thomas Gries and Matthew April
[WhoIsWatching](https://www.mediawiki.org/wiki/Extension:WhoIsWatching)	0.13.0 (41406f1) 06:49, 10 January 2023	[GPL-2.0-only](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/WhoIsWatching)	Provides a listing of usernames watching a wiki page	Paul Grinberg, Siebrand Mazeland, Vitaliy Filippov and [Mark A. Hershberger](http://web.nichework.com/)
Editors
Extension	Version	Licence	Description	Authors
[VisualEditor](https://www.mediawiki.org/wiki/Extension:VisualEditor)	0.1.2	[MIT](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/VisualEditor)	Visual editor for MediaWiki	Alex Monk, Bartosz Dziewoński, C. Scott Ananian, Christian Williams, David Lynch, Ed Sanders, Inez Korczyński, James D. Forrester, Moriel Schottlender, Roan Kattouw, Rob Moen, Subramanya Sastry, Thalia Chan, Timo Tijhof, Trevor Parscal and [others](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/Credits/VisualEditor)
Parser hooks
Extension	Version	Licence	Description	Authors
[CategoryTree](https://www.mediawiki.org/wiki/Extension:CategoryTree)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/CategoryTree)	Dynamically navigate the [category structure](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:CategoryTree)	Daniel Kinzler
[Cite](https://www.mediawiki.org/wiki/Extension:Cite)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Cite)	Adds <ref> and <references> tags for citations	Ævar Arnfjörð Bjarmason, Andrew Garrett, Brion Vibber, Ed Sanders, Marius Hoch, Steve Sanbeg, Trevor Parscal and [others](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/Credits/Cite)
[CountDownClock](https://www.mediawiki.org/wiki/Extension:CountDownClock)	1.0.0 (d2e831b) 06:09, 27 December 2022	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/CountDownClock)	Adds a parser function to show a count down time	[Indic-TechCom](https://meta.wikimedia.org/wiki/Indic-TechCom)
[Graph](https://www.mediawiki.org/wiki/Extension:Graph)	– (018d658) 06:44, 10 January 2023	[MIT](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Graph)	Allows <graph> tags or entire pages to become [Vega](http://vega.github.io/)-based graphs	Dan Andreescu, Yuri Astrakhan and Frédéric Bolduc
[ImageMap](https://www.mediawiki.org/wiki/Extension:ImageMap)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/ImageMap)	Allows client-side clickable image maps using <imagemap> tag	Tim Starling
[InputBox](https://www.mediawiki.org/wiki/Extension:InputBox)	0.3.0	[MIT](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/InputBox)	Allow inclusion of predefined HTML forms	Erik Moeller, Leonardo Pimenta, Rob Church, Trevor Parscal and DaSch
[LabeledSectionTransclusion](https://www.mediawiki.org/wiki/Extension:Labeled_Section_Transclusion)	– (5181f57) 06:10, 27 December 2022	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/LabeledSectionTransclusion)	Adds #lst and #lstx functions and <section> tag, enables marked sections of text to be transcluded	Steve Sanbeg
[MagicNoCache](https://www.mediawiki.org/wiki/Extension:MagicNoCache)	1.6.0 (47c4f50) 06:45, 10 January 2023	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/MagicNoCache)	Adds the __NOCACHE__ magic word to disable caching on a page	[Kimon Andreou](https://www.mediawiki.org/wiki/User:Kimon), [Pavel Astakhov](https://www.mediawiki.org/wiki/User:Pastakhov) and others
[Maps](https://maps.extension.wiki/)	9.0.7	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Maps)	Allows embedding of dynamic maps into wiki pages using Google Maps or Leaflet. Has a visual editor, optionally integrates with Semantic MediaWiki, supports GeoJSON and adds geocoding capabilities.	[Jeroen De Dauw](https://entropywins.wtf/mediawiki) and [Professional.Wiki](https://professional.wiki/)
[Math](https://www.mediawiki.org/wiki/Extension:Math)	3.0.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Math)	Render mathematical formulas between <math> ... </math> tags	Tomasz Wegrzanowski, Brion Vibber, Moritz Schubotz, Derk-Jan Hartman and André Greiner-Petter
[Mermaid](https://github.com/SemanticMediaWiki/Mermaid/)	3.1.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Mermaid)	Provides a parser function to help generate diagrams and flowcharts using the [mermaid](https://mermaidjs.github.io/) script language	James Hong Kong and Tyler Gibson
[MWUserAgreement](https://github.com/dafogary/MWUserAgreement)	Beta - 0.1		Renders the user agreement after login. This expires after 12 months and the user is prompted again. Based on the [UserAgreement](https://www.mediawiki.org/wiki/Extension:UserAgreement) plugin. Based on work by [Kevin Ji](https://www.mediawiki.org/wiki/User:Kevin.ji) and [Cindy Cicalese](https://www.mediawiki.org/wiki/User:Cindy.cicalese).	[DAFO Creative LLC](https://dafocreative.com/) and [Harry Cadby](https://github.com/Goldshop)
[MyVariables](https://www.mediawiki.org/wiki/Extension:MyVariables)	4.4 (c370c98) 06:46, 10 January 2023	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/MyVariables)	Adds new built-in variables	[Aran Dunkley](https://www.mediawiki.org/wiki/User:Nad), [Pavel Astakhov](https://www.mediawiki.org/wiki/User:Pastakhov) and [[1]](https://www.mediawiki.org/wiki/User:Vedmaka)
[Network](https://github.com/ProfessionalWiki/Network#network-extension)	2.0.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Network)	Allows adding interactive network visualizations in your wiki pages	[Jeroen De Dauw](https://www.entropywins.wtf/mediawiki) and [Professional.Wiki](https://professional.wiki/)
[ParserFunctions](https://www.mediawiki.org/wiki/Extension:ParserFunctions)	1.6.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/ParserFunctions)	Enhance parser with logical functions	Tim Starling, Robert Rohde, Ross McClure and Juraj Simlovic
[Poem](https://www.mediawiki.org/wiki/Extension:Poem)	–	[CC0-1.0](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Poem)	Adds <poem> tag for poem formatting	Nikola Smolenski, Brion Vibber and Steve Sanbeg
[Scribunto](https://www.mediawiki.org/wiki/Extension:Scribunto)	–	[GPL-2.0-or-later AND MIT](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Scribunto)	Framework for embedding scripting languages into MediaWiki pages	Victor Vasiliev, Tim Starling and Brad Jorsch
[SimpleMathJax](https://www.mediawiki.org/wiki/Extension:SimpleMathJax)	0.8.3	[GPL-2.0+](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SimpleMathJax)	render TeX between <math> and </math>	jmnote
[SyntaxHighlight](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight)	2.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SyntaxHighlight)	Provides syntax highlighting <syntaxhighlight> using [Pygments - Python syntax highlighter](http://pygments.org/)	Brion Vibber, Tim Starling, Rob Church, Niklas Laxström, Ori Livneh and Ed Sanders
[TemplateData](https://www.mediawiki.org/wiki/Extension:TemplateData)	0.1.2	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/TemplateData)	Implement data storage for template parameters (using JSON)	Timo Tijhof, Moriel Schottlender, James D. Forrester, Trevor Parscal, Bartosz Dziewoński, Marielle Volz and others
[Widgets](https://www.mediawiki.org/wiki/Extension:Widgets)	1.4.1 (6155da4) 06:14, 27 December 2022	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Widgets)	Allows wiki administrators to add free-form widgets to the wiki by editing pages within the Widget namespace. Community-contributed widgets can be found on [MediaWikiWidgets.org](http://www.mediawikiwidgets.org/Main_Page)	[Sergey Chernyshev](https://www.sergeychernyshev.com/), Yaron Koren and others
Media handlers
Extension	Version	Licence	Description	Authors
[PDF Handler](https://www.mediawiki.org/wiki/Extension:PdfHandler)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/PDF_Handler)	Handler for viewing PDF files in image mode	Martin Seidel and Mike Połtyn
Spam prevention
Extension	Version	Licence	Description	Authors
[ConfirmEdit](https://www.mediawiki.org/wiki/Extension:ConfirmEdit)	1.6.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/ConfirmEdit)	Provides CAPTCHA techniques to protect against spam and password-guessing	Brion Vibber, Florian Schmidt, Sam Reed and [others](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/Credits/ConfirmEdit)
[SpamBlacklist](https://www.mediawiki.org/wiki/Extension:SpamBlacklist)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SpamBlacklist)	Regex-based anti-spam tool allowing to block list URLs in pages and email addresses for registered users	Tim Starling, John Du Hart and Daniel Kinzler
[TitleBlacklist](https://www.mediawiki.org/wiki/Extension:TitleBlacklist)	1.5.0	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/TitleBlacklist)	Allows administrators to forbid creation of pages and user accounts according to a [list of disallowed](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/MediaWiki:Titleblacklist) and [allowed](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/MediaWiki:Titlewhitelist) titles	Victor Vasiliev and Fran Rogers
API
Extension	Version	Licence	Description	Authors
[PageImages](https://www.mediawiki.org/wiki/Extension:PageImages)	–	[WTFPL](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/PageImages)	Collects information about images used on page	Max Semenik
Other
Extension	Version	Licence	Description	Authors
[Bootstrap](https://www.mediawiki.org/wiki/Extension:Bootstrap)	4.6.0	[GPL-3.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Bootstrap)	Provides the [Bootstrap](https://getbootstrap.com/) framework in the wiki	[Stephan Gambke](https://www.mediawiki.org/wiki/User:F.trott), [Professional.Wiki](https://professional.wiki/) and James Hong Kong
[Gadgets](https://www.mediawiki.org/wiki/Extension:Gadgets)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Gadgets)	Lets users select custom [CSS and JavaScript gadgets](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Gadgets) in their [preferences](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Preferences#mw-prefsection-gadgets)	Daniel Kinzler and Max Semenik
[JSBreadCrumbs](https://www.mediawiki.org/wiki/Extension:JSBreadCrumbs)	1.1.0 (cc0d135) 08:12, 29 December 2022	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/JSBreadCrumbs)	Adds a trail of bread crumbs below the tab bar	Ryan Lane, [Cindy Cicalese](https://www.mediawiki.org/wiki/User:Cindy.cicalese), Kevin Forbes and others
[JsonConfig](https://www.mediawiki.org/wiki/Extension:JsonConfig)	1.1.1 (27840f2) 08:14, 29 December 2022	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/JsonConfig)	Allows JSON configuration to be stored in a wiki	Yuri Astrakhan and Eranroz
[Lockdown](https://www.mediawiki.org/wiki/Extension:Lockdown)	– (6b196cb) 06:45, 10 January 2023	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Lockdown)	Per namespace group permissions	Daniel Kinzler, Platonides, Mark A. Hershberger and others
[MultimediaViewer](https://www.mediawiki.org/wiki/Extension:MultimediaViewer)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/MultimediaViewer)	Expand thumbnails in a larger size in a fullscreen interface	MarkTraceur (Mark Holmquist), Gilles Dubuc, Gergő Tisza, Aaron Arcos, Zeljko Filipin, Pau Giner, theopolisme, MatmaRex, apsdehal, vldandrew, Ebrahim Byagowi, Dereckson, Brion VIBBER, Yuki Shira, Yaroslav Melnychuk, tonythomas01, Raimond Spekking, Kunal Mehta, Jeff Hall, Christian Aistleitner, Amir E. Aharoni and [others](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/Credits/MultimediaViewer)
[OATHAuth](https://www.mediawiki.org/wiki/Extension:OATHAuth)	0.5.0	[GPL-2.0-or-later AND GPL-3.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/OATHAuth)	Provides authentication support using HMAC based one-time passwords	Ryan Lane, Robert Vogel <vogel@hallowelt.com> and Dejan Savuljesku <savuljesku@hallowelt.com>
[PageNotice](https://www.mediawiki.org/wiki/Extension:PageNotice)	– (467ab93) 06:46, 10 January 2023	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/PageNotice)	Lets you define a fixed header or footer message for each namespace or individual page	Daniel Kinzler
[Previews](https://www.mediawiki.org/wiki/Extension:Popups)	– (7e4f05d) 06:47, 10 January 2023	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/Popups)	Displays preview popups when the user hovers over a link	Prateek Saxena, [Readers Web Team](https://www.mediawiki.org/wiki/Reading/Web/Team) and Yair Rand
[SaferHTMLTag](https://www.mediawiki.org/wiki/Extension:SaferHTMLTag)	0.3b	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SaferHTMLTag)	SaferHTMLTag is an extension that prevents unauthorized users from editing pages where the <html> tag is defined when raw html ($wgRawHtml) is enabled.	[Antoine Mercier-Linteau](https://www.mediawiki.org/wiki/User:Tinss)
[SecureLinkFixer](https://www.mediawiki.org/wiki/Extension:SecureLinkFixer)	–	[GPL-3.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/SecureLinkFixer)	Rewrites URLs to HTTPS if domain always requires HTTPS	Kunal Mehta
[TextExtracts](https://www.mediawiki.org/wiki/Extension:TextExtracts)	–	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/TextExtracts)	Provides plain-text or limited HTML extracts of page content	Max Semenik
[VEForAll](https://www.mediawiki.org/wiki/Extension:VEForAll)	0.4.1	[GPL-2.0-or-later](https://waas.dd.mcn.ice.mod.gov.uk/waas/index.php/Special:Version/License/VEForAll)	A library for extensions to add VisualEditor	Pierre Boutet, Clément Flipo, Ike Hecht, Yaron Koren and Cindy Cicalese

**Comment by malberts** [comment]
You are using SMW 4.0.2. This was fixed in SMW 4.1.0. Upgrading your version should resolve this.

**Comment by MPThLee** [comment]
fixed in 8774550901969ff9fb8dae37bfa330645743c26a
