### ISSUE TITLE
New shell install using composer - fails in importing phase from smw.groups.json

### ISSUE THREAD

**Issue by pav00** [SemanticMediaWiki/SemanticMediaWiki#5467]
New shell install using composer, all ok, tables created, fails during importing phase from smw.groups.json.

Environment: MediaWiki: 1.38.2, PHP: 7.4.33, MariaDB 10.9.4, Semantic MediaWiki 4.1.1 (shows in Special:Version).

php7 runImport.php run in SemanticMediaWiki/maintenance fails in the same way. Deprecated messages below:

php7 runImport.php 

Semantic MediaWiki:                                                   4.1.1
MediaWiki:                                                           1.38.2

--- About -----------------------------------------------------------------

This script runs an import of auto-discovered content from directories
listed in `smwgImportFileDirs`.

--- Import task(s) --------------------------------------------------------

Running auto-discovery from ...
   ... .../mediawik ... /SemanticMediaWiki/data/import (smw)

Importing from smw.groups.json ...
   ... smw/schema:Group:Schema properties ...PHP Deprecated:  SMW\MediaWiki\Content\SchemaContent overrides prepareSave which was deprecated in MediaWiki 1.38. [Called from MediaWiki\Storage\PageUpdater::makeNewRevision in .../mediawiki/includes/Storage/PageUpdater.php at line 1169] in .../mediawiki/includes/debug/MWDebug.php on line 377
PHP Deprecated:  SMW\MediaWiki\Content\SchemaContent overrides fillParserOutput which was deprecated in MediaWiki 1.38. [Called from MediaWiki\Content\Renderer\ContentRenderer::getParserOutput in .../mediawiki/includes/content/Renderer/ContentRenderer.php at line 47] in .../mediawiki/includes/debug/MWDebug.php on line 377
PHP Deprecated:  Use of AbstractContent::getParserOutput was deprecated in MediaWiki 1.38. [Called from ContentHandler::callDeprecatedContentGPO in .../mediawiki/includes/content/ContentHandler.php at line 1853] in .../mediawiki/includes/debug/MWDebug.php on line 377
[0f7e5932b8a57948a74ec54f] [no req]   Error: Call to a member function getText() on null
Backtrace:
from .../mediawiki/extensions/Lingo/src/LingoParser.php(182)
#0 .../mediawiki/extensions/Lingo/src/LingoParser.php(78): Lingo\LingoParser->realParse()
#1 .../mediawiki/extensions/Lingo/src/Lingo.php(61): Lingo\LingoParser->parse()
#2 .../mediawiki/includes/HookContainer/HookContainer.php(338): Lingo\Lingo::Lingo\{closure}()
#3 .../mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 .../mediawiki/includes/HookContainer/HookRunner.php(1195): MediaWiki\HookContainer\HookContainer->run()
#5 .../mediawiki/includes/content/AbstractContent.php(591): MediaWiki\HookContainer\HookRunner->onContentAlterParserOutput()
#6 .../mediawiki/includes/content/ContentHandler.php(1853): AbstractContent->getParserOutput()
#7 .../mediawiki/includes/content/ContentHandler.php(1688): ContentHandler->callDeprecatedContentGPO()
#8 .../mediawiki/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#9 .../mediawiki/includes/Revision/RenderedRevision.php(267): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#10 .../mediawiki/includes/Revision/RenderedRevision.php(238): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#11 .../mediawiki/includes/Revision/RevisionRenderer.php(221): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#12 .../mediawiki/includes/Revision/RevisionRenderer.php(158): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#13 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#14 .../mediawiki/includes/Revision/RenderedRevision.php(200): call_user_func()
#15 .../mediawiki/includes/Storage/DerivedPageDataUpdater.php(1422): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#16 [internal function]: MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#17 .../mediawiki/includes/edit/PreparedEdit.php(97): call_user_func()
#18 .../mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/EditInfo.php(102): MediaWiki\Edit\PreparedEdit->getOutput()
#19 .../mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(84): SMW\MediaWiki\EditInfo->fetchEditInfo()
#20 .../mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(620): SMW\MediaWiki\Hooks\RevisionFromEditComplete->process()
#21 .../mediawiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onRevisionFromEditComplete()
#22 .../mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#23 .../mediawiki/includes/HookContainer/HookRunner.php(3184): MediaWiki\HookContainer\HookContainer->run()
#24 .../mediawiki/includes/Storage/PageUpdater.php(1471): MediaWiki\HookContainer\HookRunner->onRevisionFromEditComplete()
#25 .../mediawiki/includes/Storage/PageUpdater.php(911): MediaWiki\Storage\PageUpdater->doCreate()
#26 .../mediawiki/includes/page/WikiPage.php(1993): MediaWiki\Storage\PageUpdater->saveRevision()
#27 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(167): WikiPage->doUserEditContent()
#28 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(142): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent()
#29 .../mediawiki/includes/libs/rdbms/database/Database.php(4115): SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}()
#30 .../mediawiki/includes/libs/rdbms/database/Database.php(4026): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks()
#31 .../mediawiki/includes/libs/rdbms/database/DBConnRef.php(69): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle()
#32 .../mediawiki/includes/libs/rdbms/database/DBConnRef.php(608): Wikimedia\Rdbms\DBConnRef->__call()
#33 .../mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(784): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle()
#34 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(143): SMW\MediaWiki\Connection\Database->onTransactionIdle()
#35 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create()
#36 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(142): SMW\Importer\ContentCreators\DispatchingContentCreator->create()
#37 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(120): SMW\Importer\Importer->doImport()
#38 .../mediawiki/extensions/SemanticMediaWiki/maintenance/runImport.php(123): SMW\Importer\Importer->runImport()
#39 .../mediawiki/maintenance/doMaintenance.php(114): SMW\Maintenance\runImport->execute()
#40 .../mediawiki/extensions/SemanticMediaWiki/maintenance/runImport.php(131): require_once(string)
#41 {main}
PHP Fatal error:  Uncaught Wikimedia\Rdbms\DBUnexpectedError: Cannot execute Wikimedia\Rdbms\Database::rollback critical section while session state is out of sync.

A critical section from Wikimedia\Rdbms\Database::runOnTransactionIdleCallbacks has failed
#0 .../mediawiki/vendor/wikimedia/request-timeout/src/CriticalSectionScope.php(44): Wikimedia\Rdbms\Database->Wikimedia\Rdbms\{closure}()
#1 .../mediawiki/includes/libs/rdbms/database/Database.php(4026): Wikimedia\RequestTimeout\CriticalSectionScope->__destruct()
#2 .../mediawiki/includes/libs/rdbms/database/DBConnRef.php(69): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle()
#3 .../mediawiki/includes/libs/rdbms/database/DBConnRef.php(608): Wikimedia\Rdbms\DBConnRef->__call()
#4 .../mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(784): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle()
#5 .../mediawiki/extensions/SemanticMediaWiki/src/Importer/Conten in .../mediawiki/includes/libs/rdbms/database/Database.php on line 5454

Thanks for feedback so that I can get default settings finished and start exploring SMW features.

**Comment by krabina** [comment]
Can you try the same thing, but first de-activate Lingo/Semantic Glossary?

**Comment by pav00** [comment]
Sorry about the late reply. I am not able to reproduce it, that test environment is no longer available. After initial issues, SMW was uninstalled (composer.local.json with empty require), MW run update.php. SMW software was successfully uninstalled, I cannot confirm whether tables were removed with update.php script as well. SMW was installed later again, version 4.1.2 under MW 1.39.4 and php 8.1.23 for testing (at that time was extension Lingo, this one https://www.mediawiki.org/wiki/Extension:Lingo, uninstalled due to other issues). Install if 4.1.2 was successful with no messages like above. I think you can close it.

**Comment by krabina** [comment]
You would have to run setupStore.php --delete to actually delete the tables SMW creats in the database. Only removing it from composer.local.json will not be enough.
