### ISSUE TITLE
Two questions about substring matching using wildcards

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#5480]
### Setup

- SMW version: 4.1.1
- MW version: 1.39.2
- PHP version: 8.0.28
- 10.5.18-MariaDB-0+deb11u1

### Issue
I've been looking at Page Forms, the way it handles remote autocompletion with SMW and what could be improved. I was interested to know whether SMW is at all suitable for substring matching using standard SMW syntax. 

Unfortunately, I got very mixed results, some of which could point to bugs, others to limitations, but I do hope both of these could be addressed. It would also be good to get some clarification so that we can improve the documentation on what to expect and what not to expect. 

#### Limitation
- SMW supports asterisks and question marks as wildcards, so it should be possible, in theory, to match either '1 or multiple characters' or 'any single character'. For substring matching, however, it would be more helpful to have something like a percentage symbol % to match '0, 1  or multiple characters' to support [matching on every character](https://www.mediawiki.org/wiki/Extension:Page_Forms/Values,_mappings_and_autocompletion#Matching_on_every_character). 
- Fortunately, there's support for SQL's `like:` notation, which is only summarily documented. It offers the asterisk as a wildcard, not %, but it can be used to match '0, 1 or multiple characters', as if % is used internally (see below). This may well be the solution, but I wonder if those using ElasticSearch as a backend will be able to benefit from this. 
- For now, I won't go into case/accent-insensitive searching. Another time, another issue. 

#### Bugs? 
I've tested if at least my working assumptions about working with wildcards were valid, but some of the results surprised me. See the demo on this website: https://codecs.vanhamel.nl/SMWTest. Here are some results that I thought were quite revealing: 

- `[[Has chain title::~*law*]]` - does not retrieve anything
- `[[Has chain title::like:*law*]]` - does find every string containing the substring `law`, even if the substring is in final position

- `[[Has chain title::~*law]]` - does not retrieve anything, even if `law` is in final position. 
- `[[Has chain title::like:*law]]` - works fine as long as `law` is in final position

- `[[Has chain title::~med*]]` - finds those strings where any of the individual words within the string begin with `med` (probably unless the full word had been `med`)
- `[[Has chain title::like:med*]]` - finds anything where the full string begins with `med`

#### Preliminary conclusions to draw from this:
- The operator using standard tilde notation is sensitive to word boundaries and tries to match on individual words within a string
- It may work fine if actual substrings (e.g. `med', 'la', 'aw') are used. I was wrong about the asterisk in that it can actually be used to match on 'zero, one or multiple' characters
- However, no match is detected when the 'substring' matches a complete word (so not really a substring), e.g. `~*law*` or `~*law`. 
- The like operator matches on the full string. This probably makes it more suitable for use in (remote) autocompletion in Page Forms. 

### Questions
All this leaves me with two questions :

- Is the behaviour I observed universal and pretty much as intended? If so, I will go ahead and add some clarifications to the documentation. 
- Is the like notation universally supported or is it exclusive to MySQL? In other words, will things fail if you have something else like ES as your backend?

**Comment by jaideraf** [comment]
> Is the like notation universally supported or is it exclusive to MySQL? 

I think it is exclusive to MySQL, see: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1481

> In other words, will things fail if you have something else like ES as your backend?

I don't think so, but ES has some exclusive syntax, too:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Elastic/docs/search.md

**Comment by D-Groenewegen** [comment]
It's getting more interesting, because I found two more important, undocumented differences between tilde and like: notations. Both are now illustrated on [my website](https://codecs.vanhamel.nl/SMWTest): 

1. The tilde notation lets me use a bit of **case and accent folding** - e.g. `hakon` also lets me find `Håkon` - whereas the like: notation doesn't support it. 
2. With the tilde, a space between two words used as a substring gets interpreted as signifying an **OR relation**. That was new to me. 

More testing would be necessary, of course, to confirm this behaviour, both here and other websites. 

Potentially, this also changes the question whether one or the other would be suitable for autocompletion, case and accent folding being an essential feature IMO. It's possible that I'll end up combining the best of both worlds by building some kind of OR relationship in the query condition.

**Comment by WolfgangFahl** [comment]
I think we need a replacement of ask by a proper standard query language to get rid of such nitty / gritty details.

**Comment by D-Groenewegen** [comment]
> With the tilde, a space between two words used as a substring gets interpreted as signifying an OR relation. 

Assuming that for now at least, this is a feature not a bug, I updated the official documentation: https://www.semantic-mediawiki.org/wiki/Help:Search_operators. The use of live examples can be tricky, of course, but I chose something that looks relatively stable. 

Other general observations from the stuff I reported above may be included later.
