### ISSUE TITLE
Use of `Title::newFromIDs` was deprecated in MediaWiki 1.38

### ISSUE THREAD

**Issue by marijnvanwezel** [SemanticMediaWiki/SemanticMediaWiki#5497]
### Setup

- SMW version: 4.1.1
- MW version: 1.39.3 (but also 1.38)
- PHP version: 8.0.28
- DB system (MySQL, Blazegraph, etc.) and version: Elasticsearch 6.8.23

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

We get the following deprecation warning on our server:

```
PHP Deprecated: Use of Title::newFromIDs was deprecated in MediaWiki 1.38. [Called from SMW\MediaWiki\TitleFactory::newFromIDs in /var/www/-.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/TitleFactory.php at line 53] in /var/www/-.wikibase.nl/public_html/includes/debug/MWDebug.php on line 381
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Install Semantic MediaWiki on a wiki running MediaWiki 1.38 or higher.

**Comment by krabina** [comment]
Thank you for reporting! Could you provide a PR to fix it?
