### ISSUE TITLE
PHP 8.1: `str_replace deprecated` after creating a page

### ISSUE THREAD

**Issue by Hasenhirn** [SemanticMediaWiki/SemanticMediaWiki#5514]
### Setup

- SMW version: 4.1.1
- MW version: 1.39.4
- PHP version: 8.1.21 (fpm-fcgi)
- MariaDB version: 11.0.2
- Docker

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

**Deprecated:** str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/html/extensions/SemanticMediaWiki/src/Utils/TemplateEngine.php on line 120

![mediawiki error fresh install](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/76073496/9ae381ca-948d-4677-8ee9-2efc24641afd)
_(I turned on all debug messages as shown in your help page, this is still the only debug message I get)_

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

- Fresh install of very vanilla Mediawiki with SMW
- Create a page and save

Setup logs seem perfectly fine, I double checked. Please tell me if I can provide you with any more data

**Comment by Hasenhirn** [comment]
Addition: When using PHP 8.0, the deprecated message won't appear.

- SMW Version: 4.1.1
- MediaWiki: 1.39.4
- PHP: 8.0.29 (fpm-fcgi)
- MariaDB: 11.0.2-MariaDB-1:11.0.2+maria~ubu2204
- Docker

**Comment by krabina** [comment]
Closing this. Please reopen in case #5523 did not fix it.
