### ISSUE TITLE
Depreciated code error in SemanticMediaWiki/src/Utils/TemplateEngine.php

### ISSUE THREAD

**Issue by dafogary** [SemanticMediaWiki/SemanticMediaWiki#5521]
I turned on the error notifications and noticed there is an error:

Deprecated
: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in
/home/username/public_html/wiki/extensions/SemanticMediaWiki/src/Utils/TemplateEngine.php
on line
120

I am running:

Product | Version
-- | --
MediaWiki | 1.39.4
PHP | 8.1.21 (litespeed)
MySQL | 5.6.23-cll-lve
ICU | 63.1
Lua | 5.1.5
Pygments | 2.11.2
Semantic MediaWiki | 4.1.2

**Comment by KonradHoeffner** [comment]
Happens with 1.40 as well.

**Comment by StarsRivers** [comment]
look
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5523

**Comment by krabina** [comment]
Closing this. Please reopen in case #5523 did not fix it.
