### ISSUE TITLE
Can Subobjects be set using format=template?

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5522]
_This has been asked in SMW Maillist by Lucas Billett on 2019-10-09:_

I'm trying to set some subobjects using the results of an `#ask` and a `format=template`. However, it's almost like the statement doesn't get parsed when saving the article. Is there something special I'm missing? I've replicated the behavior on the sandbox [1].

Thanks,
lpab

[1] https://sandbox.semantic-mediawiki.org/wiki/SubobjectSet

**Comment by gesinn-it-gea** [comment]
I can confirm the observation. The `#subobject` actually get's parsed but not stored for some reason.

**Comment by gesinn-it-gea** [comment]
Neither the `#subobject` nor the `#set` parser function nor the `[[ ]]` annotation work inside a template that is included via `#ask`.

@JeroenDeDauw, @kghbln  what's your opinion on this? I see the use case but is there anything that speaks against this feature from an architectural point of view?

**Comment by kghbln** [comment]
Setting the `import-annotation` parameter to "yes" should do the trick. See https://www.semantic-mediawiki.org/wiki/Help:Plainlist_format/parameter_import-annotation

**Comment by gesinn-it-gea** [comment]
@kghbln many thanks for the hint! Works as expected.
