### ISSUE TITLE
PHP 8.2 error Semantic Mediawiki 4.1.2

### ISSUE THREAD

**Issue by fw25** [SemanticMediaWiki/SemanticMediaWiki#5558]
Hi,

There is a small problem if you want to use PHP 8.2 with Semantic Mediawiki 4.1.2.

**Problem**
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /home/u447783683/domains/mgmheling.nl/public_html/mgmd/extensions/SemanticMediaWiki/src/Utils/TemplateEngine.php on line 120

**Solution**
Add after line 118: if($value==null){$value="";}

With kind regards,

Felix Wagemakers

**Comment by jaideraf** [comment]
Fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5523
