### ISSUE TITLE
Explicitely sorting by @sortkey works, but shows an error

### ISSUE THREAD

**Issue by manuel-hegner** [SemanticMediaWiki/SemanticMediaWiki#5559]
### Setup

- SMW version: 4.1.2
- MW version: 1.39.5
- PHP version: 8.1.25 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.6.5-MariaDB-1:10.6.5+maria~focal

### Issue

This query is not sorted by the `@sortkey` of the subobjects
```
{{#ask:
[[-Has subobject::MyPage]]
|?Name
}}
```
This query works as expected but creates an orange error bubble saying `"@sortkey" cannot be used as a property name in this wiki.`
```
{{#ask:
[[-Has subobject::MyPage]]
|?Name
|sort=@sortkey
}}
```
I would expect both of these queries to be sorted by the @sortkey property and not to throw an error.

**Comment by D-Groenewegen** [comment]
Hi Manuel, the first query should work. @sortkey is not a semantic property but an equivalent to the sortkey for wiki pages so the second query is wrong. 

You haven't stated how the results are sorted and what kind of sorting you expected to see.

**Comment by manuel-hegner** [comment]
The sorting is not the issue. It is sorted as expected. I expect there not to be an error bubble when using @sortkey

**Comment by D-Groenewegen** [comment]
>  I expect there not to be an error bubble when using @sortkey

Like I said, @sortkey is not a semantic property. It doesn't belong with `sort=`.

**Comment by manuel-hegner** [comment]
I am sorry, I misunderstood. While trying to make a simple example that would show the problem on our wiki I did find the culprit. The @sortKey method broke and created keys without padding, leading to seamingly random sorting.

Tanks you for your help!
