### ISSUE TITLE
Missing parentheses in SQL for disjunction when not using temporary tables

### ISSUE THREAD

**Issue by mkroetzsch** [SemanticMediaWiki/SemanticMediaWiki#556]
SMW supports disjunction in queries using || in property values. If the database supports temporary table creation, this will be used to create a temporary table to join with. If temporary table creation is not supported, then the disjunction is expanded into a WHERE clause using "OR". The bug is that this OR-condition is missing parentheses ( ) around the ORs.

Example (one must use pages and properties that exist on the test wiki):
```
{{#ask: [[SMWCon Spring 2014]] [[Has conference type::SMWCon||Semantic MediaWiki||Another page]] | format=debug}}
```
might show an SQL query like:
```
SELECT DISTINCT t4.smw_title AS t,t4.smw_namespace AS ns
FROM `smw_object_ids` AS t4 INNER JOIN `smw_di_blob` AS t2 ON t4.smw_id=t2.s_id
WHERE
 ( (t2.o_hash='Article') OR (t2.o_hash='Incollection')
   OR (t2.o_hash='Inproceedings') AND t2.p_id='504' AND t2.s_id='1302'
 )
ORDER BY t4.smw_sortkey ASC LIMIT 51 OFFSET 0;
```
Note that the WHERE clause is of the form "a OR b OR c AND d AND e" which means "a OR b OR (c AND d AND e)". The correct form would be "(a OR b OR c) AND d AND e".

This causes unwanted results (since the AND part is only applied to one case, the other cases are weakened). Also, the results will be hard to interpret for the user since they may appear quite random (in the case above, you would get "SMWCon Spring 2014" if it has conference type "Another page" plus all pages that have "SMWCon" or "Semantic MediaWiki" as value of *any* wikipage property).

The fix should be very easy: just add parentheses around the affected code.

The bug was observed in SMW 2.0. The bug might affect people who run into #455 and try to disable temporary tables to avoid this.

**Comment by mkroetzsch** [comment]
Update: This still can be fixed as I described above in SMW 2.1 (the lines are a little further down, that's all). Not sure why the "easy" tag was removed. All that is needed to fix this bug is to copy the exact lines that I have already given above into the file.

**Comment by mwjames** [comment]
> his still can be fixed as I described above in SMW 2.1 (the lines are a little further down, that's all). Not sure why the "easy" tag was removed. All that is needed to fix this bug is to copy the exact lines that I have already given above into the file.

I know, no panic.

I didn't want this to end up in 2.1 because it would have meant to change the `SQLStore` (in particular the `QueryEngine`) and since those classes [0] are  poorly tested (#682 is another example where I could scream my head off) any changes (good or bad) have the potential to make things worse off.

I also noted in (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/556#issuecomment-57659669) that only after #494 got merged we are ore likely to copy the code which still leaves to write the test and following your comment it can only happen when "temporary table creation is not supported" (not sure how to test this).

[0] https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticMediaWiki/code-structure/master

**Comment by JeroenDeDauw** [comment]
The easy tag is meant to indicate tasks suitable for people new to the codebase. This task might be easy for either of us, though I'm dubious about it being suitable for new people.

**Comment by JeroenDeDauw** [comment]
> All that is needed to fix this bug is to copy the exact lines that I have already given above into the file.

You do realize you can just go to the file in the GH web UI, click "edit", make the change, select the branch option at the bottom, and hit the big green button right? That's roughly the same amount of work as pasting it here :)

**Comment by JeroenDeDauw** [comment]
> I know, no panic.

![omgwtf](https://cloud.githubusercontent.com/assets/146040/5885504/d1dc7b9c-a36e-11e4-8feb-5a3d8e321c93.gif)

**Comment by mwjames** [comment]
I applied suggested changes (1aca61d) but the postgres integration test fails (for details see https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/978#issuecomment-92253414) and I have no time to fix this therefore the test is skipped for postgres.

> Not sure why the "easy" tag was removed. All that is needed to fix this bug is to copy the exact lines that I have already given above into the file.

PS: Fixing something without verification, is not a fix.

PSS: The added integration test would probably have failed with or without the suggested changes which just proves that this part of the code and/or the query condition has never been tested before until now.
