### ISSUE TITLE
PHP Deprecated:  Use of "self" in callables is deprecated in LinksEncoder.php on line 115

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#5562]
### Setup

- SMW version: 4.1.2
- MW version: 1.40.1
- PHP version: 8.2
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
PHP Deprecated:  Use of "self" in callables is deprecated in /data/srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Parser/LinksEncoder.php on line 115
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Observed while running `php rebuildData.php --p --namespace=NS_MAIN`

**Comment by bertrandgorge** [comment]
From what I understand, the fix is to remove self from the callback function here: 
```

	/**
	 * @since 2.5
	 *
	 * @param string $text
	 *
	 * @return text
	 */
	public static function removeAnnotation( $text ) {

		if ( strpos( $text, '::' ) === false && strpos( $text, ':=' ) === false ) {
			return $text;
		}

		return preg_replace_callback(
			LinksProcessor::getRegexpPattern( false ),
			'LinksEncoder::doRemoveAnnotation', // instead of 'self::doRemoveAnnotation',
			self::decodeSquareBracket( $text )
		);
	}


```

**Comment by Nikerabbit** [comment]
That should work. Using `[ self::class, 'doRemoveAnnotation' ]` should also work and should be more refactoring-friendly.
