### ISSUE TITLE
Issue with Semantic MediaWiki when used in conjunction with Lockdown

### ISSUE THREAD

**Issue by dafogary** [SemanticMediaWiki/SemanticMediaWiki#5566]
SMW version: 4.1.2
Asspciated with Lockdown: – (86d9ad6) 05:47, 1 August 2023
MediaWiki: 1.39.5
Operating system: Ubuntu
PHP: 8.1.25
MySQL 5.6.23-cll-lve

I am experiencing the same issue on a private Wiki on an Intranet which is using PHP 8.2 and MariaDB

When using Semantic MediaWiki in conjunction with the Lockdown extension (https://www.mediawiki.org/wiki/Extension:Lockdown) the Special:Ask page is able to display content that is supposed to be hidden from view.

I created a test page in a private namespace Private: (https://cheekyfactor.com/wiki/index.php/Private:Test_page), if you navigate via that page it prompts you to login as expected.

But from the Special:Ask page (https://cheekyfactor.com/wiki/index.php/Special:Ask), if you search for {{Private:Test page}} you can see the content of the private page.

**Comment by D-Groenewegen** [comment]
Hi @dafogary, I don't think this is an issue with SMW. You'll probably find that a 'locked down' page can be transcluded anywhere, unless you add the relevant namespace to `$wgNonincludableNamespaces` - see https://www.mediawiki.org/wiki/Extension:Lockdown. If that doesn't work for some reason, please post on https://www.mediawiki.org/wiki/Extension_talk:Lockdown

**Comment by kghbln** [comment]
https://phabricator.wikimedia.org/T352786
