### ISSUE TITLE
Token input type print multiple values as a single value in form 

### ISSUE THREAD

**Issue by HQ1791** [SemanticMediaWiki/SemanticMediaWiki#5567]
Hi,

I am having issue with input type tokens in forms. I can select multiple values using this input type 
![clip1](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/129038344/af78615b-a0f8-4dbe-aacb-d67f3b8668ab)

but when it print the values on saved page, they appeared as single value.
![clip2 png](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/129038344/039037df-03ae-450f-8881-1cbb2e246347)

I want these values to appear separately. Also, i am getting these values from a category in form. 
`{{{field|Skills|input type=tokens|values from category=MyCategory}}}`

I am using:

Mediawiki: 1.39.4
Semantic Mediawiki: 4.1.1

What is the issue here?

Thank you!

**Comment by kghbln** [comment]
You also need to store multiple values with the template. Either use `#set` together with the separator parameter https://www.semantic-mediawiki.org/wiki/Help:Setting_values/Working_with_the_separator_parameter or `#arraymap`https://www.mediawiki.org/wiki/Extension:Page_Forms/Page_Forms_and_templates#arraymap
