### ISSUE TITLE
SMW requires collation update every time

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5609]
SMW is checking the collation settings and issues a warning in case it needs the updateEntityCollation.php setting to run. After this is run, the warning goes away.

I have the following setting
- $wgCategoryCollation is NOT set, meaning it defaults to `$wgCategoryCollation="uppercase";`, according to https://www.mediawiki.org/wiki/Manual:$wgCategoryCollation
- `$smwgEntityCollation = 'uppercase';` which is not the default, according to https://www.semantic-mediawiki.org/wiki/Help:$smwgEntityCollation, but matches the MediaWiki's setting.

What happens is that even if I don't change any of these settings, SMW requires me to run updateEntityCollation every time after I run a composer update.

I don't understand the rationale. Setting `$wgCategoryCollation="uppercase";` manually in LocalSettings.php does not change it.

### Setup

- SMW version: 4.1.3
- MW version: 1.39.6
- PHP version: 8.1
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 8.0.28

see also https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2429

**Comment by Nikerabbit** [comment]
Does your "composer up" by any change remove the .smw.json file? The collation is tracked there and the file is lost or the collation key go missing there, it would cause this behavior.

If you cannot stop using composer to install SMW, try setting [$smwgConfigFileDir](https://www.semantic-mediawiki.org/wiki/Help:$smwgConfigFileDir) to some place where it is not getting lost.

**Comment by krabina** [comment]
Thank you, will certainly try this. Have never looked into this option. Thus closing this for now.
