### ISSUE TITLE
#ask -> Result->... further results -> Error

### ISSUE THREAD

**Issue by zampaleu** [SemanticMediaWiki/SemanticMediaWiki#5621]
Clicking on  .. further results in my  #ask query display following error 

format%3Dtable Error: Typed property Parser::$mOutput must not be accessed before initialization

Mediawiki: 1.4.1
MariaDB:10.11
Semantic MediaWiki: 4.1.3
PHP: 8.2

**Comment by Nikerabbit** [comment]
Should be fixed in master (pending release): #5579. Can you confirm?

**Comment by jaideraf** [comment]
As there were no response from the above question, I think this issue can be closed.
