### ISSUE TITLE
New Install. Its asking for git@gitlab.hallowelt.com's password:

### ISSUE THREAD

**Issue by JackTheTwitcher** [SemanticMediaWiki/SemanticMediaWiki#5648]
Hello, 

I am trying to do the composer install and I am getting stuck after. " sudo composer update --no-dev "

Its asking for git@gitlab.hallowelt.com's password:   and I am not sure why, or what this would be.  

The authenticity of host 'gitlab.hallowelt.com (202.61.243.62)' can't be established.
ED25519 key fingerprint is SHA256:REnojCtKtzSGDiJjQ2iGB8GBZx2zmNCM6CBsGD0Kf00.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
git@gitlab.hallowelt.com's password:

What could I be doing wrong?

**Comment by Nikerabbit** [comment]
You probably have something in your composer dependencies that pulls in from Hallowelt's gitlab. Try "grepping" for the URL or try `-v` for composer. This doesn't seem to have anything to do with SMW unless further information is provided.

**Comment by JackTheTwitcher** [comment]
Thank you.
