### ISSUE TITLE
Investigate, why tests for SQlite are failing

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5666]
example: https://github.com/SemanticMediaWiki/SemanticMediaWiki/actions/runs/9942646248/job/27464593205#step:5:5710

Seems to be an issue with table prefix

**Comment by gesinn-it-ilm** [comment]
This issue is fixed. CI for MW 1.39 and SQlite database is working now. 

Method **cloneDatabaseTables()** inside class **TestDatabaseTableBuilder** updated for database _SQlite_. 
Prefix removed and set to empty string.
