### ISSUE TITLE
Stuck on Profile:Facetedsearch default profile

### ISSUE THREAD

**Issue by keepersdungeon** [SemanticMediaWiki/SemanticMediaWiki#5675]
### Setup

- SMW version: 4.2.0
- MW version: 1.41
- PHP version: 8.1

### Issue
Upgrading from 4.1.3 to 4.2.0 seems to go well with composer but when I try to update database with mediawiki update.php, it seems to get stuck at

```
-------------------------------------------------------- Import task(s) ---

Importing from smw.search.json ...
   ... smw/schema:Profile:Facetedsearch default profile ...
   
```

And then nothing happens. If I hit Ctrl+C and I check in the wiki it seems to have been upgraded but is this a normal behavior?

**Comment by keepersdungeon** [comment]
and then I have this on the facetedsearch page

`[70a4e9955b6c30480a1be247] 2024-07-19 15:01:13: Fatal exception of type "SMW\MediaWiki\Specials\FacetedSearch\Exception\DefaultProfileNotFoundException"`

So I guess it didn't fully update 
I left it for about 5 min, how long does this usually take?

**Comment by JeroenDeDauw** [comment]
@YOUR1 @jaideraf @krabina Did any of you encounter this issue?

**Comment by jaideraf** [comment]
No, my environment is different (MW: 1.39.6, PHP 7.4.3, Elasticsearch 7.10.2) and `update.php` runs fine when updating. 
Like @krabina, I am trying to keep my wiki on MW LTS versions, and avoiding upgrade PHP while WMF runs on PHP 7.4.

**Comment by YOUR1** [comment]
> @YOUR1 @jaideraf @krabina Did any of you encounter this issue?

No, the import also shouldn't take 5 minutes. It's just creating the pages in MW; that shouldn't take too long normally. You could try rerunning the update.php script and disable any other extensions used except SMW.

**Comment by keepersdungeon** [comment]
> > @YOUR1 @jaideraf @krabina Did any of you encounter this issue?
> 
> The import process shouldn't take 5 minutes. It's only creating the pages in MediaWiki, which usually doesn't take that long.
> 
> @keepersdungeon you might want to try rerunning the update.php script with only the SMW extension enabled, and without any other extensions.

Thanks @YOUR1 , yeah that worked and then after this run re-running with all extensions enabled seems to go through as well.
facetedsearch page working too.

Thank you!
