### ISSUE TITLE
VM image creation

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#568]
It'd be cool to have VM images of debian/ubuntu with SMW installed created, either on regular basis or as part of the release process.

Thoughts on how we can make progress on this?

**Comment by kghbln** [comment]
@lexsulzer FYI

**Comment by mwjames** [comment]
- #1218
- https://gerrit.wikimedia.org/r/#/c/262833/
