### ISSUE TITLE
setupStore.php fails with "Cannot replace user for existing actor" after upgrading from MW 1.34 to MW 1.39

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticMediaWiki#5731]
### New Setup

- SMW version: 4.2.0
- MW version: 1.39
- PHP version: 8.1.30 (fpm-fcgi)
- DB system MySQL: 10.3.39

### Old Setup

- SMW version: 3.2.3
- MW version: 1.34.4
- PHP version: 7.2.33
- DB system: MySQL 5.5.68

### Issue

After importing a MW 1.34 SMW 3.2.3 mysql wiki database into mysql for a new MW 1.39 SMW 4.2.0 system, MW maintenance script update.php failed when running the SMW setup.php portion of the script. 

The output is as follows:
```
-------------------------------------------------------- Import task(s) ---

Importing from smw.groups.json ...
   ... smw/schema:Group:Schema properties ...                 [EXISTS,SKIP]
   ... smw/schema:Group:Predefined properties ...             [EXISTS,SKIP]
   ... done.

Importing from smw.search.json ...
   ... smw/schema:Profile:Facetedsearch default profile ...CannotCreateActorException from line 519 of /opt/htdocs/mediawiki/includes/user/ActorStore.php: Cannot replace user for existing actor: actor_id=1, new user_id=38
#0 /opt/htdocs/mediawiki/includes/user/User.php(883): MediaWiki\User\ActorStore->acquireSystemActorId(Object(MediaWiki\User\UserIdentityValue), Object(Wikimedia\Rdbms\DatabaseMysqli))
#1 /opt/htdocs/mediawiki/includes/user/User.php(2717): User::{closure}(Object(MediaWiki\User\UserIdentityValue), Object(Wikimedia\Rdbms\DatabaseMysqli))
#2 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(2753): User::{closure}(Object(Wikimedia\Rdbms\DatabaseMysqli), 'User::insertNew...')
#3 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->doAtomicSection('User::insertNew...', Object(Closure))
#4 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(665): Wikimedia\Rdbms\DBConnRef->__call('doAtomicSection', Array)
#5 /opt/htdocs/mediawiki/includes/user/User.php(2724): Wikimedia\Rdbms\DBConnRef->doAtomicSection('User::insertNew...', Object(Closure))
#6 /opt/htdocs/mediawiki/includes/user/User.php(884): User::insertNewUser(Object(Closure), 'token', Array)
#7 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(156): User::newSystemUser('Maintenance scr...', Array)
#8 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(142): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent(Object(WikiPage), Object(Title), Object(SMW\Importer\ImportContents), 'CREATE')
#9 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(2501): SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}(1, Object(Wikimedia\Rdbms\DatabaseMysqli))
#10 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(2412): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks(1, Array)
#11 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle(Object(Closure))
#12 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(628): Wikimedia\Rdbms\DBConnRef->__call('onTransactionCo...', Array)
#13 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(784): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle(Object(Closure))
#14 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(143): SMW\MediaWiki\Connection\Database->onTransactionCommitOrIdle(Object(Closure))
#15 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create(Object(SMW\Importer\ImportContents))
#16 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(142): SMW\Importer\ContentCreators\DispatchingContentCreator->create(Object(SMW\Importer\ImportContents))
#17 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(120): SMW\Importer\Importer->doImport(Object(SMW\Importer\ImportContents))
#18 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1510): SMW\Importer\Importer->runImport()
#19 /opt/htdocs/mediawiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete(Object(SMW\SQLStore\TableBuilder\MySQLTableBuilder), Object(Onoi\MessageReporter\ObservableMessageReporter), Object(SMW\Options))
#20 /opt/htdocs/mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook('SMW::SQLStore::...', Array, Array, Array)
#21 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/HookDispatcher.php(308): MediaWiki\HookContainer\HookContainer->run('SMW::SQLStore::...', Array)
#22 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(279): SMW\MediaWiki\HookDispatcher->onInstallerAfterCreateTablesComplete(Object(SMW\SQLStore\TableBuilder\MySQLTableBuilder), Object(Onoi\MessageReporter\ObservableMessageReporter), Object(SMW\Options))
#23 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(456): SMW\SQLStore\Installer->install(Object(SMW\Options))
#24 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php(166): SMW\SQLStore\SQLStore->setup(Object(SMW\Options))
#25 /opt/htdocs/mediawiki/maintenance/includes/MaintenanceRunner.php(309): SMW\Maintenance\setupStore->execute()
#26 /opt/htdocs/mediawiki/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#27 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php(277): require_once('/opt/htdocs/med...')
#28 {main}

Notice: Uncommitted DB writes (transaction from User::insertNewUser) in /opt/htdocs/mediawiki/includes/libs/rdbms/database/TransactionManager.php on line 583

Notice: DB transaction writes or callbacks still pending (User::insertNewUser) in /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php on line 3760
```

Steps to reproduce 

1. Export wiki database from the old wiki using: mysqldump --single-transaction wiki_foo > wiki_foo.sql
2. Copy wiki_foo.sql to new wiki server 
3. mysql> create database wiki_foo;
4. mysql> use wiki_foo;
5. mysql> source wiki_foo.sql
6. php mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php

**Comment by alex-mashin** [comment]
Have you tried `--skip-import`? I sincerely doubt that anyone has tested simultaneous actor migration and SMW contents import.

**Comment by revansx** [comment]
Thanks. I just tried it. 

`--skip import` does allow setupStore.php to run without error, however, update.php still fails after using `--skip-import` on setupStore.

**Comment by alex-mashin** [comment]
> `update.php` still fails after having run setupStore using `--skip-import`
With the same error?

**Comment by revansx** [comment]
Yes. Same error.

**Comment by alex-mashin** [comment]
Then I suggest to switch off all semantic extensions, run `update.php` and only then switch them on back and setup semantic store.

**Comment by revansx** [comment]
Trying it now..

**Comment by revansx** [comment]
no joy, but i did notice that everytime I run setupStore the value of new user_id increments in the error:

Cannot replace user for existing actor: actor_id=1, new user_id=44
then..
Cannot replace user for existing actor: actor_id=1, new user_id=45
then..
Cannot replace user for existing actor: actor_id=1, new user_id=46
etc..

Where in the SMW folder would SMW be keeping a new use_id value each time setupStore runs?

**Comment by alex-mashin** [comment]
So, you did manage to run `update.php` with SMW switched off?

> Where in the SMW folder would SMW be keeping a new use_id value each time setupStore runs?

In the table `user`, I presume; first unused ID.

Is there a field in any of the imported `.json` files called `import performer`?

**Comment by jaideraf** [comment]
@revansx Not your case, **but almost**, MediaWiki recomends not upgrading from a MediaWiki version older than 1.33 to MediaWiki 1.39.1, for example (see the warnings in red): https://www.mediawiki.org/wiki/Manual:Upgrading. Am am just leaving a note for future upgrades.

**Comment by revansx** [comment]
> So, you did manage to run `update.php` with SMW switched off?
Yes

> In the table `user`, I presume; first unused ID.
nothing new is the user table. Both the actor table and the user table are small, easy to inspect, and easy to confirm they agree

> Is there a field in any of the imported `.json` files called `import performer`?
yes.
`/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/data/import/smw.search.json` 
contains the text:
```
{
        "description": "Semantic MediaWiki search import",
        "import": [
                {
                        "page": "Profile:Facetedsearch default profile",
                        "namespace": "SMW_NS_SCHEMA",
                        "import_performer": "SemanticMediaWikiImporter",
                        "contents": {
                                "importFrom": "/search/facetedsearch.defaultprofile.json"
                        },
                        "options": {
                                "replaceable": { "LAST_EDITOR": "IS_IMPORTER" }
                        }
                }
        ],
        "meta": {
                "version": "1"
        }
}
```

**Comment by alex-mashin** [comment]
And does user `SemanticMediaWikiImporter` exist? If he does, try removing him, if he doesn't, try adding.

**Comment by revansx** [comment]
how and where would I add that user? In Mysql? In Actor table? User table? both? .. somewhere else? Thank you!

**Comment by alex-mashin** [comment]
You could try [`maintenance/CreateAndPromote.php`](https://www.mediawiki.org/wiki/Manual:CreateAndPromote.php). Although, I growing less sure that it is a good idea.

**Comment by revansx** [comment]
I added user "" using:
`php /opt/htdocs/mediawiki/maintenance/createAndPromote.php --force --sysop SemanticMediaWikiImporter ###PW###`
and then re-ran setupStore.php again .. no joy.

.. and the new user_id keeps incrementing .. but neither the actor nor the user tables are registering the increase.

so now I'm wondering what "exception" the script is trying to "create" when it says "...CannotCreateActorException" ... "Cannot replace user for existing actor: actor_id=1 ..."

**Comment by alex-mashin** [comment]
> so now I'm wondering what "exception" the script is trying to "create" when it says "...CannotCreateActorException" ... "Cannot replace user for existing actor: actor_id=1 ..."

`includes/user/ActorStore.php`, line 518:
```php
if ( $this->userNameUtils->isUsable( $userName ) || $existingActor->isRegistered() ) {
				throw new CannotCreateActorException(
					'Cannot replace user for existing actor: ' .
					"actor_id=$existingActorId, new user_id=$userId"
				);
			}
```

You can try to use debugging to find out whether it is `$this->userNameUtils->isUsable( $userName )` or `$existingActor->isRegistered()`.

**Comment by alex-mashin** [comment]
You could also try to add `SemanticMediaWikiImporter` to [`$wgReservedUsernames`](https://www.mediawiki.org/wiki/Manual:$wgReservedUsernames).

**Comment by revansx** [comment]
I tried adding `$wgReservedUsernames[] = 'SemanticMediaWikiImporter';` to LocalSettings .. no joy

I will debug the ActorStore.php later today and let you. 

Thank you.

**Comment by alex-mashin** [comment]
> I tried adding `$wgReservedUsernames[] = 'SemanticMediaWikiImporter';` to LocalSettings .. no joy

Had you removed the recently createds user `SemanticMediaWikiImporter` prior to setting `$wgReservedUsernames[] = 'SemanticMediaWikiImporter';`?

**Comment by revansx** [comment]
No. I'd like to give that a try.. sorry to have to ask.. what is the method for removing a user?  is there a maintenance script for that?

**Comment by alex-mashin** [comment]
> No. I'd like to give that a try.. sorry to have to ask.. what is the method for removing a user? is there a maintenance script for that?

Try [`maintenance\removeUnusedAccounts.php`](https://www.mediawiki.org/wiki/Manual:RemoveUnusedAccounts.php).

**Comment by revansx** [comment]
Hmm.. No unused user accounts found. That's odd.. I just created the user "SemanticMediaWikiImporter" 10 minutes ago.

**Comment by alex-mashin** [comment]
> Hmm.. removeUnusedAccounts says "No unused user accounts found". That's odd.. I just created the user "SemanticMediaWikiImporter" 10 minutes ago.

Then just delete it from `user` table; and from `actor`, if there is a linked record.

**Comment by revansx** [comment]
ok.. noticed that there were some additional messages after the stack trace that I failed to include in the original bug report (now updated) ... the are:
```
Notice: Uncommitted DB writes (transaction from User::insertNewUser) in /opt/htdocs/mediawiki/includes/libs/rdbms/database/TransactionManager.php on line 583

Notice: DB transaction writes or callbacks still pending (User::insertNewUser) in /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php on line 3760
```
This could explain why everytime I run setupStore.php the user_id increments.

Does this shed any new light on the situation?

**Comment by revansx** [comment]
UPDATE - we were finally able to get setupStore.php to run by manually adding the following two pages:

- "smw/schema:Profile:Facetedsearch default profile" and
- "MediaWiki:Smw import schema"


whatever the root issue is, it does not seem to be related to a failure to create users but rather a failure to create the required pages in the wiki.

Public examples of these pages can be found at:

- Here --> https://wikimsk.org/w/index.php?title=smw/schema:Profile:Facetedsearch_default_profile&action=edit
- and here --> https://wikimsk.org/w/index.php?title=MediaWiki:Smw%20import%20schema&action=edit

**Comment by alex-mashin** [comment]
The system user had to be the author of those required pages.

**Comment by revansx** [comment]
Ah! .. and on the MW 1.34 SMW 3.x we used the DeleteAndMerge extension to remove the sysop account. Does that explain it?
