### ISSUE TITLE
Add "ORDER BY" feature from SQL in SMW

### ISSUE THREAD

**Issue by AavaAana** [SemanticMediaWiki/SemanticMediaWiki#5734]
I'm editing a gamewiki that includes a lot of cards for various characters. There are pages I found using SMW to list the cards convieniently. But an ORDER BY feature might be good for readers to customize the order while they are sorting other stuff.

**Comment by jaideraf** [comment]
Do you mean this?: https://www.semantic-mediawiki.org/wiki/Help:Sorting

**Comment by AavaAana** [comment]
> Do you mean this?: https://www.semantic-mediawiki.org/wiki/Help:Sorting

Thankyou. This could helping us to apply it when we added the property. Sorry for my bad expression. I was kinda looking for a way to order it without adding the property……Now think about it probably easier to just simply add the property by using VLOOKUP from excel...... Well have to output the excel first

**Comment by AavaAana** [comment]
> > Do you mean this?: https://www.semantic-mediawiki.org/wiki/Help:Sorting
> 
> Thankyou. This could helping us to apply it when we added the property. Sorry for my bad expression. I was kinda looking for a way to order it without adding the property……Now think about it probably easier to just simply add the property by using VLOOKUP from excel...... Well have to output the excel first

Anyway problem fixed thanks for the help.
