### ISSUE TITLE
SMW should not load unnecessary ResourceLoader modules 

### ISSUE THREAD

**Issue by alistair3149** [SemanticMediaWiki/SemanticMediaWiki#5743]
### Setup

- SMW version: `5.0.0-alpha`
- MW version: `1.39.10`
- PHP version: `8.1.30`
- DB system (MySQL, Blazegraph, etc.) and version: `11.4.3-MariaDB-ubu2404`

### Issue

SMW is loading unnecessary ResourceLoader modules even when the page do not contain any elements that requires them.
These unused styles and scripts are render-blocking and significantly affect the load time of the page.

- ✅ `ext.smw.style` - load on all pages [(source)](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/b045a2db20bfe4d303c5fbe045b4645e63c11b5b/src/MediaWiki/Hooks/BeforePageDisplay.php#L71) 
    - Partially addressed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5752, we should break down the styles
    - Moved away from base64 images with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5761
- ✅ `ext.smw.tooltip.styles` - load on all pages [(source)](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/b045a2db20bfe4d303c5fbe045b4645e63c11b5b/src/MediaWiki/Hooks/BeforePageDisplay.php#L72)
    - Fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5752
- ✅ `ext.smw.special.styles` - load on all pages under `Special` namespace  [(source)](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/b045a2db20bfe4d303c5fbe045b4645e63c11b5b/src/MediaWiki/Hooks/BeforePageDisplay.php#L79)
    - Fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5752 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5753
- ✅ `ext.smw.skin.css` - load on all skins, it should use skinStyles instead.
    - Fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5755
- ✅ `ext.libs.tippy` - load on all pages, this is especially bad because it is an external library
  - Merged into `ext.smw.tooltip` in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5762, `ext.smw.tooltip` should no longer being loaded on non-SMW pages.
- ✅ `ext.smw` - load on all pages https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5762
  - Seems to be fixed with 
- ✅ `ext.smw.tooltips` - load on all pages
  - Merged into `ext.smw.tooltip` in  https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5762
- ✅ `smw.tippy` - load on all pages
  - Merged into `ext.smw.tooltip` in  https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5762
- probably more...

Just the `ext.smw.style` alone contributes to ~16.0 KB gzipped (40%) to the initial RL stylesheet...

Steps to reproduce:
1. Go on any pages.
2. Open your browser's dev tools and inspect network request
3. Note the first `load.php` stylesheet URL

For visibility purpose, I am linking a similar issue for SRF: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/856

**Comment by alistair3149** [comment]
Is it safe to switch base64 images back to referencing an image in the extension directory? The base64 images are adding a lot of bytes to the stylesheet, and separating them would allow different caching rules.

**Comment by jaideraf** [comment]
See also: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5635

**Comment by jaideraf** [comment]
@alistair3149 in Special:Version the `smw-callout` are not correct rendered. Maybe it is related to your changes.

![smw](https://github.com/user-attachments/assets/91689fb1-b5bf-4f86-a1cb-905b396ea3d6)

**Comment by jaideraf** [comment]
Actually not only in Special:Version... this is in the Template namespace:
![smw-template](https://github.com/user-attachments/assets/584a8c73-5fd5-488e-8adb-abb71d1c8f2d)

**Comment by alistair3149** [comment]
Looking into it, will make a patch for that

**Comment by alistair3149** [comment]
Closing the issue as there are no traces of SMW modules anymore other than `ext.smw.purge` on non-SMW page. 🎉

**Comment by jaideraf** [comment]
@alistair3149 Thank you for all these changes. Your contribution is amazing to the project. However, I am testing some of the changes (merged so far) and I have noticed the eye icon is missing on the property page, see:
![eye](https://github.com/user-attachments/assets/83538db1-0f08-4712-ada3-73593f3cc0bd)

Compare the original version: https://www.semantic-mediawiki.org/wiki/Property:Capital_of

**Comment by jaideraf** [comment]
Nevermind, I think this was a caching issue, sorry.

**Comment by jaideraf** [comment]
Actually, both icons:

* https://www.semantic-mediawiki.org/w/index.php?title=Special%3ASearchByProperty&property=Last+editor+is&value= (magnifier)
* https://www.semantic-mediawiki.org/wiki/Special:SearchByProperty/:Average-20rainy-20days/84.5 (eye)

**Comment by jaideraf** [comment]
Maybe another error related to the changes is this: 

![Captura de tela de 2024-11-20 07-59-47](https://github.com/user-attachments/assets/df3f3cc7-ca64-4ce1-9284-48810c2b1707)

**Comment by jaideraf** [comment]
I suspect this is also not correct stylized: 
![pending-tasks](https://github.com/user-attachments/assets/f7291ab7-4b29-4318-b72e-bb78352703a5)

**Comment by jaideraf** [comment]
And possibly here (click in some of the fields):
https://wikincat.org/w/index.php?title=Especial:Busca&profile=smw&search=&fulltext=1&uselang=en
![search-profile](https://github.com/user-attachments/assets/73cdc27a-c3f0-4358-ab65-cb1e27052cfb)

**Comment by alistair3149** [comment]
No problem, thanks for catching them as it is quite hard to catch the all the cases. I'll follow up with PR today to address them.

**Comment by alistair3149** [comment]
Follow up PR here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5772
The fix should do for now but eventually we will have to refactor `ext.smw.styles` and separate all the non-critical styles from it. RL module styles should only be loaded when they are needed for initial states or noscript support.

> Maybe another error related to the changes is this:
> 
> ![Captura de tela de 2024-11-20 07-59-47](https://private-user-images.githubusercontent.com/3636594/388065749-df3f3cc7-ca64-4ce1-9284-48810c2b1707.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzI4MTAsIm5iZiI6MTczMjEzMjUxMCwicGF0aCI6Ii8zNjM2NTk0LzM4ODA2NTc0OS1kZjNmM2NjNy1jYTY0LTRjZTEtOTI4NC00ODgxMGMyYjE3MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTk1NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQxMjQ0OGEzNWQxMmU1MmVmNzBlNDNiMDAzYjE1ZjI4NmExMDIwY2YxODEwMThhOTYxNDNiMGFkYmQyNWU3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rV3J2j_c1qTwS96VuScvN1_lViJZV6WLOndI-caSthY)

I couldn't reproduce this issue

**Comment by jaideraf** [comment]
> I couldn't reproduce this issue

Right. You can see the error alive here, see the console: https://wikincat.org/wiki/B000006 (maybe you need to clear the cache)

**Comment by alistair3149** [comment]
Thanks it should be now fixed in the same PR! I can't replicate the exact set up as your wiki locally but it should do the trick.

**Comment by jaideraf** [comment]
@alistair3149 unfortunately there is still errors on the console, look:
https://wikincat.org/wiki/B000006

![still-error](https://github.com/user-attachments/assets/ec055a49-8d4a-4b56-9b2f-6209f88d9db1)

**Comment by alistair3149** [comment]
I filed https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5778 to remove `mediawiki.api.parse`. As for the entity examiner error, I can't access it so I can't debug it properly. Is there a way to reproduce that entity examiner status?

**Comment by jaideraf** [comment]
> As for the entity examiner error, I can't access it so I can't debug it properly. Is there a way to reproduce that entity examiner status?

Yes, only shows up when some maintenance script is running. For example, when new changes are merged here on the repository, I run `composer update --no-dev` in my wiki. Then the SMW block access to MW until the `maintenance/update.php` (ou the SMW `setupStore.php`) is run (all fine here). When the access to the wiki returns, you see that callout from SMW asking to run two scripts ([rebuildElasticIndex.php](https://www.semantic-mediawiki.org/wiki/Help:rebuildElasticIndex.php)) and [updateEntityCollation.php](https://www.semantic-mediawiki.org/wiki/Help:updateEntityCollation.php). You can now see it in Especial:PendingTaskList (I gave you the permissions on the wiki). When [rebuildElasticIndex.php](https://www.semantic-mediawiki.org/wiki/Help:rebuildElasticIndex.php) is running you can see that error above on the console. When the script ends (or stops) the error do not show anymore. 

So, if you can't reproduce the error in your environment, I can run the script again here, if you want. Just give-me one time UTC to do it (because the script ends in a couple of minutes).

**Comment by jaideraf** [comment]
Just adding more context to the error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Object.onShow (<anonymous>:49:223)
    at Object.show (<anonymous>:27:923)
    at Lt (<anonymous>:35:855)
    at z (<anonymous>:30:75)
    at <anonymous>:36:441
    at Array.reduce (<anonymous>)
    at F (<anonymous>:36:410)
    at HTMLDivElement.d (<anonymous>:45:465)`
    
  When clicking on the link VM300:49:
  
![still-error2](https://github.com/user-attachments/assets/e5a835af-de46-4b36-846d-c6c4283d3fb5)

The begin of the code:

![still-error3](https://github.com/user-attachments/assets/ef6a6150-48f1-47bc-8423-8fbd91f41523)

**Comment by jaideraf** [comment]
Does this line: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/d007fd4d5cca2ed212509c85e6a3cca120b3a95f/res/smw/util/ext.smw.tooltip.tippy.js#L113

Should not be like this?

```js
tip.popper.firstElementChild.tooltip.classList.add( "data-tooltipclass" );
```

**Comment by alistair3149** [comment]
> Does this line:
> 
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/d007fd4d5cca2ed212509c85e6a3cca120b3a95f/res/smw/util/ext.smw.tooltip.tippy.js#L113
> 
> Should not be like this?
> 
> ```js
> tip.popper.firstElementChild.tooltip.classList.add( "data-tooltipclass" );
> ```

No that part is correct, it was ` tip.popper.firstElementChild.tooltip` that returns undef. I might be able to take a look next week.
