### ISSUE TITLE
Elasticsearch\Common\Exceptions\BadRequest400Exception on SMW 4.2.0

### ISSUE THREAD

**Issue by michael-wikibase** [SemanticMediaWiki/SemanticMediaWiki#5801]
### Setup

- SMW version: 4.2.0
- MW version: 1.39.10
- PHP version: 8.1.2
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 8.0.39

### Issue

While doing an MW upgrade from 1.35.14 to 1.39.10 im getting this exception when running update.php:
`Elasticsearch\Common\Exceptions\BadRequest400Exception from line 693 of /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [data : {dynamic_templates=[{text_fields={path_match=P:*.txtField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=2000, type=keyword}}}, match_mapping_type=*}}, {uri_fields={path_match=P:*.uriField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={analyzer=uri_lowercase_with_stopwords, type=text}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=2000, type=keyword}}}, match_mapping_type=*}}, {page_fields_text={path_match=P:*.wpgField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={normalizer=lowercase_normalizer, type=keyword}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=500, type=keyword}}}, match_mapping_type=*}}, {page_fields_identifier={path_match=P:*.wpgID, mapping={type=long}, match_mapping_type=*}}, {numeric_fields={path_match=P:*.numField, mapping={type=double, fields={keyword={ignore_above=256, type=keyword}}}, match_mapping_type=*}}, {date_fields={path_match=P:*.datField, mapping={type=double, fields={keyword={ignore_above=256, type=keyword}}}, match_mapping_type=*}}, {date_fields_raw={path_match=P:*.dat_raw, mapping={type=keyword}, match_mapping_type=*}}, {geo_fields={path_match=P:*.geoField, mapping={type=keyword, fields={point={type=geo_point}}}, match_mapping_type=string}}, {boolean_fields={path_match=P:*.booField, mapping={type=boolean}, match_mapping_type=boolean}}], properties={noop={type=integer}, subject.subobject={term_vector=with_positions_offsets, type=text, fields={keyword={ignore_above=256, type=keyword}}}, text_raw={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}}, doc_values=false}, subject.rev_id={type=integer}, text_copy={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}}, doc_values=false}, subject.interwiki={term_vector=with_positions_offsets, type=text, fields={keyword={ignore_above=256, type=keyword}}}, subject.title={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}, sort={normalizer=standard_sort_normalizer, index=false, type=keyword}, keyword={ignore_above=256, type=keyword}}}, subject.sortkey={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={normalizer=lowercase_normalizer, type=keyword}, sort={normalizer=standard_sort_normalizer, index=false, type=keyword}, keyword={ignore_above=256, type=keyword}}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [data : {dynamic_templates=[{text_fields={path_match=P:*.txtField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=2000, type=keyword}}}, match_mapping_type=*}}, {uri_fields={path_match=P:*.uriField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={analyzer=uri_lowercase_with_stopwords, type=text}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=2000, type=keyword}}}, match_mapping_type=*}}, {page_fields_text={path_match=P:*.wpgField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={normalizer=lowercase_normalizer, type=keyword}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=500, type=keyword}}}, match_mapping_type=*}}, {page_fields_identifier={path_match=P:*.wpgID, mapping={type=long}, match_mapping_type=*}}, {numeric_fields={path_match=P:*.numField, mapping={type=double, fields={keyword={ignore_above=256, type=keyword}}}, match_mapping_type=*}}, {date_fields={path_match=P:*.datField, mapping={type=double, fields={keyword={ignore_above=256, type=keyword}}}, match_mapping_type=*}}, {date_fields_raw={path_match=P:*.dat_raw, mapping={type=keyword}, match_mapping_type=*}}, {geo_fields={path_match=P:*.geoField, mapping={type=keyword, fields={point={type=geo_point}}}, match_mapping_type=string}}, {boolean_fields={path_match=P:*.booField, mapping={type=boolean}, match_mapping_type=boolean}}], properties={noop={type=integer}, subject.subobject={term_vector=with_positions_offsets, type=text, fields={keyword={ignore_above=256, type=keyword}}}, text_raw={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}}, doc_values=false}, subject.rev_id={type=integer}, text_copy={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}}, doc_values=false}, subject.interwiki={term_vector=with_positions_offsets, type=text, fields={keyword={ignore_above=256, type=keyword}}}, subject.title={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}, sort={normalizer=standard_sort_normalizer, index=false, type=keyword}, keyword={ignore_above=256, type=keyword}}}, subject.sortkey={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={normalizer=lowercase_normalizer, type=keyword}, sort={normalizer=standard_sort_normalizer, index=false, type=keyword}, keyword={ignore_above=256, type=keyword}}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [data : {dynamic_templates=[{text_fields={path_match=P:*.txtField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=2000, type=keyword}}}, match_mapping_type=*}}, {uri_fields={path_match=P:*.uriField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={analyzer=uri_lowercase_with_stopwords, type=text}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=2000, type=keyword}}}, match_mapping_type=*}}, {page_fields_text={path_match=P:*.wpgField, mapping={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={normalizer=lowercase_normalizer, type=keyword}, sort={normalizer=standard_sort_normalizer, ignore_above=256, index=false, type=keyword}, keyword={ignore_above=500, type=keyword}}}, match_mapping_type=*}}, {page_fields_identifier={path_match=P:*.wpgID, mapping={type=long}, match_mapping_type=*}}, {numeric_fields={path_match=P:*.numField, mapping={type=double, fields={keyword={ignore_above=256, type=keyword}}}, match_mapping_type=*}}, {date_fields={path_match=P:*.datField, mapping={type=double, fields={keyword={ignore_above=256, type=keyword}}}, match_mapping_type=*}}, {date_fields_raw={path_match=P:*.dat_raw, mapping={type=keyword}, match_mapping_type=*}}, {geo_fields={path_match=P:*.geoField, mapping={type=keyword, fields={point={type=geo_point}}}, match_mapping_type=string}}, {boolean_fields={path_match=P:*.booField, mapping={type=boolean}, match_mapping_type=boolean}}], properties={noop={type=integer}, subject.subobject={term_vector=with_positions_offsets, type=text, fields={keyword={ignore_above=256, type=keyword}}}, text_raw={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}}, doc_values=false}, subject.rev_id={type=integer}, text_copy={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}}, doc_values=false}, subject.interwiki={term_vector=with_positions_offsets, type=text, fields={keyword={ignore_above=256, type=keyword}}}, subject.title={term_vector=with_positions_offsets, type=text, fields={search={analyzer=search, term_vector=with_positions_offsets, type=text}, sort={normalizer=standard_sort_normalizer, index=false, type=keyword}, keyword={ignore_above=256, type=keyword}}}, subject.sortkey={copy_to=text_copy, term_vector=with_positions_offsets, type=text, fields={lowercase={normalizer=lowercase_normalizer, type=keyword}, sort={normalizer=standard_sort_normalizer, index=false, type=keyword}, keyword={ignore_above=256, type=keyword}}}}}]"}},"status":400}
#0 /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError()
#1 /data/www/znddak.wikibase.nl/public_html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#2 /data/www/znddak.wikibase.nl/public_html/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(65): React\Promise\FulfilledPromise->then()
#3 /data/www/znddak.wikibase.nl/public_html/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#4 /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): GuzzleHttp\Ring\Core::proxy()
#5 /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#6 /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest()
#7 /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/AbstractNamespace.php(63): Elasticsearch\Transport->performRequest()
#8 /data/www/znddak.wikibase.nl/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(188): Elasticsearch\Namespaces\AbstractNamespace->performRequest()
#9 /data/www/znddak.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Elastic/Connection/Client.php(328): Elasticsearch\Namespaces\IndicesNamespace->create()
#10 /data/www/znddak.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder/Rollover.php(120): SMW\Elastic\Connection\Client->createIndex()
#11 /data/www/znddak.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Elastic/Installer.php(54): SMW\Elastic\Indexer\Rebuilder\Rollover->update()
#12 /data/www/znddak.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(328): SMW\Elastic\Installer->setup()
#13 /data/www/znddak.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Store.php(490): SMW\Elastic\ElasticStore->setup()
#14 /data/www/znddak.wikibase.nl/public_html/includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore()
#15 /data/www/znddak.wikibase.nl/public_html/includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates()
#16 /data/www/znddak.wikibase.nl/public_html/maintenance/update.php(209): DatabaseUpdater->doUpdates()
#17 /data/www/znddak.wikibase.nl/public_html/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#18 /data/www/znddak.wikibase.nl/public_html/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#19 /data/www/znddak.wikibase.nl/public_html/maintenance/update.php(319): require_once('...')
#20 {main}`

I'm using ElasticSearch 7.10.2 on the server

@marijnvanwezel

**Comment by marijnvanwezel** [comment]
This is caused by a modified data standard, and does not seem to be an issue with Semantic MediaWiki itself.
