### ISSUE TITLE
Deprecate [[property::value]] input syntax

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#584]
In favour of `#set`. To be removed in some future major release.

**Comment by ankostis** [comment]
(sorry for reviving this, but i think it is not yet put to rest)

@mkroetzsch wrote:
> ... so, if you want to display a value in several places (in some template etc.), you would need to annotate it multiple times, which is not great style ...

What about capturing the output of `#set` (or the hypothetical `#add`) into a `#vardefine` from the [_Variables_ extension](https://www.mediawiki.org/wiki/Extension:Variables)?

If the `#var` trick is acceptable, then the (2) case above still needs to be addressed somehow.
I mean, to avoid the limitations of inline-annotations and still being able to properly format the DataValue (e.g. with unit-conversions).
Another consideration is the performance hit when putting too many `#show`/`#ask` parser-functions in page just to auto-format the DVs.

To recapitulate:

- **[[inline::annotation]]**: 
  - storage: 
    - yes
  - presentation:
    - :heavy_check_mark: auto formatted values (e.g units),  
    - :x: not customizeable, 
  - :heavy_check_mark: cheap (not like `#ask`/`#show`), 
  - reuse output:
    - :x: MUST NOT repeat (even with `#vardefine`)
- **`#set` annotation**: 
  - storage: 
    - yes
  - formatting:
    - no output OR 
    - :heavy_check_mark: passed to a user-defined template
    - :x: unformatted value (so still impossible to get _units_ without expensive `#show`), 
  - :heavy_check_mark: cheap, 
  - reuse output:
    - intuitively not repeatable but 
    - :heavy_check_mark: possible to reuse output with _Extension:Variables_.
- **`#ask`/`#show`** DVs: 
  - storage: 
    - no
  - formatting:
    - auto formatted
    - fully customizable
  - :x: expensive
  - reuse output:
    - :heavy_check_mark: fully

I think we're missing the middle ground, something that behaves like `#set` but with auto-formatting DVs, and that can be captured in a `#var` and copied around. 
Something like the `#add` suggested by @kdbln,  or maybe to pass one more parameter to the `#set`'s `template` parameter, e.g. one named `{{{fvalue}}}` with the autoformatted DV?

Would that worth a new RFE-issue?

**Comment by mwjames** [comment]
@kghbln Why was this pinned? What is the expected outcome?

**Comment by kghbln** [comment]
> Why was this pinned? What is the expected outcome?

My expected outcome was that I do not want to forget this. I did not know that this is a public thing. I just wanted to pin this for myself.
