### ISSUE TITLE
Support for NoSQL as graph database

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#586]
The significance of SMW as product and software to deliver on its promise to "turn your wiki into a powerful and flexible knowledge management system" also depends on its ability to support different technical platforms to store and query statements made by its users through usage of various annotation approaches.

Currently, `SQLStore` and `SPARQLStore` are supported but what about using other technical means to store graph like data.
- [Cassandra vs MongoDB vs CouchDB vs Redis vs Riak vs HBase vs Couchbase vs OrientDB vs Aerospike vs Neo4j vs Hypertable vs ElasticSearch vs Accumulo vs VoltDB vs Scalaris comparison](http://kkovacs.eu/cassandra-vs-mongodb-vs-couchdb-vs-redis)
- [Introduction to Graph Databases](http://www.slideshare.net/maxdemarzi/introduction-to-graph-databases-12735789)
- [Using MongoDB as a high performance graph database](http://www.slideshare.net/robotrobot/mongodb-uk)
- [AllegroGraphto query MongoDB database via SPARQL 1.1 query engine](http://franz.com/agraph/support/documentation/current/mongo-interface.html#header2-47)
- [neo4j](http://neo4j.com/company/)
## Questions
- Would SMW need to support NoSQL as database platform to solve some of the shortcomings encountered with the `SQLStore`?
- What would be the benefit of supporting NoSQL?
- What would be the disadvantages of supporting NoSQL as graph database?
- Should SMW support text search feature (using ElasticSearch) before thinking about other Store interfaces?

**Comment by WolfgangFahl** [comment]
For educational purposes I created an open source barebones triplestore implementation which might be helpful for discussion what a common Java API for backend triplestores could be. 
see https://github.com/BITPlan/org.sidif.triplestore
I intend to have Neo4J and Apache Jena Backends attached so targetting this java approach would open up the way to quite a few other backends.
