### ISSUE TITLE
Fix the at() matcher has been deprecated in Unit tests for MW 1.41+

### ISSUE THREAD

**Issue by gesinn-it-ilm** [SemanticMediaWiki/SemanticMediaWiki#5873]
From matrix `1.41` and higher Unit tests are failing with the warnings among others like:

`The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.`

Update those failing tests and fix the deprecation warnings.
As possible solution try to use `exactly()` instead of `at()`.

**Comment by JeroenDeDauw** [comment]
Protip: https://www.entropywins.wtf/blog/2016/05/13/5-ways-to-write-better-mocks/

**Comment by jaideraf** [comment]
Also: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5725

**Comment by gesinn-it-ilm** [comment]
Closing this one as it's duplicate to #5725.
