### ISSUE TITLE
Check possible revert of changes from PR #5865 for composer.json and main.yml

### ISSUE THREAD

**Issue by gesinn-it-ilm** [SemanticMediaWiki/SemanticMediaWiki#5883]
It should be checked if the changes in PR #5865 for `composer.json` and `main.yml` should be reverted or updated.
Before this, CI was run in a way that had separated testsuites for **Unit** and **Integration** tests. 

Now, after PR #5865 was merged, the number of executed tests dropped down a lot for MW 1.39. 

- Unit test has around **6998** tests.
- Integration tests has around **1798** tests.

For MW 1.39 in CI now there is only 1798 tests executed, like it only run Integration tests. 
[CI_1.39](https://github.com/SemanticMediaWiki/SemanticMediaWiki/actions/runs/12456428595/job/34769903121#step:4:2223)

The `steps` in `main.yml` should be separeted to run Unit and Integration tests like before. 
Steps for running _tests with coverage_ are good, and that is why in CI for MW 1.40 we have `6998` tests executed for **Unit** and `1798` tests for **Integration**.

FYI: @JeroenDeDauw, @gesinn-it-gea, @paladox

**Comment by paladox** [comment]
Oh. I wonder why that happens? I’ve got both https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/composer.json#L129 and the line blow it using integration and unit.

**Comment by gesinn-it-ilm** [comment]
I checked once again, it works good. My mistake, I missed the part where you have defined it. 
There are both unit and integration tests. 
So I will close this issue. 

@paladox thanks :)
