### ISSUE TITLE
Link to compatibility matrix in Readme breaks link on semantic-mediawiki.org

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#599]
The link to https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md in 
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-2.0.md
does not resolve correctly in https://semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.0
"Not Found. The requested URL /COMPATIBILITY.md was not found on this server."

**Comment by mwjames** [comment]
@kghbln ?

**Comment by kghbln** [comment]
I guess we should just stick it adding relative links to such docs. Will fix the link. Sit tight.

**Comment by kghbln** [comment]
This is fixed now for master and the three 2.x branches.
@JeroenDeDauw Probably still a nice thing to have with the GitHub extension.
@krabina Thanks for reporting.
@mwjames Thanks for pinging.
