### ISSUE TITLE
URL shortener extension needed for SMW query URL's and general purpose MediaWiki uses

### ISSUE THREAD

**Issue by badon** [SemanticMediaWiki/SemanticMediaWiki#642]
The workaround for this bug requires an URL shortener:

https://bugzilla.wikimedia.org/show_bug.cgi?id=34511

There are MediaWiki extensions for producing them automatically, but they are beta quality, and users report high dissatisfaction with them. Everything you ever wanted to know:

https://www.google.com/search?q=mediawiki+url+shortener

SMW query URL's can be gargantuan, and the usage of square brackets in the URL's makes it impossible to share them as-is on forums that support BBCode (nearly all modern forums). A general purpose MediaWiki URL shortener extension would be highly desirable for SMW, and it would also be welcomed on many non-SMW systems. You can see real-world sharing of SMW query URL's for historical research purposes here:

https://www.livebusinesschat.com/smf/index.php?topic=5632.msg38414#msg38414

here:

https://www.livebusinesschat.com/smf/index.php?topic=5632.msg38430#msg38430

and here:

https://www.livebusinesschat.com/smf/index.php?topic=5632.msg38431#msg38431

In all of those use cases, I had to manually convert left and right brackets to URL-encoded formats %5B and %5D

**Comment by mwjames** [comment]
SMW core will unlikely not provide such service (it is just not is part of its core) and instead one should look for solutions that focus on solving the issue:

- https://www.mediawiki.org/wiki/Requests_for_comment/URL_shortener
- https://www.mediawiki.org/wiki/Extension:ShortUrl
