### ISSUE TITLE
UTF-8 export to /exte*/inclu*/query/CsvResultPrinter.php

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [SemanticMediaWiki/SemanticMediaWiki#647]
Please add
fputs( $csv, "\xEF\xBB\xBF");
to CsvResultPrinter.php. This way the encoding of the CSV-file would be UTF-8 and could be imported to Excel for instance. 
I can be added after line 74 in the aforementioned file. 

In case this should be be hardcoded, at least add in such a way as document it properly and make it possible that it an be enabled by commenting out a line or the like.

**Comment by mwjames** [comment]
Moving this to [0], volunteers or interested parties can pick up the task if it becomes an actionable item.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4

**Comment by kghbln** [comment]
The improvement will ship with SMW 3.0.0
