### ISSUE TITLE
[Feature request] New #ask parameter "alias" to show aliases instead of master synonyms

### ISSUE THREAD

**Issue by Protonotarios** [SemanticMediaWiki/SemanticMediaWiki#655]
I hope this issue in not a duplicate one because it's something that seems rather obvious.
I've done a quick search though but nothing found.

The idea that SMW treats MediaWiki redirects as aliases is brilliant. No doubt about it. But there are cases when we need to retrieve an alias value and not the master synonym.

I have a movie ontology where I have "Property:Has alternative title" to store titles in original language. For example, page "The Mirror" -> Has alternative title = "Зеркало", where page "Зеркало" is then made a redirect to page "The Mirror" because it's a synonym to it. It's not a different movie. And this is how it should be. But sometimes there is the need to retrieve the alternative titles values, such, make a table where in row 1 there are movie titles in English and in row 2 the original language titles. Right now this not possible. Some workarounds I've found in stackoverflow propose to set $smwgQEqualitySupport to SMW_EQ_NONE. Or to change the property type to text. But if you do these then you lose the whole functionality of synonyms. So this out of the question.

Therefore I propose the introduction of a new #ask/#show parameter named "alias" that, when used in a query, it will return aliases (values exactly as stored) and not their synonyms.

Example:

```
{{#ask: [[Category:Movies]]
| mainlabel = International English title
| ?Has altenative title = Original language title
}}
```

returns

| International English title | Original language title |
| --- | --- |
| The Mirror | The Mirror |
| Dogtooth | Dogtooth |

Example with proposed parameter "alias":

```
{{#ask: [[Category:Movies]]
| mainlabel = International English title
| ?Has altenative title = Original language title
| alias = Has altenative title
}}
```

will return

| International English title | Original language title |
| --- | --- |
| The Mirror | Зеркало |
| Dogtooth | Κυνόδοντας |

So the proposed syntax is to give "alias" a list of comma separeted properties of which (and only) you want to get the alias and not the synonym.

I think that the creation of this feature is imperative because otherwise what's the point of storing values semanticly if there is no way of retrieving them?

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
