### ISSUE TITLE
{{PAGENAME}} within {{#ask:}} breaks on special characters

### ISSUE THREAD

**Issue by timmyquivy** [SemanticMediaWiki/SemanticMediaWiki#675]
I utilize a templating system that relies heavily upon the {{PAGENAME}} magic word and URL {{#explode}} to avoid having to pass a lot of parameters.

http://www.thethirdturn.com/w/index.php?title=Template:ResultForm2&action=edit

This template works perfectly fine for any page name that does not contain a special character. Ex: http://www.thethirdturn.com/wiki/Kris_Walton/Results/V8_Ute_Racing_Series/2014

However, unless I override the {{PAGENAME}} default with a local parameter, I get a broken page result.

Compare: 

{{PAGENAME}} not overriden: 

http://www.thethirdturn.com/w/index.php?title=John_O%27Neal,_Jr./Results/NASCAR_Winston_West_Series/2002&oldid=645650 

{{PAGENAME}} is overriden:

http://www.thethirdturn.com/w/index.php?title=John_O%27Neal,_Jr./Results/NASCAR_Winston_West_Series/2002&oldid=645651

Something is going wrong in the URL encoding from PAGENAME -> the query engine that allows the page to show in that category but query parameters to return empty results. I have tried encoding the PAGENAME before to no effect.

**Comment by mwjames** [comment]
As noted tests are in place that allows use the cover scenarios with special characters, I cannot find a reproducible use case therefore closing this.

If for some reason, it is till an issue, please create a new ticked and follow [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/CONTRIBUTING.md#report-bugs
