### ISSUE TITLE
Can Not Query Properties With "." in Their Name

### ISSUE THREAD

**Issue by timmyquivy** [SemanticMediaWiki/SemanticMediaWiki#676]
I utilize a system that is heavily reliant upon pagenames to set property names. For instance, if in a racing event a driver named "John O'Neal, Jr." competes in the race, the property name will be saved as "John O'Neal, Jr. Finish::"

This system usually works fine, but I have always had some issues querying those properties with '.' set as the property name.

Take for instance this template: http://www.thethirdturn.com/w/index.php?title=Template:DriverHeader2/TrackView&action=edit

I am looking for all pages where "John O'Neal, Jr. Finish" property has a value.

http://www.thethirdturn.com/wiki/John_O%27Neal,_Jr./Results/Track_Overview - No results are provided

Compare to: http://www.thethirdturn.com/wiki/Harrison_Burton/Results/Track_Overview , where the exact same code works fine.

**Comment by mwjames** [comment]
> I would argue it is useful to escape the period in the future since human
names, cities, etc., often will feature periods in their titles. I do not
believe it is high priority,

"human names, cities" are values of a property. A property represents an attributive declaration about a "Thing" and/or a relationship expressed by the property to a value.

I'm thinking that we should not allow `.` as part of a property name and therefore it might be best to introduce a `smwgEnforceStrictPropertyNameConvention` which if enabled will disallow things like `.` in the name. If one still want to use `.` then there is no guarantee that queries (more precisely subqueries) will work as expected.

Property naming needs to adhere certain conventions (e.g `-` or `_` are already such conventions) therefore adding `.` to it would be more appropriate then to try introducing an escaping strategy for those edge cases.

Imported properties are by definition to use something like `Dc:` or `Foaf:` (dot notation is not supported).

**Comment by Contrafibularity** [comment]
Just updated the documentation concerning the naming of properties here: http://semantic-mediawiki.org/wiki/Help:In-text_annotation#Naming_of_properties

(Please add to the list if you know of anything else that users of SMW should bear in mind)
