### ISSUE TITLE
SQLStore Id mismatch

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#682]
The table diff sometimes compares a string Id with an integer Id which will lead to rather odd behaviour especially in connection with redirects.

Screen-dump was produced from `SMWSQLStore3Writers::preparePropertyTableUpdates`

![idmismatch](https://cloud.githubusercontent.com/assets/1245473/5427334/748cb3d8-83db-11e4-8529-f4e6320769e9.png)

With the `di_uri` table containing double entries for above mentioned id's

![doubleentry](https://cloud.githubusercontent.com/assets/1245473/5427358/448d2932-83dc-11e4-8ab1-28ef791c607a.png)

And for yet to determine a reason as to why (`422`/`130`/`localhost:8080/mw124/abc`) does no longer exists (compared with above) after an empty update (no annotation changes).

![deletedentry](https://cloud.githubusercontent.com/assets/1245473/5427386/f9ba6ae4-83dd-11e4-89ca-1e37b4327fc6.png)

__EDIT:__

I spend some time trying to figure out on what is going wrong and at least three issues were apparent:
- `preparePropertyTableInserts` produced float type sortkey which later is compared to a string sortkey in `arrayDeleteMatchingValues`
- ids (`s_id`, `p_id`) were mixed as either string or integer 
- `preparePropertyTableInserts` to build the `newarray` from `SemanticData` could contain double entries, this can happen when a page contains a value assignment to a redirected property and at the same a value assignment to the no-redirected property (as in above case `Has url` and `Has Url` point to the same id `130` but `Has url` redirects to `Has Url` which creates an issue during `arrayDeleteMatchingValues`)

**Comment by JeroenDeDauw** [comment]
Once this is fixed, I'm going to shout some more at @yaronkoren to update Referata :)

**Comment by mwjames** [comment]
It is expected that #1018 addresses the issue as outlined.
