### ISSUE TITLE
Help:Installation_(de) needs update

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#686]
https://semantic-mediawiki.org/wiki/Help:Installation_(de)

Last update was more than two years ago!

**Comment by mwjames** [comment]
@kghbln Closing this issue? I propose on deleting the wiki page completely if it contains outdated information!

**Comment by kghbln** [comment]
>  I propose on deleting the wiki page completely if it contains outdated information!

This is not necessary since it clearly references to a specific version. However, since I will not create a respective page for newer versions this can be closed.
