### ISSUE TITLE
Drop PHP 5.3 and 5.4 support

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#698]
I suggest we drop PHP 5.3 support in the next big release. This version is not getting security fixes anymore since August 2014, so supporting users in continuing to use it is bad.

There was some talk about dropping PHP 5.3 AND 5.4 support for MediaWiki itself (since WMF finally moved away from 5.3 with HHVM). If that happens, we can do that as well.

See also:

* [Why to not support 5.3 and 5.4](http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html)
* [MW version lifecycle](https://www.mediawiki.org/wiki/Version_lifecycle)
* [MW PHP compatibility](https://www.mediawiki.org/wiki/Compatibility#Software_required_to_run_MediaWiki)

**Comment by mwjames** [comment]
I hope we can agree on dropping support for MW 1.19-1.22 as well by the time PHP 5.3 is excluded.

**Comment by JeroenDeDauw** [comment]
Sounds good to me. Presumably by then they are all no longer supported (except maybe 1.19, but then again, there already is a new LTS (1.23) people can use)

**Comment by kghbln** [comment]
Continuing to support MW 1.23 would mean to continue supporting PHP 5.3 until May 2017. However, I would love to see support go for MW 1.19-1.22 too.

**Comment by JeroenDeDauw** [comment]
> Continuing to support MW 1.23 would mean to continue supporting PHP 5.3 until May 2017.

We can support MW 1.23 without supporting PHP 5.3. We've been in this situation before, since we dropped 5.2 support before MediaWiki did. (At least I think we did, not sure now...)

**Comment by JeroenDeDauw** [comment]
I wonder if dropping PHP and MW support should not be in the compat docs somewhere... We can have this tracked all nicely in our issue tracker here, but then basically none of our users are going to see the compat drop coming.

**Comment by JeroenDeDauw** [comment]
I've now added this info by inserting a 3.x row into the compat table: 74299937d7b13f841d4679ec3ee7a1d4ba0dcadf

**Comment by kghbln** [comment]
I believe that June 2015 is too early for SMW 3.x Debian 8 will ship with PHP 5.6 if I am not mistaken but will probably not be release before the third quarter 2015. After that we should probably allow another tree months to allows server admins their act together. So SWM 3.x will be a thing of the first quarter 2016?

**Comment by mwjames** [comment]
> I believe that June 2015 is too early for SMW 3.x. 
> So SWM 3.x will be a thing of the first quarter 2016?

I wonder about what would be the main features deployable with 3. x (taken away the discussion about changes of infrastructural components that require a major version change) that would be worthwhile to declare a 3.x.

**Comment by JeroenDeDauw** [comment]
Agree. PHP version considerations do not constrain when the next breaking release happens. It affects if we can drop support for a PHP version in such a release when it happens.

We have actually not agreed upon if changing PHP version requirements requires having a breaking release. Presumably the answer there is the same as for MediaWiki versions. And argument for limiting such changes to breaking releases is that if people "composer update" with a version such as "2.x", they can't suddenly end up with something that does not work on their system. And argument against from the user side, is that it causes more breaking releases, and makes it harder to distinguish between wiki userland breaking changes, and those just relevant platform compat wise. Another against, though from the dev side, is that we cannot drop support for PHP and MW versions as readily as we might.

**Comment by kghbln** [comment]
More related to versioning than to PHP: What about this [new MW 1.25 thing](https://www.mediawiki.org/wiki/Manual:Extension_registration)? This appears to be another breaking change what justifies a new major version I guess.

**Comment by mwjames** [comment]
> What about this new MW 1.25 thing? This appears to be 

It is a bunch of cherries which defies to idea of using Composer by trying to imitate it with some sort of `extension.json` file to load static classes or configurations. If someone one's to make the transition go ahead, I'm not wasting any time on this.

**Comment by JeroenDeDauw** [comment]
Oh FFS, they actually did this? Not a single reply to my concerns on the RFC.

**Comment by JeroenDeDauw** [comment]
PHPUnit is being more progressive than us https://github.com/sebastianbergmann/phpunit/issues/1595

**Comment by JeroenDeDauw** [comment]
Looking at Wikiapiary, it seems that people are generally slow to update SMW. And it seems that people who do upgrade in anything resembling a timely fashion, generally have PHP 5.5 or above. Not sure to what extend though. Having a 2D plot with SMW version numbers against PHP versions would be very helpful. Nudge @kghbln @thingles :)

This is an argument in favour of dropping obsolete PHP version support sooner rather than later, since the people who won't be able to upgrade any more are mostly those who would not in either case.

**Comment by JeroenDeDauw** [comment]
@SemanticMediaWiki/testers anyone got feedback on this topic? Would dropping PHP 5.3 or PHP 5.4 support be problematic for you or would it be fine? What about for other people/wikis you know?

**Comment by ckoerner** [comment]
My organization currently runs RedHat RHEL 6 which has PHP 5.3 (PHP 5.3.3 to be pedantic) as the standard, supported version of PHP. I recently went through a bunch of bureaucratic and technical hoops to update to 5.4. The bureaucratic hurdles were that the linux server admins didn't want to install an unsupported release of PHP on the server. Patching and updates make things difficult for them and they're not deploying RHEL 7 yet. This segued into the technical aspect of updating PHP on RedHat. We used their "Software Collections" distribution channel to update to 5.4 (http://developerblog.redhat.com/2013/08/01/php-5-4-on-rhel-6-using-rhscl/). It was a bit of a pain, but not unsurmountable. 

We did this because we wanted to start using Flow for our talk pages (which at the time of this writing requires PHP 5.3.6 - so close!)

Consider that some folks might not be able to use SMW (while they can still use MW as its minimum is 5.3.3) and folks on lower-tierd hosting would be left out.

That all said, I say do it. We should be encouraging good web citizenry by pushing requirements like updated frameworks and languages. When news breaks that sites running <application name here> are vulnerable to security issues it's always the application (SMW, MediaWiki, WordPress, Drupal, etc.) that get the bad rap, not the underlying layers.

**Comment by JeroenDeDauw** [comment]
> server admins didn't want to install an unsupported release of PHP on the server.

Could try pointing them to http://en.wikipedia.org/wiki/PHP#Release_history :) It's 5.3 that is unsupported. Kinda doubtful that the RHEL people are providing support for PHP comparable to the PHP dev team.

**Comment by formwandler** [comment]
I also work in an organization running a bigger MW + SMW installation on CentOS 6.x. PHP 5.3.3 is the default PHP version on this distribution. I know that there are newer CentOS versions available - and in deed it would be wise to update.

However, I would recommend to follow the MW roadmap. As soon as they phase out PHP 5.3.x, SMW should do as well.

**Comment by toniher** [comment]
Hi, in my research centre we are also using CentOS & Scientific Linux 6.x. But since PHP 5.3 is already deprecated, regardless of the distro, I'm actively asking to add repos supporting PHP 5.4. So, from my side, abandoning PHP 5.3 would not be a problem, since it's something already on my radar.

**Comment by kghbln** [comment]
This is just quick and dirty since I have to figure out how to get SWM version in: For SMW 1.5+ the distribution is as follows:
```text
5.6	 54	 3,85%
5.5	165	11,78%
5.4	569	40,61%
5.3	569	40,61%
5.2	 44	 3,14%
	1401

**Comment by JeroenDeDauw** [comment]
@ckoerner @formwandler @toniher You are all looking to upgrade from 5.3 to 5.4. I don't get that. This version is already only getting security fixes and will become unsupported in less than half a year. Why not go to 5.6, which gives you support till August 2017 and also has better performance?

**Comment by JeroenDeDauw** [comment]
@kghbln thanks a lot for compiling those stats!

**Comment by formwandler** [comment]
@JeroenDeDauw Sometimes the problem is that you must live with what is available, if you are not the admin of the underlying OS. So, if we would update to latest CentOS or even RHEL (which is more likely), I would probably need to live with the "default" PHP version shipped with these distros. It's not always possible to use additional repos to get newer PHP.
Latest CentOS or RHEL ship 5.4, see http://distrowatch.com/table.php?distribution=centos. I would recommend to at least support this PHP version.

BTW: My private MW + SMW installations are running on a "better" Linux distro with cutting edge PHP 5.6.x on top. I am a fan of updating always to latest PHP versions. But as I said, we have more restrictions in our companies, running quite old-fashioned distributions with old LAMP stacks unfortunately.

**Comment by ckoerner** [comment]
@JeroenDeDauw, to echo @formwandler it's not that I don't want to go to a newer version, I do. The conundrum comes into play what a more traditionally organized, uh organization that those who run the servers (setup, install, patching, etc.) are not the same as those who run the VM architecture (VMWare, updates, patching, new hardware, etc.) are not the same as those running the applications (Drupal, MediaWiki, internal .NET apps, etc.).

I pushed to get the RedHat Community package installed on my servers. I made basically the same argument you did. PHP 5.3 isn't supported! 5.4 is old. Their argument was that (in some bizarre way) that it is still supported by RedHat, who is the vendor we pay services to - not PHP. If something went wrong with PHP 5.3 (or via the community package) on the server we could contact RedHat for support.

Now, you and I know that in reality RedHat would probably just say, well update PHP. :) However, the linux admins folks are, like many in large organizations, strapped for resources in not entirely in control of making decisions like upgrading to newer version of PHP - especially when there might be apps that were written internally. We'd have to do a lot of work to test, test, test and then upgrade - for applications that might have been written 5 years ago by people who are no longer here. 

There's even more beuqacratic/political reasons I can't even imagine, I'm sure.

This is one of those cases where I say require a newer version of PHP to push the whole community forward. For those in large orgs like myself - well some folks might not be able to upgrade (or install a new instance of SMW/MW), but most will find a way. We should be cognizant of the uses of SMW as these folks are part of our community, but we shouldn't hold back on progress when there are alternative solutions.

**Comment by mwjames** [comment]
While semver doesn't require us to wait for a major release to make changes to the PHP version, I'd suggest (given above arguments) we make a real cut with SMW 3.0 in terms of the PHP/MW version.

Question:
- Which version of PHP should be the minimum requirement for SMW 3.0?
- Which version of MW should be the minimum requirement for SMW 3.0?

**Comment by kghbln** [comment]
> - Which version of PHP should be the minimum requirement for SMW 3.0?

PHP 5.4 due to Debian 7 LTS till May 2018

> - Which version of MW should be the minimum requirement for SMW 3.0?

MW 1.23 LTS till May 2017

**Comment by toniher** [comment]
Totally agree with Karsten!

**Comment by mitchelln** [comment]
Yes, I agree, the LTS versions should be supported.

**Comment by ckoerner** [comment]
I too agree with @kghbln's comments.

**Comment by formwandler** [comment]
And I tend to agree as well with @kghbln . This would also fit IMHO with actual CentOS / RHEL.

But why not just aligning with MW requirements? MW 1.23 and MW 1.24 work both with PHP 5.3. There would be a mismatch in required PHP versions, when someone runs MW 1.24 and SMW 3.0.

**Comment by kghbln** [comment]
> But why not just aligning with MW requirements?

SMW has not done so in the past, i.e. MW 1.19 LTS still allows to run with PHP 5.2 while SMW 1.9.x dropped support for PHP 5.2. I personally think SMW should put more emphasis on following the OS distribution reality in this respect.

**Comment by JeroenDeDauw** [comment]
I'm still for more alignment with actually supported PHP versions rather than those supported by MW or an OS. Seems to be a minority opinion though.

**Comment by formwandler** [comment]
@JeroenDeDauw Okay, fair enough. You have my vote ;-)

**Comment by kghbln** [comment]
Well, @mwjames and @JeroenDeDauw do the programming. So they have the final say. I believe this is fair.

**Comment by JeroenDeDauw** [comment]
@formwandler you do realize that @kghbln and me have a different opinion on this topic right? I'm in favour of dropping 5.4 as well for the 3.0 release, as by that time it will be an unsupported PHP version. And what the article I linked in the first post here outlines.

**Comment by mitchelln** [comment]
Ubuntu 12.04 LTS is going to be around into 2017. It has PHP 5.3.6. You risk hacking off an awful lot of Ubuntu users if you drop support for 5.3.6 before then.

**Comment by mwjames** [comment]
> Ubuntu 12.04 LTS is going to be around into 2017. It has PHP 5.3.6. You risk hacking off an awful lot of Ubuntu users if you drop support for 5.3.6 before then.

One thing is for sure SMW 3.0 will not support PHP 5.3 that's one of the narratives behind using a major release to signal the cut. For users with a need of PHP 5.3, SMW 2.* will be the choice.

**Comment by mitchelln** [comment]
Then you could probably apply the same argument for most distros. RH 7.1 is PHP 5.4 for example, so could stick with SMW 2.X.

Ubuntu 14.04 LTS ships with 5.5. Happy days. I would say only supporting PHP 5.6 would trip up a lot of people though.

**Comment by JeroenDeDauw** [comment]
> I would say only supporting PHP 5.6 would trip up a lot of people though.

Support PHP 5.6?! Why would we not just drop 5.x altogether and require PHP 7? Much more effective at making people mad I figure.

More seriously though, I do agree it's to soon to drop support for 5.5.

**Comment by formwandler** [comment]
@JeroenDeDauw Yes, sorry, I recognized the difference between your and Karsten's Opinion right after making the comment. I definitively vote for PHP 5.4 as minimum.

**Comment by jamesmontalvo3** [comment]
If my understanding is correct, what's being discussed is whether to make
PHP 5.4 or 5.5 the minimum version for SMW 3.0. I think the entire discusss
thus far has been about which other organization SMW should use as a
baseline (PHP, MW, RHEL Debian, etc). I don't think I've seen any
discussion about the technical benefit of 5.5 over 5.4. Can anyone
elaborate on that and how SMW would use the added capabilities?

**Comment by mwjames** [comment]
>  I don't think I've seen any
discussion about the technical benefit of 5.5 over 5.4.

After reading a bit about 5.5 [0] vs 5.4 and considering the upcoming PHP 7, I'm now in favour of 5.5 as minimum requirement to able to use generators (whether this happens or not is a different discussion but at least I want to be able to make this choice from a technical perspective).


[0] http://php.net/manual/en/migration55.new-features.php

**Comment by JeroenDeDauw** [comment]
The development version of PHPUnit already dropped support for PHP 5.x altogether. https://github.com/sebastianbergmann/phpunit/blob/master/.travis.yml#L4-L5

**Comment by kghbln** [comment]
New numbers from WikiApiary as follow-up to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/698#issuecomment-95521119
```text
5.6	 147	9,56%
5.5	 222	14,44%
5.4	 575	37,41%
5.3	 552	35,91%
5.2	  41	2,67%
	1537	

In case we are now talking about 3.0 at the end of Q1/2016 or the beginning of Q2/2016 I am likely to defect to the 5.6+ only support opinion.

**Comment by JeroenDeDauw** [comment]
5.6	  54	 3,85%
5.5	 165	11,78%
5.4	 569	40,61%
5.3	 569	40,61%
5.2	  44	 3,14%
	1401	

```text
5.6	 147	9,56%
5.5	 222	14,44%
5.4	 575	37,41%
5.3	 552	35,91%
5.2	  41	2,67%
	1537	
```

**Comment by JeroenDeDauw** [comment]
MW master just dropped 5.3 and 5.4 support.

**Comment by kghbln** [comment]
2015-04-23
```text
5.6	  54	 3,85%
5.5	 165	11,78%
5.4	 569	40,61%
5.3	 569	40,61%
5.2	  44	 3,14%
	1401	
```
2015-09-29
```text
5.6	 147	 9,56%
5.5	 222	14,44%
5.4	 575	37,41%
5.3	 552	35,91%
5.2	  41	 2,67%
	1537	
```
2016-02-02
```text
5.6	 233	14,67%
5.5	 271	17,07%
5.4	 545	34,31%
5.3	 501	31,55%
5.2	  38	 2,39%
	1588
```

**Comment by rglasnap** [comment]
Slightly related question: I'm looking at upgrading to MW 1.27 later this summer, so I need to upgrade to PHP 5.5.9+, any idea what version SMW is going to be sticking with? I'm not sure if I should just find something in 5.5, or jump straight up to 5.6.

**Comment by kghbln** [comment]
> any idea what version SMW is going to be sticking with?

[COMPATIBILITY](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md) is your friend. This every version since SMW 1.9.0 will work, however use SWM 2.3+.

**Comment by mwjames** [comment]
>  I'm not sure if I should just find something in 5.5, or jump straight up to 5.6.

5.5 is for the conservatives and gets security support until 10 Jul 2016 [0] while 5.6 continues to receive security support until 31 Dec 2018.

> any idea what version SMW is going to be sticking with

SMW 2.4 will be the last release to support 5.3, the next version will require 5.5+ [1]. 

[0] http://php.net/supported-versions.php
[1] https://twitter.com/JeroenDeDauw/status/718782521555685376

**Comment by mwjames** [comment]
This has happened now with 2.5.0-alpha.

**Comment by kghbln** [comment]
2018-02-08

```text
PHP 7.3: (future)    |    0 |   0,00%
PHP 7.2: (supported) |   50 |   2,84%
PHP 7.1: (supported) |   37 |   2,10%
PHP 7.0: (legacy)    |  256 |  14,55%
PHP 5.6: (legacy)    |  566 |  32,18%
PHP 5.5: (obsolete)  |  240 |  13,64%
PHP 5.4: (obsolete)  |  271 |  15,41%
PHP 5.3: (obsolete)  |  307 |  17,45%
PHP 5.2: (obsolete)  |   32 |   1,82%
                     | 1759 | 100,00%

PHP (supported)      |   87 |   4,95%
PHP (legacy)         |  822 |  46,73%
                     |  909 |  51,68%
```
@JeroenDeDauw @mwjames Only 5% of wikis are using supported versions of PHP. This is a disaster for PHP. They are completely out of sync with major distros.
