### ISSUE TITLE
Sorting of the SMW category format is different from the sorting of the MediaWiki category system

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#699]
Is there any reason why the sorting of the category format to be different compared to the MediaWiki category system? See:

Sorting in MediaWiki category system: A, B, C... Z.
http://wikincat.org/wiki/Categoria:Manifestation

Sorting in SMW category format: A, B, C... Z, a, b, c... z.
http://wikincat.org/w/index.php?title=Special:Ask&offset=0&limit=500&q=%5B%5BCategory%3AManifestation%5D%5D&p=format%3Dcategory%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D%E2%80%A6-20mais-20resultados%2Fcolumns%3D3&eq=yes#

Config:
MediaWiki: 1.24.1
Semantic MediaWiki: 2.1alpha

**Comment by mwjames** [comment]
If I interpret it correctly, you are asking why some are listed as a,b,c and not as A,B,C because the category printer uses the `sortkey` as a means to filter the first character and for the example [0], you can see that the `Default sort key:ciência da informação` starts with `c` not with `C` therefore it will be listed as `c`.

[0] http://wikincat.org/w/index.php?title=A_ci%C3%AAncia_da_informa%C3%A7%C3%A3o_%282004%29&action=info

**Comment by jaideraf** [comment]
@mwjames Yes, you are correct.
But even with a "annotated" sortkey ( `DEFAULTSORT` ) with a lowercase first letter, MediaWiki (wisely, IMHO) sorts "a" and "A" together in the category page.

http://wikincat.org/w/index.php?title=A_ciência_da_informação_(2004)&action=info
("ciência da informação" goes to "C", not "c".)

**Comment by mwjames** [comment]
@kghbln How do we want proceed here? [0] doesn't make any formatting of lower to upper case. Is the sortkey output (not storage) always converted to a capital letter?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/CategoryResultPrinter.php#L77

**Comment by kghbln** [comment]
Since March 8, 2011, at least for German Wikipedia, probably in general, MW always converts the value of the standard sortkey for categories always to upper case complying with the [Unicode collation algorithm](https://en.wikipedia.org/wiki/Unicode_collation_algorithm) This however was supposed to be "just" a configuration change. So SMW should probably comply with this configuration setting, too.

**Comment by kghbln** [comment]
That's the setting: [`$wgCategoryCollation`](https://www.mediawiki.org/wiki/Manual:$wgCategoryCollation) handled via the ["Collation.php"](https://git.wikimedia.org/blob/mediawiki%2Fcore.git/47debce98b09a55f9b1b0c798ce78d1b7c54235b/includes%2FCollation.php) file.

**Comment by jaideraf** [comment]
I quickly tested the SMW 2.2 RC and, sadly to me, I noted that the Category Result Format is still incompatible with the core MediaWiki category system. Look at the two following pages: 

MediaWiki category page:
http://wikincat.org/wiki/Category:Manifestation
SMW category result format for the category above:
http://wikincat.org/wiki/Wikincat:Book_list

Look at the T letter, for example.
Now, SWM ignores the DEFAULTSORT parser function. 
So I have to remember the title of this bug "Sorting of the SMW category format is different from the sorting of the MediaWiki category system".

Sorry, I didn't notice this before. Well, I guess the RC is for discovering that kind of thing...

**Comment by mwjames** [comment]
>  I noted that the Category Result Format is still incompatible with the core MediaWiki category system.

@jaideraf @kghbln Fixed in master/2.3.x with  871d9ce and in 2.2.x with c172deb. Use cases in `format-03-01-category-en.json` have been amended.

**Comment by jaideraf** [comment]
@mwjames Wow, that was fast!
Bad news: the sorting is still different, compare the S, for example:

S order (in MediaWiki) | S order (in SMW)

sa | se 
se | so 
se | sa 
se | se
so | se
so | so 
so | so

(I run rebuildData.php after upgrade)

**Comment by mwjames** [comment]
> Bad news: the sorting is still different, compare the S, for example:

I'm not able to confirm this and unless you tell me how I can reproduce this it will be difficult to solve.

![s-order](https://cloud.githubusercontent.com/assets/1245473/7540276/0f8ca068-f5e8-11e4-89d7-bfb6b9553cd0.png)

**Comment by jaideraf** [comment]
@mwjames It seems that all pages that have DEFAULTSORT is going after the pages that don't. 
My use case is that all page names that starts with "The ", "A ", "An", "Der ", "Das ", "Dir ", "Il ", "La ", etc. has to be sorted with the "true" word after those particles.
Try to use DEFAULTSORT in some of your pages, then compare them in the category from MediaWiki and de category format from SMW.

**Comment by mwjames** [comment]
> It seems that all pages that have DEFAULTSORT is going after the pages that don't. 

Yes, because SMW takes full acount of the DEFAULTSORT while MW's cat does not.

It means (same example as above) if I have Sbaa with `{{DEFAULTSORT:Saaa}}` and Seoa with `{{DEFAULTSORT:Saaa}}` then the sorting will be ;

```
Seoa
Saaa
Sbaa
Scba
Seba
Soaa
```

while the MW's category will still say 

```
Saaa
Sbaa
Seoa
Scba
Seba
Soaa
```

**Comment by mwjames** [comment]
> My use case is that all page names that starts with "The ", "A ", "An", "Der ", "Das ", "Dir ", "Il ", "La ", etc. has to be sorted with the "true" word after those particles.

Not sure what this means but sorting is done in SQL and there is no (natural) sorting based on linguistic  concepts.

**Comment by jaideraf** [comment]
>Yes, because SMW takes full acount of the DEFAULTSORT while MW's cat does not.

I didn't understand that. Maybe I am wrong, but DEFAULTSORT parser function was created by MW exactly to be used on sorting of category pages.

>Not sure what this means but sorting is done in SQL and there is no (natural) sorting based on linguistic concepts.

I'm not asking for some different behaviror. The behavior of MW category is fine to me. The behavior of SMW is not.

>while the MW's category will still say
Saaa
Sbaa
Seoa
Scba
Seba
Soaa

I don't think MW will sort like that. MW sorts like:

Saaa
Sbaa
Scba
Seba
Seoa
Soaa

So, the issue remains: Sorting of the SMW category format is different from the sorting of the MediaWiki category. Same category, same results: different order (when using DEFAULTSORT).

**Comment by mwjames** [comment]
> So, the issue remains: Sorting of the SMW category format is different from the sorting of the MediaWiki category. Same category, same results: different order (when using DEFAULTSORT).

The part in the picture with "カテゴリ「Cat-s-order」にあるページ" is MW's sorting, so yes it does sort as:

```
Saaa
Sbaa
Seoa
Scba
Seba
Soaa
```

**Comment by mwjames** [comment]
> I'm not asking for some different behaviror. The behavior of MW category is fine to me. The behavior of SMW is not.

The implementation (especially for DEFAULTSORT) follows a different rule set [0] and since this hasn't been a regression, I'm not going to spent time on MW's sorting mechanism.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_SQLStore3.php#L528-L628

**Comment by jaideraf** [comment]
Ok.

But, second letter.
I don't see 

a
b
e
...

I see

a
b
c
...
In your image.

**Comment by mwjames** [comment]
After emending the DEFAULTSORT for Sbaa and Seoa.

![sd-order](https://cloud.githubusercontent.com/assets/1245473/7541546/34430c68-f5f1-11e4-9439-8c25d0218af8.png)

**Comment by jaideraf** [comment]
Oh, alright.
So that is a MW issue.
Thanks for making SMW a great software.
You made a big progress on it.

**Comment by mwjames** [comment]
@kghbln Do you want to make a note about the obvious differences in sorting when `DEFAULTSORT` is involved? (PS: see the screen dumps)

**Comment by kghbln** [comment]
Yeah, there should be a note.

**Comment by mwjames** [comment]
To avoid any future incongruity over the topic (DEFAULTSORT), I added `format-03-02-category-defaultsort-en.json` in f9d298e that codifies the discussed example.

**Comment by kghbln** [comment]
Just to sum up: In SMW defaultsort takes precedence before a page title with the same chars, and that's why Sbaa is shown before Saaa because page Sbaa contains the Saaa-defaultsort and page Saaa does not. So MW treats Sbaa like Saaa due to the defaultsort and sorts both. I am not sure but intuitively I would expect the MW behaviour. However then adding a defaultsort to every page then SMW and MW should sort in the same manner I suppose.

**Comment by kghbln** [comment]
> However then adding a defaultsort to every page then SMW and MW should sort in the same manner I suppose.

Affirmative, just verified this with a field test. Works allrighty.
