### ISSUE TITLE
Remove MWException 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#705]
MW-core is killing the `MWException` [0]. [1] shows the current usage.

[0] https://gerrit.wikimedia.org/r/#/c/184004/2
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=mwexception

**Comment by mwjames** [comment]
@JeroenDeDauw If you come along a `MWException` just kill them in the process.

**Comment by JeroenDeDauw** [comment]
Dear `MWException`:

![die-in-a-fire](https://cloud.githubusercontent.com/assets/146040/5836260/6daadf58-a173-11e4-9e84-2c9542ba4180.gif)
