### ISSUE TITLE
SMW 1.8*/1.9* or SB 1.9* should not be used with MW 1.23+ 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#706]
I just confirmed (antwiki.org) that using MW 1.24+ with any release lower than 2.* can (or will which  depends on whether template/RefreshLinksJobs are executed) cause trouble for the property/value storage due to changes in MW 1.23/1.24+ internal code that directly affects the storage (using of hooks etc.) of annotations and is fixed with SMW 2.*.

Instances that run such combination should be made aware (via wikiapiary list) while keeping track and inform users about the potential issue in connection with MW 1.23/1.24+.

MW 1.23 - #347
MW 1.24 - #420

## Issue and fixes
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=label%3Amediawiki+is%3Aclosed+is%3Apr
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=is%3Aclosed+is%3Aissue+label%3Amediawiki

@kghbln If those discussion appear on the forum or mailing list then the only advice is to do an upgrade.

**Comment by JeroenDeDauw** [comment]
I have updated the compat docs c1370feb8f2a2446711d6a022bcd6a46d05e4ad3#diff-556d295d45279bede662524bf7fdb0b4

We unfortunately do not have a way to distinguish between "not known if supported" and "known to not be supported" in the table. If anyone has an idea of how to do that nicely...

**Comment by JeroenDeDauw** [comment]
What more needs to be done to close this item?

**Comment by mwjames** [comment]
> What more needs to be done to close this item?

Not much, this is a tracking issue so that in case some people observe some rather odd behaviour then we politely ask to update to a version that is compatible.

@kghbln Maybe a more visble indication on the smw.org@installation docu to ensure that a user doesn't fall into the "this sh.t software isn't working" stratagem.

**Comment by kghbln** [comment]
Yeah, this incompatibility is a know fact for quite some time. I have added more visible information on the wiki [1.8](https://semantic-mediawiki.org/w/index.php?title=Help:Installation_1.8.0&curid=3155&diff=36425&oldid=33763), [1.9](https://semantic-mediawiki.org/w/index.php?title=Help%3AInstallation_1.9.0_-_1.9.2&diff=36428&oldid=34346), [2.x](https://semantic-mediawiki.org/w/index.php?title=Help%3AInstallation&diff=36427&oldid=36424).
