### ISSUE TITLE
Repairing SMW's data via script creates some problems

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [SemanticMediaWiki/SemanticMediaWiki#712]
I used these two commands in order to repair the SMW data:
```
php rebuildData.php -ftpv
php rebuildData.php -v
```
The effect had been that the German "Hat Standardformular" does not work anymore. Only after a changing it to "has default form" the form can be accessed via the head tab again. Before that it has simply vanished. 

Furthermore, also some properties do not show all entries in which they have been used. Could this be attributed to the fact that these have been set via the entry in the LocalSettings:
```
$smwgLinksInValues = true;
```

**Comment by mwjames** [comment]
> php rebuildData.php -ftpv
php rebuildData.php -v

There are not enough information to make general suggestions about your case (e.g. MW, SMW version used).

> The effect had been that the German "Hat Standardformular" does not work anymore. Only after a changing it to "has default form" the form can be accessed via the head tab again. Before that it has simply vanished.

@kghbln Any input on the German/SF issue? (I do not use either SF or German)

> Furthermore, also some properties do not show all entries in which they have been used. Could this be attributed to the fact that these have been set via the entry in the LocalSettings:
$smwgLinksInValues = true;

Do you have specific examples that can be used to verify your observations?

**Comment by kghbln** [comment]
The I18n for this special property is unchanged since about two years, both for de and de-formal. So this should work. If we are talking about SF 3.0 or 3.1 it may be a problem related to the changes made to make SF compatible with Cargo. If I remember correctly most of these changes were related to special properties. I am not sure though if this is the reason. Perhaps @yaronkoren can have a peep at this.

**Comment by yaronkoren** [comment]
Hi - I don't know if SF or SMW is the cause for your first problem, but in any case, I should note that, as of SF 3.0, the whole "default form" special property is slightly deprecated. Instead, you should use the new #default_form parser function - see here:

https://www.mediawiki.org/wiki/Extension:Semantic_Forms/The_"edit_with_form"_tab

**Comment by DestructionOfPlanetJupiter** [comment]
Thanks ... I have changed the entries according to the entry at the MediaWiki site. Skipped my mind. Thanks for the quick replies.
