### ISSUE TITLE
PSR-0 compliance

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#716]
Several of SMWs classes have been moved into namespaces, generally following the PSR-0 standard. All code is still loaded via classmap though, and it's not easy to see which parts of the codebase adhere to PSR-0 and which ones do not. Regressions to PSR-0 compliance are also hard to detect. 

Proposal: create a `src` top level directory, which gets loaded via PSR-0. All compliant code goes there, while the non-compliant code remains in `includes` until it is compliant.

Potential downside: we'll have a somewhat arbitrary split of code between the two folders. Then again, looking at two places is not the end of the world. And active contributors will likely know where the code is anyway, while people using IDEs might not even notice. Furthermore, it appears there already is a `src` folder in `includes`, presumably meant for similar purpose, yet not enforcing PSR-0 loading. We can simply move this directory up a level.

**Comment by JeroenDeDauw** [comment]
@mwjames

**Comment by mwjames** [comment]
> PSR-0 standard. All code is still loaded via classmap though, and it's not easy to see which parts of the codebase adhere to PSR-0 and which ones do not. Regressions to PSR-0 compliance are also hard to detect.

Just pulling some hair here but PSR-0 [0] "As of 2014-10-21 PSR-0 has been marked as deprecated. PSR-4 is now recommended as an alternative".

> Proposal: create a src top level directory, which gets loaded via PSR-0. All compliant code goes there, while the non-compliant code remains in includes until it is compliant.

Folders in [1] follow PSR-4, we just have to move the folder one level up.

[0] http://www.php-fig.org/psr/psr-0/

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/includes/src

**Comment by JeroenDeDauw** [comment]
> PSR-0 has been marked as deprecated. PSR-4 is now recommended as an alternative

Yeah well, pretty much the same thing for us.

> Folders in [1] follow PSR-4, we just have to move the folder one level up.

Shall I submit a PR for this?

**Comment by mwjames** [comment]
> Shall I submit a PR for this?

As this goes now into 2.2, just go ahead (I never came to the point to make the move).

**Comment by JeroenDeDauw** [comment]
I'll first rebase and merge #494. Else that'll become to much tangle for m git skills to cope with :)

**Comment by JeroenDeDauw** [comment]
Continuing to track in #725
