### ISSUE TITLE
Sesame in COMPATIBILITY.md

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#723]
Currently 2.x is listed as fully supporting Sesame. While this might be true for 2.1, is it also true for 2.0?

**Comment by mwjames** [comment]
> Currently 2.x is listed as fully supporting Sesame. While this might be true for 2.1, is it also true for 2.0?

Right, #703 were added in 2.1 (and #707 to run Travis).

**Comment by JeroenDeDauw** [comment]
Ok, updated the docs
