### ISSUE TITLE
CacheableResultCollector::findPropertyTableByType uses undefined field

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#732]
It accessed a $store field, which is not defined in the class itself. It implicitly relies on the deriving classes to define one.

**Comment by mwjames** [comment]
> It accessed a $store field, which is not defined in the class itself. It implicitly relies on the deriving classes to define one.

I know it is a rather unfortunate design and I'd like to get rid of it sooner rather than later.

**Comment by mwjames** [comment]
> I know it is a rather unfortunate design and I'd like to get rid of it sooner rather than later.

#831 will start to remove dependency on `CacheableResultCollector` and in its final process will remove this class.

**Comment by mwjames** [comment]
RIP
