### ISSUE TITLE
SerializerFactory is not a factory

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#738]
Both methods (static) do not create a serializer. Hence this is not a serializer factory, so the name is misleading.

~~`SerializerFactory::deserialize` appears to be not used in production code~~

**Comment by mwjames** [comment]
Use by UpdateDispatcherJob.php

```
	protected function addUpdateJobsFromSerializedData() {
		if ( $this->hasParameter( 'semanticData' ) ) {
			$this->addUpdateJobsForProperties(
				ApplicationFactory::getInstance()->newSerializerFactory()->deserialize( $this->getParameter( 'semanticData' ) )->getProperties()
			);
		}
	}
``
```
SemanticDataDeserializer implements Deserializer
```
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/serializer/Deserializers/SemanticDataDeserializer.php

**Comment by JeroenDeDauw** [comment]
> ApplicationFactory::getInstance()->newSerializerFactory()->deserialize

Ah, my IDE did not find this due to fail type hints in ApplicationFactory. Which funnily enough I had fixed before in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/736
