### ISSUE TITLE
Usage of the Serialization component

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#740]
We have copies of old versions of the Serializer and Deserializer interfaces from the [Serialization component](https://github.com/wmde/Serialization). If we use the component instead, we gain interoperability with other things that use it, such as the new [Ask serialization component](https://github.com/wmde/AskSerialization/).

Any objections against, or concerns with, switching to these interfaces?

**Comment by mwjames** [comment]
No. The reason that both interfaces use the same signature was to eventually switch.
