### ISSUE TITLE
SQLStore / Interface changes to the QueryEngine

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#743]
Follow-up on #494
 
Any query builder, resolver related class or object should be placed in the `SMW\SQLStore\QueryEngine` namespace.

- `QueryBuilder` should to be renamed to `CompoundQueryBuilder` (aka `SMW\SQLStore\QueryEngine\CompoundQueryBuilder`) as the responsibility lays with building a query compound by the means of employing different `QueryContainerBuilder`'s responding to an individual `Description` type
- `QueryCompiler` interface should be renamed to `QueryContainerBuilder` interface representing the contract interface, implementing classes ought to return a `QueryContainer` instance
-  Classes that implement the `QueryContainerBuilder` should be renamed accordingly (e.g. `SMW\SQLStore\QueryEngine\ContainerBuilder\NamespaceContainerBuilder`)
- Registration of  the `QueryContainerBuilder` should be moved from `CompoundQueryBuilder` to a dedicated `QueryContainerBuilderStrategyFinder` (similar to [0], `QueryContainerBuilder` instances should be registered static otherwise it will drain performance, see [0] can be seen using Xdebug) or you have to move the whole registration to the setup and inject the object through an instance chain (which is currently not really possible due to the murky `SQLStore` interface)

OR

should it be 
- `SMW\SQLStore\QueryEngine\CompoundQueryBuilder` invoking individual 
- `QueryBuilder`'s (e.g `SMW\SQLStore\QueryEngine\QueryBuilder\NamespaceQueryBuilder`) found by the 
- `SMW\SQLStore\QueryEngine\QueryBuilderStrategyFinder` to return a 
- `QueryContainer`?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SPARQLStore/QueryEngine/ConditionBuilderStrategyFinder.php

**Comment by JeroenDeDauw** [comment]
> QueryBuilder should to be renamed to CompoundQueryBuilder aka SMW\SQLStore\QueryEngine\CompoundQueryBuilder) as the responsibility lays with building a query compound by the means of employing different QueryContainerBuilder's responding to an individual Description type.

I'm not sure about that. From the outside what this service does is create what is currently called `QueryContsainer`. That this QueryContsainer might be a compound is not very relevant, and that internally the class delegates to strategies is an implementation detail.

The class currently called `QueryBuilder` already looks pretty sane, and not far from what I'd expect to interact with from the outside. Having a factory that creates this class, and puts in the (current name) query compilers would be nice. That makes the delegation logic easier to test, and makes a cleaner boundary by moving out construction/config, which is a step towards allowing extensions to register their own description types and query compilers.

At present, `QueryBuilder` does contain a bunch of state as well. It'd be nice to separate those two.

**Comment by JeroenDeDauw** [comment]
Oh, I did not realize [ConditionBuilderStrategyFinder](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SPARQLStore/QueryEngine/ConditionBuilderStrategyFinder.php) was already created.

**Comment by mwjames** [comment]
> Are the @since 2.1 tags in this class incorrect?

Why? This class was introduced with 2.1 along with the other classes to actually match a `Description` to a `ConditionBuilder`.

**Comment by JeroenDeDauw** [comment]
Ah - I thought this was part of the SQLStore stuff which got merged just after we branched 2.1.x. Did not realize it's SPARQLStore.

**Comment by JeroenDeDauw** [comment]
@mwjames so what to do with `QueryCompiler` now? Do you want it renamed to `SqlQueryPartBuilder` and end up with things such as `ValueDescriptionSqlQueryPartBuilder`?

**Comment by JeroenDeDauw** [comment]
Actually, I think it'd be helpful to close this and create new items about the things that should still be acted on, with current descriptions.

**Comment by mwjames** [comment]
#981, #984
