### ISSUE TITLE
SQLStore / QueryEngine move `getCreateTempIDTableSQL` to a safe place

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#745]
refs #743

[0] `getCreateTempIDTableSQL` code needs to go to a safe place.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_SQLStore3_Queries.php#L887

**Comment by JeroenDeDauw** [comment]
From DBALs TemporaryTableTest.php:

```
$createTempTableSQL = $platform->getCreateTemporaryTableSnippetSQL() . ' ' . $tempTable . ' ('
                . $platform->getColumnDeclarationListSQL($columnDefinitions) . ')';
```

Which means we can feed in a db type agnostic column definition. Any objections against start the use of DBAL?

**Comment by mwjames** [comment]
> Any objections against start the use of DBAL?

Not that I can think of.

Just needs a new `DBALConnectionProvider` registered as `dbal` with the `ConnectionManager` and we have access to it via `->getConnection( 'dbal' )` without jeopardizing the rest of the code and can slowly move forward.

**Comment by JeroenDeDauw** [comment]
I can't check the code now, though suspect you'll end up with an interface mismatch if you do that.

**Comment by mwjames** [comment]
> Also not sure why you'd try to unify

I'd like to see a wrapper around `DBAL` as we did with MW's DB handler so that we can talked to a DB interface instead of a specific implementation. I don't want to make the same mistake and depend on something that might change in future and if a change is necessary then the wrapper should take are of it.

For example, instead of referring to the DBAL cache client directly we will use `Onoi/Cache` that deploys an interface (well it matches that of DBAL and the MW cache is morphed accordingly) which might return something from `DBAL` or `BagOStuff` but which doesn't really matter as long as the interface stays the same.

I'd like to see `getConnection( 'mw.db' )` and `getConnection( 'dbal' )` to return the same interface (`getConnection( DB_MASTER )` is an exception as long as some MW `wfGetDB` calls lurk around).

**Comment by JeroenDeDauw** [comment]
Ok, we have some disagreement on this then.

The DBAL interfaces are not database type specific. That is something we need. They are also not likely to cause problematic BC breaks for us.

Now you are right, if we use it, it'd be DBAL specific. We can avoid this by using our own interface or one from another package, though then our code becomes specific to that. So I don't see this really improving anything, especially considering the maturity and community of DBAL.

The main value I see us getting out of using our own interface is that we can have adapters for both DBAL and MW. This is essentially what [Wikibase Database](https://github.com/wmde/WikibaseDatabase) is about. I do however not think this is worth the cost. So what if we can only stuff a DBAL connection into our new code? How will that end up being a problem?

**Comment by mwjames** [comment]
> So I don't see this really improving anything, especially considering the maturity and community of DBAL.

I don't doubt that (and given the fact that WMF/MW tries to ditch postgres in future no real argument on this side of the ocean) but I recall there is/was a lack of a clear master/slave/loadbalancer implementation. Currently we don't really care about it but would have to do afterwards.

> The DBAL interfaces are not database type specific. That is something we need. They are also not likely to cause problematic BC breaks for us.

I just don't want to being too tightly coupled to either MW or DBAL but I can't really argue here since I'm not familiar with DBAL so I go with your judgement in consideration of the points I raised.

**Comment by JeroenDeDauw** [comment]
Consider how widely DBAL is used, for instance by Symony. And Symfony definitely does not try to put its own thing in between. The most popular PHP DBAL compared to the MW (which is not even reusable) one - very very big difference :)

**Comment by JeroenDeDauw** [comment]
Starting with #768

**Comment by JeroenDeDauw** [comment]
Next up: #769

**Comment by JeroenDeDauw** [comment]
And now #771

**Comment by JeroenDeDauw** [comment]
Ah, forgot to close this
