### ISSUE TITLE
Ghost properties

### ISSUE THREAD

**Issue by aquatiki** [SemanticMediaWiki/SemanticMediaWiki#748]
I believe this error happened because I created a property, populated it, and then renamed it.  Now there is a "ghost" property, as can be seen on the Special:Properties page (link below).  That is, there are two identically named properties, only one of which can be accessed.  I tried editing this troubled properties and made a third, identical property!  When queries are made against this property, it is visible by category but not by page-specific "ask" (second and third example below).  I have cleared the cache, refreshed the pages, updated the tables, and repaired/upgraded data, all to no avail.
I don't know if it is related, but attempting to turn off the FACTBOX produce weird error.  The FACTBOX's disappear from pages only when this property is altered.

* http://danayo.referata.com/wiki/Special:Properties
* http://danayo.referata.com/w/index.php?title=Special%3AAsk&q=%5B%5B%E4%B8%AD%E5%8F%A4%E6%BC%A2%E8%AA%9E%E5%AD%97%E6%AF%8D%3A%3As%5D%5D&po=%3F%E4%B8%AD%E5%8F%A4%E6%BC%A2%E8%AA%9E%E9%9F%BB%E6%AF%8D%0D%0A%3F%E9%9F%93%E6%96%87%E2%80%8E%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&eq=yes
* http://danayo.referata.com/wiki/%E5%85%88%E7%94%9F

**Comment by mwjames** [comment]
> http://danayo.referata.com/wiki/Special:Properties

Sorry, but `referata.com` uses an outdated and not maintained SMW (1.8) therefore closing the issues under the assumption that it doesn't happen with SMW 2+. Please feel free to re-open this issue for a supported SMW release.

**Comment by JeroenDeDauw** [comment]
@aquatiki thanks for reporting this though!
