### ISSUE TITLE
rebuildData to add --no-cache option (CACHE_NONE)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#749]
Follow-up on [0] to add a `--no-cache` option for the `rebuildData` maintenance script to avoid a potential issue as reported by [0].

[0] https://semantic-mediawiki.org/wiki/Thread:Help_talk:Repairing_SMW%27s_data/rebuildData.php_freezes_at_certain_page_IDs/reply_(2)

**Comment by jongfeli** [comment]
Depending on what kind of object caching is used php in CLI will not work
or not work reliable. We used to run our wiki with Xcache and object cache
enabled but Xcache does not support CLI. This means any maintenance script
that run from the command line will not work. We had to configure a switch
in LocalSettings.php to detect if PHP is running in CLI mode to disable
Xcache, that woked fine. I am not sure what it looked like, we are running
our wiki on PHPs zend opcache now, it does not have object caching.

It seems that this issue affects Semantic Mediawiki maintenance script but
it is not a Sematic MediaWiki problem as such.

**Comment by mwjames** [comment]
Well, the only way I could think of (as I can't replicate the issue) is to set `$GLOBALS['wgMainCacheType'] = CACHE_NONE;` for the time the script is run whether this is sufficient or not I do not know.

**Comment by jongfeli** [comment]
That works, it is the default "setting" when you installl MediaWiki but in my opinion it is not a wise thing to override the caching setup via SMW. There is a lot of caching software out there and maybe someone is using something with a special configuration that does work in CLI. You use caching to speed up your wiki but when SMW then overrides the caching setup people wonder why there wiki is running there daily maintenance script so slow all of a sudden. I could start a page on the SMW site on how to make caching work in combination with PHP in CLI mode.

**Comment by mwjames** [comment]
> You use caching to speed up your wiki but when SMW then overrides the caching setup people wonder why there wiki is 

The setting would be only active for when `--no-cache` is used as option and only for the time the script is run.

**Comment by mwjames** [comment]
> I could start a page on the SMW site on how to make caching work in combination with PHP in CLI mode.

Extending the documentation is always appreciated.

**Comment by jongfeli** [comment]
Used as an option you should be ok but it only applies to the SMW
maintenance scripts. Any MW maintenance scripts used will "not" work.

**Comment by mwjames** [comment]
Implemented with #770
