### ISSUE TITLE
Clean up QueryContainer

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#754]
`QueryContainer` is (the name new name of) a class used to represent parts of an intermediate state created during the process of turning an Ask Description into SQLStore SQL.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/QueryContainer.php

On the subject of this class, and it's usage in SMWSQLStore3QueryEngine:

> One issue in the translation is that it is not feasible to build an SQL query string recursively from the ASK query. The reason is that SQL query strings have multiple places (FROM part, WHERE part, LIMIT, ORDER BY) where you will want to add text during the recursion. So one needs another intermediate representation for the SQL. SMW has a rather ad hoc approach of doing this (decomposing SQL merely into its several main fields).

> Maybe with a careful choice of intermediate representation, the SQL translation could be more readable. SMW builds (partial) query strings during the recursion, so that you have string constructions mixed up with ASK interpretation, which is somewhat messy (it also mixes concerns like correct bracketing of WHERE conditions, string escaping, and the selection of the correct SQL feature to use in the first place).

> One could also use a less syntactic object representation of SQL queries instead, and maybe there is some library for this. Memory usage might not be such a big issue if we can assume that queries are relatively small and few per page (not always true maybe). However, a full-blown object model for SQL queries would be more complex as ASK to start with.

This is an exert from a private email, though I assume Markus has no problems with me posting this here.

**Comment by JeroenDeDauw** [comment]
I'm quite dubious about the name `QueryContainer`. @mkroetzsch suggestions for a better name?

**Comment by mkroetzsch** [comment]
Well, if it is specific to SQL, it should probably have SQL in its name. Also, I would avoid "Container" which sounds to me like "Collection" (of several queries). Suggesting a name requires to know the code. Is it maybe an SqlQueryBuilder you have there?

**Comment by JeroenDeDauw** [comment]
How about `SqlQueryPart`? (it does not do building, and "Builder" suggests Builder Pattern)

**Comment by JeroenDeDauw** [comment]
Rename done in #767
