### ISSUE TITLE
#ask no results + empty searchlabel forces a raw wikitext output

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#755]
> I have upgraded from SMW 2.0 to SMW 2.1 but now encounter some issues. 
> In particular, the behaviour of some #ask queries has changed -- I don't 
> recall this from the release notes.
> 
> The normal way to disable the further-results link was to set
> 
> searchlabel=
> 
> as a parameter in ask. This still works with queries that have results, 
> but there are issues with limit=0:
> 
> {{#ask: some query that has results
> | limit = 0
> | default = no results
> | searchlabel=
> }}
> 
> This displays on the page as
> 
> [[Special:Ask/ ... query .../searchlabel=/default=no results/offset=0|]]
> 
> printed verbatim like this.
> 
> The problem only seems to occur with limit=0. If there are results, then 
> the further-results link is hidden as expected.

-- @mkroetzsch

**Comment by mwjames** [comment]
Off  the top of my head the only thing that changed in regards to the #ask was made in [0] to filter '=' within an enclosed annotation.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/query/SMW_QueryProcessor.php#L288

**Comment by mwjames** [comment]
> [[Special:Ask/ ... query .../searchlabel=/default=no results/offset=0|]]

The code [0] that produces that particular output (which is format independent) hasn't been modified recently [1].

```
// Default output for normal printers:
if ( $outputMode !== SMW_OUTPUT_FILE && $results->getCount() == 0 ) {
	if ( !$results->hasFurtherResults() ) {
		return $this->escapeText( $this->mDefault, $outputMode )
			. $this->getErrorString( $results );
	} elseif ( $this->mInline ) {
		return $this->getFurtherResultsLink( $results, $outputMode )->getText( $outputMode, $this->mLinker )
			. $this->getErrorString( $results );
	}
}
```

If you modify `} elseif ( $this->mInline ) {` with `} elseif ( $this->linkFurtherResults( $results ) ) {` it should make the correct assumption about the `searchlabel` being present or not. 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commits/master/includes/queryprinters/ResultPrinter.php

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commits/master/includes/queryprinters/ResultPrinter.php

**Comment by mkroetzsch** [comment]
I have tried the above change. It changes the behaviour, but does not lead to the expected result either. Instead of the raw wikitext, the query then produces the default string (unlinked), as if there were no results. If the searchlabel is changed to non-empty, the same query then shows a further-results link (and there are results). So this does not seem to be the correct fix yet.

**Comment by mwjames** [comment]
> I have tried the above change. It changes the behaviour, but does not lead to the expected result either. 

I'm not really sure I understand this now. What exactly is expected for which use case?

**Comment by mkroetzsch** [comment]
I would expect that this behaves like any other query based on the individual parameters (limit=0 is not really a special case; it behaves like any other limit=n). The parameters should have the following effects:
* limit=n: the query shows at most n results
* searchlabel=: the query does not show a further-results link
* default=FOO: if ther query has no results, then it shows "FOO"
So a limit=0 query shows 0 results, whether there are results or not. However, if there are results, the searchlabel setting is relevant; if there are no results, the default setting is relevant.

I have now worked around the issue by using the following code in ResultPrinter.php in the place suggested above:
```
                        } elseif ( $this->mInline ) {
                                if ( $this->linkFurtherResults( $results ) ) {
                                        return $this->getFurtherResultsLink( $results, $outputMode )->getText( $outputMode, $this->mLinker )
                                                . $this->getErrorString( $results );
                                } else {
                                        return "";
                                }
                        }
```
I still think that the link-generating code should never create raw wiki text. It makes sense that result printers have an own way of switching the further-results link off (it could also be another special setting), yet the lower level should still recognize that links with empty anchor text don't work.

I remain puzzled as to why this problem surfaces in 2.1 but not in 2.0.

**Comment by mwjames** [comment]
> I remain puzzled as to why this problem surfaces in 2.1 but not in 2.0.

Yes, and I can't recollect any changes that would have forced a different behaviour because the only other places that can have an influence are  `SMWQueryResult` and `SMWQueryProcessor` but both have not seen any changes related to `FurtherResults`. I'd like to solve this (or at least want to know what changed), just to be sure you are using the `SQLStore`?

**Comment by mwjames** [comment]
Could you check if you find `skip result for {$row->t} existing cache entry / query` or `skip result for {$row->t} due to an internal {$row->iw} pointer / query` and compare the outputted hash with the query hash annotated on the page (internal prefixed with `_QUERY` + hash) that causes the issue.

**Comment by jongfeli** [comment]
Just tested the same query on my Wiki with SMW 1.9, 2.0 & 2.1_master. They all show the same result on the page:
```
[[Special:Ask/-5B-5BCategory:Test-5D-5D/-3FTest/searchlabel=/default=no-20results/offset=0|]]
```

**Comment by mkroetzsch** [comment]
@jongfeli Interesting. Indeed, the queries that I have used before did not specify an empty searchlabel at all. It is strange (and not really logical) that they still did not show further-results links. Maybe the only change that has happened after all was that I now found the need to set an empty searchlabel, which then showed a bug that existed for a long time.

@mwjames Yes, I am using SQLStore. No special configuration there.

> Could you check if you find ...

Where should I find this?

**Comment by mwjames** [comment]
> I remain puzzled as to why this problem surfaces in 2.1 but not in 2.0.

In order to prove that we are not talking about a regression, I found a MediaWiki 1.19.7 + Semantic MediaWiki (Version 1.8.0.5) with the following test data:

```
[[Has description::FurtherResultsLimitNull]]

== Foo::9999 ==
{{#ask: [[Foo::9999]]
 |default=no result
 |searchlabel=search
}}

{{#ask: [[Foo::9999]]
 |limit=0
 |default=no result
 |searchlabel=search
}}

{{#ask: [[Foo::9999]]
 |limit=0
 |default=no result
 |searchlabel=
}}

== Has description::+ ==
{{#ask: [[Has description::+]]
 |default=no result
 |searchlabel=search
}}

{{#ask: [[Has description::+]]
 |limit=0
 |default=no result
 |searchlabel=do search ...
}}

{{#ask: [[Has description::+]]
 |limit=0
 |default=no result
 |searchlabel=
}}
```
that will produce the following output:

![furtherresultslimitnull](https://cloud.githubusercontent.com/assets/1245473/6431559/876e7b62-c076-11e4-848e-aea220d1c007.png)

**Comment by mwjames** [comment]
2.2 https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/440018458114720c50e05d0a4e92f111045cba86

2.1.x https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/6b3ace5e589f328eb4a12a7d11d728b7a312998e
