### ISSUE TITLE
Improving Semantic MediaWiki

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#757]
- refs #128, #594, #586, #573, #568, #517, #264
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/labels/enhancement

**Comment by mwjames** [comment]
Comments found on the mailing list 

http://wikimedia.7.x6.nabble.com/SMW-Ontologies-td5042397.html

> Simon Heimler wrote Jan 24, 2015
> But you're right, SMW could improve it's profile here. 

Here are some ideas: 

   - Your IDE/Ontology developing approach makes definately sense to me. 
   It's a complex project and I wouldn't expect that too many people have the 
   need for full ontologies. But if the project manages to make setting up 
   your structure faster / more convenient and consistent, people will likely 
   use it. I agree that ontologies are powerful, but they are also somewhat 
   counter-intuitive at first contact. So having a good tool that helps 
   creating them is crucial. 
   - I've thought about having something like a "fact adder" additionally 
   to SemanticForms / Source Editor. It could be as easy as having two fields. 
   The first one autocompletes on all available attributes, the second one 
   takes the value (single or multiple) and basic validation. That feature 
   could fit in both with SemanticForms (producing a visible fact table) or 
   the VisualEditor (annotating text). 
   This would actively demonstrate the ability of SMW to handle very 
   flexible, unpredicted data, because of the RDF/Graph data structure behind. 
   - That said, graph-databases / structures gain popularity the last 
   years. SMW has that capability from start. Maybe it would be an good idea 
   to demonstrate and "advertise" that? 
   - I would say that the RDF data structure, it's open W3C standard and 
   good interoperability (linked-open-data, global knowledge graph) are the 
   main argument for SMW. Improving the Semantic Web capabilities (even only 
   under the hood) would be great here.

**Comment by Fannon** [comment]
Thanky for re-posting this!

Concerning idea 2: If that feature would be implemented, properties should be able to declare if they are "general" attributes that may be used that way. Some properties do only make sense in a very specific context.

That would make the ontology approach more interesting, too. You could use ontologies with a reasoner to check if the properties make sense in their context.
