### ISSUE TITLE
Missing interwiki encoding in RDF/SMWExporter

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#759]
Currently, the `SMWExporter` does not distinguish between `Foo` and `sb:Foo` and handles both as equal entities (where `sb` is defined as interwiki link) and is returning the same `rdf:resource` encoding  `...rdf:resource="http://example.org/id/Foo"/>` which is the reason why a query to the `SPARQLStore` (e.g `[[Some thing::Foo]]` and  `[[Some thing::sb:Foo]]`) returns the same subjects because of:
```
PREFIX wiki: <http://example.org/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <http://example.org/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?result WHERE {
?result swivt:wikiPageSortKey ?resultsk .
?result property:Some_thing wiki:Foo .
}
ORDER BY ASC(?resultsk) 
OFFSET 0
LIMIT 51
```

**Comment by mwjames** [comment]
Changes needed:
```
	static public function getEncodedPageName( DIWikiPage $diWikiPage ) {

		$localName = '';

		if ( $diWikiPage->getInterwiki() !== '' ) {
			$localName = $diWikiPage->getInterwiki() . ':';
		}

		if ( $diWikiPage->getNamespace() !== 0 ) {
			$localName .= str_replace( ' ', '_', $GLOBALS['wgContLang']->getNSText( $diWikiPage->getNamespace() ) ) . ':' . $diWikiPage->getDBkey();
		} else {
			$localName .= $diWikiPage->getDBkey();
		}

		return self::encodeURI( wfUrlencode( $localName ) );
	}
```

**Comment by JeroenDeDauw** [comment]
@mwjames you know you can do

\`\`\`php
le code
\`\`\`

instead of

\`\`\`\
le code
\`\`\`\

right?

**Comment by mwjames** [comment]
2.2 https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/af2eeb7c2a966863c599a63b3c893694581c4813

2.1.x https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/36f16d93366f9656fb7a851afb58adb2763f0eea
