### ISSUE TITLE
Using "." to add multiple properties per row in {{#subobject}} and {{#set}}

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#761]
Using templates (whether through SF or not) to frame an instance of {{#subobject}} or {{#set}} is currently possible if the format "a single property = value(s)" in a single row suits you, where the property is usually predefined in the template itself. There is, however, no room for use cases such as these: 

(1) Adding custom rows. Issue: the required use of a pipe as well as an equal sign cannot be reconciled with template usage. 

(2) Adding multiple properties per value. Problems: 
  (a) if multiple rows are used, there's no way to overcome the need of a pipe to delimit rows, as in (1) above; 
  (b) if a single row is used, the issue is that it doesn't allow for more than one property to be defined. 

While I'm afraid that pipes and equal signs will remain party poopers, I'm hoping that (2b) could be resolved. Per the use of "." to concatenate properties in a query, I'd like to request that "." will also be available as an operator so that properties can be delimited in a semantic annotation: 

{{#subobject:- 
|Property1.Property2.Property3=Value(s) 
}}
equalling: 
{{#subobject:-
|Property1=Value(s)
|Property2=Value(s)
|Property3=Value(s)
}}

and of course

{{#set: 
Property1.Property2.Property3=Value(s)
}}

**Comment by mwjames** [comment]
Preliminary note (without having read the whole issue)

I rather see not `.` misused as concatenation string for allowing to divide a string into separate properties where `.` represents a separator (as in the above context) and not a declaration of a property chain.

**Comment by Contrafibularity** [comment]
It just occurs to me that "::" might be more natural as a choice of separator than ".", seeing as something like [[Property1::Property2::Property3::value]] is already possible.

**Comment by s7eph4n** [comment]
+1 on what James said! Using the . will confuse everybody.

* Maybe {{!}} could be used to pass pipes into templates.
* [#arraymap] (http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Semantic_Forms_and_templates#arraymap) could be utilized to define any separator you like

**Comment by Contrafibularity** [comment]
From several earlier discussions it appeared that in the case of the pipes in {{#subobject}} or {{#set}}, {{!}} doesn't work as a substitute in a templated call. That's why "|+sep=" was introduced as a separator for values. I started this thread to suggest something equivalent for properties, but rather than having another add-on like "|+sep=", we could simply pick a character that is not normally tolerated in a property name. So "::" is the most logical choice I can think of at the moment.

**Comment by mwjames** [comment]
@Contrafibularity I saw (while not directly related tho this thread) you added subobject/category as limitation to the subobject topic on smw.org and while it can be seen as limitation, I'd like to clarify that a category and a property are two different entity types with the first representing a class of things (a category, set of) while the later is an attributive declaration about a thing.

There is a technical reason why both concepts should not be mixed and there is conceptional difference why both should not be mingled. While most users might not really care there are still different (maybe we should have page comparing both concepts or at least try to explain the difference; there are some notes somewhere on the mailing as to when to use a category or property). A subobject is a 2-ary about a thing (explaining a thing not a set of things) with a subobject linked to subject not a class (maybe [0] can help to shed some light on the topic).

[0] http://www.linkeddatatools.com/introducing-rdfs-owl

**Comment by Contrafibularity** [comment]
Yes, I did not want to push that particular example upfront, but yes, it's one of the use cases that were on my mind. 

Although it could have been made clearer, I did try to clarify on that page that the approach is an unusual move, a hack - if you will - from the traditional conceptual perspective, but that it opens up a possibility that can't be achieved otherwise, as things are now anyway (The two approaches shouldn't be mixed, of course, but they can coexist side by side and the system itself is relatively agnostic about the way an SMW end user ends up using it). I penned a fuller e-mail on this topic some time ago, but it met with little response. 

To clarify further. The underlying limitation that it tries to address, apart from the special case of 'categoryless/classless' subobjects, is lack of hierarchical inference on the side of the property's target value: while you can link up two entities through a property and even specify the relationship, such as "is subclass of" for class hierarchies and "is example of" for hierarchies of a different order, and then query on those relationships, SMW currently has no way to make inferences that dig through much deeper levels. 


Date: Tue, 27 Jan 2015 08:19:11 -0800

**Comment by mwjames** [comment]
> +1 on what James said! Using the . will confuse everybody.

> {{#subobject:-
|Property1.Property2.Property3=Value(s)
}}

> 'categoryless/classless' subobjects, is lack of hierarchical inference on the side of the property's target value: while you can link up two entities

There is a difference between inference at query time and a value assignment to a property which will always only happen to a distinct (concrete) value and property.

As for the issue topic, the `.` is reserved for a property path declaration and not to be used for something like "...to add multiple properties per row ...".
