### ISSUE TITLE
Start using DBAL connection

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#774]
Added in #771. Not used yet, and the correctness of the connection building for postgres has not been tested

**Comment by JeroenDeDauw** [comment]
#775 is a good candidate

**Comment by JeroenDeDauw** [comment]
When starting work on this, you probably want to re-add this code: #1212

**Comment by mwjames** [comment]
Some as #775, moving this to [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4
