### ISSUE TITLE
SQLStore / move SMWSQLStore3SetupHandlers::refreshData to its own class

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#778]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_SQLStore3_SetupHandlers.php#L307

refs #533

**Comment by mwjames** [comment]
From #766

> Is there a way to determine how many IDs there are to process before processing? Perhaps the script should print something like "Beginning processing of 13035 IDs" so you know if it ends at 3000 that something went wrong. Even better would be if it could catch that something caused it to end prematurely and it said "Aborting script at ID 3000 for unknown reason. Run with --debug for more info and file a bug at https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues if required"

**Comment by JeroenDeDauw** [comment]
Seems like a fun todo :)

**Comment by mwjames** [comment]
@jamesmontalvo3

> Is there a way to determine how many IDs there are to process before processing? 

That's gonna be difficult `SMWSQLStore3SetupHandlers::refreshData` is called recursively to avoid to read the whole `page` table (which can be really large) and even if you know "how many" real page id's you expect then you still have to calculate subobjects which count as extra and receive their own id (this is the reason why the id's not correlate with the id's from MW `page` table).

**Comment by mwjames** [comment]
>Is there a way to determine how many IDs there are to process before processing?

The `rebuildData.php` could now make use of either `ByIdDataRebuildDispatcher::getMaxId` or  `ByIdDataRebuildDispatcher::getProgress` to indicate the progress of the rebuild process.

**Comment by mwjames** [comment]
Done with afc1a7a.
