### ISSUE TITLE
SQLStore / Improve ConceptCache test coverage

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#779]
refs #777

> Obvious follow up work still needed to actually clean up the code, though this can be merged if it passes as far as I'm concerned.

**Comment by JeroenDeDauw** [comment]
Well, I already did the follow up work in that PR now...

**Comment by JeroenDeDauw** [comment]
I guess you can improve how the ConceptCache gets constructed and deprecate or remove the methods from SQLStore and QueryEngine. Though that is not specific to ConceptCache, and esp the construction stuff is a wider issue affecting different parts of the SQLStore.

**Comment by mwjames** [comment]
`ConceptCache` is not yet directly tested (indirectly thought the integration tests)

**Comment by JeroenDeDauw** [comment]
There is no new behavior. If there where unit tests for the store that called the old methods, you could refactor these as well to use the new class.

Obviously it'd still be good to add nice unit tests, to the extend this is possible. (Thinking about it, I suspect integration tests are more cost effective for this code in its current form.)

**Comment by JeroenDeDauw** [comment]
Do you want a ticket to track that?

**Comment by mwjames** [comment]
Yea, because [ConceptQueryDBIntegrationTest] (https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/ConceptQueryDBIntegrationTest.php) currently does not run for postgres (this is the only one as far as I remember).

**Comment by JeroenDeDauw** [comment]
"Improve ConceptCache" is not a good title or description for that though

**Comment by mwjames** [comment]
One issue is the missing temp table/column generation for `postgres` in `ConceptCache`:

```
php maintenance/rebuildConceptCache.php --create --debug

Notice: pg_send_query(): There are results on this connection. Call pg_get_result() until it returns FALSE in ...\includes\db\DatabasePostgres.php on line 490
```

```
Unexpected non-MediaWiki exception encountered, of type "RuntimeException"
[df84578f] [no req]   Exception from line 231 of ..\src\MediaWiki\Database.php: A database error has occurred. Did you forget to run maintenance/update.php after upgrading?  See
: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: INSERT INTO smw_concept_cache SELECT DISTINCT t0.s_id AS s_id, 54 AS o_id FROM "smw_fpt_mdat" AS t0 WHERE NO
T EXISTS (SELECT NULL FROM smw_concept_cache WHERE smw_concept_cache.s_id = t0.s_id  AND  smw_concept_cache.o_id =
t0.o_id ) LIMIT 10000
Function: SMW\SQLStore\QueryEngine\ConceptCache::refresh
Error: 42703 ERROR:  column t0.o_id does not exist
LINE 1: ...che.s_id = t0.s_id  AND  smw_concept_cache.o_id = t0.o_id ) ...
                                                             ^
```

**Comment by mwjames** [comment]
https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticMediaWiki/code-structure/master/class/SMW%5CSQLStore%5CConceptCache => Test coverage	91 %
