### ISSUE TITLE
QueryBuilder::getQueryContainer is broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#797]
Returns `SqlQueryPart` in one case and empty array in another. Some code expects an array and will fail on `SqlQueryPart` instance, and some code expects an `SqlQueryPart` and will fail on an array.

**Comment by mwjames** [comment]
Do we have test that fails where this can be observed?

**Comment by JeroenDeDauw** [comment]
Nope

**Comment by JeroenDeDauw** [comment]
Will split the method into two after this is merged #800

**Comment by JeroenDeDauw** [comment]
@mwjames the method might actually do what you wanted it to do, and not be broken in that sense. Returning a different type based on some optional parameter is definitely not good function design though.

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/802
