### ISSUE TITLE
Delimiting URLs

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#803]
Normally speaking, when I need to add multiple URLs as values to a property, I tend to use a space surrounded by nowiki tags as my delimiter. E.g. 

{{#arraymap:{{{URL|}}}|&lt;nowiki> &lt;/nowiki>|@@|[[URLtypeproperty::@@|link]]}}

Now when the same sep is used in a subobject, however, e.g.

{{#subobject:
|URLtypeproperty={{{URL|}}}|+sep=&lt;nowiki> &lt;/nowiki>
}}

the space is interpreted as %20 and the URLs are merged into one.

Any suggestions as to what delimiter we should be using here?

**Comment by Contrafibularity** [comment]
This solution works and does so by splitting the array using #arraymap, creating a new array from it and splitting the new arrray in turn using a custom delimiter:

{{#subobject:
|URLtypeproperty={{#arraymap:&lt;insert multiple, space-separated URLs here >|&lt;nowiki> &lt;/nowiki>|@@|@@|SOMETHINGYOUWOULDNOTEXPECTTOSEEINAURL}}|+sep=SOMETHINGYOUWOULDNOTEXPECTTOSEEINAURL
}}

P. S. By way of following up on this (in order to help out other SMW users), I should perhaps point out that in queries multiple URL values are normally separated by spaces rather than commas. Which is nice. In a query such as the following one, it allows us to format the values in a template by using #arraymap with nowiki tags. 

{{#ask: ...
|?URLtypeproperty
|?anotherproperty
|?yetanotherproperty
|format=template
|template=...
}}

**Comment by mwjames** [comment]
@kghbln @Contrafibularity Can this be closed and if necessary update the wiki (its been 1y+ now)?

**Comment by Contrafibularity** [comment]
Tip has been added to the smw site: see https://www.semantic-mediawiki.org/wiki/Help:Using_a_space_to_separate_multiple_values_in_set/subobject

You can close this topic as far as I'm concerned.
