### ISSUE TITLE
Concept dataitem export in RDF/SMWExporter

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#817]
refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/814#issuecomment-74350427

**Comment by JeroenDeDauw** [comment]
I do not understand what this issue is about, or how exactly we can close it

**Comment by mwjames** [comment]
> I do not understand what this issue is about, or how exactly we can close it

Just needs to be added, and this issue is for tracking the [0] TODO.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/export/SMW_Exporter.php#L696

**Comment by mwjames** [comment]
Fixed with #1450.
