### ISSUE TITLE
Potential issue with message registration

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#828]
https://gerrit.wikimedia.org/r/#/c/159493/1

Might also be an issue on master

@kghbln @s7eph4n @bd808

**Comment by mwjames** [comment]
Not sure why this going to be an issue but we do a plain registration upon loading [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.php#L121

**Comment by JeroenDeDauw** [comment]
Err... What about https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/Setup.php#L115 ?

Are we doing it twice? :)

**Comment by kghbln** [comment]
I probably cannot contribute in a fruitful manner in this case. I guess you are better experts when it comes to loading stuff from here to there.
