### ISSUE TITLE
Last execution time for "rebuildData.php" and "rebuildPropertyStatistics.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#832]
In case one does not control the server on which the cron is setup for these two scripts there is no easy way to determine if they have actually been run successfully. Thus it will be nice to have date and time information somewhere on the wiki, perhaps on "Sepecial:SMWAdmin" saying e.g. "Last time successfully run on February 19, 2015, 05:15 am".

We have this for "rebuildConceptCache.php" on the respective concept pages and this is really useful.

**Comment by mwjames** [comment]
OK this can be done failry easy all you need is something like:

- Add `'maintenance-script-execution` to the bottom of settings.php
```php
$GLOBALS['smwgLogEventTypes'] = array(
	'sqlstore-query-execution' => false,
	'maintenance-script-execution' => true
```
- Add a simple logger statement such as after `$maintenanceHelper->reset();`
```php
$store->getLogger()->logToTable(
	'maintenance-script-execution', // smw event type
	'smw-maintenance-runner', // user
	'rebuildData', // target
	'rebuildData.php execution' // message in the log
);
```
and `Special:Log` (or `index.php?title=Special:Log&type=smw`) should show a log entry together with time/date of the execution. If you want the content of the options to appear in the log entry than you have do a little do more work and extend the `rebuildData.php execution'` message string.

Maybe if you only want to log specific runs, add a `--with-log` option to the script.

That's all you need

**Comment by kghbln** [comment]
This turned into a disaster. However `smwgLogEventTypes` introduced with SMW 2.1 seems to have been removed in the meantime.

**Comment by mwjames** [comment]
> This turned into a disaster. However smwgLogEventTypes introduced with SMW 2.1 seems to have been removed in the meantime so this may have something to do with it.

I kept the main class [0] `ManualEntryLogger` but I wasn't happy with the `$store->getLogger()->logToTable` thing so I removed it for now since this wasn't really helpful.

The maintenance script need to do something like:

```php
use SMW\MediaWiki\ManualEntryLogger;

	public function execute() {
		...

		if ( $this->hasOption( 'with-log' ) ) {
			$manualEntryLogger = new ManualEntryLogger ();
			$manualEntryLogger->registerLoggableEventTypes( array( 'maintenance-script' ) );

			$manualEntryLogger->log( 'maintenance-script', 'UserX', 'rebuildData', 'Some nifty comment about ...' );
		}

```

PS: I haven't tested this, just wrote this off the top of my head while looking at [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/ManualEntryLogger.php

**Comment by kghbln** [comment]
> PS: I haven't tested this, just wrote this off the top of my head while looking at [0].

Tried this including also adding the global to settings and a  but I do not get the SMW-Log back. No PHP-issues though. Never mind for now. Let's just wait till logging is cool again.

**Comment by mwjames** [comment]
My bad it needs `registerLoggableEventTypes( array( 'maintenance-script' => true ) );`.

**Comment by kghbln** [comment]
Ah, this works, but we basically need all the other stuff back like 'Logger.php' etc. so we can have `            $manualEntryLogger->log( 'maintenance-script', 'Some nifty comment about ...' );`

**Comment by mwjames** [comment]
> Ah, this works, but we basically need all the other stuff back like 'NullLogger.php' etc. so we can have

#832 should do the trick.

**Comment by kghbln** [comment]
Hey, that's cool! Sorry that I was not able to get this in even with help.
