### ISSUE TITLE
Create a new Ask API interface

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#837]
Contact person: @JeroenDeDauw 

Create an Ask API that takes Ask query serializations, rather then the wikitext notation required by the current Ask API. Support for the [Ask library](https://github.com/wmde/Ask) needs to be implemented first (see #127).

**Comment by davidforgianni** [comment]
Maybe dupe/related: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/98

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
