### ISSUE TITLE
Refactor the SMWQueryProcessor

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#840]
Contact person: @JeroenDeDauw 

Refactor the SMWQueryProcessor to follow some OO design pattern. Right now it's a pile of static functions forming almost impressive spaghetti code. [independent]
- Get rid of all the static functions and fields - can use the singleton pattern here.
- Figure out which stuff is currently public while it should not be and make it protected.
- Some methods are passing unused (inc obsolete) stuff around, which we should get rid off.
- Some methods are passing around a lot of stuff, might be better to set stuff in an object.

**Comment by JeroenDeDauw** [comment]
@mwjames looks like we did not actually poke at this class much yet. Correct?

**Comment by mwjames** [comment]
> looks like we did not actually poke at this class much yet. Correct?

Yes, and this class needs attention is an F [0] offender.

[0] https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticMediaWiki/code-structure/master/class/%2Bglobal%5CSMWQueryProcessor

**Comment by JeroenDeDauw** [comment]
Not sure how we figured this was an easy standalone task. It definitely is not

**Comment by mwjames** [comment]
Superseded by #2737.
