### ISSUE TITLE
Context refactoring

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#842]
Contact : @JeroenDeDauw (Tracking request: [37445](https://bugzilla.wikimedia.org/show_bug.cgi?id=37445))

Many places in SMW currently pull in global state to do context dependent tasks. For instance wfLanguage, SMWOutputs::requireResource or $wgUser. We should use proper inversion of control here to inject the dependencies and make sure everything is nicely segregated so we only inject what is actually needed.

Relevant Articles:
- https://en.wikipedia.org/wiki/Interface_segregation_principle
- https://en.wikipedia.org/wiki/Dependency_inversion_principle
- https://semantic-mediawiki.org/wiki/User:Jeroen_De_Dauw/Static:_The_S_in_STUPID

**Comment by JeroenDeDauw** [comment]
@mwjames seems like you created the bug. An thoughts about the status of this? I do not find the issue very clear with its current phrasing

**Comment by mwjames** [comment]
> An thoughts about the status of this? I do not find the issue very clear with its current phrasing

By that time we hailed the MediaWiki God to be almighty but soon after it one was shaken from that dream and faced reality by encountering the truth "God is dead".

**Comment by mwjames** [comment]
The task would be to remove the `RequestContext` from the printer interface.

**Comment by JeroenDeDauw** [comment]
> by encountering the truth "God is dead"

![god-is-dead](https://cloud.githubusercontent.com/assets/146040/6316135/d6b374be-ba1a-11e4-86ce-4d2737c8b857.jpg)

It seems like we can create two general tracking issues instead:

* Stop using globals (in non entry point code)
* Stop using RequestContext / IContextSource / whatever
