### ISSUE TITLE
JavaScript base for dynamic result formats

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#843]
Contact person: @JeroenDeDauw

Add a small JavaScript base for interacting with the ask API that can be used by dynamic result formats to load additional data or re-load their data after page load.

**Comment by JeroenDeDauw** [comment]
@s7eph4n and @mwjames both did some work in this direction, though no one is currently working on this

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
