### ISSUE TITLE
Improve smwdoc

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#844]
Contact person: @JeroenDeDauw

The [#smwdoc](https://semantic-mediawiki.org/wiki/Smwdoc) parser hook allows for automatically documenting parameters supported by the [result formats](https://semantic-mediawiki.org/wiki/Help:Result_formats) using [Validator](https://semantic-mediawiki.org/wiki/Validator). Right now it just lists the name, type, default value and a small description. It could also list other info available, most notably the criteria, such as that it needs to be "one of these values" or "in the range of" or "be longer then x characters" or whatever. To not clutter the UI, this should be done in a way that it is not shown by default, but rather that the param info can be expanded (using some nice jQuery effects ofc :) when the user chooses to. This requires creating a separate display class for param info that just gets given a list of params, being completely SMW agnostic and places in the Validator extension (so it can be used by the #describe hook there as well) and then modifying #smwdoc to make use of this. [independent]

Other improvements that can be done to #smwdoc:
- introducing the possibilty to control the appearance of the smwdoc table, either by introducing a seperate class for these tables out of the box or by allowing to specify a seperate class.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
