### ISSUE TITLE
Inverse referencing in concepts

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#845]
Inverse referencing as described in [Help:Inverse_properties](https://semantic-mediawiki.org/wiki/Help:Inverse_properties) should also be possible for [Help:Concepts](https://semantic-mediawiki.org/wiki/Help:Concepts)! --[Rolze](https://semantic-mediawiki.org/wiki/User:Rolze) ([talk](https://semantic-mediawiki.org/w/index.php?title=User_talk:Rolze&action=edit&redlink=1)) 12:42, 18 September 2012 (CEST)

**Comment by JeroenDeDauw** [comment]
@mwjames you did not by any chance already implement this right?

**Comment by mwjames** [comment]
> you did not by any chance already implement this right?

No

**Comment by JeroenDeDauw** [comment]
You did not not already implement this? cool!

/me hides

![hide](https://cloud.githubusercontent.com/assets/146040/6316189/7b6ff7ea-ba1e-11e4-8d4d-6d41430aab4f.jpg)

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
