### ISSUE TITLE
Use Wikibase Database

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#846]
Contact person: @JeroenDeDauw

Replace the schema modification spaghetti code in the SQLStore with sane code using the [WikibaseDatabase library](https://github.com/wikimedia/mediawiki-extensions-WikibaseDatabase).

See also: [Wikibase QueryEngine](https://semantic-mediawiki.org/wiki/Wikibase_QueryEngine)

**Comment by JeroenDeDauw** [comment]
Current plan is to use Doctrine DBAL instead of Wikibase Database, as per #775
