### ISSUE TITLE
Semantic Drilldown

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#847]
Contact person: @yaronkoren 

Planned and desired future developments for [Semantic Drilldown](http://www.mediawiki.org/wiki/Extension:Semantic_Drilldown):
* the ability to drill down on [concepts](https://semantic-mediawiki.org/wiki/Concept), not just categories.
* fix the HTML and CSS of the Special:BrowseData page so that the last column doesn't get displaced by the list of categories. [independent]

**Comment by JeroenDeDauw** [comment]
@yaronkoren how would you like to track these things, assuming they are not already tracked? This is not the right place for them.

**Comment by yaronkoren** [comment]
@JeroenDeDauw I have no real need to track them; feel free to close this. (No offense, @davidforgianni - it seems like the rest of the stuff you're doing is great!)

**Comment by davidforgianni** [comment]
@yaronkoren lol i like to imagine that i am fairly tough to offend.  although some things do offend me,  like preventable human suffering. never been offended by a bug/in an issue tracking system though that i can recall. yet! that is not a challenge Sir!  :)

@JeroenDeDauw lemme know if you want me to file these in the separate/new items here (but the drilldown code hasn't been moved to git/no separate directory for it that i see) or maybe mention them somewhere around here: http://www.mediawiki.org/wiki/Extension:Semantic_Drilldown#Bugs_and_feature_requests ?  Are the existing items here https://old-bugzilla.wikimedia.org/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=SemanticDrilldown&product=MediaWiki%20extensions&query_format=advanced ported to Phabricator?  I didn't see them in a quick glance.

I guess i coulda summed all that damn typing up in: "Is the code repo for this extension going to be moved to github, or remain on https://git.wikimedia.org/tree/mediawiki%2Fextensions%2FSemanticDrilldown.git/HEAD/ ?"  Then we can go from there?  If code moving here we should copy open items from the deprecated bugzilla instance to github too, if code not moving here i'm not sure what y'all wanna do, but please let me know if I can help, thanks!

**Comment by yaronkoren** [comment]
That's good to hear. :) No, it's not moving here, so you don't have to do anything Semantic Drilldown-related.
