### ISSUE TITLE
Semantic Result Formats

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#849]
Contact person: @JeroenDeDauw or @yaronkoren 

Plans for some of the formats defined in [Semantic Result Formats](http://www.mediawiki.org/wiki/Extension:Semantic_Result_Formats)

* Exhibit rewrite
* 'outline' format - allow for the setting of a "sub-format" for each sub-grouping, using a new parameter perhaps called "innerformat=". [independent]
* 'outline' format - add support for a "template=" parameter, similar to the ones found in various other formats. [independent]
* 'ploticus' format - fix the security leak in this (currently-disabled) format. [independent]
* 'timeline/eventline' format - add support for a "template=" parameter. [independent]
* 'exhibit' format - there are various bugs in the Javascript that need to be fixed. [independent]

**Comment by JeroenDeDauw** [comment]
The individual points should be filed at https://github.com/SemanticMediaWiki/SemanticResultFormats

**Comment by davidforgianni** [comment]
I have moved all bullet point items to the correct area, closing.
