### ISSUE TITLE
Semantic Watchlist

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#852]
Contact person: @JeroenDeDauw and @yaronkoren 

Features that can be added:
* Watch single pages (via a watch tab) [independent]
* Diff coloring [independent]

**Comment by JeroenDeDauw** [comment]
Now at https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/54 and https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/55
