### ISSUE TITLE
MySQL logging warnings about unsafe statements

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMediaWiki#855]
I've recently been doing some analysis of my logs using Sumologic. I’m seeing a large number of warnings like this in my mysqld logs (from MariaDB):

> Feb 22 11:59:59 db mysqld: 150222 11:59:59 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. Statement is unsafe because it accesses a non-transactional table after accessing a transactional table within the same transaction. Statement: REPLACE /* SearchMySQL::update Bumble Bee */ INTO `searchindex` (si_page,si_title,si_text) VALUES ('61336','macmynowski maxmind',' maxmind subpage maxmind city pasadena region_name cau800 area_code 626u800 time_zone america los_angeles dma_code 803u800 metro_code losu800 angeles cau800 country_code3 usau800 latitude 33u800u82e7866 postal_code 91125 longitude -118u800u82e2987 country_code usu800 country_name united states continent nau800 ')

On WikiApiary I've got about 20,000 warnings like this in a 3 hour period. The pattern below represents 15,000 (3/4th) of the warnings:

> $DATE db mysqld: 150222 12:*** [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. Statement is unsafe because it accesses a non-transactional table after accessing a transactional table within the same transaction. Statement: REPLACE /* SearchMySQL::update Bumble Bee */ INTO `searchindex` (si_page,si_title,si_text) VALUES ('*','***',' * subpage***** ') 

It also highlights other *unsafe* SQL like this pattern:

> $DATE db mysqld: 150222 12:***** [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. INSERT IGNORE... SELECT is unsafe because the order in which rows are retrieved by the SELECT determines which (if any) rows are ignored. This order cannot be predicted and may differ on master and the slave. Statement: INSERT /* SMW::*****/ IGNORE INTO smw_*** (id) SELECT s_id FROM `smw_fpt_subc`, smw_*** WHERE o_id=id

It’s not an error, but wondering if this is something that would be good to change? Would it be useful if I inventoried these? Even if they are fine it sure would be nice to get rid of 6,000 log events an hour. Actually, now that I see this brought to my attention I see /var/log/syslog is hitting 150+ MB a day. :-\

**Comment by mwjames** [comment]
>  SearchMySQL::update Bumble Bee */ INTO `searchindex` (si_page,si_title,si_text)

The first/secod cited example is about MW's own `searchindex` table.

> SMW::*****/ IGNORE INTO smw_*** (id) SELECT s_id FROM `smw_fpt_subc`, smw_***

The third example is about SMW's  `smw_fpt_subc`, smw_*** tables.

Generally, I'm not sure what "unsafe SQL like this pattern:" means so some clarification from `Sumologic` would be good in what needs to be done to make them "safe".

**Comment by JeroenDeDauw** [comment]
Modified first post to quote the error so it's not a single unreadable line

**Comment by thingles** [comment]
> Generally, I'm not sure what "unsafe SQL like this pattern:" means so some clarification from Sumologic would be good in what needs to be done to make them "safe".

To clarify, Sumologic isn't determining these are unsafe, those messages are from MariaDB. Sumologic is just doing the pattern matching and aggregating of /var/log/syslog that highlights how crazy often these warnings are being output. This is all just MariaDB stuff. Not sure if MySQL would output the same warnings, but would be surprised if it didn’t.

**Comment by mwjames** [comment]
> This is all just MariaDB stuff. Not sure if MySQL would output the same warnings, but would be surprised if it didn’t.

[0] suggests to "Switching your binlog_format to MIXED should make the warning go away, since the server can switch modes at its discretion... and is very unlikely to have negative side effects. If it were not for the fact that STATEMENT has always been the default"

In case you want to know more about the message, I would suggest to open a bug with MediaWiki for the first two `searchindex` table issues and see what the MW developers have to say about it. 

[0] http://stackoverflow.com/questions/20925792/mysql-warning-code-1592-unsafe-statement-written-to-the-binary-log-using-stateme
[1] http://stackoverflow.com/questions/12274047/turnoff-mysql-unsafe-statement-warning
[2] https://www.drupal.org/node/1921864

**Comment by thingles** [comment]
Okay, for the Semantic MediaWiki query highlighted

> Feb 22 18:02:38 db mysqld: 150222 18:02:38 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. INSERT IGNORE... SELECT is unsafe because the order in which rows are retrieved by the SELECT determines which (if any) rows are ignored. This order cannot be predicted and may differ on master and the slave. Statement: INSERT /* SMW::executeHierarchyQuery 62.210.75.104 */ IGNORE INTO smw_res (id) SELECT s_id FROM `mw_ccbc_smw_fpt_subc`, smw_new WHERE o_id=id

Looking into the MySQL docs it appears this is a warning because replication mode is set to statement, and the master and slave could have different results from this SQL. I *think* this solution would be to add an ORDER BY on the SELECT. Alternatively MySQL admins suggest changing the replication format to row based, but that isn't the default.

**Comment by mwjames** [comment]
> SMW::executeHierarchyQuery 62.210.75.104 */ IGNORE INTO smw_res (id) SELECT s_id FROM mw_ccbc_smw_fpt_subc, smw_new WHERE o_id=id

This query relates to query execution.

> would be to add an ORDER BY on the SELECT

`ORDER BY`is only added for when a sort/order parameter is available for a query.

**Comment by mwjames** [comment]
> SMW::executeHierarchyQuery 62.210.75.104 */ IGNORE INTO smw_res (id) SELECT s_id FROM mw_ccbc_smw_fpt_subc, smw_new WHERE o_id=id

`smw_res`/ `smw_new` tables are coming from the `TempIdTableCreator` [0] which means those are created only during query execution and delete afterwards.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/4c7c05c74a65093be04618dcbfb84403aa4594e3/includes/storage/SQLStore/SMW_SQLStore3_Queries.php#L658

**Comment by thingles** [comment]
Alright, I think I’m just going to switch my `binlog_format` and say goodbye to these.
