### ISSUE TITLE
Email notification fails

### ISSUE THREAD

**Issue by BHBarb** [SemanticMediaWiki/SemanticMediaWiki#859]
WM/SMW system was working to email group members about pending approvals for a form. Client wanted to change terminology, using Word2 instead of Word1, in forms, templates, category added to, etc. Once I did that substitution, email notification stopped working. 

The entire system works as before (form uses template, template adds to category), but email is not notifying. 

There is a Notification Reports category which I can't find documentation for. This was created with the first system but isn't being created with the second. 

In WatchlistConditions, I changed the watch to the new category and ensured it was marked in my profile.
 
MediaWiki	1.23.5
Semantic Watchlist  1.0 alpha (485b0be) 16:30, September 10, 2014

**Comment by JeroenDeDauw** [comment]
Reported under the wrong component. You want this one: https://github.com/SemanticMediaWiki/SemanticWatchlist/issues

**Comment by BHBarb** [comment]
Thanks.
