### ISSUE TITLE
Error from one #set affecting other #set calls

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMediaWiki#870]
I've found a bug in how Semantic MediaWiki is handling errors in sets. I’m using the following wikitext:

```
This should be fine: [[Has database maintenance version::31]] <br/>
This should give an error: [[Has database maintenance version::33a]] <br/>
This should be fine: [[Has database maintenance version::32]] <br/>

This should be fine: {{#set: Has database maintenance version = 31}} <br/>
This should give an error: {{#set: Has database maintenance version = 33a}} <br/>
This should be fine: {{#set: Has database maintenance version = 32}} <br/>

This is a different property and should be fine: {{#set: Has database minor version = 32}} <br/>
```

The properties I’m using here are all of type number.

The first three work as expected, with the 2nd one giving an error because of the "a". The `#set` call generates an error where it should, but then the subsequent sets, including the one for an unrelated property, display the same error but should not.

Attached is a screen grab of the output.

![screenshot](https://cloud.githubusercontent.com/assets/5351/6498636/f1de4204-c2b3-11e4-9269-f4f579e667cc.jpg)

**Comment by thingles** [comment]
You can see this error live at https://wikiapiary.com/wiki/User:Thingles/Issue870.

**Comment by mwjames** [comment]
This is not a new issue (2.1/2.2) but is should be resolvable by changing the `SetParserFunction` class by moving the error display to be line specific (and not container specific):

```
+				$this->messageFormatter->addFromArray( $dataValue->getErrors() );
+
 				$this->addFieldsToTemplate(

 				...

 		$html = $this->templateRenderer->render() . $this->messageFormatter
-			->addFromArray( $this->parserData->getErrors() )
```
