### ISSUE TITLE
Enable pipe trick in {{#ask:}} printouts

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#875]
Original author: morgon.kanter
# Description:

My wiki uses a lot of suffixes in parenthesis, as well as ask queries, and it would be really nice to have a built-in way to perform the pipe trick ([[Link (blah)|]] becomes a link with text Link) on those links output by the ask query. Right now we use a pretty ugly template that gets the job done when you use the |template and |link=none parameters (see the URL), but it's a lot less optimal in terms of speed and readability than just having an option to do this straight in Semantic MediaWiki.

URL: http://dungeons.wikia.com/wiki/Template:Semantic_Link_Pipe_Trick

Reproduced from https://phabricator.wikimedia.org/T23546.
# My suggestion:
- add `pipe_trick` option to `{{#ask:}}` parser function to output wikilinks as `[[Page|]]`,
- add pipe_trick printout format to control printounts individually, e.g.: `?parent#-p`.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
