### ISSUE TITLE
Bad handling of non-binary collations

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#876]
When saving page properties (as well as doing anything else to the page), the page is identified by the title it was accessed in the URL with `?title=Muller&action=edit` not by the title the page is stored in the database. This title will also show up in the MW logs.

If database collation is not binary, a page can be accessed by more than one title, e.g. `?title=Müller&action=edit` and `?title=Muller&action=edit` will open the same page for editing with some collations.

These two facts together cause duplication of data in SMW store: there will be a triple for each title variant (_Müller_ and _Muller_) until semantic data is rebuilt. Each one will be output separately by `{{#ask:}}` queries.

The original bug report by vicente.aguilar is here: https://phabricator.wikimedia.org/T50706.

**Comment by JeroenDeDauw** [comment]
> ATM we're using MW 1.19.3, SMW 1.8.0.4 with CentOS 6.2 (PHP 5.3.3, MySQL 5.1.61).

**Comment by mwjames** [comment]
I tried to understand the problem but I was unable do so and create a **reproducible** use case that can be used as reference and without such reference it unlikely to see any activities now or in future on this ticket. If in future there is a description (clear and simple) and how to yield an observation, the ticket maybe used as reference but until then, it will be closed.
