### ISSUE TITLE
result format "template" / link to further results wrapped in "pre" tag

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#885]
When using the result format "template" the link to "further results" is wrapped into a "pre" tag. Changing  class="smw-template-furtherresults" does not help in this case. I think this is a SMW 1.9.x regression.

A public example for this is the [page on extensions at WikiAPIary](https://wikiapiary.com/wiki/Extension:Extensions)

**Comment by mwjames** [comment]
Using a query like:

```
{{#ask: [[Modification date::+]]
 |?Modification date 
 |limit=1
 |template=TryAskTemplateNesting
 |outrotemplate=SomeOutro
 |format=template
 |searchlabel=..see more
}}
```
I'm unable to confirm the `<pre>` tag for the normal vector skin.

![template-output](https://cloud.githubusercontent.com/assets/1245473/6643792/80bf955a-c9f2-11e4-9323-b969157b0f50.png)

**Comment by kghbln** [comment]
Actually I got this on a private wiki with Monobook. Was just happy to also see it on WikiApiary which of course uses Foreground. Dunno if it matters but I am on Firefox.

**Comment by mwjames** [comment]
> Actually I got this on a private wiki with Monobook. Was just happy to also see it on WikiApiary which of course uses Foreground. Dunno if it matters but I am using Firefox.

I need an example that actually creates the issue (because currently I'm unable to replicate the issue)!

**Comment by kghbln** [comment]
Ah, found one on [smw.o](https://semantic-mediawiki.org/wiki/Help:Template_format#Usage_for_userparam) using Vector

**Comment by mwjames** [comment]
> Ah, found one on smw.o using Vector. Edit: e.g. limit=3 is causing this. See here

Yes, that was an easy enough example for me to replicate the issue.

## Solution

How about you find `return $this->rowstart . ' ' .`in [0] and remove the `. ' ' ` part. (`' '` is an extra space that let's MW interpreting it as a `<pre>` tag parser requirement)

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/ListResultPrinter.php#L455

**Comment by kghbln** [comment]
Indeed, it was not the limit option. Applied you code change and it now works. However I accidently detected another on wiki ["fix" for this](https://semantic-mediawiki.org/w/index.php?title=Template:Query_output_demo&diff=prev&oldid=37872) which proves that it was a SMW 1.9.x regression.

Great! I am always very much impressed how fast you spot and fix such nasty things. :) Kudos!

**Comment by mwjames** [comment]
> Great! I am always very much impressed how fast you spot and fix such nasty things.

It is more that if I don't do it now it will be years before anyone else will have a look at this thread therefore having a simple example always helps to get the issue resolved rather quickly.

**Comment by kghbln** [comment]
:+1: which also proves that the better the report is the faster the issue gets fixed.
