### ISSUE TITLE
PHP Notice "Undefined offset" and "Invalid marker"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#894]
During a "rebuildData.php" run I suddenly got the following [notice](https://gist.github.com/kghbln/8ae0a09c37eba6ebee44). This just happened once after version e613314 rolled into the wiki. All preceding and subsequent runs were ok. There also was no edit activity on the wiki since the 5th of March which could have triggered this in another way.

**Comment by mwjames** [comment]
But this is coming from `FormatMetadata.php on line 1057`.

>PHP Notice:  Undefined offset: 0 in /.../includes/media/FormatMetadata.php on line 1057
[35635588] [no req]   Exception from line 77 of /.../includes/parser/StripState.php: Invalid marker: UNIQ069c85ad26d773a0-item-18--QINU
Backtrace:
#0 /.../includes/parser/StripState.php(66): StripState->addItem(string, string, string)

**Comment by mwjames** [comment]
You could try out https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/880#issuecomment-78348008?

**Comment by mwjames** [comment]
Also looking a bit further, I can see `Validator/src/legacy/ParserHook.php` is involved which seems similar to the reported https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/880#issuecomment-78049132.

```
PHP Notice:  Undefined offset: 0 in /.../includes/media/FormatMetadata.php on line 1057
[35635588] [no req]   Exception from line 77 of /.../includes/parser/StripState.php: Invalid marker: UNIQ069c85ad26d773a0-item-18--QINU
Backtrace:
#0 /.../includes/parser/StripState.php(66): StripState->addItem(string, string, string)
#1 /.../includes/parser/Parser.php(980): StripState->addGeneral(string, string)
#2 /.../extensions/Validator/src/legacy/ParserHook.php(302): Parser->insertStripItem(string, StripState)
#3 [internal function]: ParserHook->renderFunction(Parser, string, string)
#4 /.../extensions/Validator/src/legacy/ParserHook.php(336): call_user_func_array(array, array)
#5 /.../extensions/Validator/src/legacy/ParserHook.php(610): ParserHook->renderFunctionObj(Parser, PPFrame_DOM, array)
```

**Comment by kghbln** [comment]
I should have known better in identifying the source of this issue. Will hopefully give it a try this weekend. Thank you for digging into this and providing valuable information!

**Comment by kghbln** [comment]
As reality has it the code at this spot in MW 1.23 is different from the on in MW 1.24 and 1.25. So tough titties for the next two years. I am sorry to have wasted everyones time on this.
