### ISSUE TITLE
[Tracking ticket] Fix coding style issues

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#899]
We want our code to be compliant with our own coding style rules. Recently we created an automated way of detecting violations, making it trivial to get a list of violations. Most violations are very easy to fix.

To get a list of violations, first get a git clone of the repository. If you want to be able to contribute back, you probably first want to create a fork, and clone that.

```
git clone git@github.com:YourGitHubAccount/SemanticMediaWiki.git
```

Then change into the directory and run `composer install`

```
cd SemanticMediaWiki
composer install
```

If you do not have Composer installed yet, [first install it](http://getcomposer.org/).

Next install [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer) in whatever manner suits you best. For instance like this:

```
curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
```

Once that is done, you can get a list of violations by running the following in the root SMW directory:

```
php phpcs.phar src/* includes/* tests/* --standard=phpcs.xml --extensions=php -sp
```

The output will look as follows (though will have the above command instead of `compsoser cs-standalone`)

![Console output](https://cloud.githubusercontent.com/assets/146040/6734757/5459c4d8-ce5a-11e4-8562-28247706f5b3.png)

![Console output](https://cloud.githubusercontent.com/assets/146040/6734761/56fafa72-ce5a-11e4-93d3-762e9ebafa7e.png)

You do not need to actually install SMW itself. So you do not need a working MediaWiki installation, a database and a webserver. Even if you have an actual SMW install, it might still be easier to work with a dedicated development version for this task.

Once you fixed a violation or a set of related violations, create a commit, push it to your fork, and create a pull request.
### More advanced usage

If you create an actual working install of SMW, you can run `composer cs`, which will execute additional code style checks.

`composer cs` and `composer cs-standalone` only run style checks in the `src` directory. You can [look at how those commands are defined](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/composer.json#L80-L97) and easily see how you can run them for other directories, such as `includes` and `tests`. Example:

```
vendor/bin/phpcs includes/* --standard=phpcs.xml --extensions=php -sp
```

The tools used are [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer) and [PHPMD](http://phpmd.org/), both of which allow you to run a single rule at a time, rather than the whole ruleset we have defined. This is useful if you only want to fix a single category of issues, such as spacing issues, or want to ignore noise from another category.

**Comment by JeroenDeDauw** [comment]
@kghbln @mwjames I'm thinking of sending this to the list as another easy way to contribute. Do you think the instructions are clear enough? It does not explain how to install git, how to fork a repo and how to push things back to github, though perhaps the task is not suited for those that need to be brought up to speed with these steps?

**Comment by mwjames** [comment]
> I'm thinking of sending this to the list as another easy way to contribute

I'd say go for it.

> It does not explain how to install git, how to fork a repo and how to push things back to github, though perhaps the task is not suited for those that need to be brought up to speed with these steps?

Certainly true.

**Comment by kghbln** [comment]
+1 per @mwjames 

Probably I could even do some of this. :)

**Comment by hermannschwaerzlerUIBK** [comment]
I was looking through the output of phpcs yesterday and fixed those issues that were easy to fix.
Doing this I found some that are not fixable IMO:
* All `method parameter ... is never used` warnings for `src/SPARQLStore/QueryEngine/RawResultParser.php`:

 > 146 | WARNING | The method parameter $parser is never used
 > 156 | WARNING | The method parameter $parser is never used
 > 196 | WARNING | The method parameter $parser is never used
 > 196 | WARNING | The method parameter $elementTag is never used
 > 203 | WARNING | The method parameter $parser is never used
 
 All those functions are xml-parser callbacks and have to have that second parameter to be valid.

*  The errors regarding empty IF/ELSEIF statements in 
 * `src/SPARQLStore/QueryEngine/ConditionBuilder/ConjunctionConditionBuilder.php` (162)
 *  `src/SPARQLStore/QueryEngine/ConditionBuilder/DisjunctionConditionBuilder.php` (163)
 * `src/SPARQLStore/QueryEngine/QueryEngine.php` (278)
 * `src/SQLStore/QueryEngine/Compiler/SomePropertyCompiler.php` (211).

 Those contain a comment why they are intentionally left empty.

What's the best way to handle these noise generating parts?
Shall we put `// @codingStandardsIgnoreStart` - `// @codingStandardsIgnoreEnd` comments around them?

**Comment by JeroenDeDauw** [comment]
@hermannschwaerzlerUIBK I checked the if/elseif stuff, and all of those are indeed better left in the code for clarity.

I'm fine with adding `@codingStandardsIgnoreStart` tags, though for some categories such as unused parameters, it's probably better to just ignore them. We might want to exclude whole such rules then by default. Alternatively, you can run PHPCS with a single rule, and thus not be bothered by the noise of others.

**Comment by jongfeli** [comment]
In [includes/](https://github.com/jongfeli/Code-violations-SemanticMediaWiki/blob/master/includes.txt) there are a lot of **Generic.ControlStructures.InlineControlStructure.NotAllowed** violations like below in **[includes/datavalues/SMW_DV_Property.php]** line 91.
```php
	/**
	 * We use the internal wikipage object to store some of this objects data.
	 * Clone it to make sure that data can be modified independently from the
	 * original object's content.
	 */
	public function __clone() {
		if ( !is_null( $this->m_wikipage ) ) $this->m_wikipage = clone $this->m_wikipage;
	}
```

Is it fixed and ok if written like this:
```php
	/**
	 * We use the internal wikipage object to store some of this objects data.
	 * Clone it to make sure that data can be modified independently from the
	 * original object's content.
	 */
	public function __clone() {
		if ( !is_null( $this->m_wikipage ) ) {
			$this->m_wikipage = clone $this->m_wikipage;
		}
	}
```

Or like this:
```php
	/**
	 * We use the internal wikipage object to store some of this objects data.
	 * Clone it to make sure that data can be modified independently from the
	 * original object's content.
	 */
	public function __clone() {
		if ( !is_null( $this->m_wikipage ) ) {
			$this->m_wikipage = clone;
			$this->m_wikipage;
		}
	}
```

**Comment by joelkp** [comment]
It's the first of those two options.

**Comment by JeroenDeDauw** [comment]
Oh yeah, indeed the first one. If you have an `if` or `while` or `for` or whatever thing as follows

```php
if ( some condition ) do some stuff 
```

```php
while ( some condition ) do some stuff 
```

It should be changed to this format

```php
if ( some condition ) {
    do some stuff
}
```

**Comment by JeroenDeDauw** [comment]
I've updated the cs-standalone command to now include `includes/` and `tests/`. https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/956

**Comment by kghbln** [comment]
Added the next version milestone. I guess this can be moved forward as we advance with new releases.

**Comment by ckoerner** [comment]
I'm seeing a lot of these:
```
Each class must be in a namespace of at least one level (a top-level vendor name)
(PSR1.Classes.ClassDeclaration.MissingNamespace)
```
Is this something to ignore? I'm counting about 92 instances.

http://www.php-fig.org/psr/psr-1/#3.-namespace-and-class-names

**Comment by mwjames** [comment]
> Is this something to ignore? I'm counting about 92 instances. If not, I can take a swing at updating them.

Most classes in `includes` have not been converted to use a namespace and therefore are not following PSR-4/PSR-1 conventions.

**Comment by JeroenDeDauw** [comment]
Yes, this move is still in progress. See #716 for more info on what we are doing. You can also help with this, though it is somewhat more involved, especially if you do not have good tooling.

**Comment by kghbln** [comment]
A lot of improvements were done here thanks to numerous contributors. This can be done again once in a while.

This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
