### ISSUE TITLE
Extend sort/order options for query / queryresults

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#902]
This discussion came up more than once therefore this RFC is being created to reflect/describe use cases in connection with providing additional sort/order options for the `SQLStore` and `SPARQLStore`.

refs #874

> A better solution could be to introduce some further allowed values than just asc or desc for the order parameter. This would also fix the issue that SMW today is assuming some inherent "natural" order for properties, which is already problematic.

refs @krabina, http://wikimedia.7.x6.nabble.com/Sorting-results-tp5045768.html

> The problem is that if a property is of type page, SMW assumes that page name are alphabetical, and probably in 90% of the cases page names don't start with numbers. But there are cases, where I want numbers to be clickable...
> Could the order= parameter be enhanced to something like
> |order=numericasc
> |order=numericdesc
> to support numerical sorting of text/page-properties?
## See also
- http://www.copterlabs.com/blog/natural-sorting-in-mysql/
- http://stackoverflow.com/questions/153633/natural-sort-in-mysql/12257917#12257917

**Comment by alex-mashin** [comment]
# Improve ordering in semantic queries

Issues wth ordering results in `{{#ask:}}` queries have been reported: see https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/874 and http://wikimedia.7.x6.nabble.com/Sorting-results-td5045768.html. This draft for an RFC addresses them.

## Goals
To correct counter-intuitive behaviour of `{{#ask:}}` queries with `sort` parametres, which renders sorting features unusable on production sites without using hacks, namely:
* when `sort=Property` is provided, removing rows for pages where the sorting property is not set from the dataset as if filtering condition `[[Property::+]]` were set; in other words, filtering when asked only to sort,
* plain lexical sorting of pages and strings representing numbers, dates, years or days.

## Proposals
* No parametres for `{{#ask:}}` other than the first—the query conditions—should add or remove rows from the dataset (subject to `limit` parametre). In particular, if `sort=Property` parametre is given, pages where `Property` is not set should stay in the query result;
* A new parametre `sortas` is to be added, with possible values `text`, `number`, `date`. If there are several properties in the `sort=...` statement, a comma-separated list should be expected. The default values should depend on property type:
 * `text` (lexical) for Text and Page,
 * `number` (numeric) for Number and Quantity. Non-numeric suffix and possibly prefix should be dropped,
 * `date` for Date. The latter should sot correctily days without years (e.g. August 8th) and time of the day (e.g. 06:30 AM);
* A new parametre `sortnullsas` is to be added providing the value that the absent property values should be substituted for when sorting. If there are several properties in the `sort=...` statement, a comma-separated list should be expected. The default values for this parametre should depend on `sortas` and possibly on `order`:
 * a string that will be last in any likely list of strings for `sortas=string|order=asc` and an empty string for `sortas=string|order=desc`,
 * a huge number (+infinity) for `sortas=number|order=asc`, -infinity for `sortas=number|order=desc`,
 * a date infinitely far in the future for `sortas=date|order=asc`, the earliest possible date for `sortas=date|order=desc`.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.

**Comment by krabina** [comment]
I think a great enhancement of SMW 3.x will be entity specific collation support
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2429
