### ISSUE TITLE
 Database returned error "1114: The table 't6' is full (localhost)" / SMW 1.8.0.5

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#918]
Copied from [0]:

> We are using the older 1.8.0.5 version of SMW with MediaWiki 1.20.2, PHP 5.4.9, MySQL 5.5.28. Everything has been working great so far and we are well over 106,000 pages in our system after over 2 years or use in production. Recently we encountered the following database error when running jobs. It seems to occur only a specific type of page invoking a specific template.

> A database query syntax error has occurred. The last attempted database query was: "INSERT IGNORE INTO `t6` SELECT t7.smw_id FROM `smw_object_ids` AS t7 WHERE t7.smw_sortkey LIKE 'CID%'" from within function "SMW::executeQueries". Database returned error "1114: The table 't6' is full (localhost)"

> Is this related to some default MySQL setting for SMW? We currently have just over 16GB RAM used for MySQL caching and buffers. We have plenty of hard disk space. I'm wondering if there is some simple MySQL setting we need to change to increase teh table size. Any help here would appreciated 

[0] https://semantic-mediawiki.org/w/index.php?title=semantic-mediawiki.org:Community_portal&offset=20150324132918&lqt_mustshow=1694#SMW_database_error_1694

**Comment by mwjames** [comment]
Why would a temporary table (t6) return with " Database returned error "1114: The table 't6' is full (localhost)"?

@JeroenDeDauw @mkroetzsch Are there any settings known that influence the behaviour of temporary tables that would return such error? Could that be a memory issue?

**Comment by mkroetzsch** [comment]
Never seen the error. There are MySQL configuration options for maximum table size, at least for InnoDB. See, e.g., http://stackoverflow.com/questions/730579/error-1114-hy000-the-table-is-full

OP should report if any of this has helped and also give some details about his/her MySQL configuration (and MediaWiki configuration as far as it affects MySQL).

**Comment by mwjames** [comment]
@mkroetzsch Thanks for the insight

Since the original author did not respond on whether the issue is solved or not, I'm inclined closing this issue. If the original author/user has more input on this topic, s(he) is free to re-open this thread again.

**Comment by Basil-L** [comment]
I had the same problem:
  „1114: The table 't4' is full (localhost)“.

I added these two lines to /etc/mysql/my.cnf
  tmp_table_size=256M
  max_heap_table_size=256M
restarted mysql and the problem was gone.

**Comment by mwjames** [comment]
I'm not sure how often this happens but we go with the general advise of increase the "tmp_table_size".
