### ISSUE TITLE
Gitter ?

### ISSUE THREAD

**Issue by Fannon** [SemanticMediaWiki/SemanticMediaWiki#919]
Gitter (https://gitter.im/) seems to get a lot of traction these days and I can really see why. It's in many ways more modern and better fitted for software projects (you can use github flavoured markdown, including syntax highligting, excellent GitHub integration, etc.) than IRC.

Not sure if this is a good idea, since IRC may be old but still kicking after all that time.

Best,
Simon

**Comment by JeroenDeDauw** [comment]
What problem would this tackle and which people would it serve?

**Comment by Fannon** [comment]
As I've written, I'm not sure if it's something for the SMW community. Just noticed that the IRC channel seems not to be used much. 

Since Gitter is "new in town", i just wanted to point out that it may be an alternative.

**Comment by JeroenDeDauw** [comment]
We're not using IRC for dev coordination, which is what makes me wonder why using something else instead of IRC would be of use.

**Comment by kghbln** [comment]
I do not think that Glitter will increase participation, in contrary. Currently it will just introduce another extra channel of communication and thus even decrease participation. The people on IRC are the ones who also participate in the MW one. As long as they do not switch ... 

Besides I think it is utterly great that you think about how to put more momentum to SMW. Much appreciated!
