### ISSUE TITLE
format "list" / PHP Notice:  Undefined variable: outputMode

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#946]
When running `rebuildData.php` I got the following notice:

``` text
PHP Notice:  Undefined variable: outputMode in /.../common/extensions/SemanticMediaWiki/includes/queryprinters/ListResultPrinter.php on line 176
```
PHP 5.4.36, MW 1.23.8, SMW 2.1.2

**Comment by mwjames** [comment]
What a f ... this happens when you apply coding style changes `$outputmode` vs `$outputMode`, so instead of `trim( $this->getFurtherResultsText( $queryResult, $outputMode ) );` in 2.1 it needs `trim( $this->getFurtherResultsText( $queryResult, $outputmode ) );`

**Comment by mwjames** [comment]
075e532e4c

Need to make a 2.1.3, this really ticks me off ...

**Comment by mwjames** [comment]
@kghbln Don't know how you want to play this but since it is a regression I just make the tag and people get 2.1.3 when running `composer update`.

Ahhhhhhhhhh ....

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases/tag/2.1.3

**Comment by mwjames** [comment]
@kghbln Maybe if you feel up to it you could write a similar a test case (as json script such as [0]) in 2.2 so that at least other options of the list printer are tested from this point forward.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/Fixtures/format-table-boolean-query-001.json

**Comment by kghbln** [comment]
Do not worry too much about this. Some days are just not meat to be good. That's part of life I guess. We should not probably advertise offensively for this release but I need to update on wiki as well as on SourceForge.

Yeah, it will be nice if I could write this test. Stay tuned.
