### ISSUE TITLE
Fix excessive complexity in SetupTest

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#954]
```
+
+FILE: ...i-1.24.1/extensions/SemanticMediaWiki/tests/phpunit/includes/SetupTest.php
+--------------------------------------------------------------------------------
+FOUND 1 ERROR AFFECTING 1 LINE
+--------------------------------------------------------------------------------
+ 156 | ERROR | Function's cyclomatic complexity (26) exceeds allowed maximum of
+ | | 10 (Generic.Metrics.CyclomaticComplexity.MaxExceeded)
+--------------------------------------------------------------------------------
```

> Yeah but some of stuff actually needs to be moved to the HookRegistry test but I never came to it. It is no longer part of Setup class but it didn't bothered me because the test still runs without me having to re-write part of it. -- @mwjames

**Comment by mwjames** [comment]
C	↗	A	SetupTest improved [0], refs #1118

[0] https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticMediaWiki/inspections/9be12e6c-2dab-427e-8be4-7d398a8bfc57
