### ISSUE TITLE
Travis running tests parallel

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#96]
Composer and Symphony running tests parallel on Travis using something like:
```
before_script:
    - sudo apt-get install parallel
```

```
script:
    - ls -d src/Symfony/*/* | parallel --gnu --keep-order 'echo "Running {} tests"; phpunit --exclude-group tty,benchmark {};' || exit 1
    - echo "Running tests requiring tty"; phpunit --group tty
```
https://github.com/symfony/symfony/blob/master/.travis.yml

https://github.com/composer/composer/commit/38917c204758f1dd97569af299b3b87b3d0d2c10#diff-50f49bafa5c7a00b65ee37ec8d0490ff

Might be useful for SMW as well.

**Comment by JeroenDeDauw** [comment]
Does that actually make a real difference on Travis?

**Comment by mwjames** [comment]
> Does that actually make a real difference on Travis?

Not really (as single test run takes on average about 2 min. max) but what would help is to have the coverage test ( `TYPE=coverage` which can  take up to 18 min) run by `HHVM` (~ 2.5 min.) but there is an unresolved `phar` issue  [0, 1, 2].

[0] https://github.com/facebook/hhvm/issues/4263
[1] https://github.com/scrutinizer-ci/ocular/issues/10
[2] 

> When uploading code coverage via php ocular.phar from HipHop VM 3.3.0 (rel) it returns with "Fatal error: Uncaught exception 'PharException' with message 'Corrupt phar, can't read 4 bytes starting at offset 1663508419'"
Details can be found at the bottom of [0].
[0] 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/37985062/log.txt

> This is a known bug for HHVM with phar archives. You can work around this by using the scrutinizer/ocular package as part of your dev dependencies instead of the ocular.phar archive.
Best,
Johannes
