### ISSUE TITLE
Fix HHVM 3.7-dev / Class Mock_DatabaseBase_10433b17 contains abstract method (getType)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#960]
```
Starting test 'SMW\Tests\MediaWiki\DatabaseTest::testCanConstruct'.
.
Starting test 'SMW\Tests\MediaWiki\DatabaseTest::testNumRowsMethod'.
Fatal error: Class Mock_DatabaseBase_10433b17 contains abstract method (getType) and must therefore be declared abstract or implement the remaining methods in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(301) : eval()'d code on line 1
```

Only HHVM 3.7-dev detects [0] the issue, HHVM 3.5 is fine. Someone from MW changed the interface on master [1, 2].

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/57027146
[1] https://github.com/wikimedia/mediawiki/blob/master/includes/db/Database.php#L599
[2] https://github.com/wikimedia/mediawiki/blob/REL1_24/includes/db/Database.php#L41

**Comment by JeroenDeDauw** [comment]
https://github.com/wikimedia/mediawiki/commit/a13b950a40f9ea54d6537e2359c2ac9db745e495

**Comment by mwjames** [comment]
This issue no longer appears on the HHVM/master.

https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/67270240
