### ISSUE TITLE
https / semantic-mediawiki.org /  OCSP server has no status for the certificate

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#967]
When trying to access `https://semantic-mediawiki.org/` via `https` it shows:

```
Secure Connection Failed

An error occurred during a connection to semantic-mediawiki.org.
The OCSP server has no status for the certificate.
(Error code: sec_error_ocsp_unknown_cert)
```

@mkroetzsch @kghbln

**Comment by kghbln** [comment]
If I am not mistaken the message suggest that a new certificate installed which is not yet known to the OCSP server. Since this it not the case I suspect a issue with the OCSP server of StartSSL. I am currently getting no error though I use Firefox and even have OCSP checks enabled (thought I disabled this).

**Comment by mwjames** [comment]
I still get

![smw-org-issue](https://cloud.githubusercontent.com/assets/1245473/6996218/5d2b7a36-db69-11e4-9dcc-6c38d70f2c33.png)

**Comment by kghbln** [comment]
That's really strange. No worries at my end. If you disable OCSP checking in your browser it should go away.

**Comment by JeroenDeDauw** [comment]
I'm always using the HTTPS and am not getting it. Not in FireFox and not in Chromium. I don't have any fancy settings though

**Comment by kghbln** [comment]
Chromium does not longer check for this and one explicitly has to enable it in Firefox. That's why I wondered that it was enabled at my end. Must have fiddled with it some time in the past. O_o

**Comment by mwjames** [comment]
> If you disable OCSP checking in your browser it should go away.

Okay then I deactivated the setting (under the assumption that this is an oversight) and in case someone else runs into the issue the option can be found here.

![smw-ocsp](https://cloud.githubusercontent.com/assets/1245473/6996294/63ce61cc-db6f-11e4-9243-b7b162d94dbe.png)
