### ISSUE TITLE
Template named args to require '?' as prefix

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#972]
Having read [0] with "This behavior seems odd to me because it prevents SMW from using templates that are also meant for normal use by users without modifying those templates to accept alternative parameters with question marks ...", I was wondering about the reason as to why `?` is required.

The line that makes it a requirement can be seen here  (`$fieldName = '?' . $field->getPrintRequest()->getLabel();`)  [1] but no obvious technical reason can be cited to make this a hard requirement. @kghbln Any idea why `?` was required when this feature was added?

Using `Template:ListOutput` manually
```
{{ListOutput
 |TemplateListOutput-1=Foo
 |TemplateListOutput-2=bar
}}
```
should be no different as in using it for/by
```
{{#ask: [[TemplateListOutput-1::+]]
 |?TemplateListOutput-1
 |?TemplateListOutput-2
 |template=ListOutput
 |format=template
 |named args=yes
 |sep=;
}}
```

[0] 	https://semantic-mediawiki.org/wiki/Thread:Help_talk:Template_format/Clarifying_something_with_named_args

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/ListResultPrinter.php#L408

**Comment by kghbln** [comment]
I cannot tell but the requirement for this"?" appears pretty noticeable. So I think there was at least at that time a good reason for doing so. I guess that either @mkroetzsch or @JeroenDeDauw added this to SMW so one of them may have an info on this.

**Comment by mwjames** [comment]
> I cannot tell but the requirement for this"?" appears pretty noticeable.

Well, I don't know why therefore the usage of named args for the category printer #974 is done without `?` which may seem counterintuitive to the user (in comparison to named args in template output) but I see no reason to continue something that has no merit or a clear technical specification.

**Comment by kghbln** [comment]
> I see no reason to continue something that has no merit or a clear technical specification.

Neither do I. I just figured to have some information about the rationale back then may be interesting.

**Comment by mkroetzsch** [comment]
The ? is to distinguish print requests from ask parameters. Without it, it would be impossible to parse ask parser function calls unambiguously. The choice of ? (as opposed to some other symbol or syntactic change) was motivated by its intuitive appeal, since printouts are part of what you are asking for.

**Comment by mkroetzsch** [comment]
Ah, now I see that this is about the parameter names passed to a template, not about the ask syntax? I guess we agree that printout requests must always start with ? in ask, and that this should not change just because you use a special format with a certain parameter. What I don't understand is why the ? is included in the parameter name when calling the template. This seems strange. I have not been involved in designing this.

**Comment by kghbln** [comment]
> I guess we agree that printout requests must always start with ? in ask, and that this should not change just because you use a special format with a certain parameter. 

Yeah, I believe that we are indeed very cool about this. :)

> What I don't understand is why the ? is included in the parameter name when calling the template.

Right, so the next best shot seems to be @JeroenDeDauw Anyway it is gone since https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/974 addresses this. So if we cannot figure this out ...

**Comment by mwjames** [comment]
> Ah, now I see that this is about the parameter names passed to a template, not about the ask syntax? 

Yes

> I guess we agree that printout requests must always start with ? in ask, and that this should not change just because you use a special format with a certain parameter.

Yes

> What I don't understand is why the ? is included in the parameter name when calling the template. This seems strange. 

I only came to it due to the inquiry of [0] and by looking at the code the intention wasn't clear nor the merit since using `?` prevents one from reusing templates (made for humans) while `#ask` templates require an explicit `?` notation parameter.

> Anyway it is gone since #974 addresses this. So if we cannot figure this out ...

I didn't change the existing implementation for the `TemplateResultPrinter`. The usage in the `CategoryResultPrinter` (as added 2.2 feature) does not require the `?` as prefix for a template parameter when using `named args`.

[0] https://semantic-mediawiki.org/wiki/Thread:Help_talk:Template_format/Clarifying_something_with_named_args

**Comment by JeroenDeDauw** [comment]
I'm not entirely sure I get what this issue is about. Can someone post an example of the current (weird) format and the (seemingly better) proposed one?

Also, it this about something that was always the case, or about a (now already quite old) regression?

**Comment by mwjames** [comment]
> Can someone post an example of the current (weird) format and the (seemingly better) proposed one?

Information are as above.

> Also, it this about something that was always the case, or about a (now already quite old) regression?

It just something that doesn't make sense, that's all.

**Comment by mwjames** [comment]
I'm will change this in 2.3 to be used either way but for 2.3 only and kill the `?` usage starting 2.4 for named args when using a template in connection with a `#ask` output.

**Comment by mwjames** [comment]
Since the question has been answered (with the result that no one knows why `?` prefix was introduced for named args in templates), I'm closing this one.

Thanks everyone for the vivid participation.

**Comment by JeroenDeDauw** [comment]
> and kill the ? usage starting 2.4 for named args

That's a breaking change no? If I'm understanding this correctly, we cannot do this in a minor release, only in a major one. I suggest deprecation and then creating a ticket for removal in 3.0, assuming the removal is not too disruptive compared to the cost of having it.

**Comment by mkroetzsch** [comment]
One could deprecate "named args=yes" (but leave it in) and add another option that leads to the desired behaviour. For example, option "template arguments" with possible values "named" and "numbered" (default).
