### ISSUE TITLE
Ask API supporting count, min, max, average, etc.

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMediaWiki#98]
I filed this [issue 46458 in Bugzilla](https://bugzilla.wikimedia.org/show_bug.cgi?id=46458) about trying to count results in the Semantic MediaWiki Ask API. I'll admit at the time I was still learning more and more about Semantic MediaWiki and I think I now _get_ the answer that @mwjames provided better now. It was also awesome that @mwjames added SMWInfo fields to get the data I was looking for at the time.

I would like to throw out though that the non-visual, data-centric formats being accessible in the API would be a really nice win. While working on WikiApiary I routinely want to ask for the count of certain things in Semantic MediaWiki but you cannot. Ideally something like:

```
https://wikiapiary.com/w/api.php?action=ask&query=[[Category:Website]][[Is%20active::True]]|format=count&format=json
```

would return the count. Other non-display formats like min, max, average, sum, earliest, latest could all be very useful via API. Obviously things like table and list make no sense, which is the reason format isn't supported in the API. To some extent the challenge here is mixing data actions (count, min, max) with visual output (table, list).

Is this something that is being considered at some point?

**FWIW:** Calling the URL example given above with the format in it still generates an exception.

PHP message: PHP Catchable fatal error:  Argument 1 passed to SMW\Api\Query::addQueryResult() must be an instance of SMWQueryResult, string given, called in /.../SemanticMediaWiki/includes/api/Ask.php on line 38 and defined in /.../SemanticMediaWiki/includes/api/Query.php on line 67

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed on moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
