### ISSUE TITLE
SMW to turn 10

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#992]
According to [0] the first official release of SMW was stamped with `2005-09-30` which would make it equivalent to be its birthday.

I'm not sure this requires some special attention such as:
- SMW can be order in 10 years anniversary box 
- Someone wants to sponsor a special feature not yet implemented in SMW
- Good timing to actual force a relaunch of the smw.org homepage
-  etc.

@s7eph4n @mkroetzsch @kghbln @JeroenDeDauw @SemanticMediaWiki/testers @hexmode  @krabina You are invited to make suggestions or throw in some ideas on whether this is something to commemorate or not and if so how to emphasize the being "10". 

[0] http://sourceforge.net/projects/semediawiki/files/semediawiki/

**Comment by ckoerner** [comment]
If others think it's appropriate, I'd love to do something at the upcoming SMWCon. Maybe a retrospective discussion on how SMW came to be, how it's grown up over the years, and what's next?
